// Content for The Amazing Journey (node g14, ages 9–12, Chapter 3) — NEW v2 build to GDD 14 (mechanic-
// embodying), the reproduction node (Thread F · Sexual & Reproductive Health). "How life begins, the real
// story." 84 researched, India-aware scenarios across six categories, each encoded as one of the shared v2
// play actions (reflect / strike-rewrite / branch / match / sort / build / role-play) — no binary "tap the
// right card", led by **awe + facts** (reflect ×28), **myth-busts** (strike-rewrite ×20), and the
// **journey-builder** (build, sequence: egg+sperm → grow → born). Teaches, accurately and inclusively: how
// life begins (egg + sperm join), pregnancy (a baby grows in the uterus ~9 months), being born (vaginal or
// C-section, both normal), the MANY ways families have children (birth, adoption, IVF, surrogacy — all real &
// loved), and busting the baby-myths (storks, swimming pools, kissing, and the harmful India belief that a
// baby's sex is the mother's 'fault' — it comes from the sperm, and daughters are equally valued). ACCURATE &
// INCLUSIVE (proper terms; intercourse referenced simply & briefly; every family form real & loved);
// PRIVATE/SOLO; NEVER GRAPHIC, never clinical, never giggly; scope-disciplined (contraception/STIs/consent
// live in later nodes); routes to trusted sources. Builds on g06 (anatomy) & g13 (puberty); prereq g38;
// family-diversity links g03 (My Family Garden). Rendered by the shared engine (components/games/v2-engine.tsx).
// gameId "amazing-journey" (the GDD/library "the-amazing-journey" is design-doc only — config must use the
// engine-host registry id). DO NOT RENAME.

import type { Scenario, V2GameConfig } from "./v2-schema";

const SCENARIOS: Scenario[] = [
  // — How life begins (egg + sperm) —
  {"id":"aj-001","cat":"spark-of-life","type":"build","hook":"Lensy: every person started as an amazing journey. Put the first steps in order.","prompt":"Order how a baby begins.","pieces":["an egg cell and a sperm cell","they join together (fertilisation)","one tiny new cell forms","it starts to grow"],"mode":"sequence","key":["an egg cell and a sperm cell","they join together (fertilisation)","one tiny new cell forms","it starts to grow"],"relearn":"A baby begins when an egg cell and a sperm cell join into one tiny new cell.","persona":"any","source":"reproduction basics"},
  {"id":"aj-002","cat":"spark-of-life","type":"match","hook":"Match the cell to where it comes from.","pairs":[{"left":"Egg cell","right":"From a woman's ovaries"},{"left":"Sperm cell","right":"From a man's testes"},{"left":"The two joining","right":"The start of a baby"}],"relearn":"An egg (from a woman) and a sperm (from a man) can join to start a baby.","persona":"any","source":"reproduction basics"},
  {"id":"aj-003","cat":"spark-of-life","type":"strike-rewrite","hook":"\"Babies just appear out of nowhere.\"","myth":{"un":"Babies appear out of nowhere (or a stork brings them).","re":"A baby begins when an egg and sperm cell join, that's the real start.","why":"It's biology, the same for all living things."},"relearn":"A baby begins from an egg and a sperm cell, not a stork.","persona":"any","source":"reproduction basics"},
  {"id":"aj-004","cat":"spark-of-life","type":"reflect","hook":"Lensy: every living thing reproduces, plants, animals, people. Amazing?","prompt":"What do you think?","options":["Yes, amazing","Cool science","Life makes life"],"affirm":"All living things make new life; you're part of that amazing chain.","relearn":"Reproduction is how all living things make new life.","persona":"any","source":"reproduction basics"},
  {"id":"aj-005","cat":"spark-of-life","type":"strike-rewrite","hook":"\"Talking about how babies are made is dirty or wrong.\"","myth":{"un":"Learning how babies are made is dirty or wrong.","re":"It's natural science everyone deserves to understand.","why":"Knowing the facts is healthy, not shameful."},"relearn":"How babies are made is natural science, nothing to be ashamed of.","persona":"Diya","source":"normalisation"},
  {"id":"aj-006","cat":"spark-of-life","type":"reflect","hook":"Lensy (matter-of-fact): usually an egg and sperm meet when two adults have sex, and sometimes with a doctor's help. Clear enough for now?","prompt":"What do you think?","options":["Yes, clear","Good to know","Makes sense"],"affirm":"That's the simple, honest version, you can always learn more when you're ready.","relearn":"Egg and sperm usually meet through sex between adults, or with a doctor's help.","persona":"Aarav","source":"reproduction basics"},
  {"id":"aj-007","cat":"spark-of-life","type":"sort","hook":"Sort: needed to start a baby, or a myth?","items":[{"id":"a","text":"An egg cell"},{"id":"b","text":"A sperm cell"},{"id":"c","text":"A wish on a star"},{"id":"d","text":"Eating a special fruit"}],"bins":[{"id":"real","label":"Really needed"},{"id":"myth","label":"Myth"}],"key":{"a":"real","b":"real","c":"myth","d":"myth"},"relearn":"It takes an egg and a sperm, not wishes or special foods.","persona":"any","source":"reproduction basics"},
  {"id":"aj-008","cat":"spark-of-life","type":"match","hook":"Match the word to its simple meaning.","pairs":[{"left":"Fertilisation","right":"Egg and sperm joining"},{"left":"Uterus","right":"Where a baby grows"},{"left":"Cell","right":"The tiny building block of life"}],"relearn":"Fertilisation is egg+sperm joining; the uterus is where the baby grows.","persona":"any","source":"reproduction vocabulary"},
  {"id":"aj-009","cat":"spark-of-life","type":"reflect","hook":"Lensy: it took an incredible bit of biology to make YOU. Feel a bit awed?","prompt":"What do you think?","options":["Yes","I'm a miracle of biology","Pretty cool"],"affirm":"You really are an amazing result of an amazing process.","relearn":"You began from one tiny joined cell, that's amazing.","persona":"any","source":"wonder"},
  // — Growing a baby (pregnancy) —
  {"id":"aj-010","cat":"growing-a-baby","type":"build","hook":"The baby grows! Put the pregnancy stages roughly in order.","prompt":"Order the growing journey.","pieces":["one cell becomes many","a tiny embryo forms","it grows in the uterus","becomes a baby ready to be born"],"mode":"sequence","key":["one cell becomes many","a tiny embryo forms","it grows in the uterus","becomes a baby ready to be born"],"relearn":"From one cell, a baby slowly grows in the uterus over months.","persona":"any","source":"pregnancy basics"},
  {"id":"aj-011","cat":"growing-a-baby","type":"reflect","hook":"Lensy: a baby grows in the uterus for about nine months. Long journey?","prompt":"What do you think?","options":["Yes, nine months!","Slow and amazing","Worth the wait"],"affirm":"Nine months of growing, the longest, most amazing journey there is.","relearn":"A baby grows in the uterus for about nine months.","persona":"any","source":"pregnancy basics"},
  {"id":"aj-012","cat":"growing-a-baby","type":"match","hook":"Match the pregnancy fact to the truth.","pairs":[{"left":"Where the baby grows","right":"In the uterus"},{"left":"How it gets food","right":"Through the cord from the parent"},{"left":"How long, roughly","right":"About 9 months"}],"relearn":"A baby grows in the uterus, fed through the cord, for about nine months.","persona":"any","source":"pregnancy basics"},
  {"id":"aj-013","cat":"growing-a-baby","type":"strike-rewrite","hook":"\"The baby grows in the parent's stomach where food goes.\"","myth":{"un":"A baby grows in the stomach with the food.","re":"A baby grows in the uterus, a special organ, not the food-stomach.","why":"The uterus is made for growing a baby."},"relearn":"A baby grows in the uterus, not the food-stomach.","persona":"any","source":"pregnancy basics"},
  {"id":"aj-014","cat":"growing-a-baby","type":"reflect","hook":"Lensy: pregnancy changes the pregnant person's body a lot. Is that normal?","prompt":"What do you think?","options":["Yes","Their body's growing a baby","Normal and amazing"],"affirm":"A growing belly and other changes are the body doing amazing work.","relearn":"A pregnant body changes a lot; that's it working hard to grow a baby.","persona":"any","source":"pregnancy basics"},
  {"id":"aj-015","cat":"growing-a-baby","type":"sort","hook":"Sort: true about pregnancy, or a myth?","items":[{"id":"a","text":"It takes about 9 months"},{"id":"b","text":"The baby grows in the uterus"},{"id":"c","text":"You can tell a baby's personality before birth from cravings"},{"id":"d","text":"The baby is fed through a cord"}],"bins":[{"id":"true","label":"True"},{"id":"myth","label":"Myth"}],"key":{"a":"true","b":"true","c":"myth","d":"true"},"relearn":"Pregnancy lasts ~9 months in the uterus, baby fed by a cord; cravings don't reveal personality.","persona":"any","source":"pregnancy basics"},
  {"id":"aj-016","cat":"growing-a-baby","type":"branch","hook":"A pregnant relative is tired and you want to help.","options":[{"text":"Be gentle and helpful; her body's working hard","consequence":"You're kind and understanding about pregnancy.","outcome":"kind","best":true},{"text":"Expect her to do everything as usual","consequence":"Growing a baby is hard work; a little help is kind."}],"debrief":"Pregnancy is hard work; kindness and help are appreciated.","relearn":"Be kind to pregnant people; their body is doing big work.","persona":"any","source":"empathy"},
  // — Being born —
  {"id":"aj-017","cat":"being-born","type":"build","hook":"Time to be born! Order the arrival, simply.","prompt":"Order being born.","pieces":["the baby is fully grown","the body signals it's time","the baby is born","the baby breathes & cries hello"],"mode":"sequence","key":["the baby is fully grown","the body signals it's time","the baby is born","the baby breathes & cries hello"],"relearn":"When ready, the baby is born and takes its first breath.","persona":"any","source":"birth basics"},
  {"id":"aj-018","cat":"being-born","type":"strike-rewrite","hook":"\"Babies can only be born one way.\"","myth":{"un":"Babies can only come out one way.","re":"A baby is born through the vagina, or by a surgery called a C-section.","why":"Both are safe, normal ways to be born."},"relearn":"Babies are born through the vagina or by a C-section; both are normal.","persona":"any","source":"birth basics"},
  {"id":"aj-019","cat":"being-born","type":"match","hook":"Match the birth word to its meaning.","pairs":[{"left":"C-section","right":"Born through a surgery cut"},{"left":"Newborn","right":"A just-born baby"},{"left":"Midwife/doctor","right":"Helps the baby be born safely"}],"relearn":"Doctors and midwives help babies be born safely, in more than one way.","persona":"any","source":"birth basics"},
  {"id":"aj-020","cat":"being-born","type":"reflect","hook":"Lensy: being born is the end of one journey and the start of a whole life. Wow?","prompt":"What do you think?","options":["Wow","Amazing","A big day"],"affirm":"Your birth was the start of the whole adventure that is you.","relearn":"Being born begins your lifelong journey.","persona":"any","source":"wonder"},
  {"id":"aj-021","cat":"being-born","type":"strike-rewrite","hook":"\"A C-section birth is 'not a real' birth.\"","myth":{"un":"A C-section isn't a 'real' birth.","re":"A C-section is a real, safe birth; the baby and parent are just as amazing.","why":"How you're born doesn't change anything about you."},"relearn":"All births, vaginal or C-section, are real and amazing.","persona":"any","source":"birth equity"},
  {"id":"aj-022","cat":"being-born","type":"reflect","hook":"Lensy: newborns are tiny and need lots of care. Makes sense why?","prompt":"What do you think?","options":["Yes","They're brand new","They need everything"],"affirm":"Newborns rely on caregivers for everything, that's where family love starts.","relearn":"Newborns need full care; that's where family caregiving begins.","persona":"any","source":"newborn care"},
  // — Many ways families have babies —
  {"id":"aj-023","cat":"many-ways","type":"strike-rewrite","hook":"\"Every family makes a baby the same way.\"","myth":{"un":"All families have babies the same way.","re":"Families are built in many ways: birth, adoption, doctors' help, and more.","why":"There's more than one path to a family."},"relearn":"Families have babies in many ways, all real and loving.","persona":"any","source":"many ways to family"},
  {"id":"aj-024","cat":"many-ways","type":"match","hook":"Match the family path to what it means.","pairs":[{"left":"Adoption","right":"A family welcomes a child as their own"},{"left":"IVF (doctors' help)","right":"Doctors help egg & sperm meet"},{"left":"Surrogacy","right":"Someone helps carry a baby for a family"}],"relearn":"Adoption, IVF and surrogacy are all real ways families have children.","persona":"Asha","source":"assisted reproduction / adoption"},
  {"id":"aj-025","cat":"many-ways","type":"strike-rewrite","hook":"\"Adopted kids aren't 'really' their parents' children.\"","myth":{"un":"Adopted children aren't really their family's own.","re":"An adopted child is fully and truly their family's child.","why":"Love and care make a family (see My Family Garden)."},"relearn":"Adopted children are completely, truly family.","persona":"any","source":"adoption (links g03)"},
  {"id":"aj-026","cat":"many-ways","type":"reflect","hook":"Lensy: some babies need a doctor's help to begin. Does that make them any less amazing?","prompt":"What do you think?","options":["No","Just as amazing","Wanted just as much"],"affirm":"However a baby begins, they're just as loved and amazing.","relearn":"A baby made with a doctor's help is just as wanted and amazing.","persona":"any","source":"assisted reproduction"},
  {"id":"aj-027","cat":"many-ways","type":"branch","hook":"A classmate says they were adopted and seems unsure how you'll react.","options":[{"text":"Say \"that's cool, your family chose you\"","consequence":"They feel accepted and proud.","outcome":"kind","best":true},{"text":"Act like it's weird","consequence":"Adoption is a loving way to build a family; be warm about it."}],"debrief":"Adoption is a loving path; respond with warmth, not surprise.","relearn":"Be warm about all the ways families are built.","persona":"any","source":"inclusion / adoption"},
  {"id":"aj-028","cat":"many-ways","type":"strike-rewrite","hook":"\"You need exactly a mum and a dad to have a baby/family.\"","myth":{"un":"A family must be exactly one mum and one dad.","re":"Loving families come in many forms; what matters is the love and care.","why":"Single parents, grandparents and others raise children with love."},"relearn":"Loving families come in many forms, not just one shape.","persona":"any","source":"family diversity (links g03)"},
  {"id":"aj-029","cat":"many-ways","type":"reflect","hook":"Lensy: in India, families also grow through adoption (with help like CARA). Good to know there are paths?","prompt":"What do you think?","options":["Yes","Many paths","Good options exist"],"affirm":"There are caring, legal ways to build a family, including adoption.","relearn":"India has caring paths to family, including adoption.","persona":"Asha","source":"India adoption (CARA)"},
  {"id":"aj-030","cat":"many-ways","type":"sort","hook":"Sort: a real way a family can have a child, or a myth?","items":[{"id":"a","text":"Giving birth"},{"id":"b","text":"Adoption"},{"id":"c","text":"Buying a baby from a shop"},{"id":"d","text":"Doctors' help (IVF)"}],"bins":[{"id":"real","label":"Real path"},{"id":"myth","label":"Not real"}],"key":{"a":"real","b":"real","c":"myth","d":"real"},"relearn":"Birth, adoption and IVF are real paths; 'buying from a shop' is a myth.","persona":"any","source":"many ways to family"},
  {"id":"aj-031","cat":"many-ways","type":"role-play","hook":"A friend wonders if their IVF/adoption story is something to hide.","setup":"Reassure them. Say:","yourLine":[{"text":"\"Your story is special, and your family loves you, that's what counts.\"","best":true},{"text":"\"Maybe keep it secret.\""}],"relearn":"However a family began, it's a story to feel good about.","persona":"any","source":"support / inclusion"},
  {"id":"aj-032","cat":"many-ways","type":"reflect","hook":"Lensy: every kid, however they joined their family, is wanted and loved. Agree?","prompt":"What do you think?","options":["Yes","Every kid","Loved is loved"],"affirm":"Every child deserves to feel wanted and loved, however they arrived.","relearn":"Every child is wanted and loved, whatever their family's path.","persona":"any","source":"belonging"},
  // — Busting the baby myths —
  {"id":"aj-033","cat":"myths-busted","type":"strike-rewrite","hook":"\"Kissing or holding hands makes a baby.\"","myth":{"un":"Kissing or holding hands can make a baby.","re":"Babies need an egg and a sperm to join; kissing can't do that.","why":"It's specific biology, not everyday contact."},"relearn":"Kissing or holding hands doesn't make a baby.","persona":"any","source":"reproduction myths"},
  {"id":"aj-034","cat":"myths-busted","type":"strike-rewrite","hook":"\"Swimming in a pool can get you pregnant.\"","myth":{"un":"You can get pregnant from a swimming pool.","re":"Pregnancy needs egg and sperm to join inside the body; a pool can't do that.","why":"It's a common myth with no science behind it."},"relearn":"You can't get pregnant from a swimming pool.","persona":"any","source":"reproduction myths"},
  {"id":"aj-035","cat":"myths-busted","type":"sort","hook":"Sort: reproduction fact, or myth?","items":[{"id":"a","text":"A baby needs an egg and a sperm"},{"id":"b","text":"Storks deliver babies"},{"id":"c","text":"A baby grows in the uterus"},{"id":"d","text":"You can wish a baby into being"}],"bins":[{"id":"fact","label":"Fact"},{"id":"myth","label":"Myth"}],"key":{"a":"fact","b":"myth","c":"fact","d":"myth"},"relearn":"Egg+sperm and the uterus are facts; storks and wishes are myths.","persona":"any","source":"reproduction myths"},
  {"id":"aj-036","cat":"myths-busted","type":"strike-rewrite","hook":"\"Only the woman decides a baby's traits.\"","myth":{"un":"A baby's traits come from only one parent.","re":"A baby gets a mix from the egg and the sperm, both contribute.","why":"That's why kids resemble different relatives."},"relearn":"A baby's traits come from both the egg and the sperm.","persona":"any","source":"genetics basics"},
  {"id":"aj-037","cat":"myths-busted","type":"branch","hook":"A friend repeats a wild 'how babies are made' myth.","options":[{"text":"Share the real, simple science kindly","consequence":"You both end up better informed.","outcome":"informed","best":true},{"text":"Laugh at them","consequence":"Sharing the facts kindly beats mocking."}],"debrief":"Replacing a myth with kind, clear facts helps everyone.","relearn":"Kindly correcting baby myths with facts is helpful.","persona":"Aarav","source":"peer education"},
  {"id":"aj-038","cat":"myths-busted","type":"strike-rewrite","hook":"\"It's a parent's fault if they can't have a baby easily.\"","myth":{"un":"Not being able to have a baby easily is someone's 'fault'.","re":"Many things affect fertility; it's nobody's fault, and there's help.","why":"Bodies differ; doctors can often help."},"relearn":"Trouble having a baby isn't anyone's fault; help exists.","persona":"any","source":"fertility / compassion"},
  {"id":"aj-039","cat":"myths-busted","type":"reflect","hook":"Lensy: knowing the real science means no one can fool you with baby myths. Useful?","prompt":"What do you think?","options":["Yes","Facts protect me","I know the truth now"],"affirm":"The real science is your shield against silly or scary myths.","relearn":"Knowing the facts protects you from reproduction myths.","persona":"any","source":"information literacy"},
  {"id":"aj-040","cat":"myths-busted","type":"strike-rewrite","hook":"\"The baby's sex is the mother's doing.\"","myth":{"un":"Whether a baby is a boy or girl is the mother's fault/doing.","re":"A baby's sex comes from the sperm's contribution, not the mother.","why":"Blaming mothers for a baby's sex is an unfair, unscientific myth."},"relearn":"A baby's sex is decided by the sperm, not the mother, and is no one's 'fault'.","persona":"Asha","source":"genetics / India gender bias"},
  {"id":"aj-041","cat":"myths-busted","type":"branch","hook":"Someone blames a woman for 'only' having daughters.","options":[{"text":"Say \"the sex comes from the father's side, and daughters are just as wonderful\"","consequence":"You bust a harmful, unfair myth.","outcome":"ally","best":true},{"text":"Stay quiet","consequence":"This myth harms women; the science (and fairness) is worth sharing."}],"debrief":"Blaming mothers for a baby's sex is both unscientific and unfair to girls.","relearn":"A baby's sex isn't the mother's doing; daughters are equally valued.","persona":"Ananya","source":"India gender bias / science"},
  // — Your own amazing journey —
  {"id":"aj-042","cat":"amazing-and-mine","type":"reflect","hook":"Lensy: YOU came from this amazing journey. How does that feel?","prompt":"What do you think?","options":["Special","Amazing","Grateful"],"affirm":"You're the result of an incredible journey, and you're here. Amazing.","relearn":"You came from an amazing journey; you're here and that's special.","persona":"any","source":"wonder / self-worth"},
  {"id":"aj-043","cat":"amazing-and-mine","type":"build","hook":"Build the whole journey in order, start to you.","prompt":"Put the amazing journey in order.","pieces":["egg + sperm join","grows in the uterus","is born","grows up into you"],"mode":"sequence","key":["egg + sperm join","grows in the uterus","is born","grows up into you"],"relearn":"Egg+sperm, grow, born, grow up, the amazing journey to you.","persona":"any","source":"consolidation"},
  {"id":"aj-044","cat":"amazing-and-mine","type":"strike-rewrite","hook":"\"How I came into my family makes me 'less' than others.\"","myth":{"un":"How I joined my family makes me less than other kids.","re":"However you arrived, you're fully wanted, loved and equal.","why":"Your worth doesn't depend on your family's path."},"relearn":"However you joined your family, you're equal, wanted and loved.","persona":"any","source":"belonging / self-worth"},
  {"id":"aj-045","cat":"amazing-and-mine","type":"reflect","hook":"Lensy: it's okay to have questions about where you came from. Ask trusted sources?","prompt":"What do you think?","options":["Yes","I'll ask","No question is silly"],"affirm":"Curiosity about your origins is natural; trusted grown-ups can help.","relearn":"You can ask trusted sources about reproduction and your own story.","persona":"Diya","source":"help-seeking"},
  {"id":"aj-046","cat":"amazing-and-mine","type":"role-play","hook":"You want to ask a trusted adult a reproduction question.","setup":"Open it up. Say:","yourLine":[{"text":"\"Can I ask you something about how babies are made?\"","best":true},{"text":"Search something random instead"}],"relearn":"A trusted adult is a great, accurate source for these questions.","persona":"Aarav","source":"help-seeking / voice"},
  {"id":"aj-047","cat":"amazing-and-mine","type":"reflect","hook":"Lensy: respecting how life is made also means respecting pregnant people and parents. Agree?","prompt":"What do you think?","options":["Yes","They do amazing work","Respect"],"affirm":"Understanding the journey grows respect for those who go through it.","relearn":"Knowing the journey grows respect for parents and pregnant people.","persona":"any","source":"respect / empathy"},
  {"id":"aj-048","cat":"amazing-and-mine","type":"sort","hook":"Sort: a healthy attitude about reproduction, or not?","items":[{"id":"a","text":"It's natural science to understand"},{"id":"b","text":"It's dirty and shameful"},{"id":"c","text":"All family paths are valid"},{"id":"d","text":"Some kids are 'less real'"}],"bins":[{"id":"healthy","label":"Healthy"},{"id":"no","label":"Unhealthy myth"}],"key":{"a":"healthy","b":"no","c":"healthy","d":"no"},"relearn":"Reproduction is natural science, and every family path and child is valid.","persona":"any","source":"values"},
  {"id":"aj-049","cat":"spark-of-life","type":"reflect","hook":"Lensy: you don't have to know every detail now; you can learn more as you grow. Okay with that?","prompt":"What do you think?","options":["Yes","Bit by bit","I'll keep learning"],"affirm":"You learn this in stages, you've got a great, honest start.","relearn":"You can learn reproduction step by step as you grow.","persona":"any","source":"developmental pacing"},
  {"id":"aj-050","cat":"growing-a-baby","type":"branch","hook":"You're curious how twins happen.","options":[{"text":"Ask a trusted source for the simple science","consequence":"You learn that twins come from one egg splitting, or two eggs.","outcome":"informed","best":true},{"text":"Make up an explanation","consequence":"The real science is more interesting than a guess."}],"debrief":"Twins happen when one egg splits, or two eggs are fertilised, real science.","relearn":"Twins come from one egg splitting or two eggs; ask to learn more.","persona":"Aarav","source":"reproduction basics"},
  {"id":"aj-051","cat":"being-born","type":"reflect","hook":"Lensy: birthdays celebrate the day your journey 'arrived'. Nice way to see it?","prompt":"What do you think?","options":["Yes","Love that","My arrival day"],"affirm":"Your birthday is the anniversary of your amazing arrival.","relearn":"A birthday celebrates the day you were born, your arrival.","persona":"any","source":"wonder"},
  {"id":"aj-052","cat":"many-ways","type":"branch","hook":"A kid teases another for not having both a mum and dad.","options":[{"text":"Say \"all kinds of families are real and good\"","consequence":"You defend a friend and the truth.","outcome":"ally","best":true},{"text":"Join the teasing","consequence":"Every family form is valid; stand up for that."}],"debrief":"Families come in many forms; teasing about that isn't okay.","relearn":"All family forms are real; you can stand up for that.","persona":"any","source":"inclusion (links g03)"},
  {"id":"aj-053","cat":"myths-busted","type":"strike-rewrite","hook":"\"You can catch pregnancy like a cold.\"","myth":{"un":"Pregnancy is something you can 'catch' like an illness.","re":"Pregnancy isn't an illness or contagious; it needs egg and sperm to join.","why":"It's a specific biological process, not a germ."},"relearn":"Pregnancy isn't catching; it's a specific biological process.","persona":"any","source":"reproduction myths"},
  {"id":"aj-054","cat":"amazing-and-mine","type":"reflect","hook":"Lensy: what amazed you most in this journey?","prompt":"Pick one.","options":["The first joined cell","Growing in the uterus","Being born","Many ways to family"],"affirm":"It's all amazing, and now you understand it. Quest complete!","relearn":"The whole journey, from one cell to you, is amazing.","persona":"any","source":"consolidation"},
  {"id":"aj-055","cat":"spark-of-life","type":"match","hook":"Match each part to its job in starting life.","pairs":[{"left":"Ovaries","right":"Make egg cells"},{"left":"Testes","right":"Make sperm cells"},{"left":"Uterus","right":"Grows the baby"}],"relearn":"Ovaries make eggs, testes make sperm, the uterus grows the baby.","persona":"any","source":"reproductive anatomy (links g06)"},
  {"id":"aj-056","cat":"growing-a-baby","type":"strike-rewrite","hook":"\"What the pregnant person feels or eats can curse the baby.\"","myth":{"un":"A pregnant person's moods or foods can 'curse' the baby.","re":"Healthy food and care help; but old 'curse' beliefs are myths.","why":"Good care matters; superstition doesn't."},"relearn":"Healthy care helps a pregnancy; superstitions don't curse a baby.","persona":"Asha","source":"pregnancy myths / India"},
  {"id":"aj-057","cat":"being-born","type":"sort","hook":"Sort: true about birth, or myth?","items":[{"id":"a","text":"Doctors/midwives help babies arrive safely"},{"id":"b","text":"Babies are born only at night"},{"id":"c","text":"C-section is a safe way to be born"},{"id":"d","text":"The baby chooses its own birthday on purpose"}],"bins":[{"id":"true","label":"True"},{"id":"myth","label":"Myth"}],"key":{"a":"true","b":"myth","c":"true","d":"myth"},"relearn":"Helpers and C-sections are real; 'only at night' and 'baby chooses' are myths.","persona":"any","source":"birth myths"},
  {"id":"aj-058","cat":"many-ways","type":"reflect","hook":"Lensy: a family is made by love and care, however the children arrive. Agree?","prompt":"What do you think?","options":["Yes","Love makes family","However they arrive"],"affirm":"Love and care make a family; the path there can be many things.","relearn":"Love and care make a family, whatever path brought it together.","persona":"any","source":"family (links g03)"},
  {"id":"aj-059","cat":"myths-busted","type":"branch","hook":"Online, someone shares scary, false 'facts' about pregnancy.","options":[{"text":"Check with a trusted source before believing","consequence":"You avoid a scary myth and learn the truth.","outcome":"savvy","best":true},{"text":"Believe and panic","consequence":"Scary online 'facts' need checking with trusted sources."}],"debrief":"Reproduction facts online can be wrong; verify with trusted sources.","relearn":"Check pregnancy and reproduction 'facts' with trusted sources.","persona":"Aarav","source":"information literacy (links g12)"},
  {"id":"aj-060","cat":"amazing-and-mine","type":"role-play","hook":"A younger sibling asks you where babies come from.","setup":"Give them the simple, honest version. Say:","yourLine":[{"text":"\"A baby starts from an egg and a sperm, and grows in the uterus.\"","best":true},{"text":"\"A stork brings them.\""}],"relearn":"You can pass on simple, honest facts to a younger child.","persona":"any","source":"peer education"},
  {"id":"aj-061","cat":"growing-a-baby","type":"reflect","hook":"Lensy: a pregnant person deserves care, rest and respect. Agree?","prompt":"What do you think?","options":["Yes","Definitely","They're doing big work"],"affirm":"Care and respect for pregnant people is part of valuing the journey.","relearn":"Pregnant people deserve care, rest and respect.","persona":"any","source":"respect"},
  {"id":"aj-062","cat":"spark-of-life","type":"strike-rewrite","hook":"\"Reproduction is too complicated for kids to understand.\"","myth":{"un":"Reproduction is too complicated for kids.","re":"The basics are simple and you can absolutely understand them.","why":"You just learned them!"},"relearn":"The basics of reproduction are simple enough to understand.","persona":"any","source":"empowerment"},
  {"id":"aj-063","cat":"many-ways","type":"match","hook":"Match the child to a true thing about their family. (All loving!)","pairs":[{"left":"Born to their parents","right":"A loving family"},{"left":"Adopted","right":"A loving family"},{"left":"Born with IVF help","right":"A loving family"}],"relearn":"However a child joined, theirs is a loving family.","persona":"any","source":"family diversity"},
  {"id":"aj-064","cat":"myths-busted","type":"reflect","hook":"Lensy: which baby-myth surprised you most to learn was false?","prompt":"Pick one.","options":["Storks","Swimming pools","Kissing","'Mother decides the sex'"],"affirm":"Now you know the real science behind each one.","relearn":"You can spot and bust common reproduction myths now.","persona":"any","source":"consolidation"},
  {"id":"aj-065","cat":"being-born","type":"branch","hook":"You hear birth described as scary and gross.","options":[{"text":"See it as natural and amazing, even if intense","consequence":"You hold a healthy, awe-filled view of birth.","outcome":"matter-of-fact","best":true},{"text":"Decide it's just gross","consequence":"Birth is intense but natural and amazing, not 'gross'."}],"debrief":"Birth is intense but natural and amazing, not something to be grossed out by.","relearn":"Birth is a natural, amazing process.","persona":"any","source":"normalisation"},
  {"id":"aj-066","cat":"amazing-and-mine","type":"reflect","hook":"Lensy: understanding this helps you respect bodies, families and yourself. Agree?","prompt":"What do you think?","options":["Yes","All of those","It's connected"],"affirm":"Knowing the journey connects respect for bodies, families and you.","relearn":"Understanding reproduction grows respect for bodies, families and yourself.","persona":"any","source":"values"},
  {"id":"aj-067","cat":"spark-of-life","type":"branch","hook":"A friend is embarrassed even hearing the words 'egg' and 'sperm'.","options":[{"text":"Treat them as normal science words","consequence":"It gets less awkward fast; they're just facts.","outcome":"matter-of-fact","best":true},{"text":"Giggle and make it weird","consequence":"They're normal science words; treating them calmly helps."}],"debrief":"Egg and sperm are normal science words; calm beats giggly.","relearn":"Reproduction words are normal science; you can say them calmly.","persona":"Aarav","source":"normalisation"},
  {"id":"aj-068","cat":"growing-a-baby","type":"build","hook":"Build a 'pregnancy needs' list, what helps a healthy pregnancy.","prompt":"Add what helps.","pieces":["good food","rest","doctor check-ups","care & support","stress and superstition"],"mode":"assemble","key":["good food","rest","doctor check-ups","care & support"],"relearn":"Good food, rest, check-ups and support help a healthy pregnancy.","persona":"Asha","source":"prenatal health"},
  {"id":"aj-069","cat":"many-ways","type":"strike-rewrite","hook":"\"A family without children isn't a real family.\"","myth":{"un":"You're only a family if you have children.","re":"A couple or group can be a full family with or without children.","why":"Family is about bonds, not only babies."},"relearn":"Families are families with or without children.","persona":"any","source":"family diversity"},
  {"id":"aj-070","cat":"myths-busted","type":"strike-rewrite","hook":"\"You can tell exactly what a baby will look like before it's born.\"","myth":{"un":"You can know exactly how a baby will look before birth.","re":"A baby's looks are a surprise mix of both parents' genes.","why":"Genes combine in unpredictable ways."},"relearn":"A baby's looks are an unpredictable mix of both parents.","persona":"any","source":"genetics"},
  {"id":"aj-071","cat":"amazing-and-mine","type":"reflect","hook":"Lensy: you can carry this knowledge calmly and confidently now. Feel ready?","prompt":"What do you think?","options":["Yes","Confident","I get it now"],"affirm":"You understand the amazing journey, calmly and confidently. Well done.","relearn":"You can understand reproduction calmly and confidently.","persona":"any","source":"empowerment"},
  {"id":"aj-072","cat":"being-born","type":"match","hook":"Match the helper to how they help at birth.","pairs":[{"left":"Doctor","right":"Handles medical care"},{"left":"Midwife/nurse","right":"Supports the birth"},{"left":"Family","right":"Welcomes the baby"}],"relearn":"A team of helpers supports a safe birth and a warm welcome.","persona":"any","source":"birth basics"},
  {"id":"aj-073","cat":"spark-of-life","type":"sort","hook":"Sort: a correct first-step fact, or muddled?","items":[{"id":"a","text":"Egg and sperm join to start a baby"},{"id":"b","text":"A baby starts on its own from nothing"},{"id":"c","text":"It takes one cell from each side"},{"id":"d","text":"Babies grow from food alone"}],"bins":[{"id":"correct","label":"Correct"},{"id":"muddled","label":"Muddled"}],"key":{"a":"correct","b":"muddled","c":"correct","d":"muddled"},"relearn":"A baby starts from an egg and a sperm joining, one cell from each side.","persona":"any","source":"reproduction basics"},
  {"id":"aj-074","cat":"many-ways","type":"reflect","hook":"Lensy: knowing many families' paths helps you be kind to everyone. Agree?","prompt":"What do you think?","options":["Yes","Kinder to all","No judging"],"affirm":"Understanding the many paths to family makes you a kinder friend.","relearn":"Knowing many family paths helps you be kind and non-judging.","persona":"any","source":"empathy"},
  {"id":"aj-075","cat":"myths-busted","type":"branch","hook":"Capstone myth check: a friend insists a baby's sex is the mother's fault.","options":[{"text":"Explain it's from the sperm, and value all children equally","consequence":"You bust a harmful myth that hurts women and girls.","outcome":"ally","best":true},{"text":"Let it slide","consequence":"This myth fuels unfairness; the science is worth sharing."}],"debrief":"A baby's sex is from the sperm, and every child is equally valued.","relearn":"A baby's sex isn't the mother's fault; all children are valued.","persona":"Ananya","source":"India gender bias / science"},
  {"id":"aj-076","cat":"amazing-and-mine","type":"reflect","hook":"Lensy: respect the journey, respect bodies, respect every family. Carry that?","prompt":"What do you think?","options":["Yes","I'll carry it","Respect all round"],"affirm":"That respect is the heart of The Amazing Journey.","relearn":"Respect the journey, bodies, and every kind of family.","persona":"any","source":"values"},
  {"id":"aj-077","cat":"growing-a-baby","type":"reflect","hook":"Lensy: the human body growing a whole new person is incredible. Agree?","prompt":"What do you think?","options":["Incredible","Amazing","Wow"],"affirm":"Bodies that grow new life are doing one of nature's most amazing things.","relearn":"Growing a new person is one of the body's most amazing feats.","persona":"any","source":"wonder"},
  {"id":"aj-078","cat":"spark-of-life","type":"reflect","hook":"Lensy: this was the science of how life begins, handled calmly. Glad you know it?","prompt":"What do you think?","options":["Yes","Glad I do","No more confusion"],"affirm":"You've got an honest, accurate foundation, that's powerful.","relearn":"You now understand, calmly and accurately, how life begins.","persona":"any","source":"empowerment"},
  {"id":"aj-079","cat":"many-ways","type":"build","hook":"Build a 'ways to family' display.","prompt":"Add the real, loving paths.","pieces":["birth","adoption","IVF / doctors' help","surrogacy","blended families"],"mode":"assemble","key":["birth","adoption","IVF / doctors' help","surrogacy","blended families"],"relearn":"Birth, adoption, IVF, surrogacy and blending, all real, loving paths to family.","persona":"any","source":"many ways to family"},
  {"id":"aj-080","cat":"being-born","type":"reflect","hook":"Lensy: every adult you've ever met went on this same journey. Mind-blowing?","prompt":"What do you think?","options":["Yes!","Everyone did","Whoa"],"affirm":"Every single person started exactly this way, you're in good company.","relearn":"Everyone went on this amazing journey; you're not alone in it.","persona":"any","source":"shared humanity"},
  {"id":"aj-081","cat":"myths-busted","type":"sort","hook":"Final myth sort: fact or myth?","items":[{"id":"a","text":"Egg + sperm makes a baby"},{"id":"b","text":"Storks deliver babies"},{"id":"c","text":"Adoption makes a real family"},{"id":"d","text":"Swimming pools cause pregnancy"}],"bins":[{"id":"fact","label":"Fact"},{"id":"myth","label":"Myth"}],"key":{"a":"fact","b":"myth","c":"fact","d":"myth"},"relearn":"You can now tell reproduction facts from myths with confidence.","persona":"any","source":"consolidation"},
  {"id":"aj-082","cat":"amazing-and-mine","type":"reflect","hook":"Lensy: what's your big take-away from The Amazing Journey?","prompt":"Pick your motto.","options":["Life begins from egg + sperm","Many ways to family","However I arrived, I'm loved","It's natural and amazing"],"affirm":"Carry that. You understand, respect, and are part of, the amazing journey.","relearn":"Life begins from egg + sperm, families form many ways, and every child is loved.","persona":"any","source":"consolidation"},
  {"id":"aj-083","cat":"spark-of-life","type":"strike-rewrite","hook":"\"Only girls need to learn how reproduction works.\"","myth":{"un":"Only girls need to learn about reproduction.","re":"Everyone should understand it; it builds knowledge and respect.","why":"It concerns and benefits everyone."},"relearn":"Everyone, all genders, should learn how reproduction works.","persona":"Aarav","source":"inclusive education"},
  {"id":"aj-084","cat":"amazing-and-mine","type":"role-play","hook":"You finished the quest and feel good knowing the truth.","setup":"Say your scientist-of-life line:","yourLine":[{"text":"\"I understand the amazing journey, and I respect it.\"","best":true},{"text":"\"I'll just stay confused.\""}],"relearn":"You can own this knowledge with calm confidence and respect.","persona":"any","source":"empowerment / consolidation"},
];

export const AMAZING_JOURNEY: V2GameConfig = {
  gameId: "amazing-journey",
  title: "The Amazing Journey",
  greet: "Hey, it's Lensy. ✨ The real, amazing science of how a new life begins and grows — and the many loving ways families have children. Clear, accurate, private.",
  scenarios: SCENARIOS,
  categories: [
    { id: "spark-of-life", emoji: "✨", label: "How life begins" },
    { id: "growing-a-baby", emoji: "🤰", label: "Growing a baby" },
    { id: "being-born", emoji: "👶", label: "Being born" },
    { id: "many-ways", emoji: "👪", label: "Many ways" },
    { id: "myths-busted", emoji: "🧹", label: "Myths busted" },
    { id: "amazing-and-mine", emoji: "🌟", label: "Amazing & mine" },
  ],
  badge: {
    title: "Amazing Journey complete! ✨",
    blurb: "You know how life begins (egg + sperm), how a baby grows and is born, the many loving ways families have children, and that a baby's sex comes from the sperm. ✨",
  },
  helpLine: "Curious to learn more? A trusted adult, teacher or doctor can answer your questions — or call Childline, one-zero-nine-eight. No question is silly.",
  helpLabel: "Get help · Childline 1098",
  reassure: "However a baby joins a family — birth, adoption, a doctor's help — that family is real and full of love, and every child is wanted. 💛",
  reassureCats: ["many-ways"],
  buildLabels: { assemble: "That's it! ✨", sequence: "That's the amazing journey! ✨" },
};
