// Content for Body Confident (node g21, ages 12–15, Chapter 4) — NEW v2 build to GDD 21 (mechanic-embodying),
// the puberty-depth + body-image + media-literacy node (Thread A · Body & Growing Up) that OPENS Chapter 4.
// "Your worth was never your looks." 84 researched, India-grounded scenarios across the changing-body →
// real-vs-filtered → worth-not-looks → beauty-myths → care-not-fix → when-heavy arc, each encoded as one of
// the shared v2 play actions (strike-rewrite / spot / sort / reflect / branch / role-play / build) — no binary
// "tap the right card". Lead mechanics: strike-rewrite (bust the beauty myth ×23), spot (Fact-or-Filter ×12),
// sort (real vs filtered, care vs 'fix' ×13). Body-NEUTRAL (worth untied from looks, never diet/ideal-body
// framing) + media literacy (spot the filter; most posts are edited). Names India's colourism / fair-skin
// pressure as a harmful false standard; every skin tone, shape and size is normal. Gender-inclusive (boys
// face body pressure too). WELLBEING-SAFE: persistent body distress / disordered-eating signs (skipping meals,
// over-exercising) route to a trusted adult, school counsellor or doctor (the when-heavy beats end on a
// reassurance). Builds on g13 (Puberty Quest); prereq c3. Rendered by the shared engine
// (components/games/v2-engine.tsx). gameId "body-confident". DO NOT RENAME.

import type { Scenario, V2GameConfig } from "./v2-schema";

const SCENARIOS: Scenario[] = [
  // — Your still-changing body —
  {"id":"bc-001","cat":"changing-body","type":"strike-rewrite","hook":"\"Everyone should finish puberty at the same time.\"","myth":{"un":"There's a 'right' time to be done with puberty.","re":"Bodies change on their own timetable; early and late are both normal.","why":"Puberty has a wide normal range."},"relearn":"Bodies grow on their own schedule; there's no 'behind'.","persona":"Veer","source":"puberty depth (UNESCO 6.3)"},
  {"id":"bc-002","cat":"changing-body","type":"strike-rewrite","hook":"\"Acne means you're dirty or doing something wrong.\"","myth":{"un":"Acne means you're unclean or bad.","re":"Acne is a normal hormonal part of puberty, not a hygiene fault.","why":"Hormones, not dirt, drive most teen acne."},"relearn":"Acne is normal puberty, not a sign you're dirty.","persona":"Riya","source":"puberty / skin"},
  {"id":"bc-003","cat":"changing-body","type":"strike-rewrite","hook":"\"Periods should be hidden and never talked about.\"","myth":{"un":"Periods are shameful and must be hidden.","re":"Menstruation is a normal, healthy body process you can manage with dignity.","why":"Stigma, not periods, is the problem."},"relearn":"Periods are normal and healthy; manage them with dignity, no shame.","persona":"Riya","source":"menstrual health (links g13)"},
  {"id":"bc-004","cat":"changing-body","type":"strike-rewrite","hook":"\"Wet dreams or getting aroused means something's wrong with me.\"","myth":{"un":"Wet dreams or arousal are signs something's wrong.","re":"They're a normal, expected part of a maturing body.","why":"This is healthy development, not a fault."},"relearn":"Wet dreams and arousal are a normal part of growing up.","persona":"Veer","source":"puberty / bodies"},
  {"id":"bc-005","cat":"changing-body","type":"strike-rewrite","hook":"\"A deeper voice or body hair means I should already look 'grown'.\"","myth":{"un":"Once changes start, I should instantly look fully grown.","re":"Changes arrive gradually and unevenly, that's how it works.","why":"Development is a slow, uneven process."},"relearn":"Puberty changes come gradually and unevenly; that's normal.","persona":"Veer","source":"puberty depth"},
  {"id":"bc-006","cat":"changing-body","type":"sort","hook":"Sort: a normal part of puberty, or a myth?","items":[{"id":"a","text":"Growing at your own pace"},{"id":"b","text":"\"Everyone develops by 13\""},{"id":"c","text":"Skin and voice changing"},{"id":"d","text":"\"Late means unhealthy\""}],"bins":[{"id":"normal","label":"Normal"},{"id":"myth","label":"Myth"}],"key":{"a":"normal","b":"myth","c":"normal","d":"myth"},"relearn":"Developing at your own pace is normal; 'deadlines' for it are myths.","persona":"any","source":"puberty depth"},
  {"id":"bc-007","cat":"changing-body","type":"sort","hook":"Sort: bodies that are all completely normal.","items":[{"id":"a","text":"Tall and short"},{"id":"b","text":"Curvy and slim"},{"id":"c","text":"Every skin tone"},{"id":"d","text":"Different at every age"}],"bins":[{"id":"normal","label":"All normal"},{"id":"no","label":"Not normal"}],"key":{"a":"normal","b":"normal","c":"normal","d":"normal"},"relearn":"Bodies come in every shape, size and shade, all normal.","persona":"any","source":"body diversity"},
  {"id":"bc-008","cat":"changing-body","type":"sort","hook":"Sort: who can help with a body question?","items":[{"id":"a","text":"A doctor"},{"id":"b","text":"A random ad"},{"id":"c","text":"A trusted adult or counsellor"},{"id":"d","text":"A 'miracle cure' seller"}],"bins":[{"id":"trusted","label":"Trusted source"},{"id":"no","label":"Not reliable"}],"key":{"a":"trusted","b":"no","c":"trusted","d":"no"},"relearn":"For body questions, trust a doctor or trusted adult, not ads.","persona":"Counsellor","source":"help-seeking"},
  {"id":"bc-009","cat":"changing-body","type":"reflect","hook":"Lensy: your body is doing something amazing right now, growing you up. Ever thank it?","prompt":"What do you think?","options":["Not really","It is amazing","I'll be kinder to it"],"affirm":"Your body works hard for you every single day.","relearn":"Your changing body is doing impressive work; it deserves kindness.","persona":"any","source":"body appreciation"},
  {"id":"bc-010","cat":"changing-body","type":"reflect","hook":"Lensy: questions about your changing body are normal. Got one you've been shy to ask?","prompt":"What do you think?","options":["Yes, a few","Maybe","Good to know I can ask"],"affirm":"Every body question is valid, and there's always someone safe to ask.","relearn":"It's normal to have body questions and to ask them privately.","persona":"any","source":"help-seeking / privacy"},
  {"id":"bc-011","cat":"changing-body","type":"spot","hook":"A 'puberty timeline' post online. Spot what's misleading.","scene":[{"id":"a","text":"\"By 14 you should look like this\" with one body type","trick":true},{"id":"b","text":"It mentions changes happen over years","trick":false},{"id":"c","text":"\"If not, something's wrong\"","trick":true}],"why":"Strict 'should look like this by X' timelines ignore the wide normal range.","relearn":"Be wary of rigid puberty timelines; the normal range is wide.","persona":"any","source":"media literacy / puberty"},
  {"id":"bc-012","cat":"changing-body","type":"spot","hook":"A menstrual-product ad. Spot the stigma it quietly sells.","scene":[{"id":"a","text":"Blue liquid instead of showing reality","trick":true},{"id":"b","text":"\"Stay fresh and active\"","trick":false},{"id":"c","text":"\"So no one ever has to know\"","trick":true}],"why":"Ads often frame periods as a secret to hide, feeding shame.","relearn":"Period ads can sell secrecy and shame; periods aren't shameful.","persona":"Riya","source":"media literacy / menstruation"},
  {"id":"bc-013","cat":"changing-body","type":"build","hook":"Build a kind 'my changing body' fact-kit.","prompt":"Pick the steady truths to keep.","pieces":["I grow at my own pace","every body is normal","changes are gradual","I can ask a trusted adult"],"mode":"assemble","key":["I grow at my own pace","every body is normal","changes are gradual","I can ask a trusted adult"],"relearn":"Your body facts: own pace, all normal, gradual, ask for help.","persona":"any","source":"consolidation"},
  {"id":"bc-014","cat":"changing-body","type":"build","hook":"Build a dignified period-care plan.","prompt":"Order a calm, no-shame routine.","pieces":["track roughly when it's due","keep supplies handy","change regularly for hygiene","rest or ask for help if it hurts a lot"],"mode":"sequence","key":["track roughly when it's due","keep supplies handy","change regularly for hygiene","rest or ask for help if it hurts a lot"],"relearn":"Period care is simple hygiene and self-care, handled with dignity.","persona":"Riya","source":"menstrual health"},
  // — Real vs filtered —
  {"id":"bc-015","cat":"real-vs-filtered","type":"spot","hook":"Fact or Filter: a glowing 'flawless' selfie. Spot the edits.","scene":[{"id":"a","text":"Skin smoothed to have zero pores","trick":true},{"id":"b","text":"They're smiling","trick":false},{"id":"c","text":"Jaw and waist subtly reshaped","trick":true}],"why":"Smoothed skin and reshaped features are classic filter edits, not real.","relearn":"'Flawless' selfies are usually filtered; real skin has texture.","persona":"Riya","source":"media literacy (protective)"},
  {"id":"bc-016","cat":"real-vs-filtered","type":"spot","hook":"Fact or Filter: a fitness influencer's 'effortless' photo. Spot the tricks.","scene":[{"id":"a","text":"Perfect lighting and a flexed, posed angle","trick":true},{"id":"b","text":"They worked out","trick":false},{"id":"c","text":"Subtle editing on the abs","trick":true}],"why":"Lighting, posing and editing manufacture 'effortless' bodies.","relearn":"Influencer bodies are lit, posed and edited; not an everyday reality.","persona":"Veer","source":"media literacy / male body image"},
  {"id":"bc-017","cat":"real-vs-filtered","type":"spot","hook":"Fact or Filter: a 'just woke up like this' post. Spot the setup.","scene":[{"id":"a","text":"Full makeup and a filter at 'wake up'","trick":true},{"id":"b","text":"It's morning","trick":false},{"id":"c","text":"Tenth take, best angle chosen","trick":true}],"why":"'Natural' posts are often staged, filtered and re-shot many times.","relearn":"'Natural' online often means staged, filtered and re-taken.","persona":"Riya","source":"media literacy"},
  {"id":"bc-018","cat":"real-vs-filtered","type":"spot","hook":"Fact or Filter: an ad promising 'fair, perfect skin in 7 days'. Spot the lie.","scene":[{"id":"a","text":"Before/after with changed lighting and edits","trick":true},{"id":"b","text":"It's a cream","trick":false},{"id":"c","text":"\"Fairer = more beautiful\"","trick":true}],"why":"Skin-tone 'before/afters' are edited, and 'fair = beautiful' is a false, harmful idea.","relearn":"Skin-lightening ads edit results and sell a false beauty standard.","persona":"Riya","source":"media literacy / colourism (India)"},
  {"id":"bc-019","cat":"real-vs-filtered","type":"spot","hook":"Fact or Filter: a celebrity magazine cover. Spot the retouching.","scene":[{"id":"a","text":"Skin airbrushed, body slimmed","trick":true},{"id":"b","text":"They're a real person","trick":false},{"id":"c","text":"Blemishes and lines erased","trick":true}],"why":"Even the people in photos don't look like their retouched photos.","relearn":"Retouched covers aren't real; not even the celebrity looks like that.","persona":"any","source":"media literacy"},
  {"id":"bc-020","cat":"real-vs-filtered","type":"spot","hook":"Spot the honest post among the filtered ones.","scene":[{"id":"a","text":"\"Filter off, here's my real skin\"","trick":false},{"id":"b","text":"A heavily smoothed glam shot","trick":true},{"id":"c","text":"A reshaped 'gym body' edit","trick":true}],"why":"The honest one names the filter; the others hide the edits.","relearn":"Honest posts admit the filter; spot the difference.","persona":"any","source":"media literacy"},
  {"id":"bc-021","cat":"real-vs-filtered","type":"sort","hook":"Sort: real, or filtered/edited?","items":[{"id":"a","text":"Pores, freckles, stray hairs"},{"id":"b","text":"Zero-pore 'glass' skin"},{"id":"c","text":"A normal in-between body"},{"id":"d","text":"An impossibly tiny waist"}],"bins":[{"id":"real","label":"Real"},{"id":"filtered","label":"Filtered"}],"key":{"a":"real","b":"filtered","c":"real","d":"filtered"},"relearn":"Real bodies have texture and variety; filters erase them.","persona":"any","source":"media literacy"},
  {"id":"bc-022","cat":"real-vs-filtered","type":"sort","hook":"Sort: makes you feel worse, or genuinely good, in your feed?","items":[{"id":"a","text":"Accounts that make you compare and feel small"},{"id":"b","text":"People who post real, varied bodies"},{"id":"c","text":"Endless 'perfect' edited bodies"},{"id":"d","text":"Things you actually enjoy"}],"bins":[{"id":"worse","label":"Unfollow / mute"},{"id":"good","label":"Keep"}],"key":{"a":"worse","b":"good","c":"worse","d":"good"},"relearn":"Curate your feed: mute what makes you compare; keep what lifts you.","persona":"Riya","source":"feed curation"},
  {"id":"bc-023","cat":"real-vs-filtered","type":"sort","hook":"Sort: a fact, or a filter-fed myth?","items":[{"id":"a","text":"\"Most posts are edited\""},{"id":"b","text":"\"Everyone else looks perfect\""},{"id":"c","text":"\"Real skin has texture\""},{"id":"d","text":"\"I'm the only normal one\""}],"bins":[{"id":"fact","label":"Fact"},{"id":"myth","label":"Myth"}],"key":{"a":"fact","b":"myth","c":"fact","d":"myth"},"relearn":"Most posts are edited; you're not 'the only normal one'.","persona":"any","source":"media literacy"},
  {"id":"bc-024","cat":"real-vs-filtered","type":"strike-rewrite","hook":"\"If I just had that filter's face/body, I'd be happy.\"","myth":{"un":"Looking like the filter would make me happy.","re":"The filter isn't real, and happiness isn't a face or a waistline.","why":"You'd be chasing something that doesn't exist."},"relearn":"Chasing a filtered look chases something that isn't real.","persona":"Riya","source":"comparison"},
  {"id":"bc-025","cat":"real-vs-filtered","type":"strike-rewrite","hook":"\"Comparing myself to influencers is harmless.\"","myth":{"un":"Comparing myself to edited influencers is harmless.","re":"Comparing your real self to edited images quietly chips at how you feel.","why":"It's an unfair, rigged comparison."},"relearn":"Comparing yourself to edited posts is a rigged, harmful game.","persona":"Veer","source":"comparison / wellbeing"},
  {"id":"bc-026","cat":"real-vs-filtered","type":"branch","hook":"Scrolling is leaving you feeling worse about your body tonight.","options":[{"text":"Put the phone down and do something kind for yourself","consequence":"The comparison spiral stops; you feel better.","outcome":"self-care","best":true},{"text":"Keep scrolling and comparing","consequence":"Stepping away beats feeding the comparison spiral."}],"debrief":"When a feed makes you feel small, stepping away is self-respect.","relearn":"If scrolling makes you feel worse, step away, that's self-care.","persona":"any","source":"feed / wellbeing"},
  {"id":"bc-027","cat":"real-vs-filtered","type":"branch","hook":"A friend posts only heavily filtered photos and seems down about it.","options":[{"text":"Gently remind them they look great unfiltered too","consequence":"You offer real support, not more pressure.","outcome":"kind","best":true},{"text":"Just like the filtered posts","consequence":"A kind, real reminder helps more than another like."}],"debrief":"Friends can free each other from the filter pressure.","relearn":"You can gently remind friends their real selves are enough.","persona":"Riya","source":"peer support"},
  // — Worth isn't looks —
  {"id":"bc-028","cat":"worth-not-looks","type":"strike-rewrite","hook":"\"My worth depends on how I look.\"","myth":{"un":"How much I'm worth depends on how I look.","re":"Your worth comes from who you are, not your appearance.","why":"Looks are the smallest part of a person."},"relearn":"Your worth isn't your looks; it's who you are.","persona":"any","source":"body neutrality / self-worth"},
  {"id":"bc-029","cat":"worth-not-looks","type":"strike-rewrite","hook":"\"Bodies are mainly for being looked at.\"","myth":{"un":"A body's main job is to look good for others.","re":"Your body is for living, moving, feeling and doing, not display.","why":"Bodies are instruments, not ornaments."},"relearn":"Your body is for living, not for being on display.","persona":"any","source":"body neutrality"},
  {"id":"bc-030","cat":"worth-not-looks","type":"strike-rewrite","hook":"\"People will only like me if I look a certain way.\"","myth":{"un":"People will only like me if I look a certain way.","re":"The people worth keeping like you for you, not your selfie.","why":"Real connection isn't about appearance."},"relearn":"The right people like you for who you are, not your looks.","persona":"Veer","source":"self-worth / relationships"},
  {"id":"bc-031","cat":"worth-not-looks","type":"strike-rewrite","hook":"\"If I don't love how I look, I've failed.\"","myth":{"un":"I must love how I look, or I've failed.","re":"You don't have to love your looks; you can respect your body and move on.","why":"Body neutrality is a kinder, realistic aim."},"relearn":"You don't have to love your looks; respecting your body is enough.","persona":"any","source":"body neutrality"},
  {"id":"bc-032","cat":"worth-not-looks","type":"reflect","hook":"Lensy: name three things you like about yourself that aren't about looks.","prompt":"Think of them.","options":["I'm kind","I'm funny","I'm a good friend","I try hard"],"affirm":"Those are the real you, and they matter far more than a mirror.","relearn":"Who you are matters far more than how you look.","persona":"any","source":"self-worth"},
  {"id":"bc-033","cat":"worth-not-looks","type":"reflect","hook":"Lensy: what does your body let you DO that you're grateful for?","prompt":"Pick one.","options":["Play and move","Hug people I love","Create things","Just be me"],"affirm":"Bodies are amazing for what they let us do, not just how they look.","relearn":"Appreciating what your body does builds a kinder body relationship.","persona":"any","source":"body functionality"},
  {"id":"bc-034","cat":"worth-not-looks","type":"reflect","hook":"Lensy: whose voice is the harshest about your body, usually yours?","prompt":"Be honest.","options":["My own","Online","Relatives","A mix"],"affirm":"Noticing the critic is the first step to turning its volume down.","relearn":"Often the harshest body critic is our own inner voice.","persona":"any","source":"self-talk"},
  {"id":"bc-035","cat":"worth-not-looks","type":"reflect","hook":"Lensy: would you talk to a friend the way you talk to yourself about your body?","prompt":"What do you think?","options":["No way","Probably not","I'll be kinder"],"affirm":"Offer yourself the kindness you'd give a good friend.","relearn":"Speak to yourself about your body as kindly as you'd speak to a friend.","persona":"any","source":"self-compassion"},
  {"id":"bc-036","cat":"worth-not-looks","type":"role-play","hook":"A relative says \"you've put on weight, careful now\".","setup":"Hold your worth. Say:","yourLine":[{"text":"\"My body's fine, and I'd rather not talk about it.\"","best":true},{"text":"\"You're right, I feel awful.\""}],"relearn":"You can set a boundary on body comments, even from relatives.","persona":"Riya","source":"boundaries / body comments (India)"},
  {"id":"bc-037","cat":"worth-not-looks","type":"role-play","hook":"Friends are all running themselves down about their bodies.","setup":"Change the script. Say:","yourLine":[{"text":"\"Our bodies are fine, can we talk about something we love?\"","best":true},{"text":"Join in the self-criticism"}],"relearn":"You can refuse to join group body-bashing.","persona":"any","source":"peer / body talk"},
  {"id":"bc-038","cat":"worth-not-looks","type":"branch","hook":"You skipped an event you'd enjoy because you felt self-conscious about your body.","options":[{"text":"Next time, go anyway; your life isn't on hold for your looks","consequence":"You live fully instead of hiding.","outcome":"freedom","best":true},{"text":"Keep skipping things until you 'look right'","consequence":"Don't put your life on hold for an impossible standard."}],"debrief":"Waiting to 'look right' to live means missing your actual life.","relearn":"Don't put living on hold for how you look.","persona":"Veer","source":"body image / living"},
  {"id":"bc-039","cat":"worth-not-looks","type":"branch","hook":"Someone compliments only your looks, never anything else about you.","options":[{"text":"Notice you'd rather be seen for more than looks","consequence":"You value the deeper compliments more.","outcome":"insight","best":true},{"text":"Decide looks are all that matter","consequence":"You're far more than your appearance; seek to be seen fully."}],"debrief":"Being valued only for looks is thin; you're worth being known.","relearn":"You deserve to be valued for more than your appearance.","persona":"any","source":"self-worth"},
  {"id":"bc-040","cat":"worth-not-looks","type":"build","hook":"Build your 'I am more than a body' list.","prompt":"Add what makes you, you.","pieces":["my sense of humour","how I treat people","what I'm curious about","what I'm good at"],"mode":"assemble","key":["my sense of humour","how I treat people","what I'm curious about","what I'm good at"],"relearn":"You're a whole person; looks are just one small part.","persona":"any","source":"self-worth"},
  {"id":"bc-041","cat":"worth-not-looks","type":"build","hook":"Build a kinder inner-voice swap.","prompt":"Swap each harsh line for a kind, true one.","pieces":["'I look awful' -> 'I'm having a hard body day, and that passes'","'I'm not enough' -> 'I'm enough as I am'","'everyone's judging me' -> 'most people are busy with themselves'"],"mode":"assemble","key":["'I look awful' -> 'I'm having a hard body day, and that passes'","'I'm not enough' -> 'I'm enough as I am'","'everyone's judging me' -> 'most people are busy with themselves'"],"relearn":"You can swap harsh body self-talk for kinder, truer lines.","persona":"any","source":"self-compassion"},
  // — Bust the beauty myths —
  {"id":"bc-042","cat":"beauty-myths","type":"strike-rewrite","hook":"\"There's one ideal body everyone should aim for.\"","myth":{"un":"There's a single ideal body everyone should have.","re":"There is no one ideal body; healthy bodies come in huge variety.","why":"'Ideal bodies' are invented and keep changing."},"relearn":"There's no single ideal body; variety is the reality.","persona":"any","source":"beauty myths"},
  {"id":"bc-043","cat":"beauty-myths","type":"strike-rewrite","hook":"\"Fairer skin is more beautiful.\"","myth":{"un":"Fair skin is more beautiful or better.","re":"Every skin tone is beautiful; 'fair is better' is a harmful myth.","why":"Colourism is a prejudice, not a fact."},"relearn":"Every skin tone is beautiful; 'fair is better' is a harmful myth.","persona":"Riya","source":"colourism (India)"},
  {"id":"bc-044","cat":"beauty-myths","type":"strike-rewrite","hook":"\"Skin-lightening creams make you better.\"","myth":{"un":"Skin-lightening products improve you.","re":"They can harm your skin and health and sell a false standard.","why":"You don't need 'fixing'; the standard is the problem."},"relearn":"Skin-lightening sells a false, harmful standard; your skin is good.","persona":"Riya","source":"colourism / health (India)"},
  {"id":"bc-045","cat":"beauty-myths","type":"strike-rewrite","hook":"\"Real men are big and muscular.\"","myth":{"un":"A real man has to be big and muscular.","re":"Bodies of every build are fine; manhood isn't a body type.","why":"The 'muscular = man' ideal pressures boys too."},"relearn":"Manhood isn't a body type; every build is fine.","persona":"Veer","source":"male body image"},
  {"id":"bc-046","cat":"beauty-myths","type":"strike-rewrite","hook":"\"Being tall is necessary to be attractive or respected.\"","myth":{"un":"You must be tall to be attractive or respected.","re":"Height doesn't decide your worth or respect.","why":"This is just another impossible body rule."},"relearn":"Your height doesn't decide your worth or respect.","persona":"Veer","source":"male body image"},
  {"id":"bc-047","cat":"beauty-myths","type":"strike-rewrite","hook":"\"Thin always means healthy and beautiful.\"","myth":{"un":"Thin always means healthy and beautiful.","re":"Health and beauty come in many shapes; thinness isn't a measure of either.","why":"Equating thin with healthy is false and harmful."},"relearn":"Thin doesn't equal healthy or beautiful; bodies vary.","persona":"Riya","source":"beauty myths / wellbeing"},
  {"id":"bc-048","cat":"beauty-myths","type":"strike-rewrite","hook":"\"Beauty standards have always been the same.\"","myth":{"un":"Beauty standards are fixed and timeless.","re":"Beauty 'ideals' change wildly by era and place, they're invented.","why":"What's 'ideal' is fashion, not truth."},"relearn":"Beauty standards are invented and keep changing.","persona":"any","source":"media literacy / history"},
  {"id":"bc-049","cat":"beauty-myths","type":"strike-rewrite","hook":"\"Companies just want me to look my best.\"","myth":{"un":"Beauty brands only want me to look my best.","re":"Many profit by making you feel not-good-enough first.","why":"Insecurity sells products."},"relearn":"Some brands manufacture insecurity to sell you the 'fix'.","persona":"any","source":"media literacy / marketing"},
  {"id":"bc-050","cat":"beauty-myths","type":"sort","hook":"Sort: a real health signal, or just a beauty myth?","items":[{"id":"a","text":"Energy and feeling well"},{"id":"b","text":"A number on a scale"},{"id":"c","text":"Sleeping and eating enough"},{"id":"d","text":"Having a 'thigh gap'"}],"bins":[{"id":"health","label":"Real health"},{"id":"myth","label":"Beauty myth"}],"key":{"a":"health","b":"myth","c":"health","d":"myth"},"relearn":"Real health is energy and care, not beauty-myth markers.","persona":"any","source":"health vs beauty myth"},
  {"id":"bc-051","cat":"beauty-myths","type":"sort","hook":"Sort: breaks a beauty myth, or repeats one?","items":[{"id":"a","text":"A model with vitiligo or a scar"},{"id":"b","text":"\"Only fair skin is pretty\""},{"id":"c","text":"All body types in an ad"},{"id":"d","text":"\"Bigger muscles = better man\""}],"bins":[{"id":"breaks","label":"Breaks the myth"},{"id":"repeats","label":"Repeats it"}],"key":{"a":"breaks","b":"repeats","c":"breaks","d":"repeats"},"relearn":"Real diversity breaks beauty myths; narrow 'ideals' repeat them.","persona":"any","source":"beauty myths"},
  {"id":"bc-052","cat":"beauty-myths","type":"sort","hook":"Sort: who decides what's beautiful?","items":[{"id":"a","text":"Ad companies chasing profit"},{"id":"b","text":"Old prejudices like colourism"},{"id":"c","text":"You, for yourself"},{"id":"d","text":"Filters and trends"}],"bins":[{"id":"outside","label":"Outside pressure"},{"id":"you","label":"You get a say"}],"key":{"a":"outside","b":"outside","c":"you","d":"outside"},"relearn":"You don't have to accept beauty 'rules' set by ads and prejudice.","persona":"any","source":"agency"},
  {"id":"bc-053","cat":"beauty-myths","type":"spot","hook":"Spot the colourism hidden in a 'beauty' post.","scene":[{"id":"a","text":"Only fair-skinned faces shown as 'beautiful'","trick":true},{"id":"b","text":"It's a makeup brand","trick":false},{"id":"c","text":"\"Get fairer to get noticed\"","trick":true}],"why":"Showing only fair skin and 'get fairer' messaging is colourism.","relearn":"Spot colourism: only-fair 'beauty' and 'get fairer' messages.","persona":"Riya","source":"colourism (India)"},
  {"id":"bc-054","cat":"beauty-myths","type":"spot","hook":"Spot the male body-pressure hidden in a post.","scene":[{"id":"a","text":"\"No abs, no respect\"","trick":true},{"id":"b","text":"A workout clip","trick":false},{"id":"c","text":"\"Real men look like this\"","trick":true}],"why":"'No abs, no respect' and 'real men look like this' pressure boys' bodies.","relearn":"Boys face body pressure too; spot the 'real men look like this' trap.","persona":"Veer","source":"male body image"},
  {"id":"bc-055","cat":"beauty-myths","type":"reflect","hook":"Lensy: if beauty standards are invented, do you have to obey them?","prompt":"What do you think?","options":["No","I can opt out","Good point"],"affirm":"You can step out of a game that was rigged to make you feel less.","relearn":"You can opt out of invented beauty standards.","persona":"any","source":"agency"},
  {"id":"bc-056","cat":"beauty-myths","type":"reflect","hook":"Lensy: imagine the kindest thing you'd tell a younger kid about their looks. Say it to you?","prompt":"What do you think?","options":["I can try","They'd deserve kindness","So do I"],"affirm":"You deserve the same kindness you'd give a younger kid.","relearn":"Give yourself the body-kindness you'd give a younger child.","persona":"any","source":"self-compassion"},
  {"id":"bc-057","cat":"beauty-myths","type":"reflect","hook":"Lensy: who in real life do you admire for something other than their looks?","prompt":"Think of someone.","options":["For their kindness","For their talent","For their courage","For their humour"],"affirm":"That's what truly draws us to people, and what draws them to you.","relearn":"We admire people for who they are, not just how they look.","persona":"any","source":"values"},
  // — Care, don't 'fix' —
  {"id":"bc-058","cat":"care-not-fix","type":"sort","hook":"Sort: caring for your body, or 'fixing' it to a standard?","items":[{"id":"a","text":"Sleeping enough"},{"id":"b","text":"Starving to look thinner"},{"id":"c","text":"Eating enough to feel good"},{"id":"d","text":"Over-exercising to punish your body"}],"bins":[{"id":"care","label":"Caring for it"},{"id":"fix","label":"'Fixing' / harming"}],"key":{"a":"care","b":"fix","c":"care","d":"fix"},"relearn":"Care nourishes your body; 'fixing' to a standard can harm it.","persona":"any","source":"body neutrality / safeguarding"},
  {"id":"bc-059","cat":"care-not-fix","type":"sort","hook":"Sort: a reason to move your body that's kind, or pressuring?","items":[{"id":"a","text":"Because it feels good and fun"},{"id":"b","text":"To punish yourself for eating"},{"id":"c","text":"For energy and health"},{"id":"d","text":"To force a 'perfect' body"}],"bins":[{"id":"kind","label":"Kind reason"},{"id":"pressure","label":"Pressuring reason"}],"key":{"a":"kind","b":"pressure","c":"kind","d":"pressure"},"relearn":"Move because it feels good and healthy, not as punishment.","persona":"Veer","source":"movement / wellbeing"},
  {"id":"bc-060","cat":"care-not-fix","type":"sort","hook":"Sort: food thoughts that are healthy, or harmful?","items":[{"id":"a","text":"\"Food is fuel and joy\""},{"id":"b","text":"\"I must skip meals to look right\""},{"id":"c","text":"\"All foods can fit\""},{"id":"d","text":"\"I should feel guilty for eating\""}],"bins":[{"id":"healthy","label":"Healthy"},{"id":"harmful","label":"Harmful"}],"key":{"a":"healthy","b":"harmful","c":"healthy","d":"harmful"},"relearn":"Food is fuel and joy; guilt and skipping meals are harmful.","persona":"any","source":"eating / safeguarding"},
  {"id":"bc-061","cat":"care-not-fix","type":"strike-rewrite","hook":"\"Skipping meals is a good way to look better.\"","myth":{"un":"Skipping meals is a smart way to change my body.","re":"Skipping meals harms your health and mood; your body needs fuel.","why":"Under-eating is dangerous, not clever."},"relearn":"Skipping meals harms you; your body needs regular fuel.","persona":"any","source":"eating / safeguarding"},
  {"id":"bc-062","cat":"care-not-fix","type":"strike-rewrite","hook":"\"Exercise is punishment for what you eat.\"","myth":{"un":"Exercise is a punishment to 'earn' or 'burn off' food.","re":"Movement is for feeling strong and well, not punishment.","why":"Punishing your body isn't care."},"relearn":"Movement is care and joy, not punishment for eating.","persona":"Veer","source":"movement / wellbeing"},
  {"id":"bc-063","cat":"care-not-fix","type":"build","hook":"Build a kind body-care routine (care, not 'fix').","prompt":"Pick care habits.","pieces":["sleep enough","eat regularly and enough","move in ways you enjoy","rest without guilt"],"mode":"assemble","key":["sleep enough","eat regularly and enough","move in ways you enjoy","rest without guilt"],"relearn":"Real body care: sleep, eat enough, move for joy, rest without guilt.","persona":"any","source":"self-care"},
  {"id":"bc-064","cat":"care-not-fix","type":"build","hook":"Build a 'feed clean-up' plan for kinder scrolling.","prompt":"Order steps to a kinder feed.","pieces":["notice who makes you feel small","mute or unfollow them","follow real, varied, kind accounts","check how you feel after a week"],"mode":"sequence","key":["notice who makes you feel small","mute or unfollow them","follow real, varied, kind accounts","check how you feel after a week"],"relearn":"Curate your feed so it supports, not shrinks, you.","persona":"Riya","source":"feed curation"},
  {"id":"bc-065","cat":"care-not-fix","type":"branch","hook":"A trend pushes a risky 'glow-up' challenge (extreme diet or product).","options":[{"text":"Skip it; check facts with a trusted adult or doctor","consequence":"You avoid harm and get real guidance.","outcome":"safe","best":true},{"text":"Try it to keep up","consequence":"Risky trends can harm you; check with a trusted adult first."}],"debrief":"Risky 'glow-up' trends can hurt your body; verify before trying.","relearn":"Skip risky body trends; check facts with a trusted adult or doctor.","persona":"any","source":"safeguarding"},
  {"id":"bc-066","cat":"care-not-fix","type":"branch","hook":"You want to get fitter, and you're not sure how to do it healthily.","options":[{"text":"Ask a doctor, coach or trusted adult for a healthy plan","consequence":"You get safe, real guidance.","outcome":"healthy","best":true},{"text":"Copy an extreme influencer routine","consequence":"A trusted adult or coach beats an extreme online routine."}],"debrief":"For real fitness, trusted guidance beats extreme online plans.","relearn":"Get healthy-body guidance from trusted people, not extreme influencers.","persona":"Veer","source":"help-seeking / health"},
  {"id":"bc-067","cat":"care-not-fix","type":"spot","hook":"Spot the healthy self-care among the harmful 'fixes'.","scene":[{"id":"a","text":"Getting enough sleep","trick":false},{"id":"b","text":"A crash diet from a reel","trick":true},{"id":"c","text":"A 'detox tea' that skips meals","trick":true}],"why":"Sleep is care; crash diets and 'detox' meal-skipping are harmful fixes.","relearn":"Sleep and rest are care; crash diets and 'detoxes' are harmful.","persona":"any","source":"safeguarding"},
  {"id":"bc-068","cat":"care-not-fix","type":"spot","hook":"Spot the kind, doable habit (not a punishing one).","scene":[{"id":"a","text":"A walk you enjoy","trick":false},{"id":"b","text":"\"No food till you've burned 1000 calories\"","trick":true},{"id":"c","text":"\"Earn your dinner\"","trick":true}],"why":"Enjoyable movement is kind; 'earn/burn' rules turn care into punishment.","relearn":"Kind habits feel good; 'earn/burn your food' rules are harmful.","persona":"any","source":"movement / wellbeing"},
  {"id":"bc-069","cat":"care-not-fix","type":"reflect","hook":"Lensy: what's one kind thing you could do for your body today, no 'fixing'?","prompt":"Pick one.","options":["Sleep well","Eat a proper meal","Move for fun","Rest"],"affirm":"Small acts of care add up to a kinder body relationship.","relearn":"Caring for your body daily beats trying to 'fix' it.","persona":"any","source":"self-care"},
  // — When it gets heavy —
  {"id":"bc-070","cat":"when-heavy","type":"branch","hook":"Body thoughts are taking up more and more of your day.","options":[{"text":"Talk to a trusted adult or school counsellor about it","consequence":"You get support before it grows.","outcome":"supported","best":true},{"text":"Keep it all to yourself","consequence":"Heavy body thoughts ease when you share them with someone safe."}],"debrief":"If body worries fill your days, that's a sign to reach out.","relearn":"Persistent body worries deserve a trusted adult or counsellor.","persona":"Counsellor","source":"safeguarding / help-seeking"},
  {"id":"bc-071","cat":"when-heavy","type":"branch","hook":"You notice yourself skipping meals or over-exercising to change your body.","options":[{"text":"Tell a trusted adult or doctor, this matters and help exists","consequence":"You get care early, when it helps most.","outcome":"supported","best":true},{"text":"Hide it and push harder","consequence":"These are signs to get support from a trusted adult or doctor."}],"debrief":"Skipping meals or over-exercising to change your body are signs to get help.","relearn":"If you're skipping meals or over-exercising, tell a trusted adult or doctor.","persona":"Counsellor","source":"eating-disorder safeguarding"},
  {"id":"bc-072","cat":"when-heavy","type":"branch","hook":"A friend confides they feel terrible about their body, maybe not eating.","options":[{"text":"Listen kindly and help them reach a trusted adult","consequence":"You support them and bring in real help.","outcome":"caring","best":true},{"text":"Tell them to just 'get over it'","consequence":"Listen, then help them reach a trusted adult, this is real."}],"debrief":"For a friend struggling with eating or body image, listen and route to help.","relearn":"Support a struggling friend and help them reach a trusted adult.","persona":"any","source":"peer support / safeguarding"},
  {"id":"bc-073","cat":"when-heavy","type":"role-play","hook":"You want to open up about feeling bad about your body.","setup":"Start the conversation. Say:","yourLine":[{"text":"\"I've been feeling really down about my body, can we talk?\"","best":true},{"text":"Say nothing and keep struggling"}],"relearn":"You can name body distress and ask a trusted person to talk.","persona":"any","source":"help-seeking"},
  {"id":"bc-074","cat":"when-heavy","type":"role-play","hook":"A counsellor asks how you've been feeling about yourself.","setup":"Be honest. Say:","yourLine":[{"text":"\"Honestly, not great about how I look lately.\"","best":true},{"text":"\"I'm fine\" (when you're not)"}],"relearn":"Being honest with a counsellor lets them actually help.","persona":"Counsellor","source":"help-seeking"},
  {"id":"bc-075","cat":"when-heavy","type":"role-play","hook":"Friends keep up a stream of body-shaming 'banter'.","setup":"Set the tone. Say:","yourLine":[{"text":"\"Let's not do the body-shaming thing, even as a joke.\"","best":true},{"text":"Join in so you fit in"}],"relearn":"You can call time on body-shaming 'banter'.","persona":"Veer","source":"peer / body talk"},
  {"id":"bc-076","cat":"when-heavy","type":"role-play","hook":"An adult brushes off your body worry as 'just a phase'.","setup":"Advocate for yourself. Say:","yourLine":[{"text":"\"It's really affecting me, I'd like some help with it.\"","best":true},{"text":"Drop it and feel unheard"}],"relearn":"If one adult dismisses your worry, restate it or tell another.","persona":"any","source":"help-seeking / persistence"},
  {"id":"bc-077","cat":"when-heavy","type":"role-play","hook":"You're supporting a friend to tell an adult about their eating.","setup":"Encourage them. Say:","yourLine":[{"text":"\"I'll come with you, you don't have to do this alone.\"","best":true},{"text":"\"Just deal with it yourself.\""}],"relearn":"Going with a friend makes reaching out far easier.","persona":"any","source":"peer support"},
  {"id":"bc-078","cat":"when-heavy","type":"strike-rewrite","hook":"\"Struggling with body image means I'm vain or weak.\"","myth":{"un":"Struggling with body image makes me vain or weak.","re":"It's incredibly common, and reaching out is strong.","why":"The pressure is huge; you're not weak for feeling it."},"relearn":"Body-image struggles are common; getting help is strong.","persona":"any","source":"de-stigmatise"},
  {"id":"bc-079","cat":"when-heavy","type":"strike-rewrite","hook":"\"Boys don't get body-image problems.\"","myth":{"un":"Boys don't struggle with body image.","re":"Boys face real body pressure too, around muscles, height and more.","why":"Body image isn't only a girls' issue."},"relearn":"Boys get body-image pressure too; it's okay to talk about it.","persona":"Veer","source":"male body image / de-stigmatise"},
  {"id":"bc-080","cat":"when-heavy","type":"reflect","hook":"Lensy: hard body days happen to everyone, and they pass. Reassuring?","prompt":"What do you think?","options":["Yes","They do pass","Good to remember"],"affirm":"A hard body day is a day, not a verdict, and it passes.","relearn":"Hard body days are normal and they pass.","persona":"any","source":"normalising"},
  {"id":"bc-081","cat":"when-heavy","type":"reflect","hook":"Lensy: who is one safe person you could talk to if body worries got heavy?","prompt":"Think of one.","options":["A parent","A counsellor","A doctor","An older sibling"],"affirm":"Good, knowing your person means you're never alone with it.","relearn":"Knowing your safe person means help is always within reach.","persona":"any","source":"help-seeking"},
  {"id":"bc-082","cat":"when-heavy","type":"sort","hook":"Sort: a sign to reach out for help, or an ordinary off-day?","items":[{"id":"a","text":"Body thoughts most of the day, most days"},{"id":"b","text":"One 'meh' day about a photo"},{"id":"c","text":"Skipping meals to change your body"},{"id":"d","text":"Wishing your hair behaved today"}],"bins":[{"id":"reach","label":"Reach out"},{"id":"ordinary","label":"Ordinary off-day"}],"key":{"a":"reach","b":"ordinary","c":"reach","d":"ordinary"},"relearn":"Daily body distress or skipping meals are signs to reach out.","persona":"Counsellor","source":"safeguarding"},
  {"id":"bc-083","cat":"when-heavy","type":"reflect","hook":"Lensy: biggest take-away from Body Confident?","prompt":"Pick your motto.","options":["My body is mine and good","Spot the filter","I'm more than my looks","Care, don't 'fix'"],"affirm":"Hold onto that, it's the steady ground under all the noise.","relearn":"Your body is yours and good; spot the filter; you're more than looks.","persona":"any","source":"consolidation"},
  {"id":"bc-084","cat":"when-heavy","type":"reflect","hook":"Lensy: can you give your body a little credit today, just as it is?","prompt":"What do you think?","options":["Yes","I'll try","It's done a lot for me"],"affirm":"That's body confidence, not loving every inch, just respecting the body that's yours.","relearn":"Body confidence is respecting your body as it is, today.","persona":"any","source":"body neutrality"},
];

export const BODY_CONFIDENT: V2GameConfig = {
  gameId: "body-confident",
  title: "Body Confident",
  greet: "Hey, it's Lensy. 🪞 Bodies are still changing at this age, and the internet is full of filters and 'rules' about how you should look. Let's spot what's fake, bust the beauty myths, and remember your worth was never about your looks.",
  scenarios: SCENARIOS,
  categories: [
    { id: "changing-body", emoji: "🌱", label: "Changing body" },
    { id: "real-vs-filtered", emoji: "📸", label: "Real vs filtered" },
    { id: "worth-not-looks", emoji: "💎", label: "Worth isn't looks" },
    { id: "beauty-myths", emoji: "🪞", label: "Beauty myths" },
    { id: "care-not-fix", emoji: "💚", label: "Care, don't 'fix'" },
    { id: "when-heavy", emoji: "🤝", label: "When it gets heavy" },
  ],
  badge: {
    title: "Body Confident! 🪞",
    blurb: "You can spot a filter, bust the beauty myths (including colourism), care for your body instead of 'fixing' it, and untie your worth from your looks — and if body worries get heavy, you know to reach out. 💎",
  },
  helpLine: "If worries about your body or eating start filling your days, please talk to someone you trust, a parent, a teacher, a school counsellor or a doctor. You can also call Childline, one-zero-nine-eight. Reaching out is strong, and help really works.",
  helpLabel: "Get support · Childline 1098",
  reassure: "A hard body day is a day, not a verdict, and it passes. If heavy body or eating worries stick around, that's not vanity or weakness, it's a sign to reach out to a trusted adult, counsellor or doctor. 💛",
  reassureCats: ["when-heavy"],
  buildLabels: { assemble: "That feels kind 💛", sequence: "That's the kinder way ✨" },
};
