// Content for Bounce (node g39, ages 12–15, Chapter 4) — NEW v2 build to GDD 39 (mechanic-embodying), the
// resilience + stress + teen-mental-health node (Thread C · Feelings & Life Skills). "Bounce back, the real
// way." 84 researched, India-grounded scenarios across the what-resilience → reframe-setback → bounce-toolkit
// → exam-pressure → support-friend → reach-out arc, each encoded as one of the shared v2 play actions (branch /
// strike-rewrite / role-play / reflect / sort / build / match) — no binary "tap the right card". Lead
// mechanics: branch (choose the move that actually helps ×19), strike-rewrite (bust the resilience myth ×17),
// role-play (say the brave words ×12). Teaches: real resilience (not toughing-it-out or toxic positivity),
// reframing a real setback, a coping toolkit that's REAL not a poster, exam/performance pressure, being there
// for a struggling friend, and when + how to reach out. WELLBEING-SAFE: no toxic positivity, no pain-based
// coping; persistent distress and any dark thoughts route FIRMLY to a trusted adult, **Tele-MANAS 14416**, or
// **Childline 1098 / 112** (crisis-routing first, never therapy). Builds on g38 (Mind Matters); prereq g21.
// Rendered by the shared engine (components/games/v2-engine.tsx). gameId "bounce". DO NOT RENAME.

import type { Scenario, V2GameConfig } from "./v2-schema";

const SCENARIOS: Scenario[] = [
  // — What resilience really is —
  {"id":"bn-001","cat":"what-resilience","type":"strike-rewrite","hook":"\"Resilient people just don't feel bad when things go wrong.\"","myth":{"un":"Being resilient means not feeling bad when things go wrong.","re":"Resilience is feeling the hurt and then finding a way through, not skipping it.","why":"You can't bounce back from something you won't let yourself feel."},"relearn":"Resilience is moving through hard feelings, not avoiding them.","persona":"Veer","source":"resilience concept"},
  {"id":"bn-002","cat":"what-resilience","type":"strike-rewrite","hook":"\"Just think positive and you'll be fine.\"","myth":{"un":"You just have to think positive and you'll be fine.","re":"Forcing 'positive' ignores real feelings; honest coping works better.","why":"Toxic positivity buries problems instead of solving them."},"relearn":"Honest coping beats forced positivity; it's okay to not be okay.","persona":"any","source":"anti-toxic-positivity"},
  {"id":"bn-003","cat":"what-resilience","type":"strike-rewrite","hook":"\"Bouncing back should be instant.\"","myth":{"un":"If you're strong, you bounce back instantly.","re":"Recovery takes time; bouncing back is a process, not a switch.","why":"Healing on a timer isn't how people actually work."},"relearn":"Bouncing back takes time; it's a process, not a switch.","persona":"Riya","source":"resilience concept"},
  {"id":"bn-004","cat":"what-resilience","type":"strike-rewrite","hook":"\"Some people are just born resilient and others aren't.\"","myth":{"un":"Resilience is something you're born with or not.","re":"Resilience is a skill anyone can build with practice and support.","why":"It grows; it isn't fixed."},"relearn":"Resilience is a skill you can build, not a fixed trait.","persona":"any","source":"resilience is learnable"},
  {"id":"bn-005","cat":"what-resilience","type":"strike-rewrite","hook":"\"Needing other people means you're not really resilient.\"","myth":{"un":"Truly resilient people don't need anyone.","re":"Leaning on caring people is one of the biggest sources of resilience.","why":"At least one supportive relationship is a top protective factor."},"relearn":"Leaning on others is a core part of resilience, not a weakness.","persona":"Veer","source":"supportive relationships (evidence)"},
  {"id":"bn-006","cat":"what-resilience","type":"reflect","hook":"Lensy: think of a hard thing you got through before. You bounced once, you can again. Feel that?","prompt":"What do you think?","options":["Yes","I have done hard things","I'm stronger than I feel"],"affirm":"Past bounce-backs are real proof of what you can do.","relearn":"Remembering past recoveries is evidence you can cope again.","persona":"any","source":"self-efficacy"},
  {"id":"bn-007","cat":"what-resilience","type":"reflect","hook":"Lensy: 'coping that's real, not a poster' means honest, doable, yours. Like that?","prompt":"What do you think?","options":["Yes","Real over slogans","That helps"],"affirm":"Real coping fits your actual life, not a motivational poster.","relearn":"Real resilience is honest and doable, not a slogan.","persona":"Veer","source":"authenticity"},
  {"id":"bn-008","cat":"what-resilience","type":"reflect","hook":"Lensy: setbacks are part of every worthwhile life, not a sign you've failed at life. Agree?","prompt":"What do you think?","options":["Yes","Everyone has them","Less alone now"],"affirm":"Setbacks are universal; they're a comma, not a full stop.","relearn":"Setbacks are a normal part of life, not proof you've failed.","persona":"any","source":"normalising"},
  {"id":"bn-009","cat":"what-resilience","type":"sort","hook":"Sort: real resilience, or toxic positivity?","items":[{"id":"a","text":"\"This is hard, and I'll get through it\""},{"id":"b","text":"\"Just be happy, ignore it\""},{"id":"c","text":"\"I'll feel this, then make a plan\""},{"id":"d","text":"\"Good vibes only, no sad stuff\""}],"bins":[{"id":"real","label":"Real resilience"},{"id":"toxic","label":"Toxic positivity"}],"key":{"a":"real","b":"toxic","c":"real","d":"toxic"},"relearn":"Real resilience allows hard feelings; toxic positivity bans them.","persona":"any","source":"anti-toxic-positivity"},
  {"id":"bn-010","cat":"what-resilience","type":"sort","hook":"Sort: builds resilience, or chips at it?","items":[{"id":"a","text":"A caring person to talk to"},{"id":"b","text":"Bottling everything up"},{"id":"c","text":"Reframing a failure as learning"},{"id":"d","text":"Harsh self-blame"}],"bins":[{"id":"builds","label":"Builds it"},{"id":"chips","label":"Chips at it"}],"key":{"a":"builds","b":"chips","c":"builds","d":"chips"},"relearn":"Support and reframing build resilience; bottling up and self-blame erode it.","persona":"any","source":"resilience factors"},
  {"id":"bn-011","cat":"what-resilience","type":"sort","hook":"Sort: a setback you can grow from, or proof you're worthless?","items":[{"id":"a","text":"A failed test"},{"id":"b","text":"\"So I'm worthless\""},{"id":"c","text":"A rejection"},{"id":"d","text":"\"I'll never be good enough\""}],"bins":[{"id":"grow","label":"Setback to grow from"},{"id":"false","label":"False, harsh story"}],"key":{"a":"grow","b":"false","c":"grow","d":"false"},"relearn":"A setback is a setback; 'I'm worthless' is a false story.","persona":"Riya","source":"cognitive"},
  {"id":"bn-012","cat":"what-resilience","type":"match","hook":"Match the resilience ingredient to what it gives you.","pairs":[{"left":"Growth mindset","right":"Keep trying after a flop"},{"left":"A caring person","right":"You're not alone"},{"left":"Small steps","right":"A way forward"}],"relearn":"Resilience is built from mindset, support and small steps.","persona":"any","source":"resilience factors"},
  // — Reframe the setback —
  {"id":"bn-013","cat":"reframe-setback","type":"strike-rewrite","hook":"\"Failing means I'm a failure.\"","myth":{"un":"If I fail at something, I am a failure.","re":"Failing at a thing is an event, not your identity.","why":"What you do isn't all of who you are."},"relearn":"Failing at something doesn't make you 'a failure'.","persona":"Veer","source":"growth mindset"},
  {"id":"bn-014","cat":"reframe-setback","type":"strike-rewrite","hook":"\"If I can't do it, that's final.\"","myth":{"un":"I can't do it, full stop.","re":"You can't do it yet, with practice that can change.","why":"'Yet' keeps the door open."},"relearn":"Add 'yet': 'I can't do it yet' keeps growth possible.","persona":"any","source":"growth mindset ('not yet')"},
  {"id":"bn-015","cat":"reframe-setback","type":"strike-rewrite","hook":"\"A mistake is wasted, there's nothing good in it.\"","myth":{"un":"A mistake is just a waste.","re":"A mistake is data, it shows you what to try differently.","why":"Most learning is built on mistakes."},"relearn":"A mistake is useful data for next time, not a waste.","persona":"any","source":"failure as learning"},
  {"id":"bn-016","cat":"reframe-setback","type":"strike-rewrite","hook":"\"Everyone saw me fail; I can never recover from the shame.\"","myth":{"un":"People saw me fail, so I'll never live it down.","re":"People forget far faster than you fear; this will pass.","why":"Others are mostly focused on themselves."},"relearn":"Public stumbles fade fast; you will live it down.","persona":"Riya","source":"spotlight effect"},
  {"id":"bn-017","cat":"reframe-setback","type":"strike-rewrite","hook":"\"One bad result ruins my whole future.\"","myth":{"un":"One bad result ruins my entire future.","re":"One result is one moment; there are many paths forward.","why":"Lives rarely turn on a single score."},"relearn":"One bad result doesn't decide your whole future.","persona":"Veer","source":"exam pressure / reframe"},
  {"id":"bn-018","cat":"reframe-setback","type":"strike-rewrite","hook":"\"If I reframe it, I'm just pretending it doesn't hurt.\"","myth":{"un":"Reframing means pretending it doesn't hurt.","re":"Reframing holds both: it hurts, and there's a way forward.","why":"You can be honest and hopeful at once."},"relearn":"Reframing isn't denial; it holds the hurt and the hope together.","persona":"any","source":"reframing vs denial"},
  {"id":"bn-019","cat":"reframe-setback","type":"branch","hook":"You bombed a test you studied hard for.","options":[{"text":"Let yourself be gutted, then look at what to change","consequence":"You feel it, learn from it, and move on stronger.","outcome":"resilient","best":true},{"text":"Decide you're hopeless and stop trying","consequence":"Feel it, then treat it as data, you're not hopeless."}],"debrief":"Feel the disappointment, then mine it for what to do differently.","relearn":"Feel the setback, then turn it into a lesson.","persona":"Veer","source":"bounce-back"},
  {"id":"bn-020","cat":"reframe-setback","type":"branch","hook":"You didn't make the team or the role you wanted.","options":[{"text":"Grieve it, then look for the next chance or a new path","consequence":"You stay open instead of shutting down.","outcome":"open","best":true},{"text":"Give up on the whole thing","consequence":"A 'no' can redirect you; stay open to the next chance."}],"debrief":"A closed door can point you to a different, good one.","relearn":"A rejection can redirect you; keep looking forward.","persona":"Riya","source":"reframe"},
  {"id":"bn-021","cat":"reframe-setback","type":"branch","hook":"You're stuck replaying a mistake on a loop.","options":[{"text":"Name one lesson, then deliberately shift your focus","consequence":"You break the loop and free up your mind.","outcome":"unstuck","best":true},{"text":"Keep replaying it endlessly","consequence":"Pull one lesson, then redirect; looping just hurts."}],"debrief":"Take the lesson, then choose to put the loop down.","relearn":"Extract the lesson, then deliberately stop the replay.","persona":"any","source":"rumination"},
  {"id":"bn-022","cat":"reframe-setback","type":"branch","hook":"A friend nails what you struggled with, and envy stings.","options":[{"text":"Let it teach you, ask how they did it, run your own race","consequence":"Envy becomes information and motivation.","outcome":"growth","best":true},{"text":"Spiral into 'I'm worse than everyone'","consequence":"Turn envy into a question, not a verdict on you."}],"debrief":"Envy can point to what you want; use it, don't drown in it.","relearn":"Turn envy into curiosity and your own next step.","persona":"Riya","source":"comparison / growth"},
  {"id":"bn-023","cat":"reframe-setback","type":"reflect","hook":"Lensy: what's one setback that, looking back, taught you something useful?","prompt":"Think of one.","options":["A failure that taught me","A loss that grew me","A mistake I learned from"],"affirm":"That's resilience in your own history, proof it works.","relearn":"Past setbacks often became lessons; this one can too.","persona":"any","source":"reframing"},
  {"id":"bn-024","cat":"reframe-setback","type":"reflect","hook":"Lensy: would you judge a friend as harshly for this as you're judging yourself?","prompt":"What do you think?","options":["No","I'd be kinder to them","I'll be kinder to me"],"affirm":"Offer yourself the same grace you'd give a friend.","relearn":"Be as fair to yourself after a setback as you'd be to a friend.","persona":"any","source":"self-compassion"},
  {"id":"bn-025","cat":"reframe-setback","type":"sort","hook":"Sort: a growth-mindset thought, or a fixed one?","items":[{"id":"a","text":"\"I can improve with practice\""},{"id":"b","text":"\"I'm just bad at this, always\""},{"id":"c","text":"\"Mistakes help me learn\""},{"id":"d","text":"\"Smart people never struggle\""}],"bins":[{"id":"growth","label":"Growth mindset"},{"id":"fixed","label":"Fixed mindset"}],"key":{"a":"growth","b":"fixed","c":"growth","d":"fixed"},"relearn":"Growth-mindset thoughts keep you trying; fixed ones stop you.","persona":"any","source":"growth mindset"},
  {"id":"bn-026","cat":"reframe-setback","type":"sort","hook":"Sort: helps you bounce, or keeps you down?","items":[{"id":"a","text":"\"What can I learn here?\""},{"id":"b","text":"\"I always ruin everything\""},{"id":"c","text":"\"This is hard but temporary\""},{"id":"d","text":"\"It'll be like this forever\""}],"bins":[{"id":"bounce","label":"Helps you bounce"},{"id":"down","label":"Keeps you down"}],"key":{"a":"bounce","b":"down","c":"bounce","d":"down"},"relearn":"'What can I learn' and 'this is temporary' help you bounce back.","persona":"any","source":"cognitive reframing"},
  // — The bounce-back toolkit —
  {"id":"bn-027","cat":"bounce-toolkit","type":"build","hook":"Build your bounce-back routine after a knock.","prompt":"Order the steps that actually help.","pieces":["let yourself feel it","talk to someone you trust","find one lesson","take one small next step"],"mode":"sequence","key":["let yourself feel it","talk to someone you trust","find one lesson","take one small next step"],"relearn":"Bounce back: feel it, talk it out, find the lesson, take one step.","persona":"any","source":"bounce-back process"},
  {"id":"bn-028","cat":"bounce-toolkit","type":"build","hook":"Build a 'shrink the comeback' plan for a big goal you slipped on.","prompt":"Break it into doable steps.","pieces":["name the goal again","break it into small parts","do the first small part today","celebrate that small win"],"mode":"sequence","key":["name the goal again","break it into small parts","do the first small part today","celebrate that small win"],"relearn":"Comebacks are built from small steps and small wins.","persona":"Veer","source":"SMART goals / small steps"},
  {"id":"bn-029","cat":"bounce-toolkit","type":"build","hook":"Build a calm-the-storm kit for when stress spikes.","prompt":"Pick real, healthy tools.","pieces":["slow breathing","move your body","write it down","reach out to someone"],"mode":"assemble","key":["slow breathing","move your body","write it down","reach out to someone"],"relearn":"Regulate stress with breath, movement, writing, and reaching out.","persona":"any","source":"emotional regulation"},
  {"id":"bn-030","cat":"bounce-toolkit","type":"build","hook":"Build a 'zoom out' perspective check.","prompt":"Order questions that widen the view.","pieces":["will this matter in a year?","what's still okay right now?","what's one thing I can control?","who can help?"],"mode":"sequence","key":["will this matter in a year?","what's still okay right now?","what's one thing I can control?","who can help?"],"relearn":"Zooming out (time, what's okay, control, help) shrinks a setback.","persona":"any","source":"perspective-taking"},
  {"id":"bn-031","cat":"bounce-toolkit","type":"build","hook":"Build a self-compassion line to use after a flop.","prompt":"Assemble a kind, true message to yourself.","pieces":["this is genuinely hard","anyone would struggle with this","I'm allowed to find it tough","I'll get through it"],"mode":"assemble","key":["this is genuinely hard","anyone would struggle with this","I'm allowed to find it tough","I'll get through it"],"relearn":"A self-compassion line steadies you faster than self-attack.","persona":"any","source":"self-compassion"},
  {"id":"bn-032","cat":"bounce-toolkit","type":"branch","hook":"After a hard knock, your instinct is to isolate.","options":[{"text":"Reach out to one trusted person anyway","consequence":"Connection eases the weight; you're not alone.","outcome":"connected","best":true},{"text":"Shut everyone out","consequence":"Isolation deepens it; one caring person helps most."}],"debrief":"One caring connection is the strongest bounce-back tool there is.","relearn":"Reach out instead of isolating after a setback.","persona":"Veer","source":"supportive relationships"},
  {"id":"bn-033","cat":"bounce-toolkit","type":"branch","hook":"Stress is so high you can't think straight before a deadline.","options":[{"text":"Take a short reset, breathe, then start one small piece","consequence":"Your mind clears enough to begin.","outcome":"regulated","best":true},{"text":"Spiral and freeze","consequence":"A short reset and one small step beat freezing."}],"debrief":"Regulate first, then act; a frozen mind can't problem-solve.","relearn":"Calm the body first, then take one small step.","persona":"any","source":"regulate-then-act"},
  {"id":"bn-034","cat":"bounce-toolkit","type":"branch","hook":"You want to give your comeback the best shot.","options":[{"text":"Protect sleep, movement and one caring connection","consequence":"Your basics fuel your resilience.","outcome":"resourced","best":true},{"text":"Skip sleep and grind alone","consequence":"Sleep, movement and connection are resilience fuel."}],"debrief":"Resilience runs on the basics: rest, movement, connection.","relearn":"Sleep, movement and connection power your bounce-back.","persona":"any","source":"resilience basics"},
  {"id":"bn-035","cat":"bounce-toolkit","type":"sort","hook":"Sort: a real coping tool, or an empty/avoidant one?","items":[{"id":"a","text":"Talking it through with someone"},{"id":"b","text":"Endless doomscrolling"},{"id":"c","text":"A walk or workout"},{"id":"d","text":"Pretending you're fine"}],"bins":[{"id":"real","label":"Real coping"},{"id":"avoid","label":"Empty / avoidant"}],"key":{"a":"real","b":"avoid","c":"real","d":"avoid"},"relearn":"Real coping connects and moves you; avoidance just numbs.","persona":"any","source":"coping"},
  {"id":"bn-036","cat":"bounce-toolkit","type":"sort","hook":"Sort: in your control, or not, after a setback?","items":[{"id":"a","text":"My next effort"},{"id":"b","text":"What already happened"},{"id":"c","text":"Asking for help"},{"id":"d","text":"Others' opinions"}],"bins":[{"id":"control","label":"In my control"},{"id":"not","label":"Not in my control"}],"key":{"a":"control","b":"not","c":"control","d":"not"},"relearn":"Spend energy on what you control: your next step and asking for help.","persona":"any","source":"locus of control"},
  {"id":"bn-037","cat":"bounce-toolkit","type":"reflect","hook":"Lensy: which bounce-back tool will you actually use next time?","prompt":"Pick your go-to.","options":["Talk to someone","Breathe and reset","One small step","Zoom out"],"affirm":"Having a go-to tool ready makes the next knock easier.","relearn":"A ready bounce-back tool helps you recover faster.","persona":"any","source":"coping / readiness"},
  {"id":"bn-038","cat":"bounce-toolkit","type":"reflect","hook":"Lensy: rest is part of bouncing back, not a reward you must earn. Believe it?","prompt":"What do you think?","options":["Yes","Rest helps me recover","I'll allow it"],"affirm":"Rest refuels the resilience tank; it's allowed.","relearn":"Rest is part of recovery, not a reward to earn.","persona":"Veer","source":"rest / recovery"},
  // — Exam & performance pressure —
  {"id":"bn-039","cat":"exam-pressure","type":"branch","hook":"Board exams loom and the pressure feels crushing.","options":[{"text":"Make a realistic plan, protect rest, and ask for support","consequence":"The mountain becomes a set of steps.","outcome":"steady","best":true},{"text":"Panic, skip sleep, and spiral","consequence":"A plan, rest and support steady you better than panic."}],"debrief":"Exam pressure shrinks with a plan, rest and people in your corner.","relearn":"Face exam pressure with a plan, rest and support, not panic.","persona":"Veer","source":"exam stress (India)"},
  {"id":"bn-040","cat":"exam-pressure","type":"branch","hook":"Everyone's comparing marks and predicted ranks; it's spiking your anxiety.","options":[{"text":"Step back from the comparison and focus on your own plan","consequence":"Your anxiety eases and focus returns.","outcome":"grounded","best":true},{"text":"Join the rank-comparison frenzy","consequence":"Comparison fuels anxiety; run your own race."}],"debrief":"Comparing ranks feeds the spiral; your plan is what helps.","relearn":"Step out of rank-comparison; focus on your own progress.","persona":"Riya","source":"comparison / exam stress"},
  {"id":"bn-041","cat":"exam-pressure","type":"branch","hook":"A parent says your whole future rides on this one exam.","options":[{"text":"Hear their worry, but remember one exam isn't your whole life","consequence":"You keep perspective and lower the stakes.","outcome":"perspective","best":true},{"text":"Absorb it as total truth and panic","consequence":"Their worry is real, but one exam isn't your entire future."}],"debrief":"Love can sound like pressure; one exam isn't your whole life.","relearn":"One exam isn't your whole future, whatever the pressure says.","persona":"Veer","source":"exam pressure / family (India)"},
  {"id":"bn-042","cat":"exam-pressure","type":"branch","hook":"You did poorly in a big exam and feel like you've let everyone down.","options":[{"text":"Talk to a trusted adult about next steps and other paths","consequence":"You find there's more than one road forward.","outcome":"supported","best":true},{"text":"Carry it all alone in silence","consequence":"There are always other paths; a trusted adult can help you see them."}],"debrief":"A low result is survivable, and there's always another path.","relearn":"A poor result isn't the end; talk it through and find another path.","persona":"Counsellor","source":"exam stress / help-seeking"},
  {"id":"bn-043","cat":"exam-pressure","type":"branch","hook":"Exam stress is affecting your sleep and appetite for weeks.","options":[{"text":"Tell a trusted adult or call Tele-MANAS (14416) for support","consequence":"You get real help with the stress.","outcome":"supported","best":true},{"text":"Push through alone and hope it passes","consequence":"Weeks of stress affecting sleep and eating deserve support."}],"debrief":"When stress hits sleep and appetite for weeks, reach out for help.","relearn":"Lasting exam stress deserves a trusted adult or Tele-MANAS (14416).","persona":"Counsellor","source":"help-seeking / Tele-MANAS"},
  {"id":"bn-044","cat":"exam-pressure","type":"strike-rewrite","hook":"\"My marks decide my worth as a person.\"","myth":{"un":"My marks decide how much I'm worth.","re":"Marks measure one exam on one day, not your value.","why":"Your worth is not a number on a result sheet."},"relearn":"Marks measure a test, not your worth as a person.","persona":"Riya","source":"exam pressure (India)"},
  {"id":"bn-045","cat":"exam-pressure","type":"strike-rewrite","hook":"\"There's only one acceptable career path, and this exam is it.\"","myth":{"un":"There's only one path, and this exam is the only gate.","re":"There are many paths to a good life and career.","why":"Success has countless routes, not one gate."},"relearn":"There are many paths to a good life, not just one exam.","persona":"Veer","source":"exam pressure / paths"},
  {"id":"bn-046","cat":"exam-pressure","type":"strike-rewrite","hook":"\"Taking breaks while studying is lazy.\"","myth":{"un":"Breaks while studying are just laziness.","re":"Breaks and sleep are what let your brain actually learn.","why":"A rested brain remembers; a fried one doesn't."},"relearn":"Breaks and sleep help you learn; they aren't laziness.","persona":"any","source":"study / rest"},
  {"id":"bn-047","cat":"exam-pressure","type":"sort","hook":"Sort: helps under exam pressure, or harms?","items":[{"id":"a","text":"A realistic study plan"},{"id":"b","text":"All-night cramming, no sleep"},{"id":"c","text":"Short breaks and rest"},{"id":"d","text":"Comparing ranks constantly"}],"bins":[{"id":"helps","label":"Helps"},{"id":"harms","label":"Harms"}],"key":{"a":"helps","b":"harms","c":"helps","d":"harms"},"relearn":"Plans and rest help; no-sleep cramming and rank-watching harm.","persona":"any","source":"exam strategies"},
  {"id":"bn-048","cat":"exam-pressure","type":"sort","hook":"Sort: a true source of your worth, or just exam pressure talking?","items":[{"id":"a","text":"How you treat people"},{"id":"b","text":"Your exam rank"},{"id":"c","text":"Your curiosity and effort"},{"id":"d","text":"A single test score"}],"bins":[{"id":"true","label":"Real worth"},{"id":"pressure","label":"Pressure talking"}],"key":{"a":"true","b":"pressure","c":"true","d":"pressure"},"relearn":"Your worth is your character and effort, not a rank or score.","persona":"any","source":"self-worth"},
  {"id":"bn-049","cat":"exam-pressure","type":"reflect","hook":"Lensy: imagine it's ten years from now. How much will this one exam matter?","prompt":"What do you think?","options":["Much less","Barely","Good to remember"],"affirm":"Most of what feels huge now softens a lot with time.","relearn":"Most single exams matter far less in the long run.","persona":"any","source":"perspective"},
  {"id":"bn-050","cat":"exam-pressure","type":"reflect","hook":"Lensy: what's one thing you're good at that no exam can measure?","prompt":"Think of one.","options":["Being kind","Making people laugh","Fixing things","Sticking with friends"],"affirm":"Those strengths are real and they matter in life, deeply.","relearn":"You have real strengths no exam can measure.","persona":"any","source":"self-worth"},
  {"id":"bn-051","cat":"exam-pressure","type":"match","hook":"Match the pressure thought to a steadier truth.","pairs":[{"left":"\"I must be perfect\"","right":"Doing my best is enough"},{"left":"\"One score defines me\"","right":"I'm far more than a score"},{"left":"\"No time to rest\"","right":"Rest helps me perform"}],"relearn":"Each pressure thought has a steadier, truer reply.","persona":"any","source":"reframing"},
  // — Being there for a friend —
  {"id":"bn-052","cat":"support-friend","type":"role-play","hook":"A friend says they're really struggling lately.","setup":"Open the door, don't fix. Say:","yourLine":[{"text":"\"That sounds really hard. I'm here, do you want to talk?\"","best":true},{"text":"\"Just cheer up, it's not a big deal.\""}],"relearn":"Start with listening and presence, not fixing or dismissing.","persona":"any","source":"peer support / listening"},
  {"id":"bn-053","cat":"support-friend","type":"role-play","hook":"A friend opens up; you don't know how to 'solve' it.","setup":"You don't have to solve it. Say:","yourLine":[{"text":"\"I don't have all the answers, but I'm not going anywhere.\"","best":true},{"text":"\"Here's exactly what you should do...\" (then list fixes)"}],"relearn":"Being present matters more than having the perfect fix.","persona":"any","source":"peer support"},
  {"id":"bn-054","cat":"support-friend","type":"role-play","hook":"A friend brushes off their own pain with a joke.","setup":"Gently let them know it's safe. Say:","yourLine":[{"text":"\"You can be real with me, I won't judge you.\"","best":true},{"text":"\"Haha yeah, anyway...\""}],"relearn":"Letting a friend know it's safe to be real opens the door.","persona":"Veer","source":"peer support"},
  {"id":"bn-055","cat":"support-friend","type":"role-play","hook":"A friend shares something heavy and asks you to tell no one, ever.","setup":"Care honestly about safety. Say:","yourLine":[{"text":"\"I've got you, but if you're in danger I'll help you get an adult, because I care.\"","best":true},{"text":"\"Okay, I promise I'll never tell anyone.\""}],"relearn":"Don't promise secrecy about safety; caring means helping them get help.","persona":"any","source":"safeguarding / secrets"},
  {"id":"bn-056","cat":"support-friend","type":"role-play","hook":"You want to check in on a friend who's gone quiet and withdrawn.","setup":"Reach out simply. Say:","yourLine":[{"text":"\"Hey, I've noticed you've seemed down. I'm here if you want to talk.\"","best":true},{"text":"Say nothing and hope they're fine"}],"relearn":"A simple 'I noticed, I'm here' can mean everything to someone.","persona":"any","source":"peer support / noticing"},
  {"id":"bn-057","cat":"support-friend","type":"role-play","hook":"Helping a friend take the step to tell an adult.","setup":"Offer to go with them. Say:","yourLine":[{"text":"\"Let's tell someone who can help, I'll come with you.\"","best":true},{"text":"\"You should probably tell someone\" (then leave it)"}],"relearn":"Going with a friend to an adult makes help far easier to reach.","persona":"Counsellor","source":"help-routing"},
  {"id":"bn-058","cat":"support-friend","type":"role-play","hook":"You feel out of your depth supporting a friend who's really low.","setup":"Set a kind limit and route up. Say:","yourLine":[{"text":"\"I care about you, and this is bigger than just us, let's get a trusted adult.\"","best":true},{"text":"Carry it all alone and burn out"}],"relearn":"You can care for a friend and still bring in an adult; you're not their therapist.","persona":"any","source":"safeguarding / limits"},
  {"id":"bn-059","cat":"support-friend","type":"role-play","hook":"A friend says something that worries you about their safety.","setup":"Take it seriously, don't keep it secret. Say:","yourLine":[{"text":"\"I'm really glad you told me. Let's talk to someone who can help, right now.\"","best":true},{"text":"\"You're probably just being dramatic.\""}],"relearn":"Take any safety worry seriously and bring in a trusted adult at once.","persona":"Counsellor","source":"safeguarding / escalate"},
  {"id":"bn-060","cat":"support-friend","type":"branch","hook":"Your friend seems okay online but you sense something's really wrong.","options":[{"text":"Check in privately and honestly","consequence":"They feel seen and may finally open up.","outcome":"caring","best":true},{"text":"Assume the happy posts are the full story","consequence":"Posts can hide pain; a private check-in helps."}],"debrief":"Online cheerfulness can mask real struggle; check in for real.","relearn":"Don't take happy posts as proof; check in privately.","persona":"Riya","source":"peer support"},
  {"id":"bn-061","cat":"support-friend","type":"branch","hook":"A friend confides they've been having dark thoughts.","options":[{"text":"Stay calm, take it seriously, and get a trusted adult now","consequence":"You help keep your friend safe; adults can step in.","outcome":"protective","best":true},{"text":"Keep it secret to honour their trust","consequence":"This is a 'tell a trusted adult now' moment, for their safety."}],"debrief":"Dark thoughts are too big to hold alone, bring in a trusted adult immediately.","relearn":"If a friend has dark thoughts, get a trusted adult right away.","persona":"Counsellor","source":"safeguarding / crisis"},
  {"id":"bn-062","cat":"support-friend","type":"branch","hook":"You supported a friend through a hard time and now you feel drained.","options":[{"text":"Look after yourself too, and lean on your own support","consequence":"You refill so you can keep being there.","outcome":"balanced","best":true},{"text":"Ignore your own needs until you crash","consequence":"You matter too; supporters need support."}],"debrief":"Caring for others works only if you also care for yourself.","relearn":"Look after your own wellbeing while supporting a friend.","persona":"any","source":"supporter self-care"},
  {"id":"bn-063","cat":"support-friend","type":"sort","hook":"Sort: helps a struggling friend, or hurts?","items":[{"id":"a","text":"Listening without judging"},{"id":"b","text":"\"Others have it worse\""},{"id":"c","text":"Helping them reach an adult"},{"id":"d","text":"Telling everyone their business"}],"bins":[{"id":"helps","label":"Helps"},{"id":"hurts","label":"Hurts"}],"key":{"a":"helps","b":"hurts","c":"helps","d":"hurts"},"relearn":"Listen and route to help; don't minimise or gossip.","persona":"any","source":"peer support"},
  {"id":"bn-064","cat":"support-friend","type":"sort","hook":"Sort: a helpful thing to say, or one to avoid?","items":[{"id":"a","text":"\"I'm here for you\""},{"id":"b","text":"\"Just get over it\""},{"id":"c","text":"\"That sounds really tough\""},{"id":"d","text":"\"You're overreacting\""}],"bins":[{"id":"say","label":"Helpful"},{"id":"avoid","label":"Avoid"}],"key":{"a":"say","b":"avoid","c":"say","d":"avoid"},"relearn":"Validate and stay present; skip 'get over it' and 'you're overreacting'.","persona":"any","source":"what to say"},
  {"id":"bn-065","cat":"support-friend","type":"match","hook":"Match the friend's need to your move.","pairs":[{"left":"They need to be heard","right":"Listen, don't fix"},{"left":"They're in danger","right":"Get a trusted adult now"},{"left":"They feel alone","right":"Keep showing up"}],"relearn":"Match your support to what your friend actually needs.","persona":"any","source":"peer support"},
  {"id":"bn-066","cat":"support-friend","type":"match","hook":"Match the unhelpful response to a kinder one.","pairs":[{"left":"\"Cheer up\"","right":"\"I'm here, take your time\""},{"left":"\"It's nothing\"","right":"\"That matters, tell me more\""},{"left":"\"Just be positive\"","right":"\"It's okay to not be okay\""}],"relearn":"Swap brush-offs for presence and validation.","persona":"any","source":"what to say"},
  {"id":"bn-067","cat":"support-friend","type":"reflect","hook":"Lensy: being the one steady friend can change everything for someone. Worth being?","prompt":"What do you think?","options":["Yes","I want to be that","It matters"],"affirm":"One steady, caring friend is a real protective force in someone's life.","relearn":"Being one steady, caring friend genuinely protects people.","persona":"any","source":"supportive relationships (evidence)"},
  // — When to reach out —
  {"id":"bn-068","cat":"reach-out","type":"branch","hook":"Your own low feelings have lasted weeks and aren't lifting.","options":[{"text":"Tell a trusted adult or call Tele-MANAS (14416)","consequence":"You get real support instead of waiting it out alone.","outcome":"supported","best":true},{"text":"Keep waiting and hoping it passes","consequence":"Weeks of low mood deserve real support; reach out."}],"debrief":"Resilience has limits; lasting low feelings are a sign to get help.","relearn":"If low feelings last for weeks, tell an adult or call Tele-MANAS (14416).","persona":"Counsellor","source":"help-seeking / Tele-MANAS"},
  {"id":"bn-069","cat":"reach-out","type":"branch","hook":"You're having thoughts that scare you, or that you don't want to be here.","options":[{"text":"Tell a trusted adult right now, or call Tele-MANAS 14416 / Childline 1098","consequence":"You reach people trained to help; you don't face this alone.","outcome":"safe","best":true},{"text":"Keep it hidden","consequence":"These thoughts deserve immediate support; please tell someone now."}],"debrief":"If thoughts ever scare you, reach a trusted adult or helpline right away, you deserve support.","relearn":"Scary or dark thoughts are a reason to reach out now, you're not alone.","persona":"Counsellor","source":"crisis / help-seeking"},
  {"id":"bn-070","cat":"reach-out","type":"branch","hook":"You're not sure your problem is 'big enough' to ask for help.","options":[{"text":"Reach out anyway; help isn't only for emergencies","consequence":"You get support early, when it's easiest.","outcome":"supported","best":true},{"text":"Decide you should handle it alone","consequence":"You don't have to be in crisis to deserve support."}],"debrief":"You don't need to be at breaking point to deserve help.","relearn":"You can ask for help any time, not only in a crisis.","persona":"any","source":"help-seeking"},
  {"id":"bn-071","cat":"reach-out","type":"branch","hook":"You told an adult once and felt brushed off.","options":[{"text":"Tell another trusted adult, or try a helpline","consequence":"Someone will take it seriously; keep going.","outcome":"persistent","best":true},{"text":"Give up on getting help","consequence":"If one adult misses it, try another or a helpline."}],"debrief":"If one person doesn't hear you, there are others who will.","relearn":"If brushed off once, tell someone else or call a helpline.","persona":"any","source":"help-seeking / persistence"},
  {"id":"bn-072","cat":"reach-out","type":"role-play","hook":"You're ready to tell someone you're not coping.","setup":"Say it plainly. Say:","yourLine":[{"text":"\"I'm not coping right now, and I need some help.\"","best":true},{"text":"\"I'm fine\" (when you're not)"}],"relearn":"Saying 'I'm not coping, I need help' is brave and it works.","persona":"any","source":"help-seeking"},
  {"id":"bn-073","cat":"reach-out","type":"role-play","hook":"You want to call a helpline but feel nervous.","setup":"Remind yourself what it's for. Say:","yourLine":[{"text":"\"They're trained to listen and help, that's exactly what this is for.\"","best":true},{"text":"\"They'll think I'm being silly.\""}],"relearn":"Helplines like Tele-MANAS (14416) are there for exactly this; calling is okay.","persona":"any","source":"helpline / de-stigmatise"},
  {"id":"bn-074","cat":"reach-out","type":"role-play","hook":"A counsellor asks how you're really doing.","setup":"Be honest. Say:","yourLine":[{"text":"\"Honestly, I've been struggling more than I let on.\"","best":true},{"text":"\"All good\" (when it isn't)"}],"relearn":"Honesty with a counsellor lets them actually help you.","persona":"Counsellor","source":"help-seeking"},
  {"id":"bn-075","cat":"reach-out","type":"role-play","hook":"You're encouraging a friend to reach out for help.","setup":"Normalise it. Say:","yourLine":[{"text":"\"Getting help is smart, not weak, I'll help you find someone.\"","best":true},{"text":"\"Maybe just wait and see.\""}],"relearn":"You can normalise help-seeking and help a friend take the step.","persona":"any","source":"peer / help-routing"},
  {"id":"bn-076","cat":"reach-out","type":"strike-rewrite","hook":"\"Reaching out for mental health help means I'm weak or broken.\"","myth":{"un":"Asking for mental-health help means I'm weak or broken.","re":"Reaching out is one of the strongest, smartest things you can do.","why":"Everyone needs support sometimes; that's human."},"relearn":"Asking for mental-health help is strong, not weak.","persona":"Veer","source":"de-stigmatise"},
  {"id":"bn-077","cat":"reach-out","type":"strike-rewrite","hook":"\"If I just had more willpower, I wouldn't need help.\"","myth":{"un":"Enough willpower means I'd never need help.","re":"Some struggles need support and care, not just willpower.","why":"You can't willpower your way through everything alone."},"relearn":"Some things need support, not just willpower; that's okay.","persona":"any","source":"de-stigmatise"},
  {"id":"bn-078","cat":"reach-out","type":"reflect","hook":"Lensy: name one safe person and one helpline you could reach if things got heavy.","prompt":"Think of them.","options":["A parent + Tele-MANAS 14416","A counsellor + Childline 1098","An adult I trust + a helpline"],"affirm":"Knowing your people and numbers means help is always in reach.","relearn":"Knowing a safe person and a helpline means you're never stuck alone.","persona":"any","source":"safety planning"},
  {"id":"bn-079","cat":"reach-out","type":"reflect","hook":"Lensy: 'it's okay to not be okay' isn't giving up, it's being honest. Sit right with you?","prompt":"What do you think?","options":["Yes","It's honest","That helps"],"affirm":"Honesty about struggling is the first step to feeling better.","relearn":"It's okay to not be okay; saying so is honest and brave.","persona":"any","source":"normalising"},
  {"id":"bn-080","cat":"reach-out","type":"sort","hook":"Sort: a 'reach out now' sign, or an ordinary rough patch?","items":[{"id":"a","text":"Dark thoughts or not wanting to be here"},{"id":"b","text":"A bad day that passes"},{"id":"c","text":"Weeks of not eating or sleeping"},{"id":"d","text":"Feeling nervous before a test"}],"bins":[{"id":"now","label":"Reach out now"},{"id":"ordinary","label":"Ordinary rough patch"}],"key":{"a":"now","b":"ordinary","c":"now","d":"ordinary"},"relearn":"Dark thoughts or weeks of not eating/sleeping mean reach out now.","persona":"Counsellor","source":"safeguarding"},
  {"id":"bn-081","cat":"reach-out","type":"sort","hook":"Sort: who or what can help when it's heavy?","items":[{"id":"a","text":"A trusted adult"},{"id":"b","text":"Tele-MANAS (14416)"},{"id":"c","text":"A 'just toughen up' message"},{"id":"d","text":"Childline (1098 / 112)"}],"bins":[{"id":"helps","label":"Real help"},{"id":"no","label":"Not help"}],"key":{"a":"helps","b":"helps","c":"no","d":"helps"},"relearn":"Trusted adults and helplines (Tele-MANAS 14416, Childline 1098) are real help.","persona":"any","source":"help routes (India)"},
  {"id":"bn-082","cat":"reach-out","type":"reflect","hook":"Lensy: hard times pass, and asking for help speeds that up. Hold onto that?","prompt":"What do you think?","options":["Yes","Help speeds it up","I'll remember"],"affirm":"Reaching out doesn't just feel better, it helps things get better faster.","relearn":"Hard times pass, and reaching out helps them pass sooner.","persona":"any","source":"hope / help-seeking"},
  {"id":"bn-083","cat":"reach-out","type":"strike-rewrite","hook":"\"Talking to a helpline or counsellor won't actually change anything.\"","myth":{"un":"Talking to a counsellor or helpline won't change anything.","re":"Trained support genuinely helps, with the feeling and the next steps.","why":"That's literally what they're trained and there to do."},"relearn":"Trained support really does help; it's worth reaching out.","persona":"any","source":"help efficacy"},
  {"id":"bn-084","cat":"reach-out","type":"reflect","hook":"Lensy: biggest take-away from Bounce?","prompt":"Pick your motto.","options":["Feel it, then move through it","Setbacks aren't the end","Lean on people","It's okay to ask for help"],"affirm":"That's resilience, real, honest, and never something you do alone.","relearn":"Bounce back by feeling it, reframing, leaning on people, and asking for help.","persona":"any","source":"consolidation"},
];

export const BOUNCE: V2GameConfig = {
  gameId: "bounce",
  title: "Bounce",
  greet: "Hey, it's Lensy. 🌱 Everyone hits setbacks, failed tests, rough days, hard knocks. Real resilience isn't 'just be positive' or tough it out alone. Let's learn the moves that actually help you bounce back, and when to lean on others.",
  scenarios: SCENARIOS,
  categories: [
    { id: "what-resilience", emoji: "🌱", label: "What resilience is" },
    { id: "reframe-setback", emoji: "🔄", label: "Reframe the setback" },
    { id: "bounce-toolkit", emoji: "🧰", label: "Bounce-back toolkit" },
    { id: "exam-pressure", emoji: "📝", label: "Exam pressure" },
    { id: "support-friend", emoji: "🤝", label: "Be there for a friend" },
    { id: "reach-out", emoji: "📞", label: "When to reach out" },
  ],
  badge: {
    title: "Bounce-Back Pro! 🌱",
    blurb: "You know real resilience (not toxic positivity), how to reframe a setback, a coping toolkit that actually works, how to be there for a friend — and that reaching out for help is strong, never weak. 💪",
  },
  helpLine: "If low feelings last for weeks, or you ever have thoughts that scare you, please tell a trusted adult right now, or call Tele-MANAS on one-four-four-one-six, or Childline on one-zero-nine-eight. Trained people are there for exactly this, and reaching out is strong.",
  helpLabel: "Reach out · Tele-MANAS 14416",
  reassure: "Resilience has limits, and that's human. Lasting low feelings, or any thought that you don't want to be here, mean reach out NOW, not later: a trusted adult, Tele-MANAS 14416, or Childline 1098/112. Asking for help is the strongest move there is. 💛",
  reassureCats: ["reach-out"],
  buildLabels: { assemble: "That's my bounce kit 🧰", sequence: "That's the bounce-back way ✨" },
};
