// Content for Capstone 4: Reading Relationships (node c4, Chapter 4 graduation, ages 12-15). NEW rich build
// to GDD c4 ("Capstone format v1"), following the c1 reference. Not a lesson, never a test: a calm, near-peer,
// no-fail celebration that consolidates the chapter's eleven big truths through spaced, VARIED retrieval (each
// truth re-cued through a DIFFERENT mechanic: gallery · branch · swipe · sort · strike-rewrite · build · spot ·
// match), then lights up the Reading-Relationships constellation and awards a graduation star. Closes Chapter 4
// (g21, g28, g39, g40, g43). Faithful from the Landing JSON, rendered by the shared rich engine
// (components/games/capstone-rich.tsx). gameId "capstone-4" (the Landing's "capstone-ch4" is design-doc only).
// DO NOT RENAME.

import type { CapstoneConfig } from "./capstone-schema";

export const CAPSTONE_4: CapstoneConfig = {
  gameId: "capstone-4",
  capstone: "Reading Relationships",
  node: "c4",
  chapter: 4,
  ages: "12-15",
  arrival: "Lensy: look how you've grown this chapter. Relationships got more real, and you learned to read them: green lights, red flags, fact from myth, real from fake.",
  canvasPayoff: "The Reading Relationships map lights up across a teen city at night, window by window, street by street, till your eleven stickers rise into a constellation.",
  threadsRecapped: ["A", "B", "C", "E", "F", "G"],
  recap: [
    {"node":"g21","game":"Body Confident","thread":"A · Body & Growing Up","bigTruth":"Your changing body is yours; real confidence grows from facts and self-kindness, not from comparison to edited images.","glyph":"body-confident"},
    {"node":"g39","game":"Bounce","thread":"C · Feelings & Life Skills","bigTruth":"Stress and low moods pass, you have real coping tools, and showing up for a friend who's struggling matters.","glyph":"bounce-spark"},
    {"node":"g22","game":"Plan It","thread":"F · Sexual & Reproductive Health","bigTruth":"You understand fertility, pregnancy and contraception, knowledge that lets you plan your own future with care.","glyph":"plan-it"},
    {"node":"g23","game":"Outbreak: Stop the Spread","thread":"F · Sexual & Reproductive Health","bigTruth":"You know how STIs and HIV really spread, and how they don't, so you can stay safe and be a kind, informed friend.","glyph":"outbreak-shield"},
    {"node":"g24","game":"Green Light / Red Light","thread":"B · Safety, Consent & Boundaries","bigTruth":"You can read a relationship, the green lights of respect and the red flags of control, and you know you deserve the green.","glyph":"green-red-light"},
    {"node":"g25","game":"MythBuster: Gender","thread":"E · Gender & Respect","bigTruth":"The gender myths teens hear constantly aren't facts, and you can bust them on sight.","glyph":"mythbuster"},
    {"node":"g26","game":"Equalize","thread":"E · Gender & Respect","bigTruth":"Equality isn't a contest where someone loses, it lifts everyone, and child marriage is a rights issue you can help prevent.","glyph":"equalize"},
    {"node":"g27","game":"Stand Up","thread":"B · Safety, Consent & Boundaries","bigTruth":"You can go from bystander to upstander, safely, with the five Ds and the helplines behind you.","glyph":"stand-up"},
    {"node":"g40","game":"Firewall","thread":"B · Safety, Consent & Boundaries","bigTruth":"You can stay safe online by spotting grooming, pressure and your footprint, and if you're ever targeted, it's not your fault, and you know where to get help.","glyph":"firewall"},
    {"node":"g43","game":"The Rabbit Hole","thread":"E/G · Gender & Media","bigTruth":"You can see the online-misogyny funnel and the grift for what they are, and choose real strength and respect over their hooks.","glyph":"rabbit-hole"},
    {"node":"g28","game":"Reality Check","thread":"G · Values, Rights & Media","bigTruth":"You can read the feed, real, staged, faked or false, and you know screen romance and sex are a performance, not real life.","glyph":"reality-check"},
  ],
  playback: [
    {"id":"c4-p1","from":"all","type":"gallery","frame":"Your Reading Relationships constellation, eleven stickers from a whole chapter. Tap any star to revisit what you grew into there.","stickers":["body-confident","bounce-spark","plan-it","outbreak-shield","green-red-light","mythbuster","equalize","stand-up","firewall","rabbit-hole","reality-check"],"celebrate":"Eleven stars in your sky. That's a whole chapter of reading relationships, and yourself."},
    {"id":"c4-p2","from":"g24","type":"branch","frame":"One more Green Light / Red Light, just for the joy of knowing your read. A partner texts constantly to check where you are and sulks when you see friends.","options":[{"text":"Name it: that's a red flag of control, and you deserve respect","consequence":"You read it clearly, like the relationship-reader you've become.","outcome":"reads-it","best":true},{"text":"Tell yourself it just means they care","consequence":"You know the read now, control isn't care, and respect is the green light."}],"debrief":"Green lights are trust, space and respect; red flags are control and pressure. You can tell them apart.","celebrate":"Relationship-reader, you see clearly now."},
    {"id":"c4-p3","from":"g28","type":"swipe","frame":"From Reality Check, swipe up for every one you can now see straight through.","cue":"The flawless 'woke up like this' selfie. The 'perfect couple' who never fight. The viral forward with no source. The screen romance that reads minds.","up":"Curated, staged or faked, and I can tell.","celebrate":"Hard to fool now, that's the whole point."},
    {"id":"c4-p4","from":"g23","type":"sort","frame":"From Outbreak, sort what spreads HIV from what truly doesn't, facts beat fear every time.","items":[{"id":"a","text":"A hug or shared meal"},{"id":"b","text":"Unprotected sex"},{"id":"c","text":"Sharing needles"},{"id":"d","text":"Sitting beside someone"}],"bins":[{"id":"not","label":"Does NOT spread it","valence":"neutral"},{"id":"can","label":"Can spread it","valence":"neutral"}],"key":{"a":"not","b":"can","c":"can","d":"not"},"celebrate":"Facts clear, heart kind, a real friend to anyone."},
    {"id":"c4-p5","from":"g25","type":"strike-rewrite","frame":"From MythBuster, here's a gender myth you can flip in your sleep now. Strike it, then write the truth.","myth":{"un":"Girls just aren't built for maths and science.","re":"Ability isn't gendered; that's a myth, not a fact, and the evidence is clear.","why":"There's no brain difference that makes a subject 'for boys'."},"celebrate":"Flipped on sight, myth-buster."},
    {"id":"c4-p6","from":"g27","type":"build","frame":"From Stand Up, build the upstander toolkit, the five safe ways to help.","pieces":["distract","delegate (get others)","document if safe","delay (check in after)","direct, only if safe"],"mode":"assemble","celebrate":"Five Ds ready, always one that's safe to use."},
    {"id":"c4-p7","from":"g43","type":"spot","frame":"From The Rabbit Hole, spot the funnel and the grift, you see it coming a mile off now.","scene":[{"text":"He blames all your problems on women","trick":true},{"text":"A normal fitness or study tip","trick":false},{"text":"He funnels you toward paying for 'secret' brotherhood content","trick":true}],"why":"Blame plus a paywall is the funnel and the grift; real strength needs neither.","celebrate":"Seen straight through, that's clarity."},
    {"id":"c4-p8","from":"g22","type":"sort","frame":"From Plan It, sort the reliable fact from the myth, you hold this knowledge with calm confidence.","items":[{"id":"a","text":"Condoms help prevent STIs and pregnancy"},{"id":"b","text":"You can't get pregnant the first time"},{"id":"c","text":"Contraception lets people plan if and when"},{"id":"d","text":"Myths are a safe way to plan"}],"bins":[{"id":"fact","label":"A reliable fact","valence":"pos"},{"id":"myth","label":"A myth","valence":"neg"}],"key":{"a":"fact","b":"myth","c":"fact","d":"myth"},"celebrate":"Knowledge that puts your future in your own hands."},
    {"id":"c4-p9","from":"g26","type":"match","frame":"From Equalize, match the myth to the truth that lifts everyone, you sort these easily now.","pairs":[{"left":"\"If women win, men fall behind\"","right":"Equality lifts everyone"},{"left":"\"Sharing housework is weak\"","right":"It builds a happier home"},{"left":"\"Child marriage is just tradition\"","right":"It's a rights issue, and preventable"}],"celebrate":"Fairness is everyone's win, and you know it."},
    {"id":"c4-p10","from":"g40","type":"branch","frame":"From Firewall, one more safe read. Someone you only know online asks to keep your chats a secret and meet up alone.","options":[{"text":"Don't meet, and tell a trusted adult","consequence":"You spot the red flags and stay safe.","outcome":"safe","best":true},{"text":"Go along to be polite","consequence":"Secrecy and 'meet alone' are red flags; telling a trusted adult is the safe read."}],"debrief":"Secrecy, pressure and 'don't tell anyone' are the warning signs; a trusted adult is always the move.","celebrate":"Safe and savvy online, firewall up."},
    {"id":"c4-p11","from":"g21","type":"sort","frame":"From Body Confident, sort the kind, true thing to tell yourself, be gentle here.","items":[{"id":"a","text":"My body is mine, and changing is normal"},{"id":"b","text":"I should look like an edited photo"},{"id":"c","text":"Confidence comes from facts and self-kindness"},{"id":"d","text":"I must compare myself to feeds"}],"bins":[{"id":"kind","label":"Kind & true","valence":"pos"},{"id":"not","label":"Not so kind","valence":"uhoh"}],"key":{"a":"kind","b":"not","c":"kind","d":"not"},"celebrate":"Kind to yourself, that's real confidence."},
  ],
  reflect: [
    {"id":"c4-r1","prompt":"Lensy: look how far you've come this chapter. What feels different about how you see relationships now?","options":["I read people more clearly","I know my worth","I spot red flags","I know more"],"affirm":"That clarity is real, and it's all yours."},
    {"id":"c4-r2","prompt":"Lensy: which skill from this chapter are you most glad to have?","options":["Reading green and red flags","Busting gender myths","Standing up safely","Seeing through the feed"],"affirm":"A skill like that will protect and serve you for life."},
    {"id":"c4-r3","prompt":"Lensy: when a relationship or something online feels off now, what do you reach for?","options":["My read of the flags","A trusted person","The helplines","My own values"],"affirm":"You've built real ways to handle things that feel off."},
    {"id":"c4-r4","prompt":"Lensy: what will you carry into the years just ahead?","options":["I deserve respect","Read before I trust","Stand up safely","Keep growing"],"affirm":"Carry it forward, the next chapter's ready for you."},
  ],
  celebration: {"glyph":"reading-relationships-star","certificate":"This certifies you a Reading Relationships graduate. You read green lights and red flags, hold the facts on bodies and health, bust myths and see a faked feed.","stickerBook":"All eleven Chapter 4 stickers now shine in your Reading Relationships constellation, topped by a golden star, your Chapter 4 graduation sticker."},
  preview: "Next, Chapter 5: Ready for the World (ages 15-18). You'll take fuller ownership of your health, consent, identity and rights, deeper, real, at your own pace.",
  share: "This chapter is your own, so it's your call: if you like, share one thing you're proud of learning with a trusted grown-up. Or keep it for yourself, okay too.",
  doneTitle: "🎓 Chapter Four complete!",
};
