// Content for Defenders of the Body (node g20, ages 9–12, Chapter 3) — NEW v2 build to GDD 20
// (mechanic-embodying), the immune-system + infection-myth-busting + HIV anti-stigma node (Thread F · Sexual
// & Reproductive Health) that CLOSES Chapter 3. "Strong body, clear facts, open heart." 84 researched,
// India-grounded scenarios across the defenders → how-germs-spread → defend-yourself → HIV-basics →
// spreads-or-not → kindness-not-fear arc, each encoded as one of the shared v2 play actions (strike-rewrite /
// sort / branch / role-play / spot / match / reflect) — no binary "tap the right card". Lead mechanics:
// strike-rewrite (myth-bust ×22), sort (true/false & spreads-or-not ×16), branch (choose to include ×12).
// Teaches: the body's defence team (skin, white blood cells), how germs really spread, everyday prevention
// habits, HIV explained simply, what spreads HIV vs what NEVER does (CDC/NIH), and — the biggest lesson —
// KINDNESS, NOT FEAR: people living with HIV belong fully in school, play and friendship; HIV is a virus,
// never a punishment or a verdict on character; with treatment people live long, healthy, normal lives; a
// health matter is private; defend others' dignity, not just your own health. Builds on g12 (Smart Screen
// Heroes — hygiene + be-kind-to-a-sick-friend); prereq g19. Rendered by the shared engine
// (components/games/v2-engine.tsx). gameId "defenders" (the engine-host registry id; the GDD/library
// aspirational id is "defenders-of-the-body"). DO NOT RENAME.

import type { Scenario, V2GameConfig } from "./v2-schema";

const SCENARIOS: Scenario[] = [
  // — Your body's defenders —
  {"id":"df-001","cat":"body-defenders","type":"match","hook":"Meet your body's defence team. Match the defender to its job.","pairs":[{"left":"Skin","right":"A wall that keeps germs out"},{"left":"White blood cells","right":"Soldiers that fight germs"},{"left":"A scab","right":"A shield over a cut"}],"relearn":"Your body has a built-in defence team: skin, white blood cells and more.","persona":"Asha","source":"immune system"},
  {"id":"df-002","cat":"body-defenders","type":"match","hook":"Match the defender to what it does.","pairs":[{"left":"Snot and mucus","right":"Traps germs in your nose"},{"left":"Tears","right":"Wash germs from your eyes"},{"left":"Stomach acid","right":"Kills germs you swallow"}],"relearn":"Even snot and tears are part of your body's defences.","persona":"any","source":"immune system"},
  {"id":"df-003","cat":"body-defenders","type":"sort","hook":"Sort: a body defender, or not?","items":[{"id":"a","text":"White blood cells"},{"id":"b","text":"Your hair colour"},{"id":"c","text":"Skin"},{"id":"d","text":"Your favourite song"}],"bins":[{"id":"def","label":"A defender"},{"id":"not","label":"Not a defender"}],"key":{"a":"def","b":"not","c":"def","d":"not"},"relearn":"Skin and white blood cells defend you; not everything about you does.","persona":"any","source":"immune system"},
  {"id":"df-004","cat":"body-defenders","type":"sort","hook":"Sort: what a fever means.","items":[{"id":"a","text":"Your body is fighting germs"},{"id":"b","text":"Your body gave up"},{"id":"c","text":"The defence team is working hard"},{"id":"d","text":"You're being punished"}],"bins":[{"id":"true","label":"True"},{"id":"false","label":"False"}],"key":{"a":"true","b":"false","c":"true","d":"false"},"relearn":"A fever is often a sign your body is fighting germs.","persona":"any","source":"immune system"},
  {"id":"df-005","cat":"body-defenders","type":"sort","hook":"Sort: helps your defenders, or weakens them?","items":[{"id":"a","text":"Good sleep"},{"id":"b","text":"Never washing"},{"id":"c","text":"Healthy food"},{"id":"d","text":"Skipping all meals"}],"bins":[{"id":"helps","label":"Helps defenders"},{"id":"weakens","label":"Weakens them"}],"key":{"a":"helps","b":"weakens","c":"helps","d":"weakens"},"relearn":"Sleep and good food strengthen your body's defences.","persona":"Rohit","source":"immune system"},
  {"id":"df-006","cat":"body-defenders","type":"strike-rewrite","hook":"\"Once a germ gets in, your body can't do anything.\"","myth":{"un":"If a germ gets in, your body is helpless.","re":"Your immune system fights germs every single day.","why":"You have a whole defence team inside you."},"relearn":"Your immune system actively fights germs all the time.","persona":"any","source":"immune system"},
  {"id":"df-007","cat":"body-defenders","type":"strike-rewrite","hook":"\"Getting a little sick sometimes means something is wrong with me.\"","myth":{"un":"Catching a cold sometimes means I'm weak or broken.","re":"Everyone catches germs sometimes; recovering shows your defences work.","why":"Getting better is your immune system winning."},"relearn":"Catching the odd cold is normal; recovering shows your defences work.","persona":"Aarav","source":"immune system"},
  {"id":"df-008","cat":"body-defenders","type":"reflect","hook":"Lensy: you have a tiny army defending you right now. Cool to think about?","prompt":"What do you think?","options":["Very cool","My body's amazing","Go team!"],"affirm":"Your body's defenders work around the clock, for free.","relearn":"Your body defends you constantly, without you even noticing.","persona":"any","source":"immune system"},
  {"id":"df-009","cat":"body-defenders","type":"reflect","hook":"Lensy: you can help your defenders with simple habits. Worth doing?","prompt":"What do you think?","options":["Yes","Easy wins","I'll help my team"],"affirm":"Sleep, food, water and clean hands are gifts to your defence team.","relearn":"Simple healthy habits help your body's defenders do their job.","persona":"any","source":"immune system"},
  {"id":"df-010","cat":"body-defenders","type":"spot","hook":"A cut on the knee over a few days. Spot the defenders at work.","scene":[{"id":"a","text":"Blood clots to plug the cut","trick":true},{"id":"b","text":"The knee is a bit muddy","trick":false},{"id":"c","text":"A scab forms, then new skin grows","trick":true}],"why":"Clotting, scabbing and new skin are your defenders repairing the wound.","relearn":"Healing a cut is your body's defence and repair team in action.","persona":"any","source":"immune system"},
  {"id":"df-011","cat":"body-defenders","type":"match","hook":"Match the defender to the germ-threat it handles.","pairs":[{"left":"Skin barrier","right":"Germs on the outside"},{"left":"Stomach acid","right":"Germs in food"},{"left":"White blood cells","right":"Germs that get inside"}],"relearn":"Different defenders guard different doorways into the body.","persona":"Asha","source":"immune system"},
  {"id":"df-012","cat":"body-defenders","type":"match","hook":"Match: defender, and how to keep it strong.","pairs":[{"left":"Skin","right":"Keep it clean, cover cuts"},{"left":"Whole body","right":"Sleep and eat well"},{"left":"Defences","right":"Get your vaccines"}],"relearn":"You can keep each defender strong with simple care.","persona":"Rohit","source":"immune system / prevention"},
  // — How germs spread —
  {"id":"df-013","cat":"how-germs-spread","type":"sort","hook":"Sort: how do germs travel?","items":[{"id":"a","text":"A cough or sneeze in the air"},{"id":"b","text":"Wishing really hard"},{"id":"c","text":"Dirty hands touching food"},{"id":"d","text":"Feeling jealous"}],"bins":[{"id":"real","label":"Real way germs spread"},{"id":"no","label":"Not how germs spread"}],"key":{"a":"real","b":"no","c":"real","d":"no"},"relearn":"Germs spread by coughs, dirty hands and unclean food, not by feelings.","persona":"any","source":"infection basics"},
  {"id":"df-014","cat":"how-germs-spread","type":"sort","hook":"Sort: a germ that spreads through the air, or through dirty water?","items":[{"id":"a","text":"A cold or flu"},{"id":"b","text":"A tummy bug from unclean water"},{"id":"c","text":"A cough illness"},{"id":"d","text":"Diarrhoea from dirty water"}],"bins":[{"id":"air","label":"Through air"},{"id":"water","label":"Through water/food"}],"key":{"a":"air","b":"water","c":"air","d":"water"},"relearn":"Some germs spread through air, others through unclean water or food.","persona":"Asha","source":"infection basics"},
  {"id":"df-015","cat":"how-germs-spread","type":"sort","hook":"Sort: spreads germs, or is harmless?","items":[{"id":"a","text":"Sneezing into your bare hands then sharing food"},{"id":"b","text":"Smiling at a friend"},{"id":"c","text":"Drinking unclean water"},{"id":"d","text":"Sitting beside someone"}],"bins":[{"id":"spreads","label":"Spreads germs"},{"id":"harmless","label":"Harmless"}],"key":{"a":"spreads","b":"harmless","c":"spreads","d":"harmless"},"relearn":"Germs spread through specific routes; just sitting near someone is harmless.","persona":"any","source":"infection basics"},
  {"id":"df-016","cat":"how-germs-spread","type":"sort","hook":"Sort: which spreads more easily, an airborne cold or HIV?","items":[{"id":"a","text":"A cold (airborne)"},{"id":"b","text":"HIV (only certain fluids)"},{"id":"c","text":"Flu (airborne)"},{"id":"d","text":"HIV from a hug"}],"bins":[{"id":"easy","label":"Spreads easily in air"},{"id":"hard","label":"Does NOT spread that way"}],"key":{"a":"easy","b":"hard","c":"easy","d":"hard"},"relearn":"Colds spread easily through air; HIV does not, and never from a hug.","persona":"Asha","source":"infection basics / HIV contrast"},
  {"id":"df-017","cat":"how-germs-spread","type":"spot","hook":"In the classroom. Spot the germ-spreading move.","scene":[{"id":"a","text":"A kid sneezes openly onto shared books","trick":true},{"id":"b","text":"The fan is on","trick":false},{"id":"c","text":"Then hands them to a friend","trick":true}],"why":"Sneezing openly and passing on shared things spreads germs.","relearn":"Open sneezes onto shared things spread germs to others.","persona":"any","source":"infection basics"},
  {"id":"df-018","cat":"how-germs-spread","type":"spot","hook":"At the water point. Spot the risk.","scene":[{"id":"a","text":"Water is taken from an uncovered, dirty pot","trick":true},{"id":"b","text":"It's a hot day","trick":false},{"id":"c","text":"No one washed hands first","trick":true}],"why":"Unclean water and unwashed hands are common ways tummy germs spread.","relearn":"Dirty water and unwashed hands spread many infections.","persona":"Asha","source":"infection basics / India context"},
  {"id":"df-019","cat":"how-germs-spread","type":"spot","hook":"Spot what does NOT spread germs.","scene":[{"id":"a","text":"Sharing a laugh with a friend","trick":false},{"id":"b","text":"Coughing on someone's food","trick":true},{"id":"c","text":"Sitting together at lunch","trick":false}],"why":"Laughing and sitting together are safe; coughing on food spreads germs.","relearn":"Everyday friendly contact is safe; only certain actions spread germs.","persona":"any","source":"infection basics"},
  {"id":"df-020","cat":"how-germs-spread","type":"strike-rewrite","hook":"\"You catch colds from cold weather alone.\"","myth":{"un":"Cold weather by itself gives you a cold.","re":"Colds come from germs, which can spread more when we're indoors together.","why":"It's the germs, not the temperature, that infect you."},"relearn":"Colds come from germs, not from cold air by itself.","persona":"any","source":"infection basics"},
  {"id":"df-021","cat":"how-germs-spread","type":"strike-rewrite","hook":"\"If you can't see germs, they can't hurt you.\"","myth":{"un":"Germs are invisible, so they can't really affect you.","re":"Germs are tiny but real, and good hygiene keeps them in check.","why":"Invisible doesn't mean harmless."},"relearn":"Germs are invisible but real; hygiene keeps them in check.","persona":"any","source":"infection basics"},
  {"id":"df-022","cat":"how-germs-spread","type":"strike-rewrite","hook":"\"Only dirty or bad people get infections.\"","myth":{"un":"Only dirty or bad people catch infections.","re":"Anyone can catch an infection; it's about germs, not character.","why":"Blaming people for getting sick is unfair and untrue."},"relearn":"Anyone can get an infection; it's not about being 'good' or 'bad'.","persona":"Asha","source":"infection basics / anti-stigma"},
  {"id":"df-023","cat":"how-germs-spread","type":"match","hook":"Match the infection to how it usually spreads.","pairs":[{"left":"Common cold","right":"Coughs and sneezes"},{"left":"Tummy bug","right":"Unclean water or food"},{"left":"Infected cut","right":"Germs entering a wound"}],"relearn":"Different infections spread by different, knowable routes.","persona":"any","source":"infection basics"},
  {"id":"df-024","cat":"how-germs-spread","type":"match","hook":"Match: myth about catching illness, to the truth.","pairs":[{"left":"\"Wet hair causes flu\"","right":"Flu comes from a virus"},{"left":"\"Sugar alone causes colds\"","right":"Colds come from germs"},{"left":"\"Going out at night\"","right":"It's germs, not the dark"}],"relearn":"Illnesses come from germs, not from old wives' tales.","persona":"any","source":"infection basics"},
  // — Defend yourself —
  {"id":"df-025","cat":"defend-yourself","type":"sort","hook":"Sort: a strong defence habit, or not?","items":[{"id":"a","text":"Washing hands with soap"},{"id":"b","text":"Sharing a half-eaten snack mouth-to-mouth"},{"id":"c","text":"Covering your cough"},{"id":"d","text":"Drinking from puddles"}],"bins":[{"id":"good","label":"Good defence"},{"id":"bad","label":"Weak defence"}],"key":{"a":"good","b":"bad","c":"good","d":"bad"},"relearn":"Handwashing and covering coughs are strong defence habits.","persona":"any","source":"prevention"},
  {"id":"df-026","cat":"defend-yourself","type":"sort","hook":"Sort: helps stop germs spreading to others?","items":[{"id":"a","text":"Coughing into your elbow"},{"id":"b","text":"Sneezing on your friend"},{"id":"c","text":"Staying home when very ill"},{"id":"d","text":"Sharing your water bottle when sick"}],"bins":[{"id":"yes","label":"Helps stop spread"},{"id":"no","label":"Spreads it"}],"key":{"a":"yes","b":"no","c":"yes","d":"no"},"relearn":"Covering coughs and resting when ill protect others too.","persona":"any","source":"prevention"},
  {"id":"df-027","cat":"defend-yourself","type":"sort","hook":"Sort: what vaccines do.","items":[{"id":"a","text":"Train your defenders to recognise a germ"},{"id":"b","text":"Make you magnetic"},{"id":"c","text":"Help stop dangerous diseases"},{"id":"d","text":"Control your mind"}],"bins":[{"id":"true","label":"True"},{"id":"false","label":"False"}],"key":{"a":"true","b":"false","c":"true","d":"false"},"relearn":"Vaccines train your defenders to fight specific germs.","persona":"Asha","source":"prevention / vaccines"},
  {"id":"df-028","cat":"defend-yourself","type":"branch","hook":"You're about to eat but your hands are dirty from play.","options":[{"text":"Wash with soap and water first","consequence":"You wash off germs before they reach your mouth.","outcome":"healthy","best":true},{"text":"Just eat, it's fine","consequence":"Washing first stops germs from hitching a ride into you."}],"debrief":"Washing hands before eating is one of the best defences there is.","relearn":"Wash hands before eating to keep germs out.","persona":"any","source":"prevention"},
  {"id":"df-029","cat":"defend-yourself","type":"branch","hook":"You're getting over an illness; a friend asks to share your drink.","options":[{"text":"Say \"let me get you a fresh cup, I'm just recovering\"","consequence":"You protect your friend kindly.","outcome":"caring","best":true},{"text":"Share the same bottle","consequence":"A fresh cup protects your friend while you recover."}],"debrief":"Not sharing mouth-touched things when ill protects others.","relearn":"When recovering, avoid sharing mouth-touched items to protect others.","persona":"any","source":"prevention"},
  {"id":"df-030","cat":"defend-yourself","type":"branch","hook":"There's a vaccination drive at school and you feel nervous.","options":[{"text":"Get it; a quick pinch trains your defenders","consequence":"You're protected against a serious disease.","outcome":"brave","best":true},{"text":"Skip it out of nerves","consequence":"A moment's pinch gives lasting protection; it's worth it."}],"debrief":"Vaccines are a quick way to give your defenders a big advantage.","relearn":"Vaccines give lasting protection for a moment's pinch.","persona":"Aarav","source":"prevention / vaccines"},
  {"id":"df-031","cat":"defend-yourself","type":"strike-rewrite","hook":"\"Washing hands is pointless if they look clean.\"","myth":{"un":"If my hands look clean, washing is pointless.","re":"Germs are invisible; washing with soap removes them.","why":"Clean-looking isn't germ-free."},"relearn":"Hands can look clean but still carry germs; wash with soap.","persona":"any","source":"prevention"},
  {"id":"df-032","cat":"defend-yourself","type":"strike-rewrite","hook":"\"Vaccines aren't needed if you feel healthy.\"","myth":{"un":"If I feel healthy, I don't need vaccines.","re":"Vaccines protect you before a germ ever strikes.","why":"They prepare your defences in advance."},"relearn":"Vaccines protect you in advance, even when you feel fine.","persona":"Asha","source":"prevention / vaccines"},
  {"id":"df-033","cat":"defend-yourself","type":"spot","hook":"A handwashing poster. Spot the steps that matter.","scene":[{"id":"a","text":"Use soap and rub for a count of twenty","trick":true},{"id":"b","text":"The sink is blue","trick":false},{"id":"c","text":"Cover all parts, then rinse","trick":true}],"why":"Soap, scrubbing time, and covering all parts are what make handwashing work.","relearn":"Good handwashing means soap, time, full coverage, and a rinse.","persona":"any","source":"prevention"},
  {"id":"df-034","cat":"defend-yourself","type":"spot","hook":"In the kitchen. Spot the safe-food defence.","scene":[{"id":"a","text":"Water is boiled or filtered before drinking","trick":true},{"id":"b","text":"There's a steel tiffin","trick":false},{"id":"c","text":"Food is covered to keep flies off","trick":true}],"why":"Clean water and covered food keep many infections away.","relearn":"Clean water and covered food are everyday defences.","persona":"Rohit","source":"prevention / India context"},
  {"id":"df-035","cat":"defend-yourself","type":"match","hook":"Match the defence habit to the germ it blocks.","pairs":[{"left":"Soap handwash","right":"Germs on hands"},{"left":"Covering a cough","right":"Germs in the air"},{"left":"Boiling water","right":"Germs in water"}],"relearn":"Each simple habit blocks a specific germ route.","persona":"any","source":"prevention"},
  {"id":"df-036","cat":"defend-yourself","type":"reflect","hook":"Lensy: which defence habit will you do better from today?","prompt":"Pick one.","options":["Wash hands properly","Cover my cough","Drink clean water"],"affirm":"Small habits, repeated, keep you and others well.","relearn":"Choosing one defence habit to improve protects you and others.","persona":"any","source":"prevention"},
  // — HIV, simply explained —
  {"id":"df-037","cat":"hiv-basics","type":"strike-rewrite","hook":"\"HIV is something only 'certain people' get.\"","myth":{"un":"Only certain 'bad' people get HIV.","re":"HIV is a virus; anyone can have it, and it says nothing about character.","why":"A virus doesn't judge who's 'good' or 'bad'."},"relearn":"HIV is a virus anyone can have; it's not about character.","persona":"Asha","source":"HIV basics / anti-stigma"},
  {"id":"df-038","cat":"hiv-basics","type":"strike-rewrite","hook":"\"Having HIV means you'll always be sick.\"","myth":{"un":"People with HIV are always sick and can't live normally.","re":"With daily medicine, people with HIV live long, healthy, normal lives.","why":"Treatment keeps the virus in check."},"relearn":"With treatment, people with HIV live long, healthy, normal lives.","persona":"Asha","source":"HIV basics / treatment"},
  {"id":"df-039","cat":"hiv-basics","type":"strike-rewrite","hook":"\"You can tell who has HIV just by looking.\"","myth":{"un":"You can tell someone has HIV by how they look.","re":"You cannot tell; people with HIV look just like anyone else.","why":"HIV has no 'look'."},"relearn":"You can't tell who has HIV; they look like anyone else.","persona":"any","source":"HIV basics"},
  {"id":"df-040","cat":"hiv-basics","type":"strike-rewrite","hook":"\"HIV is a punishment for doing something wrong.\"","myth":{"un":"HIV is a punishment for being bad.","re":"HIV is just an infection, not a punishment for anything.","why":"Illness isn't a verdict on a person."},"relearn":"HIV is an infection, never a punishment.","persona":"Asha","source":"HIV basics / anti-stigma"},
  {"id":"df-041","cat":"hiv-basics","type":"strike-rewrite","hook":"\"There's nothing doctors can do about HIV.\"","myth":{"un":"Doctors can't do anything about HIV.","re":"Medicine controls HIV so well that people stay healthy for life.","why":"HIV care has come a very long way."},"relearn":"Medicine controls HIV; people on treatment stay healthy.","persona":"Asha","source":"HIV basics / treatment"},
  {"id":"df-042","cat":"hiv-basics","type":"sort","hook":"Sort: true or false about HIV?","items":[{"id":"a","text":"Medicine helps people with HIV stay well"},{"id":"b","text":"HIV makes someone a bad person"},{"id":"c","text":"Anyone can get HIV"},{"id":"d","text":"You can spot HIV by looking"}],"bins":[{"id":"true","label":"True"},{"id":"false","label":"False"}],"key":{"a":"true","b":"false","c":"true","d":"false"},"relearn":"HIV is treatable, can affect anyone, and is invisible from outside.","persona":"any","source":"HIV basics"},
  {"id":"df-043","cat":"hiv-basics","type":"sort","hook":"Sort: how HIV mainly spreads, or how it does NOT?","items":[{"id":"a","text":"Through blood (like shared needles)"},{"id":"b","text":"From a parent to a baby"},{"id":"c","text":"From a friendly hug"},{"id":"d","text":"From sharing lunch"}],"bins":[{"id":"how","label":"How it can spread"},{"id":"not","label":"NOT how it spreads"}],"key":{"a":"how","b":"how","c":"not","d":"not"},"relearn":"HIV can spread through blood or parent-to-baby; never through hugs or sharing food.","persona":"Asha","source":"HIV basics / transmission"},
  {"id":"df-044","cat":"hiv-basics","type":"branch","hook":"You hear a scary rumour about HIV and aren't sure what's true.","options":[{"text":"Ask a trusted adult or health worker for the facts","consequence":"You get the truth instead of fear.","outcome":"informed","best":true},{"text":"Believe and repeat the rumour","consequence":"Checking facts beats spreading a scary rumour."}],"debrief":"Facts from a trusted source beat rumours every time.","relearn":"Check HIV facts with a trusted adult or health worker.","persona":"Asha","source":"HIV basics / help-seeking"},
  {"id":"df-045","cat":"hiv-basics","type":"branch","hook":"A friend says \"older kids learn more about how HIV spreads, right?\"","options":[{"text":"\"Yes, and the main thing now is: it's not from everyday contact\"","consequence":"You keep it age-right and stigma-free.","outcome":"wise","best":true},{"text":"Make up scary details","consequence":"Keep to what you know: it's not from everyday contact."}],"debrief":"You'll learn more as you grow; for now, everyday contact is safe.","relearn":"You learn more about HIV as you grow; everyday contact is always safe.","persona":"any","source":"HIV basics / age-appropriate"},
  {"id":"df-046","cat":"hiv-basics","type":"spot","hook":"A health poster. Spot the accurate messages.","scene":[{"id":"a","text":"\"People with HIV can live full, healthy lives\"","trick":true},{"id":"b","text":"The poster is green","trick":false},{"id":"c","text":"\"HIV is not spread by everyday contact\"","trick":true}],"why":"Both messages are true and help fight fear and stigma.","relearn":"Accurate HIV messages: treatment works, and everyday contact is safe.","persona":"Asha","source":"HIV basics"},
  {"id":"df-047","cat":"hiv-basics","type":"reflect","hook":"Lensy: knowing the facts about HIV makes it less scary. Agree?","prompt":"What do you think?","options":["Yes","Facts beat fear","Much less scary"],"affirm":"Facts replace fear with understanding and kindness.","relearn":"Knowing the facts about HIV replaces fear with understanding.","persona":"any","source":"HIV basics"},
  {"id":"df-048","cat":"hiv-basics","type":"reflect","hook":"Lensy: a person with HIV is a whole person, not their virus. Makes sense?","prompt":"What do you think?","options":["Yes","They're a person first","Of course"],"affirm":"People are always more than any illness they live with.","relearn":"A person living with HIV is a whole person, not defined by it.","persona":"Asha","source":"HIV basics / dignity"},
  // — Spreads, or doesn't? —
  {"id":"df-049","cat":"spreads-or-not","type":"strike-rewrite","hook":"\"You can get HIV from hugging someone who has it.\"","myth":{"un":"Hugging someone with HIV can give you HIV.","re":"HIV is never spread by hugging; hug freely.","why":"HIV isn't in everyday touch."},"relearn":"You cannot get HIV from a hug.","persona":"any","source":"transmission / stigma (CDC)"},
  {"id":"df-050","cat":"spreads-or-not","type":"strike-rewrite","hook":"\"Sharing food or a plate spreads HIV.\"","myth":{"un":"Sharing food or a plate with someone with HIV spreads it.","re":"HIV does not spread through food, plates or cups.","why":"It's not carried that way."},"relearn":"You cannot get HIV from sharing food, plates or cups.","persona":"Asha","source":"transmission / stigma (CDC)"},
  {"id":"df-051","cat":"spreads-or-not","type":"strike-rewrite","hook":"\"Mosquito bites can give you HIV.\"","myth":{"un":"A mosquito that bit someone with HIV can give it to you.","re":"Mosquitoes do not spread HIV at all.","why":"The virus can't survive or pass on that way."},"relearn":"Mosquitoes do not spread HIV.","persona":"any","source":"transmission / stigma (CDC)"},
  {"id":"df-052","cat":"spreads-or-not","type":"strike-rewrite","hook":"\"You can catch HIV from a toilet seat.\"","myth":{"un":"Using the same toilet seat spreads HIV.","re":"HIV is not spread by toilet seats.","why":"It isn't passed by surfaces."},"relearn":"You cannot get HIV from a toilet seat.","persona":"any","source":"transmission / stigma (CDC)"},
  {"id":"df-053","cat":"spreads-or-not","type":"strike-rewrite","hook":"\"Sitting next to a classmate with HIV is risky.\"","myth":{"un":"Sitting next to a classmate with HIV could infect you.","re":"Sharing a class, desk or bench is completely safe.","why":"Everyday closeness doesn't spread HIV."},"relearn":"Sharing a class or bench with someone with HIV is completely safe.","persona":"Diya","source":"transmission / stigma"},
  {"id":"df-054","cat":"spreads-or-not","type":"strike-rewrite","hook":"\"HIV spreads through coughs and sneezes like a cold.\"","myth":{"un":"HIV spreads through the air like a cold.","re":"HIV is not airborne; coughs and sneezes don't spread it.","why":"It isn't a respiratory germ."},"relearn":"HIV is not airborne; coughs and sneezes don't spread it.","persona":"any","source":"transmission / stigma"},
  {"id":"df-055","cat":"spreads-or-not","type":"strike-rewrite","hook":"\"Playing sport with someone with HIV will infect you.\"","myth":{"un":"Playing sport or games with someone with HIV infects you.","re":"Playing together is safe; HIV isn't passed in everyday play.","why":"Sweat and casual contact don't spread it."},"relearn":"Playing sport or games with someone with HIV is safe.","persona":"Aarav","source":"transmission / stigma"},
  {"id":"df-056","cat":"spreads-or-not","type":"strike-rewrite","hook":"\"Being friends with someone with HIV puts you at risk.\"","myth":{"un":"Just being friends with someone with HIV is risky.","re":"Friendship is completely safe; your friend stays your friend.","why":"None of the things friends do spread HIV."},"relearn":"Being friends with someone with HIV is completely safe.","persona":"any","source":"transmission / stigma"},
  {"id":"df-057","cat":"spreads-or-not","type":"sort","hook":"Sort: can spread HIV, or cannot?","items":[{"id":"a","text":"Sharing needles"},{"id":"b","text":"A hug"},{"id":"c","text":"Shaking hands"},{"id":"d","text":"Sharing food"}],"bins":[{"id":"can","label":"Can spread it"},{"id":"cannot","label":"Cannot"}],"key":{"a":"can","b":"cannot","c":"cannot","d":"cannot"},"relearn":"HIV can spread by shared needles, but not by hugs, handshakes or food.","persona":"Asha","source":"transmission"},
  {"id":"df-058","cat":"spreads-or-not","type":"sort","hook":"Sort: safe everyday thing, or actual risk?","items":[{"id":"a","text":"Sharing a water bottle with a friend with HIV"},{"id":"b","text":"A doctor using clean, new needles"},{"id":"c","text":"Hugging a relative with HIV"},{"id":"d","text":"Sharing a toothbrush or razor (blood)"}],"bins":[{"id":"safe","label":"Safe"},{"id":"avoid","label":"Avoid (blood risk)"}],"key":{"a":"safe","b":"safe","c":"safe","d":"avoid"},"relearn":"Sharing food and hugs are safe; only blood-contact items like razors are avoided.","persona":"any","source":"transmission"},
  {"id":"df-059","cat":"spreads-or-not","type":"sort","hook":"Sort: everyday contact (safe), or not how friends interact?","items":[{"id":"a","text":"Sitting together"},{"id":"b","text":"Sharing a pencil"},{"id":"c","text":"Eating lunch side by side"},{"id":"d","text":"Laughing together"}],"bins":[{"id":"safe","label":"Safe everyday contact"},{"id":"risk","label":"A real risk"}],"key":{"a":"safe","b":"safe","c":"safe","d":"safe"},"relearn":"All everyday friendly contact with someone with HIV is safe.","persona":"any","source":"transmission / stigma"},
  {"id":"df-060","cat":"spreads-or-not","type":"sort","hook":"Sort: fact, or myth?","items":[{"id":"a","text":"\"HIV spreads through hugs\""},{"id":"b","text":"\"HIV is not airborne\""},{"id":"c","text":"\"Mosquitoes spread HIV\""},{"id":"d","text":"\"You can't tell by looking\""}],"bins":[{"id":"fact","label":"Fact"},{"id":"myth","label":"Myth"}],"key":{"a":"myth","b":"fact","c":"myth","d":"fact"},"relearn":"Hugs and mosquitoes are myths; not-airborne and not-visible are facts.","persona":"any","source":"transmission"},
  {"id":"df-061","cat":"spreads-or-not","type":"spot","hook":"A 'how HIV spreads' chart. Spot the wrong (myth) entries.","scene":[{"id":"a","text":"\"By sharing meals\" listed as a way it spreads","trick":true},{"id":"b","text":"\"Through certain body fluids\" listed","trick":false},{"id":"c","text":"\"By holding hands\" listed as a way","trick":true}],"why":"Sharing meals and holding hands are myths; they never spread HIV.","relearn":"Watch for myths on charts: meals and hand-holding never spread HIV.","persona":"any","source":"transmission / media literacy"},
  {"id":"df-062","cat":"spreads-or-not","type":"spot","hook":"A leaflet. Spot the reassuring true facts.","scene":[{"id":"a","text":"\"Everyday contact is safe\"","trick":true},{"id":"b","text":"\"Leaflet printed locally\"","trick":false},{"id":"c","text":"\"Treatment keeps people healthy\"","trick":true}],"why":"Everyday contact being safe and treatment working are both true and reassuring.","relearn":"True, reassuring facts: everyday contact is safe; treatment works.","persona":"Asha","source":"transmission"},
  {"id":"df-063","cat":"spreads-or-not","type":"branch","hook":"A classmate refuses to share a bench with a kid rumoured to have HIV.","options":[{"text":"Explain calmly that sitting together is totally safe","consequence":"You replace fear with a fact.","outcome":"informed","best":true},{"text":"Move away too, just in case","consequence":"Sitting together is safe; the fear is based on a myth."}],"debrief":"Knowing it's safe lets you act with facts, not fear.","relearn":"Sitting with someone with HIV is safe; share the bench.","persona":"Diya","source":"transmission / stigma action"},
  {"id":"df-064","cat":"spreads-or-not","type":"branch","hook":"Someone says \"don't drink from that cup, she has HIV\".","options":[{"text":"Say \"HIV doesn't spread through cups, it's fine\"","consequence":"You correct the myth kindly.","outcome":"informed","best":true},{"text":"Throw the cup away dramatically","consequence":"Cups don't spread HIV; there's no need to fear."}],"debrief":"Correcting a transmission myth protects someone from cruelty.","relearn":"HIV doesn't spread through cups; correct that myth.","persona":"any","source":"transmission / stigma action"},
  {"id":"df-065","cat":"spreads-or-not","type":"reflect","hook":"Lensy: most 'ways HIV spreads' that scare people are myths. Surprising?","prompt":"What do you think?","options":["Yes","Most are myths","Good to know"],"affirm":"Most fears about catching HIV from daily life simply aren't true.","relearn":"Most everyday fears about catching HIV are myths.","persona":"any","source":"transmission"},
  {"id":"df-066","cat":"spreads-or-not","type":"reflect","hook":"Lensy: if everyday contact is safe, what does that mean for friends with HIV?","prompt":"What do you think?","options":["We can be normal friends","Hug, share, play freely","Nothing to fear"],"affirm":"It means you can be a completely normal friend.","relearn":"Since everyday contact is safe, you can be a normal friend.","persona":"Diya","source":"transmission / stigma"},
  // — Kindness, not fear —
  {"id":"df-067","cat":"kindness-not-fear","type":"branch","hook":"A new classmate is known to be living with HIV; others keep their distance.","options":[{"text":"Welcome them and sit with them like anyone else","consequence":"They feel included; others see it's safe.","outcome":"kind","best":true},{"text":"Keep your distance like the others","consequence":"It's safe and kind to include them fully."}],"debrief":"Including someone with HIV is both safe and the right thing.","relearn":"Include someone living with HIV just like any other friend.","persona":"Diya","source":"stigma reduction"},
  {"id":"df-068","cat":"kindness-not-fear","type":"branch","hook":"Kids are whispering and excluding a child because of an illness.","options":[{"text":"Go include them and gently correct the fear","consequence":"You break the exclusion with facts and warmth.","outcome":"upstander","best":true},{"text":"Join the whispering","consequence":"Including them and sharing facts beats whispering."}],"debrief":"Exclusion based on illness-fear can be undone with kindness and facts.","relearn":"You can include someone shut out over illness, and correct the fear.","persona":"any","source":"stigma reduction / upstander (links g19)"},
  {"id":"df-069","cat":"kindness-not-fear","type":"branch","hook":"A relative says people with HIV should be kept apart.","options":[{"text":"Share calmly that everyday contact is safe","consequence":"You offer a fact that softens the fear.","outcome":"informed","best":true},{"text":"Agree to avoid conflict","consequence":"A gentle fact can ease an elder's fear."}],"debrief":"Even with elders, a calm fact can reduce stigma.","relearn":"You can gently correct an elder's fear about HIV with facts.","persona":"Asha","source":"stigma reduction / respect"},
  {"id":"df-070","cat":"kindness-not-fear","type":"branch","hook":"Your friend is scared to tell anyone a family member has HIV.","options":[{"text":"Be a safe, kind friend who keeps it private and supportive","consequence":"Your friend feels less alone.","outcome":"caring","best":true},{"text":"Tell others it's 'big news'","consequence":"A health matter is private; be a supportive, discreet friend."}],"debrief":"Someone's health is private; kindness means support, not gossip.","relearn":"Keep others' health private; offer support, not gossip.","persona":"any","source":"stigma reduction / privacy"},
  {"id":"df-071","cat":"kindness-not-fear","type":"branch","hook":"You catch yourself feeling a little scared around someone with HIV.","options":[{"text":"Remind yourself of the facts and act normally","consequence":"Your knowledge calms the fear.","outcome":"growth","best":true},{"text":"Avoid them to be 'safe'","consequence":"The facts say it's safe; let them calm the fear."}],"debrief":"It's okay to feel unsure; let facts guide you back to kindness.","relearn":"Let the facts calm any fear so you can act with kindness.","persona":"Aarav","source":"stigma reduction / self"},
  {"id":"df-072","cat":"kindness-not-fear","type":"role-play","hook":"A friend mocks a classmate over an illness.","setup":"Stand up for them. Say:","yourLine":[{"text":"\"That's not okay, and it's not even how it spreads.\"","best":true},{"text":"Laugh along"}],"relearn":"You can defend someone and correct the myth at once.","persona":"Aarav","source":"stigma reduction / voice"},
  {"id":"df-073","cat":"kindness-not-fear","type":"role-play","hook":"Someone says \"stay away from them, they're sick\".","setup":"Reassure and include. Say:","yourLine":[{"text":"\"It's safe, come on, let's all play together.\"","best":true},{"text":"\"Okay, I'll stay away too.\""}],"relearn":"You can lead others back to including someone.","persona":"Diya","source":"stigma reduction / voice"},
  {"id":"df-074","cat":"kindness-not-fear","type":"role-play","hook":"A child with HIV looks left out at lunch.","setup":"Invite them in. Say:","yourLine":[{"text":"\"Come sit with us!\"","best":true},{"text":"Look away"}],"relearn":"A simple 'come sit with us' fights stigma powerfully.","persona":"any","source":"stigma reduction / inclusion"},
  {"id":"df-075","cat":"kindness-not-fear","type":"role-play","hook":"Friends are spreading a scary HIV rumour about someone.","setup":"Stop the rumour. Say:","yourLine":[{"text":"\"That's not true, and it's unkind, let's drop it.\"","best":true},{"text":"Pass the rumour on"}],"relearn":"You can refuse to spread a hurtful, untrue rumour.","persona":"any","source":"stigma reduction / voice"},
  {"id":"df-076","cat":"kindness-not-fear","type":"role-play","hook":"A classmate with HIV is nervous you'll treat them differently.","setup":"Put them at ease. Say:","yourLine":[{"text":"\"You're my friend, same as always.\"","best":true},{"text":"Act awkward around them"}],"relearn":"Treating a friend the same as always is the kindest message.","persona":"Diya","source":"stigma reduction / friendship"},
  {"id":"df-077","cat":"kindness-not-fear","type":"role-play","hook":"Your younger sibling repeats a stigma myth they heard.","setup":"Gently teach them. Say:","yourLine":[{"text":"\"Actually you can't catch HIV that way, let me explain.\"","best":true},{"text":"Let the myth stand"}],"relearn":"You can pass accurate, kind facts to younger kids.","persona":"any","source":"stigma reduction / mentoring"},
  {"id":"df-078","cat":"kindness-not-fear","type":"role-play","hook":"A teacher asks the class to welcome a student with a health condition.","setup":"Set a warm tone. Say:","yourLine":[{"text":"\"Welcome! You'll like it here.\"","best":true},{"text":"Stay silent and unsure"}],"relearn":"A warm welcome sets the tone for everyone else.","persona":"any","source":"stigma reduction / inclusion"},
  {"id":"df-079","cat":"kindness-not-fear","type":"role-play","hook":"Someone insists HIV makes a person 'less'.","setup":"Affirm their worth. Say:","yourLine":[{"text":"\"Having HIV doesn't make anyone less of a person.\"","best":true},{"text":"Say nothing"}],"relearn":"A person's worth is never reduced by an illness.","persona":"Asha","source":"stigma reduction / dignity"},
  {"id":"df-080","cat":"kindness-not-fear","type":"strike-rewrite","hook":"\"People with HIV should be kept separate from everyone.\"","myth":{"un":"People with HIV should be kept apart from others.","re":"They belong fully in school, play and friendship; it's safe.","why":"Separation is based on fear, not facts."},"relearn":"People with HIV belong fully in everyday life; separating them is wrong.","persona":"any","source":"stigma reduction"},
  {"id":"df-081","cat":"kindness-not-fear","type":"strike-rewrite","hook":"\"It's fine to tease someone about being ill.\"","myth":{"un":"Teasing someone about an illness is harmless fun.","re":"Mocking illness is cruel and can really hurt.","why":"No one chooses to be ill."},"relearn":"Teasing someone about illness is cruel, not funny.","persona":"any","source":"stigma reduction"},
  {"id":"df-082","cat":"kindness-not-fear","type":"reflect","hook":"Lensy: the real 'defender of the body' includes defending others' dignity. See it?","prompt":"What do you think?","options":["Yes","Defend dignity too","Kindness is strength"],"affirm":"Defending someone's dignity is the bravest defence of all.","relearn":"Being a defender includes protecting others' dignity, not just health.","persona":"any","source":"stigma reduction / values"},
  {"id":"df-083","cat":"kindness-not-fear","type":"reflect","hook":"Lensy: biggest take-away from Defenders of the Body?","prompt":"Pick your motto.","options":["My body defends me","Germs spread in known ways","HIV isn't everyday contact","Kindness, not fear"],"affirm":"Strong body, clear facts, open heart, you're a true defender.","relearn":"Know your defences, know the facts, and choose kindness over fear.","persona":"any","source":"consolidation"},
  {"id":"df-084","cat":"kindness-not-fear","type":"reflect","hook":"Lensy: would you be a kind, fact-knowing friend to someone with HIV now?","prompt":"What do you think?","options":["Definitely","Yes, easily","Friend, same as always"],"affirm":"That's exactly the defender the world needs more of.","relearn":"You can be a safe, kind, well-informed friend to anyone with HIV.","persona":"Diya","source":"consolidation"},
];

export const DEFENDERS: V2GameConfig = {
  gameId: "defenders",
  title: "Defenders of the Body",
  greet: "Hey, it's Lensy. 🛡️ Your body has a whole defence team inside it. Let's meet your defenders, learn how germs really spread, get the real facts about HIV — and the biggest lesson of all: kindness, not fear.",
  scenarios: SCENARIOS,
  categories: [
    { id: "body-defenders", emoji: "🛡️", label: "Your defenders" },
    { id: "how-germs-spread", emoji: "🦠", label: "How germs spread" },
    { id: "defend-yourself", emoji: "🧼", label: "Defend yourself" },
    { id: "hiv-basics", emoji: "📘", label: "HIV, simply" },
    { id: "spreads-or-not", emoji: "⚖️", label: "Spreads, or not?" },
    { id: "kindness-not-fear", emoji: "💛", label: "Kindness, not fear" },
  ],
  badge: {
    title: "Body Defender! 🛡️",
    blurb: "You know your body's defence team, how germs really spread, the real facts about HIV — and that people living with HIV belong fully, with kindness, not fear. 💛",
  },
  helpLine: "If you're worried about an illness — yours or someone else's — talk to a trusted grown-up, your school nurse or a doctor. For health questions you can call Childline, one-zero-nine-eight. The facts beat fear every time.",
  helpLabel: "Get the facts · Childline 1098",
  reassure: "HIV is a virus, never a punishment or a sign of a 'bad' person — and people living with HIV belong fully in school, play and friendship. Choose kindness, not fear. 💛",
  reassureCats: ["hiv-basics", "kindness-not-fear"],
};
