// Content for Equalize (node g26, ages 12–15, Chapter 4) — NEW v2 build to GDD 26 (mechanic-embodying), the
// gender-equality BALANCING-SIM node (Thread E · Gender & Respect). "Equality isn't just a belief — it's
// something you live, and it lifts everyone." 84 researched, India-grounded scenarios across the
// belief-vs-practice → unpaid-load → pay-and-power → pays-off → child-marriage → rebalance-it arc, each
// encoded as one of the shared v2 play actions (branch / strike-rewrite / sort / reflect / match / role-play /
// build) — no binary "tap the right card". Lead mechanics: branch (rebalance choices ×23), strike-rewrite
// (bust the myth ×17), sort (gap vs lived practice ×15). Teaches: spotting the gap between believing in
// equality and living it, the invisible unpaid-care load, pay & power gaps, how equality PAYS OFF for
// everyone (boys/men included — it's not zero-sum), and rebalancing home/school/community. EVENHANDED.
// CHILD MARRIAGE is handled as a RIGHTS ISSUE — respectful, non-graphic, legally accurate (illegal in India;
// 18 for girls), never blaming the target ("it's not her fault"), evenhanded (it harms boys too), and it
// always routes an at-risk child to a trusted adult / Childline 1098. Builds on g10 (Fair Play World); prereq
// g25. Rendered by the shared engine (components/games/v2-engine.tsx). gameId "equalize". DO NOT RENAME.

import type { Scenario, V2GameConfig } from "./v2-schema";

const SCENARIOS: Scenario[] = [
  // — Belief vs practice —
  {"id":"eq-001","cat":"belief-vs-practice","type":"sort","hook":"Sort: a belief in equality, or equality actually practised?","items":[{"id":"a","text":"\"I think chores should be shared\""},{"id":"b","text":"Dad and son also cook and clean"},{"id":"c","text":"\"Of course women can lead\""},{"id":"d","text":"The girl is actually made class captain"}],"bins":[{"id":"belief","label":"Just a belief"},{"id":"practice","label":"Lived practice"}],"key":{"a":"belief","b":"practice","c":"belief","d":"practice"},"relearn":"Believing in equality and living it are different; the gap is the issue.","persona":"any","source":"belief-action gap"},
  {"id":"eq-002","cat":"belief-vs-practice","type":"sort","hook":"Sort: where's the gap between words and action?","items":[{"id":"a","text":"Says girls are equal, but only sons inherit"},{"id":"b","text":"Says and shares decisions equally"},{"id":"c","text":"Praises working women, expects daughter to quit"},{"id":"d","text":"Backs his daughter's career fully"}],"bins":[{"id":"gap","label":"A gap"},{"id":"aligned","label":"Words match action"}],"key":{"a":"gap","b":"aligned","c":"gap","d":"aligned"},"relearn":"Spot where fine words about equality don't match what's done.","persona":"any","source":"belief-action gap"},
  {"id":"eq-003","cat":"belief-vs-practice","type":"sort","hook":"Sort: equal in theory, or equal in practice, at home?","items":[{"id":"a","text":"Everyone says the home is shared"},{"id":"b","text":"Mum still does almost all of it"},{"id":"c","text":"Tasks are actually split fairly"},{"id":"d","text":"Only girls are asked to help"}],"bins":[{"id":"practice","label":"Equal in practice"},{"id":"theory","label":"Only in theory"}],"key":{"a":"theory","b":"theory","c":"practice","d":"theory"},"relearn":"A home is only equal when the work is actually shared, not just claimed.","persona":"Rohit","source":"home / practice"},
  {"id":"eq-004","cat":"belief-vs-practice","type":"strike-rewrite","hook":"\"We already have equality, so there's nothing left to do.\"","myth":{"un":"Equality is already achieved; there's nothing left to do.","re":"Belief has moved faster than practice; real gaps remain.","why":"Saying it's done hides the work still needed."},"relearn":"Believing in equality isn't the same as having achieved it.","persona":"any","source":"belief-action gap"},
  {"id":"eq-005","cat":"belief-vs-practice","type":"strike-rewrite","hook":"\"If people say the right things, that's enough.\"","myth":{"un":"Saying the right things about equality is enough.","re":"Equality lives in what we actually do, not just say.","why":"Action is what changes lives."},"relearn":"Equality is what you do, not only what you say.","persona":"any","source":"practice"},
  {"id":"eq-006","cat":"belief-vs-practice","type":"reflect","hook":"Lensy: where do you notice the gap between 'we believe in equality' and real life?","prompt":"Pick one.","options":["At home","At school","Around me","Everywhere a bit"],"affirm":"Noticing the gap is the first step to closing it.","relearn":"Spotting the belief-practice gap is how you start to close it.","persona":"any","source":"awareness"},
  {"id":"eq-007","cat":"belief-vs-practice","type":"reflect","hook":"Lensy: have you ever believed something is fair but not actually done it?","prompt":"Be honest.","options":["Yes","Probably","I'll do better"],"affirm":"We all have gaps; closing your own is real progress.","relearn":"We all have belief-action gaps; closing yours matters.","persona":"any","source":"self"},
  {"id":"eq-008","cat":"belief-vs-practice","type":"reflect","hook":"Lensy: why do you think practice lags so far behind belief?","prompt":"What do you think?","options":["Old habits","No one rebalances it","It's invisible","All of these"],"affirm":"Habits and invisibility keep gaps alive, until someone rebalances.","relearn":"Gaps persist through habit and invisibility until we act.","persona":"any","source":"systems"},
  {"id":"eq-009","cat":"belief-vs-practice","type":"branch","hook":"Your family says it values equality, but you do nothing at home while your sister does it all.","options":[{"text":"Start pitching in to close your own gap","consequence":"You make the belief real at home.","outcome":"changemaker","best":true},{"text":"Keep enjoying the unfair setup","consequence":"Living the belief means sharing the load yourself."}],"debrief":"Closing the gap starts with your own actions, not just words.","relearn":"Live the equality you believe in by sharing the load.","persona":"Veer","source":"home / action"},
  {"id":"eq-010","cat":"belief-vs-practice","type":"branch","hook":"A class 'believes in equality' but only picks boys for the science fair.","options":[{"text":"Point out the gap and push for fair selection","consequence":"The class lives up to its words.","outcome":"changemaker","best":true},{"text":"Let the pattern continue","consequence":"Naming the gap turns belief into fair practice."}],"debrief":"Calling out a belief-practice gap helps a group live its values.","relearn":"You can name a gap so a group lives its stated values.","persona":"Riya","source":"school / action"},
  {"id":"eq-011","cat":"belief-vs-practice","type":"branch","hook":"You're rebalancing a 'believes-in-equality' home in the sim.","options":[{"text":"Redistribute the real tasks and decisions fairly","consequence":"The home moves from talk to true balance.","outcome":"balanced","best":true},{"text":"Only change the slogans on the wall","consequence":"Rebalance the real tasks, not just the words."}],"debrief":"Real rebalancing changes what people do, not just what they say.","relearn":"Rebalancing means changing actions, not slogans.","persona":"any","source":"balancing-sim"},
  {"id":"eq-012","cat":"belief-vs-practice","type":"sort","hook":"Sort: closes the belief-practice gap, or just talks?","items":[{"id":"a","text":"Sharing chores from today"},{"id":"b","text":"Posting an equality quote"},{"id":"c","text":"Giving the girl her turn to lead"},{"id":"d","text":"Saying 'I support equality'"}],"bins":[{"id":"closes","label":"Closes the gap"},{"id":"talks","label":"Just talk"}],"key":{"a":"closes","b":"talks","c":"closes","d":"talks"},"relearn":"Actions like sharing and giving turns close the gap; talk alone doesn't.","persona":"any","source":"action"},
  {"id":"eq-013","cat":"belief-vs-practice","type":"sort","hook":"Sort: a fair practice, or unfair, in a 'modern' family?","items":[{"id":"a","text":"Son and daughter both study and help"},{"id":"b","text":"Daughter cooks while son studies"},{"id":"c","text":"Both get the same curfew"},{"id":"d","text":"Only the girl has a strict curfew"}],"bins":[{"id":"fair","label":"Fair practice"},{"id":"unfair","label":"Unfair"}],"key":{"a":"fair","b":"unfair","c":"fair","d":"unfair"},"relearn":"Equal study, help and rules show equality is actually being lived.","persona":"any","source":"home / practice"},
  {"id":"eq-014","cat":"belief-vs-practice","type":"reflect","hook":"Lensy: imagine if belief and practice matched everywhere. Different world?","prompt":"What do you think?","options":["Hugely","Fairer for all","Worth building"],"affirm":"Closing the gap, home by home, builds exactly that world.","relearn":"A fairer world is built by closing the belief-practice gap.","persona":"any","source":"vision"},
  // — The unpaid load —
  {"id":"eq-015","cat":"unpaid-load","type":"branch","hook":"At home, the cooking, cleaning and care all fall on the women. Rebalance it.","options":[{"text":"Share the tasks across everyone, by ability not gender","consequence":"The load lightens and it's fair.","outcome":"balanced","best":true},{"text":"Leave it all to the women","consequence":"Sharing the unpaid load fairly is the rebalance."}],"debrief":"Unpaid work shared fairly is the heart of a balanced home.","relearn":"Share the unpaid home load by ability, not by gender.","persona":"Rohit","source":"unpaid care (verified)"},
  {"id":"eq-016","cat":"unpaid-load","type":"branch","hook":"Your mum works all day, then does all the housework while others relax.","options":[{"text":"Step up and take a real share of the work","consequence":"Her 'second shift' eases; the home is fairer.","outcome":"caring","best":true},{"text":"Assume it's just her job","consequence":"Her double shift is real; share the load."}],"debrief":"The 'second shift' is invisible work; sharing it is true equality.","relearn":"You can share the invisible 'second shift' at home.","persona":"Veer","source":"second shift"},
  {"id":"eq-017","cat":"unpaid-load","type":"branch","hook":"Relatives expect only the girls to serve guests while boys sit.","options":[{"text":"Have everyone, boys included, help host","consequence":"Hosting becomes a shared, fairer job.","outcome":"changemaker","best":true},{"text":"Follow the old serving rule","consequence":"Hosting can be shared by everyone, not just girls."}],"debrief":"Serving guests can be everyone's job, not just the girls'.","relearn":"Hosting and serving can be shared by all, not just girls.","persona":"any","source":"home / India"},
  {"id":"eq-018","cat":"unpaid-load","type":"branch","hook":"You notice you leave your dishes for your sister 'because that's her thing'.","options":[{"text":"Own your own mess from now on","consequence":"You stop adding to her unfair load.","outcome":"accountable","best":true},{"text":"Keep leaving it","consequence":"Cleaning up after yourself lightens her load."}],"debrief":"Doing your own share is the simplest rebalance there is.","relearn":"Carry your own share of the home's work.","persona":"Veer","source":"accountability"},
  {"id":"eq-019","cat":"unpaid-load","type":"branch","hook":"In the sim, a household runs on the mum's unpaid work alone.","options":[{"text":"Redistribute care and chores so it's sustainable for all","consequence":"The home thrives and everyone contributes.","outcome":"balanced","best":true},{"text":"Pile more onto her","consequence":"A home runs better when care is shared, not dumped."}],"debrief":"A home built on one person's unpaid work isn't balanced or kind.","relearn":"Care and chores work best shared across the whole home.","persona":"Rohit","source":"balancing-sim"},
  {"id":"eq-020","cat":"unpaid-load","type":"sort","hook":"Sort: counts as real work, even if unpaid?","items":[{"id":"a","text":"Cooking every meal"},{"id":"b","text":"Caring for elders"},{"id":"c","text":"Cleaning the house"},{"id":"d","text":"Relaxing on the sofa"}],"bins":[{"id":"work","label":"Real (unpaid) work"},{"id":"rest","label":"Rest"}],"key":{"a":"work","b":"work","c":"work","d":"rest"},"relearn":"Cooking, caring and cleaning are real work, even when unpaid.","persona":"any","source":"unpaid work"},
  {"id":"eq-021","cat":"unpaid-load","type":"sort","hook":"Sort: lightens the load fairly, or keeps it lopsided?","items":[{"id":"a","text":"A chore rota for everyone"},{"id":"b","text":"\"Girls help, boys rest\""},{"id":"c","text":"Dad doing bedtime"},{"id":"d","text":"Only mum on call 24/7"}],"bins":[{"id":"fair","label":"Lightens fairly"},{"id":"lopsided","label":"Keeps it lopsided"}],"key":{"a":"fair","b":"lopsided","c":"fair","d":"lopsided"},"relearn":"Rotas and shared parenting lighten the load fairly.","persona":"any","source":"home"},
  {"id":"eq-022","cat":"unpaid-load","type":"sort","hook":"Sort: who can do this household task?","items":[{"id":"a","text":"Cook"},{"id":"b","text":"Fix a tap"},{"id":"c","text":"Bathe a baby"},{"id":"d","text":"Pay the bills"}],"bins":[{"id":"anyone","label":"Anyone"},{"id":"gendered","label":"One gender only"}],"key":{"a":"anyone","b":"anyone","c":"anyone","d":"anyone"},"relearn":"Every household task can be done by anyone.","persona":"Rohit","source":"home / roles"},
  {"id":"eq-023","cat":"unpaid-load","type":"build","hook":"Build a fair household rota.","prompt":"Assemble a fair-share plan.","pieces":["list all the chores and care","split by who's free, not gender","rotate the boring jobs","everyone owns their own mess"],"mode":"assemble","key":["list all the chores and care","split by who's free, not gender","rotate the boring jobs","everyone owns their own mess"],"relearn":"A fair home: list it, split by availability, rotate, own your mess.","persona":"any","source":"home / planning"},
  {"id":"eq-024","cat":"unpaid-load","type":"build","hook":"Build the case for why unpaid work should count.","prompt":"Assemble the points.","pieces":["it takes real time and effort","it keeps everyone going","it's worth a lot economically","so it should be shared and valued"],"mode":"assemble","key":["it takes real time and effort","it keeps everyone going","it's worth a lot economically","so it should be shared and valued"],"relearn":"Unpaid work is real, vital and valuable, so it should be shared.","persona":"any","source":"unpaid care economics"},
  {"id":"eq-025","cat":"unpaid-load","type":"match","hook":"Match the home job to who can do it.","pairs":[{"left":"Cooking","right":"Anyone"},{"left":"Childcare","right":"Any parent"},{"left":"Repairs","right":"Anyone who learns"}],"relearn":"Home jobs aren't gendered; anyone can learn and do them.","persona":"any","source":"home"},
  {"id":"eq-026","cat":"unpaid-load","type":"match","hook":"Match the unfair pattern to its fairer fix.","pairs":[{"left":"Mum's 'second shift'","right":"Share the housework"},{"left":"Only girls serve","right":"Everyone hosts"},{"left":"Boys never cook","right":"Boys learn to cook"}],"relearn":"Each lopsided home pattern has a simple, fairer fix.","persona":"any","source":"home"},
  {"id":"eq-027","cat":"unpaid-load","type":"reflect","hook":"Lensy: who carries the most invisible work in your home? Could it be shared?","prompt":"What do you think?","options":["Mum, usually","It could be shared","I'll help more"],"affirm":"Seeing the invisible work is the first step to sharing it.","relearn":"Noticing who carries the invisible load helps you share it.","persona":"any","source":"awareness"},
  // — Pay & power —
  {"id":"eq-028","cat":"pay-and-power","type":"sort","hook":"Sort: a real gender gap, or already equal?","items":[{"id":"a","text":"Who gets paid more on average"},{"id":"b","text":"Who holds most top leadership roles"},{"id":"c","text":"Equal right to vote"},{"id":"d","text":"Who does most unpaid care"}],"bins":[{"id":"gap","label":"Still a gap"},{"id":"equal","label":"Already equal"}],"key":{"a":"gap","b":"gap","c":"equal","d":"gap"},"relearn":"Voting is equal, but pay, power and unpaid care still show gaps.","persona":"any","source":"gaps"},
  {"id":"eq-029","cat":"pay-and-power","type":"sort","hook":"Sort: a fair reason for a pay/power gap, or unfair bias?","items":[{"id":"a","text":"Doing a harder, skilled role"},{"id":"b","text":"Being paid less for the same job"},{"id":"c","text":"Earning a promotion"},{"id":"d","text":"Passed over just for being a woman"}],"bins":[{"id":"fair","label":"Fair reason"},{"id":"bias","label":"Unfair bias"}],"key":{"a":"fair","b":"bias","c":"fair","d":"bias"},"relearn":"Skill and effort are fair reasons; same-job pay gaps and bias aren't.","persona":"any","source":"pay gap"},
  {"id":"eq-030","cat":"pay-and-power","type":"sort","hook":"Sort: helps close the power gap, or widens it?","items":[{"id":"a","text":"Mentoring women into leadership"},{"id":"b","text":"\"Leadership is a man's job\""},{"id":"c","text":"Fair, blind hiring"},{"id":"d","text":"Only promoting 'the lads'"}],"bins":[{"id":"closes","label":"Closes the gap"},{"id":"widens","label":"Widens it"}],"key":{"a":"closes","b":"widens","c":"closes","d":"widens"},"relearn":"Mentoring and fair hiring close the power gap; old-boys' networks widen it.","persona":"any","source":"power gap"},
  {"id":"eq-031","cat":"pay-and-power","type":"sort","hook":"Sort: a fact about gaps, or a myth?","items":[{"id":"a","text":"Women do most unpaid care"},{"id":"b","text":"\"Pay is perfectly equal now\""},{"id":"c","text":"Few women in top jobs, still"},{"id":"d","text":"\"Women just don't want to lead\""}],"bins":[{"id":"fact","label":"Fact"},{"id":"myth","label":"Myth"}],"key":{"a":"fact","b":"myth","c":"fact","d":"myth"},"relearn":"Real gaps remain; 'pay is equal' and 'women don't want to lead' are myths.","persona":"any","source":"gaps / myths"},
  {"id":"eq-032","cat":"pay-and-power","type":"strike-rewrite","hook":"\"Women earn less because they choose easier work.\"","myth":{"un":"Women earn less simply because they choose easier work.","re":"Much of the gap is bias and the unpaid-care load, not 'easier choices'.","why":"Same jobs still often pay women less."},"relearn":"The pay gap is largely bias and care load, not 'easier choices'.","persona":"any","source":"pay gap"},
  {"id":"eq-033","cat":"pay-and-power","type":"strike-rewrite","hook":"\"There just aren't women good enough to lead.\"","myth":{"un":"There aren't enough capable women to lead.","re":"There are plenty; barriers, not ability, keep them out.","why":"Remove the barriers and women lead everywhere."},"relearn":"It's barriers, not a lack of able women, that limit women's leadership.","persona":"Riya","source":"power gap"},
  {"id":"eq-034","cat":"pay-and-power","type":"branch","hook":"In the sim, a workplace pays women less for the same role.","options":[{"text":"Set equal pay for equal work","consequence":"Fairness rises and so does morale.","outcome":"balanced","best":true},{"text":"Keep the gap to 'save money'","consequence":"Equal pay for equal work is the fair rebalance."}],"debrief":"Equal pay for equal work is a basic fairness rebalance.","relearn":"Equal work deserves equal pay; rebalance it.","persona":"any","source":"balancing-sim / pay"},
  {"id":"eq-035","cat":"pay-and-power","type":"branch","hook":"A team keeps picking men to present, women to take notes.","options":[{"text":"Rotate roles so everyone leads and supports","consequence":"Talent gets seen across the team.","outcome":"fair","best":true},{"text":"Keep the women on notes","consequence":"Rotating visible roles shares power fairly."}],"debrief":"Who gets the visible roles shapes who gets the power.","relearn":"Rotate visible roles so power is shared, not gendered.","persona":"Riya","source":"power / work"},
  {"id":"eq-036","cat":"pay-and-power","type":"match","hook":"Match the gap to what helps close it.","pairs":[{"left":"Pay gap","right":"Equal pay for equal work"},{"left":"Power gap","right":"Mentoring & fair hiring"},{"left":"Care gap","right":"Sharing unpaid work"}],"relearn":"Each gap has a concrete way to close it.","persona":"any","source":"solutions"},
  {"id":"eq-037","cat":"pay-and-power","type":"match","hook":"Match the woman leader to her field (India).","pairs":[{"left":"Head of State","right":"A woman President"},{"left":"Past PM","right":"Indira Gandhi"},{"left":"Space","right":"Kalpana Chawla"}],"relearn":"Indian women have reached the very top across fields.","persona":"any","source":"role models (India)"},
  {"id":"eq-038","cat":"pay-and-power","type":"reflect","hook":"Lensy: who holds the power in the rooms you know, and is that fair?","prompt":"What do you think?","options":["Mostly men","It varies","Could be fairer"],"affirm":"Noticing who holds power is how fairer rooms get built.","relearn":"Noticing who holds power helps you push for fairer rooms.","persona":"any","source":"awareness"},
  {"id":"eq-039","cat":"pay-and-power","type":"strike-rewrite","hook":"\"A woman leader must act like a man to be respected.\"","myth":{"un":"To be respected, a woman leader must act like a man.","re":"Great leadership comes in every style; she can lead as herself.","why":"There's no single 'right' way to lead."},"relearn":"Women can lead as themselves; there's no one 'manly' way to lead.","persona":"Riya","source":"leadership"},
  // — Equality pays off —
  {"id":"eq-040","cat":"pays-off","type":"strike-rewrite","hook":"\"Equality is a fight where if women win, men lose.\"","myth":{"un":"Gender equality is a zero-sum fight; if women win, men lose.","re":"Equality isn't zero-sum; reducing barriers benefits men too.","why":"Fairer homes and workplaces lift everyone."},"relearn":"Equality isn't men losing; it benefits everyone.","persona":"Veer","source":"not zero-sum (verified)"},
  {"id":"eq-041","cat":"pays-off","type":"strike-rewrite","hook":"\"Men get nothing out of gender equality.\"","myth":{"un":"There's nothing in equality for men.","re":"Men gain freedom, closer relationships and far less pressure.","why":"Loosening 'provide alone, never cry' frees boys too."},"relearn":"Men gain freedom and less pressure from equality.","persona":"Veer","source":"men gain"},
  {"id":"eq-042","cat":"pays-off","type":"strike-rewrite","hook":"\"Equality is just a 'nice idea' with no real payoff.\"","myth":{"un":"Equality is a nice idea with no concrete benefit.","re":"It pays off hugely, fairer homes and trillions added to economies.","why":"Closing gaps grows prosperity for all."},"relearn":"Equality pays off, in fairer homes and stronger economies.","persona":"any","source":"economics (verified)"},
  {"id":"eq-043","cat":"pays-off","type":"strike-rewrite","hook":"\"Keeping women out of work protects men's jobs.\"","myth":{"un":"Keeping women out of work protects men's jobs.","re":"More women working grows the whole economy, helping everyone.","why":"Bigger, fairer economies create more, not fewer, chances."},"relearn":"Women working grows the economy for everyone, not at men's expense.","persona":"any","source":"economics"},
  {"id":"eq-044","cat":"pays-off","type":"strike-rewrite","hook":"\"A man who shares housework is weak or 'whipped'.\"","myth":{"un":"A man who shares housework is weak.","re":"Sharing the load builds respect, partnership and a happier home.","why":"Strength is fairness, not dominance."},"relearn":"Sharing housework is strength and partnership, not weakness.","persona":"Veer","source":"masculinity / home"},
  {"id":"eq-045","cat":"pays-off","type":"strike-rewrite","hook":"\"Equality threatens family and tradition.\"","myth":{"un":"Equality destroys family and tradition.","re":"Fairer families are often closer and stronger, you keep what's good.","why":"You can honour culture and drop what's unfair."},"relearn":"Equality can strengthen families; you keep the good, drop the unfair.","persona":"any","source":"family / culture"},
  {"id":"eq-046","cat":"pays-off","type":"strike-rewrite","hook":"\"Boys lose out when girls get more chances.\"","myth":{"un":"Every chance a girl gains is one a boy loses.","re":"Opportunity isn't a fixed pie; fairness expands it for all.","why":"Lifting everyone grows the whole."},"relearn":"Opportunity isn't a fixed pie; fairness grows it for everyone.","persona":"Veer","source":"not zero-sum"},
  {"id":"eq-047","cat":"pays-off","type":"sort","hook":"Sort: how equality helps boys and men, or doesn't?","items":[{"id":"a","text":"Freedom to show feelings"},{"id":"b","text":"Less pressure to provide alone"},{"id":"c","text":"Being forced to hide weakness"},{"id":"d","text":"Closer family relationships"}],"bins":[{"id":"helps","label":"Helps men"},{"id":"old","label":"Old pressure"}],"key":{"a":"helps","b":"helps","c":"old","d":"helps"},"relearn":"Equality frees men, from sole-provider pressure and hidden feelings.","persona":"Veer","source":"men gain"},
  {"id":"eq-048","cat":"pays-off","type":"sort","hook":"Sort: a payoff of equality, or a myth about it?","items":[{"id":"a","text":"Stronger economy"},{"id":"b","text":"\"Men become useless\""},{"id":"c","text":"Happier, fairer homes"},{"id":"d","text":"\"Society falls apart\""}],"bins":[{"id":"payoff","label":"Real payoff"},{"id":"myth","label":"Myth"}],"key":{"a":"payoff","b":"myth","c":"payoff","d":"myth"},"relearn":"Equality brings stronger economies and fairer homes, not collapse.","persona":"any","source":"economics"},
  {"id":"eq-049","cat":"pays-off","type":"match","hook":"Match the equality move to who it helps.","pairs":[{"left":"Sharing housework","right":"The whole family"},{"left":"Women in the workforce","right":"The economy"},{"left":"Boys allowed to feel","right":"Boys themselves"}],"relearn":"Each step toward equality has a clear, shared payoff.","persona":"any","source":"payoffs"},
  {"id":"eq-050","cat":"pays-off","type":"match","hook":"Match the 'zero-sum' fear to the real, win-win truth.","pairs":[{"left":"\"Women win, men lose\"","right":"Both gain"},{"left":"\"Fewer jobs for men\"","right":"Economy grows"},{"left":"\"Men become weak\"","right":"Men gain freedom"}],"relearn":"The zero-sum fears are myths; equality is win-win.","persona":"Veer","source":"not zero-sum"},
  {"id":"eq-051","cat":"pays-off","type":"branch","hook":"A friend thinks equality means men get pushed down.","options":[{"text":"Show how it frees him too, less pressure, more choice","consequence":"He sees equality as his win as well.","outcome":"ally","best":true},{"text":"Argue he should just accept losing","consequence":"Equality is win-win; show him what he gains."}],"debrief":"The best case for equality to a doubter is what they gain.","relearn":"Show doubters how equality frees them too.","persona":"Veer","source":"persuasion / evenhanded"},
  {"id":"eq-052","cat":"pays-off","type":"branch","hook":"In the sim, a community rebalances toward equality.","options":[{"text":"Invest in girls' schooling and shared work","consequence":"The whole community grows richer and fairer.","outcome":"balanced","best":true},{"text":"Keep resources for boys only","consequence":"Investing in everyone lifts the whole community."}],"debrief":"Communities that rebalance toward equality thrive together.","relearn":"Rebalancing toward equality lifts the whole community.","persona":"any","source":"balancing-sim / economics"},
  {"id":"eq-053","cat":"pays-off","type":"reflect","hook":"Lensy: name one way equality would make YOUR life better.","prompt":"Think of one.","options":["Less pressure","More choices","Fairer home","A partner, not a servant"],"affirm":"Equality has a real, personal payoff for you, whoever you are.","relearn":"Equality has concrete benefits for you personally.","persona":"any","source":"self / payoff"},
  {"id":"eq-054","cat":"pays-off","type":"reflect","hook":"Lensy: 'equality lifts everyone' isn't a slogan, it's measurable. Reassuring?","prompt":"What do you think?","options":["Yes","Win-win is real","Good to know"],"affirm":"The data backs it: fairer really is better, for all.","relearn":"Equality measurably lifts everyone; it's win-win.","persona":"any","source":"economics"},
  {"id":"eq-055","cat":"pays-off","type":"reflect","hook":"Lensy: would you rather a partnership of equals, or a boss-and-servant home?","prompt":"What do you think?","options":["Partnership","Equals","Definitely partnership"],"affirm":"Partnerships of equals are happier, that's the payoff.","relearn":"A partnership of equals beats a boss-and-servant home, for everyone.","persona":"any","source":"relationships / payoff"},
  // — Child marriage (a rights issue) —
  {"id":"eq-056","cat":"child-marriage","type":"strike-rewrite","hook":"\"Marrying girls young is just our tradition, so it's fine.\"","myth":{"un":"Marrying girls young is a tradition, so it's fine.","re":"Child marriage is harmful and illegal in India; the legal age is 18 for girls.","why":"It ends education and risks health; 'tradition' doesn't make it safe."},"relearn":"Child marriage is harmful and illegal in India; girls should grow up first.","persona":"Riya","source":"child marriage law (verified)"},
  {"id":"eq-057","cat":"child-marriage","type":"strike-rewrite","hook":"\"A girl is ready for marriage as soon as she gets her period.\"","myth":{"un":"A girl is ready to marry once she's physically able.","re":"Being physically able isn't being ready; she needs to grow, learn and choose.","why":"Childhood and education come first."},"relearn":"Physical change isn't readiness for marriage; girls need to grow and choose.","persona":"any","source":"child marriage"},
  {"id":"eq-058","cat":"child-marriage","type":"strike-rewrite","hook":"\"Marrying a girl early protects her and the family's honour.\"","myth":{"un":"Early marriage protects girls and family honour.","re":"It removes her education, health and choices, that's harm, not protection.","why":"Real protection is school, safety and a say in her life."},"relearn":"Early marriage harms girls; real protection is education and choice.","persona":"any","source":"child marriage / rights"},
  {"id":"eq-059","cat":"child-marriage","type":"strike-rewrite","hook":"\"Once a girl marries young, nothing can be done.\"","myth":{"un":"If a child marriage is planned, nothing can stop it.","re":"It can be reported and prevented; Childline 1098 and officials help.","why":"The law and helplines exist exactly for this."},"relearn":"A child marriage can be reported and prevented via Childline 1098.","persona":"Counsellor","source":"child marriage / help"},
  {"id":"eq-060","cat":"child-marriage","type":"strike-rewrite","hook":"\"Girls don't need to finish school if they'll be married.\"","myth":{"un":"A girl who'll marry doesn't need to finish school.","re":"Every girl deserves a full education and her own future.","why":"Education is her right, and it transforms lives."},"relearn":"Every girl deserves full education, marriage plans don't cancel that.","persona":"Riya","source":"education / rights"},
  {"id":"eq-061","cat":"child-marriage","type":"branch","hook":"A classmate confides her family is arranging her marriage, and she's 14.","options":[{"text":"Help her tell a trusted adult or call Childline 1098","consequence":"She gets real protection and options.","outcome":"protective","best":true},{"text":"Tell her to just accept it","consequence":"This is reportable; help her reach a trusted adult or Childline 1098."}],"debrief":"Child marriage is preventable; helping her reach help can change her life.","relearn":"Help a friend facing child marriage reach a trusted adult or Childline 1098.","persona":"Counsellor","source":"safeguarding (verified)"},
  {"id":"eq-062","cat":"child-marriage","type":"branch","hook":"Relatives pressure a girl to leave school to marry.","options":[{"text":"Support her right to stay in school and speak up","consequence":"You stand for her education and future.","outcome":"ally","best":true},{"text":"Stay silent","consequence":"Backing her schooling supports her whole future."}],"debrief":"Standing for a girl's schooling is standing for her future.","relearn":"You can support a girl's right to stay in school.","persona":"any","source":"education / voice"},
  {"id":"eq-063","cat":"child-marriage","type":"branch","hook":"You hear a child marriage is being planned in your community.","options":[{"text":"Tell a trusted adult or report to Childline 1098","consequence":"Officials can step in to prevent it.","outcome":"upstander","best":true},{"text":"Decide it's none of your business","consequence":"Reporting can prevent real harm to a child."}],"debrief":"Reporting a planned child marriage can protect a child.","relearn":"You can report a planned child marriage to a trusted adult or 1098.","persona":"any","source":"safeguarding"},
  {"id":"eq-064","cat":"child-marriage","type":"branch","hook":"A boy is told he must marry young and start providing now.","options":[{"text":"Recognise child marriage harms boys too, and seek help","consequence":"His childhood and schooling are protected too.","outcome":"protective","best":true},{"text":"Assume it only affects girls","consequence":"Child marriage harms boys too; the same help applies."}],"debrief":"Child marriage harms boys as well; everyone deserves to grow up first.","relearn":"Child marriage harms boys too; all children deserve to grow up first.","persona":"Veer","source":"child marriage / boys"},
  {"id":"eq-065","cat":"child-marriage","type":"branch","hook":"In the sim, you can invest in keeping girls in school.","options":[{"text":"Fund schooling, child marriage drops, futures open","consequence":"The community grows fairer and stronger.","outcome":"changemaker","best":true},{"text":"Cut girls' schooling","consequence":"Keeping girls in school is the proven way to cut child marriage."}],"debrief":"Education is the strongest protection against child marriage.","relearn":"Keeping girls in school is the best protection against child marriage.","persona":"any","source":"balancing-sim / evidence"},
  {"id":"eq-066","cat":"child-marriage","type":"branch","hook":"A friend feels alone and ashamed about pressure to marry young.","options":[{"text":"Remind her it's not her fault and help her find support","consequence":"She feels less alone and seeks help.","outcome":"caring","best":true},{"text":"Tell her it's her duty","consequence":"It's not her fault; support and help are what she needs."}],"debrief":"A girl facing this needs support and facts, never blame.","relearn":"Pressure to marry young isn't a girl's fault; support her to get help.","persona":"Riya","source":"support / no blame"},
  {"id":"eq-067","cat":"child-marriage","type":"role-play","hook":"You're helping a friend tell a teacher about a planned marriage.","setup":"Encourage her. Say:","yourLine":[{"text":"\"This isn't allowed and you deserve help, let's tell someone together.\"","best":true},{"text":"\"Maybe just go along with it.\""}],"relearn":"You can help a friend reach a teacher about a child marriage.","persona":"Counsellor","source":"help-routing"},
  {"id":"eq-068","cat":"child-marriage","type":"role-play","hook":"A relative says a 15-year-old cousin is 'old enough to marry'.","setup":"Speak up respectfully. Say:","yourLine":[{"text":"\"She's still a child, and the law says 18, let her finish growing up.\"","best":true},{"text":"Stay quiet"}],"relearn":"You can respectfully name that a child isn't ready, and the law agrees.","persona":"any","source":"voice / law"},
  {"id":"eq-069","cat":"child-marriage","type":"role-play","hook":"Reassuring a friend who's scared after speaking up about her marriage.","setup":"Stand with her. Say:","yourLine":[{"text":"\"You were brave, and you're not alone in this.\"","best":true},{"text":"\"You probably caused trouble.\""}],"relearn":"Support a friend who's spoken up; she's brave, not 'trouble'.","persona":"Riya","source":"support"},
  {"id":"eq-070","cat":"child-marriage","type":"sort","hook":"Sort: a fact about child marriage in India, or a myth?","items":[{"id":"a","text":"It's illegal under 18 for girls"},{"id":"b","text":"\"It's harmless tradition\""},{"id":"c","text":"It can be reported to Childline 1098"},{"id":"d","text":"\"Nothing can stop it\""}],"bins":[{"id":"fact","label":"Fact"},{"id":"myth","label":"Myth"}],"key":{"a":"fact","b":"myth","c":"fact","d":"myth"},"relearn":"Child marriage is illegal and reportable; 'harmless' and 'unstoppable' are myths.","persona":"any","source":"child marriage facts"},
  {"id":"eq-071","cat":"child-marriage","type":"reflect","hook":"Lensy: every child deserves to grow up, learn and choose first. Agree?","prompt":"What do you think?","options":["Completely","Yes","Every child"],"affirm":"Childhood, education and choice come first, for every child.","relearn":"Every child deserves to grow up, learn and choose before marriage.","persona":"any","source":"rights"},
  // — Rebalance it —
  {"id":"eq-072","cat":"rebalance-it","type":"branch","hook":"You want to make your own corner of the world a bit more equal.","options":[{"text":"Pick one real thing, share a chore, back a friend, and do it","consequence":"Small actions add up to real change.","outcome":"changemaker","best":true},{"text":"Wait for someone else to fix it all","consequence":"Real rebalancing starts with one action of yours."}],"debrief":"Equality is rebalanced by everyday actions, starting with yours.","relearn":"Start rebalancing with one real, everyday action.","persona":"any","source":"action"},
  {"id":"eq-073","cat":"rebalance-it","type":"branch","hook":"You could call out a small unfairness, or let it slide.","options":[{"text":"Name it kindly and suggest a fairer way","consequence":"You nudge things toward balance.","outcome":"upstander","best":true},{"text":"Let it slide every time","consequence":"Naming small unfairness gently shifts the norm."}],"debrief":"Lots of small call-outs reshape what's normal.","relearn":"Gently naming small unfairness helps rebalance the norm.","persona":"any","source":"voice"},
  {"id":"eq-074","cat":"rebalance-it","type":"branch","hook":"At home you could quietly take on a 'not my job' task.","options":[{"text":"Just do it, regardless of gender 'rules'","consequence":"You model equality without a lecture.","outcome":"model","best":true},{"text":"Stick to 'my' gendered tasks","consequence":"Crossing the 'gender task' line models real equality."}],"debrief":"Doing a 'not my gender's' task quietly is everyday equality.","relearn":"Crossing gendered task lines at home models equality.","persona":"Veer","source":"home / modelling"},
  {"id":"eq-075","cat":"rebalance-it","type":"branch","hook":"Friends exclude someone from a 'gendered' activity.","options":[{"text":"Invite them in; activities aren't gendered","consequence":"You open the group up fairly.","outcome":"ally","best":true},{"text":"Go along with the exclusion","consequence":"Including everyone rebalances the group."}],"debrief":"Inclusion is rebalancing in action.","relearn":"Include people across gender lines; activities aren't gendered.","persona":"any","source":"inclusion"},
  {"id":"eq-076","cat":"rebalance-it","type":"branch","hook":"You spot the chance to give a quieter girl the lead role.","options":[{"text":"Back her for it","consequence":"You help share who gets seen and heard.","outcome":"ally","best":true},{"text":"Default to the usual boy","consequence":"Backing her shares the spotlight more fairly."}],"debrief":"Sharing the spotlight is how power gets rebalanced.","relearn":"You can back others into roles they're usually denied.","persona":"Riya","source":"power / action"},
  {"id":"eq-077","cat":"rebalance-it","type":"role-play","hook":"You want to suggest fairer chore-sharing at home.","setup":"Propose it warmly. Say:","yourLine":[{"text":"\"Let's all share the work, it's fairer and easier on everyone.\"","best":true},{"text":"Say nothing and stay annoyed"}],"relearn":"You can warmly propose fairer sharing at home.","persona":"Rohit","source":"home / voice"},
  {"id":"eq-078","cat":"rebalance-it","type":"role-play","hook":"Someone says 'why do you even care about equality?'","setup":"Answer simply. Say:","yourLine":[{"text":"\"Because it's fairer, and it makes everyone's life better.\"","best":true},{"text":"\"...no reason.\""}],"relearn":"You can state plainly why equality matters: it's fairer and better for all.","persona":"Veer","source":"voice"},
  {"id":"eq-079","cat":"rebalance-it","type":"role-play","hook":"A friend wants to act but feels too small to make a difference.","setup":"Encourage them. Say:","yourLine":[{"text":"\"Small actions add up, let's start with one.\"","best":true},{"text":"\"Yeah, we can't do anything.\""}],"relearn":"You can remind others that small actions add up.","persona":"any","source":"agency"},
  {"id":"eq-080","cat":"rebalance-it","type":"build","hook":"Build your personal 'rebalance' plan.","prompt":"Pick actions you can actually do.","pieces":["share the load at home","back people into fair roles","call out small unfairness kindly","keep learning the facts"],"mode":"assemble","key":["share the load at home","back people into fair roles","call out small unfairness kindly","keep learning the facts"],"relearn":"Your rebalance plan: share, back others, call it out, keep learning.","persona":"any","source":"action plan"},
  {"id":"eq-081","cat":"rebalance-it","type":"build","hook":"Build the 'equality pays off' summary to remember.","prompt":"Assemble the core truths.","pieces":["belief must become practice","share the unpaid load","equality isn't zero-sum","fairness lifts everyone"],"mode":"assemble","key":["belief must become practice","share the unpaid load","equality isn't zero-sum","fairness lifts everyone"],"relearn":"Belief into practice, share the load, not zero-sum, lifts everyone.","persona":"any","source":"consolidation"},
  {"id":"eq-082","cat":"rebalance-it","type":"build","hook":"Build a fair classroom from an unequal one.","prompt":"Order the rebalancing steps.","pieces":["notice who's left out or overused","share roles and chances","check how it feels after","keep adjusting"],"mode":"sequence","key":["notice who's left out or overused","share roles and chances","check how it feels after","keep adjusting"],"relearn":"Rebalance a space: notice, share, check, keep adjusting.","persona":"any","source":"balancing-sim"},
  {"id":"eq-083","cat":"rebalance-it","type":"reflect","hook":"Lensy: biggest take-away from Equalize?","prompt":"Pick your motto.","options":["Live it, don't just say it","Share the load","Equality isn't zero-sum","Every child grows up first"],"affirm":"Close the gap, share the load, and watch equality lift everyone.","relearn":"Turn belief into practice, share the load, and equality lifts everyone.","persona":"any","source":"consolidation"},
  {"id":"eq-084","cat":"rebalance-it","type":"reflect","hook":"Lensy: you're someone who can actually rebalance the world around you. Feel it?","prompt":"What do you think?","options":["Yes","I can act","Starting now"],"affirm":"You really can; small, steady rebalancing is how the world changes.","relearn":"You can rebalance your corner of the world, starting now.","persona":"any","source":"agency"},
];

export const EQUALIZE: V2GameConfig = {
  gameId: "equalize",
  title: "Equalize",
  greet: "Hey, it's Lensy. ⚖️ Lots of people SAY they believe in equality — living it is the real game. Let's spot the gaps, rebalance the load at home and school, and see how fairness lifts everyone, boys included.",
  scenarios: SCENARIOS,
  categories: [
    { id: "belief-vs-practice", emoji: "🧭", label: "Belief vs practice" },
    { id: "unpaid-load", emoji: "🧺", label: "The unpaid load" },
    { id: "pay-and-power", emoji: "💼", label: "Pay & power" },
    { id: "pays-off", emoji: "📈", label: "Equality pays off" },
    { id: "child-marriage", emoji: "🛡️", label: "Child marriage" },
    { id: "rebalance-it", emoji: "⚖️", label: "Rebalance it" },
  ],
  badge: {
    title: "Equalizer! ⚖️",
    blurb: "You can spot the gap between believing and living equality, share the unpaid load, and stand up on rights like keeping every child in school — because fairness lifts everyone. ⚖️",
  },
  helpLine: "If you or a friend is being pushed toward marriage as a child, you don't have to face it alone — tell a trusted adult, or call Childline on one-zero-nine-eight. It's illegal, it can be stopped, and it's never your fault.",
  helpLabel: "Get help · Childline 1098",
  reassure: "If you or someone you know is being pressured to marry as a child, it's never your fault — and it can be stopped. Tell a trusted adult or call Childline 1098. Every child deserves to grow up, learn and choose. 💛",
  reassureCats: ["child-marriage"],
  buildLabels: { assemble: "That's the balance! ⚖️", sequence: "That's my plan!" },
};
