// Content for Fair Play World (node g10, ages 6–9, Chapter 2) — NEW v2 build to GDD 10 (mechanic-embodying),
// the fairness game in the Gender & Respect thread. "Everyone gets a fair turn." 84 researched, India-grounded
// scenarios across six categories, each encoded as one of the shared v2 play actions (branch / reflect /
// strike-rewrite / sort / role-play / match / build / spot) — no binary "tap the right card", led by fairness
// DILEMMAS (branch — decide the fair move, see the ripple, get a debrief), the fair-chore-chart builder
// (build), and spot-the-unfair-rule scenes (spot). Teaches fairness as gender equality: what fair means
// (a turn / what you need), sharing chores by turns not gender (India's chore gap, named plainly), fair
// opportunity, equity (fair can mean meeting different needs), and spotting/standing up to unfair rules.
// DECIDE NOT BE TOLD (multiple good moves; the child reasons it out); BOTH DIRECTIONS (frees girls toward
// chances AND boys toward home help; no gender villain); SAFE TO BE WRONG (gentle debriefs, no buzzer);
// family-safe ("everyone helps the family", an elder can nod to). Builds on g07 (What Makes Me, Me); prereq
// g41 (Heart Smart). Rendered by the shared engine (components/games/v2-engine.tsx).
// gameId "fair-play" (the engine-host registry id; the GDD/library "fair-play-world" is design-doc only). DO NOT RENAME.

import type { Scenario, V2GameConfig } from "./v2-schema";

const SCENARIOS: Scenario[] = [
  // — What fair means (everyone gets a turn / what they need) —
  {"id":"fp-001","cat":"what-is-fair","type":"sort","hook":"Lensy: welcome to Fair Play World! Sort these into fair or not fair.","items":[{"id":"a","text":"Everyone gets a turn on the swing"},{"id":"b","text":"One kid hogs the swing all break"},{"id":"c","text":"Sharing the snacks equally"},{"id":"d","text":"Only my friends get any"}],"bins":[{"id":"fair","label":"Fair"},{"id":"no","label":"Not fair"}],"key":{"a":"fair","b":"no","c":"fair","d":"no"},"relearn":"Fair usually means everyone gets a turn or a share.","persona":"any","source":"fairness development"},
  {"id":"fp-002","cat":"what-is-fair","type":"reflect","hook":"Lensy: what does 'fair' feel like to you?","prompt":"Pick one.","options":["Everyone gets a turn","No one's left out","People get what they need"],"affirm":"Fair feels like everyone matters, that's the heart of it.","relearn":"Fairness means everyone matters and no one's left out.","persona":"Ananya","source":"fairness"},
  {"id":"fp-003","cat":"what-is-fair","type":"strike-rewrite","hook":"\"Fair means I always get my way.\"","myth":{"un":"Fair means I always get what I want.","re":"Fair means everyone gets a turn or a share, not just me.","why":"Fairness is about everyone, not only you."},"relearn":"Fair is about everyone, not just me getting my way.","persona":"any","source":"fairness"},
  {"id":"fp-004","cat":"what-is-fair","type":"branch","hook":"Two of you want the last samosa.","options":[{"text":"Split it or take turns next time","consequence":"Both of you feel it was fair.","outcome":"fair","best":true},{"text":"Grab it all","consequence":"You win once, but it doesn't feel fair to your friend.","outcome":"unfair"}],"debrief":"Sharing or taking turns keeps things fair for everyone.","relearn":"Splitting or taking turns is a fair fix.","persona":"any","source":"fairness"},
  {"id":"fp-005","cat":"what-is-fair","type":"match","hook":"Match the situation to the fair fix.","pairs":[{"left":"One ball, many players","right":"Take turns"},{"left":"A big cake","right":"Equal slices"},{"left":"One person did all the work","right":"They get a say in the prize"}],"relearn":"Different situations have fair fixes: turns, equal shares, a say.","persona":"any","source":"fairness"},
  {"id":"fp-006","cat":"what-is-fair","type":"reflect","hook":"Lensy: is fair the same as kind?","prompt":"What do you think?","options":["They go together","Fair is part of kind","Both matter"],"affirm":"Fairness and kindness work together to make everyone feel okay.","relearn":"Being fair is one way of being kind.","persona":"any","source":"values"},
  {"id":"fp-007","cat":"what-is-fair","type":"sort","hook":"Sort: a fair rule, or an unfair rule?","items":[{"id":"a","text":"Whoever's next gets a turn"},{"id":"b","text":"Only boys go first, always"},{"id":"c","text":"We rotate who chooses the game"},{"id":"d","text":"The loudest kid always decides"}],"bins":[{"id":"fair","label":"Fair rule"},{"id":"no","label":"Unfair rule"}],"key":{"a":"fair","b":"no","c":"fair","d":"no"},"relearn":"Fair rules give everyone a chance; unfair ones favour a few.","persona":"Ananya","source":"fairness / rules"},
  {"id":"fp-008","cat":"what-is-fair","type":"branch","hook":"You're picking teams and one kid is always picked last.","options":[{"text":"Mix it up so everyone gets picked","consequence":"That kid feels included; teams are still fun.","outcome":"fair","best":true},{"text":"Leave them till last again","consequence":"They feel rubbish, and it wasn't their fault.","outcome":"unfair"}],"debrief":"Fair picking means no one is always left till last.","relearn":"Fair teams don't leave the same kid out every time.","persona":"any","source":"fairness / inclusion"},
  {"id":"fp-009","cat":"what-is-fair","type":"reflect","hook":"Lensy: have you ever felt something was unfair?","prompt":"How did it feel?","options":["Frustrating","Not nice","Like I wasn't counted"],"affirm":"That feeling is your fairness-sense working. It helps you put things right.","relearn":"Noticing unfairness is the first step to fixing it.","persona":"Ananya","source":"justice sensitivity"},
  {"id":"fp-010","cat":"what-is-fair","type":"strike-rewrite","hook":"\"Rules can't be changed, even unfair ones.\"","myth":{"un":"Unfair rules can never be changed.","re":"People can change unfair rules to fairer ones.","why":"Rules are made by people, and can be improved."},"relearn":"Unfair rules can be changed to fair ones.","persona":"Ananya","source":"rights / agency"},
  {"id":"fp-011","cat":"what-is-fair","type":"sort","hook":"Sort: this helps everyone get a fair go, or blocks it?","items":[{"id":"a","text":"Taking turns to speak"},{"id":"b","text":"Talking over everyone"},{"id":"c","text":"A turn-list for the tablet"},{"id":"d","text":"One kid keeping the tablet all day"}],"bins":[{"id":"help","label":"Fair go"},{"id":"block","label":"Blocks it"}],"key":{"a":"help","b":"block","c":"help","d":"block"},"relearn":"Turns and turn-lists give everyone a fair go.","persona":"any","source":"fairness"},
  {"id":"fp-012","cat":"what-is-fair","type":"build","hook":"Build the rules for Fair Play World.","prompt":"Pick the fair rules.","pieces":["everyone gets a turn","share what we can","no one left out","help those who need it","loudest always wins"],"mode":"assemble","key":["everyone gets a turn","share what we can","no one left out","help those who need it"],"relearn":"Fair Play World runs on turns, sharing, including everyone and helping.","persona":"any","source":"fairness"},
  // — Sharing chores fairly (everyone helps, not by gender) —
  {"id":"fp-013","cat":"chores-shared","type":"strike-rewrite","hook":"\"Chores are girls' work.\"","myth":{"un":"Chores are girls' work.","re":"Everyone in the family shares the chores, whatever their gender.","why":"A home runs when everyone helps."},"relearn":"Chores are everyone's, not just girls'.","persona":"Ananya","source":"India chore gap"},
  {"id":"fp-014","cat":"chores-shared","type":"branch","hook":"Your brother plays while your sister does all the housework.","options":[{"text":"Say \"let's all take turns with the chores\"","consequence":"The work is shared; it's fair and faster.","outcome":"fair","best":true},{"text":"Let it carry on","consequence":"One kid carries it all, day after day.","outcome":"unfair"}],"debrief":"In India, girls do about 40% more chores than boys, sharing fixes that.","relearn":"Chores shared by turns, not by gender, is fair.","persona":"Ananya","source":"India chore gap"},
  {"id":"fp-015","cat":"chores-shared","type":"sort","hook":"Sort: who can do this chore? (Trick: anyone!)","items":[{"id":"a","text":"Cooking"},{"id":"b","text":"Fixing a shelf"},{"id":"c","text":"Washing up"},{"id":"d","text":"Caring for a younger sibling"}],"bins":[{"id":"anyone","label":"Anyone can"},{"id":"one-gender","label":"Only one gender"}],"key":{"a":"anyone","b":"anyone","c":"anyone","d":"anyone"},"relearn":"Every chore can be done by anyone, of any gender.","persona":"any","source":"gender-equal caregiving"},
  {"id":"fp-016","cat":"chores-shared","type":"build","hook":"Build a fair family chore chart.","prompt":"Give everyone a turn at each job.","pieces":["amma cooks Mon","appa cooks Tue","brother washes up","sister fixes the bulb","everyone tidies"],"mode":"assemble","key":["amma cooks Mon","appa cooks Tue","brother washes up","sister fixes the bulb","everyone tidies"],"relearn":"A fair chart rotates jobs so no one's stuck with all of them.","persona":"Sunita","source":"India joint family / fairness"},
  {"id":"fp-017","cat":"chores-shared","type":"branch","hook":"It's festival prep and the girls are cooking while the boys watch TV.","options":[{"text":"Say \"everyone helps the family\" and rope the boys in","consequence":"Prep's done faster and everyone shares the fun and work.","outcome":"fair","best":true},{"text":"Let the girls do it all","consequence":"The girls miss the fun and rest; that's not fair.","outcome":"unfair"}],"debrief":"\"Everyone helps the family\" is a fairness even elders can nod to.","relearn":"Festival and home work is for everyone, not just the girls.","persona":"Sunita","source":"India / gender-equal caregiving"},
  {"id":"fp-018","cat":"chores-shared","type":"strike-rewrite","hook":"\"Boys shouldn't have to help at home.\"","myth":{"un":"Boys shouldn't have to help at home.","re":"Boys help at home just like everyone else.","why":"Helping is part of being in a family."},"relearn":"Boys do chores too; everyone helps.","persona":"any","source":"gender-equal caregiving"},
  {"id":"fp-019","cat":"chores-shared","type":"role-play","hook":"You want chores shared more fairly at home.","setup":"Ask kindly. Say:","yourLine":[{"text":"\"Can we make a turn-by-turn chore chart so it's fair?\"","best":true},{"text":"Say nothing and feel cross"}],"relearn":"Asking for a fair chore plan is reasonable and brave.","persona":"Ananya","source":"voice / agency"},
  {"id":"fp-020","cat":"chores-shared","type":"reflect","hook":"Lensy: when chores are shared fairly, who has time to study and play?","prompt":"What do you think?","options":["Everyone","Both girls and boys","All of us"],"affirm":"Sharing chores fairly means everyone gets time to study, rest and play.","relearn":"Fair chores free up everyone's time for school and play.","persona":"Ananya","source":"India chore gap / education"},
  {"id":"fp-021","cat":"chores-shared","type":"sort","hook":"Sort: fair chore-sharing, or unfair?","items":[{"id":"a","text":"Everyone takes a turn"},{"id":"b","text":"Only the girls clean up"},{"id":"c","text":"Dad and son cook dinner"},{"id":"d","text":"Boys never lift a finger"}],"bins":[{"id":"fair","label":"Fair"},{"id":"no","label":"Unfair"}],"key":{"a":"fair","b":"no","c":"fair","d":"no"},"relearn":"Fair homes share the work across everyone.","persona":"Sunita","source":"fairness"},
  {"id":"fp-022","cat":"chores-shared","type":"branch","hook":"A friend says \"my sister does my chores for me.\"","options":[{"text":"Say \"that's not really fair to her, want to swap sometimes?\"","consequence":"Your friend sees it and starts sharing.","outcome":"fair","best":true},{"text":"Say \"lucky you!\"","consequence":"His sister keeps doing double; that's unfair."}],"debrief":"One kid doing another's chores isn't fair to them.","relearn":"It's not fair for one kid to carry another's chores.","persona":"Ananya","source":"fairness"},
  {"id":"fp-023","cat":"chores-shared","type":"match","hook":"Match the chore to who should do it. (Trick: it rotates!)","pairs":[{"left":"Monday cooking","right":"Whoever's turn it is"},{"left":"Taking out rubbish","right":"Whoever's turn it is"},{"left":"Helping a sibling","right":"Whoever's turn it is"}],"relearn":"Chores rotate by turns, not fixed by gender.","persona":"Sunita","source":"gender-equal caregiving"},
  {"id":"fp-024","cat":"chores-shared","type":"reflect","hook":"Lensy: would you like a fairer chore deal at home? It's okay to want that.","prompt":"What do you think?","options":["Yes","It'd feel fairer","I'd like to share"],"affirm":"Wanting fair chores is reasonable, you can talk to your family about it.","relearn":"It's okay to want and ask for fair chores.","persona":"Ananya","source":"agency"},
  {"id":"fp-025","cat":"chores-shared","type":"strike-rewrite","hook":"\"Helping at home is a waste of a boy's time.\"","myth":{"un":"Helping at home wastes a boy's time.","re":"Learning to cook, clean and care helps every kid for life.","why":"Everyone needs these life skills."},"relearn":"Home skills are valuable for everyone to learn.","persona":"any","source":"life skills"},
  {"id":"fp-026","cat":"chores-shared","type":"branch","hook":"Capstone-style: you notice chores at home aren't shared fairly.","options":[{"text":"Suggest a family chat and a fair chart","consequence":"The family tries it; things get fairer over time.","outcome":"changemaker","best":true},{"text":"Just accept it","consequence":"Speaking up, kindly, is how unfair things change."}],"debrief":"You can be the one who starts a fairer system at home.","relearn":"You can help make chores fairer at home.","persona":"Ananya","source":"agency / changemaking"},
  {"id":"fp-027","cat":"chores-shared","type":"reflect","hook":"Lensy: sharing chores fairly is a small act with a big effect. Agree?","prompt":"What do you think?","options":["Yes","It frees everyone","Big effect"],"affirm":"Fair chores give everyone, especially girls, time to learn and dream.","relearn":"Fair chores at home ripple out into fairer chances in life.","persona":"Ananya","source":"India chore gap"},
  // — Fair opportunity (who gets to play, lead, learn, rest) —
  {"id":"fp-028","cat":"fair-opportunity","type":"branch","hook":"Only boys are being picked to use the new science kit.","options":[{"text":"Say \"girls should get a turn too\"","consequence":"Everyone gets a go; the best ideas come from all.","outcome":"fair","best":true},{"text":"Let only boys use it","consequence":"Girls miss out on a chance for no good reason.","outcome":"unfair"}],"debrief":"Fair opportunity means everyone gets a chance to try.","relearn":"Opportunities should be open to everyone, not one gender.","persona":"Ananya","source":"gender equality / opportunity"},
  {"id":"fp-029","cat":"fair-opportunity","type":"strike-rewrite","hook":"\"Boys get first chance at the good stuff.\"","myth":{"un":"Boys get first chance at the best opportunities.","re":"Everyone deserves a fair chance, regardless of gender.","why":"Talent and interest aren't gendered."},"relearn":"Fair chances go to everyone, not boys first.","persona":"Ananya","source":"gender equality"},
  {"id":"fp-030","cat":"fair-opportunity","type":"sort","hook":"Sort: a fair chance, or an unfair head-start?","items":[{"id":"a","text":"Everyone tries out for the team"},{"id":"b","text":"Only boys allowed to try out"},{"id":"c","text":"Picking the best, any gender"},{"id":"d","text":"Girls can only watch"}],"bins":[{"id":"fair","label":"Fair chance"},{"id":"no","label":"Unfair"}],"key":{"a":"fair","b":"no","c":"fair","d":"no"},"relearn":"Fair chances are open to all; unfair ones shut people out.","persona":"any","source":"opportunity"},
  {"id":"fp-031","cat":"fair-opportunity","type":"branch","hook":"The class captain is always a boy 'because that's how it's done'.","options":[{"text":"Say \"let's choose the best leader, any gender\"","consequence":"A great captain is picked on merit.","outcome":"fair","best":true},{"text":"Keep it boys-only","consequence":"Good leaders are skipped for no reason.","outcome":"unfair"}],"debrief":"Leadership chances should be open to everyone.","relearn":"Anyone can lead; pick on skill, not gender.","persona":"Ananya","source":"leadership / equality"},
  {"id":"fp-032","cat":"fair-opportunity","type":"role-play","hook":"You want a fair chance at something only boys are getting.","setup":"Speak up. Say:","yourLine":[{"text":"\"I'd like a fair turn too, please.\"","best":true},{"text":"Stay quiet and miss out"}],"relearn":"Asking for a fair turn is your right.","persona":"Ananya","source":"voice / agency"},
  {"id":"fp-033","cat":"fair-opportunity","type":"strike-rewrite","hook":"\"Some kids just don't deserve a turn.\"","myth":{"un":"Some kids don't deserve a chance.","re":"Everyone deserves a fair chance to try.","why":"You can't shine if you're never given a go."},"relearn":"Everyone deserves a fair chance to try.","persona":"any","source":"opportunity"},
  {"id":"fp-034","cat":"fair-opportunity","type":"reflect","hook":"Lensy: a fair chance to try, does everyone deserve one?","prompt":"What do you think?","options":["Yes","Everyone","Of course"],"affirm":"Yes, a fair chance to try is something everyone deserves.","relearn":"Everyone deserves a fair chance.","persona":"any","source":"opportunity"},
  {"id":"fp-035","cat":"fair-opportunity","type":"branch","hook":"Your friend never gets to choose the game because they're quiet.","options":[{"text":"Say \"your turn to choose today\"","consequence":"They light up; the group tries something new.","outcome":"fair","best":true},{"text":"Let the loud kids decide again","consequence":"The quiet friend never gets a say."}],"debrief":"Fair opportunity includes the quiet kids too.","relearn":"Give quieter kids a fair turn to choose.","persona":"any","source":"inclusion"},
  {"id":"fp-036","cat":"fair-opportunity","type":"match","hook":"Match the chance to who should get it. (Trick: anyone who wants it!)","pairs":[{"left":"Lead the project","right":"Anyone, by turns"},{"left":"Try the new instrument","right":"Anyone who wants"},{"left":"Represent the class","right":"Anyone, fairly chosen"}],"relearn":"Opportunities belong to anyone who wants a fair shot.","persona":"any","source":"opportunity"},
  {"id":"fp-037","cat":"fair-opportunity","type":"reflect","hook":"Lensy: when everyone gets a fair chance, who wins?","prompt":"What do you think?","options":["Everyone","The whole group","We all do"],"affirm":"When chances are fair, the whole group gets everyone's best.","relearn":"Fair chances make the whole group better.","persona":"any","source":"equality"},
  {"id":"fp-038","cat":"fair-opportunity","type":"strike-rewrite","hook":"\"Girls shouldn't get the same chances because they'll just do chores later.\"","myth":{"un":"Girls don't need the same chances.","re":"Girls deserve the very same chances to learn, lead and dream.","why":"Their futures are as wide as anyone's."},"relearn":"Girls deserve exactly the same chances as boys.","persona":"Ananya","source":"gender equality / India"},
  {"id":"fp-039","cat":"fair-opportunity","type":"branch","hook":"There's money for one kid's extra class, and it's assumed it'll be the son.","options":[{"text":"Say \"could we choose fairly, by who wants it most?\"","consequence":"The chance goes to whoever will use it, not by gender.","outcome":"fair","best":true},{"text":"Assume the son should get it","consequence":"A keen daughter might miss out unfairly."}],"debrief":"Family chances should go fairly, not default to the boy.","relearn":"Opportunities at home should be shared fairly, not by gender.","persona":"Ananya","source":"India / gender equality"},
  // — Fair isn't always 'the same' (needs differ) —
  {"id":"fp-040","cat":"equal-vs-equity","type":"branch","hook":"Two friends watch a match over a wall; one is short and can't see.","options":[{"text":"Give the shorter friend a box to stand on","consequence":"Now both can see; that's truly fair.","outcome":"equity","best":true},{"text":"Give them both the same-size box","consequence":"The tall one still sees, the short one still can't, fair means meeting needs."}],"debrief":"Fair sometimes means different help so everyone can join in.","relearn":"Fair isn't always 'the same'; it's everyone getting what they need.","persona":"any","source":"equity"},
  {"id":"fp-041","cat":"equal-vs-equity","type":"strike-rewrite","hook":"\"Fair means everyone gets exactly the same, always.\"","myth":{"un":"Fair always means exactly the same for everyone.","re":"Sometimes fair means giving people what they each need.","why":"Different needs need different help."},"relearn":"Fair can mean meeting different needs, not identical shares.","persona":"any","source":"equity"},
  {"id":"fp-042","cat":"equal-vs-equity","type":"sort","hook":"Sort: this is fair (meets needs), or only looks equal?","items":[{"id":"a","text":"A kid who can't see gets glasses"},{"id":"b","text":"Everyone must run the same with a hurt leg"},{"id":"c","text":"Extra help for someone struggling"},{"id":"d","text":"Same homework, no help for anyone ever"}],"bins":[{"id":"fair","label":"Fair (meets needs)"},{"id":"no","label":"Not really fair"}],"key":{"a":"fair","b":"no","c":"fair","d":"no"},"relearn":"Meeting needs is fair, even when it's not identical.","persona":"any","source":"equity"},
  {"id":"fp-043","cat":"equal-vs-equity","type":"branch","hook":"A new classmate doesn't speak the language well yet.","options":[{"text":"Give them extra help and patience","consequence":"They catch up and join in; that's fair.","outcome":"equity","best":true},{"text":"Expect them to manage alone","consequence":"Same treatment isn't fair when needs differ."}],"debrief":"Extra help for different needs is fairness, not favouritism.","relearn":"Helping someone who needs more is fair.","persona":"Kabir-type","source":"equity / inclusion"},
  {"id":"fp-044","cat":"equal-vs-equity","type":"reflect","hook":"Lensy: is giving someone extra help when they need it fair?","prompt":"What do you think?","options":["Yes","It meets their need","That's fair"],"affirm":"Yes, helping someone meet their need is real fairness.","relearn":"Extra help for real needs is fair, not unfair.","persona":"any","source":"equity"},
  {"id":"fp-045","cat":"equal-vs-equity","type":"match","hook":"Match the person to the fair help.","pairs":[{"left":"Can't reach the shelf","right":"A step-stool"},{"left":"Can't hear well","right":"A seat at the front"},{"left":"New to the game","right":"A quick how-to"}],"relearn":"Fair help fits what each person actually needs.","persona":"any","source":"equity"},
  {"id":"fp-046","cat":"equal-vs-equity","type":"branch","hook":"Your team has a younger, smaller player.","options":[{"text":"Adjust so they can join in fairly","consequence":"They play and have fun; the team's kinder and stronger.","outcome":"equity","best":true},{"text":"Make them keep up exactly","consequence":"They can't, and feel left out, fair means adjusting."}],"debrief":"Adjusting for who's playing keeps it fair and fun for all.","relearn":"Fair play can mean small adjustments so everyone joins.","persona":"any","source":"equity / inclusion"},
  {"id":"fp-047","cat":"equal-vs-equity","type":"reflect","hook":"Lensy: 'same' and 'fair' aren't always the same word. Surprised?","prompt":"What do you think?","options":["A bit","Makes sense","Fair fits the need"],"affirm":"Fair means everyone can truly take part, not just identical shares.","relearn":"Fairness is about everyone being able to take part.","persona":"any","source":"equity"},
  // — Spotting & standing up to unfairness —
  {"id":"fp-048","cat":"stand-up","type":"spot","hook":"Spot the unfair rule in the playground.","scene":[{"id":"a","text":"\"Everyone gets a turn to bat.\"","trick":false},{"id":"b","text":"\"Girls can't play cricket here.\"","trick":true},{"id":"c","text":"\"We rotate who's captain.\"","trick":false}],"why":"Banning girls from cricket is an unfair, gendered rule.","relearn":"An unfair rule often shuts one group out, spot it.","persona":"Ananya","source":"spot unfairness"},
  {"id":"fp-049","cat":"stand-up","type":"role-play","hook":"You see a gender-unfair rule and want to speak up.","setup":"Say it calm and clear:","yourLine":[{"text":"\"That's not fair, everyone should get a turn.\"","best":true},{"text":"Say nothing"}],"relearn":"A calm, clear \"that's not fair\" can change a rule.","persona":"Ananya","source":"assertiveness / voice"},
  {"id":"fp-050","cat":"stand-up","type":"branch","hook":"Your friend is told they can't join because of their gender.","options":[{"text":"Stand with them: \"they're playing too, that's fair\"","consequence":"The group often relents when someone speaks up.","outcome":"ally","best":true},{"text":"Stay quiet to avoid fuss","consequence":"Your friend stays shut out; speaking up helps."}],"debrief":"Standing up for a friend's fair turn is brave and kind.","relearn":"You can stand up for someone shut out unfairly.","persona":"Faizan-type","source":"bystander / fairness"},
  {"id":"fp-051","cat":"stand-up","type":"strike-rewrite","hook":"\"If a rule's unfair, there's nothing a kid can do.\"","myth":{"un":"Kids can't do anything about unfair rules.","re":"Kids can speak up, suggest fairer rules, and ask a grown-up.","why":"Lots of fair rules exist because someone spoke up."},"relearn":"Kids can help change unfair rules.","persona":"Ananya","source":"agency / rights"},
  {"id":"fp-052","cat":"stand-up","type":"branch","hook":"You spoke up about an unfair rule and got brushed off.","options":[{"text":"Tell a fair-minded grown-up (teacher) too","consequence":"A grown-up can help make the rule fairer.","outcome":"persistent","best":true},{"text":"Give up","consequence":"Bringing in a grown-up is a good next step, not giving up."}],"debrief":"If speaking up isn't enough, ask a fair grown-up for help.","relearn":"If you're not heard, a trusted grown-up can help.","persona":"Ananya","source":"escalation / agency"},
  {"id":"fp-053","cat":"stand-up","type":"spot","hook":"Spot the fair one (the others are unfair).","scene":[{"id":"a","text":"\"Only boys answer the hard questions.\"","trick":false},{"id":"b","text":"\"Anyone who knows can answer.\"","trick":true},{"id":"c","text":"\"Girls just take notes.\"","trick":false}],"why":"\"Anyone who knows can answer\" is the fair one; the others shut girls out.","relearn":"The fair rule lets anyone take part; the unfair ones don't.","persona":"Ananya","source":"spot fairness"},
  {"id":"fp-054","cat":"stand-up","type":"role-play","hook":"A classmate makes a 'girls can't do that' comment.","setup":"Give a calm comeback. Say:","yourLine":[{"text":"\"Actually, anyone can, let's give it a fair go.\"","best":true},{"text":"Laugh along"}],"relearn":"A calm comeback can flip an unfair comment.","persona":"Reyansh","source":"comebacks / voice"},
  {"id":"fp-055","cat":"stand-up","type":"branch","hook":"The group is dividing jobs: 'boys build, girls decorate', no choice.","options":[{"text":"Say \"let everyone pick what they want to do\"","consequence":"Kids do what they're keen on; the project's better.","outcome":"fair","best":true},{"text":"Go along with it","consequence":"People get stuck in boxes they didn't choose.","outcome":"unfair"}],"debrief":"Letting everyone choose their role is fairer than gender boxes.","relearn":"Roles should be chosen, not assigned by gender.","persona":"Ananya","source":"gender roles / fairness"},
  {"id":"fp-056","cat":"stand-up","type":"reflect","hook":"Lensy: speaking up for fairness can feel scary. Worth it?","prompt":"What do you think?","options":["Yes","For my friends","To make it fair"],"affirm":"Speaking up for fairness is brave, and it makes the world kinder.","relearn":"Speaking up for fairness is brave and worth it.","persona":"Ananya","source":"courage"},
  {"id":"fp-057","cat":"stand-up","type":"strike-rewrite","hook":"\"Standing up for fairness is just causing trouble.\"","myth":{"un":"Standing up for fairness is causing trouble.","re":"Standing up for fairness is making things right.","why":"Fairness helps everyone, not just one side."},"relearn":"Standing up for fairness isn't trouble; it's making things right.","persona":"Ananya","source":"values"},
  {"id":"fp-058","cat":"stand-up","type":"branch","hook":"You benefit from an unfair rule (you always get to go first).","options":[{"text":"Suggest taking turns so it's fair for all","consequence":"You give up a small perk; everyone feels it's fair.","outcome":"fair","best":true},{"text":"Keep your advantage quietly","consequence":"Real fairness sometimes means giving up an unfair perk."}],"debrief":"Being fair sometimes means letting go of an unfair advantage.","relearn":"Fairness can mean sharing an advantage you didn't earn.","persona":"Reyansh","source":"fairness / privilege (kid-level)"},
  {"id":"fp-059","cat":"stand-up","type":"role-play","hook":"You want to invite a left-out kid into a fair turn.","setup":"Include them. Say:","yourLine":[{"text":"\"Come on, it's your turn now.\"","best":true},{"text":"Ignore them"}],"relearn":"Inviting someone into a fair turn is fairness in action.","persona":"any","source":"inclusion / voice"},
  {"id":"fp-060","cat":"stand-up","type":"reflect","hook":"Lensy: who could YOU stand up for this week?","prompt":"Think of someone.","options":["A left-out friend","Someone treated unfairly","Anyone shut out","Myself"],"affirm":"That's a fairness hero move. Small stands change big things.","relearn":"You can choose to stand up for fairness, in small ways, often.","persona":"Ananya","source":"agency"},
  // — Fair at home, school & play —
  {"id":"fp-061","cat":"fair-everywhere","type":"branch","hook":"At home, you always get served first and the most.","options":[{"text":"Suggest everyone gets a fair share","consequence":"Mealtimes feel fair to all the kids.","outcome":"fair","best":true},{"text":"Enjoy the extra quietly","consequence":"Fairness at home means equal shares for the kids too."}],"debrief":"Fairness counts at home as much as at school.","relearn":"Fair shares matter at home too, not just at school.","persona":"Ananya","source":"fairness / India"},
  {"id":"fp-062","cat":"fair-everywhere","type":"sort","hook":"Sort: fair at school, or not?","items":[{"id":"a","text":"Everyone gets help when stuck"},{"id":"b","text":"Only favourites get picked"},{"id":"c","text":"Turns on the computer"},{"id":"d","text":"Same kids always told to sit out"}],"bins":[{"id":"fair","label":"Fair"},{"id":"no","label":"Unfair"}],"key":{"a":"fair","b":"no","c":"fair","d":"no"},"relearn":"Fair classrooms share help, turns and chances.","persona":"any","source":"fairness"},
  {"id":"fp-063","cat":"fair-everywhere","type":"branch","hook":"In a game, you could cheat to win.","options":[{"text":"Play fair, even if you might lose","consequence":"Win or lose, you played fair and kept friends.","outcome":"fair","best":true},{"text":"Cheat to win","consequence":"A cheated win doesn't feel good and loses trust.","outcome":"unfair"}],"debrief":"Playing fair matters more than winning by cheating.","relearn":"Fair play means no cheating, even to win.","persona":"any","source":"fair play / integrity"},
  {"id":"fp-064","cat":"fair-everywhere","type":"role-play","hook":"A friend cheated and you both know it.","setup":"Say something fair, not mean. Say:","yourLine":[{"text":"\"Let's play it fair, it's more fun that way.\"","best":true},{"text":"Cheat back next time"}],"relearn":"Asking to keep it fair beats cheating back.","persona":"any","source":"fair play / voice"},
  {"id":"fp-065","cat":"fair-everywhere","type":"reflect","hook":"Lensy: does fairness make games more fun or less?","prompt":"What do you think?","options":["More fun","Everyone enjoys it","More, for sure"],"affirm":"Fair games are more fun, because everyone gets to enjoy them.","relearn":"Fair play makes games more fun for everyone.","persona":"any","source":"fair play"},
  {"id":"fp-066","cat":"fair-everywhere","type":"sort","hook":"Sort: fair sharing, or hogging?","items":[{"id":"a","text":"Passing the ball to everyone"},{"id":"b","text":"Never passing"},{"id":"c","text":"Letting others have a go"},{"id":"d","text":"Keeping all the toys"}],"bins":[{"id":"fair","label":"Fair sharing"},{"id":"no","label":"Hogging"}],"key":{"a":"fair","b":"no","c":"fair","d":"no"},"relearn":"Fair sharing passes the fun around.","persona":"any","source":"sharing"},
  {"id":"fp-067","cat":"fair-everywhere","type":"branch","hook":"You and your sibling must split screen time.","options":[{"text":"Agree on equal turns with a timer","consequence":"You both get fair time; no fights.","outcome":"fair","best":true},{"text":"Grab as much as you can","consequence":"Fair turns beat grabbing and fighting."}],"debrief":"A timer and turns make screen time fair.","relearn":"Fair turns solve a lot of sharing fights.","persona":"any","source":"fairness"},
  {"id":"fp-068","cat":"fair-everywhere","type":"reflect","hook":"Lensy: you can bring fairness anywhere you go. Ready?","prompt":"Where will you bring it?","options":["Home","School","Play","Everywhere"],"affirm":"Fairness travels with you, home, school and play.","relearn":"You can choose fairness wherever you are.","persona":"any","source":"transfer"},
  {"id":"fp-069","cat":"chores-shared","type":"reflect","hook":"Lensy: girls in India do about 40% more chores than boys. Is that fair?","prompt":"What do you think?","options":["No","Not fair","We can change it"],"affirm":"It's not fair, and sharing chores is how families can change it.","relearn":"The chore gap isn't fair; sharing fixes it.","persona":"Ananya","source":"India chore gap"},
  {"id":"fp-070","cat":"fair-opportunity","type":"branch","hook":"A teacher asks 'a strong boy' to carry books.","options":[{"text":"Say \"any strong kid can help, I'll come too\"","consequence":"Help isn't assumed by gender; anyone pitches in.","outcome":"fair","best":true},{"text":"Assume only boys should","consequence":"Strength and helping aren't a boys-only thing."}],"debrief":"Jobs and help shouldn't be assigned by gender by default.","relearn":"Don't assume tasks by gender; anyone can help.","persona":"Ananya","source":"gender norms"},
  {"id":"fp-071","cat":"equal-vs-equity","type":"branch","hook":"One friend gets pocket money, another never does.","options":[{"text":"Understand families differ, and share treats kindly","consequence":"You're thoughtful about different situations.","outcome":"kind","best":true},{"text":"Brag about yours","consequence":"Fairness includes being kind about what others have."}],"debrief":"Fairness includes kindness about different family situations.","relearn":"Be kind and thoughtful about what others have or don't.","persona":"Kabir-type","source":"equity / empathy"},
  {"id":"fp-072","cat":"stand-up","type":"spot","hook":"Spot the unfair assumption.","scene":[{"id":"a","text":"\"She's a girl, so she'll do the tidying.\"","trick":true},{"id":"b","text":"\"Let's see who wants which job.\"","trick":false},{"id":"c","text":"\"We'll take turns tidying.\"","trick":false}],"why":"Assuming the girl tidies is an unfair, gendered assumption.","relearn":"Watch for 'she's a girl, so...' assumptions, they're unfair.","persona":"Ananya","source":"gender norms"},
  {"id":"fp-073","cat":"what-is-fair","type":"branch","hook":"You made a mistake that was unfair to someone.","options":[{"text":"Own it and make it right","consequence":"You repair it; fairness includes fixing your own slips.","outcome":"fair","best":true},{"text":"Pretend it didn't happen","consequence":"Fairness means owning and fixing your own unfair moves."}],"debrief":"Being fair includes putting right your own mistakes.","relearn":"If you were unfair, own it and make it right.","persona":"any","source":"accountability"},
  {"id":"fp-074","cat":"fair-opportunity","type":"reflect","hook":"Lensy: imagine a world where everyone got a fair chance. Good?","prompt":"What do you think?","options":["Amazing","Everyone could shine","Yes!"],"affirm":"That's the world Fair Play builds, one fair turn at a time.","relearn":"Fair chances let everyone shine.","persona":"any","source":"vision"},
  {"id":"fp-075","cat":"chores-shared","type":"role-play","hook":"Your little brother says chores are 'for girls'.","setup":"Set him straight, kindly. Say:","yourLine":[{"text":"\"Nope, everyone helps, let's do it together.\"","best":true},{"text":"\"Fine, I'll do it.\""}],"relearn":"Teach a sibling that chores are for everyone.","persona":"Ananya","source":"voice / gender-equal caregiving"},
  {"id":"fp-076","cat":"stand-up","type":"branch","hook":"Everyone's laughing at an unfair 'joke' that puts girls down.","options":[{"text":"Say \"that's not fair or funny\"","consequence":"You take the air out of it; some agree.","outcome":"ally","best":true},{"text":"Laugh along","consequence":"Laughing feeds an unfair put-down."}],"debrief":"Unfair 'jokes' aren't funny; you can say so (see Not Fair, Not Funny).","relearn":"You don't have to laugh at unfair put-downs.","persona":"Ananya","source":"bystander (links g11)"},
  {"id":"fp-077","cat":"equal-vs-equity","type":"sort","hook":"Sort: fairness that meets needs, or unfair sameness?","items":[{"id":"a","text":"A ramp so a wheelchair user can enter"},{"id":"b","text":"Stairs only, everyone the same"},{"id":"c","text":"Extra reading time for who needs it"},{"id":"d","text":"No one ever gets help"}],"bins":[{"id":"fair","label":"Fair (meets needs)"},{"id":"no","label":"Unfair sameness"}],"key":{"a":"fair","b":"no","c":"fair","d":"no"},"relearn":"Real fairness removes barriers so everyone can take part.","persona":"any","source":"equity / accessibility"},
  {"id":"fp-078","cat":"fair-everywhere","type":"role-play","hook":"Your team won; the other team is sad.","setup":"Be a fair winner. Say:","yourLine":[{"text":"\"Good game! You played really well.\"","best":true},{"text":"\"We're way better than you.\""}],"relearn":"Being fair includes being a kind winner.","persona":"any","source":"sportsmanship / voice"},
  {"id":"fp-079","cat":"stand-up","type":"reflect","hook":"Lensy: what's one unfair thing you'd love to change?","prompt":"Think of one.","options":["Chores at home","Who gets picked","Who gets a say","An unfair rule"],"affirm":"Hold that. Noticing it is the first step to changing it.","relearn":"Noticing unfairness is how change begins.","persona":"Ananya","source":"changemaking"},
  {"id":"fp-080","cat":"fair-opportunity","type":"branch","hook":"Capstone: you're in charge of picking who does the fun science demo.","options":[{"text":"Pick fairly, by turns, any gender","consequence":"Everyone gets a fair shot; the class trusts you.","outcome":"fair","best":true},{"text":"Pick only your friends / only boys","consequence":"Fair leaders share chances with everyone.","outcome":"unfair"}],"debrief":"When you have the power to choose, choosing fairly is the test.","relearn":"Fair leaders share opportunities with everyone.","persona":"Ananya","source":"leadership / consolidation"},
  {"id":"fp-081","cat":"chores-shared","type":"build","hook":"Capstone: build a fair-share plan for your home.","prompt":"Pick what makes it fair.","pieces":["turns for every chore","everyone helps, any gender","time to study and play for all","a family chat to agree"],"mode":"assemble","key":["turns for every chore","everyone helps, any gender","time to study and play for all","a family chat to agree"],"relearn":"A fair-share home: turns for all, everyone helps, time for all to study and play.","persona":"Ananya","source":"India chore gap / consolidation"},
  {"id":"fp-082","cat":"what-is-fair","type":"reflect","hook":"Lensy: what will you carry from Fair Play World?","prompt":"Pick your motto.","options":["Everyone gets a fair turn","Chores are everyone's","Fair means meeting needs","I can stand up for fair"],"affirm":"Carry that. You're a Fair Play champion now.","relearn":"Fairness: everyone gets a turn, chores are shared, needs are met, and you can stand up for it.","persona":"any","source":"consolidation"},
  {"id":"fp-083","cat":"stand-up","type":"strike-rewrite","hook":"\"It's not my problem if something's unfair to someone else.\"","myth":{"un":"Unfairness to others is none of my business.","re":"Fairness is everyone's business; you can help.","why":"We all do better when things are fair for all."},"relearn":"You can care about fairness for others, not just yourself.","persona":"Ananya","source":"solidarity"},
  {"id":"fp-084","cat":"fair-everywhere","type":"reflect","hook":"Lensy: fairness is a habit you build. Ready to practise it daily?","prompt":"What do you think?","options":["Yes","Every day","I'll practise"],"affirm":"Fairness grows with practice, one fair choice at a time. Go well!","relearn":"Fairness is a daily habit you can keep building.","persona":"any","source":"habit / growth"},
];

export const FAIR_PLAY: V2GameConfig = {
  gameId: "fair-play",
  title: "Fair Play World",
  greet: "Hey! Welcome to Fair Play World. 🏆 Let's make things fair — everyone gets a turn, chores are shared, and we can stand up to unfair rules.",
  scenarios: SCENARIOS,
  categories: [
    { id: "what-is-fair", emoji: "⚖️", label: "What's fair" },
    { id: "chores-shared", emoji: "🧹", label: "Sharing chores" },
    { id: "fair-opportunity", emoji: "🌟", label: "Fair chances" },
    { id: "equal-vs-equity", emoji: "📦", label: "Fair ≠ same" },
    { id: "stand-up", emoji: "✊", label: "Stand up" },
    { id: "fair-everywhere", emoji: "🏠", label: "Fair everywhere" },
  ],
  badge: {
    title: "Fair Play Champion! 🏆",
    blurb: "You can tell fair from unfair, share chores and chances by turns not gender, see when fair means meeting different needs, and stand up to an unfair rule — fairness is everyone's, and you can help make it. 🏆⚖️",
  },
  helpLine: "If something's unfair and speaking up isn't enough on your own, tell a fair-minded grown-up — a teacher or a parent can help change it. Standing up for fairness is making things right.",
  helpLabel: "Get help",
  reassure: "Standing up for fairness can feel scary — doing it, even in a small way, is brave, and it makes things right. ✊",
  reassureCats: ["stand-up"],
  buildLabels: { assemble: "That's fair for everyone! ⚖️" },
};
