// Content for Feelings Friends (node g01, ages 3–6) — reworked to GDD 01 (the Chapter-1 pilot, the
// template the other 68 follow). "Name it to tame it." Built on real personas + a researched library of
// 88 scenarios across six verb-moves, so it's a feelings sandbox, never a wrapper. Audio-first, no-fail.
// Evidence: affect labeling (Siegel; Lieberman), CASEL 5, Zones of Regulation, gender emotion-socialisation.
// gameId "feelings" — node.game === GameDone key === engine-host id. DO NOT RENAME.

export type Cat = "name" | "all-okay" | "calm" | "empathy" | "big-no" | "help";
export type Mechanic =
  | "name-match" | "all-okay" | "calm-pick" | "calm-do" | "empathy-read" | "empathy-act" | "big-no" | "help-pick";

// One researched scenario — the unit the verb runs on. `answer` is the kind/true option (position varies,
// never a fixed slot); `relearn` is the truth Sam writes after; `myth` (on all-okay items + a few big-no
// consent myths) is the struck idea UN erases — the component keys the UN→RE beat on `myth`, on any cat.
// There is no hard fail — a wrong tap gets a gentle "let's look again", never a buzzer.
export type Scenario = {
  id: string; cat: Cat; situation: string; prompt: string; options: string[];
  answer: string; relearn: string; myth?: string; persona: string; mechanic: Mechanic; source: string;
};

// 24 feeling faces — a distinct colour + emoji per feeling so a pre-reader recognises it without words.
// Used by the Name-it and empathy tiles; non-feeling options (phrases, yes/no) fall back to a text tile.
export type Face = { emoji: string; color: string };
export const FEELING_FACES: Record<string, Face> = {
  happy: { emoji: "😄", color: "#F5C518" }, sad: { emoji: "😢", color: "#5B9BD5" },
  angry: { emoji: "😠", color: "#E05C52" }, scared: { emoji: "😨", color: "#9B6FD6" },
  shy: { emoji: "🫣", color: "#F49AC2" }, excited: { emoji: "🤩", color: "#FF9F40" },
  calm: { emoji: "😌", color: "#62B84B" }, frustrated: { emoji: "😤", color: "#E8743B" },
  sleepy: { emoji: "😴", color: "#8E7CC3" }, proud: { emoji: "😊", color: "#FFB347" },
  bored: { emoji: "😑", color: "#9AA0A6" }, silly: { emoji: "🤪", color: "#FF8FCF" },
  jealous: { emoji: "😒", color: "#7FB069" }, embarrassed: { emoji: "😳", color: "#F2868C" },
  grumpy: { emoji: "😣", color: "#C28B5C" }, surprised: { emoji: "😲", color: "#4FC3E8" },
  disappointed: { emoji: "😞", color: "#6C8EBF" }, lonely: { emoji: "🥺", color: "#8AA1C9" },
  nervous: { emoji: "😬", color: "#D6A75C" }, loved: { emoji: "🥰", color: "#FF6F91" },
  curious: { emoji: "🤔", color: "#3FB6C6" }, confused: { emoji: "😕", color: "#B0A0D0" },
  worried: { emoji: "😟", color: "#C9A66B" }, tired: { emoji: "🥱", color: "#9A8CC0" },
};

// The 88-scenario library (GDD 01 rework v1) — research-grounded, India-real; the content the verbs run on.
export const SCENARIOS: Scenario[] = [
  { id: "ff-001", cat: "name", situation: "Aarav's block tower falls down right before it was finished.", prompt: "How does Aarav feel?", options: ["frustrated", "sleepy", "proud"], answer: "frustrated", relearn: "That big huff is frustration. Naming it helps it shrink.", persona: "Vihaan (bold, kinetic)", mechanic: "name-match", source: "affect labeling; CASEL self-awareness" },
  { id: "ff-002", cat: "name", situation: "It's a birthday party with balloons and cake.", prompt: "How do you feel?", options: ["excited", "scared", "bored"], answer: "excited", relearn: "That fizzy, jumpy feeling is excitement.", persona: "any", mechanic: "name-match", source: "CASEL self-awareness" },
  { id: "ff-003", cat: "name", situation: "A big dog barks loudly right next to you.", prompt: "How do you feel?", options: ["scared", "happy", "silly"], answer: "scared", relearn: "Scared is your body keeping you safe. Everyone feels it.", persona: "Aria (sensitive)", mechanic: "name-match", source: "CASEL self-awareness" },
  { id: "ff-004", cat: "name", situation: "Your favourite ice cream falls on the floor.", prompt: "How do you feel?", options: ["sad", "excited", "calm"], answer: "sad", relearn: "Sad is okay. It means you cared about it.", persona: "any", mechanic: "name-match", source: "affect labeling" },
  { id: "ff-005", cat: "name", situation: "Your friend got a turn on the swing and you didn't yet.", prompt: "How do you feel?", options: ["jealous", "sleepy", "proud"], answer: "jealous", relearn: "Wanting what someone has is jealousy. It passes.", persona: "any", mechanic: "name-match", source: "CASEL self-awareness" },
  { id: "ff-006", cat: "name", situation: "You tripped in front of the whole class.", prompt: "How do you feel?", options: ["embarrassed", "excited", "calm"], answer: "embarrassed", relearn: "Embarrassed is that hot-cheeks feeling. It fades.", persona: "any", mechanic: "name-match", source: "CASEL self-awareness" },
  { id: "ff-007", cat: "name", situation: "You finished a puzzle all by yourself.", prompt: "How do you feel?", options: ["proud", "scared", "grumpy"], answer: "proud", relearn: "That tall, happy feeling is proud. You did it.", persona: "Kabir (deep focus)", mechanic: "name-match", source: "CASEL self-awareness" },
  { id: "ff-008", cat: "name", situation: "A new kid asks you to play and you don't know them yet.", prompt: "How do you feel?", options: ["shy", "angry", "bored"], answer: "shy", relearn: "Shy is okay. You can take your time.", persona: "Aria (observer)", mechanic: "name-match", source: "CASEL self-awareness" },
  { id: "ff-009", cat: "name", situation: "Someone took your toy without asking.", prompt: "How do you feel?", options: ["angry", "happy", "sleepy"], answer: "angry", relearn: "Angry is a normal feeling. It tells us something feels unfair.", persona: "Vihaan (bold)", mechanic: "name-match", source: "CASEL self-awareness" },
  { id: "ff-010", cat: "name", situation: "A magic trick surprises you out of nowhere.", prompt: "How do you feel?", options: ["surprised", "sad", "shy"], answer: "surprised", relearn: "Surprised is the big-eyes, jumpy feeling.", persona: "any", mechanic: "name-match", source: "CASEL self-awareness" },
  { id: "ff-011", cat: "name", situation: "The park trip was cancelled because of rain.", prompt: "How do you feel?", options: ["disappointed", "excited", "proud"], answer: "disappointed", relearn: "Disappointed is when something you wanted didn't happen.", persona: "any", mechanic: "name-match", source: "CASEL self-awareness" },
  { id: "ff-012", cat: "name", situation: "Everyone is playing together and no one called you over.", prompt: "How do you feel?", options: ["lonely", "silly", "calm"], answer: "lonely", relearn: "Lonely is wanting to be included. You can ask to join.", persona: "Faizan-type (left out)", mechanic: "name-match", source: "CASEL social awareness" },
  { id: "ff-013", cat: "name", situation: "It's your first day and you're about to walk in.", prompt: "How do you feel?", options: ["nervous", "bored", "grumpy"], answer: "nervous", relearn: "Nervous is butterflies before something new. Brave feels like this too.", persona: "Aria", mechanic: "name-match", source: "CASEL self-awareness" },
  { id: "ff-014", cat: "name", situation: "You're snuggled up with someone who loves you.", prompt: "How do you feel?", options: ["loved", "scared", "angry"], answer: "loved", relearn: "Warm and safe is feeling loved.", persona: "any", mechanic: "name-match", source: "CASEL self-awareness" },
  { id: "ff-015", cat: "name", situation: "You just woke up from a nap and nothing feels right.", prompt: "How do you feel?", options: ["grumpy", "excited", "proud"], answer: "grumpy", relearn: "Grumpy is okay. Sometimes our body just needs a minute.", persona: "any", mechanic: "name-match", source: "CASEL self-management" },
  { id: "ff-016", cat: "name", situation: "You found a wiggly caterpillar on a leaf.", prompt: "How do you feel?", options: ["curious", "angry", "embarrassed"], answer: "curious", relearn: "Curious is the want-to-know feeling. Lensy loves it.", persona: "any", mechanic: "name-match", source: "CASEL self-awareness" },
  { id: "ff-017", cat: "name", situation: "You've been waiting a long time with nothing to do.", prompt: "How do you feel?", options: ["bored", "scared", "proud"], answer: "bored", relearn: "Bored is okay. It's a chance to imagine something.", persona: "any", mechanic: "name-match", source: "CASEL self-awareness" },
  { id: "ff-018", cat: "name", situation: "You can't decide which game to play.", prompt: "How do you feel?", options: ["confused", "loved", "silly"], answer: "confused", relearn: "Confused is the foggy feeling. Asking helps.", persona: "any", mechanic: "name-match", source: "CASEL self-awareness" },
  { id: "ff-019", cat: "name", situation: "You're making the silliest face in the mirror.", prompt: "How do you feel?", options: ["silly", "sad", "nervous"], answer: "silly", relearn: "Silly is a happy, playful feeling.", persona: "Vihaan", mechanic: "name-match", source: "CASEL self-awareness" },
  { id: "ff-020", cat: "name", situation: "Tomorrow you're going somewhere you've never been.", prompt: "How do you feel?", options: ["worried", "calm", "bored"], answer: "worried", relearn: "Worried is when our mind asks 'what if'. Talking helps.", persona: "Aria", mechanic: "name-match", source: "CASEL self-awareness" },
  { id: "ff-021", cat: "name", situation: "You're lying in the grass watching slow clouds.", prompt: "How do you feel?", options: ["calm", "angry", "jealous"], answer: "calm", relearn: "Calm is the slow, easy feeling. We can make more of it.", persona: "Kabir", mechanic: "name-match", source: "Zones of Regulation" },
  { id: "ff-022", cat: "name", situation: "Your tummy rumbles and snacks aren't ready.", prompt: "How does your body feel?", options: ["hungry and cranky", "proud", "shy"], answer: "hungry and cranky", relearn: "Sometimes a feeling is really our body needing food or rest.", persona: "any", mechanic: "name-match", source: "CASEL self-management" },
  { id: "ff-023", cat: "name", situation: "It's very late and your eyes keep closing.", prompt: "How does your body feel?", options: ["tired", "excited", "curious"], answer: "tired", relearn: "Tired is your body asking for rest. That's wise to listen to.", persona: "any", mechanic: "name-match", source: "CASEL self-management" },
  { id: "ff-024", cat: "name", situation: "You hear a song you absolutely love.", prompt: "How do you feel?", options: ["happy", "scared", "grumpy"], answer: "happy", relearn: "Happy is the light, bouncy feeling. Enjoy it.", persona: "any", mechanic: "name-match", source: "CASEL self-awareness" },
  { id: "ff-025", cat: "all-okay", situation: "A boy falls and scrapes his knee and starts to cry. Another kid says 'boys don't cry'.", prompt: "Is that true?", options: ["No, everyone cries", "Yes, only girls cry"], answer: "No, everyone cries", relearn: "Everyone cries. Crying lets big feelings out. Feelings aren't a gender.", myth: "Boys don't cry.", persona: "Vihaan; gender thread", mechanic: "all-okay", source: "gender emotion socialization research (no innate difference)" },
  { id: "ff-026", cat: "all-okay", situation: "A girl is really angry that the game was unfair. Someone says 'good girls don't get angry'.", prompt: "Is that true?", options: ["No, anyone can feel angry", "Yes, girls must stay sweet"], answer: "No, anyone can feel angry", relearn: "Girls feel angry too. Anger is okay; it shows us unfairness.", myth: "Good girls don't get angry.", persona: "Aria; gender thread", mechanic: "all-okay", source: "gender emotion socialization research" },
  { id: "ff-027", cat: "all-okay", situation: "You feel scared of the dark and wonder if that's babyish.", prompt: "Is being scared okay?", options: ["Yes, everyone feels scared", "No, big kids are never scared"], answer: "Yes, everyone feels scared", relearn: "Everyone feels scared sometimes, even grown-ups. Brave can feel scared too.", myth: "Big kids are never scared.", persona: "any", mechanic: "all-okay", source: "CASEL" },
  { id: "ff-028", cat: "all-okay", situation: "You feel jealous of a friend's new shoes and worry that's mean.", prompt: "Is it okay to feel jealous?", options: ["Yes, the feeling is okay", "No, jealousy is bad"], answer: "Yes, the feeling is okay", relearn: "Feeling jealous is okay. What matters is being kind anyway.", myth: "Some feelings are bad.", persona: "any", mechanic: "all-okay", source: "CASEL self-management" },
  { id: "ff-029", cat: "all-okay", situation: "A boy is dancing and twirling with joy. Someone laughs that boys shouldn't.", prompt: "Can boys feel joyful and dance?", options: ["Yes, joy is for everyone", "No, that's only for girls"], answer: "Yes, joy is for everyone", relearn: "Every feeling and every joy is for every kid.", myth: "Some feelings belong to one gender.", persona: "Faizan-type; gender thread", mechanic: "all-okay", source: "gender socialization research" },
  { id: "ff-030", cat: "all-okay", situation: "You're crying and someone says 'stop crying, it's nothing'.", prompt: "Are your tears okay?", options: ["Yes, my feelings are real", "No, I should hide them"], answer: "Yes, my feelings are real", relearn: "Your feelings are real and okay to show. Hiding them makes them bigger.", myth: "Keep big feelings inside.", persona: "any", mechanic: "all-okay", source: "affect labeling" },
  { id: "ff-031", cat: "all-okay", situation: "You feel two things at once: happy to start school but sad to leave home.", prompt: "Can you feel two feelings together?", options: ["Yes, that's normal", "No, only one at a time"], answer: "Yes, that's normal", relearn: "You can feel two feelings at once. That's how hearts work.", persona: "Aria", mechanic: "all-okay", source: "CASEL self-awareness" },
  { id: "ff-032", cat: "all-okay", situation: "A dad is crying happy tears at something sweet. A child wonders if dads cry.", prompt: "Do grown-up men cry too?", options: ["Yes, everyone does", "No, men never cry"], answer: "Yes, everyone does", relearn: "Grown-ups cry too, including dads. Tears aren't weak.", myth: "Real men don't cry.", persona: "gender thread; parent", mechanic: "all-okay", source: "gender socialization research" },
  { id: "ff-033", cat: "all-okay", situation: "You're angry and worried that being angry makes you naughty.", prompt: "Does feeling angry make you naughty?", options: ["No, anger is just a feeling", "Yes, angry kids are bad"], answer: "No, anger is just a feeling", relearn: "Anger isn't naughty. Hurting others isn't okay, but the feeling is fine.", myth: "Being angry means you're bad.", persona: "Vihaan", mechanic: "all-okay", source: "CASEL self-management" },
  { id: "ff-034", cat: "all-okay", situation: "You feel shy and someone says 'don't be shy, that's silly'.", prompt: "Is it okay to feel shy?", options: ["Yes, shy is okay", "No, shy is silly"], answer: "Yes, shy is okay", relearn: "Shy is okay. You can join in when you're ready.", persona: "Aria", mechanic: "all-okay", source: "CASEL" },
  { id: "ff-035", cat: "all-okay", situation: "Loud sounds upset you and someone says you're being dramatic.", prompt: "Is it okay that loud sounds bother you?", options: ["Yes, that's okay for me", "No, I'm being silly"], answer: "Yes, that's okay for me", relearn: "Bodies feel things differently. Your feelings are real and okay.", persona: "Kabir (sensory-sensitive)", mechanic: "all-okay", source: "neurodiversity-affirming" },
  { id: "ff-036", cat: "all-okay", situation: "You feel proud and wonder if saying so is showing off.", prompt: "Is it okay to feel proud of yourself?", options: ["Yes, proud is healthy", "No, that's bragging"], answer: "Yes, proud is healthy", relearn: "Feeling proud of your effort is healthy and good.", persona: "Kabir", mechanic: "all-okay", source: "CASEL self-awareness" },
  { id: "ff-037", cat: "all-okay", situation: "You don't feel like smiling today and a grown-up says 'put on a happy face'.", prompt: "Do you have to feel happy all the time?", options: ["No, all feelings are okay", "Yes, always be happy"], answer: "No, all feelings are okay", relearn: "You don't have to be happy all the time. Every feeling is allowed.", myth: "You should always be happy.", persona: "any", mechanic: "all-okay", source: "CASEL" },
  { id: "ff-038", cat: "all-okay", situation: "A girl wants to be the brave leader in a game. Someone says that's a boy's role.", prompt: "Can girls feel brave and lead?", options: ["Yes, bravery is for everyone", "No, only boys are brave"], answer: "Yes, bravery is for everyone", relearn: "Bravery and leading are for every kid.", myth: "Only boys are brave.", persona: "gender thread", mechanic: "all-okay", source: "gender socialization research" },
  { id: "ff-039", cat: "calm", situation: "You're so angry your hands are tight fists.", prompt: "What could help right now?", options: ["Take three slow belly breaths", "Hit the wall"], answer: "Take three slow belly breaths", relearn: "Slow belly breaths tell your body it's safe. Breathe with Lensy.", persona: "Vihaan", mechanic: "calm-pick", source: "deep belly breathing (evidence-based)" },
  { id: "ff-040", cat: "calm", situation: "Big feelings are bubbling up fast.", prompt: "Try the candle breath:", options: ["Smell the flower, blow the candle", "Hold your breath tight"], answer: "Smell the flower, blow the candle", relearn: "Breathe in like smelling a flower, out like blowing a candle.", persona: "any", mechanic: "calm-do", source: "preschool breathing technique" },
  { id: "ff-041", cat: "calm", situation: "You feel like you might burst.", prompt: "What can you count?", options: ["Count slowly to five", "Count nothing, just yell"], answer: "Count slowly to five", relearn: "Counting to five gives the big feeling time to soften.", persona: "any", mechanic: "calm-pick", source: "self-regulation strategies" },
  { id: "ff-042", cat: "calm", situation: "Everything feels too loud and too much.", prompt: "What might help you?", options: ["Go to a quiet calm corner", "Stay in the loud room"], answer: "Go to a quiet calm corner", relearn: "A quiet calm corner is a safe place to settle. It's okay to take space.", persona: "Kabir", mechanic: "calm-pick", source: "calm-down corner (evidence-based)" },
  { id: "ff-043", cat: "calm", situation: "You're upset and don't know what to do with it.", prompt: "What's a good first step?", options: ["Name the feeling out loud", "Pretend it's not there"], answer: "Name the feeling out loud", relearn: "Naming it ('I feel angry') makes it smaller. Name it to tame it.", persona: "any", mechanic: "calm-pick", source: "affect labeling (Siegel; Lieberman)" },
  { id: "ff-044", cat: "calm", situation: "You feel wobbly and sad inside.", prompt: "Who could you ask?", options: ["Ask a trusted grown-up for a hug", "Hide it from everyone"], answer: "Ask a trusted grown-up for a hug", relearn: "Asking for a hug or help is brave, not babyish.", persona: "Aria", mechanic: "calm-pick", source: "CASEL relationship skills" },
  { id: "ff-045", cat: "calm", situation: "Your body feels jittery and hot with anger.", prompt: "A safe way to let it out:", options: ["Stomp like a dinosaur, then breathe", "Push your friend"], answer: "Stomp like a dinosaur, then breathe", relearn: "Move the energy safely (stomp, squeeze a pillow), then breathe.", persona: "Vihaan", mechanic: "calm-pick", source: "self-regulation strategies" },
  { id: "ff-046", cat: "calm", situation: "You're crying hard and feel thirsty after.", prompt: "What can help your body reset?", options: ["Sip some water", "Skip the water"], answer: "Sip some water", relearn: "A drink of water and a breath help your body settle.", persona: "any", mechanic: "calm-pick", source: "self-regulation strategies" },
  { id: "ff-047", cat: "calm", situation: "You squeeze your hands and shoulders when worried.", prompt: "Try the squeeze-and-release:", options: ["Squeeze tight, then let go floppy", "Stay tight forever"], answer: "Squeeze tight, then let go floppy", relearn: "Squeeze tight, then go floppy like jelly. Your body softens.", persona: "Kabir", mechanic: "calm-do", source: "progressive relaxation for kids" },
  { id: "ff-048", cat: "calm", situation: "Your mind is racing and you can't sit still.", prompt: "Try the look-around game:", options: ["Find 5 things you can see", "Close your eyes and spin"], answer: "Find 5 things you can see", relearn: "Looking for things you can see brings you back to now.", persona: "any", mechanic: "calm-do", source: "5-4-3-2-1 grounding" },
  { id: "ff-049", cat: "calm", situation: "You want to calm down but don't want to be alone.", prompt: "What can you do together?", options: ["Breathe with a grown-up", "Run away from everyone"], answer: "Breathe with a grown-up", relearn: "Calming down with someone you trust works too. Co-regulation.", persona: "any; parent co-play", mechanic: "calm-pick", source: "co-regulation (early childhood)" },
  { id: "ff-050", cat: "calm", situation: "The big feeling is fading but you still feel shaky.", prompt: "What's a kind thing to tell yourself?", options: ["'This feeling will pass'", "'I'll feel awful forever'"], answer: "'This feeling will pass'", relearn: "Feelings come and go like weather. This one will pass.", persona: "any", mechanic: "calm-pick", source: "CASEL self-management" },
  { id: "ff-051", cat: "calm", situation: "You did your breathing and feel a bit better.", prompt: "What now?", options: ["Notice you feel calmer", "Decide it didn't work"], answer: "Notice you feel calmer", relearn: "Notice the calm. You helped yourself, that's a superpower.", persona: "any", mechanic: "calm-pick", source: "CASEL self-management" },
  { id: "ff-052", cat: "calm", situation: "You're frustrated with a hard puzzle.", prompt: "What helps with stuck feelings?", options: ["Take a break, then try again", "Give up and feel bad"], answer: "Take a break, then try again", relearn: "A break resets your brain. Stuck isn't forever.", persona: "Kabir", mechanic: "calm-pick", source: "self-regulation; growth mindset" },
  { id: "ff-053", cat: "calm", situation: "You feel a meltdown coming.", prompt: "Early sign spotting:", options: ["Tell someone 'I need a minute'", "Wait until you explode"], answer: "Tell someone 'I need a minute'", relearn: "Catching it early and asking for a minute is a real skill.", persona: "any", mechanic: "calm-pick", source: "self-regulation strategies" },
  { id: "ff-054", cat: "calm", situation: "Your tummy feels fluttery before something new.", prompt: "Calm the butterflies:", options: ["Slow breaths and a brave thought", "Run away"], answer: "Slow breaths and a brave thought", relearn: "Nervous and brave feel the same; breathe and try the brave step.", persona: "Aria", mechanic: "calm-pick", source: "CASEL self-management" },
  { id: "ff-055", cat: "empathy", situation: "Your friend's face is scrunched and tears are coming.", prompt: "How does your friend feel?", options: ["sad", "excited", "silly"], answer: "sad", relearn: "You can read feelings on faces. Your friend looks sad.", persona: "any", mechanic: "empathy-read", source: "CASEL social awareness" },
  { id: "ff-056", cat: "empathy", situation: "A classmate is sitting alone while everyone plays.", prompt: "How might they feel?", options: ["lonely", "proud", "grumpy"], answer: "lonely", relearn: "They might feel lonely. You could invite them in.", persona: "Faizan-type", mechanic: "empathy-read", source: "CASEL social awareness" },
  { id: "ff-057", cat: "empathy", situation: "Your friend is jumping and clapping with a big grin.", prompt: "How do they feel?", options: ["excited", "scared", "bored"], answer: "excited", relearn: "A big grin and jumping usually means excited.", persona: "any", mechanic: "empathy-read", source: "CASEL social awareness" },
  { id: "ff-058", cat: "empathy", situation: "A kid's shoulders are slumped and they're very quiet.", prompt: "How might they feel?", options: ["down or upset", "silly", "proud"], answer: "down or upset", relearn: "Bodies talk too. Slumped and quiet can mean upset.", persona: "any", mechanic: "empathy-read", source: "CASEL social awareness" },
  { id: "ff-059", cat: "empathy", situation: "Your brother's toy broke and he's stomping around.", prompt: "How does he feel?", options: ["frustrated", "calm", "loved"], answer: "frustrated", relearn: "Stomping can mean frustrated. He's not being 'bad'.", persona: "Vihaan; sibling", mechanic: "empathy-read", source: "CASEL social awareness" },
  { id: "ff-060", cat: "empathy", situation: "A new kid is hiding behind their parent's leg.", prompt: "How might they feel?", options: ["shy or nervous", "angry", "bored"], answer: "shy or nervous", relearn: "Hiding can mean shy or nervous. A gentle smile helps.", persona: "Aria", mechanic: "empathy-read", source: "CASEL social awareness" },
  { id: "ff-061", cat: "empathy", situation: "Your friend dropped their snack and looks at it sadly.", prompt: "What might help?", options: ["Offer to share yours", "Laugh at them"], answer: "Offer to share yours", relearn: "Noticing and offering to share is kindness in action.", persona: "any", mechanic: "empathy-act", source: "CASEL relationship skills" },
  { id: "ff-062", cat: "empathy", situation: "A friend lost their game and is frowning.", prompt: "What's a kind thing to say?", options: ["'Good try, want to play again?'", "'You're a loser'"], answer: "'Good try, want to play again?'", relearn: "Kind words help a friend's hard feeling soften.", persona: "any", mechanic: "empathy-act", source: "CASEL relationship skills" },
  { id: "ff-063", cat: "empathy", situation: "Two friends both want the same red crayon.", prompt: "How do they both feel, and what helps?", options: ["Both want it; take turns", "Grab it and run"], answer: "Both want it; take turns", relearn: "Both feel wanting. Taking turns is fair and kind.", persona: "any", mechanic: "empathy-act", source: "CASEL relationship skills" },
  { id: "ff-064", cat: "empathy", situation: "A boy is crying and other kids start to giggle.", prompt: "What's the kind choice?", options: ["Check if he's okay", "Giggle along"], answer: "Check if he's okay", relearn: "Kindness over giggles. Everyone's tears deserve care.", persona: "gender thread", mechanic: "empathy-act", source: "CASEL; gender socialization" },
  { id: "ff-065", cat: "empathy", situation: "Your friend is scared of the slide.", prompt: "How can you help?", options: ["Stay with them and cheer gently", "Call them a baby"], answer: "Stay with them and cheer gently", relearn: "Being with someone scared helps them feel brave.", persona: "any", mechanic: "empathy-act", source: "CASEL relationship skills" },
  { id: "ff-066", cat: "empathy", situation: "A grown-up looks tired and sighs a lot.", prompt: "Can grown-ups have big feelings too?", options: ["Yes, everyone does", "No, only kids"], answer: "Yes, everyone does", relearn: "Grown-ups have feelings too. A hug can help them.", persona: "parent", mechanic: "empathy-read", source: "CASEL social awareness" },
  { id: "ff-067", cat: "empathy", situation: "Your friend made a face you can't read.", prompt: "What can you do to understand?", options: ["Ask 'how are you feeling?'", "Guess and ignore them"], answer: "Ask 'how are you feeling?'", relearn: "When unsure, asking is the kindest way to understand.", persona: "any", mechanic: "empathy-act", source: "CASEL social awareness" },
  { id: "ff-068", cat: "empathy", situation: "A kid is proud of their drawing and shows you.", prompt: "How do they feel and what helps?", options: ["Proud; say something kind", "Say it's ugly"], answer: "Proud; say something kind", relearn: "Sharing in someone's pride grows friendship.", persona: "any", mechanic: "empathy-act", source: "CASEL relationship skills" },
  { id: "ff-069", cat: "empathy", situation: "Your friend is angry at you and you don't know why.", prompt: "What's a good move?", options: ["Ask calmly what's wrong", "Get angry back"], answer: "Ask calmly what's wrong", relearn: "Asking calmly helps you both understand the feeling.", persona: "any", mechanic: "empathy-act", source: "CASEL relationship skills" },
  { id: "ff-070", cat: "empathy", situation: "A classmate uses a wheelchair and feels left out of a game.", prompt: "What's the kind, fair choice?", options: ["Change the game so they can join", "Leave them out"], answer: "Change the game so they can join", relearn: "Including everyone is what good friends do.", persona: "inclusion", mechanic: "empathy-act", source: "CASEL social awareness" },
  { id: "ff-071", cat: "big-no", situation: "A relative wants a big hug and you don't feel like it.", prompt: "What can you say?", options: ["'No thank you, maybe a high-five'", "You must hug them"], answer: "'No thank you, maybe a high-five'", relearn: "Your body is yours. 'No thank you' is always okay.", myth: "You must hug someone if they ask.", persona: "any; consent seed", mechanic: "big-no", source: "body autonomy; consent foundations" },
  { id: "ff-072", cat: "big-no", situation: "A friend keeps tickling you after you stopped laughing.", prompt: "What do you do?", options: ["Say a Big No: 'Stop, I don't like it'", "Keep quiet and hate it"], answer: "Say a Big No: 'Stop, I don't like it'", relearn: "You can say a Big No when something doesn't feel good.", persona: "any", mechanic: "big-no", source: "consent foundations" },
  { id: "ff-073", cat: "big-no", situation: "You said yes to a game but now you want to stop.", prompt: "Can you change your mind?", options: ["Yes, you can say stop anytime", "No, you must keep playing"], answer: "Yes, you can say stop anytime", relearn: "You can change your mind. Yes can become no.", myth: "If you said yes, you can't stop.", persona: "any; consent seed", mechanic: "big-no", source: "consent foundations" },
  { id: "ff-074", cat: "big-no", situation: "Someone offers a sweet but you don't want it.", prompt: "What can you say?", options: ["'No thank you'", "Take it to be polite"], answer: "'No thank you'", relearn: "Saying no politely is allowed, even to grown-ups.", persona: "any", mechanic: "big-no", source: "assertiveness" },
  { id: "ff-075", cat: "big-no", situation: "A friend wants you to do something that feels wrong.", prompt: "What's okay to do?", options: ["Say no and walk away", "Do it so they like you"], answer: "Say no and walk away", relearn: "You can say no to a friend and still be a good friend.", myth: "You must do what friends say.", persona: "any", mechanic: "big-no", source: "CASEL responsible decision-making" },
  { id: "ff-076", cat: "big-no", situation: "Your cheeks feel hot and your tummy says 'uh-oh' about something.", prompt: "What is that uh-oh feeling?", options: ["A signal to say no or tell someone", "Nothing, ignore it"], answer: "A signal to say no or tell someone", relearn: "That uh-oh feeling is your helper. Listen and tell a trusted adult — it's never your fault.", persona: "any; safety", mechanic: "big-no", source: "body-safety foundations" },
  { id: "ff-077", cat: "big-no", situation: "A bigger kid says 'do it or you're a baby'.", prompt: "What can you do?", options: ["Say no and find a trusted adult", "Do it to prove yourself"], answer: "Say no and find a trusted adult", relearn: "Dares don't decide for you. No is brave.", persona: "Vihaan", mechanic: "big-no", source: "assertiveness; safety" },
  { id: "ff-078", cat: "big-no", situation: "Someone wants to take a photo of you and you feel unsure.", prompt: "Is it okay to say no?", options: ["Yes, you can say no", "No, you have to smile"], answer: "Yes, you can say no", relearn: "You can say no to photos too. Your body, your choice.", persona: "any", mechanic: "big-no", source: "body autonomy" },
  { id: "ff-079", cat: "big-no", situation: "You feel angry but you also feel like saying sorry isn't enough.", prompt: "Can you say what you need?", options: ["'I'm still upset, I need space'", "Pretend you're fine"], answer: "'I'm still upset, I need space'", relearn: "Naming what you need is a kind, honest kind of no.", persona: "Aria (people-pleaser)", mechanic: "big-no", source: "CASEL self-awareness; assertiveness" },
  { id: "ff-080", cat: "big-no", situation: "A game is too rough and you want out.", prompt: "What can you say?", options: ["'I want to stop now'", "Get hurt rather than speak"], answer: "'I want to stop now'", relearn: "You can leave a game that feels too much. Speak up.", persona: "Kabir", mechanic: "big-no", source: "assertiveness" },
  { id: "ff-081", cat: "help", situation: "Your friend is crying after falling down.", prompt: "What can you do?", options: ["Ask 'are you okay?' and get help", "Walk away"], answer: "Ask 'are you okay?' and get help", relearn: "Checking in and getting a grown-up is being a good friend.", persona: "any", mechanic: "help-pick", source: "CASEL relationship skills" },
  { id: "ff-082", cat: "help", situation: "You accidentally knocked over a friend's tower.", prompt: "What's the kind thing?", options: ["Say sorry and help rebuild", "Blame someone else"], answer: "Say sorry and help rebuild", relearn: "Sorry plus helping fixes feelings and friendships.", persona: "Vihaan", mechanic: "help-pick", source: "CASEL responsible decision-making" },
  { id: "ff-083", cat: "help", situation: "A new kid doesn't know anyone.", prompt: "How can you help them feel better?", options: ["Invite them to play", "Ignore them"], answer: "Invite them to play", relearn: "An invitation can turn lonely into belonging.", persona: "Faizan-type", mechanic: "help-pick", source: "CASEL social awareness" },
  { id: "ff-084", cat: "help", situation: "Your friend is scared and squeezing your hand.", prompt: "What helps?", options: ["Stay close and breathe together", "Pull your hand away"], answer: "Stay close and breathe together", relearn: "Staying close helps a scared friend feel safe.", persona: "any", mechanic: "help-pick", source: "co-regulation" },
  { id: "ff-085", cat: "help", situation: "Two friends are fighting over a toy and both are upset.", prompt: "What could you suggest?", options: ["'Let's take turns'", "Take the toy yourself"], answer: "'Let's take turns'", relearn: "Helping friends share calms everyone's big feelings.", persona: "any", mechanic: "help-pick", source: "CASEL relationship skills" },
  { id: "ff-086", cat: "help", situation: "Your sibling is sad their drawing tore.", prompt: "What's a caring thing to do?", options: ["Offer to fix it or make a new one", "Say 'who cares'"], answer: "Offer to fix it or make a new one", relearn: "Small caring acts say 'your feelings matter to me'.", persona: "sibling", mechanic: "help-pick", source: "CASEL relationship skills" },
  { id: "ff-087", cat: "help", situation: "A friend keeps being left out by others.", prompt: "What can you do?", options: ["Include them and tell a grown-up if it keeps happening", "Join the others"], answer: "Include them and tell a grown-up if it keeps happening", relearn: "Being an includer, and asking for help, is brave kindness.", persona: "Faizan-type; ally seed", mechanic: "help-pick", source: "CASEL; bystander foundations" },
  { id: "ff-088", cat: "help", situation: "You feel too big a feeling to handle alone.", prompt: "Who is on your Help-Map?", options: ["A trusted grown-up I can go to", "No one, handle it alone"], answer: "A trusted grown-up I can go to", relearn: "Knowing your trusted grown-ups (your Help-Map) is a life skill.", persona: "any; toolkit Help-Map", mechanic: "help-pick", source: "CASEL; safeguarding (Help-Map tool)" }];

export const byCat = (c: Cat): Scenario[] => SCENARIOS.filter((s) => s.cat === c);

// The six verb-moves — a sandbox, not a quiz. Each maps to a category; the mechanic IS the lesson, and the
// session rotates them so a child never meets the same beat twice running (the strategy palette rule).
export type Move = { id: Cat; emoji: string; label: string; sam: string; teaches: string; coplay: string };
export const MOVES: Move[] = [
  { id: "name", emoji: "🎯", label: "Name it", sam: "How does this feel? Tap the feeling.", teaches: "Name the feeling", coplay: "Ask them which one it is — there's no wrong answer." },
  { id: "all-okay", emoji: "✅", label: "It's okay", sam: "Someone said something about feelings. Is it true?", teaches: "Every feeling is okay", coplay: "Talk it over — every feeling is allowed, for every kid." },
  { id: "calm", emoji: "🌸", label: "Calm it", sam: "Let's calm a big feeling together.", teaches: "Calm the big feeling", coplay: "Breathe along with them — flower in, candle out." },
  { id: "empathy", emoji: "💗", label: "How do they feel?", sam: "Let's read a friend's feeling.", teaches: "Read how others feel", coplay: "Wonder aloud: how do you think they feel?" },
  { id: "big-no", emoji: "✋", label: "Big No", sam: "Let's practise our big, brave No.", teaches: "You can say no", coplay: "Cheer their Big No — their body is theirs." },
  { id: "help", emoji: "🤝", label: "I can help", sam: "What kind thing can you do?", teaches: "Help a friend", coplay: "Ask: what would help your friend?" },
];
export const MOVE_BY_ID: Record<Cat, Move> = Object.fromEntries(MOVES.map((m) => [m.id, m])) as Record<Cat, Move>;

// Calm Corner — the flower/candle belly-breath, kept and deepened (the only place the game slows right down).
export const CALM_STEPS = [
  { id: "in", label: "Smell the flower", emoji: "🌸", say: "Smell the flower… breathe in slowly.", ms: 4000 },
  { id: "out", label: "Blow the candle", emoji: "🕯️", say: "Blow the candle… breathe out slowly.", ms: 4000 },
] as const;
export const CALM_CYCLES = 3;

export const SAM = {
  greet: "Hello! I'm Sam, and this is Lensy. Every feeling is okay — let's play!",
  home: "What shall we play?",
  play: "Let's play! Ready?",
  nudge: "Hmm, let's look again. Which one feels right?",
  sticker: "A sticker for your feelings book!",
  badge: "You earned a sticker!",
  unAll: "Some people say that — but it isn't true. Let's rub it out.",
  complete: "You did it! Every feeling is okay — and you have ways to handle the big ones. 💛",
};
