// Content for Friend or Frenemy? (node g09, ages 6–9, Chapter 2) — reworked to GDD 09 v2 (mechanic-embodying).
// "Spot a real friend, be one." The healthy-friendship game (the protocol's first reference implementation):
// 82 researched, India-grounded scenarios across six categories, each re-encoded to one of the shared v2 play
// actions (reflect / role-play / strike-rewrite / branch / sort / match / build / spot) — no binary "tap the
// right card", led by real friendship DILEMMAS (branch ×28 — decide, see the ripple, get a debrief) +
// say-the-line comebacks (role-play) + frenemy-flag SPOT scenes. Teaches friendship-quality literacy: what a
// real friend is, the frenemy flags (mean teasing, jealousy, control, exclusion, hot-and-cold, online), the
// everyday dilemmas, assertive + ally lines, and repair. AUTONOMY OVER VERDICTS (dilemmas have several good
// moves; the game backs the child's reasoning, never one "right" tap); SAFE TO BE WRONG (a weaker choice gets
// a kind consequence + a second look, no buzzer); NAME BEHAVIOURS NOT "BAD KIDS"; bullying / not-feeling-safe
// routes to a trusted adult (Childline 1098), help-seeking framed as brave. Builds on g03 (My Family Garden).
// Rendered by the shared engine (components/games/v2-engine.tsx). gameId "friend-frenemy". DO NOT RENAME.

import type { Scenario, V2GameConfig } from "./v2-schema";

const SCENARIOS: Scenario[] = [
  // — Real friends —
  {"id":"ff-001","cat":"real-friend","type":"build","hook":"Lensy: let's build a real friend, what goes in?","prompt":"Drag the real-friend qualities into the jar.","pieces":["is kind to you","listens to you","is happy when you do well","laughs AT you","includes you","only plays when no one better is around","keeps your secrets","tells you the truth gently"],"mode":"assemble","key":["is kind to you","listens to you","is happy when you do well","includes you","keeps your secrets","tells you the truth gently"],"relearn":"A real friend is kind, listens, includes you, and is glad when you do well.","persona":"any","source":"friendship-quality research"},
  {"id":"ff-002","cat":"real-friend","type":"match","hook":"What a good friend does, and how it makes you feel.","pairs":[{"left":"Cheers when you score","right":"You feel proud"},{"left":"Listens when you're sad","right":"You feel understood"},{"left":"Shares the snack","right":"You feel cared for"},{"left":"Saves you a seat","right":"You feel included"}],"relearn":"Good friends leave you feeling proud, understood, cared for and included.","persona":"any","source":"friendship-quality"},
  {"id":"ff-003","cat":"real-friend","type":"sort","hook":"Sort what you'd want in a friend.","items":[{"id":"a","text":"Happy when you win"},{"id":"b","text":"Sulks when you win"},{"id":"c","text":"Tells you the truth kindly"},{"id":"d","text":"Teases you in front of others"},{"id":"e","text":"Sticks around when you're sad"},{"id":"f","text":"Only calls when bored"}],"bins":[{"id":"real","label":"Real friend"},{"id":"not","label":"Not so much"}],"key":{"a":"real","b":"not","c":"real","d":"not","e":"real","f":"not"},"relearn":"Real friends are glad for you, honest-but-kind, and there in the hard moments.","persona":"any","source":"friendship-quality"},
  {"id":"ff-004","cat":"real-friend","type":"strike-rewrite","hook":"Someone says you can only have ONE best friend.","myth":{"un":"You're only allowed one real friend.","re":"You can have lots of friends, of different kinds.","why":"Friendship isn't a prize only one person can hold."},"relearn":"You can have many friends, and a wide circle is a strong one.","persona":"Reyansh","source":"social development"},
  {"id":"ff-005","cat":"real-friend","type":"reflect","hook":"Think of a friend who makes you feel good.","prompt":"What is one thing they do?","options":["They make me laugh","They listen to me","They include me","They're kind when I mess up"],"affirm":"That feeling, safe and glad, is what a real friend gives. Look for it, and give it.","relearn":"Notice who leaves you feeling good; that's a clue to a real friend.","persona":"any","source":"reflection / friendship-quality"},
  {"id":"ff-006","cat":"real-friend","type":"branch","hook":"A new kid is sitting alone at lunch.","options":[{"text":"Wave them over to your group","consequence":"They light up; your table gets more fun.","outcome":"kind","best":true},{"text":"Go sit with them","consequence":"They relax; you make their day.","outcome":"kind","best":true},{"text":"Leave them; not your problem","consequence":"They eat alone again; you both miss out.","outcome":"missed"}],"debrief":"More than one kind move works. Including someone is friendship.","relearn":"Including a lonely kid is an easy way to be kind.","persona":"Faizan","source":"inclusion"},
  {"id":"ff-007","cat":"real-friend","type":"role-play","hook":"You want to make friends with the new kid.","setup":"You walk over. What do you say?","yourLine":[{"text":"\"Hi, I'm ___. Want to play with us?\"","best":true},{"text":"Say nothing and hope they notice you"},{"text":"\"Why are you sitting alone?\""}],"relearn":"A warm, simple \"want to join us?\" is how most friendships start.","persona":"Reyansh","source":"social skills"},
  {"id":"ff-008","cat":"real-friend","type":"strike-rewrite","hook":"\"Real friends always say yes to you.\"","myth":{"un":"A real friend never says no to you.","re":"A real friend can say no and still care about you.","why":"Respect, not obedience, is what holds a friendship."},"relearn":"A friend who can say no honestly is a friend you can trust.","persona":"Ananya","source":"boundaries in friendship"},
  {"id":"ff-009","cat":"real-friend","type":"sort","hook":"Which of these are about being a GOOD friend yourself?","items":[{"id":"a","text":"Take turns"},{"id":"b","text":"Always be the boss"},{"id":"c","text":"Say sorry when you slip"},{"id":"d","text":"Keep score of favours"},{"id":"e","text":"Cheer your friend on"}],"bins":[{"id":"good","label":"Good friend move"},{"id":"no","label":"Not really"}],"key":{"a":"good","b":"no","c":"good","d":"no","e":"good"},"relearn":"Being a good friend means turns, repair and cheering, not bossing or scorekeeping.","persona":"any","source":"prosocial skills"},
  {"id":"ff-010","cat":"real-friend","type":"match","hook":"A friend has a problem. Match a kind response.","pairs":[{"left":"They failed a test","right":"\"That's hard. Want to study together?\""},{"left":"They're left out","right":"\"Come play with us.\""},{"left":"They're scared","right":"\"I'm here. You're not alone.\""}],"relearn":"Real friendship shows up most when a friend is struggling.","persona":"any","source":"empathy / support"},
  {"id":"ff-011","cat":"real-friend","type":"reflect","hook":"Lensy: what kind of friend do YOU want to be?","prompt":"Pick one to grow this week.","options":["A better listener","More including","Quicker to say sorry","More honest-but-kind"],"affirm":"Choosing how you show up is how good friends are made, not born.","relearn":"You can practise being a good friend, like any skill.","persona":"any","source":"growth mindset"},
  {"id":"ff-012","cat":"real-friend","type":"build","hook":"Build your friendship recipe.","prompt":"Pick the three ingredients you value most.","pieces":["honesty","fun","loyalty","kindness","respect","always agreeing"],"mode":"assemble","key":["honesty","fun","loyalty","kindness","respect"],"relearn":"Good friendships are built on respect and kindness, never on always agreeing.","persona":"any","source":"friendship-quality"},

  // — Frenemy flags —
  {"id":"ff-013","cat":"frenemy-flags","type":"spot","hook":"A 'friend' is doing a few things. Spot the frenemy flag.","scene":[{"id":"a","text":"Shares their colours with you","trick":false},{"id":"b","text":"Says \"I won't be your friend unless you give me your snack\"","trick":true},{"id":"c","text":"Saves you a seat","trick":false}],"why":"Threatening to drop you unless you do something is a control flag, not friendship.","relearn":"A friend who uses 'or else' to get their way is waving a frenemy flag.","persona":"any","source":"coercion / friendship-quality"},
  {"id":"ff-014","cat":"frenemy-flags","type":"strike-rewrite","hook":"\"She's just jealous because she cares about me.\"","myth":{"un":"A jealous friend is just being protective.","re":"Real friends celebrate you; they don't compete with you.","why":"Jealousy that sulks at your wins works against you, not for you."},"relearn":"A real friend is happy when good things happen to you.","persona":"Aanya","source":"friendship-quality / jealousy"},
  {"id":"ff-015","cat":"frenemy-flags","type":"sort","hook":"Sort these into Friend or Frenemy.","items":[{"id":"a","text":"Keeps your secret"},{"id":"b","text":"Tells your secret to be funny"},{"id":"c","text":"Includes you"},{"id":"d","text":"Leaves you out to feel powerful"},{"id":"e","text":"Is glad you did well"},{"id":"f","text":"Copies then mocks you"}],"bins":[{"id":"friend","label":"Friend"},{"id":"frenemy","label":"Frenemy"}],"key":{"a":"friend","b":"frenemy","c":"friend","d":"frenemy","e":"friend","f":"frenemy"},"relearn":"Frenemy moves use you, belittle you, or leave you out on purpose.","persona":"any","source":"friendship-quality"},
  {"id":"ff-016","cat":"frenemy-flags","type":"spot","hook":"Spot the flag in the group chat.","scene":[{"id":"a","text":"\"Great goal today!\"","trick":false},{"id":"b","text":"\"Do my homework or you're out of the group\"","trick":true},{"id":"c","text":"\"Who wants to play after school?\"","trick":false}],"why":"\"Do this or you're out\" is using the group to control you.","relearn":"Being threatened with exclusion is a control flag, online too.","persona":"Reyansh","source":"relational aggression"},
  {"id":"ff-017","cat":"frenemy-flags","type":"strike-rewrite","hook":"\"If they tease me, I must have earned it.\"","myth":{"un":"If a friend is mean to me, it's my fault.","re":"Unkindness is a choice the other person makes, not something you earn.","why":"You don't deserve cruelty for being yourself."},"relearn":"How a friend treats you is about their choices, not your worth.","persona":"Faizan","source":"self-worth / bullying"},
  {"id":"ff-018","cat":"frenemy-flags","type":"spot","hook":"Which one is a frenemy flag?","scene":[{"id":"a","text":"Disagrees with you sometimes","trick":false},{"id":"b","text":"Only nice when they need something","trick":true},{"id":"c","text":"Likes different games than you","trick":false}],"why":"Real friends can disagree and like different things; the flag is being used only when convenient.","relearn":"Disagreeing isn't a flag; being used is.","persona":"Ananya","source":"friendship-quality"},
  {"id":"ff-019","cat":"frenemy-flags","type":"strike-rewrite","hook":"\"To keep my friends, I have to do whatever they say.\"","myth":{"un":"You must do whatever your friends say or lose them.","re":"Friends worth keeping respect your no.","why":"A friendship that needs you to obey isn't a safe one."},"relearn":"You can keep your own mind and still keep real friends.","persona":"Reyansh","source":"peer pressure"},
  {"id":"ff-020","cat":"frenemy-flags","type":"sort","hook":"Teasing: all in good fun, or a flag?","items":[{"id":"a","text":"You both laugh and it stops when you ask"},{"id":"b","text":"It keeps going after you say stop"},{"id":"c","text":"It's about hurting, not fun"},{"id":"d","text":"It's gentle and you're both smiling"}],"bins":[{"id":"ok","label":"Friendly fun"},{"id":"flag","label":"Frenemy flag"}],"key":{"a":"ok","b":"flag","c":"flag","d":"ok"},"relearn":"Fun teasing stops when you ask; mean teasing keeps going and aims to hurt.","persona":"any","source":"teasing vs bullying"},
  {"id":"ff-021","cat":"frenemy-flags","type":"branch","hook":"Your friend laughs at your drawing in front of others.","options":[{"text":"Laugh along so you fit in","consequence":"It stings, and it recurs.","outcome":"unkind-to-self"},{"text":"Say \"that wasn't kind\" and step back","consequence":"They're surprised; a real friend apologises.","outcome":"assertive","best":true},{"text":"Quietly tell them later how it felt","consequence":"They listen; you get each other.","outcome":"repair","best":true}],"debrief":"More than one good move works.","relearn":"Name unkindness and still leave room to mend.","persona":"Aanya","source":"friendship"},
  {"id":"ff-022","cat":"frenemy-flags","type":"reflect","hook":"After playing with someone, how do you usually feel?","prompt":"Check in with yourself.","options":["Happy and relaxed","Worn out or put down","A mix","Not sure yet"],"affirm":"How a friend leaves you feeling is real information. Trust it.","relearn":"If someone often leaves you feeling small, that's worth noticing.","persona":"any","source":"emotional cues"},
  {"id":"ff-023","cat":"frenemy-flags","type":"spot","hook":"Spot the flag at the party.","scene":[{"id":"a","text":"Invites everyone but you, then tells you about it","trick":true},{"id":"b","text":"Invites the whole class","trick":false},{"id":"c","text":"Asks what games you like","trick":false}],"why":"Leaving you out on purpose, then making sure you know, is meant to hurt.","relearn":"Deliberate exclusion is a frenemy move, even with a smile.","persona":"Ananya","source":"relational aggression"},
  {"id":"ff-024","cat":"frenemy-flags","type":"match","hook":"Match the frenemy move to what it really is.","pairs":[{"left":"\"Only joking!\" after a mean dig","right":"Hurting, then hiding it"},{"left":"\"Best friends today\" then ignores you tomorrow","right":"Hot and cold control"},{"left":"Shares your secret for a laugh","right":"Betraying trust"}],"relearn":"Naming a frenemy move takes away its power to confuse you.","persona":"any","source":"relational aggression"},
  {"id":"ff-025","cat":"frenemy-flags","type":"branch","hook":"A friend says \"give me your pen or I'll tell everyone your secret.\"","options":[{"text":"Hand over the pen","consequence":"It works once, so they do it again.","outcome":"gives-in"},{"text":"Say \"that's not how friends act\" and tell a trusted adult","consequence":"The threat loses power; a grown-up can help.","outcome":"assertive","best":true}],"debrief":"A secret used as a threat isn't friendship.","relearn":"A friend who blackmails you isn't one; tell a trusted adult.","persona":"any","source":"safeguarding"},
  {"id":"ff-026","cat":"frenemy-flags","type":"sort","hook":"Online 'friend' behaviour, sort it.","items":[{"id":"a","text":"Likes your post and cheers you on"},{"id":"b","text":"Makes a group just to leave you out"},{"id":"c","text":"Shares a screenshot to embarrass you"},{"id":"d","text":"Tags you in something fun"}],"bins":[{"id":"friend","label":"Friend"},{"id":"frenemy","label":"Frenemy"}],"key":{"a":"friend","b":"frenemy","c":"frenemy","d":"friend"},"relearn":"The same flags fly online: cheering is friendship; excluding and embarrassing are not.","persona":"Reyansh","source":"digital friendships"},
  {"id":"ff-027","cat":"frenemy-flags","type":"strike-rewrite","hook":"\"Popular kids can treat others however they like.\"","myth":{"un":"Being popular means you can be unkind.","re":"Kindness, not popularity, is what makes someone worth following.","why":"Status never earns the right to hurt people."},"relearn":"No amount of cool makes unkindness okay.","persona":"Reyansh","source":"status / values"},
  {"id":"ff-028","cat":"frenemy-flags","type":"reflect","hook":"Lensy: a tricky one. Can someone be a friend sometimes and a frenemy other times?","prompt":"What do you think?","options":["Yes, and that mix is confusing","Friends should be steady","I've felt that before"],"affirm":"That on-off feeling is real and tiring. You deserve friends who are steady-kind.","relearn":"Ambivalent 'frenemy' ties are uniquely stressful; steady kindness is worth holding out for.","persona":"any","source":"ambivalent ties research"},
  {"id":"ff-072","cat":"frenemy-flags","type":"spot","hook":"Spot the kind one (the others are flags).","scene":[{"id":"a","text":"\"Be my friend or I'll tell everyone your secret\"","trick":true},{"id":"b","text":"\"You can't sit here, this is our table\"","trick":true},{"id":"c","text":"\"Want to share my umbrella?\"","trick":false}],"why":"Threats and shutting people out are flags; sharing is friendship.","relearn":"Sharing and welcoming are the real-friend signals to look for.","persona":"any","source":"friendship-quality"},
  {"id":"ff-078","cat":"frenemy-flags","type":"sort","hook":"Last flag check, sort fast.","items":[{"id":"a","text":"Happy for your win"},{"id":"b","text":"Makes you prove your loyalty"},{"id":"c","text":"Keeps your secrets"},{"id":"d","text":"Blows hot and cold"}],"bins":[{"id":"friend","label":"Friend"},{"id":"frenemy","label":"Frenemy"}],"key":{"a":"friend","b":"frenemy","c":"friend","d":"frenemy"},"relearn":"Steady gladness and trust are friend signals; loyalty-tests and hot-cold are flags.","persona":"any","source":"friendship-quality"},

  // — Friend dilemmas —
  {"id":"ff-029","cat":"dilemmas","type":"branch","hook":"Your group wants to leave one kid out of the game.","options":[{"text":"Go along with the group","consequence":"The kid is hurt; you feel off.","outcome":"bystander"},{"text":"Say \"let's all play\"","consequence":"Some grumble, but the kid joins.","outcome":"ally","best":true},{"text":"Quietly go play with the left-out kid","consequence":"You make a friend and set an example.","outcome":"ally","best":true}],"debrief":"You can change a moment; including is brave.","relearn":"One voice for 'everyone plays' can shift a group.","persona":"Faizan","source":"bystander"},
  {"id":"ff-030","cat":"dilemmas","type":"branch","hook":"A friend dares you to take chocolate from a shop without paying.","options":[{"text":"Do it so they don't call you scared","consequence":"You could get caught, and feel bad after.","outcome":"risky"},{"text":"Say \"no thanks, that's stealing\"","consequence":"A real friend backs off; a frenemy pushes harder.","outcome":"assertive","best":true}],"debrief":"A dare doesn't cancel right and wrong.","relearn":"Real friends don't make you choose them over right.","persona":"Reyansh","source":"peer pressure"},
  {"id":"ff-031","cat":"dilemmas","type":"branch","hook":"Two friends have fallen out and each wants you to pick a side.","options":[{"text":"Pick one, drop the other","consequence":"Someone loses two friends.","outcome":"escalates"},{"text":"Stay kind to both, don't carry messages","consequence":"You keep both friendships, dodge the storm.","outcome":"wise","best":true},{"text":"Help them talk it out when ready","consequence":"They cool down.","outcome":"peacemaker","best":true}],"debrief":"More than one good move works.","relearn":"Care for two friends without taking sides.","persona":"Ananya","source":"loyalty"},
  {"id":"ff-032","cat":"dilemmas","type":"branch","hook":"Your best friend wants to copy your homework.","options":[{"text":"Let them copy to avoid upset","consequence":"It doesn't help them learn, and risks trouble.","outcome":"short-term"},{"text":"Help them understand it instead","consequence":"They actually learn; better help.","outcome":"caring","best":true},{"text":"Say no and feel bad","consequence":"No is okay; helping is better.","outcome":"okay"}],"debrief":"The kindest help isn't always what's asked.","relearn":"Helping a friend learn beats letting them copy.","persona":"any","source":"integrity"},
  {"id":"ff-033","cat":"dilemmas","type":"branch","hook":"A classmate says \"that game's for girls\" when you reach for it.","options":[{"text":"Put it down so you're not teased","consequence":"You miss out, and the myth wins.","outcome":"gives-in"},{"text":"Say \"games are for everyone\" and play","consequence":"Some pause, some join; the myth loses power.","outcome":"comeback","best":true}],"debrief":"A calm comeback can flip a playground rule.","relearn":"Toys and games are for everyone; a good comeback travels fast.","persona":"Reyansh","source":"gender norms / peers"},
  {"id":"ff-034","cat":"dilemmas","type":"branch","hook":"Your friend is being teased and looks at you for help.","options":[{"text":"Look away so it doesn't turn on you","consequence":"Your friend feels alone.","outcome":"bystander"},{"text":"Stand next to them and say \"leave them alone\"","consequence":"The teaser often backs down.","outcome":"ally","best":true},{"text":"Get a trusted adult","consequence":"Help arrives; that's brave too.","outcome":"ally","best":true}],"debrief":"Standing beside a friend or fetching help both count.","relearn":"A bystander who steps in can stop it.","persona":"Faizan","source":"bystander"},
  {"id":"ff-035","cat":"dilemmas","type":"branch","hook":"A new friend wants you to stop seeing your old friend.","options":[{"text":"Drop your old friend to keep the new one","consequence":"You lose a real friend to please a controlling one.","outcome":"control"},{"text":"Say \"I can have both of you\"","consequence":"A good new friend is fine with that; a controlling one isn't.","outcome":"assertive","best":true}],"debrief":"A friend who makes you give up other friends is a red flag.","relearn":"You're allowed more than one friend.","persona":"any","source":"control"},
  {"id":"ff-036","cat":"dilemmas","type":"branch","hook":"You promised to keep a friend's secret, but they're being hurt at home.","options":[{"text":"Keep the secret because you promised","consequence":"Your friend stays in danger and alone.","outcome":"risky"},{"text":"Tell a trusted adult so your friend gets help","consequence":"The caring thing; some secrets are too big to keep.","outcome":"caring","best":true}],"debrief":"A promise doesn't hold when a friend's safety is at stake.","relearn":"If a friend is being hurt, tell a trusted adult.","persona":"any","source":"safeguarding (links g08)"},
  {"id":"ff-037","cat":"dilemmas","type":"branch","hook":"Everyone's laughing at a mean joke about a kid, and it IS funny.","options":[{"text":"Laugh along","consequence":"The kid feels worse; the group meaner.","outcome":"bystander"},{"text":"Stay quiet and change the subject","consequence":"You take the air out, no fight.","outcome":"okay","best":true},{"text":"Say \"that's enough, it's not nice\"","consequence":"Brave; others often agree.","outcome":"ally","best":true}],"debrief":"A joke can be funny and unkind; don't feed it.","relearn":"You needn't laugh at what hurts someone.","persona":"Ananya","source":"empathy"},
  {"id":"ff-038","cat":"dilemmas","type":"branch","hook":"Your friend keeps cancelling on you but always plays with others.","options":[{"text":"Keep waiting and hoping","consequence":"You feel let down again and again.","outcome":"stuck"},{"text":"Tell them how it feels, and also make other friends","consequence":"They may step up, and either way your circle grows.","outcome":"wise","best":true}],"debrief":"You can speak up AND widen your circle; you're not stuck.","relearn":"If someone keeps letting you down, it's fine to widen your circle.","persona":"any","source":"friendship-quality"},
  {"id":"ff-039","cat":"dilemmas","type":"branch","hook":"A popular kid offers to be your friend if you ignore your current best friend.","options":[{"text":"Take the offer","consequence":"You trade a real friend for a deal that can be cancelled anytime.","outcome":"control"},{"text":"Say no thanks","consequence":"You keep a real friend; worth more than status.","outcome":"wise","best":true}],"debrief":"Friendship offered as a deal with conditions isn't the real thing.","relearn":"A real friend doesn't come with a price tag of dropping others.","persona":"Reyansh","source":"status / loyalty"},
  {"id":"ff-040","cat":"dilemmas","type":"branch","hook":"You did something that hurt your friend's feelings, by accident.","options":[{"text":"Pretend you didn't notice","consequence":"The hurt sits there and grows.","outcome":"avoids"},{"text":"Say sorry and ask how to make it right","consequence":"They feel respected; the friendship gets stronger.","outcome":"repair","best":true}],"debrief":"Owning a mistake is one of the strongest friend moves there is.","relearn":"A real friend says sorry and tries to make it right.","persona":"any","source":"repair / accountability"},
  {"id":"ff-041","cat":"dilemmas","type":"reflect","hook":"Lensy: which dilemma felt most like your real life?","prompt":"Pick one to remember.","options":["Being left out","Being dared","Picking sides","Standing up for someone"],"affirm":"Noticing the ones that feel real means you'll spot them faster next time.","relearn":"Rehearsing choices now makes the real moment easier.","persona":"any","source":"transfer / metacognition"},
  {"id":"ff-073","cat":"dilemmas","type":"branch","hook":"Your friend wants you to gang up online against another kid.","options":[{"text":"Join in so your friend's happy","consequence":"It hurts someone and can spread fast.","outcome":"risky"},{"text":"Say \"I'm not doing that\" and tell a trusted adult if it continues","consequence":"You protect someone and keep your own kindness.","outcome":"assertive","best":true}],"debrief":"Ganging up online is bullying; a real friend won't ask you to.","relearn":"You can refuse to pile on, online or off.","persona":"Reyansh","source":"cyberbullying"},
  {"id":"ff-076","cat":"dilemmas","type":"branch","hook":"A friend tells you a secret, then you hear them lie about you.","options":[{"text":"Lie about them right back","consequence":"Now you're both frenemies; it spirals.","outcome":"escalates"},{"text":"Tell them what you heard and how it felt","consequence":"You give the friendship an honest chance.","outcome":"honest","best":true}],"debrief":"Meeting unkindness with honesty, not revenge, keeps you the good one.","relearn":"Answering unkindness with honesty beats revenge.","persona":"Ananya","source":"repair"},
  {"id":"ff-081","cat":"dilemmas","type":"branch","hook":"Capstone choice: a kid no one likes asks to be your friend.","options":[{"text":"Say no to protect your image","consequence":"You play it safe and miss a possible good friend.","outcome":"status"},{"text":"Give them a real chance","consequence":"You judge by how they treat you, not by gossip.","outcome":"openhearted","best":true}],"debrief":"Judge a possible friend by how they treat you, not by what others say.","relearn":"Everyone deserves a fair chance; you decide by how they treat you.","persona":"Faizan","source":"inclusion / values"},

  // — Stand up & speak —
  {"id":"ff-042","cat":"stand-up","type":"role-play","hook":"A friend keeps teasing you and won't stop.","setup":"Say the assertive line (calm, clear).","yourLine":[{"text":"\"Stop, I don't like that.\"","best":true},{"text":"Laugh and pretend it's fine"},{"text":"Tease them back harder"}],"relearn":"A calm, clear \"stop, I don't like that\" is strong, not rude.","persona":"Faizan","source":"assertiveness"},
  {"id":"ff-043","cat":"stand-up","type":"role-play","hook":"Someone says \"pink is a girl colour\" about your bag.","setup":"Reyansh wants a line for school tomorrow. Pick yours.","yourLine":[{"text":"\"Colours are for everyone.\"","best":true},{"text":"Hide the bag"},{"text":"\"No it's not!\" (just louder)"}],"relearn":"\"Colours are for everyone\" is a comeback you can actually use.","persona":"Reyansh","source":"gender norms / comebacks"},
  {"id":"ff-044","cat":"stand-up","type":"role-play","hook":"Your friend is being left out of the game.","setup":"Be the ally. What do you say to the group?","yourLine":[{"text":"\"Let's all play, it's more fun.\"","best":true},{"text":"Nothing"},{"text":"\"You're so mean!\" (and start a fight)"}],"relearn":"\"Let's all play\" includes your friend without starting a war.","persona":"Faizan","source":"bystander"},
  {"id":"ff-045","cat":"stand-up","type":"role-play","hook":"A kid is being dared to do something unsafe by the group.","setup":"Say something that helps them say no.","yourLine":[{"text":"\"You don't have to. Come on, let's go.\"","best":true},{"text":"\"Do it, do it!\""},{"text":"Watch silently"}],"relearn":"Giving a friend an exit (\"come on, let's go\") helps them say no.","persona":"any","source":"peer pressure / ally"},
  {"id":"ff-046","cat":"stand-up","type":"role-play","hook":"Someone spread a rumour about your friend.","setup":"What do you say when others repeat it?","yourLine":[{"text":"\"I don't think that's true, and it's not kind.\"","best":true},{"text":"Repeat it too"},{"text":"Say nothing and feel bad"}],"relearn":"Refusing to pass on a rumour helps it die out.","persona":"Ananya","source":"rumours / bystander"},
  {"id":"ff-047","cat":"stand-up","type":"branch","hook":"You said your assertive line, and the teasing didn't stop.","options":[{"text":"Give up and put up with it","consequence":"It keeps going; you feel worse.","outcome":"stuck"},{"text":"Walk away and tell a trusted adult","consequence":"Grown-ups can help when your words aren't enough.","outcome":"help","best":true}],"debrief":"Speaking up is step one; getting help is the brave step two.","relearn":"If standing up doesn't work, telling a trusted adult is the next move, not a failure.","persona":"Faizan","source":"escalation / help-seeking"},
  {"id":"ff-048","cat":"stand-up","type":"role-play","hook":"A friend made a mean joke about someone's family.","setup":"Say something, kindly but clear.","yourLine":[{"text":"\"That's not okay, that's their family.\"","best":true},{"text":"Laugh"},{"text":"Make a meaner joke back"}],"relearn":"You can call out a mean joke without being mean yourself.","persona":"Ananya","source":"values / assertiveness"},
  {"id":"ff-049","cat":"stand-up","type":"strike-rewrite","hook":"\"Standing up for someone is none of my business.\"","myth":{"un":"If it's not happening to me, it's none of my business.","re":"A bystander who speaks up can stop it; silence lets it grow.","why":"Friends look out for each other, and for those with no one."},"relearn":"Speaking up for someone else is exactly a friend's business.","persona":"any","source":"bystander research"},
  {"id":"ff-050","cat":"stand-up","type":"role-play","hook":"You want to check on a kid who was just teased.","setup":"What do you say to them after?","yourLine":[{"text":"\"You okay? That wasn't fair to you.\"","best":true},{"text":"Pretend nothing happened"},{"text":"\"Why do you let them do that?\""}],"relearn":"A quiet \"you okay?\" tells someone they're not alone.","persona":"Faizan","source":"support / empathy"},
  {"id":"ff-051","cat":"stand-up","type":"reflect","hook":"Lensy: which is hardest for you, saying stop, or backing up a friend?","prompt":"Be honest with yourself.","options":["Saying stop for me","Backing up someone else","Both are hard","I'm getting braver"],"affirm":"Naming the hard one is how you practise it. Bravery grows with reps.","relearn":"Standing up is a skill; it gets easier each time you try.","persona":"any","source":"self-efficacy"},
  {"id":"ff-052","cat":"stand-up","type":"branch","hook":"You see bullying happening but you're scared to step in alone.","options":[{"text":"Do nothing because you're scared","consequence":"Understandable, but it continues.","outcome":"stuck"},{"text":"Get a friend or an adult to step in with you","consequence":"It's easier and safer with backup, and it works.","outcome":"help","best":true}],"debrief":"You don't have to be a lone hero; getting backup is smart and brave.","relearn":"When it's not safe to step in alone, bring a friend or an adult.","persona":"any","source":"bystander / safety"},
  {"id":"ff-074","cat":"stand-up","type":"role-play","hook":"A friend keeps interrupting and never lets you talk.","setup":"Say the calm boundary line.","yourLine":[{"text":"\"I'd like a turn to talk too.\"","best":true},{"text":"Stop talking altogether"},{"text":"Shout over them"}],"relearn":"\"I'd like a turn too\" claims your space without a fight.","persona":"Ananya","source":"assertiveness"},
  {"id":"ff-079","cat":"stand-up","type":"branch","hook":"You stood up for someone and now the group is annoyed at you.","options":[{"text":"Wish you'd stayed quiet","consequence":"Maybe easier, but someone needed you.","outcome":"doubt"},{"text":"Feel proud, and find friends who value kindness","consequence":"The right friends respect what you did.","outcome":"values","best":true}],"debrief":"Doing the kind thing isn't always popular; the right people will respect it.","relearn":"Standing up can cost you in the moment and still be worth it.","persona":"Ananya","source":"values / courage"},

  // — Make up after a fight —
  {"id":"ff-053","cat":"repair","type":"strike-rewrite","hook":"\"Real friends never fight.\"","myth":{"un":"If you ever argue, you're not really friends.","re":"All friends disagree sometimes; what matters is how you make up.","why":"Conflict is normal; repair is the skill."},"relearn":"Good friends can disagree and still be good friends.","persona":"Ananya","source":"conflict / repair"},
  {"id":"ff-054","cat":"repair","type":"build","hook":"You and a friend argued. Build the make-up steps in order.","prompt":"Put the repair steps in a good order.","pieces":["cool down","say how you felt","listen to their side","say sorry for your part","agree what to do next"],"mode":"sequence","key":["cool down","say how you felt","listen to their side","say sorry for your part","agree what to do next"],"relearn":"Cool down, share, listen, say sorry, move on, that's how friends repair.","persona":"any","source":"conflict resolution"},
  {"id":"ff-055","cat":"repair","type":"role-play","hook":"You want to make up after a fight.","setup":"Pick the 'I' line that opens repair.","yourLine":[{"text":"\"I felt left out when that happened.\"","best":true},{"text":"\"You always ruin everything.\""},{"text":"Say nothing and stay cross"}],"relearn":"Starting with \"I felt...\" opens a door; \"you always...\" slams it.","persona":"Ananya","source":"I-statements"},
  {"id":"ff-056","cat":"repair","type":"branch","hook":"Your friend says sorry, but you're still a bit hurt.","options":[{"text":"Say \"it's fine\" but stay cold","consequence":"The hurt hides and lingers.","outcome":"avoids"},{"text":"Say \"thanks, I'm still a little sad, can we talk?\"","consequence":"Honest and kind; the friendship heals properly.","outcome":"repair","best":true}],"debrief":"You can accept a sorry and still be honest about your feelings.","relearn":"Forgiving doesn't mean hiding how you feel.","persona":"any","source":"repair / honesty"},
  {"id":"ff-057","cat":"repair","type":"sort","hook":"Repair move, or makes it worse?","items":[{"id":"a","text":"Listen to their side"},{"id":"b","text":"Bring up every old fight"},{"id":"c","text":"Say sorry for your part"},{"id":"d","text":"Give the silent treatment"},{"id":"e","text":"Find a fair fix together"}],"bins":[{"id":"repair","label":"Repair"},{"id":"worse","label":"Makes it worse"}],"key":{"a":"repair","b":"worse","c":"repair","d":"worse","e":"repair"},"relearn":"Listening, owning your part and finding a fair fix repair; scorekeeping and silence don't.","persona":"any","source":"conflict resolution"},
  {"id":"ff-058","cat":"repair","type":"branch","hook":"You apologised but your friend isn't ready to make up yet.","options":[{"text":"Demand they forgive you now","consequence":"Pushing makes them pull away.","outcome":"pushy"},{"text":"Give them a little time and stay kind","consequence":"Space plus kindness often brings them back.","outcome":"patient","best":true}],"debrief":"Repair sometimes needs time; you can't force a friend to be ready.","relearn":"After a real sorry, giving a friend some time is okay.","persona":"any","source":"repair / patience"},
  {"id":"ff-059","cat":"repair","type":"strike-rewrite","hook":"\"Saying sorry first means you lost.\"","myth":{"un":"Whoever says sorry first is the loser.","re":"Saying sorry first is a sign of strength, not defeat.","why":"Repair isn't a contest; it's care."},"relearn":"Going first to make up is brave, not weak.","persona":"Reyansh","source":"repair / values"},
  {"id":"ff-060","cat":"repair","type":"role-play","hook":"A friend is upset with you and you don't fully understand why.","setup":"What do you ask?","yourLine":[{"text":"\"Can you help me understand what upset you?\"","best":true},{"text":"\"You're overreacting.\""},{"text":"Walk off"}],"relearn":"Asking to understand beats guessing or dismissing.","persona":"Ananya","source":"perspective-taking"},
  {"id":"ff-061","cat":"repair","type":"branch","hook":"You and your friend want different games and start bickering.","options":[{"text":"Insist on your game","consequence":"One of you sulks; the fun stops.","outcome":"stuck"},{"text":"Take turns, your game then theirs","consequence":"You both get a turn and keep playing.","outcome":"fair","best":true}],"debrief":"Most small friend-fights melt with a fair turn-taking fix.","relearn":"Taking turns settles a lot of friendly disagreements.","persona":"any","source":"compromise"},
  {"id":"ff-062","cat":"repair","type":"reflect","hook":"Lensy: think of a time you made up with someone.","prompt":"What helped most?","options":["Saying sorry","Being listened to","A bit of time","A fair fix"],"affirm":"Whatever worked, you already have a repair tool. Use it again.","relearn":"You've repaired a friendship before; you can do it again.","persona":"any","source":"reflection"},
  {"id":"ff-075","cat":"repair","type":"branch","hook":"You realise YOU were the one who was unkind to a friend.","options":[{"text":"Hope they forget about it","consequence":"They don't, and trust frays.","outcome":"avoids"},{"text":"Go to them, own it, and say sorry","consequence":"They feel respected; you grow as a friend.","outcome":"repair","best":true}],"debrief":"Owning your own unkindness is the bravest repair of all.","relearn":"When you've been the frenemy, owning it and saying sorry makes it right.","persona":"any","source":"accountability"},

  // — Being a good friend —
  {"id":"ff-063","cat":"good-friend","type":"reflect","hook":"Lensy: honest check, are you sometimes the frenemy?","prompt":"We all slip. Pick one to watch.","options":["Teasing that goes too far","Leaving someone out","Sulking when a friend wins","Being only-sometimes kind"],"affirm":"Noticing your own slip is exactly what a good friend does. No shame, just a nudge.","relearn":"Being a good friend includes checking your own moves, kindly.","persona":"any","source":"self-awareness"},
  {"id":"ff-064","cat":"good-friend","type":"branch","hook":"One kid is always unkind to you, no matter what you try.","options":[{"text":"Keep chasing their approval","consequence":"You keep getting hurt.","outcome":"stuck"},{"text":"Step back and spend time with kinder friends","consequence":"You feel lighter; better friends have room now.","outcome":"wise","best":true}],"debrief":"Stepping back from someone always unkind isn't giving up; it's self-respect.","relearn":"You're allowed to step back from a friendship that keeps hurting you.","persona":"any","source":"boundaries / wellbeing"},
  {"id":"ff-065","cat":"good-friend","type":"branch","hook":"You feel lonely because your one friend moved away.","options":[{"text":"Decide you'll never find another friend","consequence":"That feels heavy and isn't true.","outcome":"stuck"},{"text":"Try one small step, sit with someone new, join a game","consequence":"New friendships start with small, brave steps.","outcome":"hopeful","best":true}],"debrief":"Friendships can be made again; it starts with one small move.","relearn":"You can always make new friends, one small step at a time.","persona":"any","source":"loneliness / agency"},
  {"id":"ff-066","cat":"good-friend","type":"strike-rewrite","hook":"\"Having lots of friends is the only thing that matters.\"","myth":{"un":"You need a big crowd of friends to be okay.","re":"A few kind, steady friends matter more than a big crowd.","why":"Quality of friendship beats quantity for how good you feel."},"relearn":"Even one or two kind friends is real richness.","persona":"any","source":"friendship-quality research"},
  {"id":"ff-067","cat":"good-friend","type":"sort","hook":"When a friendship is hard, what helps?","items":[{"id":"a","text":"Talk it out"},{"id":"b","text":"Bottle it up"},{"id":"c","text":"Ask a trusted adult"},{"id":"d","text":"Spread it as gossip"},{"id":"e","text":"Widen your circle"}],"bins":[{"id":"helps","label":"Helps"},{"id":"hurts","label":"Hurts"}],"key":{"a":"helps","b":"hurts","c":"helps","d":"hurts","e":"helps"},"relearn":"Talking it out, asking for help and widening your circle all help; bottling and gossip don't.","persona":"any","source":"coping"},
  {"id":"ff-068","cat":"good-friend","type":"branch","hook":"A friend is being bullied and asks you not to tell anyone.","options":[{"text":"Stay silent because they asked","consequence":"The bullying continues and they suffer alone.","outcome":"risky"},{"text":"Tell a trusted adult so it can stop","consequence":"Caring; bullying needs grown-up help.","outcome":"caring","best":true}],"debrief":"Helping a bullied friend means getting an adult, even if they're scared.","relearn":"For bullying, telling a trusted adult is how you truly help.","persona":"Faizan","source":"bullying"},
  {"id":"ff-069","cat":"good-friend","type":"role-play","hook":"You want to invite a lonely classmate into your group.","setup":"What's a warm way to say it?","yourLine":[{"text":"\"We're playing tag, want to join us?\"","best":true},{"text":"\"You can come if you want, I guess.\""},{"text":"Wait for them to ask first"}],"relearn":"A warm, specific invite is the kindest door to open.","persona":"any","source":"inclusion"},
  {"id":"ff-070","cat":"good-friend","type":"reflect","hook":"Lensy: what's one friend-skill you got better at today?","prompt":"Pick your win.","options":["Spotting a flag","Saying my line","Including someone","Making up after a fight"],"affirm":"That's a real skill you'll use for life, not just a sticker.","relearn":"Good friendship is a set of skills you keep growing.","persona":"any","source":"mastery"},
  {"id":"ff-071","cat":"good-friend","type":"strike-rewrite","hook":"\"If a friendship ends, you failed.\"","myth":{"un":"A friendship ending means you did something wrong.","re":"Some friendships fade or end, and that's a normal part of life.","why":"People grow and change; an ending isn't always a failure."},"relearn":"Friendships can change or end without anyone being bad.","persona":"any","source":"social development"},
  {"id":"ff-077","cat":"good-friend","type":"reflect","hook":"Lensy: who are your steady-kind friends?","prompt":"Picture one or two.","options":["I have one","I have a few","I'm still finding them","My family counts too"],"affirm":"Even one steady-kind friend is something to treasure and tend.","relearn":"Knowing who your steady friends are helps you invest in them.","persona":"any","source":"friendship-quality"},
  {"id":"ff-080","cat":"good-friend","type":"build","hook":"Build your friend-or-frenemy detector to take with you.","prompt":"Pick the green-flag signals for your detector.","pieces":["happy for me","includes me","honest and kind","uses 'or else'","leaves me out on purpose","keeps my secrets"],"mode":"assemble","key":["happy for me","includes me","honest and kind","keeps my secrets"],"relearn":"Green flags: glad for you, includes you, honest-kind, keeps trust. Hold out for those.","persona":"any","source":"friendship-quality"},
  {"id":"ff-082","cat":"good-friend","type":"reflect","hook":"Lensy: friend or frenemy, you can spot it now. What will you carry?","prompt":"Pick your motto.","options":["Real friends are glad for me","I can name a flag","I can stand up and make up","I deserve steady-kind friends"],"affirm":"Carry that. You're going to be a wonderful friend, and choose wonderful ones.","relearn":"You can spot real friends, be one, and hold out for steady-kind people.","persona":"any","source":"consolidation"},
];

export const FRIEND_FRENEMY: V2GameConfig = {
  gameId: "friend-frenemy",
  title: "Friend or Frenemy?",
  greet: "Hey! Let's figure out friends together. 🤝 What makes a real friend — and how do you spot a frenemy?",
  scenarios: SCENARIOS,
  categories: [
  { id: "real-friend", emoji: "🌟", label: "Real friends" },
  { id: "frenemy-flags", emoji: "🚩", label: "Frenemy flags" },
  { id: "dilemmas", emoji: "🤔", label: "Friend dilemmas" },
  { id: "stand-up", emoji: "💪", label: "Stand up & speak" },
  { id: "repair", emoji: "🩹", label: "Make up after a fight" },
  { id: "good-friend", emoji: "🤝", label: "Being a good friend" },
  ],
  badge: {
    title: "Friend Detector! 🤝",
    blurb: "You can spot a real friend, name the frenemy flags, say the line, and make up after a fight — real friends are glad for you; unkindness is never your worth. 🤝💛",
  },
  helpLine: "If someone keeps being unkind, or you don't feel safe, tell a trusted grown-up, or call Childline, one-zero-nine-eight. Asking for help is brave, not tattling.",
  helpLabel: "Get help · Childline 1098",
  reassure: "If someone's unkind to you, it's not your fault — and telling a trusted grown-up is brave. 💛",
  reassureCats: ["frenemy-flags"],
  buildLabels: { assemble: "That's a real friend! 🌟", sequence: "That's how we make up! 🩹" },
};
