// Content for Green Light / Red Light (node g24, ages 12–15, Chapter 4) — NEW v2 build to GDD 24
// (mechanic-embodying), THE TEEN FLAGSHIP and the namesake swipe game (Thread B/D · relationships & consent).
// "Read the flags. Insist on real consent. Keep the green, lose the red." 84 researched, India-grounded
// scenarios across the what-is-consent → green-flags → red-flags → read-any → say-and-hear → when-wrong arc,
// each encoded as one of the shared v2 play actions — LED BY THE SIGNATURE **SWIPE** verb (×28: read a
// relationship cue and swipe it green-flag / red-flag), plus branch / strike-rewrite / role-play / sort /
// reflect / spot. Teaches: green/red flag reading (One Love) and the **FRIES consent model** (Free,
// Reversible, Informed, Enthusiastic, Specific) across friendships, family and romantic relationships.
// Safeguarding: a crossed line is NEVER your fault; serious red flags / coercion route to a trusted adult or
// **Childline 1098 / 112**; leaving what harms you is strength, not failure. School-comfort, non-explicit.
// GATED at the path layer (age band). Builds on g15 (Boundary Bot); prereq g23. Rendered by the shared engine
// (components/games/v2-engine.tsx; the swipe mechanic was ADDED to the engine for this flagship). gameId
// "glrl" (the engine-host registry id; the GDD/library aspirational id is "green-light-red-light"). DO NOT RENAME.

import type { Scenario, V2GameConfig } from "./v2-schema";

const SCENARIOS: Scenario[] = [
  // — What consent is (FRIES) —
  {"id":"gl-001","cat":"what-is-consent","type":"strike-rewrite","hook":"\"If someone doesn't say no, that means yes.\"","myth":{"un":"No 'no' means yes.","re":"Only a free, clear yes is a yes; silence or freezing isn't consent.","why":"Consent is an enthusiastic yes, not the absence of a no."},"relearn":"Only a clear, willing yes is consent; silence isn't a yes.","persona":"any","source":"FRIES / enthusiastic"},
  {"id":"gl-002","cat":"what-is-consent","type":"strike-rewrite","hook":"\"Once you say yes, you can't change your mind.\"","myth":{"un":"A yes can't be taken back.","re":"Consent is reversible, you can change your mind at any time.","why":"You always keep the right to stop."},"relearn":"Consent is reversible; you can change your mind anytime.","persona":"any","source":"FRIES / reversible"},
  {"id":"gl-003","cat":"what-is-consent","type":"strike-rewrite","hook":"\"Saying yes to one thing means yes to everything.\"","myth":{"un":"Yes to one thing is yes to all things.","re":"Consent is specific, agreeing to one thing isn't agreeing to more.","why":"Each step needs its own yes."},"relearn":"Consent is specific; one yes isn't a yes to everything.","persona":"any","source":"FRIES / specific"},
  {"id":"gl-004","cat":"what-is-consent","type":"strike-rewrite","hook":"\"A yes given under pressure still counts.\"","myth":{"un":"A 'yes' counts even if it was pressured or guilt-tripped.","re":"Consent must be freely given; pressure or guilt makes it not real consent.","why":"A yes squeezed out by pressure isn't a free yes."},"relearn":"Consent must be free; pressured or guilted 'yes' isn't real consent.","persona":"Riya","source":"FRIES / freely given"},
  {"id":"gl-005","cat":"what-is-consent","type":"strike-rewrite","hook":"\"You don't need to know what you're agreeing to.\"","myth":{"un":"You can consent without really knowing what to.","re":"Consent must be informed, you know what you're saying yes to.","why":"You can't truly agree to something hidden."},"relearn":"Consent is informed; you know what you're agreeing to.","persona":"any","source":"FRIES / informed"},
  {"id":"gl-006","cat":"what-is-consent","type":"strike-rewrite","hook":"\"Consent only matters for romantic or grown-up stuff.\"","myth":{"un":"Consent only applies to romantic situations.","re":"Consent applies to any touch, sharing or boundary, with anyone.","why":"A hug, a photo, your stuff, all need a yes."},"relearn":"Consent applies to all touch and sharing, not only romance.","persona":"any","source":"consent / everyday"},
  {"id":"gl-007","cat":"what-is-consent","type":"sort","hook":"Sort: real consent, or not real consent?","items":[{"id":"a","text":"A clear, willing yes"},{"id":"b","text":"Silence or freezing"},{"id":"c","text":"An enthusiastic 'sure!'"},{"id":"d","text":"A yes after being nagged"}],"bins":[{"id":"real","label":"Real consent"},{"id":"not","label":"Not consent"}],"key":{"a":"real","b":"not","c":"real","d":"not"},"relearn":"Real consent is a free, willing yes, not silence or a nagged 'yes'.","persona":"any","source":"FRIES"},
  {"id":"gl-008","cat":"what-is-consent","type":"sort","hook":"Sort each to its FRIES letter.","items":[{"id":"a","text":"You can change your mind"},{"id":"b","text":"No pressure or guilt"},{"id":"c","text":"Yes to one isn't yes to all"},{"id":"d","text":"An eager, real yes"}],"bins":[{"id":"rev","label":"Reversible / Free"},{"id":"spec","label":"Specific / Enthusiastic"}],"key":{"a":"rev","b":"rev","c":"spec","d":"spec"},"relearn":"FRIES: free, reversible, informed, enthusiastic, specific.","persona":"any","source":"FRIES"},
  {"id":"gl-009","cat":"what-is-consent","type":"sort","hook":"Sort: respects consent, or ignores it?","items":[{"id":"a","text":"Asking before a hug"},{"id":"b","text":"Sharing a photo without asking"},{"id":"c","text":"Checking 'is this okay?'"},{"id":"d","text":"Pushing past a 'not sure'"}],"bins":[{"id":"respects","label":"Respects consent"},{"id":"ignores","label":"Ignores it"}],"key":{"a":"respects","b":"ignores","c":"respects","d":"ignores"},"relearn":"Asking and checking respect consent; assuming or pushing ignore it.","persona":"any","source":"consent in practice"},
  {"id":"gl-010","cat":"what-is-consent","type":"branch","hook":"You want to hug a friend who seems a bit down.","options":[{"text":"Ask first: 'do you want a hug?'","consequence":"They get to choose; the care lands right.","outcome":"respectful","best":true},{"text":"Just grab them in a hug","consequence":"Even kind touch needs a yes; ask first."}],"debrief":"Even well-meant touch is better with a quick consent check.","relearn":"Ask before touching, even with kind intentions.","persona":"any","source":"consent / everyday"},
  {"id":"gl-011","cat":"what-is-consent","type":"branch","hook":"Someone says yes but looks unsure and uncomfortable.","options":[{"text":"Pause and check: 'we don't have to, only if you want'","consequence":"You honour the real feeling under the word.","outcome":"attuned","best":true},{"text":"Take the 'yes' and carry on","consequence":"An uneasy 'yes' isn't enthusiastic; check in."}],"debrief":"A reluctant 'yes' isn't real consent; read the whole person.","relearn":"If a yes seems unsure, pause, real consent is willing.","persona":"any","source":"FRIES / enthusiastic"},
  {"id":"gl-012","cat":"what-is-consent","type":"branch","hook":"You changed your mind about something you'd agreed to.","options":[{"text":"Say so: 'actually, I've changed my mind'","consequence":"You exercise your right to stop.","outcome":"empowered","best":true},{"text":"Feel you have to go through with it","consequence":"You can always change your mind; consent is reversible."}],"debrief":"Changing your mind is always allowed, that's what reversible means.","relearn":"You can change your mind anytime; you're never locked in.","persona":"Riya","source":"FRIES / reversible"},
  {"id":"gl-013","cat":"what-is-consent","type":"reflect","hook":"Lensy: consent is really just 'check it's a yes, every time'. Simple enough?","prompt":"What do you think?","options":["Yes","Makes sense","Check every time"],"affirm":"Consent is a habit of checking, not a one-time box.","relearn":"Consent is an ongoing check that it's a willing yes.","persona":"any","source":"FRIES"},
  {"id":"gl-014","cat":"what-is-consent","type":"reflect","hook":"Lensy: your yes and your no both matter, completely. Feel that?","prompt":"What do you think?","options":["Yes","Both count","My call"],"affirm":"Your yes and your no are equally yours to give.","relearn":"Both your yes and your no fully count and are yours.","persona":"any","source":"autonomy"},
  // — Green flags —
  {"id":"gl-015","cat":"flags","type":"swipe","hook":"Swipe: green flag or red?","cue":"A friend is genuinely happy when good things happen to you","left":"Red flag","right":"Green flag","answer":"right","relearn":"Being happy for you is a green flag of a healthy bond.","persona":"any","source":"One Love / healthy"},
  {"id":"gl-016","cat":"flags","type":"swipe","hook":"Swipe: green flag or red?","cue":"They respect your 'no' without sulking or punishing you","left":"Red flag","right":"Green flag","answer":"right","relearn":"Respecting your 'no' is a core green flag.","persona":"any","source":"One Love / respect"},
  {"id":"gl-017","cat":"flags","type":"swipe","hook":"Swipe: green flag or red?","cue":"You can be honest with them without fear of how they'll react","left":"Red flag","right":"Green flag","answer":"right","relearn":"Safe honesty is a green flag.","persona":"any","source":"One Love / honesty"},
  {"id":"gl-018","cat":"flags","type":"swipe","hook":"Swipe: green flag or red?","cue":"They're happy for you to have other friends and your own hobbies","left":"Red flag","right":"Green flag","answer":"right","relearn":"Supporting your independence is a green flag.","persona":"any","source":"One Love / independence"},
  {"id":"gl-019","cat":"flags","type":"swipe","hook":"Swipe: green flag or red?","cue":"You both share decisions and hear each other out","left":"Red flag","right":"Green flag","answer":"right","relearn":"Equality and being heard are green flags.","persona":"any","source":"One Love / equality"},
  {"id":"gl-020","cat":"flags","type":"swipe","hook":"Swipe: green flag or red?","cue":"They own their mistakes and say a real sorry","left":"Red flag","right":"Green flag","answer":"right","relearn":"Taking accountability is a green flag.","persona":"any","source":"One Love / accountability"},
  {"id":"gl-021","cat":"flags","type":"swipe","hook":"Swipe: green flag or red?","cue":"The relationship moves at a pace that feels comfortable to you both","left":"Red flag","right":"Green flag","answer":"right","relearn":"A comfortable, mutual pace is a green flag.","persona":"any","source":"One Love / comfortable pace"},
  {"id":"gl-022","cat":"flags","type":"swipe","hook":"Swipe: green flag or red?","cue":"They cheer your wins instead of competing with you","left":"Red flag","right":"Green flag","answer":"right","relearn":"Cheering you on, not competing, is a green flag.","persona":"any","source":"One Love / support"},
  {"id":"gl-023","cat":"flags","type":"swipe","hook":"Swipe: green flag or red?","cue":"You feel calmer and more yourself around them","left":"Red flag","right":"Green flag","answer":"right","relearn":"Feeling safe and yourself is a green flag.","persona":"any","source":"One Love / healthy"},
  {"id":"gl-024","cat":"flags","type":"swipe","hook":"Swipe: green flag or red?","cue":"They keep your secrets and have your back","left":"Red flag","right":"Green flag","answer":"right","relearn":"Trust and loyalty are green flags.","persona":"any","source":"One Love / trust"},
  {"id":"gl-025","cat":"flags","type":"sort","hook":"Sort: a green flag, or just a nice surface?","items":[{"id":"a","text":"Consistent respect over time"},{"id":"b","text":"Big gifts but no respect"},{"id":"c","text":"Listening when you disagree"},{"id":"d","text":"Charming in public, cold in private"}],"bins":[{"id":"green","label":"Real green flag"},{"id":"surface","label":"Just surface"}],"key":{"a":"green","b":"surface","c":"green","d":"surface"},"relearn":"Green flags are consistent respect, not just charm or gifts.","persona":"any","source":"One Love"},
  {"id":"gl-026","cat":"flags","type":"sort","hook":"Sort: which green flags show up in ALL good relationships?","items":[{"id":"a","text":"Respect"},{"id":"b","text":"Trust"},{"id":"c","text":"Control"},{"id":"d","text":"Kindness"}],"bins":[{"id":"green","label":"Green flag"},{"id":"not","label":"Not a green flag"}],"key":{"a":"green","b":"green","c":"not","d":"green"},"relearn":"Respect, trust and kindness are green flags in friendships, family and romance alike.","persona":"any","source":"One Love"},
  {"id":"gl-027","cat":"flags","type":"reflect","hook":"Lensy: name a green flag someone in your life shows you.","prompt":"Think of one.","options":["They respect my no","They're happy for me","They're honest with me","They give me space"],"affirm":"Notice and value the green flags, they're worth keeping close.","relearn":"Noticing green flags helps you value healthy relationships.","persona":"any","source":"reflection"},
  {"id":"gl-028","cat":"flags","type":"reflect","hook":"Lensy: are YOU a green flag for others? Worth aiming for?","prompt":"What do you think?","options":["I try to be","I want to be","Good goal"],"affirm":"Being someone's green flag is one of the kindest things you can be.","relearn":"You can choose to be a green flag in others' lives.","persona":"any","source":"self / values"},
  // — Red flags —
  {"id":"gl-029","cat":"flags","type":"swipe","hook":"Swipe: green flag or red?","cue":"They check your phone and want to know where you are all the time","left":"Red flag","right":"Green flag","answer":"left","relearn":"Monitoring and control are red flags, not love.","persona":"Riya","source":"One Love / control"},
  {"id":"gl-030","cat":"flags","type":"swipe","hook":"Swipe: green flag or red?","cue":"They get angry when you spend time with other friends","left":"Red flag","right":"Green flag","answer":"left","relearn":"Trying to isolate you from others is a red flag.","persona":"any","source":"One Love / isolation"},
  {"id":"gl-031","cat":"flags","type":"swipe","hook":"Swipe: green flag or red?","cue":"They put you down, then say they were 'just joking'","left":"Red flag","right":"Green flag","answer":"left","relearn":"Belittling disguised as jokes is a red flag.","persona":"any","source":"One Love / belittling"},
  {"id":"gl-032","cat":"flags","type":"swipe","hook":"Swipe: green flag or red?","cue":"They guilt-trip you into things with 'if you loved me, you would'","left":"Red flag","right":"Green flag","answer":"left","relearn":"Guilt-tripping and pressure are red flags.","persona":"any","source":"One Love / manipulation"},
  {"id":"gl-033","cat":"flags","type":"swipe","hook":"Swipe: green flag or red?","cue":"Big mood swings, sweet one minute, scary the next","left":"Red flag","right":"Green flag","answer":"left","relearn":"A volatile rollercoaster is a red flag.","persona":"any","source":"One Love / volatility"},
  {"id":"gl-034","cat":"flags","type":"swipe","hook":"Swipe: green flag or red?","cue":"They blame you for everything that goes wrong","left":"Red flag","right":"Green flag","answer":"left","relearn":"Always blaming you is a red flag.","persona":"any","source":"One Love / blame"},
  {"id":"gl-035","cat":"flags","type":"swipe","hook":"Swipe: green flag or red?","cue":"They pressure you to share photos you're not comfortable sharing","left":"Red flag","right":"Green flag","answer":"left","relearn":"Pressuring you past your boundaries is a red flag.","persona":"Riya","source":"One Love / pressure (links g15)"},
  {"id":"gl-036","cat":"flags","type":"swipe","hook":"Swipe: green flag or red?","cue":"They come on super intense and fast, 'you're my whole world already'","left":"Red flag","right":"Green flag","answer":"left","relearn":"Rushing intensity can be a red flag, not romance.","persona":"any","source":"One Love / intensity"},
  {"id":"gl-037","cat":"flags","type":"swipe","hook":"Swipe: green flag or red?","cue":"They threaten to hurt themselves if you leave","left":"Red flag","right":"Green flag","answer":"left","relearn":"Threats to control you are a serious red flag, tell a trusted adult.","persona":"Counsellor","source":"One Love / coercion / safeguarding"},
  {"id":"gl-038","cat":"flags","type":"swipe","hook":"Swipe: green flag or red?","cue":"They ignore your 'no' and keep pushing","left":"Red flag","right":"Green flag","answer":"left","relearn":"Ignoring your 'no' is a serious red flag.","persona":"any","source":"One Love / consent"},
  {"id":"gl-039","cat":"flags","type":"strike-rewrite","hook":"\"Jealousy and control mean they really love you.\"","myth":{"un":"Jealousy and control are proof of love.","re":"Control isn't love; trust and freedom are.","why":"Love expands your world; control shrinks it."},"relearn":"Jealous control isn't love; it's a red flag.","persona":"Riya","source":"One Love / 'jealousy isn't love'"},
  {"id":"gl-040","cat":"flags","type":"strike-rewrite","hook":"\"If they get angry, you must have caused it.\"","myth":{"un":"Their anger or bad behaviour is your fault.","re":"People are responsible for their own behaviour, not you.","why":"You don't 'make' someone mistreat you."},"relearn":"You're not responsible for someone else's red-flag behaviour.","persona":"any","source":"no self-blame"},
  {"id":"gl-041","cat":"flags","type":"strike-rewrite","hook":"\"Red flags only matter in dating, not friends or family.\"","myth":{"un":"Red flags only count in romantic relationships.","re":"Control, belittling and manipulation are red flags in any relationship.","why":"Friends and family can show them too."},"relearn":"Red flags can appear in friendships and family, not just dating.","persona":"any","source":"all relationships"},
  {"id":"gl-042","cat":"flags","type":"sort","hook":"Sort: a red flag, or a normal disagreement?","items":[{"id":"a","text":"Controlling who you see"},{"id":"b","text":"Disagreeing but talking it out"},{"id":"c","text":"Constant put-downs"},{"id":"d","text":"Needing some space sometimes"}],"bins":[{"id":"red","label":"Red flag"},{"id":"normal","label":"Normal"}],"key":{"a":"red","b":"normal","c":"red","d":"normal"},"relearn":"Control and put-downs are red flags; disagreement and space are normal.","persona":"any","source":"One Love"},
  {"id":"gl-043","cat":"flags","type":"sort","hook":"Sort: a serious red flag (get help), or a 'talk about it' one?","items":[{"id":"a","text":"Threats or any violence"},{"id":"b","text":"Being a bit forgetful"},{"id":"c","text":"Pressuring or scaring you"},{"id":"d","text":"Liking different music"}],"bins":[{"id":"serious","label":"Serious, get help"},{"id":"minor","label":"Not a red flag"}],"key":{"a":"serious","b":"minor","c":"serious","d":"minor"},"relearn":"Threats, violence and fear are serious red flags, reach a trusted adult.","persona":"Counsellor","source":"safeguarding"},
  {"id":"gl-044","cat":"flags","type":"spot","hook":"Spot the red flags in this 'romantic' message.","scene":[{"id":"a","text":"\"Delete your other friends, you only need me\"","trick":true},{"id":"b","text":"\"Had a good day?\"","trick":false},{"id":"c","text":"\"Send a pic now or I'll be upset\"","trick":true}],"why":"Isolation and pressure are red flags hiding in 'romantic' words.","relearn":"Isolation and pressure can hide inside 'romantic'-sounding messages.","persona":"any","source":"One Love / spotting"},
  // — Read any relationship —
  {"id":"gl-045","cat":"read-any","type":"swipe","hook":"Friendship. Swipe: green flag or red?","cue":"A friend drops you the moment someone 'cooler' shows up","left":"Red flag","right":"Green flag","answer":"left","relearn":"A fair-weather friend who drops you is a red flag.","persona":"any","source":"friendship"},
  {"id":"gl-046","cat":"read-any","type":"swipe","hook":"Friendship. Swipe: green flag or red?","cue":"A friend gently tells you a hard truth because they care","left":"Red flag","right":"Green flag","answer":"right","relearn":"Honest care, even hard truths, is a green flag.","persona":"any","source":"friendship"},
  {"id":"gl-047","cat":"read-any","type":"swipe","hook":"Family. Swipe: green flag or red?","cue":"A relative respects your privacy as you grow up","left":"Red flag","right":"Green flag","answer":"right","relearn":"Respecting your growing privacy is a green flag, even in family.","persona":"any","source":"family"},
  {"id":"gl-048","cat":"read-any","type":"swipe","hook":"Family. Swipe: green flag or red?","cue":"An older cousin pressures you to keep an uncomfortable secret","left":"Red flag","right":"Green flag","answer":"left","relearn":"Pressure to keep an unsafe secret is a red flag, even from family.","persona":"Counsellor","source":"family / safeguarding"},
  {"id":"gl-049","cat":"read-any","type":"swipe","hook":"Crush. Swipe: green flag or red?","cue":"A crush respects it when you say you're not ready for something","left":"Red flag","right":"Green flag","answer":"right","relearn":"Respecting your pace is a green flag.","persona":"any","source":"romantic / consent"},
  {"id":"gl-050","cat":"read-any","type":"swipe","hook":"Crush. Swipe: green flag or red?","cue":"They sulk and threaten to leave when you say 'not yet'","left":"Red flag","right":"Green flag","answer":"left","relearn":"Sulking or threats over your 'no' are a red flag.","persona":"any","source":"romantic / pressure"},
  {"id":"gl-051","cat":"read-any","type":"swipe","hook":"Online. Swipe: green flag or red?","cue":"Someone you met online quickly asks for personal info and secrecy","left":"Red flag","right":"Green flag","answer":"left","relearn":"Fast secrecy and info-pushing online is a red flag.","persona":"any","source":"online safety (links g15)"},
  {"id":"gl-052","cat":"read-any","type":"swipe","hook":"Swipe: green flag or red?","cue":"They apologise, change, and treat you better over time","left":"Red flag","right":"Green flag","answer":"right","relearn":"Real change backed by action is a green flag.","persona":"any","source":"accountability"},
  {"id":"gl-053","cat":"read-any","type":"branch","hook":"You've spotted a few red flags in a friendship. What now?","options":[{"text":"Name what's bothering you and see if it changes","consequence":"You give it an honest chance with clear eyes.","outcome":"clear","best":true},{"text":"Ignore them and hope they vanish","consequence":"Naming the issue beats hoping red flags disappear."}],"debrief":"Spotting red flags is step one; addressing them is step two.","relearn":"When you spot red flags, name them rather than ignore them.","persona":"any","source":"action"},
  {"id":"gl-054","cat":"read-any","type":"branch","hook":"A relationship has many red flags and few green ones.","options":[{"text":"Lean on trusted people and consider stepping back","consequence":"You protect your wellbeing.","outcome":"self-respect","best":true},{"text":"Stay and accept the treatment","consequence":"Mostly-red relationships are worth stepping back from, with support."}],"debrief":"You deserve relationships that are mostly green, not mostly red.","relearn":"You can step back from a mostly-red relationship, with support.","persona":"Riya","source":"healthy choices"},
  {"id":"gl-055","cat":"read-any","type":"branch","hook":"A relationship is mostly green but you hit a rough patch.","options":[{"text":"Talk it through; healthy ones can repair","consequence":"You work through it and grow closer.","outcome":"repair","best":true},{"text":"Assume one fight ruins everything","consequence":"Healthy relationships can weather and repair rough patches."}],"debrief":"A rough patch in a healthy relationship can be repaired by talking.","relearn":"Healthy relationships can repair after a rough patch.","persona":"any","source":"repair"},
  {"id":"gl-056","cat":"read-any","type":"branch","hook":"You notice a red flag in your OWN behaviour toward someone.","options":[{"text":"Own it, apologise, and change","consequence":"You grow into a greener flag yourself.","outcome":"growth","best":true},{"text":"Decide it's fine because you mean well","consequence":"Good intentions don't excuse red-flag behaviour; own and change it."}],"debrief":"Reading flags includes honestly reading your own.","relearn":"You can spot and change your own red-flag behaviour.","persona":"Veer","source":"self-accountability"},
  {"id":"gl-057","cat":"read-any","type":"sort","hook":"Sort this run of cards: green flag or red?","items":[{"id":"a","text":"Respects your 'no'"},{"id":"b","text":"Tracks your every move"},{"id":"c","text":"Happy for your wins"},{"id":"d","text":"Puts you down 'as a joke'"}],"bins":[{"id":"green","label":"Green"},{"id":"red","label":"Red"}],"key":{"a":"green","b":"red","c":"green","d":"red"},"relearn":"Reading relationships is sorting the green from the red, fast and fairly.","persona":"any","source":"One Love"},
  {"id":"gl-058","cat":"read-any","type":"sort","hook":"Sort: which relationship is healthier overall?","items":[{"id":"a","text":"Mostly respect, trust, fun"},{"id":"b","text":"Mostly control and fear"},{"id":"c","text":"Honest and supportive"},{"id":"d","text":"Constant put-downs"}],"bins":[{"id":"healthy","label":"Healthier"},{"id":"unhealthy","label":"Unhealthy"}],"key":{"a":"healthy","b":"unhealthy","c":"healthy","d":"unhealthy"},"relearn":"Judge a relationship by its pattern of flags, not one moment.","persona":"any","source":"pattern reading"},
  {"id":"gl-059","cat":"read-any","type":"spot","hook":"Spot the green flags in this scene.","scene":[{"id":"a","text":"They ask before borrowing your things","trick":true},{"id":"b","text":"It's a rainy day","trick":false},{"id":"c","text":"They're glad you made a new friend","trick":true}],"why":"Asking first and being glad for you are green flags.","relearn":"Green flags include asking first and being glad for your other bonds.","persona":"any","source":"One Love"},
  // — Say it & hear it —
  {"id":"gl-060","cat":"say-and-hear","type":"role-play","hook":"You want to say no to something you're not comfortable with.","setup":"Say it clearly. Say:","yourLine":[{"text":"\"No, I don't want to, and that's final.\"","best":true},{"text":"\"Um, maybe, I guess, if you really want...\""}],"relearn":"A clear 'no' is a full sentence; you don't owe a long excuse.","persona":"Riya","source":"refusal (UNESCO 5.3)"},
  {"id":"gl-061","cat":"say-and-hear","type":"role-play","hook":"Someone says no to you. How do you respond?","setup":"Respect it warmly. Say:","yourLine":[{"text":"\"Totally okay, thanks for telling me.\"","best":true},{"text":"\"Come on, why not, just this once?\""}],"relearn":"Hearing a 'no' gracefully is as important as giving one.","persona":"Veer","source":"respecting refusal"},
  {"id":"gl-062","cat":"say-and-hear","type":"role-play","hook":"You want to check a friend is comfortable.","setup":"Ask openly. Say:","yourLine":[{"text":"\"Is this okay with you? We can stop anytime.\"","best":true},{"text":"Assume it's fine and keep going"}],"relearn":"Checking 'is this okay?' is how consent works in real life.","persona":"any","source":"checking in"},
  {"id":"gl-063","cat":"say-and-hear","type":"role-play","hook":"You're being pressured with 'everyone does this'.","setup":"Hold your line. Say:","yourLine":[{"text":"\"I don't care what everyone does, my answer is no.\"","best":true},{"text":"\"Fine, if everyone does...\""}],"relearn":"'Everyone does it' doesn't override your no.","persona":"any","source":"refusal / pressure"},
  {"id":"gl-064","cat":"say-and-hear","type":"role-play","hook":"You said yes earlier but now want to stop.","setup":"Use your reversible right. Say:","yourLine":[{"text":"\"I've changed my mind, I want to stop.\"","best":true},{"text":"Stay silent and uncomfortable"}],"relearn":"You can stop at any point; consent is reversible.","persona":"any","source":"FRIES / reversible"},
  {"id":"gl-065","cat":"say-and-hear","type":"role-play","hook":"A friend confides someone keeps pressuring them.","setup":"Back them up. Say:","yourLine":[{"text":"\"Your no is enough. Want help telling someone?\"","best":true},{"text":"\"Maybe just give in to keep the peace.\""}],"relearn":"Support a pressured friend; their 'no' is enough.","persona":"any","source":"peer support"},
  {"id":"gl-066","cat":"say-and-hear","type":"role-play","hook":"You need to set a boundary with a pushy relative.","setup":"Be respectful but firm. Say:","yourLine":[{"text":"\"I'd rather not, please respect that.\"","best":true},{"text":"Give in because they're older"}],"relearn":"You can set a respectful boundary, even with elders.","persona":"any","source":"boundaries / family"},
  {"id":"gl-067","cat":"say-and-hear","type":"role-play","hook":"You want to apologise for not respecting someone's no earlier.","setup":"Own it. Say:","yourLine":[{"text":"\"I'm sorry I pushed, I'll respect your no.\"","best":true},{"text":"\"You were being dramatic anyway.\""}],"relearn":"Owning a past push and committing to respect is real growth.","persona":"Veer","source":"accountability"},
  {"id":"gl-068","cat":"say-and-hear","type":"role-play","hook":"You're not sure how to say no without hurting feelings.","setup":"Kind and clear. Say:","yourLine":[{"text":"\"I care about you, and my answer is still no.\"","best":true},{"text":"Say yes to avoid awkwardness"}],"relearn":"You can be kind and say no at the same time.","persona":"Riya","source":"refusal"},
  {"id":"gl-069","cat":"say-and-hear","type":"branch","hook":"Someone keeps asking after you've already said no.","options":[{"text":"Repeat your no firmly; a real friend stops","consequence":"You hold the line; their reaction tells you a lot.","outcome":"firm","best":true},{"text":"Cave because they won't stop","consequence":"Repeated pushing after a no is a red flag; hold your no."}],"debrief":"Asking again after a no is pressure; you can keep saying no.","relearn":"You can repeat your no; pushing past it is a red flag.","persona":"any","source":"refusal / red flags"},
  {"id":"gl-070","cat":"say-and-hear","type":"branch","hook":"You realise you didn't actually check if your friend was okay.","options":[{"text":"Go back and check in now","consequence":"You repair it and they feel respected.","outcome":"caring","best":true},{"text":"Assume it was probably fine","consequence":"Checking in, even late, shows you care about consent."}],"debrief":"It's never too late to check in and respect someone's comfort.","relearn":"You can always go back and check someone was okay.","persona":"any","source":"checking in"},
  {"id":"gl-071","cat":"say-and-hear","type":"branch","hook":"A friend keeps saying yes to a group but seems uncomfortable.","options":[{"text":"Quietly offer them an out: 'we can leave if you want'","consequence":"You give them room for their real answer.","outcome":"ally","best":true},{"text":"Assume their 'yes' is genuine","consequence":"Offering an out helps someone whose 'yes' is really pressure."}],"debrief":"You can help a friend whose 'yes' is really going-along.","relearn":"You can offer a pressured friend a graceful way out.","persona":"any","source":"allyship / consent"},
  {"id":"gl-072","cat":"say-and-hear","type":"reflect","hook":"Lensy: 'No' is a complete sentence. Does that feel freeing?","prompt":"What do you think?","options":["Yes","I don't owe excuses","Freeing"],"affirm":"Your no needs no justification; it stands on its own.","relearn":"'No' is a complete answer; you don't owe an explanation.","persona":"any","source":"refusal"},
  {"id":"gl-073","cat":"say-and-hear","type":"reflect","hook":"Lensy: which is harder for you, saying no, or hearing one?","prompt":"Be honest.","options":["Saying no","Hearing no","Both","Neither now"],"affirm":"Both get easier with practice, and both matter equally.","relearn":"Both giving and accepting a 'no' are skills worth practising.","persona":"any","source":"reflection"},
  // — When a line is crossed —
  {"id":"gl-074","cat":"when-wrong","type":"branch","hook":"Someone crossed a line and did something to you that wasn't okay.","options":[{"text":"Tell a trusted adult; it's not your fault","consequence":"You get support and safety.","outcome":"safe","best":true},{"text":"Stay silent and blame yourself","consequence":"It's never your fault; please tell a trusted adult."}],"debrief":"If a line is crossed, it's not your fault, and telling a trusted adult helps.","relearn":"If someone crosses a line, it's not your fault; tell a trusted adult.","persona":"Counsellor","source":"safeguarding"},
  {"id":"gl-075","cat":"when-wrong","type":"branch","hook":"A friend tells you someone is hurting or coercing them.","options":[{"text":"Believe them and help them reach a trusted adult","consequence":"They're supported and safer.","outcome":"caring","best":true},{"text":"Tell them not to make a fuss","consequence":"Believe them and help them reach a trusted adult."}],"debrief":"Believing a friend and routing to help can change everything.","relearn":"Believe a friend who's being hurt and help them get help.","persona":"any","source":"safeguarding / peer"},
  {"id":"gl-076","cat":"when-wrong","type":"branch","hook":"You feel scared of someone's reactions in a relationship.","options":[{"text":"Take that fear seriously and talk to a trusted adult","consequence":"You get help for a real warning sign.","outcome":"safe","best":true},{"text":"Tell yourself you're overreacting","consequence":"Feeling scared is a serious sign; talk to a trusted adult."}],"debrief":"Fear in a relationship is a serious red flag worth getting help for.","relearn":"If you feel scared of someone, that's a sign to seek help.","persona":"Counsellor","source":"safeguarding"},
  {"id":"gl-077","cat":"when-wrong","type":"role-play","hook":"You're ready to tell a trusted adult about an unsafe relationship.","setup":"Open up. Say:","yourLine":[{"text":"\"Something's happening that doesn't feel safe, can we talk?\"","best":true},{"text":"Keep it hidden"}],"relearn":"You can name that something feels unsafe and ask to talk.","persona":"any","source":"help-seeking"},
  {"id":"gl-078","cat":"when-wrong","type":"role-play","hook":"You want to reassure a friend it wasn't their fault.","setup":"Say it plainly. Say:","yourLine":[{"text":"\"This is not your fault, and I'm here for you.\"","best":true},{"text":"\"What did you do to cause it?\""}],"relearn":"Tell someone harmed: it's not your fault, and I'm here.","persona":"any","source":"support / no blame"},
  {"id":"gl-079","cat":"when-wrong","type":"role-play","hook":"A helpline could help, but your friend is nervous to call.","setup":"Encourage them. Say:","yourLine":[{"text":"\"Childline 1098 is there to help, I'll sit with you.\"","best":true},{"text":"\"Don't bother, no one helps.\""}],"relearn":"Helplines like Childline 1098/112 help; you can support a friend to call.","persona":"Counsellor","source":"helpline (India)"},
  {"id":"gl-080","cat":"when-wrong","type":"strike-rewrite","hook":"\"If something bad happened, you must have led them on.\"","myth":{"un":"If someone crossed a line, the other person led them on.","re":"Only the person who crossed the line is responsible for it.","why":"Nothing you wear, say or do is 'asking for it'."},"relearn":"Crossing a line is always the crosser's fault, never the target's.","persona":"any","source":"no victim-blaming"},
  {"id":"gl-081","cat":"when-wrong","type":"strike-rewrite","hook":"\"You should keep relationship problems secret to avoid shame.\"","myth":{"un":"Relationship problems should be kept secret out of shame.","re":"Telling a trusted adult about an unsafe relationship is brave and right.","why":"Secrecy protects the harm, not you."},"relearn":"Telling a trusted adult about an unsafe relationship is right, not shameful.","persona":"any","source":"help-seeking / de-stigmatise"},
  {"id":"gl-082","cat":"when-wrong","type":"strike-rewrite","hook":"\"Leaving an unhealthy relationship means you failed.\"","myth":{"un":"Walking away from an unhealthy relationship is failure.","re":"Choosing to leave what harms you is strength and self-respect.","why":"Protecting yourself is never failure."},"relearn":"Leaving an unhealthy relationship is strength, not failure.","persona":"Riya","source":"self-respect"},
  {"id":"gl-083","cat":"when-wrong","type":"reflect","hook":"Lensy: you always deserve relationships that are safe and kind. Believe it?","prompt":"What do you think?","options":["Yes","I deserve safe & kind","Always"],"affirm":"Safe, kind, respectful, that's the baseline you deserve, always.","relearn":"You always deserve safe, kind, respectful relationships.","persona":"any","source":"worth"},
  {"id":"gl-084","cat":"when-wrong","type":"reflect","hook":"Lensy: biggest take-away from Green Light / Red Light?","prompt":"Pick your motto.","options":["Only yes means yes","Read the flags","Control isn't love","My no is enough"],"affirm":"Read the flags, insist on real consent, and keep the green, lose the red.","relearn":"Read the flags and insist on real, freely-given consent.","persona":"any","source":"consolidation"},
];

export const GLRL: V2GameConfig = {
  gameId: "glrl",
  title: "Green Light / Red Light",
  greet: "Hey, it's Lensy. 🚦 Time to read the flags. Swipe each one green or red, learn what real consent looks like (FRIES), and remember: keep the green, lose the red, and a crossed line is never your fault.",
  scenarios: SCENARIOS,
  categories: [
    { id: "what-is-consent", emoji: "🤝", label: "Consent (FRIES)" },
    // green-flags + red-flags merged into one MIXED category so each swipe is a real judgment (separate tiles
    // telegraphed the answer — every card in a green-flags session was a swipe-right).
    { id: "flags", emoji: "🚦", label: "Green or red?" },
    { id: "read-any", emoji: "🔍", label: "Read any bond" },
    { id: "say-and-hear", emoji: "🗣️", label: "Say it & hear it" },
    { id: "when-wrong", emoji: "🆘", label: "When a line's crossed" },
  ],
  badge: {
    title: "Flag Reader! 🚦",
    blurb: "You can read green and red flags, you know real consent is Free, Reversible, Informed, Enthusiastic and Specific (FRIES), and you know a crossed line is never your fault, you reach for help and keep the green. 💚",
  },
  helpLine: "If a relationship ever feels unsafe, or someone crosses a line, it is NOT your fault, tell a trusted adult. For serious harm or coercion you can call Childline, one-zero-nine-eight, or one-one-two. Leaving what harms you is strength, not failure.",
  helpLabel: "Get help · Childline 1098",
  reassure: "A crossed line is never your fault, and you always deserve relationships that are safe, kind and respectful. If something feels unsafe, tell a trusted adult or call Childline 1098/112, leaving what harms you is strength. 💚",
  reassureCats: ["when-wrong"],
};
