// Content for If, When & Whether (node g59, ages 22+, Chapter 7) — NEW v2 build to GDD 59 (mechanic-embodying),
// the reproductive-decision heart of Chapter 7 and the adult version of My Choices (g29): whether to have children,
// when, and how many — made with real knowledge, together, and free of pressure in ANY direction. 84 researched,
// India-grounded scenarios across whether-and-why → fertility-for-real → when-and-spacing → if-its-hard →
// free-of-pressure → tools-and-help, each encoded as one of the shared v2 play actions (strike-rewrite / branch /
// sort / reflect / match / role-play / spot) — no binary "tap the right card". Lead: strike-rewrite (bust the
// myth), branch (your move), sort. Six modes: whether & why (children are an if/when/whether CHOICE, not the
// assumed default; childfree is a complete, valid life; busts "a woman who doesn't want kids is selfish"), fertility
// for real (calm, honest fertility awareness — the fertile window, age trends for women AND men, preconception
// health & folic acid; busts both "there's always time" and "it just happens instantly"; refuses scare tactics),
// when & spacing (timing, readiness as honest reflection not perfection, spacing & contraception, your own timeline
// not the crowd's), if it's hard (infertility with compassion & realism — ~1 in 6 people, men & women roughly
// equally; options like IVF help many but aren't guaranteed; no false hope, no shame; routes to Many Ways to Family
// g60), free of pressure (the couple's autonomy; resisting "good news" pressure; confronting son-preference and
// sex-selection, ILLEGAL under the PCPNDT Act; refusing a weaponised fertility clock), tools & help (a
// decision-reflection tool, fertility basics, RKSK/public services & clinicians). Even-handed and non-coercive: NO
// pressure toward children or against; childfree and many-paths-to-parenthood equally valid; medically accurate but
// panic-free; NOT medical advice — points to clinicians. Builds on My Choices (g29); pairs with Many Ways to Family
// (g60). India: intense pressure to have children soon and ideally a son; infertility heavily stigmatised
// (especially for women, though male factor is common); sex selection illegal (PCPNDT Act); RKSK & public
// reproductive-health services. gameId "if-when-whether".
import type { V2GameConfig, Scenario } from "./v2-schema";

const SCENARIOS: Scenario[] = [
  {"id":"iw-001","cat":"whether-and-why","type":"strike-rewrite","hook":"\"Having children is just what everyone does; it's not really a choice.\"","myth":{"un":"Having children is just what everyone does; it's not really a choice.","re":"Whether to have children is a genuine, personal choice, not a foregone conclusion.","why":"A default isn't the same as a decision."},"relearn":"Whether to have children is a real, personal choice, not an automatic default.","persona":"Sneha","source":"whether is real"},
  {"id":"iw-002","cat":"whether-and-why","type":"strike-rewrite","hook":"\"A woman who doesn't want children is selfish or incomplete.\"","myth":{"un":"A woman who doesn't want children is selfish or incomplete.","re":"Choosing not to have children is a valid, complete life; womanhood is not the same as motherhood.","why":"Worth isn't measured by parenthood."},"relearn":"Choosing to be childfree is a valid, complete life; it isn't selfish or incomplete.","persona":"Sneha","source":"childfree is complete"},
  {"id":"iw-003","cat":"whether-and-why","type":"sort","hook":"Sort: a valid reason to shape this decision, or outside pressure that shouldn't?","items":[{"id":"a","text":"What you and your partner actually want"},{"id":"b","text":"Relatives asking for 'good news'"},{"id":"c","text":"Your readiness and circumstances"},{"id":"d","text":"Neighbours' expectations"}],"bins":[{"id":"valid","label":"Yours to weigh"},{"id":"pressure","label":"Outside pressure"}],"key":{"a":"valid","b":"pressure","c":"valid","d":"pressure"},"relearn":"Your own wishes and readiness are yours to weigh; relatives' and neighbours' expectations are outside pressure.","persona":"any","source":"yours vs pressure"},
  {"id":"iw-004","cat":"whether-and-why","type":"branch","hook":"You realise you've never actually asked yourself whether you want children, only when.","options":[{"text":"Pause and ask the real 'whether' question honestly, with your partner","consequence":"You make a decision instead of a default.","outcome":"deliberate","best":true},{"text":"Skip it; assume children are just the next step","consequence":"Asking the real 'whether' makes it a decision; assuming the next step lets a default run your life."}],"debrief":"The 'whether' is worth asking deliberately, before the 'when'.","relearn":"Ask the 'whether' question honestly first; don't let a default decide one of life's biggest choices.","persona":"Karthik","source":"ask whether"},
  {"id":"iw-005","cat":"whether-and-why","type":"match","hook":"Match each path to what it can be.","pairs":[{"left":"Choosing to have children","right":"A valid, joyful path"},{"left":"Choosing to be childfree","right":"An equally valid, full life"},{"left":"Still deciding","right":"A fine place to be, no rush"}],"relearn":"Having children, being childfree and still deciding are all valid; none is a failure.","persona":"any","source":"all valid"},
  {"id":"iw-006","cat":"whether-and-why","type":"strike-rewrite","hook":"\"You'll definitely regret it if you don't have children.\"","myth":{"un":"You'll definitely regret it if you don't have children.","re":"Many childfree people live happy, fulfilled lives; regret is not guaranteed in any direction.","why":"Fear of regret isn't a reason to decide either way."},"relearn":"Childfree people can be happy and fulfilled; guaranteed regret is a myth, not a fact.","persona":"Sneha","source":"regret isn't certain"},
  {"id":"iw-007","cat":"whether-and-why","type":"reflect","hook":"Sam: this is your decision and your partner's, no one else's. How does owning it feel?","prompt":"What do you think?","options":["It's ours","Freeing","Owning it"],"affirm":"Whether and when to have children belongs to you and your partner, not to family or society.","relearn":"Whether and when to have children is yours and your partner's to decide, no one else's.","persona":"any","source":"yours to own"},
  {"id":"iw-008","cat":"whether-and-why","type":"spot","hook":"Spot the healthy way to approach the 'whether' question.","scene":[{"id":"a","text":"Talking it through honestly together","trick":false},{"id":"b","text":"Letting shame or pressure decide it","trick":true},{"id":"c","text":"Giving yourself permission to choose either way","trick":false}],"why":"Honest talk and permission to choose either way are healthy; letting shame or pressure decide isn't.","relearn":"Approach 'whether' with honest talk and permission to choose either way, not shame or pressure.","persona":"any","source":"healthy approach"},
  {"id":"iw-009","cat":"whether-and-why","type":"branch","hook":"You and your partner want different things about having children, and it's tense.","options":[{"text":"Have honest, repeated conversations about the real wants beneath it","consequence":"You face a big difference with care, not avoidance.","outcome":"honest","best":true},{"text":"Avoid the topic and hope it resolves itself","consequence":"Honest, repeated talks let you face a real difference with care; avoidance just defers a decision this big."}],"debrief":"Differences about children need honest, ongoing conversation, not avoidance.","relearn":"Talk through differences about children honestly; this is too big to avoid.","persona":"Karthik","source":"face the difference"},
  {"id":"iw-010","cat":"whether-and-why","type":"sort","hook":"Sort: a complete, valid life, or a 'failure' the way pressure frames it?","items":[{"id":"a","text":"A fulfilling childfree life"},{"id":"b","text":"'She never had kids, poor thing'"},{"id":"c","text":"A chosen, content single life"},{"id":"d","text":"'They're incomplete without a child'"}],"bins":[{"id":"complete","label":"Complete & valid"},{"id":"framed","label":"Pressure's false frame"}],"key":{"a":"complete","b":"framed","c":"complete","d":"framed"},"relearn":"A childfree or chosen single life is complete and valid; 'poor thing' and 'incomplete' are pressure's false frames.","persona":"Sneha","source":"complete not failure"},
  {"id":"iw-011","cat":"whether-and-why","type":"reflect","hook":"Sam: 'not yet', 'never', and 'another way' are all real, respectable answers. Permission granted?","prompt":"What's your take?","options":["Granted","All valid","Good to hear"],"affirm":"'Not yet', 'never' and 'another way' are all legitimate answers to the children question.","relearn":"'Not yet', 'never' and 'another way' are all real, respectable answers.","persona":"any","source":"permission granted"},
  {"id":"iw-012","cat":"whether-and-why","type":"role-play","hook":"A relative asks yet again when you'll have 'good news'. You want a warm, boundaried answer.","setup":"Answer warmly:","yourLine":[{"text":"\"When and whether we have children is something we'll decide ourselves, thanks for caring.\"","best":true},{"text":"\"Soon, soon, don't worry.\""}],"relearn":"A warm 'we'll decide ourselves' holds the boundary on a deeply personal choice without a fight.","persona":"Pooja","source":"good-news boundary"},
  {"id":"iw-013","cat":"whether-and-why","type":"strike-rewrite","hook":"\"If you love each other, having children is the obvious next step.\"","myth":{"un":"If you love each other, having children is the obvious next step.","re":"Love is complete in itself; having children is a separate, deliberate choice, not a proof of love.","why":"A relationship doesn't require children to be whole."},"relearn":"Having children is a separate, deliberate choice, not the automatic proof or next step of love.","persona":"any","source":"love needs no proof"},
  {"id":"iw-014","cat":"fertility-for-real","type":"strike-rewrite","hook":"\"There's always plenty of time; fertility doesn't really change with age.\"","myth":{"un":"There's always plenty of time; fertility doesn't really change with age.","re":"Fertility does gradually decline with age, sooner for women, and somewhat for men too, so it's worth knowing for planning.","why":"Knowing the facts helps you plan, calmly."},"relearn":"Fertility gradually declines with age (sooner for women, somewhat for men); knowing this helps calm planning.","persona":"any","source":"age matters, calmly"},
  {"id":"iw-015","cat":"fertility-for-real","type":"strike-rewrite","hook":"\"Pregnancy just happens instantly whenever you decide you're ready.\"","myth":{"un":"Pregnancy just happens instantly whenever you decide you're ready.","re":"Conception can take several months even when all is well, and isn't guaranteed on a schedule.","why":"Real timelines are more variable than the movies suggest."},"relearn":"Conception can take months even when all is well; it doesn't happen instantly on demand.","persona":"any","source":"not instant"},
  {"id":"iw-016","cat":"fertility-for-real","type":"strike-rewrite","hook":"\"Fertility 'awareness' is really just scaring women into rushing.\"","myth":{"un":"Fertility 'awareness' is really just scaring women into rushing.","re":"Honest fertility facts are tools for your own planning, calm information, never a scare tactic or a deadline imposed on you.","why":"Information empowers; panic manipulates."},"relearn":"Honest fertility facts are calm planning tools you own, not scare tactics or an imposed deadline.","persona":"Sneha","source":"facts not fear"},
  {"id":"iw-017","cat":"fertility-for-real","type":"sort","hook":"Sort: an honest fertility fact, or a panic-driven myth?","items":[{"id":"a","text":"Fertility declines gradually with age"},{"id":"b","text":"After 30 it's basically over"},{"id":"c","text":"Conception can take a few months"},{"id":"d","text":"One 'wrong' year ruins everything"}],"bins":[{"id":"fact","label":"Honest fact"},{"id":"panic","label":"Panic myth"}],"key":{"a":"fact","b":"panic","c":"fact","d":"panic"},"relearn":"Gradual decline and conception taking months are facts; 'over after 30' and 'one year ruins it' are panic myths.","persona":"any","source":"fact vs panic"},
  {"id":"iw-018","cat":"fertility-for-real","type":"match","hook":"Match each fertility basic to what it means.","pairs":[{"left":"The fertile window","right":"The few days each cycle conception is likeliest"},{"left":"Age and fertility","right":"A gradual decline, faster later for women"},{"left":"Preconception health","right":"Getting healthy before trying helps"}],"relearn":"The fertile window, age trends and preconception health are the calm basics of fertility awareness.","persona":"any","source":"fertility basics"},
  {"id":"iw-019","cat":"fertility-for-real","type":"strike-rewrite","hook":"\"Preconception health doesn't matter; you only think about health once pregnant.\"","myth":{"un":"Preconception health doesn't matter; you only think about health once pregnant.","re":"Getting healthy before trying, including folic acid, helps; folic acid before and early in pregnancy cuts certain birth defects sharply.","why":"The months before conception count."},"relearn":"Preconception health matters; folic acid before and early in pregnancy sharply cuts certain birth defects.","persona":"Pooja","source":"preconception counts"},
  {"id":"iw-020","cat":"fertility-for-real","type":"reflect","hook":"Sam: knowing your fertility facts is power, to plan on your terms, not to panic. Sit right?","prompt":"What do you think?","options":["Sits right","On my terms","Power not panic"],"affirm":"Fertility knowledge is for planning on your own terms, calmly, not for panic or pressure.","relearn":"Fertility facts are power to plan on your terms, not a reason to panic.","persona":"any","source":"power not panic"},
  {"id":"iw-021","cat":"fertility-for-real","type":"spot","hook":"Spot the calm, honest fertility message, versus the manipulative one.","scene":[{"id":"a","text":"\"Here are the facts, so you can plan your way\"","trick":false},{"id":"b","text":"\"Hurry up or you'll miss your only chance\"","trick":true},{"id":"c","text":"\"Both partners' health and age can matter\"","trick":false}],"why":"Facts-to-plan-your-way and both-partners messaging are honest; 'hurry or miss your only chance' is manipulation.","relearn":"Honest fertility messaging informs and includes both partners; the manipulative kind rushes and scares.","persona":"Sneha","source":"honest message"},
  {"id":"iw-022","cat":"fertility-for-real","type":"branch","hook":"You want to understand your own fertility but every article online is either panic or false comfort.","options":[{"text":"Seek calm, accurate sources, a clinician or trusted health service","consequence":"You get real information without the noise.","outcome":"informed","best":true},{"text":"Either panic from one article or dismiss it all","consequence":"A clinician gives real information without the noise; panicking or dismissing both lose you the calm facts."}],"debrief":"Get fertility facts from calm, accurate sources like a clinician, not panic or false-comfort articles.","relearn":"Seek calm, accurate fertility info from a clinician; skip the panic and the false comfort.","persona":"Pooja","source":"calm sources"},
  {"id":"iw-023","cat":"fertility-for-real","type":"match","hook":"Match each partner factor to the calm truth.","pairs":[{"left":"Women's age","right":"Gradual decline, faster after the mid-30s"},{"left":"Men's age and health","right":"Can affect fertility too, it's not only women"},{"left":"Lifestyle","right":"Health habits can support fertility for both"}],"relearn":"Fertility involves both partners: women's and men's age and health all matter, calmly understood.","persona":"Karthik","source":"both partners"},
  {"id":"iw-024","cat":"fertility-for-real","type":"reflect","hook":"Sam: fertility is something to understand, not fear, and it's never only the woman's concern. Agree?","prompt":"What's your take?","options":["Agree","Both of us","Understand not fear"],"affirm":"Fertility is to be understood calmly by both partners, not feared or pinned on women alone.","relearn":"Fertility is a both-partners matter to understand calmly, not to fear or pin on women.","persona":"any","source":"not only her"},
  {"id":"iw-025","cat":"fertility-for-real","type":"sort","hook":"Sort: supports calm, real planning, or feeds anxiety unhelpfully?","items":[{"id":"a","text":"Learning the basics from a clinician"},{"id":"b","text":"Doomscrolling fertility scare posts"},{"id":"c","text":"Both partners getting informed"},{"id":"d","text":"Treating a guideline as a personal deadline"}],"bins":[{"id":"calm","label":"Calm planning"},{"id":"anxiety","label":"Feeds anxiety"}],"key":{"a":"calm","b":"anxiety","c":"calm","d":"anxiety"},"relearn":"Clinician basics and both partners informed support calm planning; doomscrolling and self-imposed deadlines feed anxiety.","persona":"any","source":"calm vs anxiety"},
  {"id":"iw-026","cat":"when-and-spacing","type":"strike-rewrite","hook":"\"You must have children immediately after marriage.\"","myth":{"un":"You must have children immediately after marriage.","re":"Timing is yours to choose; there's no rule that children must follow a wedding at once.","why":"A wedding date isn't a fertility deadline."},"relearn":"When to have children is yours to time; there's no rule they must follow marriage immediately.","persona":"Pooja","source":"timing is yours"},
  {"id":"iw-027","cat":"when-and-spacing","type":"sort","hook":"Sort: a sound reason to time or space children, or someone else's agenda?","items":[{"id":"a","text":"Your readiness and stability"},{"id":"b","text":"Relatives wanting a grandchild now"},{"id":"c","text":"Health and recovery between pregnancies"},{"id":"d","text":"Keeping up with friends' families"}],"bins":[{"id":"sound","label":"Sound reason"},{"id":"agenda","label":"Someone else's agenda"}],"key":{"a":"sound","b":"agenda","c":"sound","d":"agenda"},"relearn":"Your readiness and health are sound reasons to time children; relatives' and peers' timelines are their agenda.","persona":"any","source":"sound vs agenda"},
  {"id":"iw-028","cat":"when-and-spacing","type":"strike-rewrite","hook":"\"Readiness means having everything perfect first.\"","myth":{"un":"Readiness means having everything perfect first.","re":"No one is ever fully 'ready'; readiness is honest reflection on the essentials, not perfection.","why":"Waiting for perfect can mean waiting forever."},"relearn":"Readiness is honest reflection on the essentials, not having everything perfect first.","persona":"Sneha","source":"readiness not perfection"},
  {"id":"iw-029","cat":"when-and-spacing","type":"branch","hook":"You feel pressured to have a second child quickly, though you'd prefer to space them.","options":[{"text":"Decide spacing on your health and circumstances, with your partner","consequence":"You plan on your terms, not the pressure's.","outcome":"spaced","best":true},{"text":"Rush a second child to satisfy relatives","consequence":"Spacing on your health and choice plans on your terms; rushing to satisfy relatives ignores your wellbeing."}],"debrief":"Space children on your own health and circumstances, not on family pressure.","relearn":"Decide spacing on your health and choice; relatives' wishes don't set the timeline.","persona":"Pooja","source":"space on your terms"},
  {"id":"iw-030","cat":"when-and-spacing","type":"match","hook":"Match each spacing tool or idea to its role.","pairs":[{"left":"Contraception for spacing","right":"Choosing the gap between children"},{"left":"Recovery time","right":"Health between pregnancies"},{"left":"Honest readiness check","right":"Deciding when, together"}],"relearn":"Contraception, recovery time and an honest readiness check are how couples plan when and how many, on their terms.","persona":"any","source":"spacing tools"},
  {"id":"iw-031","cat":"when-and-spacing","type":"reflect","hook":"Sam: 'when' and 'how many' are yours to set, revisited as life changes. Feel ownable?","prompt":"What do you think?","options":["Ownable","Mine to set","Yes"],"affirm":"Timing and number of children are yours to decide and revisit as your life and circumstances change.","relearn":"When and how many children are yours to set and revisit as life changes.","persona":"any","source":"yours to set"},
  {"id":"iw-032","cat":"when-and-spacing","type":"spot","hook":"Spot what genuinely belongs in a 'when are we ready' check.","scene":[{"id":"a","text":"Your relationship stability and wishes","trick":false},{"id":"b","text":"Whether the neighbours approve","trick":true},{"id":"c","text":"Your health and practical circumstances","trick":false}],"why":"Your relationship, wishes, health and circumstances belong in a readiness check; the neighbours' approval doesn't.","relearn":"A readiness check is about your relationship, wishes, health and circumstances, not others' approval.","persona":"any","source":"real readiness check"},
  {"id":"iw-033","cat":"when-and-spacing","type":"branch","hook":"Friends are all having babies and you feel behind, though you're not actually ready.","options":[{"text":"Honour your own timeline instead of matching the crowd","consequence":"You decide from readiness, not comparison.","outcome":"own-timeline","best":true},{"text":"Have a child now just to keep pace","consequence":"Honouring your own timeline decides from readiness; keeping pace with friends decides from comparison and fear."}],"debrief":"Set your own timeline for children; don't have one just to keep pace with friends.","relearn":"Honour your own readiness; comparison isn't a reason to have a child now.","persona":"Sneha","source":"own timeline"},
  {"id":"iw-034","cat":"when-and-spacing","type":"strike-rewrite","hook":"\"More children is always better, regardless of what the parents want or can manage.\"","myth":{"un":"More children is always better, regardless of what the parents want or can manage.","re":"How many children is the parents' choice, weighing their wishes, health and circumstances, not a number to maximise.","why":"Family size is a personal decision."},"relearn":"How many children is the parents' choice based on their wishes and circumstances, not a number to maximise.","persona":"any","source":"how many is yours"},
  {"id":"iw-035","cat":"when-and-spacing","type":"reflect","hook":"Sam: there's no universal 'right time', only your right time, decided together. Land okay?","prompt":"What's your take?","options":["Lands okay","My right time","Together"],"affirm":"There is no universal right time for children, only the time that's right for you, decided together.","relearn":"There's no universal right time for children, only yours, decided together.","persona":"any","source":"your right time"},
  {"id":"iw-036","cat":"when-and-spacing","type":"role-play","hook":"Your partner wants to start trying; you'd like to wait a bit. You want to talk it through fairly.","setup":"Open it honestly:","yourLine":[{"text":"\"I want this with you, and I'd like us to agree on timing that works for us both, can we talk it through?\"","best":true},{"text":"\"Fine, whatever you want.\""}],"relearn":"Naming both the shared want and your timing need opens a fair conversation instead of a silent concession.","persona":"Karthik","source":"timing talk"},
  {"id":"iw-037","cat":"if-its-hard","type":"strike-rewrite","hook":"\"Infertility is rare and always the woman's fault.\"","myth":{"un":"Infertility is rare and always the woman's fault.","re":"Infertility is common, affecting around 1 in 6 people, and involves men and women roughly equally, male factors are in about a third or more of cases.","why":"It's common, and it's not a woman's fault."},"relearn":"Infertility is common (about 1 in 6) and involves men and women roughly equally; it isn't 'the woman's fault'.","persona":"Reshma","source":"common, not her fault"},
  {"id":"iw-038","cat":"if-its-hard","type":"strike-rewrite","hook":"\"If you're struggling to conceive, you just aren't trying hard enough.\"","myth":{"un":"If you're struggling to conceive, you just aren't trying hard enough.","re":"Difficulty conceiving usually has medical causes and is no one's failing; a clinician can help find out why.","why":"Effort isn't the issue; biology often is."},"relearn":"Trouble conceiving usually has medical causes and is no one's failing; a clinician can help investigate.","persona":"Reshma","source":"not a failing"},
  {"id":"iw-039","cat":"if-its-hard","type":"sort","hook":"Sort: a compassionate, realistic truth about infertility, or a harmful myth?","items":[{"id":"a","text":"Both partners should be evaluated"},{"id":"b","text":"It's shameful and must be hidden"},{"id":"c","text":"Options exist but aren't guaranteed"},{"id":"d","text":"IVF always works if you really want it"}],"bins":[{"id":"true","label":"Compassionate truth"},{"id":"myth","label":"Harmful myth"}],"key":{"a":"true","b":"myth","c":"true","d":"myth"},"relearn":"Evaluating both partners and honest option-talk are compassionate truths; shame and 'IVF always works' are harmful myths.","persona":"Reshma","source":"truth vs myth"},
  {"id":"iw-040","cat":"if-its-hard","type":"strike-rewrite","hook":"\"IVF and treatments are a guaranteed fix, so there's nothing to think through.\"","myth":{"un":"IVF and treatments are a guaranteed fix, so there's nothing to think through.","re":"Treatments like IVF help many but don't always succeed and can be demanding; honest, realistic expectations matter.","why":"Real hope is honest, not absolute."},"relearn":"Treatments like IVF help many but aren't guaranteed and can be demanding; realistic expectations matter.","persona":"Reshma","source":"honest hope"},
  {"id":"iw-041","cat":"if-its-hard","type":"branch","hook":"A year of trying hasn't worked, and you're scared and unsure what to do.","options":[{"text":"See a clinician together for honest evaluation and options","consequence":"You move from fear to information and support.","outcome":"evaluated","best":true},{"text":"Blame yourself silently and avoid finding out","consequence":"Seeing a clinician together turns fear into information and options; silent self-blame just prolongs the distress."}],"debrief":"If conceiving is hard, see a clinician together for honest evaluation; don't suffer in self-blame.","relearn":"See a clinician together when conceiving is hard; that beats silent self-blame.","persona":"Reshma","source":"get evaluated"},
  {"id":"iw-042","cat":"if-its-hard","type":"match","hook":"Match each route when conceiving is hard to what it offers.","pairs":[{"left":"Medical evaluation","right":"Finding out why, for both partners"},{"left":"Assisted reproduction (e.g. IVF)","right":"An option for some, not a guarantee"},{"left":"Many Ways to Family (g60)","right":"Adoption and other routes to family"}],"relearn":"Evaluation, assisted reproduction and other routes (g60) are all real options when conceiving is hard.","persona":"Reshma","source":"routes when hard"},
  {"id":"iw-043","cat":"if-its-hard","type":"reflect","hook":"Sam: infertility is common, it's no one's shame, and you don't have to face it alone. Hear that?","prompt":"What do you think?","options":["I hear it","Not my shame","Not alone"],"affirm":"Infertility is common and never shameful; support, evaluation and options exist, and you needn't face it alone.","relearn":"Infertility is common and no one's shame; support and options exist, and you're not alone.","persona":"Reshma","source":"not your shame"},
  {"id":"iw-044","cat":"if-its-hard","type":"spot","hook":"Spot the supportive response to a couple facing infertility.","scene":[{"id":"a","text":"\"It's common, and it's not your fault\"","trick":false},{"id":"b","text":"\"You must be doing something wrong\"","trick":true},{"id":"c","text":"\"Let's look at the options calmly together\"","trick":false}],"why":"'It's common, not your fault' and 'options calmly' are supportive; 'you're doing something wrong' is harmful.","relearn":"Support for infertility says 'it's common, not your fault, options exist', never 'you're doing something wrong'.","persona":"Reshma","source":"supportive response"},
  {"id":"iw-045","cat":"if-its-hard","type":"strike-rewrite","hook":"\"A couple without a biological child has failed.\"","myth":{"un":"A couple without a biological child has failed.","re":"A family can be whole in many forms; a biological child is one path to family, not the measure of one.","why":"Family is defined by love, not biology alone."},"relearn":"A couple without a biological child hasn't failed; family takes many whole forms.","persona":"Razia","source":"many forms whole"},
  {"id":"iw-046","cat":"if-its-hard","type":"reflect","hook":"Sam: there are many ways to build a family, and we explore them fully in the next node. Comforting?","prompt":"What's your take?","options":["Comforting","Many ways","Good to know"],"affirm":"Biological children are one route to family; Many Ways to Family (g60) covers the others, all valid.","relearn":"There are many valid ways to build a family; a biological child is one route, not the only one.","persona":"any","source":"many ways"},
  {"id":"iw-047","cat":"if-its-hard","type":"branch","hook":"Relatives shame your friend for not conceiving, piling on the pressure.","options":[{"text":"Support her gently and push back on the shame, not her","consequence":"She feels less alone against the stigma.","outcome":"supported","best":true},{"text":"Join the chorus asking when she'll 'give good news'","consequence":"Supporting her and naming the shame as wrong eases the stigma; joining the chorus adds to a deeply unfair burden."}],"debrief":"Support someone facing infertility and push back on the shame; never add to the 'good news' pressure.","relearn":"Stand with someone facing infertility against the shame; don't join the pressure.","persona":"Razia","source":"stand with her"},
  {"id":"iw-048","cat":"free-of-pressure","type":"strike-rewrite","hook":"\"It's the family's right to decide when you have children.\"","myth":{"un":"It's the family's right to decide when you have children.","re":"Whether and when to have children is the couple's own decision; family can have feelings but not the final say.","why":"Reproductive choices belong to those who live them."},"relearn":"Whether and when to have children is the couple's decision; family doesn't get the final say.","persona":"Pooja","source":"couple decides"},
  {"id":"iw-049","cat":"free-of-pressure","type":"strike-rewrite","hook":"\"You must keep trying until you have a son.\"","myth":{"un":"You must keep trying until you have a son.","re":"Son-preference is harmful and unjust; daughters and sons are equally valued, and sex selection is illegal in India.","why":"A child's worth has nothing to do with sex."},"relearn":"Son-preference is unjust; daughters and sons are equally valued, and sex selection is illegal in India.","persona":"Razia","source":"no son-preference"},
  {"id":"iw-050","cat":"free-of-pressure","type":"strike-rewrite","hook":"\"Finding out and choosing the baby's sex before birth is a private family matter.\"","myth":{"un":"Finding out and choosing the baby's sex before birth is a private family matter.","re":"Prenatal sex determination and sex selection are illegal in India under the PCPNDT Act, to stop the loss of girls.","why":"The law protects daughters from being selected away."},"relearn":"Prenatal sex determination and sex selection are illegal in India under the PCPNDT Act.","persona":"Razia","source":"PCPNDT"},
  {"id":"iw-051","cat":"free-of-pressure","type":"sort","hook":"Sort: respects the couple's reproductive autonomy, or violates it?","items":[{"id":"a","text":"The couple deciding whether and when"},{"id":"b","text":"Pressure to produce a son"},{"id":"c","text":"Choosing your own family size"},{"id":"d","text":"Demands to conceive on the family's schedule"}],"bins":[{"id":"respects","label":"Respects autonomy"},{"id":"violates","label":"Violates it"}],"key":{"a":"respects","b":"violates","c":"respects","d":"violates"},"relearn":"The couple deciding whether, when and how many respects autonomy; son-pressure and forced schedules violate it.","persona":"Pooja","source":"autonomy or not"},
  {"id":"iw-052","cat":"free-of-pressure","type":"branch","hook":"Your in-laws pressure you constantly to conceive, and quickly.","options":[{"text":"Kindly but firmly hold that this is yours and your partner's to decide","consequence":"You protect a deeply personal choice.","outcome":"held","best":true},{"text":"Give in to end the pressure, ready or not","consequence":"Holding the boundary protects a deeply personal choice; giving in hands your most personal decision to others."}],"debrief":"Hold kindly but firmly that whether and when to conceive is yours; don't surrender it to pressure.","relearn":"Hold your reproductive choice kindly but firmly; don't surrender it to end the pressure.","persona":"Pooja","source":"hold the choice"},
  {"id":"iw-053","cat":"free-of-pressure","type":"reflect","hook":"Sam: a fertility 'clock' should never be weaponised against you, by anyone. This is your decision. Clear?","prompt":"What do you think?","options":["Clear","My decision","Not weaponised"],"affirm":"Your reproductive timeline is yours; a fertility clock should never be used as a weapon to pressure you.","relearn":"Your fertility timeline is yours; it should never be weaponised to pressure you.","persona":"Sneha","source":"not weaponised"},
  {"id":"iw-054","cat":"free-of-pressure","type":"spot","hook":"Spot pressure dressed up as care.","scene":[{"id":"a","text":"\"We just want grandchildren now\" pushed relentlessly","trick":true},{"id":"b","text":"Offering genuine, no-strings support either way","trick":false},{"id":"c","text":"\"When's the good news?\" at every meeting","trick":true}],"why":"Relentless grandchild demands and constant 'good news' jabs are pressure; genuine no-strings support is care.","relearn":"Relentless pushing for grandchildren or 'good news' is pressure, not the support it pretends to be.","persona":"any","source":"pressure vs care"},
  {"id":"iw-055","cat":"free-of-pressure","type":"strike-rewrite","hook":"\"Once you have a child, you have to immediately have another so they're not alone.\"","myth":{"un":"Once you have a child, you have to immediately have another so they're not alone.","re":"Whether and when to have another child stays the parents' choice; an only child can thrive too.","why":"Each decision is still yours to make."},"relearn":"Whether to have another child stays the parents' choice; an only child can thrive too.","persona":"Sneha","source":"still your choice"},
  {"id":"iw-056","cat":"free-of-pressure","type":"match","hook":"Match each pressure line to a calm, autonomous reply.","pairs":[{"left":"\"When's the good news?\"","right":"\"We'll share our news in our own time.\""},{"left":"\"You need a son.\"","right":"\"We'll love any child equally.\""},{"left":"\"Hurry, you're not young.\"","right":"\"We're deciding this on our own terms.\""}],"relearn":"Each pressure line has a calm, autonomous reply that holds your choice without a fight.","persona":"any","source":"calm replies"},
  {"id":"iw-057","cat":"free-of-pressure","type":"reflect","hook":"Sam: no pressure toward children, no pressure against, just your honest, free choice. Feel respected?","prompt":"What's your take?","options":["Respected","My free choice","No pressure"],"affirm":"The node pushes no answer in any direction; the goal is your honest, free, well-informed choice.","relearn":"No pressure toward children or against, just your honest, free, informed choice.","persona":"any","source":"free choice"},
  {"id":"iw-058","cat":"tools-and-help","type":"branch","hook":"You want a calm way to actually work through the whether/when/how-many decision.","options":[{"text":"Use a reflection tool: your wishes, your partner's, readiness and facts, no outside voices","consequence":"The decision becomes clear and yours.","outcome":"reflected","best":true},{"text":"Just let pressure and panic decide it","consequence":"A reflection tool centres your wishes and the facts; pressure and panic decide it for you and badly."}],"debrief":"Work the decision through a calm reflection of your wishes, readiness and facts, free of outside voices.","relearn":"Use a calm reflection of wishes, readiness and facts; don't let pressure and panic decide.","persona":"Karthik","source":"reflection tool"},
  {"id":"iw-059","cat":"tools-and-help","type":"match","hook":"Match each tool or service to what it's for.","pairs":[{"left":"The decision-reflection tool","right":"Thinking it through, pressure-free"},{"left":"Fertility basics & a clinician","right":"Accurate facts and real care"},{"left":"Public services (e.g. RKSK)","right":"Reproductive health support in India"}],"relearn":"A reflection tool, a clinician for fertility facts, and public services like RKSK are the core supports here.","persona":"any","source":"the toolkit"},
  {"id":"iw-060","cat":"tools-and-help","type":"strike-rewrite","hook":"\"This is medical advice you can just follow off an app.\"","myth":{"un":"This is medical advice you can just follow off an app.","re":"This game gives general information to help you think and ask better questions; a clinician gives medical advice.","why":"An app informs; a doctor diagnoses."},"relearn":"This is general information to help you think and ask, not medical advice; a clinician gives that.","persona":"any","source":"not medical advice"},
  {"id":"iw-061","cat":"tools-and-help","type":"sort","hook":"Sort: a healthy support for this decision, or a harmful pressure to avoid?","items":[{"id":"a","text":"Accurate facts from a clinician"},{"id":"b","text":"Scare-tactic fertility posts"},{"id":"c","text":"Honest talk with your partner"},{"id":"d","text":"Relatives' constant deadlines"}],"bins":[{"id":"support","label":"Healthy support"},{"id":"pressure","label":"Harmful pressure"}],"key":{"a":"support","b":"pressure","c":"support","d":"pressure"},"relearn":"Clinician facts and honest partner talk support the decision; scare posts and relatives' deadlines pressure it.","persona":"any","source":"support vs pressure"},
  {"id":"iw-062","cat":"tools-and-help","type":"reflect","hook":"Sam: whether, when, how many, and what if it's hard, you've now got calm ways through all of it. Ready?","prompt":"What do you think?","options":["Ready","Calm ways through","Got it"],"affirm":"Whether, when, how many and the if-it's-hard path each now have calm, informed ways through.","relearn":"You hold calm, informed ways through whether, when, how many, and if it's hard.","persona":"any","source":"ways through"},
  {"id":"iw-063","cat":"tools-and-help","type":"branch","hook":"You're not sure if a worry about fertility or conceiving needs a doctor yet.","options":[{"text":"Ask a clinician, you don't need to be sure to get checked or reassured","consequence":"You get clarity early instead of worrying alone.","outcome":"asked","best":true},{"text":"Wait and worry until it feels like a crisis","consequence":"Asking a clinician gives clarity or reassurance early; waiting alone until crisis just prolongs the worry."}],"debrief":"You can see a clinician while unsure; you don't have to be certain to get checked or reassured.","relearn":"See a clinician while unsure; you needn't wait for a crisis to get checked.","persona":"Reshma","source":"ask early"},
  {"id":"iw-064","cat":"tools-and-help","type":"match","hook":"Match a moment to the tool that fits it.","pairs":[{"left":"Deciding whether or when","right":"The reflection tool, pressure-free"},{"left":"Wanting real fertility facts","right":"A clinician or trusted service"},{"left":"Facing pressure or shame","right":"A boundary line and support"}],"relearn":"Each moment has a fit: reflection to decide, a clinician for facts, a boundary and support against pressure.","persona":"any","source":"moment to tool"},
  {"id":"iw-065","cat":"tools-and-help","type":"spot","hook":"Spot the sustainable way to make this big decision.","scene":[{"id":"a","text":"Honest reflection plus accurate facts","trick":false},{"id":"b","text":"A panicked rush to beat a 'deadline'","trick":true},{"id":"c","text":"Deciding with your partner, on your terms","trick":false}],"why":"Honest reflection with facts and deciding together are sustainable; a panicked rush to beat a deadline isn't.","relearn":"Make this decision through honest reflection, facts and partnership, not a panicked rush.","persona":"any","source":"sustainable decision"},
  {"id":"iw-066","cat":"tools-and-help","type":"reflect","hook":"Sam: this is one of life's biggest choices, and now it's an informed, unpressured, shared one. Feel ready to own it?","prompt":"What's your take?","options":["Ready to own it","Informed & free","Yes"],"affirm":"The whether/when/how-many decision is best made informed, unpressured and shared; now you're equipped to own it.","relearn":"This big choice is now an informed, unpressured, shared one, and it's yours to own.","persona":"any","source":"own the choice"},
  {"id":"iw-067","cat":"tools-and-help","type":"role-play","hook":"Your partner asks how you two should approach the whole children question. Set the tone together.","setup":"Say it as a team:","yourLine":[{"text":"\"Let's decide it ourselves, with honest facts and no outside pressure, and revisit it as we grow.\"","best":true},{"text":"\"Let's just see what everyone expects of us.\""}],"relearn":"Setting an informed, pressure-free, revisitable tone keeps the decision yours rather than the family's.","persona":"Karthik","source":"set the tone"},
  {"id":"iw-068","cat":"tools-and-help","type":"strike-rewrite","hook":"\"There's no real way to make this choice well; you just hope it works out.\"","myth":{"un":"There's no real way to make this choice well; you just hope it works out.","re":"You can make it well, with honest reflection, accurate facts, partnership and freedom from pressure.","why":"Big choices are navigable with the right tools."},"relearn":"You can make this choice well using honest reflection, accurate facts, partnership and freedom from pressure.","persona":"any","source":"navigable choice"},
  {"id":"iw-069","cat":"whether-and-why","type":"role-play","hook":"A friend confides she's not sure she ever wants kids and feels guilty about it. You want to reassure her.","setup":"Reassure her warmly:","yourLine":[{"text":"\"That's a completely valid choice, you don't owe anyone children to live a full life.\"","best":true},{"text":"\"You'll change your mind, everyone does.\""}],"relearn":"Affirming that childfree is valid, with no 'you'll change your mind', lets her decide free of guilt.","persona":"Sneha","source":"reassure childfree"},
  {"id":"iw-070","cat":"fertility-for-real","type":"role-play","hook":"Your partner brushes off learning any fertility basics as 'her department'. You want to make it shared.","setup":"Make it shared:","yourLine":[{"text":"\"Fertility's a both-of-us thing, let's learn the basics together so we plan well.\"","best":true},{"text":"\"Yeah, that's really more your area.\""}],"relearn":"Framing fertility as a both-of-us thing corrects the 'her department' default and shares the planning.","persona":"Karthik","source":"shared learning"},
  {"id":"iw-071","cat":"fertility-for-real","type":"branch","hook":"An influencer post has you panicking that you've 'left it too late' at 33.","options":[{"text":"Step back and get calm, individual facts from a clinician","consequence":"You replace panic with real information.","outcome":"calm-facts","best":true},{"text":"Spiral and make a rushed decision from fear","consequence":"Calm individual facts from a clinician replace panic; a fear-driven rush makes a huge decision badly."}],"debrief":"Replace fertility panic with calm, individual facts from a clinician, not a rushed fear-decision.","relearn":"Get calm, personal facts from a clinician; don't let a scare post rush a huge decision.","persona":"Pooja","source":"calm not panic"},
  {"id":"iw-072","cat":"when-and-spacing","type":"role-play","hook":"Relatives keep asking when the 'second one' is coming. You want a light, firm reply.","setup":"Reply lightly:","yourLine":[{"text":"\"We'll decide if and when, on what's right for us, thanks for the love.\"","best":true},{"text":"\"Soon, I suppose, whenever they want.\""}],"relearn":"A light 'if and when, on what's right for us' holds your timing without conflict.","persona":"Pooja","source":"second-child reply"},
  {"id":"iw-073","cat":"when-and-spacing","type":"sort","hook":"Sort: a healthy input into timing, or pressure to ignore?","items":[{"id":"a","text":"Your own readiness and health"},{"id":"b","text":"A festival 'auspicious' deadline imposed on you"},{"id":"c","text":"Your partner's honest view"},{"id":"d","text":"Competing with a cousin's family"}],"bins":[{"id":"healthy","label":"Healthy input"},{"id":"ignore","label":"Pressure to ignore"}],"key":{"a":"healthy","b":"ignore","c":"healthy","d":"ignore"},"relearn":"Your readiness, health and partner's view are healthy inputs; imposed deadlines and competition are pressure.","persona":"any","source":"input vs pressure"},
  {"id":"iw-074","cat":"when-and-spacing","type":"match","hook":"Match each 'when' question to who it really belongs to.","pairs":[{"left":"Whether you're ready","right":"You and your partner"},{"left":"How to space children","right":"You, with health guidance"},{"left":"Your family size","right":"Your decision, not the relatives'"}],"relearn":"Readiness, spacing and family size all belong to the couple, informed by health, not to relatives.","persona":"any","source":"whose when"},
  {"id":"iw-075","cat":"if-its-hard","type":"role-play","hook":"Your partner feels like 'a failure' after a hard fertility result. You want to hold them.","setup":"Hold them gently:","yourLine":[{"text":"\"This isn't a failure and it isn't yours to carry alone, we face it together, with help.\"","best":true},{"text":"\"Maybe we just weren't meant to.\""}],"relearn":"Naming that it's not a failure and not theirs alone holds your partner and keeps you a team.","persona":"Karthik","source":"hold them"},
  {"id":"iw-076","cat":"if-its-hard","type":"branch","hook":"Treatment hasn't worked and you're exhausted, unsure whether to continue.","options":[{"text":"Make space to grieve, get honest counsel, and choose your next step without shame","consequence":"You decide from care, not pressure or false hope.","outcome":"compassionate","best":true},{"text":"Push on endlessly because stopping feels like 'giving up'","consequence":"Grief, honest counsel and a shame-free choice let you decide with care; endless pushing from 'never give up' can harm you."}],"debrief":"When treatment is hard, allow grief and honest counsel and choose your next step without shame.","relearn":"Allow grief and honest counsel; continuing or stopping treatment is a caring choice, not 'giving up'.","persona":"Reshma","source":"choose with care"},
  {"id":"iw-077","cat":"if-its-hard","type":"sort","hook":"Sort: a compassionate truth to hold onto, or a cruel myth to drop?","items":[{"id":"a","text":"Infertility is common and not your fault"},{"id":"b","text":"It's a punishment you deserve"},{"id":"c","text":"Family can take many whole forms"},{"id":"d","text":"You're 'less of a man or woman'"}],"bins":[{"id":"hold","label":"Compassionate truth"},{"id":"drop","label":"Cruel myth"}],"key":{"a":"hold","b":"drop","c":"hold","d":"drop"},"relearn":"'Common, not your fault' and 'family takes many forms' are truths to hold; punishment and 'less of a person' are cruel myths.","persona":"Reshma","source":"hold vs drop"},
  {"id":"iw-078","cat":"free-of-pressure","type":"role-play","hook":"An elder insists you 'must give the family an heir, ideally a son'. You want to answer with calm dignity.","setup":"Answer with dignity:","yourLine":[{"text":"\"We'll welcome any child equally, and whether and when is ours to decide.\"","best":true},{"text":"\"We'll keep trying for a boy then.\""}],"relearn":"A calm 'any child equally, ours to decide' rejects son-preference and holds your autonomy at once.","persona":"Razia","source":"heir pressure"},
  {"id":"iw-079","cat":"free-of-pressure","type":"branch","hook":"You're offered an illegal test to reveal the baby's sex, with hints to 'plan accordingly'.","options":[{"text":"Refuse it firmly; sex determination and selection are illegal and unjust","consequence":"You protect a daughter and obey the law.","outcome":"refused","best":true},{"text":"Go along quietly to keep the peace","consequence":"Refusing protects against sex selection and obeys the law; going along enables an illegal, unjust harm."}],"debrief":"Refuse prenatal sex determination and selection; they're illegal under the PCPNDT Act and deeply unjust.","relearn":"Refuse illegal sex determination and selection; the law and justice both forbid it.","persona":"Razia","source":"refuse sex selection"},
  {"id":"iw-080","cat":"free-of-pressure","type":"match","hook":"Match each form of pressure to what actually counters it.","pairs":[{"left":"Son-preference","right":"Valuing every child equally"},{"left":"'Good news' nagging","right":"A calm 'in our own time'"},{"left":"A weaponised fertility clock","right":"Your own informed timeline"}],"relearn":"Son-preference, nagging and a weaponised clock are each countered by equality, calm boundaries and your own timeline.","persona":"any","source":"countering pressure"},
  {"id":"iw-081","cat":"free-of-pressure","type":"spot","hook":"Spot the response that keeps the choice yours.","scene":[{"id":"a","text":"Holding your timeline kindly but firmly","trick":false},{"id":"b","text":"Conceiving on demand to silence relatives","trick":true},{"id":"c","text":"Refusing son-preference outright","trick":false}],"why":"Holding your timeline and refusing son-preference keep the choice yours; conceiving on demand surrenders it.","relearn":"Keep the choice yours: hold your timeline and refuse son-preference, don't conceive on demand.","persona":"Pooja","source":"keep it yours"},
  {"id":"iw-082","cat":"tools-and-help","type":"role-play","hook":"You want to agree with your partner how you'll handle all the outside pressure together.","setup":"Agree a shared front:","yourLine":[{"text":"\"Let's keep our decision between us, give everyone the same calm line, and lean on each other.\"","best":true},{"text":"\"Let's just tell people whatever they want to hear.\""}],"relearn":"A shared front, one calm line and leaning on each other keeps the pressure from splitting you.","persona":"Karthik","source":"shared front"},
  {"id":"iw-083","cat":"tools-and-help","type":"role-play","hook":"A worried younger relative asks you how to even start thinking about all this. You want to guide simply.","setup":"Guide her simply:","yourLine":[{"text":"\"Start with what you want, get honest facts, and remember it's your choice, no rush.\"","best":true},{"text":"\"Just do what the family expects.\""}],"relearn":"A simple 'your wants, honest facts, your choice, no rush' hands her the calm method, not the pressure.","persona":"Sneha","source":"guide simply"},
  {"id":"iw-084","cat":"tools-and-help","type":"sort","hook":"Sort: a trustworthy source for this decision, or one to be wary of?","items":[{"id":"a","text":"A qualified clinician"},{"id":"b","text":"A clinic promising guaranteed babies"},{"id":"c","text":"Public health services like RKSK"},{"id":"d","text":"Scare-driven social media"}],"bins":[{"id":"trust","label":"Trustworthy"},{"id":"wary","label":"Be wary"}],"key":{"a":"trust","b":"wary","c":"trust","d":"wary"},"relearn":"A clinician and public services like RKSK are trustworthy; 'guaranteed baby' clinics and scare media aren't.","persona":"any","source":"trust vs wary"},
];

export const IF_WHEN_WHETHER: V2GameConfig = {
  gameId: "if-when-whether",
  title: "If, When & Whether",
  greet: "Hey — it’s Sam. Whether to have children, when, and how many is one of life’s biggest decisions — and it’s yours and your partner’s, made with real knowledge and free of pressure in any direction. We’ll get honest, calm facts about fertility (for men and women), talk readiness and spacing on your own timeline, and hold infertility with compassion — it’s common and no one’s fault. Childfree is a complete life; so is parenthood. No ‘good news’ pressure, and no scare tactics. This is learning, not medical advice.",
  scenarios: SCENARIOS,
  categories: [
    { id: "whether-and-why", emoji: "🤔", label: "Whether & why" },
    { id: "fertility-for-real", emoji: "📅", label: "Fertility for real" },
    { id: "when-and-spacing", emoji: "⏳", label: "When & spacing" },
    { id: "if-its-hard", emoji: "💗", label: "If it’s hard" },
    { id: "free-of-pressure", emoji: "🕊️", label: "Free of pressure" },
    { id: "tools-and-help", emoji: "🧰", label: "Tools & help" },
  ],
  badge: {
    title: "If, When & Whether 🤰",
    blurb: "You know whether, when and how many children is your choice — childfree and parenthood are equally valid — made with calm, honest facts about fertility, on your own timeline. You can meet infertility with compassion, and resist pressure in any direction. 🕊️",
  },
  helpLine: "Whether, when and how many children you have is yours and your partner’s — free of pressure in any direction, and no one else’s ‘good news’ to demand. Fertility and preconception questions are best answered by a clinician; RKSK and public reproductive-health services can help. Sex selection is illegal in India under the PCPNDT Act. This is learning, not medical advice — a doctor can guide your specific situation.",
  helpLabel: "Find care · RKSK / a clinician",
  reassure: "Whether, when and how many children you have is yours to decide — free of pressure in any direction. Childfree is a complete life, and so is parenthood. If it’s proving hard, infertility is common (around 1 in 6 people, men and women roughly equally) and never a failing or a fault; real options exist, with no false hope and no shame. A clinician and RKSK/public services can guide you. 🕊️",
  reassureCats: ["free-of-pressure", "if-its-hard"],
};
