// Content for Looking After You (node g63, Parenthood, Chapter 8) — NEW v2 build to GDD 63 (mechanic-embodying),
// the parent's-OWN-wellbeing node and a HIGH-CARE one: you can't pour from an empty cup. 84 researched,
// India-grounded scenarios across empty-cup → your-needs-count → baby-blues-and-beyond → reach-out →
// healthy-coping → tools-and-help, each encoded as one of the shared v2 play actions (strike-rewrite / branch /
// reflect / sort / match / role-play / spot) — no binary "tap the right card". Lead: strike-rewrite (bust the
// myth), branch (your move), reflect. Six modes: the empty cup (spot burnout; busts "good parents sacrifice
// everything" — self-care is part of childcare, not selfish; struggling is not failing), your needs count
// (protect your needs, identity & a little time of your own without guilt; you're still a whole person), baby
// blues and beyond (normalise the common, passing baby blues AND recognise postpartum depression & anxiety — in
// yourself, a partner, and in FATHERS too; frightening intrusive thoughts treated as a SYMPTOM and a cue to get
// help, never a verdict), reach out (help-seeking is strength not weakness; build a support net; you needn't be in
// crisis to deserve help), healthy coping (safe strategies under load — rest, breathe, move, connect, accept help;
// unhealthy coping gently swapped out; NEVER any pain/discomfort technique), tools & help (a breathing space, a
// help-finder and crisis routing). HIGH-CARE and non-shaming: any sign of postnatal depression/anxiety, or any
// crisis, is met with warmth and an IMMEDIATE route to help (concern + resources); healthy coping only and
// explicitly NOT therapy — always signposting professional care; includes fathers and addresses joint-family
// pressure & stigma. Builds on Mind & Belonging (g49) and Bounce (g39); protects the parent so they can do
// everything else in Chapter 8. India: postpartum depression affects ~1 in 5 (about 22%) Indian mothers — nearly
// double the global average and badly under-recognised amid heavy expectations and stigma — and fathers can be
// affected too (~1 in 10); routes to Tele-MANAS 14416, KIRAN 1800-599-0019, a doctor, and emergency 112. gameId
// "looking-after-you".
import type { V2GameConfig, Scenario } from "./v2-schema";

const SCENARIOS: Scenario[] = [
  {"id":"ly-001","cat":"empty-cup","type":"strike-rewrite","hook":"\"A good parent sacrifices everything and needs nothing for themselves.\"","myth":{"un":"A good parent sacrifices everything and needs nothing for themselves.","re":"You can't pour from an empty cup; looking after yourself is part of looking after your child, not selfish.","why":"A depleted parent has less to give."},"relearn":"Self-care is part of childcare, not selfishness; an empty cup pours nothing.","persona":"Divya","source":"empty cup"},
  {"id":"ly-002","cat":"empty-cup","type":"strike-rewrite","hook":"\"Burnout is just normal tiredness you should push through.\"","myth":{"un":"Burnout is just normal tiredness you should push through.","re":"Parental burnout is real, ongoing exhaustion, detachment and feeling overwhelmed, and it's a signal to rest and get support, not push harder.","why":"Burnout is a signal, not a weakness."},"relearn":"Parental burnout is real and a signal to rest and get support, not just tiredness to push through.","persona":"Divya","source":"burnout is real"},
  {"id":"ly-003","cat":"empty-cup","type":"sort","hook":"Sort: a sign of parental burnout to take seriously, or ordinary busy-day tiredness?","items":[{"id":"a","text":"Feeling constantly drained and detached"},{"id":"b","text":"A single rough, sleepless night"},{"id":"c","text":"Dreading each day, nothing left to give"},{"id":"d","text":"Being tired after a long outing"}],"bins":[{"id":"burnout","label":"Burnout signal"},{"id":"ordinary","label":"Ordinary tiredness"}],"key":{"a":"burnout","b":"ordinary","c":"burnout","d":"ordinary"},"relearn":"Constant drain, detachment and dread are burnout signals; a single rough night or post-outing tiredness is ordinary.","persona":"any","source":"burnout vs tired"},
  {"id":"ly-004","cat":"empty-cup","type":"branch","hook":"You're running on empty but feel guilty even thinking about your own needs.","options":[{"text":"Treat refuelling yourself as part of caring for your child","consequence":"You give from a fuller, steadier place.","outcome":"refuel","best":true},{"text":"Keep draining yourself to prove devotion","consequence":"Refuelling lets you care from a fuller place; draining yourself to prove devotion leaves less for your child, not more."}],"debrief":"Caring for yourself refuels your capacity to parent; depleting yourself helps no one.","relearn":"Refuel yourself as part of caring for your child; self-depletion isn't devotion.","persona":"Divya","source":"refuel to give"},
  {"id":"ly-005","cat":"empty-cup","type":"match","hook":"Match each sign to what it's telling you.","pairs":[{"left":"Constant exhaustion and dread","right":"You're burning out, rest and get support"},{"left":"Snapping at everyone","right":"Your reserves are empty, refill them"},{"left":"Feeling numb to things you loved","right":"A signal to reach for help"}],"relearn":"Exhaustion, short temper and numbness are signals to rest, refill and reach for help, not to push harder.","persona":"any","source":"what signs tell you"},
  {"id":"ly-006","cat":"empty-cup","type":"reflect","hook":"Lensy: looking after yourself isn't taking away from your child; it's part of what you give them. Sit right?","prompt":"What do you think?","options":["Sits right","Part of giving","For them too"],"affirm":"Self-care isn't taken from your child; a steadier, refuelled parent is part of what you give them.","relearn":"Looking after yourself is part of what you give your child, not something taken from them.","persona":"any","source":"part of giving"},
  {"id":"ly-007","cat":"empty-cup","type":"spot","hook":"Spot the healthy response to running on empty.","scene":[{"id":"a","text":"Resting and accepting help when you can","trick":false},{"id":"b","text":"Pushing harder until you collapse","trick":true},{"id":"c","text":"Naming the burnout and reaching out","trick":false}],"why":"Resting, accepting help and reaching out are healthy; pushing to collapse harms you and the family.","relearn":"Meet burnout by resting, accepting help and reaching out, not by pushing to collapse.","persona":"Vikram","source":"healthy response"},
  {"id":"ly-008","cat":"empty-cup","type":"strike-rewrite","hook":"\"If I admit I'm struggling as a parent, I'm failing.\"","myth":{"un":"If I admit I'm struggling as a parent, I'm failing.","re":"Struggling is not failing; parenting is genuinely hard, and naming the struggle is the brave first step to coping.","why":"Honesty about struggle is strength."},"relearn":"Admitting you're struggling isn't failing; it's the brave first step toward getting the support you need.","persona":"Divya","source":"struggle isn't failing"},
  {"id":"ly-009","cat":"empty-cup","type":"branch","hook":"You haven't had a moment to yourself in so long you've stopped noticing how depleted you are.","options":[{"text":"Build in small, regular refills, even ten minutes, as a non-negotiable","consequence":"You stop the slow slide into burnout.","outcome":"refill","best":true},{"text":"Wait for a free day that never comes","consequence":"Small regular refills prevent the slide into burnout; waiting for a free day means never refilling at all."}],"debrief":"Protect small, regular refills for yourself; don't wait for a free day that never arrives.","relearn":"Build tiny regular refills in now; a depleted parent can't wait for a someday free day.","persona":"Divya","source":"small refills"},
  {"id":"ly-010","cat":"empty-cup","type":"reflect","hook":"Lensy: even the most devoted parent has limits, and respecting yours keeps you in the game. Land okay?","prompt":"What's your take?","options":["Lands okay","I have limits","Respect them"],"affirm":"Every parent has limits; respecting yours, rather than overriding them, is what keeps you going for your child.","relearn":"Even the most devoted parent has limits; respecting yours keeps you going.","persona":"any","source":"respect limits"},
  {"id":"ly-011","cat":"empty-cup","type":"sort","hook":"Sort: protects a parent from burnout, or speeds it up?","items":[{"id":"a","text":"Accepting help and sharing the load"},{"id":"b","text":"Doing everything alone, always"},{"id":"c","text":"Small daily moments of rest"},{"id":"d","text":"Guilt over any break"}],"bins":[{"id":"protects","label":"Protects you"},{"id":"speeds","label":"Speeds burnout"}],"key":{"a":"protects","b":"speeds","c":"protects","d":"speeds"},"relearn":"Accepting help and small rests protect you; doing it all alone and feeling guilty for breaks speed burnout.","persona":"any","source":"protect vs speed"},
  {"id":"ly-012","cat":"empty-cup","type":"branch","hook":"A fellow parent confides they're completely burnt out and ashamed of it.","options":[{"text":"Tell them it's common, not shameful, and help them find support","consequence":"They feel less alone and more able to act.","outcome":"supported","best":true},{"text":"Tell them everyone copes and to toughen up","consequence":"Naming burnout as common and helping them find support eases the shame; 'toughen up' deepens the isolation."}],"debrief":"Meet a burnt-out parent with 'it's common, not shameful' and help finding support, never 'toughen up'.","relearn":"Support a burnt-out parent with warmth and help, not 'everyone copes, toughen up'.","persona":"Priya","source":"support a parent"},
  {"id":"ly-013","cat":"your-needs-count","type":"strike-rewrite","hook":"\"Once you're a parent, your own needs and identity stop mattering.\"","myth":{"un":"Once you're a parent, your own needs and identity stop mattering.","re":"You're still a whole person with real needs and an identity; keeping them alive makes you a steadier parent.","why":"A self is the ground you parent from."},"relearn":"Your needs and identity still matter as a parent; keeping them alive makes you steadier, not selfish.","persona":"Divya","source":"you still matter"},
  {"id":"ly-014","cat":"your-needs-count","type":"sort","hook":"Sort: a legitimate parent's need, or a 'selfish' want to feel guilty about?","items":[{"id":"a","text":"Some sleep and rest"},{"id":"b","text":"A little time for yourself"},{"id":"c","text":"Adult connection and support"},{"id":"d","text":"Keeping one thing you love"}],"bins":[{"id":"need","label":"Legitimate need"},{"id":"guilt","label":"Nothing to feel guilty for"}],"key":{"a":"need","b":"guilt","c":"need","d":"guilt"},"relearn":"Rest, a little time, connection and a thing you love are all legitimate needs, none worth guilt.","persona":"any","source":"needs not guilt"},
  {"id":"ly-015","cat":"your-needs-count","type":"strike-rewrite","hook":"\"Taking any time for yourself makes you a bad, selfish parent.\"","myth":{"un":"Taking any time for yourself makes you a bad, selfish parent.","re":"A little time for yourself refills you and models healthy self-respect for your child; it's good parenting.","why":"Modelling self-respect teaches your child."},"relearn":"Taking a little time for yourself isn't selfish; it refills you and models self-respect for your child.","persona":"Divya","source":"time isn't selfish"},
  {"id":"ly-016","cat":"your-needs-count","type":"branch","hook":"You feel like you've vanished into 'just a parent' and miss who you were.","options":[{"text":"Reclaim small pieces of your own identity, bit by bit","consequence":"You feel like yourself again, and parent better for it.","outcome":"reclaim","best":true},{"text":"Accept that the old you is just gone for good","consequence":"Reclaiming small pieces brings you back; writing off the old you entirely deepens the loss and the depletion."}],"debrief":"Reclaim small pieces of your identity; the 'old you' isn't gone for good, and you parent better whole.","relearn":"Reclaim bits of who you are; you needn't accept that parenthood erased you for good.","persona":"Divya","source":"reclaim identity"},
  {"id":"ly-017","cat":"your-needs-count","type":"match","hook":"Match each small act to the need it meets.","pairs":[{"left":"Ten quiet minutes with chai","right":"A moment to breathe"},{"left":"A call with an old friend","right":"Adult connection"},{"left":"Twenty minutes on a hobby","right":"Keeping your own spark"}],"relearn":"Small acts, a quiet chai, a friend's call, a little hobby time, meet real needs that keep a parent whole.","persona":"any","source":"acts meet needs"},
  {"id":"ly-018","cat":"your-needs-count","type":"reflect","hook":"Lensy: your child benefits from a parent who is also still a person. Feel the truth of that?","prompt":"What do you think?","options":["I feel it","Still a person","True"],"affirm":"A child benefits from a parent who remains a whole person, not one who has erased themselves entirely.","relearn":"Your child benefits from a parent who's also still a whole person.","persona":"any","source":"still a person"},
  {"id":"ly-019","cat":"your-needs-count","type":"role-play","hook":"You want to ask your partner to cover so you can take an hour for yourself, without guilt. You ask.","setup":"Ask plainly:","yourLine":[{"text":"\"I need an hour to myself today to recharge, can you take over? It'll help me be a better parent too.\"","best":true},{"text":"\"Sorry to ask, ignore me if it's too much, I'll manage somehow.\""}],"relearn":"Asking plainly and guilt-free for what you need makes it likelier to happen and models healthy needs.","persona":"Divya","source":"ask without guilt"},
  {"id":"ly-020","cat":"your-needs-count","type":"spot","hook":"Spot what keeps a parent's own self alive.","scene":[{"id":"a","text":"Guarding a little time of your own","trick":false},{"id":"b","text":"Feeling you must be 'on' every hour","trick":true},{"id":"c","text":"Staying connected to who you are","trick":false}],"why":"Guarding a little time and staying connected to yourself keep you whole; being 'on' every hour erases you.","relearn":"Keep your self alive by guarding a little time and staying connected to who you are.","persona":"any","source":"self alive"},
  {"id":"ly-021","cat":"your-needs-count","type":"strike-rewrite","hook":"\"A parent's only job is the child; their own happiness is irrelevant.\"","myth":{"un":"A parent's only job is the child; their own happiness is irrelevant.","re":"A parent's wellbeing shapes the home and the child; your happiness matters in its own right and for them.","why":"Happy parents help raise happy kids."},"relearn":"Your happiness as a parent matters, both in itself and because it shapes the home your child grows up in.","persona":"Vikram","source":"your happiness matters"},
  {"id":"ly-022","cat":"your-needs-count","type":"branch","hook":"Relatives imply that wanting time or space makes you ungrateful for your child.","options":[{"text":"Hold that loving your child and having needs both fit","consequence":"You keep your needs without guilt.","outcome":"both-true","best":true},{"text":"Suppress your needs to seem grateful enough","consequence":"Holding that love and needs coexist keeps you whole; suppressing needs to look grateful drives you toward burnout."}],"debrief":"Loving your child and having your own needs both fit; you don't have to suppress one to prove the other.","relearn":"You can adore your child and still have needs; don't suppress them to seem grateful.","persona":"Priya","source":"both fit"},
  {"id":"ly-023","cat":"your-needs-count","type":"reflect","hook":"Lensy: needing rest, help and a self doesn't make you less of a parent; it makes you a sustainable one. Agree?","prompt":"What's your take?","options":["Agree","Sustainable","Not less"],"affirm":"Needing rest, help and a sense of self makes you a sustainable parent, not a lesser one.","relearn":"Needing rest, help and a self makes you a sustainable parent, not a worse one.","persona":"any","source":"sustainable parent"},
  {"id":"ly-024","cat":"your-needs-count","type":"sort","hook":"Sort: a healthy way to hold your identity as a parent, or one that erases you?","items":[{"id":"a","text":"Both devoted parent and your own person"},{"id":"b","text":"Only ever 'someone's mum or dad'"},{"id":"c","text":"Needs voiced and met sometimes"},{"id":"d","text":"Needs always last, forever"}],"bins":[{"id":"healthy","label":"Healthy"},{"id":"erases","label":"Erases you"}],"key":{"a":"healthy","b":"erases","c":"healthy","d":"erases"},"relearn":"Being both a devoted parent and your own person, with needs sometimes met, is healthy; total self-erasure isn't.","persona":"any","source":"hold identity"},
  {"id":"ly-025","cat":"baby-blues-and-beyond","type":"strike-rewrite","hook":"\"Any sadness after birth is just weakness you should hide.\"","myth":{"un":"Any sadness after birth is just weakness you should hide.","re":"Mild 'baby blues', tearfulness and mood swings in the first days, are very common and usually pass; they're not weakness.","why":"Early blues are a normal, passing wave."},"relearn":"Mild 'baby blues' in the first days are very common and usually pass; they're not weakness to hide.","persona":"Divya","source":"baby blues"},
  {"id":"ly-026","cat":"baby-blues-and-beyond","type":"strike-rewrite","hook":"\"Postnatal depression isn't real; new mothers just need to cheer up.\"","myth":{"un":"Postnatal depression isn't real; new mothers just need to cheer up.","re":"Postpartum depression and anxiety are real, common medical conditions, affecting around one in five mothers in India, and they need care, not 'cheer up'.","why":"It's an illness, not an attitude."},"relearn":"Postpartum depression and anxiety are real, common conditions needing care, not a 'cheer up'.","persona":"Divya","source":"PPD is real"},
  {"id":"ly-027","cat":"baby-blues-and-beyond","type":"sort","hook":"Sort: likely short-lived baby blues, or a sign to seek help for postnatal depression or anxiety?","items":[{"id":"a","text":"Tearful and up-and-down for a few days"},{"id":"b","text":"Low, hopeless or anxious for weeks"},{"id":"c","text":"Mood lifting as the first week passes"},{"id":"d","text":"Losing interest in the baby or yourself"}],"bins":[{"id":"blues","label":"Likely baby blues"},{"id":"help","label":"Seek help"}],"key":{"a":"blues","b":"help","c":"blues","d":"help"},"relearn":"A few up-and-down days that lift are likely blues; weeks of low or anxious mood or lost interest are signs to seek help.","persona":"Divya","source":"blues or help"},
  {"id":"ly-028","cat":"baby-blues-and-beyond","type":"match","hook":"Match each duration and depth to the gentle next step.","pairs":[{"left":"A few teary days that ease","right":"Rest and support; it usually passes"},{"left":"Low or anxious for two weeks or more","right":"Talk to a doctor or helpline"},{"left":"Frightening thoughts about self or baby","right":"Reach for help right away"}],"relearn":"How long and how deep the feelings run guides the step: rest for brief blues, help for lasting symptoms, urgent help for frightening thoughts.","persona":"Divya","source":"step by signs"},
  {"id":"ly-029","cat":"baby-blues-and-beyond","type":"strike-rewrite","hook":"\"Only mothers get depressed after a baby; fathers are unaffected.\"","myth":{"un":"Only mothers get depressed after a baby; fathers are unaffected.","re":"Fathers can develop postnatal depression too, around one in ten, so partners should watch out for and support each other.","why":"Both parents can be affected."},"relearn":"Fathers can get postnatal depression too (around one in ten); both partners should watch out for each other.","persona":"Vikram","source":"dads too"},
  {"id":"ly-030","cat":"baby-blues-and-beyond","type":"branch","hook":"For weeks you've felt low, anxious and disconnected from your baby, and you're scared to say so.","options":[{"text":"Tell someone you trust and a doctor or helpline; this is treatable","consequence":"You take the first step toward real help.","outcome":"help","best":true},{"text":"Hide it and hope it goes away on its own","consequence":"Telling someone and a professional opens treatment; hiding lasting symptoms lets a treatable condition deepen."}],"debrief":"Lasting low, anxious, disconnected feelings after birth are treatable; tell someone you trust and a professional.","relearn":"Reach out about lasting post-birth low mood; it's treatable, and hiding it only prolongs the pain.","persona":"Divya","source":"tell someone"},
  {"id":"ly-031","cat":"baby-blues-and-beyond","type":"spot","hook":"Spot the signs that say 'reach for help', gently.","scene":[{"id":"a","text":"Weeks of feeling low, anxious or numb","trick":true},{"id":"b","text":"A couple of teary days that pass","trick":false},{"id":"c","text":"Losing interest in the baby or in living","trick":true}],"why":"Weeks of low or numb feelings, or losing interest in the baby or in living, are signs to reach for help.","relearn":"Lasting low or numb feelings, or losing interest in the baby or in living, are gentle cues to reach for help.","persona":"Divya","source":"help signs"},
  {"id":"ly-032","cat":"baby-blues-and-beyond","type":"branch","hook":"You notice your partner has seemed hopeless and withdrawn for weeks since the birth.","options":[{"text":"Gently raise it and encourage support together; postnatal depression is treatable","consequence":"Your partner feels seen and less alone.","outcome":"seen","best":true},{"text":"Say nothing and assume they'll snap out of it","consequence":"Gently raising it and encouraging support helps; assuming they'll 'snap out of it' leaves a treatable illness unaddressed."}],"debrief":"If a partner seems hopeless and withdrawn for weeks after birth, gently raise it and encourage support together.","relearn":"Notice and gently support a partner's lasting post-birth low mood; don't wait for them to 'snap out of it'.","persona":"Vikram","source":"notice your partner"},
  {"id":"ly-033","cat":"baby-blues-and-beyond","type":"reflect","hook":"Lensy: postnatal depression and anxiety are common and treatable; spotting them early changes everything. Hear that?","prompt":"What do you think?","options":["I hear it","Common & treatable","Spot it early"],"affirm":"Postnatal depression and anxiety are common and treatable, and recognising them early makes recovery far more likely.","relearn":"Postnatal depression and anxiety are common and treatable; spotting them early changes everything.","persona":"Divya","source":"common and treatable"},
  {"id":"ly-034","cat":"baby-blues-and-beyond","type":"strike-rewrite","hook":"\"Having a dark or scary thought as a new parent makes you a monster.\"","myth":{"un":"Having a dark or scary thought as a new parent makes you a monster.","re":"Intrusive, frightening thoughts can come with postnatal anxiety and don't make you bad; they're a strong cue to get support quickly.","why":"A scary thought is a symptom, not a verdict."},"relearn":"Frightening intrusive thoughts can come with postnatal anxiety and don't make you bad; they're a cue to get support.","persona":"Divya","source":"thoughts not monster"},
  {"id":"ly-035","cat":"baby-blues-and-beyond","type":"branch","hook":"You're having frightening thoughts about harming yourself or the baby, and it terrifies you.","options":[{"text":"Reach out for help now, a doctor, a helpline, a trusted person","consequence":"You get support and safety quickly.","outcome":"reach-now","best":true},{"text":"Carry it alone in silence and shame","consequence":"Reaching out now brings support and safety; carrying frightening thoughts alone in shame is dangerous and unfair to you."}],"debrief":"Frightening thoughts of harm are a signal to reach out for help right away; you deserve support, not shame.","relearn":"If you have frightening thoughts of harm, reach for help now (a doctor, a helpline, a trusted person); you're not alone.","persona":"Divya","source":"reach now"},
  {"id":"ly-036","cat":"baby-blues-and-beyond","type":"reflect","hook":"Lensy: if it ever feels too heavy or frightening, that's exactly when reaching out matters most. Okay?","prompt":"What's your take?","options":["Okay","I'd reach out","Thank you"],"affirm":"When feelings become too heavy or frightening, reaching out for help is the most important and caring thing to do.","relearn":"When it feels too heavy or frightening, reaching out matters most; help is there and you deserve it.","persona":"Divya","source":"reach when heavy"},
  {"id":"ly-037","cat":"reach-out","type":"strike-rewrite","hook":"\"Asking for help with parenting or your mood means you're a weak parent.\"","myth":{"un":"Asking for help with parenting or your mood means you're a weak parent.","re":"Reaching out is a strength and a skill; the strongest parents build support and ask for help when they need it.","why":"Help-seeking is wisdom, not weakness."},"relearn":"Asking for help isn't weakness; it's a strength, and strong parents build support and reach out.","persona":"Divya","source":"help is strength"},
  {"id":"ly-038","cat":"reach-out","type":"sort","hook":"Sort: a real source of support to lean on, or a barrier to push past?","items":[{"id":"a","text":"A partner, friend or family who'll listen"},{"id":"b","text":"Shame about 'admitting' you struggle"},{"id":"c","text":"A doctor or a helpline"},{"id":"d","text":"The belief you must cope alone"}],"bins":[{"id":"support","label":"Lean on it"},{"id":"barrier","label":"Push past it"}],"key":{"a":"support","b":"barrier","c":"support","d":"barrier"},"relearn":"People who'll listen and professionals are support to lean on; shame and 'must cope alone' are barriers to push past.","persona":"any","source":"support vs barrier"},
  {"id":"ly-039","cat":"reach-out","type":"branch","hook":"You're struggling but the idea of telling anyone fills you with shame.","options":[{"text":"Tell one safe person, the shame shrinks once it's shared","consequence":"You break the isolation that makes it worse.","outcome":"shared","best":true},{"text":"Keep it hidden to protect your image","consequence":"Telling one safe person shrinks the shame; hiding it to protect an image keeps you isolated, which deepens the struggle."}],"debrief":"Tell one safe person; sharing shrinks the shame and breaks the isolation that makes struggle worse.","relearn":"Share with one safe person; hidden struggle and shame only grow in isolation.","persona":"Divya","source":"tell one person"},
  {"id":"ly-040","cat":"reach-out","type":"match","hook":"Match each part of a support net to what it offers.","pairs":[{"left":"Trusted people","right":"Everyday listening and practical help"},{"left":"A doctor or counsellor","right":"Assessment and treatment"},{"left":"A helpline (Tele-MANAS 14416)","right":"Support any time, including crises"}],"relearn":"Trusted people, professionals and helplines each offer real, different support; together they're a parent's net.","persona":"any","source":"support net"},
  {"id":"ly-041","cat":"reach-out","type":"strike-rewrite","hook":"\"There's no real help for struggling parents anyway, so why reach out.\"","myth":{"un":"There's no real help for struggling parents anyway, so why reach out.","re":"Real help exists, doctors, counsellors, helplines like Tele-MANAS 14416 and KIRAN 1800-599-0019, and it can genuinely turn things around.","why":"Support is closer than it feels."},"relearn":"Real help exists for struggling parents, doctors, counsellors and helplines, and it can genuinely turn things around.","persona":"any","source":"help exists"},
  {"id":"ly-042","cat":"reach-out","type":"reflect","hook":"Lensy: you weren't meant to do this alone; humans raise children in support networks, not in isolation. Resonate?","prompt":"What do you think?","options":["Resonates","Not alone","Build the net"],"affirm":"Parenting was never meant to be done in isolation; building and using a support network is how humans raise children.","relearn":"You weren't meant to parent alone; building a support network is how it's meant to work.","persona":"any","source":"not alone"},
  {"id":"ly-043","cat":"reach-out","type":"role-play","hook":"You want to reach out to a friend but don't know how to start. You open up.","setup":"Open up honestly:","yourLine":[{"text":"\"Can I be honest? I'm really struggling lately and I could use someone to talk to.\"","best":true},{"text":"\"Everything's great, just a bit tired, ignore me.\""}],"relearn":"An honest 'I'm struggling and could use someone' opens the door to the support you actually need.","persona":"Vikram","source":"open up"},
  {"id":"ly-044","cat":"reach-out","type":"spot","hook":"Spot the move that builds a parent's support.","scene":[{"id":"a","text":"Letting trusted people in","trick":false},{"id":"b","text":"Insisting you must cope alone","trick":true},{"id":"c","text":"Knowing a helpline you can call","trick":false}],"why":"Letting people in and knowing a helpline build support; insisting on coping alone removes it.","relearn":"Build support by letting trusted people in and knowing where to call, not by insisting on coping alone.","persona":"any","source":"build support"},
  {"id":"ly-045","cat":"reach-out","type":"branch","hook":"A parent friend brushes off real distress with 'I'm fine'. You sense they're not.","options":[{"text":"Gently let them know you're there and help is okay to want","consequence":"They know the door is open when ready.","outcome":"door-open","best":true},{"text":"Take 'I'm fine' at face value and move on","consequence":"Gently opening the door helps them reach out when ready; taking 'I'm fine' at face value can miss real distress."}],"debrief":"When a parent's 'I'm fine' rings hollow, gently let them know you're there and help is okay to want.","relearn":"Offer a gentle open door when a parent's 'I'm fine' seems hollow, rather than just moving on.","persona":"Priya","source":"open the door"},
  {"id":"ly-046","cat":"reach-out","type":"reflect","hook":"Lensy: the bravest, most loving thing a struggling parent can do is reach out. Sit right?","prompt":"What's your take?","options":["Sits right","Brave & loving","I would"],"affirm":"Reaching out when struggling is among the bravest and most loving things a parent can do, for themselves and their child.","relearn":"The bravest, most loving thing a struggling parent can do is reach out.","persona":"any","source":"bravest thing"},
  {"id":"ly-047","cat":"reach-out","type":"strike-rewrite","hook":"\"I should wait until I'm completely falling apart before I get help.\"","myth":{"un":"I should wait until I'm completely falling apart before I get help.","re":"You don't have to be in crisis to deserve support; reaching out early is easier and works better than waiting for collapse.","why":"Early help beats last-resort help."},"relearn":"You don't have to be falling apart to deserve help; reaching out early is easier and more effective.","persona":"any","source":"don't wait for crisis"},
  {"id":"ly-048","cat":"healthy-coping","type":"strike-rewrite","hook":"\"There's no healthy way to cope with this much stress, so why try.\"","myth":{"un":"There's no healthy way to cope with this much stress, so why try.","re":"Small healthy strategies, rest when you can, breathe, move, connect, accept help, genuinely lower the load and build over time.","why":"Tiny healthy habits add up."},"relearn":"Small healthy coping, rest, breathing, movement, connection, accepting help, genuinely eases the load over time.","persona":"any","source":"healthy coping works"},
  {"id":"ly-049","cat":"healthy-coping","type":"sort","hook":"Sort: a healthy way to cope under parenting load, or one that quietly harms you?","items":[{"id":"a","text":"Resting and accepting help"},{"id":"b","text":"Numbing out with too much alcohol"},{"id":"c","text":"A few slow breaths or a short walk"},{"id":"d","text":"Bottling it all up alone"}],"bins":[{"id":"healthy","label":"Healthy coping"},{"id":"harm","label":"Quietly harmful"}],"key":{"a":"healthy","b":"harm","c":"healthy","d":"harm"},"relearn":"Rest, accepting help, breathing and a short walk are healthy; numbing with alcohol or bottling up quietly harm you.","persona":"any","source":"healthy vs harm"},
  {"id":"ly-050","cat":"healthy-coping","type":"match","hook":"Match each load-moment to a healthy coping move.","pairs":[{"left":"Overwhelm rising","right":"Pause and take a few slow breaths"},{"left":"Touched out and tense","right":"Step away a moment if it's safe"},{"left":"Lonely and low","right":"Reach out to one person"}],"relearn":"Overwhelm, tension and loneliness each have a healthy move: breathe, take a safe pause, reach out.","persona":"any","source":"coping moves"},
  {"id":"ly-051","cat":"healthy-coping","type":"branch","hook":"You feel your stress spiking toward snapping at your child.","options":[{"text":"If it's safe, pause, breathe, and reset before responding","consequence":"You protect your child and model calm.","outcome":"pause","best":true},{"text":"Let the stress drive how you react","consequence":"Pausing to breathe and reset protects your child and models calm; letting stress drive the moment can cause harm and regret."}],"debrief":"When stress spikes, if it's safe, pause and breathe before you respond, protecting your child and yourself.","relearn":"Pause and reset when stress spikes near snapping; a breath protects both you and your child.","persona":"Vikram","source":"pause and breathe"},
  {"id":"ly-052","cat":"healthy-coping","type":"strike-rewrite","hook":"\"Coping means white-knuckling through and never showing strain.\"","myth":{"un":"Coping means white-knuckling through and never showing strain.","re":"Real coping is using supports and healthy habits and being honest about strain, not gritting your teeth alone.","why":"Sustainable coping is supported, not solo."},"relearn":"Coping isn't white-knuckling alone; it's using supports and healthy habits and being honest about strain.","persona":"Divya","source":"supported coping"},
  {"id":"ly-053","cat":"healthy-coping","type":"reflect","hook":"Lensy: you can't remove all the stress of parenting, but you can change how you carry it. Make sense?","prompt":"What do you think?","options":["Makes sense","How I carry it","I can do that"],"affirm":"You can't eliminate parenting stress, but healthy coping changes how you carry it, which is within your power.","relearn":"You can't remove all parenting stress, but you can change how you carry it.","persona":"any","source":"how you carry it"},
  {"id":"ly-054","cat":"healthy-coping","type":"spot","hook":"Spot the genuinely healthy coping strategy.","scene":[{"id":"a","text":"A few minutes of fresh air or breathing","trick":false},{"id":"b","text":"Skipping meals and sleep to cope","trick":true},{"id":"c","text":"Leaning on a friend or a routine","trick":false}],"why":"Fresh air, breathing and leaning on people or routines are healthy; skipping meals and sleep harms you further.","relearn":"Healthy coping refills you, fresh air, breathing, connection, rather than depriving you further.","persona":"any","source":"genuinely healthy"},
  {"id":"ly-055","cat":"healthy-coping","type":"branch","hook":"Your old way of coping was unhealthy, and under this load you feel it pulling at you.","options":[{"text":"Reach for a healthier swap and tell someone you trust","consequence":"You protect yourself with support, not willpower alone.","outcome":"swap","best":true},{"text":"Slip back into the harmful habit quietly","consequence":"A healthier swap with support protects you; slipping back into a harmful habit alone deepens the trouble."}],"debrief":"Under load, swap an unhealthy coping habit for a healthier one and tell someone, rather than relying on willpower alone.","relearn":"Swap a harmful coping habit for a healthier one and lean on support; don't white-knuckle it alone.","persona":"any","source":"healthier swap"},
  {"id":"ly-056","cat":"healthy-coping","type":"reflect","hook":"Lensy: even one small healthy habit, kept up, can steady a very hard season. Worth starting?","prompt":"What's your take?","options":["Worth it","One small habit","Starting"],"affirm":"Even a single small healthy habit, kept up, can meaningfully steady a parent through a very hard season.","relearn":"Even one small healthy habit, kept up, can steady a very hard season.","persona":"any","source":"one small habit"},
  {"id":"ly-057","cat":"healthy-coping","type":"sort","hook":"Sort: builds you back up under load, or wears you down further?","items":[{"id":"a","text":"Sleep when you can and good-enough food"},{"id":"b","text":"Endless doomscrolling at 3am"},{"id":"c","text":"A little movement and daylight"},{"id":"d","text":"Isolating from everyone"}],"bins":[{"id":"up","label":"Builds you up"},{"id":"down","label":"Wears you down"}],"key":{"a":"up","b":"down","c":"up","d":"down"},"relearn":"Sleep, food, a little movement and daylight build you up; doomscrolling and isolating wear you down.","persona":"any","source":"up vs down"},
  {"id":"ly-058","cat":"healthy-coping","type":"role-play","hook":"Your partner is fraying and you want to offer a healthy reset, not a lecture. You suggest one.","setup":"Offer gently:","yourLine":[{"text":"\"Why don't you take ten minutes outside to breathe, I've got things here, you'll feel a bit steadier.\"","best":true},{"text":"\"You just need to calm down and stop stressing.\""}],"relearn":"Offering a concrete, gentle reset and covering for them helps far more than telling them to 'calm down'.","persona":"Vikram","source":"offer a reset"},
  {"id":"ly-059","cat":"tools-and-help","type":"branch","hook":"You want something you can actually reach for on the hardest days.","options":[{"text":"Set up a tiny plan: a breathing space, one person to call, and a helpline saved","consequence":"Help is ready before you need it.","outcome":"ready","best":true},{"text":"Assume you'll figure it out in the moment","consequence":"A tiny plan readied in advance helps on the hardest days; figuring it out mid-crisis is far harder."}],"debrief":"Ready a tiny plan now, a breathing space, a person to call, a saved helpline, for the hardest days.","relearn":"Set up your supports before the hard day; a saved plan beats figuring it out in the moment.","persona":"Divya","source":"ready a plan"},
  {"id":"ly-060","cat":"tools-and-help","type":"match","hook":"Match each tool to what it's for.","pairs":[{"left":"A breathing or grounding space","right":"Calming an overwhelming moment"},{"left":"A help-finder and saved contacts","right":"Knowing where to turn fast"},{"left":"Crisis lines (Tele-MANAS 14416)","right":"Support any time, including emergencies"}],"relearn":"A grounding space, saved contacts and crisis lines are the core tools for a parent's hard moments.","persona":"any","source":"the toolkit"},
  {"id":"ly-061","cat":"tools-and-help","type":"strike-rewrite","hook":"\"An app or game can replace real treatment for depression.\"","myth":{"un":"An app or game can replace real treatment for depression.","re":"This offers gentle support and signposting, not therapy; postnatal depression and anxiety need real professional care.","why":"Support tools point to care; they don't replace it."},"relearn":"This game supports and signposts but isn't therapy; postnatal depression and anxiety need professional care.","persona":"any","source":"not therapy"},
  {"id":"ly-062","cat":"tools-and-help","type":"sort","hook":"Sort: a wise move when things feel very heavy, or one to avoid?","items":[{"id":"a","text":"Calling a helpline or doctor"},{"id":"b","text":"Waiting silently for it to pass"},{"id":"c","text":"Telling a trusted person now"},{"id":"d","text":"Deciding you're not 'bad enough' for help"}],"bins":[{"id":"wise","label":"Wise move"},{"id":"avoid","label":"To avoid"}],"key":{"a":"wise","b":"avoid","c":"wise","d":"avoid"},"relearn":"Calling a helpline or doctor and telling someone are wise; waiting silently or 'not bad enough' keep help away.","persona":"any","source":"wise vs avoid"},
  {"id":"ly-063","cat":"tools-and-help","type":"reflect","hook":"Lensy: knowing the number before you need it is a quiet act of self-care. Worth saving them now?","prompt":"What do you think?","options":["Worth it","Saving them","Good idea"],"affirm":"Saving crisis and support numbers before you need them is a simple, powerful act of looking after yourself.","relearn":"Knowing the helpline before you need it is a quiet, powerful act of self-care.","persona":"any","source":"save the number"},
  {"id":"ly-064","cat":"tools-and-help","type":"branch","hook":"You're not sure your struggle is 'serious enough' to call a helpline or see a doctor.","options":[{"text":"Reach out anyway, you don't have to be in crisis to deserve support","consequence":"You get help early, when it's easiest.","outcome":"early","best":true},{"text":"Talk yourself out of it until it's much worse","consequence":"Reaching out while unsure gets help early; talking yourself out of it until it worsens makes recovery harder."}],"debrief":"You don't have to be 'serious enough' or in crisis to call for support; reaching out early is valid and wise.","relearn":"Reach out even if unsure it's 'serious enough'; you needn't be in crisis to deserve support.","persona":"Divya","source":"reach out anyway"},
  {"id":"ly-065","cat":"tools-and-help","type":"match","hook":"Match a moment to the right India support.","pairs":[{"left":"Needing to talk, any time","right":"Tele-MANAS 14416 (mental health)"},{"left":"Wanting structured support","right":"KIRAN 1800-599-0019 / a doctor"},{"left":"Immediate danger to anyone","right":"Emergency 112, right away"}],"relearn":"Tele-MANAS, KIRAN and a doctor are there for support, and emergency 112 for immediate danger.","persona":"any","source":"right support"},
  {"id":"ly-066","cat":"tools-and-help","type":"spot","hook":"Spot the sustainable way to look after yourself as a parent.","scene":[{"id":"a","text":"Small daily self-care and a support net","trick":false},{"id":"b","text":"Ignoring yourself until you break","trick":true},{"id":"c","text":"Reaching for help early and often","trick":false}],"why":"Small daily self-care, a support net and early help are sustainable; ignoring yourself until you break isn't.","relearn":"Looking after yourself well is small daily care and early help, not ignoring yourself until you break.","persona":"any","source":"sustainable self-care"},
  {"id":"ly-067","cat":"tools-and-help","type":"reflect","hook":"Lensy: a well-looked-after parent is the foundation of a well-looked-after child. Feel the weight of that?","prompt":"What's your take?","options":["Feel it","Foundation","It matters"],"affirm":"Looking after yourself is foundational, not optional: a well parent is the ground a well child grows on.","relearn":"A well-looked-after parent is the foundation of a well-looked-after child.","persona":"any","source":"the foundation"},
  {"id":"ly-068","cat":"tools-and-help","type":"strike-rewrite","hook":"\"Once I'm coping a bit better, I can stop looking after myself again.\"","myth":{"un":"Once I'm coping a bit better, I can stop looking after myself again.","re":"Self-care is ongoing, not a one-time fix; keeping the small habits and supports is what stops you sliding back.","why":"Maintenance keeps the gains."},"relearn":"Self-care is ongoing, not a one-off; keeping small habits and supports is what prevents sliding back.","persona":"any","source":"ongoing care"},
  {"id":"ly-069","cat":"tools-and-help","type":"role-play","hook":"Your partner asks how you both can stay okay through the parenting years. You set the tone.","setup":"Set it together:","yourLine":[{"text":"\"Let's check on each other honestly, take turns to rest, and never be too proud to get help.\"","best":true},{"text":"\"Let's just power through and hope for the best.\""}],"relearn":"A shared tone of honest check-ins, shared rest and openness to help keeps both parents okay through the long haul.","persona":"Vikram","source":"set the tone"},
  {"id":"ly-070","cat":"empty-cup","type":"role-play","hook":"Your partner keeps insisting they're fine while clearly running on empty. You want to give them real permission to rest.","setup":"Give them permission:","yourLine":[{"text":"\"You don't have to earn rest, take a break, I've got things, you matter too.\"","best":true},{"text":"\"Push through, you'll be fine, we all are.\""}],"relearn":"Telling a depleted partner they don't have to earn rest, and covering for them, lets them actually refill.","persona":"Vikram","source":"permission to rest"},
  {"id":"ly-071","cat":"empty-cup","type":"sort","hook":"Sort: refills a depleted parent, or drains them further?","items":[{"id":"a","text":"A nap or a shared night off"},{"id":"b","text":"Saying yes to every demand"},{"id":"c","text":"A meal someone else cooks"},{"id":"d","text":"Skipping your own basic care"}],"bins":[{"id":"refill","label":"Refills you"},{"id":"drain","label":"Drains you more"}],"key":{"a":"refill","b":"drain","c":"refill","d":"drain"},"relearn":"Naps, a night off and being cooked for refill you; saying yes to everything and skipping your own care drain you.","persona":"any","source":"refill or drain"},
  {"id":"ly-072","cat":"your-needs-count","type":"role-play","hook":"A relative implies you're a bad mother for wanting an evening out. You want to hold your ground gently.","setup":"Hold it gently:","yourLine":[{"text":"\"Loving my child and needing a break both fit, this break helps me be a better parent.\"","best":true},{"text":"\"You're right, I shouldn't be so selfish.\""}],"relearn":"Naming that love and needs coexist holds your ground without guilt or a family fight.","persona":"Divya","source":"hold ground gently"},
  {"id":"ly-073","cat":"your-needs-count","type":"match","hook":"Match each parent need to why honouring it helps the child too.","pairs":[{"left":"Rest","right":"A calmer, more patient parent"},{"left":"Connection","right":"A less isolated, steadier parent"},{"left":"A little identity","right":"A parent who models a full life"}],"relearn":"Honouring rest, connection and identity makes you calmer, steadier and a fuller model, which helps your child.","persona":"Meena","source":"needs help kids"},
  {"id":"ly-074","cat":"baby-blues-and-beyond","type":"role-play","hook":"You think your partner may have postnatal depression and want to raise it with love, not alarm.","setup":"Raise it lovingly:","yourLine":[{"text":"\"I've noticed how heavy things feel for you lately, you're not alone, can we get some support together?\"","best":true},{"text":"\"Why can't you just be happy? We have a baby.\""}],"relearn":"A loving, non-alarming 'you're not alone, let's get support together' opens the door to help, not shame.","persona":"Vikram","source":"raise it lovingly"},
  {"id":"ly-075","cat":"baby-blues-and-beyond","type":"sort","hook":"Sort: a caring, accurate response to a struggling new parent, or a harmful one?","items":[{"id":"a","text":"'This is common and treatable, let's get help'"},{"id":"b","text":"'Snap out of it, others manage'"},{"id":"c","text":"'You're not alone, I'm here'"},{"id":"d","text":"'Good mothers don't feel this way'"}],"bins":[{"id":"caring","label":"Caring & accurate"},{"id":"harmful","label":"Harmful"}],"key":{"a":"caring","b":"harmful","c":"caring","d":"harmful"},"relearn":"'Common and treatable' and 'you're not alone' are caring; 'snap out of it' and 'good mothers don't' are harmful.","persona":"any","source":"caring vs harmful"},
  {"id":"ly-076","cat":"reach-out","type":"role-play","hook":"You finally decide to call a helpline but feel nervous about it. You picture how to start.","setup":"Just begin simply:","yourLine":[{"text":"\"Hi, I'm a new parent and I've been really struggling, I wasn't sure who else to talk to.\"","best":true},{"text":"\"Sorry, never mind, it's probably nothing, I'll hang up.\""}],"relearn":"A simple, honest opening is all a helpline needs; you don't have to have the words perfect to get support.","persona":"Divya","source":"call a helpline"},
  {"id":"ly-077","cat":"reach-out","type":"match","hook":"Match each worry about reaching out to the reassuring truth.","pairs":[{"left":"'I'll be judged'","right":"Helplines and doctors are there to support, not judge"},{"left":"'It's not bad enough'","right":"You don't have to be in crisis to call"},{"left":"'Nothing will help'","right":"Support genuinely changes things"}],"relearn":"Each worry about reaching out has a reassurance: no judgement, no threshold needed, and support that helps.","persona":"any","source":"worry to truth"},
  {"id":"ly-078","cat":"reach-out","type":"spot","hook":"Spot the strong, healthy move when you're struggling.","scene":[{"id":"a","text":"Telling a trusted person","trick":false},{"id":"b","text":"Hiding it to protect your image","trick":true},{"id":"c","text":"Calling a doctor or helpline","trick":false}],"why":"Telling someone and calling for support are strong, healthy moves; hiding to protect an image isn't.","relearn":"The strong move when struggling is to tell someone and reach for support, not to hide it.","persona":"any","source":"strong move"},
  {"id":"ly-079","cat":"healthy-coping","type":"role-play","hook":"A friend is coping with parenting stress in an unhealthy way. You want to steer them gently.","setup":"Steer gently:","yourLine":[{"text":"\"I get why you reach for that, want to try a walk or a chat with me instead next time?\"","best":true},{"text":"\"You're going to ruin your life doing that.\""}],"relearn":"A gentle, non-judging offer of a healthier alternative helps a friend far more than a harsh warning.","persona":"Priya","source":"steer gently"},
  {"id":"ly-080","cat":"healthy-coping","type":"sort","hook":"Sort: a coping habit that helps in the long run, or one that costs you later?","items":[{"id":"a","text":"Talking it out with someone"},{"id":"b","text":"Numbing out every night"},{"id":"c","text":"A short daily wind-down"},{"id":"d","text":"Running on caffeine and no sleep"}],"bins":[{"id":"helps","label":"Helps long-term"},{"id":"costs","label":"Costs you later"}],"key":{"a":"helps","b":"costs","c":"helps","d":"costs"},"relearn":"Talking it out and a daily wind-down help long-term; nightly numbing and no sleep cost you later.","persona":"any","source":"helps vs costs"},
  {"id":"ly-081","cat":"healthy-coping","type":"match","hook":"Match each hard feeling to a healthy first response.","pairs":[{"left":"Overwhelmed","right":"Slow your breath, drop your shoulders"},{"left":"Isolated","right":"Message one person"},{"left":"Wired and exhausted","right":"Rest your body even if sleep won't come"}],"relearn":"Overwhelm, isolation and wired exhaustion each have a gentle first response that steadies you.","persona":"any","source":"feeling to response"},
  {"id":"ly-082","cat":"tools-and-help","type":"role-play","hook":"You want to set up your phone so help is one tap away on a bad day. You tell your partner the plan.","setup":"Make it concrete:","yourLine":[{"text":"\"Let's save Tele-MANAS, our doctor and a couple of people, so on a bad day help is one tap away.\"","best":true},{"text":"\"We'll look up numbers if we ever really need them.\""}],"relearn":"Saving help contacts in advance means that on a bad day support is one tap away, not a frantic search.","persona":"Vikram","source":"one tap away"},
  {"id":"ly-083","cat":"tools-and-help","type":"role-play","hook":"Your partner asks how to know when it's time to actually get professional help. You answer warmly.","setup":"Answer warmly:","yourLine":[{"text":"\"If it's lasting weeks, getting heavier, or scaring you, that's the time, and sooner is always okay.\"","best":true},{"text":"\"Only when you absolutely can't function at all.\""}],"relearn":"A clear, warm threshold, lasting, heavier, or frightening, and sooner is okay, helps a partner act in time.","persona":"Divya","source":"when to get help"},
  {"id":"ly-084","cat":"tools-and-help","type":"spot","hook":"Spot the response that treats a parent's mental health as it deserves.","scene":[{"id":"a","text":"Meeting struggle with warmth and resources","trick":false},{"id":"b","text":"Telling them it's nothing, move on","trick":true},{"id":"c","text":"Helping them reach real care","trick":false}],"why":"Warmth-plus-resources and helping reach care treat mental health seriously; 'it's nothing' dismisses it.","relearn":"A parent's mental health deserves warmth and real resources, never 'it's nothing, move on'.","persona":"any","source":"treat it seriously"},
];

export const LOOKING_AFTER_YOU: V2GameConfig = {
  gameId: "looking-after-you",
  title: "Looking After You",
  greet: "Hey — it’s Lensy. You can’t pour from an empty cup. Self-care IS part of caring for your child, and struggling is not failing. Reaching out is strength.",
  scenarios: SCENARIOS,
  categories: [
    { id: "empty-cup", emoji: "☕", label: "The empty cup" },
    { id: "your-needs-count", emoji: "🌱", label: "Your needs count" },
    { id: "baby-blues-and-beyond", emoji: "🌧️", label: "Baby blues & beyond" },
    { id: "reach-out", emoji: "🤝", label: "Reach out" },
    { id: "healthy-coping", emoji: "🧘", label: "Healthy coping" },
    { id: "tools-and-help", emoji: "🧰", label: "Tools & help" },
  ],
  badge: {
    title: "Looking After You 🌿",
    blurb: "You know self-care is part of childcare, struggling isn’t failing, and baby blues differ from postpartum depression (real, treatable). Reaching out is strength.",
  },
  helpLine: "Struggling is not failing. Persistent low mood or scary thoughts are a treatable symptom, not a verdict. Tele-MANAS 14416, KIRAN 1800-599-0019, crisis 112.",
  helpLabel: "Get help · Tele-MANAS 14416 / 112",
  reassure: "Struggling isn’t failing. Persistent low mood or scary thoughts are a treatable symptom, not a verdict. Tele-MANAS 14416, KIRAN 1800-599-0019, crisis 112.",
  reassureCats: ["empty-cup", "baby-blues-and-beyond", "reach-out"],
};
