// Content for Mind Matters (node g38, ages 9–12, Chapter 3) — NEW v2 build to GDD 38 (mechanic-embodying),
// the mental-wellbeing game (Thread C). "Your mind matters too." 84 researched, India-grounded scenarios
// across six categories, each encoded as one of the shared v2 play actions (branch / strike-rewrite / sort /
// reflect / role-play / build / match) — no binary "tap the right card", led by the **coping chooser**
// (branch ×25 — decide a healthy response, see it help), the **build-your-toolkit** board (build), and
// de-stigmatising myth-flips (strike-rewrite). Teaches: the mind has health too, stress & pressure, handling
// rejection & setbacks (resilience), a personal toolkit of healthy coping moves, asking for help (the
// bravest skill), and being kind to your own mind (self-compassion). WELLBEING-SAFE: healthy coping only
// (breathe, talk, move, rest, problem-break — NO pain-based or risky 'tricks'); NEVER diagnoses or labels;
// NO harsh self-talk (actively replaces self-criticism with self-compassion); normalising, never alarmist;
// ALWAYS A WAY TO HELP — big/lasting feelings or dark thoughts route firmly to a trusted adult & Childline
// 1098 / 112. Builds on g01 (Feelings Friends); prereq g13; pairs with g39 (Bounce) & g41 (Heart Smart) and
// shares the coping-chooser / toolkit-builder. Rendered by the shared engine (components/games/v2-engine.tsx).
// gameId "mind-matters". DO NOT RENAME.

import type { Scenario, V2GameConfig } from "./v2-schema";

const SCENARIOS: Scenario[] = [
  // — Your mind matters too —
  {"id":"mm-001","cat":"mind-matters-too","type":"strike-rewrite","hook":"\"Only your body can be healthy or unwell, not your mind.\"","myth":{"un":"Only the body can be healthy or unwell.","re":"Your mind has health too, and it matters just as much.","why":"Mental health is part of being well."},"relearn":"Your mind has health too; it matters as much as your body.","persona":"any","source":"mental health literacy"},
  {"id":"mm-002","cat":"mind-matters-too","type":"strike-rewrite","hook":"\"Feeling down or worried means something is wrong with me.\"","myth":{"un":"Feeling down or worried means I'm broken.","re":"Everyone feels down or worried sometimes; it's part of being human.","why":"Ups and downs are normal, not a fault."},"relearn":"Everyone has ups and downs; difficult feelings are normal.","persona":"Aarav","source":"normalising"},
  {"id":"mm-003","cat":"mind-matters-too","type":"strike-rewrite","hook":"\"Big feelings last forever.\"","myth":{"un":"Once a hard feeling hits, it stays forever.","re":"Feelings rise, peak and pass, like weather.","why":"No feeling is permanent."},"relearn":"Hard feelings pass; they're like weather, not the climate.","persona":"any","source":"normalising"},
  {"id":"mm-004","cat":"mind-matters-too","type":"strike-rewrite","hook":"\"Caring for your mind is silly or a waste of time.\"","myth":{"un":"Looking after your mind is silly.","re":"Caring for your mind is as sensible as brushing your teeth.","why":"A cared-for mind helps with everything else."},"relearn":"Caring for your mind is sensible self-care, not silly.","persona":"any","source":"mental health literacy"},
  {"id":"mm-005","cat":"mind-matters-too","type":"reflect","hook":"Lensy: your mind works hard all day, thinking, feeling, learning. Deserves care?","prompt":"What do you think?","options":["Yes","It works so hard","I'll care for it"],"affirm":"A mind that's cared for feels steadier and stronger.","relearn":"Your hard-working mind deserves care and rest.","persona":"any","source":"mental health literacy"},
  {"id":"mm-006","cat":"mind-matters-too","type":"reflect","hook":"Lensy: how's your mind feeling today, honestly?","prompt":"Check in.","options":["Pretty good","A bit heavy","Up and down","Not sure"],"affirm":"Just checking in with yourself is a real mind-care skill.","relearn":"Checking in with how you feel is a healthy habit.","persona":"any","source":"self-awareness"},
  {"id":"mm-007","cat":"mind-matters-too","type":"reflect","hook":"Lensy: everyone, even the calmest-looking person, has tough days. Reassuring?","prompt":"What do you think?","options":["Yes","I'm not alone","Everyone struggles sometimes"],"affirm":"Tough days are part of every human life; you're not alone in them.","relearn":"Everyone has tough days; you're never alone in that.","persona":"any","source":"normalising"},
  {"id":"mm-008","cat":"mind-matters-too","type":"sort","hook":"Sort: a sign of a cared-for mind, or a neglected one?","items":[{"id":"a","text":"Enough sleep and rest"},{"id":"b","text":"Bottling everything up"},{"id":"c","text":"Talking about feelings"},{"id":"d","text":"Never taking a break"}],"bins":[{"id":"cared","label":"Cared-for mind"},{"id":"neglected","label":"Neglected mind"}],"key":{"a":"cared","b":"neglected","c":"cared","d":"neglected"},"relearn":"Rest and talking help the mind; bottling up and no breaks harm it.","persona":"any","source":"mind-care"},
  {"id":"mm-009","cat":"mind-matters-too","type":"sort","hook":"Sort: true or false about feelings?","items":[{"id":"a","text":"All feelings are allowed"},{"id":"b","text":"Some feelings make you bad"},{"id":"c","text":"Feelings give us useful information"},{"id":"d","text":"You should never feel sad"}],"bins":[{"id":"true","label":"True"},{"id":"false","label":"False"}],"key":{"a":"true","b":"false","c":"true","d":"false"},"relearn":"All feelings are allowed and informative; none make you 'bad'.","persona":"any","source":"emotional literacy (links g01)"},
  {"id":"mm-010","cat":"mind-matters-too","type":"sort","hook":"Sort: helps your mind, or just feels good for a second?","items":[{"id":"a","text":"A good night's sleep"},{"id":"b","text":"Hours of doomscrolling"},{"id":"c","text":"Time with people who care"},{"id":"d","text":"Comparing yourself online all day"}],"bins":[{"id":"helps","label":"Truly helps"},{"id":"empty","label":"Empty / hurts"}],"key":{"a":"helps","b":"empty","c":"helps","d":"empty"},"relearn":"Sleep and real connection help; endless scrolling and comparing drain you.","persona":"any","source":"mind-care"},
  {"id":"mm-011","cat":"mind-matters-too","type":"match","hook":"Match the part of you to its care.","pairs":[{"left":"Body","right":"Food, sleep, movement"},{"left":"Mind","right":"Rest, talking, calm"},{"left":"Both","right":"Kindness and care"}],"relearn":"Body and mind both need care; they work together.","persona":"Rohit","source":"mental health literacy"},
  {"id":"mm-012","cat":"mind-matters-too","type":"match","hook":"Match the feeling to what it might be telling you.","pairs":[{"left":"Worry","right":"Something matters to me"},{"left":"Sadness","right":"I've lost something"},{"left":"Anger","right":"Something feels unfair"}],"relearn":"Feelings carry useful messages worth listening to.","persona":"any","source":"emotional literacy"},
  // — Stress & pressure —
  {"id":"mm-013","cat":"stress-and-pressure","type":"branch","hook":"Exams are near and your chest feels tight with stress.","options":[{"text":"Pause, breathe slowly, and make a small study plan","consequence":"The stress eases enough to start.","outcome":"coped","best":true},{"text":"Panic and stare at everything at once","consequence":"A breath and a small plan calm the overwhelm."}],"debrief":"Stress shrinks when you breathe and break it into small steps.","relearn":"Breathe and break a big task into small steps to ease stress.","persona":"Aarav","source":"stress management"},
  {"id":"mm-014","cat":"stress-and-pressure","type":"branch","hook":"Everyone seems to be doing better than you, and it stings.","options":[{"text":"Remind yourself comparison isn't the full story; focus on your own steps","consequence":"You feel steadier and less behind.","outcome":"grounded","best":true},{"text":"Spiral into 'I'm the worst'","consequence":"Comparison shows a highlight reel, not the truth; focus on you."}],"debrief":"Comparison steals calm; your own progress is what counts.","relearn":"Don't measure yourself by others' highlight reels.","persona":"Diya","source":"comparison / stress"},
  {"id":"mm-015","cat":"stress-and-pressure","type":"branch","hook":"A parent says \"just study harder\" but you're already overwhelmed.","options":[{"text":"Calmly share that you're stressed and ask for support","consequence":"They understand better and help.","outcome":"supported","best":true},{"text":"Bottle it up and feel worse","consequence":"Telling someone how you really feel invites support."}],"debrief":"Naming stress to a caring adult turns pressure into support.","relearn":"You can tell a caring adult you're overwhelmed and ask for help.","persona":"Rohit","source":"stress / help-seeking"},
  {"id":"mm-016","cat":"stress-and-pressure","type":"branch","hook":"Stress is making it hard to sleep before a big day.","options":[{"text":"Wind down: screens off, slow breaths, calm routine","consequence":"Your body settles enough to rest.","outcome":"rested","best":true},{"text":"Scroll your phone in bed for hours","consequence":"A calm wind-down helps sleep more than scrolling."}],"debrief":"A calm wind-down routine helps a stressed mind rest.","relearn":"Wind down calmly, not on a screen, to sleep when stressed.","persona":"any","source":"stress / sleep"},
  {"id":"mm-017","cat":"stress-and-pressure","type":"branch","hook":"You have so much to do you don't know where to start.","options":[{"text":"Write it down and pick just the first small thing","consequence":"Starting small breaks the freeze.","outcome":"unstuck","best":true},{"text":"Avoid it all and feel guilty","consequence":"One small first step beats freezing under the pile."}],"debrief":"A big pile feels lighter once you start with one small step.","relearn":"Start with one small step when everything feels too much.","persona":"any","source":"stress / overwhelm"},
  {"id":"mm-018","cat":"stress-and-pressure","type":"sort","hook":"Sort: a sign your body shows when stressed, or not?","items":[{"id":"a","text":"Tight chest or tummy"},{"id":"b","text":"Growing taller instantly"},{"id":"c","text":"Racing heart"},{"id":"d","text":"Turning invisible"}],"bins":[{"id":"sign","label":"A stress sign"},{"id":"no","label":"Not a stress sign"}],"key":{"a":"sign","b":"no","c":"sign","d":"no"},"relearn":"Stress shows in the body, like a tight chest or racing heart.","persona":"any","source":"stress signals"},
  {"id":"mm-019","cat":"stress-and-pressure","type":"sort","hook":"Sort: eases stress, or adds to it?","items":[{"id":"a","text":"A short walk or play"},{"id":"b","text":"Skipping all sleep to cram"},{"id":"c","text":"Talking to a friend"},{"id":"d","text":"Telling yourself you'll fail"}],"bins":[{"id":"eases","label":"Eases stress"},{"id":"adds","label":"Adds stress"}],"key":{"a":"eases","b":"adds","c":"eases","d":"adds"},"relearn":"Movement and talking ease stress; no sleep and harsh self-talk add to it.","persona":"any","source":"stress management"},
  {"id":"mm-020","cat":"stress-and-pressure","type":"sort","hook":"Sort: a healthy amount of stress, or too much to handle alone?","items":[{"id":"a","text":"Butterflies before a test"},{"id":"b","text":"Feeling hopeless for weeks"},{"id":"c","text":"Nerves before a match"},{"id":"d","text":"Stress that never lets up"}],"bins":[{"id":"normal","label":"Normal, manageable"},{"id":"gethelp","label":"Time to get help"}],"key":{"a":"normal","b":"gethelp","c":"normal","d":"gethelp"},"relearn":"Some stress is normal; stress that won't lift means it's time to get help.","persona":"any","source":"stress / help-seeking"},
  {"id":"mm-021","cat":"stress-and-pressure","type":"strike-rewrite","hook":"\"Feeling stressed means you're weak.\"","myth":{"un":"Stress is a sign of weakness.","re":"Stress is a normal response to pressure that everyone feels.","why":"Even strong, capable people get stressed."},"relearn":"Stress is normal under pressure, not a sign of weakness.","persona":"Aarav","source":"stress / de-stigmatise"},
  {"id":"mm-022","cat":"stress-and-pressure","type":"strike-rewrite","hook":"\"Your marks decide your whole worth.\"","myth":{"un":"My exam marks decide how much I'm worth.","re":"Marks measure one test, not your value as a person.","why":"Your worth is far bigger than a score."},"relearn":"Exam marks measure a test, not your worth as a person.","persona":"Diya","source":"exam pressure / India"},
  {"id":"mm-023","cat":"stress-and-pressure","type":"strike-rewrite","hook":"\"You should be able to handle everything on your own.\"","myth":{"un":"I should handle all my stress completely alone.","re":"Everyone needs support sometimes; sharing the load is wise.","why":"No one copes with everything alone."},"relearn":"Sharing the load is wise; no one copes alone.","persona":"any","source":"stress / help-seeking"},
  {"id":"mm-024","cat":"stress-and-pressure","type":"reflect","hook":"Lensy: what's one thing that stresses you most right now?","prompt":"Name it (just to yourself).","options":["Exams","Friend stuff","Family stuff","Comparing myself"],"affirm":"Naming the stressor is the first step to handling it.","relearn":"Naming what stresses you helps you start to handle it.","persona":"any","source":"self-awareness"},
  {"id":"mm-025","cat":"stress-and-pressure","type":"reflect","hook":"Lensy: a little stress before something big is your body getting ready. Reframe it?","prompt":"What do you think?","options":["Yes","It's energy","Less scary now"],"affirm":"Some nerves are just your body powering up to do well.","relearn":"A little pre-event stress is your body getting ready.","persona":"any","source":"reframing"},
  {"id":"mm-026","cat":"stress-and-pressure","type":"branch","hook":"Pressure from everywhere is piling up and you feel close to tears.","options":[{"text":"Step away, breathe, and let the feeling out safely","consequence":"Releasing it gently helps you reset.","outcome":"regulated","best":true},{"text":"Push it all down and carry on","consequence":"Letting feelings out safely beats bottling them up."}],"debrief":"Letting a big feeling out safely is healthier than burying it.","relearn":"It's okay to step away and let big feelings out safely.","persona":"Aarav","source":"emotion regulation"},
  // — Handling rejection —
  {"id":"mm-027","cat":"handling-rejection","type":"branch","hook":"You weren't picked for the team and feel crushed.","options":[{"text":"Let yourself feel sad, then plan to try again or find another spot","consequence":"You honour the hurt and keep going.","outcome":"resilient","best":true},{"text":"Decide you're worthless at everything","consequence":"One 'no' isn't about your whole worth; feel it, then keep going."}],"debrief":"Rejection hurts and passes; it isn't a verdict on all of you.","relearn":"A rejection stings but isn't a verdict on your whole worth.","persona":"Aarav","source":"rejection / resilience"},
  {"id":"mm-028","cat":"handling-rejection","type":"branch","hook":"A friend didn't invite you to something and it really hurts.","options":[{"text":"Feel it, then check in kindly instead of assuming the worst","consequence":"You may learn it wasn't a snub at all.","outcome":"grounded","best":true},{"text":"Decide nobody likes you","consequence":"Check before concluding; one miss isn't 'nobody likes me'."}],"debrief":"One left-out moment isn't proof you're unliked.","relearn":"Being left out once isn't proof that no one likes you.","persona":"Diya","source":"rejection / thinking traps"},
  {"id":"mm-029","cat":"handling-rejection","type":"branch","hook":"You failed a test you studied hard for.","options":[{"text":"Be kind to yourself, then learn what to try differently","consequence":"You bounce back wiser.","outcome":"growth","best":true},{"text":"Call yourself stupid and give up","consequence":"Kindness plus a new plan beats harsh self-blame."}],"debrief":"A failure is information for next time, not proof you're 'stupid'.","relearn":"Treat a failure as a lesson, not a label.","persona":"any","source":"rejection / growth mindset"},
  {"id":"mm-030","cat":"handling-rejection","type":"branch","hook":"Someone you liked as a friend pulled away.","options":[{"text":"Let yourself be sad, lean on other friends, stay open","consequence":"You heal and keep your circle warm.","outcome":"resilient","best":true},{"text":"Shut everyone out","consequence":"Leaning on others helps more than shutting them out."}],"debrief":"Losing one connection doesn't mean closing all of them.","relearn":"When one friendship fades, lean on others; stay open.","persona":"Diya","source":"rejection / connection"},
  {"id":"mm-031","cat":"handling-rejection","type":"branch","hook":"You made a mistake in front of everyone and feel like hiding forever.","options":[{"text":"Remind yourself everyone messes up; let the moment pass","consequence":"The embarrassment fades faster than you fear.","outcome":"resilient","best":true},{"text":"Replay it forever and avoid people","consequence":"Embarrassment fades; everyone has these moments."}],"debrief":"Embarrassing moments pass; they feel bigger than they are.","relearn":"Everyone has cringe moments; they pass faster than you think.","persona":"any","source":"rejection / self-compassion"},
  {"id":"mm-032","cat":"handling-rejection","type":"branch","hook":"You keep dwelling on a disappointment from days ago.","options":[{"text":"Do one small kind or fun thing to shift the loop","consequence":"You gently break the rumination.","outcome":"unstuck","best":true},{"text":"Keep replaying it on repeat","consequence":"A small positive action can interrupt the dwelling."}],"debrief":"Dwelling deepens a rut; a small action helps you climb out.","relearn":"Break a dwelling loop with one small, kind action.","persona":"any","source":"rumination"},
  {"id":"mm-033","cat":"handling-rejection","type":"strike-rewrite","hook":"\"If someone rejects me, it means I'm not good enough.\"","myth":{"un":"Being rejected means I'm not good enough.","re":"Rejection often isn't about your worth at all.","why":"Many reasons have nothing to do with you."},"relearn":"Rejection usually isn't about your worth.","persona":"Diya","source":"rejection / cognitive"},
  {"id":"mm-034","cat":"handling-rejection","type":"strike-rewrite","hook":"\"Failing once means I'll always fail.\"","myth":{"un":"Failing once means I'll fail at everything forever.","re":"One setback doesn't decide your future.","why":"People grow and improve all the time."},"relearn":"One failure doesn't decide your future.","persona":"Aarav","source":"resilience"},
  {"id":"mm-035","cat":"handling-rejection","type":"strike-rewrite","hook":"\"I should never feel sad about being left out.\"","myth":{"un":"I shouldn't feel sad about being left out.","re":"It's natural to feel hurt; the feeling is allowed.","why":"Pretending not to care doesn't help."},"relearn":"It's natural and okay to feel hurt by being left out.","persona":"any","source":"emotional validation"},
  {"id":"mm-036","cat":"handling-rejection","type":"role-play","hook":"A friend is crushed after being rejected.","setup":"Comfort them. Say:","yourLine":[{"text":"\"That really hurts. I'm here, and it's not about your worth.\"","best":true},{"text":"\"Just get over it.\""}],"relearn":"You can comfort a friend by validating the hurt, not dismissing it.","persona":"any","source":"peer support"},
  {"id":"mm-037","cat":"handling-rejection","type":"role-play","hook":"You need to be kinder to yourself after a setback.","setup":"Talk to yourself like a friend. Say:","yourLine":[{"text":"\"That was hard. I'll be okay, and I can try again.\"","best":true},{"text":"\"I'm useless and always will be.\""}],"relearn":"Talk to yourself as kindly as you'd talk to a friend.","persona":"any","source":"self-compassion"},
  {"id":"mm-038","cat":"handling-rejection","type":"reflect","hook":"Lensy: think of a past disappointment you got through. Proof you can again?","prompt":"What do you think?","options":["Yes","I've bounced back before","I'm stronger than I feel"],"affirm":"You've survived hard things before; that's real evidence you can again.","relearn":"Remembering past bounce-backs reminds you that you can cope.","persona":"any","source":"resilience"},
  {"id":"mm-039","cat":"handling-rejection","type":"reflect","hook":"Lensy: a 'no' can sometimes point you to a better 'yes' later. Open to that?","prompt":"What do you think?","options":["Maybe","I hope so","New doors"],"affirm":"Some closed doors gently steer you to better ones.","relearn":"A rejection can sometimes open the way to something better.","persona":"any","source":"reframing"},
  {"id":"mm-040","cat":"handling-rejection","type":"sort","hook":"Sort: kind self-talk, or harsh self-talk?","items":[{"id":"a","text":"\"I'll be okay\""},{"id":"b","text":"\"I'm a total failure\""},{"id":"c","text":"\"I can try again\""},{"id":"d","text":"\"Everyone hates me\""}],"bins":[{"id":"kind","label":"Kind self-talk"},{"id":"harsh","label":"Harsh self-talk"}],"key":{"a":"kind","b":"harsh","c":"kind","d":"harsh"},"relearn":"Kind self-talk helps you recover; harsh self-talk keeps you stuck.","persona":"any","source":"self-talk"},
  // — Your mind-care toolkit —
  {"id":"mm-041","cat":"mind-care-toolkit","type":"build","hook":"Build your calm-down toolkit. Pick the healthy tools.","prompt":"Choose what belongs in a mind-care kit.","pieces":["slow breathing","talk to someone you trust","move your body","do something you enjoy"],"mode":"assemble","key":["slow breathing","talk to someone you trust","move your body","do something you enjoy"],"relearn":"A mind-care kit: breathe, talk, move, and do what you enjoy.","persona":"any","source":"coping toolkit"},
  {"id":"mm-042","cat":"mind-care-toolkit","type":"build","hook":"Build the steps of slow 'square' breathing.","prompt":"Put the calm-breathing steps in order.","pieces":["breathe in for four","hold for four","breathe out for four","pause for four"],"mode":"sequence","key":["breathe in for four","hold for four","breathe out for four","pause for four"],"relearn":"Slow square breathing calms your body: in, hold, out, pause.","persona":"any","source":"breathing technique"},
  {"id":"mm-043","cat":"mind-care-toolkit","type":"build","hook":"Build a wind-down routine for a hard day.","prompt":"Order a calming evening.","pieces":["finish screens early","do something soothing","slow breaths in bed","sleep"],"mode":"sequence","key":["finish screens early","do something soothing","slow breaths in bed","sleep"],"relearn":"A calming wind-down helps your mind rest after a hard day.","persona":"any","source":"sleep / routine"},
  {"id":"mm-044","cat":"mind-care-toolkit","type":"build","hook":"Build a 'shrink the problem' plan.","prompt":"Order how to handle something overwhelming.","pieces":["name the problem","break it into small parts","do the first small part","ask for help if stuck"],"mode":"sequence","key":["name the problem","break it into small parts","do the first small part","ask for help if stuck"],"relearn":"Shrink a big problem: name it, break it, start small, ask if stuck.","persona":"Aarav","source":"problem-solving"},
  {"id":"mm-045","cat":"mind-care-toolkit","type":"build","hook":"Build a quick mood-lifter list (healthy ones).","prompt":"Pick healthy mood-lifters.","pieces":["go outside","listen to music you love","play or move","spend time with someone kind"],"mode":"assemble","key":["go outside","listen to music you love","play or move","spend time with someone kind"],"relearn":"Healthy mood-lifters: nature, music, movement, kind company.","persona":"any","source":"behavioural activation"},
  {"id":"mm-046","cat":"mind-care-toolkit","type":"build","hook":"Build the 'name it to tame it' steps.","prompt":"Order how to handle a big feeling.","pieces":["notice the feeling","name it","breathe","choose what it needs"],"mode":"sequence","key":["notice the feeling","name it","breathe","choose what it needs"],"relearn":"Notice, name, breathe, then choose what the feeling needs.","persona":"any","source":"emotion regulation"},
  {"id":"mm-047","cat":"mind-care-toolkit","type":"build","hook":"Build a 'grounding' move for a panicky moment.","prompt":"Order a simple grounding step.","pieces":["feel your feet on the floor","name five things you see","take slow breaths","let the wave pass"],"mode":"sequence","key":["feel your feet on the floor","name five things you see","take slow breaths","let the wave pass"],"relearn":"Grounding (feet, look, breathe) helps a panicky moment pass.","persona":"any","source":"grounding technique"},
  {"id":"mm-048","cat":"mind-care-toolkit","type":"branch","hook":"A wave of worry hits before bed.","options":[{"text":"Use slow breathing and a calming thought","consequence":"Your body settles and the wave passes.","outcome":"calm","best":true},{"text":"Lie there letting worries spiral","consequence":"Slow breathing helps the worry wave pass."}],"debrief":"Breathing tools turn down the volume on worry.","relearn":"Slow breathing helps a worry wave settle.","persona":"any","source":"coping in action"},
  {"id":"mm-049","cat":"mind-care-toolkit","type":"branch","hook":"You feel a big feeling building in class.","options":[{"text":"Quietly breathe and ground yourself until it eases","consequence":"You ride it out calmly.","outcome":"regulated","best":true},{"text":"Let it explode or freeze","consequence":"A quiet grounding move helps you ride the feeling out."}],"debrief":"You can use a calm tool even in the middle of class.","relearn":"You can quietly use a calming tool wherever you are.","persona":"any","source":"coping in action"},
  {"id":"mm-050","cat":"mind-care-toolkit","type":"branch","hook":"You've had a heavy day and don't know what you need.","options":[{"text":"Try one toolkit tool, rest, a walk, or a chat","consequence":"You give your mind what it needs.","outcome":"cared","best":true},{"text":"Numb out on screens for hours","consequence":"A real toolkit tool helps more than numbing out."}],"debrief":"On a heavy day, one caring tool beats numbing out.","relearn":"Reach for a real coping tool on a heavy day.","persona":"any","source":"coping in action"},
  {"id":"mm-051","cat":"mind-care-toolkit","type":"branch","hook":"Anger is rising fast and you might say something you'll regret.","options":[{"text":"Step away and breathe before responding","consequence":"You cool down and avoid harm.","outcome":"regulated","best":true},{"text":"Lash out right away","consequence":"A pause and a breath prevent regret."}],"debrief":"A pause when angry protects you and others.","relearn":"Step away and breathe before acting on anger.","persona":"Aarav","source":"anger management (links g41)"},
  {"id":"mm-052","cat":"mind-care-toolkit","type":"sort","hook":"Sort: a healthy coping tool, or an unhealthy one?","items":[{"id":"a","text":"Talking to someone you trust"},{"id":"b","text":"Taking it out on others"},{"id":"c","text":"Moving your body"},{"id":"d","text":"Hiding from everyone for days"}],"bins":[{"id":"healthy","label":"Healthy"},{"id":"unhealthy","label":"Unhealthy"}],"key":{"a":"healthy","b":"unhealthy","c":"healthy","d":"unhealthy"},"relearn":"Talking and moving help; lashing out and total isolation don't.","persona":"any","source":"coping"},
  {"id":"mm-053","cat":"mind-care-toolkit","type":"sort","hook":"Sort: calms the body, or revs up the stress?","items":[{"id":"a","text":"Slow, deep breaths"},{"id":"b","text":"Holding your breath in panic"},{"id":"c","text":"A gentle walk"},{"id":"d","text":"Endless worried scrolling"}],"bins":[{"id":"calms","label":"Calms the body"},{"id":"revs","label":"Revs up stress"}],"key":{"a":"calms","b":"revs","c":"calms","d":"revs"},"relearn":"Slow breaths and gentle movement calm the body.","persona":"any","source":"coping"},
  {"id":"mm-054","cat":"mind-care-toolkit","type":"sort","hook":"Sort: which tool fits, in-the-moment calm, or longer-term care?","items":[{"id":"a","text":"Square breathing right now"},{"id":"b","text":"Getting enough sleep daily"},{"id":"c","text":"Grounding during a panic"},{"id":"d","text":"Regular time with friends"}],"bins":[{"id":"now","label":"In-the-moment"},{"id":"longterm","label":"Longer-term care"}],"key":{"a":"now","b":"longterm","c":"now","d":"longterm"},"relearn":"Some tools calm you now; others keep your mind well over time.","persona":"any","source":"coping"},
  {"id":"mm-055","cat":"mind-care-toolkit","type":"match","hook":"Match the feeling to a helpful tool.","pairs":[{"left":"Panic","right":"Grounding and breathing"},{"left":"Sadness","right":"Talk to someone kind"},{"left":"Restlessness","right":"Move your body"}],"relearn":"Different feelings respond to different healthy tools.","persona":"any","source":"coping"},
  {"id":"mm-056","cat":"mind-care-toolkit","type":"match","hook":"Match the tool to what it does.","pairs":[{"left":"Slow breathing","right":"Calms the body"},{"left":"Talking it out","right":"Lightens the load"},{"left":"Movement","right":"Shifts the mood"}],"relearn":"Each coping tool helps your mind in its own way.","persona":"any","source":"coping"},
  // — Asking for help —
  {"id":"mm-057","cat":"ask-for-help","type":"role-play","hook":"A feeling is too big to handle alone.","setup":"Reach out. Say:","yourLine":[{"text":"\"I'm not okay right now, can we talk?\"","best":true},{"text":"Say nothing and struggle alone"}],"relearn":"You can tell a trusted person 'I'm not okay, can we talk?'.","persona":"any","source":"help-seeking"},
  {"id":"mm-058","cat":"ask-for-help","type":"role-play","hook":"You want to tell a parent you've been feeling low.","setup":"Open up simply. Say:","yourLine":[{"text":"\"I've been feeling really low lately, I need some help.\"","best":true},{"text":"\"Nothing's wrong\" (when something is)"}],"relearn":"You can name a low mood and ask a parent for help.","persona":"Rohit","source":"help-seeking"},
  {"id":"mm-059","cat":"ask-for-help","type":"role-play","hook":"A friend confides they feel really down.","setup":"Support and guide them. Say:","yourLine":[{"text":"\"Thank you for telling me. Let's also talk to an adult who can help.\"","best":true},{"text":"\"Don't tell anyone, just forget it.\""}],"relearn":"Support a struggling friend and help them reach a trusted adult.","persona":"Asha","source":"peer support / help-routing"},
  {"id":"mm-060","cat":"ask-for-help","type":"role-play","hook":"You're nervous to ask the school counsellor for help.","setup":"Take the step. Say:","yourLine":[{"text":"\"Can I talk to you about something that's bothering me?\"","best":true},{"text":"Walk away and keep it in"}],"relearn":"A counsellor is there to help; you can simply ask to talk.","persona":"any","source":"help-seeking"},
  {"id":"mm-061","cat":"ask-for-help","type":"role-play","hook":"Someone says talking about feelings is 'for the weak'.","setup":"Reframe it. Say:","yourLine":[{"text":"\"Asking for help is actually strong.\"","best":true},{"text":"\"You're right, I'll keep quiet.\""}],"relearn":"You can push back on the idea that help-seeking is weak.","persona":"Aarav","source":"de-stigmatise"},
  {"id":"mm-062","cat":"ask-for-help","type":"branch","hook":"Heavy feelings have lasted a long time and won't lift.","options":[{"text":"Tell a trusted adult; ask them to help you find support","consequence":"You get the care you need.","outcome":"supported","best":true},{"text":"Keep waiting for it to pass alone","consequence":"Long-lasting heavy feelings deserve a trusted adult's help."}],"debrief":"Feelings that stay heavy for a long time are a sign to get help.","relearn":"If heavy feelings last, tell a trusted adult and get support.","persona":"any","source":"help-seeking / safety"},
  {"id":"mm-063","cat":"ask-for-help","type":"branch","hook":"You don't know who's safe to talk to about your feelings.","options":[{"text":"Pick any trusted adult, or call Childline 1098 / 112","consequence":"You find a caring first listener.","outcome":"resourceful","best":true},{"text":"Decide there's no one","consequence":"There's always someone, a trusted adult or Childline 1098."}],"debrief":"There's always somewhere to turn, including Childline 1098.","relearn":"A trusted adult or Childline 1098 is always there to listen.","persona":"Asha","source":"help-seeking / helpline"},
  {"id":"mm-064","cat":"ask-for-help","type":"branch","hook":"You told one adult and they brushed it off.","options":[{"text":"Tell another trusted adult; keep going until you're heard","consequence":"Someone listens and helps.","outcome":"persistent","best":true},{"text":"Give up on getting help","consequence":"If one adult misses it, tell another, don't give up."}],"debrief":"If the first person doesn't hear you, tell someone else.","relearn":"Keep reaching out until a trusted adult really listens.","persona":"any","source":"help-seeking / persistence"},
  {"id":"mm-065","cat":"ask-for-help","type":"branch","hook":"A friend hints they're having scary or very dark thoughts.","options":[{"text":"Take it seriously and tell a trusted adult right away","consequence":"You help keep your friend safe.","outcome":"caring","best":true},{"text":"Keep it a secret because they asked","consequence":"For safety, this is a 'tell a trusted adult now' moment."}],"debrief":"Some worries are too big to hold alone, telling an adult keeps a friend safe.","relearn":"If a friend has dark thoughts, tell a trusted adult right away.","persona":"Asha","source":"safeguarding / help-routing"},
  {"id":"mm-066","cat":"ask-for-help","type":"strike-rewrite","hook":"\"Asking for help with feelings is shameful.\"","myth":{"un":"Asking for help with my feelings is shameful.","re":"Reaching out is brave and a sign of strength.","why":"Everyone needs support sometimes."},"relearn":"Reaching out for help is brave, not shameful.","persona":"Aarav","source":"de-stigmatise"},
  {"id":"mm-067","cat":"ask-for-help","type":"strike-rewrite","hook":"\"Counsellors and helplines are only for 'crazy' people.\"","myth":{"un":"Counsellors and helplines are only for 'crazy' people.","re":"They're for anyone who needs a listening ear or support.","why":"Getting support is normal and healthy."},"relearn":"Counsellors and helplines are for anyone who needs support.","persona":"any","source":"de-stigmatise"},
  {"id":"mm-068","cat":"ask-for-help","type":"strike-rewrite","hook":"\"Talking about a problem won't change anything.\"","myth":{"un":"Talking about a problem is pointless.","re":"Sharing a worry often makes it lighter and clearer.","why":"A problem shared is a problem halved."},"relearn":"Talking about a worry can make it lighter and clearer.","persona":"any","source":"help-seeking"},
  {"id":"mm-069","cat":"ask-for-help","type":"match","hook":"Match the situation to where to turn.","pairs":[{"left":"A worry at school","right":"A teacher or counsellor"},{"left":"Feelings at home","right":"A trusted family adult"},{"left":"An urgent crisis","right":"Childline 1098 / 112"}],"relearn":"Different worries have a right person or helpline to turn to.","persona":"Asha","source":"help-routing / UNESCO 5.5"},
  {"id":"mm-070","cat":"ask-for-help","type":"match","hook":"Match: myth about help, to the truth.","pairs":[{"left":"\"Help is for the weak\"","right":"Help is for everyone"},{"left":"\"I'll be a burden\"","right":"People want to help"},{"left":"\"Nothing will help\"","right":"Support really does help"}],"relearn":"The fears that stop us asking for help are usually untrue.","persona":"any","source":"de-stigmatise"},
  // — Be kind to your mind —
  {"id":"mm-071","cat":"be-kind-to-mind","type":"branch","hook":"You catch yourself thinking \"I'm so stupid\" after a mistake.","options":[{"text":"Swap it for what you'd tell a friend: \"that's okay, try again\"","consequence":"Kind self-talk softens the blow.","outcome":"self-kind","best":true},{"text":"Repeat 'I'm stupid' all day","consequence":"Talk to yourself like a friend, not a critic."}],"debrief":"Be as kind to yourself as you'd be to a good friend.","relearn":"Replace harsh self-talk with what you'd tell a friend.","persona":"any","source":"self-compassion"},
  {"id":"mm-072","cat":"be-kind-to-mind","type":"branch","hook":"You're tempted to skip rest and push through exhaustion.","options":[{"text":"Let yourself rest; rest is productive too","consequence":"You recharge and do better after.","outcome":"balanced","best":true},{"text":"Push till you crash","consequence":"Rest isn't lazy; it's part of doing well."}],"debrief":"Rest is part of looking after your mind, not a weakness.","relearn":"Rest is productive and part of mind-care.","persona":"any","source":"rest / balance"},
  {"id":"mm-073","cat":"be-kind-to-mind","type":"branch","hook":"You feel guilty for taking time to do something you enjoy.","options":[{"text":"Allow it; joy refuels your mind","consequence":"You return lighter and steadier.","outcome":"balanced","best":true},{"text":"Feel you must always be 'productive'","consequence":"Joy and downtime are fuel, not waste."}],"debrief":"Doing things you enjoy is real mind-care, not slacking.","relearn":"Enjoyable downtime refuels your mind; it's not slacking.","persona":"any","source":"self-care"},
  {"id":"mm-074","cat":"be-kind-to-mind","type":"branch","hook":"A classmate is being teased for seeing a counsellor.","options":[{"text":"Stand up: \"getting help is smart, leave them alone\"","consequence":"You reduce the stigma for everyone.","outcome":"ally","best":true},{"text":"Join the teasing","consequence":"Defending help-seeking makes it safer for everyone."}],"debrief":"Standing up for help-seekers reduces mental-health stigma.","relearn":"Defend people who seek help; it's smart, not shameful.","persona":"any","source":"de-stigmatise / upstander (links g19)"},
  {"id":"mm-075","cat":"be-kind-to-mind","type":"branch","hook":"Your inner voice is being a harsh critic today.","options":[{"text":"Notice it and gently talk back with kindness","consequence":"You loosen the critic's grip.","outcome":"self-kind","best":true},{"text":"Believe every harsh thought","consequence":"You don't have to believe every harsh thought."}],"debrief":"You can notice harsh thoughts without believing them.","relearn":"You don't have to believe every harsh thought you have.","persona":"any","source":"cognitive defusion"},
  {"id":"mm-076","cat":"be-kind-to-mind","type":"strike-rewrite","hook":"\"Being hard on myself makes me do better.\"","myth":{"un":"Being harsh with myself pushes me to do better.","re":"Self-kindness helps you grow more than harshness.","why":"Cruelty drains you; encouragement fuels you."},"relearn":"Self-kindness helps you improve more than self-criticism.","persona":"any","source":"self-compassion"},
  {"id":"mm-077","cat":"be-kind-to-mind","type":"strike-rewrite","hook":"\"I have to be happy and positive all the time.\"","myth":{"un":"I must feel happy and positive all the time.","re":"All feelings are okay; you don't have to fake being fine.","why":"Forcing happiness ignores real feelings."},"relearn":"You don't have to be happy all the time; all feelings are okay.","persona":"any","source":"emotional honesty"},
  {"id":"mm-078","cat":"be-kind-to-mind","type":"strike-rewrite","hook":"\"Other people's feelings matter more than mine.\"","myth":{"un":"My feelings matter less than everyone else's.","re":"Your feelings matter just as much as anyone's.","why":"You deserve care too."},"relearn":"Your feelings matter just as much as anyone else's.","persona":"Diya","source":"self-worth"},
  {"id":"mm-079","cat":"be-kind-to-mind","type":"reflect","hook":"Lensy: name one kind thing you could say to yourself today.","prompt":"Pick one.","options":["\"I'm doing my best\"","\"I'm allowed to rest\"","\"I'll be okay\""],"affirm":"Saying it counts; your mind hears your kindness.","relearn":"A kind word to yourself genuinely helps your mind.","persona":"any","source":"self-compassion"},
  {"id":"mm-080","cat":"be-kind-to-mind","type":"reflect","hook":"Lensy: what's one small thing that reliably lifts your mood?","prompt":"Think of one.","options":["A favourite song","Time outside","A chat with someone","A hobby"],"affirm":"Keep that close, it's a tool you can use any time.","relearn":"Knowing your reliable mood-lifters gives you a ready tool.","persona":"any","source":"self-care"},
  {"id":"mm-081","cat":"be-kind-to-mind","type":"role-play","hook":"A friend is being very hard on themselves.","setup":"Offer kindness. Say:","yourLine":[{"text":"\"Be kind to yourself, you'd forgive a friend for this.\"","best":true},{"text":"\"Yeah, you did mess up.\""}],"relearn":"You can help a friend be kinder to themselves.","persona":"any","source":"self-compassion / peer"},
  {"id":"mm-082","cat":"be-kind-to-mind","type":"sort","hook":"Sort: kind-to-your-mind, or hard-on-your-mind?","items":[{"id":"a","text":"Resting when tired"},{"id":"b","text":"Never forgiving a mistake"},{"id":"c","text":"Celebrating small wins"},{"id":"d","text":"Comparing yourself non-stop"}],"bins":[{"id":"kind","label":"Kind to your mind"},{"id":"hard","label":"Hard on your mind"}],"key":{"a":"kind","b":"hard","c":"kind","d":"hard"},"relearn":"Rest and celebrating wins are kind; non-stop comparison is hard.","persona":"any","source":"self-care"},
  {"id":"mm-083","cat":"be-kind-to-mind","type":"build","hook":"Build your personal mind-care promise.","prompt":"Pick promises to your own mind.","pieces":["I'll rest when I need to","I'll talk to someone when it's heavy","I'll be kind to myself","I'll ask for help if it's too big"],"mode":"assemble","key":["I'll rest when I need to","I'll talk to someone when it's heavy","I'll be kind to myself","I'll ask for help if it's too big"],"relearn":"Your mind-care promise: rest, talk, be kind, and ask for help.","persona":"any","source":"consolidation"},
  {"id":"mm-084","cat":"be-kind-to-mind","type":"reflect","hook":"Lensy: biggest take-away from Mind Matters?","prompt":"Pick your motto.","options":["My mind matters","Feelings pass","I have tools","Asking for help is strong"],"affirm":"Your mind matters, you have tools, and help is always there.","relearn":"Your mind matters, feelings pass, you have tools, and help is strong.","persona":"any","source":"consolidation"},
];

export const MIND_MATTERS: V2GameConfig = {
  gameId: "mind-matters",
  title: "Mind Matters",
  greet: "Hey, it's Lensy. 🧠 Your mind matters as much as your body. Let's talk stress, bouncing back, and the tools that help — plus how asking for help is brave.",
  scenarios: SCENARIOS,
  categories: [
    { id: "mind-matters-too", emoji: "🧠", label: "Mind matters too" },
    { id: "stress-and-pressure", emoji: "🌪️", label: "Stress & pressure" },
    { id: "handling-rejection", emoji: "🌧️", label: "Handling rejection" },
    { id: "mind-care-toolkit", emoji: "🧰", label: "Mind-care toolkit" },
    { id: "ask-for-help", emoji: "🆘", label: "Ask for help" },
    { id: "be-kind-to-mind", emoji: "💛", label: "Be kind to your mind" },
  ],
  badge: {
    title: "Mind Matters! 🧠",
    blurb: "You know your mind has health too, that hard feelings rise and pass, how to handle stress and rejection — and that asking for help is strength. 🧠",
  },
  helpLine: "If a feeling gets too big, lasts long, or you have dark thoughts, tell a trusted grown-up — or call Childline, one-zero-nine-eight (or one-one-two).",
  helpLabel: "Get help · Childline 1098",
  reassure: "It's okay to not be okay — asking for help is brave and strong, never weak. If a feeling won't lift, tell a trusted grown-up or call Childline 1098. 💛",
  reassureCats: ["ask-for-help"],
  buildLabels: { assemble: "That's your mind-care kit! 🧰", sequence: "Nice — that's the order! ✅" },
};
