// Content for MythBuster: Gender (node g25, ages 12–15, Chapter 4) — NEW v2 build to GDD 25
// (mechanic-embodying), the gender-myth-busting node (Thread E · Gender & Respect) — a FLAGSHIP of the
// strike-and-rewrite signature. "Bust the myth. Write the truth." 90 researched, India-grounded,
// EVIDENCE-BASED scenarios across the ability → roles → emotion-&-leadership → "it's just science" →
// equality → spot-and-flip arc, each encoded as one of the shared v2 play actions (strike-rewrite / sort /
// spot / branch / match / reflect / role-play) — no binary "tap the right card". Lead mechanics:
// strike-rewrite (bust the myth ×31), sort (fact vs myth ×15), spot (catch the myth ×7). Busts the gender
// myths teens hear constantly: ability/brains aren't gendered, roles are cultural not biological, emotion &
// leadership aren't male/female traits, the "it's just science" pseudo-science (naturalistic fallacy,
// averages-aren't-individuals, cherry-picking, "facts over feelings" shutdowns), and what equality really
// means. EVENHANDED, NEVER ANTI-BOY: equality lifts everyone (boys included — less pressure to provide
// alone, freedom to feel); boys' real struggles are validated AND equality is championed. Inoculation
// against pseudo-science gender claims. Builds on g18 (Norm Storm); prereq g24. Rendered by the shared
// engine (components/games/v2-engine.tsx). gameId "mythbuster-lab" (the engine-host registry id; the
// GDD/library aspirational id is "mythbuster-gender"). DO NOT RENAME.

import type { Scenario, V2GameConfig } from "./v2-schema";

const SCENARIOS: Scenario[] = [
  // — Ability isn't gendered —
  {"id":"mb-001","cat":"ability-myths","type":"strike-rewrite","hook":"\"Boys are just naturally better at maths.\"","myth":{"un":"Boys are naturally better at maths than girls.","re":"There's no brain difference in maths ability; the gap is cultural, not biological.","why":"Studies find equal maths-brain development, and the gap vanishes where equality is higher."},"relearn":"Boys aren't naturally better at maths; the gap is cultural, not biological.","persona":"Veer","source":"math/brain evidence (verified)"},
  {"id":"mb-002","cat":"ability-myths","type":"strike-rewrite","hook":"\"There's a 'male brain' and a 'female brain'.\"","myth":{"un":"Brains come in a clear 'male' and 'female' type.","re":"Brains overlap hugely; there's no neat male/female split for ability.","why":"Individual variation dwarfs any average difference."},"relearn":"There's no tidy 'male brain / female brain'; brains overlap enormously.","persona":"any","source":"neuroscience (verified)"},
  {"id":"mb-003","cat":"ability-myths","type":"strike-rewrite","hook":"\"Girls can't do science, coding or engineering.\"","myth":{"un":"Girls just aren't suited to science or engineering.","re":"Girls excel in every STEM field; ability isn't gendered.","why":"From Kalpana Chawla to top engineers, the proof is everywhere."},"relearn":"Girls excel in STEM; ability there isn't gendered.","persona":"Riya","source":"STEM / role models"},
  {"id":"mb-004","cat":"ability-myths","type":"strike-rewrite","hook":"\"Boys can't be good at art, languages or caring work.\"","myth":{"un":"Boys aren't suited to art, languages or caring roles.","re":"Boys excel at all of these; talent has no gender.","why":"Limiting boys this way wastes their gifts too."},"relearn":"Boys can excel at art, languages and care; talent has no gender.","persona":"Veer","source":"ability / boys too"},
  {"id":"mb-005","cat":"ability-myths","type":"strike-rewrite","hook":"\"Girls are just bad at sport.\"","myth":{"un":"Girls are naturally bad at sport.","re":"Girls are world-class athletes; skill comes from training, not gender.","why":"Mary Kom, PV Sindhu and millions more disprove it daily."},"relearn":"Girls are top athletes; sport skill comes from training, not gender.","persona":"any","source":"sport / role models"},
  {"id":"mb-006","cat":"ability-myths","type":"strike-rewrite","hook":"\"Men are logical, women are emotional, that's just how brains are.\"","myth":{"un":"Men are wired for logic, women for emotion.","re":"Everyone has both logic and emotion; this binary is a myth.","why":"There's no logic-vs-emotion gender switch in the brain."},"relearn":"The 'men=logic, women=emotion' brain split is a myth.","persona":"any","source":"neuroscience"},
  {"id":"mb-007","cat":"ability-myths","type":"strike-rewrite","hook":"\"If fewer women are in tech, they must be worse at it.\"","myth":{"un":"Fewer women in tech proves women are worse at it.","re":"Lower numbers come from barriers and bias, not ability.","why":"Where barriers drop, women's numbers rise fast."},"relearn":"Fewer women in a field reflects barriers, not lesser ability.","persona":"Riya","source":"bias vs ability"},
  {"id":"mb-008","cat":"ability-myths","type":"strike-rewrite","hook":"\"Telling a girl 'girls are bad at maths' is harmless.\"","myth":{"un":"Saying 'girls are bad at maths' does no harm.","re":"Hearing that belief actually lowers girls' maths performance.","why":"Stereotypes can become self-fulfilling."},"relearn":"The 'girls are bad at maths' belief itself harms girls' performance.","persona":"any","source":"stereotype threat (verified)"},
  {"id":"mb-009","cat":"ability-myths","type":"strike-rewrite","hook":"\"Boys mature slower, so they just can't focus in school.\"","myth":{"un":"Boys can't help underperforming; they just mature slower.","re":"Expectations and support shape focus far more than gender.","why":"Low expectations become an excuse, not a destiny."},"relearn":"Boys' focus depends on support and expectations, not a gender excuse.","persona":"Veer","source":"expectations"},
  {"id":"mb-010","cat":"ability-myths","type":"sort","hook":"Sort: decides ability, or doesn't?","items":[{"id":"a","text":"Practice and teaching"},{"id":"b","text":"Your gender"},{"id":"c","text":"Effort and interest"},{"id":"d","text":"Whether you're a boy or girl"}],"bins":[{"id":"yes","label":"Shapes ability"},{"id":"no","label":"Doesn't"}],"key":{"a":"yes","b":"no","c":"yes","d":"no"},"relearn":"Practice, teaching and interest build ability; gender doesn't.","persona":"any","source":"ability"},
  {"id":"mb-011","cat":"ability-myths","type":"sort","hook":"Sort: a real reason for a skill gap, or a myth reason?","items":[{"id":"a","text":"Less encouragement"},{"id":"b","text":"'Wrong' gender"},{"id":"c","text":"Fewer chances to try"},{"id":"d","text":"'Born without the talent'"}],"bins":[{"id":"real","label":"Real reason"},{"id":"myth","label":"Myth reason"}],"key":{"a":"real","b":"myth","c":"real","d":"myth"},"relearn":"Skill gaps come from chances and encouragement, not being 'born wrong'.","persona":"any","source":"bias"},
  {"id":"mb-012","cat":"ability-myths","type":"sort","hook":"Sort: which are gendered by nature?","items":[{"id":"a","text":"Maths ability"},{"id":"b","text":"Eye colour"},{"id":"c","text":"Coding skill"},{"id":"d","text":"Height range (on average)"}],"bins":[{"id":"natural","label":"Set by biology"},{"id":"notnatural","label":"Not gendered ability"}],"key":{"a":"notnatural","b":"natural","c":"notnatural","d":"natural"},"relearn":"Skills like maths and coding aren't gendered, unlike some physical traits.","persona":"any","source":"ability vs biology"},
  {"id":"mb-013","cat":"ability-myths","type":"match","hook":"Match the field to someone who broke the 'girls can't' myth.","pairs":[{"left":"Space","right":"Kalpana Chawla"},{"left":"Boxing","right":"Mary Kom"},{"left":"Leadership","right":"India's woman President"}],"relearn":"Real women have excelled in every 'girls can't' field.","persona":"any","source":"role models (India)"},
  {"id":"mb-014","cat":"ability-myths","type":"match","hook":"Match the myth to the fact that beats it.","pairs":[{"left":"\"Boys are better at maths\"","right":"No brain difference"},{"left":"\"Girls can't do science\"","right":"Girls excel in STEM"},{"left":"\"Male and female brains\"","right":"Brains overlap hugely"}],"relearn":"Each ability myth has clear evidence against it.","persona":"any","source":"evidence"},
  {"id":"mb-015","cat":"ability-myths","type":"reflect","hook":"Lensy: has anyone ever doubted what you could do because of your gender?","prompt":"What do you think?","options":["Yes","Maybe","It's unfair"],"affirm":"Your ability is yours to build; no one's gender myth gets to cap it.","relearn":"Your ability isn't capped by anyone's gender assumptions.","persona":"any","source":"agency"},
  {"id":"mb-016","cat":"ability-myths","type":"reflect","hook":"Lensy: if the maths gap is cultural, what does that mean you can do?","prompt":"What do you think?","options":["Ignore the myth","Try anyway","Encourage others"],"affirm":"A cultural gap can be closed, by you, and by changing what we expect.","relearn":"Cultural gaps can be closed; the myth doesn't have to win.","persona":"Riya","source":"agency"},
  // — Roles aren't gendered —
  {"id":"mb-017","cat":"role-myths","type":"strike-rewrite","hook":"\"A woman's place is in the home.\"","myth":{"un":"A woman's place is in the home.","re":"Women belong wherever they choose, home, work, the world.","why":"Homemaking can be a choice, never a destiny imposed by gender."},"relearn":"Women belong wherever they choose; 'a woman's place' is a myth.","persona":"any","source":"roles"},
  {"id":"mb-018","cat":"role-myths","type":"strike-rewrite","hook":"\"A real man is the provider; a man who earns less has failed.\"","myth":{"un":"A real man must be the main provider.","re":"Providing can be shared; a man's worth isn't his pay.","why":"This myth crushes boys with pressure too."},"relearn":"Providing is shared; a man's worth isn't his income.","persona":"Veer","source":"masculinity / pressure on boys"},
  {"id":"mb-019","cat":"role-myths","type":"strike-rewrite","hook":"\"Men can't cook, clean or look after children properly.\"","myth":{"un":"Men aren't suited to cooking, cleaning or childcare.","re":"Men do all of these brilliantly; they're skills, not gender traits.","why":"Top chefs and caring dads prove it."},"relearn":"Men can cook, clean and care for kids; these are learned skills.","persona":"Veer","source":"roles / care"},
  {"id":"mb-020","cat":"role-myths","type":"strike-rewrite","hook":"\"Some jobs are just men's jobs and some are women's.\"","myth":{"un":"Jobs are naturally split into men's and women's.","re":"Any job can be done by anyone; the split is a made-up custom.","why":"Skill, not gender, fits a person to a job."},"relearn":"Jobs aren't gendered; anyone can do any job.","persona":"any","source":"jobs (links g17)"},
  {"id":"mb-021","cat":"role-myths","type":"strike-rewrite","hook":"\"Girls should study less since they'll run a home anyway.\"","myth":{"un":"Girls need less education; they'll run a home.","re":"Every girl deserves a full education and her own future.","why":"Education is a right, not a gender privilege."},"relearn":"Girls deserve full education; 'they'll just marry' is a harmful myth.","persona":"Riya","source":"education (links g18)"},
  {"id":"mb-022","cat":"role-myths","type":"strike-rewrite","hook":"\"A husband helping at home is 'doing his wife a favour'.\"","myth":{"un":"A man doing housework is helping his wife out.","re":"A shared home is shared work, not a favour.","why":"It's his home and his job too."},"relearn":"Sharing housework is fairness, not a favour to women.","persona":"any","source":"shared work / equality"},
  {"id":"mb-023","cat":"role-myths","type":"sort","hook":"Sort: a job for anyone, or 'only one gender'?","items":[{"id":"a","text":"Pilot"},{"id":"b","text":"Nurse"},{"id":"c","text":"Soldier"},{"id":"d","text":"Chef"}],"bins":[{"id":"any","label":"Anyone"},{"id":"one","label":"One gender only"}],"key":{"a":"any","b":"any","c":"any","d":"any"},"relearn":"Every one of these jobs is open to anyone.","persona":"any","source":"jobs"},
  {"id":"mb-024","cat":"role-myths","type":"sort","hook":"Sort: a free choice, or a gender rule imposed?","items":[{"id":"a","text":"Choosing to be a homemaker"},{"id":"b","text":"Being forced to quit work to marry"},{"id":"c","text":"A dad choosing to stay home"},{"id":"d","text":"'Boys must earn, girls must cook'"}],"bins":[{"id":"choice","label":"Free choice"},{"id":"rule","label":"Imposed rule"}],"key":{"a":"choice","b":"rule","c":"choice","d":"rule"},"relearn":"Roles chosen freely are fine; roles forced by gender are not.","persona":"any","source":"choice vs rule"},
  {"id":"mb-025","cat":"role-myths","type":"sort","hook":"Sort: who can lead a household?","items":[{"id":"a","text":"A father"},{"id":"b","text":"A mother"},{"id":"c","text":"Both, together"},{"id":"d","text":"Only the man"}],"bins":[{"id":"fair","label":"Fair view"},{"id":"myth","label":"Myth"}],"key":{"a":"fair","b":"fair","c":"fair","d":"myth"},"relearn":"Any parent, or both together, can lead a household.","persona":"any","source":"roles"},
  {"id":"mb-026","cat":"role-myths","type":"match","hook":"Match the role to the truth.","pairs":[{"left":"Breadwinner","right":"Can be anyone"},{"left":"Caregiver","right":"Can be anyone"},{"left":"Leader","right":"Can be anyone"}],"relearn":"Provider, carer and leader can each be any gender.","persona":"any","source":"roles"},
  {"id":"mb-027","cat":"role-myths","type":"match","hook":"Match the 'role myth' to who it limits.","pairs":[{"left":"\"Men must provide\"","right":"Pressures men"},{"left":"\"Women belong at home\"","right":"Limits women"},{"left":"\"Men can't nurture\"","right":"Robs men of family"}],"relearn":"Role myths box in both men and women.","persona":"Veer","source":"roles / both harmed"},
  {"id":"mb-028","cat":"role-myths","type":"branch","hook":"A relative says you must pick a 'gender-appropriate' career.","options":[{"text":"Say you'll choose by your talent and interest","consequence":"You keep your future open.","outcome":"self-led","best":true},{"text":"Accept the gendered limit","consequence":"Your career is yours; choose by talent, not gender."}],"debrief":"Careers should fit your talents, not a gender rule.","relearn":"Choose a career by talent and interest, not gender.","persona":"any","source":"aspiration"},
  {"id":"mb-029","cat":"role-myths","type":"branch","hook":"Friends mock a boy who wants to be a nurse or a chef.","options":[{"text":"Back him: those are great careers for anyone","consequence":"You defend his real choice.","outcome":"ally","best":true},{"text":"Join the mocking","consequence":"Nursing and cooking are skilled careers, open to anyone."}],"debrief":"Boys deserve support for any career, including caring ones.","relearn":"Support boys in any career, including 'caring' ones.","persona":"Veer","source":"roles / boys"},
  // — Emotion & leadership —
  {"id":"mb-030","cat":"emotion-leadership","type":"strike-rewrite","hook":"\"Men shouldn't cry; showing emotion is weak.\"","myth":{"un":"A real man hides his emotions; crying is weak.","re":"Everyone feels; expressing emotion is healthy and strong.","why":"Bottling up harms boys' mental health."},"relearn":"Men feel and can show emotion; that's strength, not weakness.","persona":"Veer","source":"masculinity / mental health"},
  {"id":"mb-031","cat":"emotion-leadership","type":"strike-rewrite","hook":"\"Women are too emotional to lead.\"","myth":{"un":"Women are too emotional to be good leaders.","re":"Understanding emotions makes someone a stronger leader.","why":"Emotional skill is a leadership asset, not a flaw."},"relearn":"Emotional skill helps leadership; 'too emotional to lead' is a myth.","persona":"Riya","source":"leadership"},
  {"id":"mb-032","cat":"emotion-leadership","type":"strike-rewrite","hook":"\"Men are just natural leaders.\"","myth":{"un":"Men are naturally better leaders.","re":"Leadership is a skill set anyone can build; gender doesn't grant it.","why":"India has had a woman PM and has a woman President."},"relearn":"Leadership is a skill, not a male birthright.","persona":"any","source":"leadership (India)"},
  {"id":"mb-033","cat":"emotion-leadership","type":"strike-rewrite","hook":"\"A girl who leads is bossy; a boy who leads is a leader.\"","myth":{"un":"A girl who takes charge is 'bossy'.","re":"A girl who takes charge is a leader, same as a boy.","why":"The double standard is the only difference."},"relearn":"A girl who leads is a leader, not 'bossy'.","persona":"Riya","source":"double standard"},
  {"id":"mb-034","cat":"emotion-leadership","type":"strike-rewrite","hook":"\"Anger is okay for boys, but not sadness or fear.\"","myth":{"un":"Boys may show anger, but not sadness or fear.","re":"Boys are allowed the full range of feelings, like everyone.","why":"Only-anger-allowed harms boys and others."},"relearn":"Boys get the whole range of feelings, not just anger.","persona":"Veer","source":"emotions / boys"},
  {"id":"mb-035","cat":"emotion-leadership","type":"strike-rewrite","hook":"\"Caring and gentleness are unmanly.\"","myth":{"un":"Caring and gentleness make a man less manly.","re":"Kindness and gentleness are strengths in anyone.","why":"Good character isn't gendered."},"relearn":"Kindness and gentleness are strengths, not 'unmanly'.","persona":"Veer","source":"masculinity"},
  {"id":"mb-036","cat":"emotion-leadership","type":"sort","hook":"Sort: a leadership strength, or a gender myth?","items":[{"id":"a","text":"Listening and empathy"},{"id":"b","text":"\"Only men can command respect\""},{"id":"c","text":"Making fair decisions"},{"id":"d","text":"\"Women are too soft to lead\""}],"bins":[{"id":"strength","label":"Real strength"},{"id":"myth","label":"Gender myth"}],"key":{"a":"strength","b":"myth","c":"strength","d":"myth"},"relearn":"Empathy and fairness make leaders; gender doesn't.","persona":"any","source":"leadership"},
  {"id":"mb-037","cat":"emotion-leadership","type":"sort","hook":"Sort: a feeling boys are allowed, or 'not allowed' by the myth?","items":[{"id":"a","text":"Sadness"},{"id":"b","text":"Fear"},{"id":"c","text":"Joy"},{"id":"d","text":"All of them"}],"bins":[{"id":"allowed","label":"Allowed (truth)"},{"id":"myth","label":"'Banned' by myth"}],"key":{"a":"allowed","b":"allowed","c":"allowed","d":"allowed"},"relearn":"Boys are allowed every feeling; the 'ban' is a harmful myth.","persona":"Veer","source":"emotions"},
  {"id":"mb-038","cat":"emotion-leadership","type":"match","hook":"Match the leader-myth to the reality.","pairs":[{"left":"\"Men are natural leaders\"","right":"Leadership is learned"},{"left":"\"Women too emotional\"","right":"Emotion aids leading"},{"left":"\"Bossy girl\"","right":"She's a leader"}],"relearn":"Leadership myths fall apart against real leaders of every gender.","persona":"any","source":"leadership"},
  {"id":"mb-039","cat":"emotion-leadership","type":"branch","hook":"A male friend is fighting back tears and embarrassed.","options":[{"text":"Tell him it's okay to feel, you're there","consequence":"He feels less alone and ashamed.","outcome":"caring","best":true},{"text":"Tell him to 'man up'","consequence":"'It's okay to feel' helps far more than 'man up'."}],"debrief":"Letting a boy feel is a gift, not a weakness.","relearn":"You can free a friend from 'boys don't cry'.","persona":"Veer","source":"masculinity / support"},
  {"id":"mb-040","cat":"emotion-leadership","type":"reflect","hook":"Lensy: who's a leader you admire who isn't the 'tough strongman' type?","prompt":"Think of one.","options":["A calm leader","A kind leader","A woman leader","A quiet one"],"affirm":"Great leadership comes in every style and gender.","relearn":"Leadership comes in many styles, not one gendered mould.","persona":"any","source":"leadership"},
  {"id":"mb-041","cat":"emotion-leadership","type":"reflect","hook":"Lensy: how would it feel to be allowed every emotion, no gender rules?","prompt":"What do you think?","options":["Freeing","Honest","Healthier"],"affirm":"Permission to feel everything is freedom, and it's yours.","relearn":"You're allowed your full range of feelings, whatever your gender.","persona":"Veer","source":"emotions"},
  // — "It's just science" —
  {"id":"mb-042","cat":"its-just-science","type":"strike-rewrite","hook":"\"It's just science, men are biologically meant to dominate.\"","myth":{"un":"Biology means men are meant to dominate.","re":"There's no biological law that men must dominate; behaviour is shaped by culture and choice.","why":"'It's natural' never proves something is right or fixed."},"relearn":"No biology makes domination 'natural' or right; choice and culture shape us.","persona":"Veer","source":"naturalistic fallacy"},
  {"id":"mb-043","cat":"its-just-science","type":"strike-rewrite","hook":"\"Testosterone makes men aggressive, so it's just their nature.\"","myth":{"un":"Hormones make men aggressive, so it can't be helped.","re":"Hormones nudge, but behaviour is a choice shaped by upbringing.","why":"'My hormones made me' isn't an excuse for how you treat people."},"relearn":"Hormones don't excuse behaviour; how you treat people is a choice.","persona":"Veer","source":"behaviour vs biology"},
  {"id":"mb-044","cat":"its-just-science","type":"strike-rewrite","hook":"\"On average men are X, so every man beats every woman at it.\"","myth":{"un":"An average difference means every man beats every woman.","re":"Averages aren't individuals; the overlap between groups is huge.","why":"You can't predict a person from a group average."},"relearn":"Group averages don't decide individuals; overlap is huge.","persona":"any","source":"statistics literacy"},
  {"id":"mb-045","cat":"its-just-science","type":"strike-rewrite","hook":"\"Cavemen prove men hunt and women stay home, it's evolution.\"","myth":{"un":"Evolution and 'cavemen' prove fixed gender roles.","re":"These are just-so stories; real societies have varied wildly.","why":"History shows women hunters, leaders and warriors too."},"relearn":"'Caveman' gender roles are myths; human societies vary hugely.","persona":"any","source":"anthropology"},
  {"id":"mb-046","cat":"its-just-science","type":"strike-rewrite","hook":"\"If a gender difference is natural, it must be good and unchangeable.\"","myth":{"un":"If something is natural, it's good and can't change.","re":"'Natural' doesn't mean good or fixed, that's the naturalistic fallacy.","why":"Plenty of natural things are harmful; plenty change."},"relearn":"'Natural' never proves something is good or unchangeable.","persona":"any","source":"naturalistic fallacy"},
  {"id":"mb-047","cat":"its-just-science","type":"sort","hook":"Sort: a real, careful science claim, or pseudo-science to sell a myth?","items":[{"id":"a","text":"\"Studies show no maths-brain gap\""},{"id":"b","text":"\"Science proves men should rule\""},{"id":"c","text":"\"Behaviour is shaped by culture too\""},{"id":"d","text":"\"It's just biology, deal with it\""}],"bins":[{"id":"real","label":"Careful science"},{"id":"pseudo","label":"Pseudo-science"}],"key":{"a":"real","b":"pseudo","c":"real","d":"pseudo"},"relearn":"Real science is careful and tested; 'science proves men rule' is pseudo-science.","persona":"Veer","source":"science literacy"},
  {"id":"mb-048","cat":"its-just-science","type":"sort","hook":"Sort: shaped mostly by biology, or mostly by culture?","items":[{"id":"a","text":"Who does the cooking at home"},{"id":"b","text":"Average adult height"},{"id":"c","text":"Who 'should' lead"},{"id":"d","text":"Needing food and sleep"}],"bins":[{"id":"culture","label":"Mostly culture"},{"id":"biology","label":"Mostly biology"}],"key":{"a":"culture","b":"biology","c":"culture","d":"biology"},"relearn":"Roles like cooking and leading are cultural; height and needs are biological.","persona":"any","source":"nature vs culture"},
  {"id":"mb-049","cat":"its-just-science","type":"sort","hook":"Sort: a sign someone's twisting 'science' to push a gender agenda?","items":[{"id":"a","text":"Cites one study, ignores the rest"},{"id":"b","text":"Links to careful, repeated research"},{"id":"c","text":"Says 'facts don't care about feelings' to shut you up"},{"id":"d","text":"Welcomes questions"}],"bins":[{"id":"twist","label":"Twisting it"},{"id":"honest","label":"Honest"}],"key":{"a":"twist","b":"honest","c":"twist","d":"honest"},"relearn":"Cherry-picking and 'facts over feelings' shutdowns are signs of a twisted agenda.","persona":"Veer","source":"media literacy / manosphere"},
  {"id":"mb-050","cat":"its-just-science","type":"branch","hook":"An online 'expert' uses science-y words to claim women are inferior.","options":[{"text":"Check the real evidence before believing it","consequence":"You find the actual science disagrees.","outcome":"critical","best":true},{"text":"Believe it because it sounds smart","consequence":"Science-y words aren't proof; check the real evidence."}],"debrief":"Sounding scientific isn't being scientific; verify the claim.","relearn":"Check real evidence before trusting a science-y gender claim.","persona":"Veer","source":"critical thinking (links g43)"},
  {"id":"mb-051","cat":"its-just-science","type":"branch","hook":"A mate shares a video 'proving' men are superior, and watches your reaction.","options":[{"text":"Ask 'where's the actual evidence?' calmly","consequence":"You question it without a fight.","outcome":"critical","best":true},{"text":"Just agree to fit in","consequence":"A calm 'where's the evidence?' beats going along."}],"debrief":"You can question a viral 'fact' without making it a battle.","relearn":"Calmly ask for real evidence behind big gender claims.","persona":"Veer","source":"peer / critical thinking"},
  {"id":"mb-052","cat":"its-just-science","type":"reflect","hook":"Lensy: 'it's just science' is often used to shut down questions. Notice that?","prompt":"What do you think?","options":["Yes","It's a tactic","I'll ask anyway"],"affirm":"Real science loves questions; only a weak claim fears them.","relearn":"'It's just science' used to silence you is a red flag, not proof.","persona":"any","source":"science literacy"},
  {"id":"mb-053","cat":"its-just-science","type":"reflect","hook":"Lensy: even if a difference were natural, would that make unfairness okay?","prompt":"What do you think?","options":["No","Fairness still matters","Good point"],"affirm":"What's natural doesn't decide what's fair; we choose fairness.","relearn":"'Natural' never settles what's fair; we choose how to treat people.","persona":"any","source":"naturalistic fallacy"},
  {"id":"mb-054","cat":"its-just-science","type":"match","hook":"Match the pseudo-science move to what's really going on.","pairs":[{"left":"One cherry-picked study","right":"Ignoring the evidence"},{"left":"'Facts over feelings'","right":"Shutting down debate"},{"left":"'It's just nature'","right":"Excusing unfairness"}],"relearn":"Pseudo-science gender claims rely on a few predictable tricks.","persona":"Veer","source":"media literacy"},
  // — What equality really means —
  {"id":"mb-055","cat":"equality-myths","type":"strike-rewrite","hook":"\"Feminism means hating men.\"","myth":{"un":"Feminism is about hating men.","re":"It's about equal rights for all genders, men included.","why":"Equality lifts everyone, not one side over another."},"relearn":"Equality (feminism) means equal rights for all, not hating men.","persona":"Veer","source":"equality"},
  {"id":"mb-056","cat":"equality-myths","type":"strike-rewrite","hook":"\"If women gain, men must lose.\"","myth":{"un":"Gender equality means men lose out.","re":"Equality isn't a zero-sum game; everyone gains.","why":"Fairer homes, less pressure on boys, better for all."},"relearn":"Equality isn't men losing; it frees everyone.","persona":"Veer","source":"equality / not zero-sum"},
  {"id":"mb-057","cat":"equality-myths","type":"strike-rewrite","hook":"\"The gender gap is a myth, it's all equal now.\"","myth":{"un":"There's no gender gap left; it's all equal already.","re":"Real gaps remain in pay, leadership and safety.","why":"Progress is real, but the work isn't finished."},"relearn":"Gender gaps still exist; equality isn't 'done'.","persona":"Riya","source":"equality / data"},
  {"id":"mb-058","cat":"equality-myths","type":"strike-rewrite","hook":"\"Caring about gender equality makes a boy less of a man.\"","myth":{"un":"A boy who supports equality is weak or 'less of a man'.","re":"Standing for fairness is a sign of real strength and character.","why":"The bravest thing is to be fair when it's unpopular."},"relearn":"Supporting equality is strength; it doesn't make a boy 'less'.","persona":"Veer","source":"allyship"},
  {"id":"mb-059","cat":"equality-myths","type":"branch","hook":"Someone says equality has 'gone too far' and men are the real victims now.","options":[{"text":"Acknowledge boys' real struggles AND keep supporting equality","consequence":"You hold both truths without buying the myth.","outcome":"balanced","best":true},{"text":"Accept that equality is the enemy","consequence":"Boys' struggles are real, and equality helps with them too."}],"debrief":"Boys' struggles are real; equality is an ally to them, not the enemy.","relearn":"You can take boys' struggles seriously and back equality, both.","persona":"Veer","source":"evenhanded / manosphere counter"},
  {"id":"mb-060","cat":"equality-myths","type":"branch","hook":"You see equality helping in your own home or class. What do you make of it?","options":[{"text":"Notice everyone seems freer and happier","consequence":"You see equality's real, shared payoff.","outcome":"insight","best":true},{"text":"Assume someone must be losing","consequence":"Fairer sharing tends to lift everyone, not cost one side."}],"debrief":"Equality usually makes the whole group freer, not one side poorer.","relearn":"Equality tends to free everyone, not cost one side.","persona":"any","source":"equality"},
  {"id":"mb-061","cat":"equality-myths","type":"sort","hook":"Sort: what equality actually means, or a myth about it?","items":[{"id":"a","text":"Equal rights and chances"},{"id":"b","text":"Women ruling over men"},{"id":"c","text":"Freedom for all genders"},{"id":"d","text":"Hating men"}],"bins":[{"id":"real","label":"What it means"},{"id":"myth","label":"Myth about it"}],"key":{"a":"real","b":"myth","c":"real","d":"myth"},"relearn":"Equality means equal rights and freedom for all, not flipping the hierarchy.","persona":"any","source":"equality"},
  {"id":"mb-062","cat":"equality-myths","type":"sort","hook":"Sort: how equality helps boys, or doesn't?","items":[{"id":"a","text":"Less pressure to hide feelings"},{"id":"b","text":"Freedom to choose any path"},{"id":"c","text":"Being forced to provide alone"},{"id":"d","text":"Sharing the load at home"}],"bins":[{"id":"helps","label":"Helps boys"},{"id":"not","label":"The old pressure"}],"key":{"a":"helps","b":"helps","c":"not","d":"helps"},"relearn":"Equality frees boys too, from pressure to provide alone and hide feelings.","persona":"Veer","source":"equality / boys gain"},
  {"id":"mb-063","cat":"equality-myths","type":"reflect","hook":"Lensy: name one way equality would make YOUR life better.","prompt":"Think of one.","options":["Less pressure","More choices","Fairer home","Freedom to be me"],"affirm":"Equality has something in it for you, personally, whoever you are.","relearn":"Gender equality has real, personal benefits for you too.","persona":"Veer","source":"equality"},
  {"id":"mb-064","cat":"equality-myths","type":"reflect","hook":"Lensy: would you rather be free to be fully yourself, or boxed by gender rules?","prompt":"What do you think?","options":["Free to be me","No boxes","Freedom"],"affirm":"Equality is really just the freedom to be fully yourself.","relearn":"Equality is the freedom to be fully yourself, beyond gender boxes.","persona":"any","source":"equality / freedom"},
  {"id":"mb-065","cat":"equality-myths","type":"role-play","hook":"A mate says 'feminism is just man-hating'.","setup":"Reframe it calmly. Say:","yourLine":[{"text":"\"It's about fairness for everyone, including us.\"","best":true},{"text":"\"Yeah, probably.\""}],"relearn":"You can reframe equality as fairness for everyone, boys included.","persona":"Veer","source":"allyship / voice"},
  {"id":"mb-066","cat":"equality-myths","type":"role-play","hook":"Someone mocks you for backing equality.","setup":"Stand firm. Say:","yourLine":[{"text":"\"Being fair isn't something I'm going to apologise for.\"","best":true},{"text":"Back down to fit in"}],"relearn":"You can stand by fairness without apology.","persona":"any","source":"allyship"},
  {"id":"mb-067","cat":"equality-myths","type":"role-play","hook":"A friend feels equality talk ignores boys' problems.","setup":"Bring them in. Say:","yourLine":[{"text":"\"Your struggles matter too, and equality actually helps with them.\"","best":true},{"text":"\"Boys have no problems, stop whining.\""}],"relearn":"You can validate boys' struggles while championing equality.","persona":"Veer","source":"evenhanded / inclusion"},
  // — Spot it & flip it —
  {"id":"mb-068","cat":"spot-and-flip","type":"spot","hook":"Spot the gender myth in this reel.","scene":[{"id":"a","text":"\"Real men never show weakness\"","trick":true},{"id":"b","text":"It has gym music","trick":false},{"id":"c","text":"\"Women just aren't built to lead\"","trick":true}],"why":"'Real men never show weakness' and 'women can't lead' are gender myths.","relearn":"Spot myths like 'real men never show weakness' and 'women can't lead'.","persona":"Veer","source":"media literacy"},
  {"id":"mb-069","cat":"spot-and-flip","type":"spot","hook":"Spot the myth dressed up as a 'fact'.","scene":[{"id":"a","text":"\"Studies prove women are worse drivers\"","trick":true},{"id":"b","text":"A car advert plays","trick":false},{"id":"c","text":"\"It's just biology\"","trick":true}],"why":"Cherry-picked 'studies' and 'it's just biology' often hide a myth.","relearn":"Watch for myths hiding behind 'studies prove' and 'it's just biology'.","persona":"any","source":"media literacy"},
  {"id":"mb-070","cat":"spot-and-flip","type":"spot","hook":"Spot the gender myth a relative repeats.","scene":[{"id":"a","text":"\"Boys will be boys\" excusing bad behaviour","trick":true},{"id":"b","text":"Tea is served","trick":false},{"id":"c","text":"\"Girls must adjust and stay quiet\"","trick":true}],"why":"'Boys will be boys' and 'girls must adjust' are harmful myths.","relearn":"'Boys will be boys' and 'girls adjust' are myths, even from family.","persona":"any","source":"media literacy / family"},
  {"id":"mb-071","cat":"spot-and-flip","type":"spot","hook":"Spot the myth in a 'motivational' post for boys.","scene":[{"id":"a","text":"\"Crying is for the weak, grind in silence\"","trick":true},{"id":"b","text":"A sunrise photo","trick":false},{"id":"c","text":"\"Provide or you're nothing\"","trick":true}],"why":"'Crying is weak' and 'provide or you're nothing' are myths that harm boys.","relearn":"Spot boy-targeted myths like 'crying is weak' and 'provide or you're nothing'.","persona":"Veer","source":"media literacy / manosphere"},
  {"id":"mb-072","cat":"spot-and-flip","type":"spot","hook":"Spot the true, myth-free message among the others.","scene":[{"id":"a","text":"\"Anyone can be anything, with effort\"","trick":false},{"id":"b","text":"\"Men are superior leaders\"","trick":true},{"id":"c","text":"\"Real women don't have opinions\"","trick":true}],"why":"Only 'anyone can be anything' is myth-free; the others are gender myths.","relearn":"A myth-free message says anyone can be anything; the rest are myths.","persona":"any","source":"media literacy"},
  {"id":"mb-073","cat":"spot-and-flip","type":"spot","hook":"Check yourself: spot a gender myth you might have believed.","scene":[{"id":"a","text":"\"I assumed boys are just better at this\"","trick":true},{"id":"b","text":"\"I worked hard at it\"","trick":false},{"id":"c","text":"\"Maybe she can't because she's a girl\"","trick":true}],"why":"We all absorb gender myths; spotting our own is real growth.","relearn":"Spotting a gender myth you absorbed is the first step to dropping it.","persona":"any","source":"self-reflection"},
  {"id":"mb-074","cat":"spot-and-flip","type":"spot","hook":"Spot the myth in a careers fair flyer.","scene":[{"id":"a","text":"\"Engineering: for the boys\"","trick":true},{"id":"b","text":"\"Free snacks\"","trick":false},{"id":"c","text":"\"Nursing: a girl's calling\"","trick":true}],"why":"Labelling careers by gender is a myth; all careers are open to all.","relearn":"Careers aren't gendered; spot the 'for boys / for girls' labels.","persona":"Riya","source":"media literacy / careers"},
  {"id":"mb-075","cat":"spot-and-flip","type":"role-play","hook":"You spotted a gender myth in a group chat.","setup":"Flip it lightly. Say:","yourLine":[{"text":"\"Actually that's a myth, the real facts say otherwise.\"","best":true},{"text":"Stay silent and let it stand"}],"relearn":"You can flip a gender myth with the real facts, even in a group chat.","persona":"any","source":"voice / flip"},
  {"id":"mb-076","cat":"spot-and-flip","type":"role-play","hook":"A younger sibling repeats a gender myth they heard online.","setup":"Gently correct it. Say:","yourLine":[{"text":"\"That's a popular myth, here's what's actually true.\"","best":true},{"text":"Let it slide"}],"relearn":"You can pass accurate, myth-free facts to younger kids.","persona":"Veer","source":"mentoring / flip"},
  {"id":"mb-077","cat":"spot-and-flip","type":"role-play","hook":"Friends pressure you to agree with a sexist 'joke-fact'.","setup":"Hold your ground kindly. Say:","yourLine":[{"text":"\"I'm not buying that one, it's just not true.\"","best":true},{"text":"Laugh and agree"}],"relearn":"You can decline to co-sign a sexist 'joke-fact'.","persona":"Veer","source":"peer / voice"},
  {"id":"mb-078","cat":"spot-and-flip","type":"branch","hook":"You realise a creator you follow pushes gender myths as 'truth'.","options":[{"text":"Unfollow or fact-check their claims","consequence":"You stop feeding on the myths.","outcome":"savvy","best":true},{"text":"Keep absorbing it uncritically","consequence":"Fact-checking or unfollowing protects your thinking."}],"debrief":"You choose what shapes your beliefs; curate it wisely.","relearn":"You can unfollow or fact-check creators who push gender myths.","persona":"Veer","source":"feed curation (links g43)"},
  {"id":"mb-079","cat":"spot-and-flip","type":"branch","hook":"A teacher states a gender myth as fact in class.","options":[{"text":"Respectfully ask about the evidence","consequence":"You model questioning, even up the ladder.","outcome":"brave","best":true},{"text":"Assume teachers are always right","consequence":"Even experts can repeat myths; it's okay to ask for evidence."}],"debrief":"Anyone can repeat a myth; respectful questioning is fair game.","relearn":"You can respectfully question a gender myth, even from a teacher.","persona":"any","source":"critical thinking"},
  {"id":"mb-080","cat":"spot-and-flip","type":"reflect","hook":"Lensy: now you can spot a gender myth a mile off. Feel that power?","prompt":"What do you think?","options":["Yes","Myth radar on","I can flip them"],"affirm":"A myth-spotting radar protects you and everyone around you.","relearn":"Spotting gender myths quickly is a skill that protects everyone.","persona":"any","source":"consolidation"},
  {"id":"mb-081","cat":"spot-and-flip","type":"reflect","hook":"Lensy: biggest take-away from MythBuster: Gender?","prompt":"Pick your motto.","options":["Ability isn't gendered","'Natural' isn't 'right'","Equality frees everyone","Check the real facts"],"affirm":"Bust the myths, check the facts, and equality lifts us all.","relearn":"Ability isn't gendered, 'natural' isn't 'right', and equality frees everyone.","persona":"any","source":"consolidation"},
  {"id":"mb-082","cat":"equality-myths","type":"strike-rewrite","hook":"\"Standing up for girls means putting boys down.\"","myth":{"un":"Supporting girls means putting boys down.","re":"You can support girls and boys at once; it's not a competition.","why":"Fairness isn't a seesaw."},"relearn":"Supporting girls doesn't mean putting boys down; back both.","persona":"Veer","source":"equality / both"},
  {"id":"mb-083","cat":"emotion-leadership","type":"branch","hook":"You're picking a team captain; someone says it should be a boy.","options":[{"text":"Say the best leader can be anyone, then pick on merit","consequence":"The choice opens up fairly.","outcome":"fair","best":true},{"text":"Default to a boy","consequence":"Leadership isn't gendered; pick the best person."}],"debrief":"Captaincy is about leadership skill, not gender.","relearn":"Pick leaders on merit; leadership isn't a gender.","persona":"any","source":"leadership"},
  {"id":"mb-084","cat":"ability-myths","type":"reflect","hook":"Lensy: imagine no one was ever told what they 'can't' do because of gender. Better world?","prompt":"What do you think?","options":["Yes","So much potential freed","Definitely"],"affirm":"Dropping ability myths unlocks everyone's full potential.","relearn":"Without gender ability-myths, everyone's potential is freed.","persona":"any","source":"vision / equality"},
  {"id":"mb-085","cat":"role-myths","type":"sort","hook":"Sort: a dad can do this, or 'only mums can'?","items":[{"id":"a","text":"Cook the family dinner"},{"id":"b","text":"Plait a child's hair"},{"id":"c","text":"Comfort a crying baby"},{"id":"d","text":"Run the home"}],"bins":[{"id":"dad","label":"A dad can"},{"id":"myth","label":"'Only mums' myth"}],"key":{"a":"dad","b":"dad","c":"dad","d":"dad"},"relearn":"Dads can cook, groom, comfort and run a home; 'only mums can' is a myth.","persona":"Rohit","source":"roles / fathers"},
  {"id":"mb-086","cat":"role-myths","type":"match","hook":"Match the family role to who can hold it.","pairs":[{"left":"Earning money","right":"Either parent"},{"left":"Raising the kids","right":"Either parent"},{"left":"Cooking daily","right":"Anyone at home"}],"relearn":"Earning, raising and cooking can each be done by any parent.","persona":"Rohit","source":"roles / shared"},
  {"id":"mb-087","cat":"ability-myths","type":"reflect","hook":"Lensy: a dad notices his daughter is brilliant at maths. What should that tell us all?","prompt":"What do you think?","options":["Ability isn't gendered","Encourage every kid","Drop the myth"],"affirm":"Every child's talent is worth backing, whatever their gender.","relearn":"Children's talent isn't gendered; back every kid's strengths.","persona":"Rohit","source":"ability / parenting"},
  {"id":"mb-088","cat":"its-just-science","type":"branch","hook":"You bring a 'science says men are smarter' claim to a counsellor to check.","options":[{"text":"Ask them to help you find the real evidence","consequence":"You learn the careful science debunks it.","outcome":"critical","best":true},{"text":"Just trust the claim because it sounded confident","consequence":"A counsellor can help you check; the real science disagrees."}],"debrief":"A trusted adult can help you separate real science from pseudo-science.","relearn":"Ask a trusted adult to help you fact-check big gender claims.","persona":"Counsellor","source":"critical thinking / help-seeking"},
  {"id":"mb-089","cat":"equality-myths","type":"sort","hook":"Sort: a fact about equality in India, or a myth?","items":[{"id":"a","text":"India has had a woman Prime Minister"},{"id":"b","text":"India has a woman President now"},{"id":"c","text":"'Women have never led India'"},{"id":"d","text":"A law reserves seats for women in legislatures"}],"bins":[{"id":"fact","label":"Fact"},{"id":"myth","label":"Myth"}],"key":{"a":"fact","b":"fact","c":"myth","d":"fact"},"relearn":"India has had women leaders and a women's reservation law; 'women never led' is a myth.","persona":"Counsellor","source":"India equality facts (verified)"},
  {"id":"mb-090","cat":"emotion-leadership","type":"role-play","hook":"A classmate calls a boy 'girly' for being gentle and kind.","setup":"Flip it. Say:","yourLine":[{"text":"\"Kindness is a strength in anyone, full stop.\"","best":true},{"text":"Laugh along to fit in"}],"relearn":"Kindness is a strength in anyone; defend boys who show it.","persona":"any","source":"masculinity / voice"},
];

export const MYTHBUSTER: V2GameConfig = {
  gameId: "mythbuster-lab",
  title: "MythBuster: Gender",
  greet: "It's Lensy. 🧪 Heard a gender 'fact' that didn't sit right? Let's bust the fake science and write the truth — equality lifts everyone, boys included.",
  scenarios: SCENARIOS,
  categories: [
    { id: "ability-myths", emoji: "🧠", label: "Ability myths" },
    { id: "role-myths", emoji: "🔄", label: "Role myths" },
    { id: "emotion-leadership", emoji: "🗣️", label: "Emotion & leading" },
    { id: "its-just-science", emoji: "🔬", label: "'Just science'?" },
    { id: "equality-myths", emoji: "⚖️", label: "Equality myths" },
    { id: "spot-and-flip", emoji: "🕵️", label: "Spot it & flip it" },
  ],
  badge: {
    title: "MythBuster! 🧪",
    blurb: "You can spot a gender myth, see through fake 'just science', and know the truth: ability and roles aren't gendered, and equality frees everyone — boys too. ⚖️",
  },
  helpLine: "Facing unfair treatment or harassment over your gender? You don't have to handle it alone — tell a trusted adult or call Childline on one-zero-nine-eight.",
  helpLabel: "Get help · Childline 1098",
};
