// Content for Navigating Addictions (node g68, Parent Layer, Chapter 8) — NEW v2 build to GDD 68
// (mechanic-embodying), a HIGH-CARE Parent-Layer pillar. The core insight: shame and punishment drive addiction
// UNDERGROUND, while calm, connection and the right help bring it into the light. 84 researched, India-grounded
// scenarios across spot-the-signs → respond-dont-rupture → its-a-health-issue → get-the-right-help →
// screens-and-modelling → tools-and-safety, each encoded as one of the shared v2 play actions (strike-rewrite /
// branch / role-play / sort / match / reflect / spot) — no binary "tap the right card". Lead: strike-rewrite (bust
// the myth), branch (your move), role-play (say it). Six modes: spot the signs (warning signs of substance &
// screen/gaming dependence, typical vs concerning, calm noticing not panic or snooping; gaming disorder is a
// recognised condition), respond don't rupture (busts 'crack down / it's just willpower / good kids don't / shame
// will scare them straight'; connection over control & surveillance; firm about the behaviour and unconditionally
// there for the child), it's a health issue (dependence is a treatable health condition involving brain, genes &
// environment — not weak willpower or a moral failing; treatment works and recovery is real), get the right help
// (counselling & de-addiction services EARLY; family involvement strongly improves outcomes; routes to Tele-MANAS
// 14416 and Childline 1098), screens and modelling (calm agreed screen limits the WHOLE family keeps, healthy
// outlets, honestly tending your OWN substance & screen habits), tools and safety (a signs-and-help-finder &
// calm-response plan; any acute risk such as a possible overdose or danger is an EMERGENCY — route immediately to
// 112 or a hospital). HIGH-CARE and firmly non-shaming of both child AND parent; frames dependence as health, not
// moral failure; NEVER provides any how-to for obtaining or using substances; treats acute risk as an emergency;
// NOT medical advice — points to professionals. Builds on Bounce (g39) and connects to the screen-literacy thread
// (Reality Check g28, Decoded g36). India: youth substance use and screen/gaming dependence are both rising while
// stigma and harsh punitive responses are common — exactly what drives the problem deeper — so the node
// de-stigmatises and signposts real help. gameId "navigating-addictions".
import type { V2GameConfig, Scenario } from "./v2-schema";

const SCENARIOS: Scenario[] = [
  {"id":"na-001","cat":"spot-the-signs","type":"strike-rewrite","hook":"\"A good kid would never get into substances or get hooked on screens.\"","myth":{"un":"A good kid would never get into substances or get hooked on screens.","re":"Dependence can affect any child from any family; it's about a developing brain and pressures, not about being a 'bad' kid.","why":"It isn't a verdict on your child or your parenting."},"relearn":"Dependence can affect any child; it's not a sign of a 'bad' kid or bad parenting, and it can be addressed.","persona":"Vikram","source":"any kid"},
  {"id":"na-002","cat":"spot-the-signs","type":"sort","hook":"Sort: a possible warning sign worth gently checking, or ordinary teen behaviour?","items":[{"id":"a","text":"Secrecy, withdrawal and lost interest in everything else"},{"id":"b","text":"Wanting some more privacy"},{"id":"c","text":"Skipping sleep, school and meals for a habit"},{"id":"d","text":"Enjoying time with friends"}],"bins":[{"id":"sign","label":"Worth checking"},{"id":"ordinary","label":"Ordinary"}],"key":{"a":"sign","b":"ordinary","c":"sign","d":"ordinary"},"relearn":"Withdrawal, lost interest and skipping life for a habit are worth checking; wanting privacy or seeing friends is ordinary.","persona":"any","source":"sign vs ordinary"},
  {"id":"na-003","cat":"spot-the-signs","type":"strike-rewrite","hook":"\"Screen and gaming overuse isn't a real problem, only drugs count.\"","myth":{"un":"Screen and gaming overuse isn't a real problem, only drugs count.","re":"Gaming disorder is a recognised condition, and screen or phone dependence can genuinely disrupt a child's sleep, mood and life.","why":"Behavioural dependence is real too."},"relearn":"Screen and gaming dependence is real and recognised; it can disrupt a child's sleep, mood and life, not just substances.","persona":"Priya","source":"screens count too"},
  {"id":"na-004","cat":"spot-the-signs","type":"match","hook":"Match each area to a sign that it may have tipped into dependence.","pairs":[{"left":"Substances","right":"Hiding use, needing more, can't stop"},{"left":"Gaming or screens","right":"Gaming over sleep, school and everything else"},{"left":"Either","right":"Distress or conflict when it's taken away"}],"relearn":"Across substances and screens, the signs of dependence are loss of control, escalation and disruption of normal life.","persona":"any","source":"signs by area"},
  {"id":"na-005","cat":"spot-the-signs","type":"reflect","hook":"Lensy: noticing early, with calm not panic, gives you the best chance to help. Sit right?","prompt":"What do you think?","options":["Sits right","Calm not panic","Notice early"],"affirm":"Noticing signs early and calmly, rather than panicking or ignoring them, gives you the best chance to help.","relearn":"Noticing early, with calm rather than panic, gives you the best chance to help.","persona":"any","source":"notice early"},
  {"id":"na-006","cat":"spot-the-signs","type":"spot","hook":"Spot the calm, helpful way to read a possible warning sign.","scene":[{"id":"a","text":"Staying curious and gently checking in","trick":false},{"id":"b","text":"Jumping to accusations and panic","trick":true},{"id":"c","text":"Looking at the whole picture over time","trick":false}],"why":"Curiosity, gentle check-ins and the whole picture are helpful; jumping to accusations and panic shut a child down.","relearn":"Read warning signs with curiosity and the whole picture, not panic and accusations.","persona":"Divya","source":"calm reading"},
  {"id":"na-007","cat":"spot-the-signs","type":"branch","hook":"You notice changes that worry you in your teen.","options":[{"text":"Stay observant and open the door gently to talk","consequence":"You learn what's going on without rupture.","outcome":"gentle","best":true},{"text":"Confront them with accusations immediately","consequence":"Staying open and gentle helps you learn what's going on; immediate accusations make a worried teen hide and deny."}],"debrief":"Meet worrying changes by staying observant and opening the door gently, not with immediate accusations.","relearn":"Open the door gently when worried; accusations make a teen hide what you most need to understand.","persona":"Vikram","source":"open the door"},
  {"id":"na-008","cat":"spot-the-signs","type":"strike-rewrite","hook":"\"If I just search their things, I'll know everything and fix it.\"","myth":{"un":"If I just search their things, I'll know everything and fix it.","re":"Surveillance alone breaks trust and drives a child further underground; connection reveals more than searching ever will.","why":"Trust opens doors that snooping slams shut."},"relearn":"Surveillance alone breaks trust and drives a child underground; connection reveals more than searching does.","persona":"any","source":"connection over snooping"},
  {"id":"na-009","cat":"spot-the-signs","type":"reflect","hook":"Lensy: the goal isn't to catch your child, it's to reach them. Feel the difference?","prompt":"What's your take?","options":["Feel it","Reach not catch","Yes"],"affirm":"The aim with a struggling child isn't to catch them out but to reach them, which keeps the door open to help.","relearn":"The goal isn't to catch your child, it's to reach them.","persona":"any","source":"reach not catch"},
  {"id":"na-010","cat":"spot-the-signs","type":"sort","hook":"Sort: helps you spot dependence early, or misses or worsens it?","items":[{"id":"a","text":"Knowing the real warning signs"},{"id":"b","text":"Assuming it could never be your kid"},{"id":"c","text":"Calm, ongoing connection"},{"id":"d","text":"Only reacting once it's a crisis"}],"bins":[{"id":"helps","label":"Helps you spot it"},{"id":"misses","label":"Misses or worsens"}],"key":{"a":"helps","b":"misses","c":"helps","d":"misses"},"relearn":"Knowing the signs and calm connection help you spot it early; denial and waiting for a crisis miss or worsen it.","persona":"any","source":"spot or miss"},
  {"id":"na-011","cat":"respond-dont-rupture","type":"strike-rewrite","hook":"\"The way to stop it is to crack down hard, punish and threaten.\"","myth":{"un":"The way to stop it is to crack down hard, punish and threaten.","re":"Harsh crackdowns and threats usually drive it underground; calm, connected responses keep a child reachable and willing to get help.","why":"Connection works where fear fails."},"relearn":"Cracking down with punishment and threats drives it underground; calm, connected responses keep a child reachable.","persona":"Vikram","source":"connection over crackdown"},
  {"id":"na-012","cat":"respond-dont-rupture","type":"strike-rewrite","hook":"\"Shaming my child about it will scare them into stopping.\"","myth":{"un":"Shaming my child about it will scare them into stopping.","re":"Shame drives dependence underground and deepens it; a child who feels safe to be honest is far easier to help.","why":"Shame closes the door you need open."},"relearn":"Shaming a child about dependence drives it underground; safety to be honest is what makes help possible.","persona":"Vikram","source":"shame drives it under"},
  {"id":"na-013","cat":"respond-dont-rupture","type":"branch","hook":"You've just discovered your teen is using something, and you're furious and scared.","options":[{"text":"Take a breath and respond with calm concern, not an explosion","consequence":"Your teen stays willing to talk and get help.","outcome":"calm","best":true},{"text":"Explode, punish, and shut down the conversation","consequence":"Calm concern keeps your teen talking and reachable; an explosion makes them hide, lie and feel they can't come to you."}],"debrief":"When you discover use, respond with calm concern rather than an explosion, so your teen stays reachable.","relearn":"Respond to a discovery with calm concern, not an explosion; rupture sends a struggling teen underground.","persona":"Vikram","source":"calm not explosion"},
  {"id":"na-014","cat":"respond-dont-rupture","type":"match","hook":"Match each instinct to the connecting response that works better.","pairs":[{"left":"'You're grounded forever'","right":"'I'm worried about you, let's talk'"},{"left":"'How could you do this to us'","right":"'You can be honest with me'"},{"left":"'You're a disappointment'","right":"'We'll face this together'"}],"relearn":"Each punitive instinct has a connecting response that keeps a child reachable and willing to accept help.","persona":"Vikram","source":"connecting responses"},
  {"id":"na-015","cat":"respond-dont-rupture","type":"role-play","hook":"Your child admits they've been using or can't stop gaming. You want your first words to keep them safe and talking.","setup":"Respond with calm care:","yourLine":[{"text":"\"Thank you for telling me, I'm not angry, I'm worried, and we'll get through this together.\"","best":true},{"text":"\"I knew it. You've ruined everything, get out of my sight.\""}],"relearn":"A calm 'thank you for telling me, we'll get through this together' keeps a struggling child safe and reachable.","persona":"Vikram","source":"first words"},
  {"id":"na-016","cat":"respond-dont-rupture","type":"reflect","hook":"Lensy: a child who fears your reaction hides; a child who trusts it comes to you. Which keeps them safer?","prompt":"What do you think?","options":["Trust keeps them safe","Come to me","Calm wins"],"affirm":"A child who trusts your calm reaction will come to you, which keeps them far safer than one who hides in fear.","relearn":"A child who fears your reaction hides; one who trusts it comes to you, and that keeps them safer.","persona":"any","source":"trust keeps safe"},
  {"id":"na-017","cat":"respond-dont-rupture","type":"spot","hook":"Spot the response that keeps a struggling child reachable.","scene":[{"id":"a","text":"Calm concern and an open door","trick":false},{"id":"b","text":"Rage, threats and humiliation","trick":true},{"id":"c","text":"'We'll face this together'","trick":false}],"why":"Calm concern and 'we'll face this together' keep a child reachable; rage and humiliation drive them away.","relearn":"Keep a struggling child reachable with calm concern and togetherness, not rage and humiliation.","persona":"any","source":"stay reachable"},
  {"id":"na-018","cat":"respond-dont-rupture","type":"strike-rewrite","hook":"\"Cutting off all connection until they 'sort themselves out' will teach them.\"","myth":{"un":"Cutting off all connection until they 'sort themselves out' will teach them.","re":"Connection is the most protective thing you have; withdrawing it removes the lifeline a struggling child most needs.","why":"Stay connected, especially when it's hard."},"relearn":"Cutting off connection removes a struggling child's lifeline; staying connected is the most protective thing you can do.","persona":"Vikram","source":"stay the lifeline"},
  {"id":"na-019","cat":"respond-dont-rupture","type":"branch","hook":"Your child lies to you about their use, and you feel betrayed.","options":[{"text":"Address the behaviour while keeping the relationship and door open","consequence":"You hold a limit without losing your child.","outcome":"both","best":true},{"text":"Declare you can never trust them again","consequence":"Addressing the behaviour while keeping the door open holds a limit and your child; declaring all trust gone severs the lifeline."}],"debrief":"Address lying about use while keeping the relationship and door open; don't sever the connection a child needs.","relearn":"Hold the limit and the relationship both; 'I can never trust you' cuts the lifeline a struggling child relies on.","persona":"Divya","source":"limit and door"},
  {"id":"na-020","cat":"respond-dont-rupture","type":"reflect","hook":"Lensy: you can be firm about the behaviour and unconditionally there for the child, at the same time. Sit right?","prompt":"What's your take?","options":["Sits right","Firm and there","Both at once"],"affirm":"You can hold firm limits about the behaviour while being unconditionally there for the child; both at once is the goal.","relearn":"You can be firm about the behaviour and unconditionally there for the child at the same time.","persona":"any","source":"firm and there"},
  {"id":"na-021","cat":"its-a-health-issue","type":"strike-rewrite","hook":"\"Addiction is just weak willpower or a moral failing.\"","myth":{"un":"Addiction is just weak willpower or a moral failing.","re":"Addiction is a treatable health condition involving the brain, genes and environment, not simply weakness or bad character.","why":"It's a health issue, and health issues have treatments."},"relearn":"Addiction is a treatable health condition, not weak willpower or a moral failing.","persona":"Vikram","source":"health not weakness"},
  {"id":"na-022","cat":"its-a-health-issue","type":"strike-rewrite","hook":"\"If my child were strong enough, they'd just stop on their own.\"","myth":{"un":"If my child were strong enough, they'd just stop on their own.","re":"Dependence changes the brain's reward system, making 'just stop' very hard; that's why support and treatment matter.","why":"It's not about strength; it's about help."},"relearn":"Dependence changes the brain, so 'just stop' is very hard; it isn't about strength, it's about getting support.","persona":"Vikram","source":"not about strength"},
  {"id":"na-023","cat":"its-a-health-issue","type":"sort","hook":"Sort: a fact that helps, or a stigma that harms, a child with dependence?","items":[{"id":"a","text":"It's a treatable health condition"},{"id":"b","text":"'They're just bad or weak'"},{"id":"c","text":"Recovery is possible with support"},{"id":"d","text":"'It's a hopeless disgrace'"}],"bins":[{"id":"helps","label":"Helpful fact"},{"id":"stigma","label":"Harmful stigma"}],"key":{"a":"helps","b":"stigma","c":"helps","d":"stigma"},"relearn":"'Treatable health condition' and 'recovery is possible' help; 'bad or weak' and 'hopeless disgrace' are harmful stigma.","persona":"any","source":"fact vs stigma"},
  {"id":"na-024","cat":"its-a-health-issue","type":"reflect","hook":"Lensy: seeing dependence as a health issue, not a disgrace, changes everything about how you respond. Resonate?","prompt":"What do you think?","options":["Resonates","Health not disgrace","Changes everything"],"affirm":"Viewing dependence as a treatable health issue rather than a disgrace shifts a parent from punishment toward effective help.","relearn":"Seeing dependence as a health issue, not a disgrace, changes how you respond, toward help.","persona":"any","source":"health not disgrace"},
  {"id":"na-025","cat":"its-a-health-issue","type":"strike-rewrite","hook":"\"Treatment doesn't work; once an addict, always an addict.\"","myth":{"un":"Treatment doesn't work; once an addict, always an addict.","re":"Addiction can be managed successfully; people who get and stay in treatment can recover and rebuild good lives.","why":"Recovery is real and common."},"relearn":"Treatment works; addiction can be managed and people recover and rebuild good lives with support.","persona":"Vikram","source":"recovery is real"},
  {"id":"na-026","cat":"its-a-health-issue","type":"match","hook":"Match each health-issue truth to what it means for your child.","pairs":[{"left":"It's treatable","right":"There's real hope and a path"},{"left":"It's not a moral failing","right":"Less shame, more honesty"},{"left":"Support improves outcomes","right":"Getting help is the strong move"}],"relearn":"Seeing dependence as treatable, not a moral failing, and helped by support gives a child hope, honesty and a path.","persona":"any","source":"health truths"},
  {"id":"na-027","cat":"its-a-health-issue","type":"reflect","hook":"Lensy: you'd get your child help for any other illness without shame; this deserves the same. Sit right?","prompt":"What's your take?","options":["Sits right","Same as any illness","No shame"],"affirm":"Dependence deserves the same shame-free, get-help response you'd give any other illness your child faced.","relearn":"You'd get your child help for any other illness without shame; this deserves the same.","persona":"any","source":"same as any illness"},
  {"id":"na-028","cat":"its-a-health-issue","type":"spot","hook":"Spot the health-issue framing that helps a child recover.","scene":[{"id":"a","text":"'This is treatable, let's get help'","trick":false},{"id":"b","text":"'You're a hopeless addict'","trick":true},{"id":"c","text":"'Recovery is possible, I believe in you'","trick":false}],"why":"'Treatable, let's get help' and 'recovery is possible' help recovery; 'hopeless addict' deepens shame and despair.","relearn":"Frame dependence as treatable with hope, not as a hopeless, shameful identity.","persona":"any","source":"framing for recovery"},
  {"id":"na-029","cat":"its-a-health-issue","type":"branch","hook":"You feel your child's dependence is a source of family shame to hide.","options":[{"text":"Treat it as a health challenge to face openly and get help for","consequence":"You free your child and family to heal.","outcome":"openly","best":true},{"text":"Hide it and let shame block help","consequence":"Facing it as a health challenge frees you to get help; hiding it in shame blocks the very support your child needs."}],"debrief":"Treat dependence as a health challenge to face and get help for, not a family shame to hide.","relearn":"Face dependence openly as a health issue; hiding it in shame just blocks the help your child needs.","persona":"Kamla","source":"face it openly"},
  {"id":"na-030","cat":"get-the-right-help","type":"strike-rewrite","hook":"\"We should handle this entirely within the family and tell no professional.\"","myth":{"un":"We should handle this entirely within the family and tell no professional.","re":"Dependence usually needs professional help; counsellors and de-addiction services know what works, and family plus help is strongest.","why":"Asking for help is wise, not weak."},"relearn":"Dependence usually needs professional help; counsellors and de-addiction services work best alongside family support.","persona":"Vikram","source":"get professional help"},
  {"id":"na-031","cat":"get-the-right-help","type":"branch","hook":"You realise your child's dependence is beyond what you can manage alone.","options":[{"text":"Reach out early to a counsellor or de-addiction service","consequence":"Your child gets effective, evidence-based help.","outcome":"early-help","best":true},{"text":"Wait and hope it resolves itself","consequence":"Reaching out early gets effective help; waiting and hoping usually lets dependence deepen and harm grow."}],"debrief":"Reach out early to a counsellor or de-addiction service when dependence is beyond what you can manage alone.","relearn":"Get professional help early rather than waiting; effective, evidence-based treatment exists.","persona":"Vikram","source":"reach out early"},
  {"id":"na-032","cat":"get-the-right-help","type":"match","hook":"Match each India support to what it offers.","pairs":[{"left":"Tele-MANAS 14416","right":"Mental-health and addiction support, any time"},{"left":"A de-addiction centre / counsellor","right":"Assessment and structured treatment"},{"left":"Childline 1098","right":"Help for a child in distress or danger"}],"relearn":"Tele-MANAS, de-addiction services and Childline are real routes for a family navigating a child's dependence.","persona":"any","source":"the help routes"},
  {"id":"na-033","cat":"get-the-right-help","type":"strike-rewrite","hook":"\"Family involvement doesn't matter once a child is in treatment.\"","myth":{"un":"Family involvement doesn't matter once a child is in treatment.","re":"Family-based support strongly improves outcomes; a calm, connected, involved parent is part of what makes treatment work.","why":"You're part of the treatment, not outside it."},"relearn":"Family involvement strongly improves outcomes; a calm, connected parent is part of what makes treatment work.","persona":"Divya","source":"family helps treatment"},
  {"id":"na-034","cat":"get-the-right-help","type":"sort","hook":"Sort: a step toward effective help, or a barrier to it?","items":[{"id":"a","text":"Seeking a professional assessment"},{"id":"b","text":"Shame that stops you asking"},{"id":"c","text":"Staying involved in treatment"},{"id":"d","text":"Believing nothing can help"}],"bins":[{"id":"step","label":"Step toward help"},{"id":"barrier","label":"A barrier"}],"key":{"a":"step","b":"barrier","c":"step","d":"barrier"},"relearn":"Assessment and staying involved are steps toward help; shame and hopelessness are barriers to it.","persona":"any","source":"step or barrier"},
  {"id":"na-035","cat":"get-the-right-help","type":"reflect","hook":"Lensy: getting help early, before crisis, gives your child the best chance, just like any health issue. Worth it?","prompt":"What do you think?","options":["Worth it","Early is best","Best chance"],"affirm":"Getting help early, before a crisis, gives a child the best chance of recovery, as with any health condition.","relearn":"Getting help early, before crisis, gives your child the best chance.","persona":"any","source":"early help best"},
  {"id":"na-036","cat":"get-the-right-help","type":"role-play","hook":"Your partner resists getting outside help out of shame. You want to bring them on board.","setup":"Bring them on board:","yourLine":[{"text":"\"This is a health issue and help works, getting it isn't shameful, it's how we protect our child.\"","best":true},{"text":"\"Fine, we'll just keep pretending everything is okay.\""}],"relearn":"Framing help as protecting your child, not a shameful admission, helps a reluctant partner accept it.","persona":"Kamla","source":"partner on board"},
  {"id":"na-037","cat":"get-the-right-help","type":"spot","hook":"Spot the move that gets a child real, lasting help.","scene":[{"id":"a","text":"Early professional support plus family involvement","trick":false},{"id":"b","text":"A one-off threat and hoping for the best","trick":true},{"id":"c","text":"Treating it as a health issue with a plan","trick":false}],"why":"Early professional support with family involvement and a real plan get lasting help; threats and hoping don't.","relearn":"Lasting help comes from early professional support, family involvement and a plan, not threats and hoping.","persona":"any","source":"real help"},
  {"id":"na-038","cat":"screens-and-modelling","type":"strike-rewrite","hook":"\"My own drinking, smoking or phone habits have nothing to do with my child.\"","myth":{"un":"My own drinking, smoking or phone habits have nothing to do with my child.","re":"Children learn habits by watching; honestly looking at what you model is part of helping your child with theirs.","why":"Kids copy what they see at home."},"relearn":"Your own substance and screen habits are part of the picture; children learn by watching what you model.","persona":"Kamla","source":"model honestly"},
  {"id":"na-039","cat":"screens-and-modelling","type":"sort","hook":"Sort: a healthy screen boundary, or one that backfires?","items":[{"id":"a","text":"Agreed screen-free times, for everyone"},{"id":"b","text":"A sudden, total, angry ban"},{"id":"c","text":"Devices out of bedrooms at night"},{"id":"d","text":"Rules for the child but not the parent"}],"bins":[{"id":"healthy","label":"Healthy boundary"},{"id":"backfire","label":"Backfires"}],"key":{"a":"healthy","b":"backfire","c":"healthy","d":"backfire"},"relearn":"Agreed screen-free times and no devices at night are healthy; angry total bans and one-rule-for-the-child backfire.","persona":"any","source":"boundary or backfire"},
  {"id":"na-040","cat":"screens-and-modelling","type":"strike-rewrite","hook":"\"The best way to handle screens is a sudden, total ban with no discussion.\"","myth":{"un":"The best way to handle screens is a sudden, total ban with no discussion.","re":"Calm, consistent, agreed limits and replacing screen time with other good things work better than a sudden, total ban.","why":"Steady limits beat shock bans."},"relearn":"Calm, agreed, consistent screen limits work better than a sudden total ban with no discussion.","persona":"Priya","source":"steady limits"},
  {"id":"na-041","cat":"screens-and-modelling","type":"branch","hook":"You want to set screen limits but realise you're glued to your own phone.","options":[{"text":"Set shared limits and model them yourself too","consequence":"Your limits gain real credibility.","outcome":"model","best":true},{"text":"Demand the child unplug while you scroll","consequence":"Modelling shared limits gives them credibility; demanding the child unplug while you scroll teaches the rule is fake."}],"debrief":"Set screen limits the whole family keeps, modelling them yourself, rather than one rule for the child only.","relearn":"Model the screen limits you set; 'unplug while I scroll' tells a child the rule isn't real.","persona":"Kamla","source":"model the limits"},
  {"id":"na-042","cat":"screens-and-modelling","type":"match","hook":"Match each healthy-habit area to a simple family practice.","pairs":[{"left":"Screens","right":"Agreed limits and screen-free meals"},{"left":"Stress and boredom","right":"Healthy outlets, not numbing"},{"left":"Modelling","right":"Parents keep the rules too"}],"relearn":"Agreed screen limits, healthy outlets for stress, and parents keeping the rules are simple practices that protect a child.","persona":"any","source":"habit practices"},
  {"id":"na-043","cat":"screens-and-modelling","type":"reflect","hook":"Lensy: kids learn how to handle stress, screens and substances largely from watching us. Worth a look at our own habits?","prompt":"What do you think?","options":["Worth it","Look at my own","They watch us"],"affirm":"Children learn how to handle stress, screens and substances largely by watching their parents, so our own habits matter.","relearn":"Kids learn how to handle stress, screens and substances by watching us; our own habits are worth a look.","persona":"Kamla","source":"look at our habits"},
  {"id":"na-044","cat":"screens-and-modelling","type":"spot","hook":"Spot what genuinely helps a child build healthy habits.","scene":[{"id":"a","text":"Parents modelling balance","trick":false},{"id":"b","text":"Do-as-I-say-not-as-I-do rules","trick":true},{"id":"c","text":"Shared limits and good alternatives","trick":false}],"why":"Parents modelling balance and shared limits help; do-as-I-say-not-as-I-do rules undermine a child's habits.","relearn":"Help a child build healthy habits by modelling balance and shared limits, not do-as-I-say rules.","persona":"any","source":"build healthy habits"},
  {"id":"na-045","cat":"screens-and-modelling","type":"branch","hook":"You recognise your own habit may be a problem while you address your child's.","options":[{"text":"Address your own with the same compassion you give your child","consequence":"You model recovery and honesty.","outcome":"own-habit","best":true},{"text":"Focus only on the child and ignore your own","consequence":"Addressing your own habit compassionately models recovery and honesty; ignoring it undercuts everything you ask of your child."}],"debrief":"Address your own habit with the same compassion you offer your child; modelling recovery is powerful.","relearn":"Tend your own habit too, with compassion; ignoring it while policing your child's undercuts the message.","persona":"Kamla","source":"own habit too"},
  {"id":"na-046","cat":"tools-and-safety","type":"branch","hook":"You want to be ready to respond well if you discover a problem.","options":[{"text":"Know the signs, plan a calm response, and save the help numbers","consequence":"You can act with calm and care, not panic.","outcome":"ready","best":true},{"text":"Assume you'll figure it out in the heat of the moment","consequence":"Knowing the signs and saving help numbers lets you act calmly; figuring it out mid-crisis is far harder."}],"debrief":"Be ready: know the signs, plan a calm response, and save the help numbers before you need them.","relearn":"Prepare a calm response and saved help numbers now; mid-crisis is the hardest time to plan.","persona":"Vikram","source":"be ready"},
  {"id":"na-047","cat":"tools-and-safety","type":"match","hook":"Match each tool to what it does.","pairs":[{"left":"A signs-and-help-finder","right":"Knowing what to watch for and where to turn"},{"left":"A calm-response plan","right":"Responding without rupture"},{"left":"Saved help lines","right":"Support and emergencies covered"}],"relearn":"A signs-and-help-finder, a calm-response plan and saved help lines are the core tools for navigating a child's dependence.","persona":"any","source":"the toolkit"},
  {"id":"na-048","cat":"tools-and-safety","type":"strike-rewrite","hook":"\"An app or game can treat my child's addiction.\"","myth":{"un":"An app or game can treat my child's addiction.","re":"This helps you understand and respond, but it isn't treatment; counsellors and de-addiction services provide that.","why":"Support tools point to care; they don't replace it."},"relearn":"This supports understanding and response but isn't treatment; professionals provide that.","persona":"any","source":"not treatment"},
  {"id":"na-049","cat":"tools-and-safety","type":"branch","hook":"There's an acute emergency, a possible overdose, or your child is in danger.","options":[{"text":"Treat it as an emergency and get medical help immediately","consequence":"You act fast to keep your child safe.","outcome":"emergency","best":true},{"text":"Wait to see if it passes on its own","consequence":"Treating it as an emergency and getting help fast can save a life; waiting risks irreversible harm."}],"debrief":"Treat a possible overdose or any acute danger as an emergency and get medical help immediately (112, a hospital).","relearn":"Act immediately in an acute emergency like a possible overdose; get medical help now, don't wait it out.","persona":"Vikram","source":"emergency now"},
  {"id":"na-050","cat":"tools-and-safety","type":"sort","hook":"Sort: a wise move in a serious situation, or one to avoid?","items":[{"id":"a","text":"Calling emergency help for acute danger"},{"id":"b","text":"Hiding it to avoid embarrassment"},{"id":"c","text":"Reaching a helpline when unsure"},{"id":"d","text":"Punishing instead of getting help"}],"bins":[{"id":"wise","label":"Wise move"},{"id":"avoid","label":"To avoid"}],"key":{"a":"wise","b":"avoid","c":"wise","d":"avoid"},"relearn":"Calling emergency help and reaching a helpline are wise; hiding it or punishing instead of helping put a child at risk.","persona":"any","source":"wise vs avoid"},
  {"id":"na-051","cat":"tools-and-safety","type":"reflect","hook":"Lensy: in any acute danger, getting help fast always comes before worrying about shame or trouble. Clear?","prompt":"What do you think?","options":["Clear","Help first","Safety over shame"],"affirm":"In any acute danger, a child's safety and getting help fast always come before any worry about shame or trouble.","relearn":"In acute danger, get help fast; safety always comes before shame or trouble.","persona":"any","source":"safety over shame"},
  {"id":"na-052","cat":"tools-and-safety","type":"match","hook":"Match a situation to the right India support.","pairs":[{"left":"Needing to talk or find help","right":"Tele-MANAS 14416"},{"left":"A child in distress or danger","right":"Childline 1098"},{"left":"An acute medical emergency","right":"Emergency 112 or a hospital"}],"relearn":"Tele-MANAS, Childline and emergency 112 cover support, child-distress and acute emergencies as a family navigates dependence.","persona":"any","source":"right support"},
  {"id":"na-053","cat":"tools-and-safety","type":"spot","hook":"Spot the sustainable way to help a child through dependence.","scene":[{"id":"a","text":"Calm connection, early help and a plan","trick":false},{"id":"b","text":"Shame, secrecy and one big crackdown","trick":true},{"id":"c","text":"Staying involved through recovery","trick":false}],"why":"Calm connection, early help and staying involved are sustainable; shame, secrecy and a single crackdown aren't.","relearn":"Help a child through dependence with calm connection, early help and staying involved, not shame and crackdowns.","persona":"any","source":"sustainable help"},
  {"id":"na-054","cat":"tools-and-safety","type":"reflect","hook":"Lensy: spot it early, respond with calm connection, treat it as health, get help, and check your own habits. Equipped?","prompt":"What's your take?","options":["Equipped","I've got this","Ready"],"affirm":"Spotting early, responding with calm connection, treating it as health, getting help and checking your own habits equip you fully.","relearn":"You hold the kit: spot early, connect calmly, treat it as health, get help, and check your own habits.","persona":"any","source":"equipped"},
  {"id":"na-055","cat":"tools-and-safety","type":"role-play","hook":"Your co-parent wants to respond to your child's problem with harsh punishment. You want to steer toward help.","setup":"Steer toward help:","yourLine":[{"text":"\"Punishing will push him away, let's stay calm, keep him close, and get the right help together.\"","best":true},{"text":"\"Yes, let's come down on him as hard as we can.\""}],"relearn":"Steering a co-parent from punishment toward calm connection and help keeps a struggling child reachable and safe.","persona":"Divya","source":"steer to help"},
  {"id":"na-056","cat":"spot-the-signs","type":"role-play","hook":"You're worried about your teen and want to open a check-in without an interrogation. You start gently.","setup":"Start gently:","yourLine":[{"text":"\"You've seemed a bit different lately, and I'm here, no judgement, if anything's going on.\"","best":true},{"text":"\"What are you hiding from me? Tell me right now.\""}],"relearn":"A gentle, no-judgement opener invites a worried teen to talk, where an interrogation makes them clam up.","persona":"Vikram","source":"gentle check-in"},
  {"id":"na-057","cat":"spot-the-signs","type":"sort","hook":"Sort: a sign of possible dependence, or just normal ups and downs?","items":[{"id":"a","text":"Needing more and more for the same effect"},{"id":"b","text":"An off day or a bad mood"},{"id":"c","text":"Lying and sneaking to keep a habit going"},{"id":"d","text":"A new hobby they enjoy"}],"bins":[{"id":"sign","label":"Possible sign"},{"id":"normal","label":"Normal"}],"key":{"a":"sign","b":"normal","c":"sign","d":"normal"},"relearn":"Needing more for the same effect and sneaking to keep a habit going are signs; an off day or a new hobby aren't.","persona":"any","source":"sign or normal"},
  {"id":"na-058","cat":"spot-the-signs","type":"branch","hook":"You see a worrying sign but tell yourself you might be overreacting.","options":[{"text":"Take it seriously enough to gently look closer","consequence":"You catch a real issue early.","outcome":"look-closer","best":true},{"text":"Dismiss it so you don't have to deal with it","consequence":"Taking a worry seriously enough to look closer catches issues early; dismissing it can let a real problem grow."}],"debrief":"Take a worrying sign seriously enough to look closer gently, rather than dismissing it to avoid worry.","relearn":"Don't talk yourself out of a real worry; look closer gently rather than dismissing it.","persona":"Divya","source":"look closer"},
  {"id":"na-059","cat":"spot-the-signs","type":"spot","hook":"Spot the steady, helpful way to watch for dependence.","scene":[{"id":"a","text":"Noticing patterns over time, calmly","trick":false},{"id":"b","text":"One panicked search of their room","trick":true},{"id":"c","text":"Keeping the relationship open","trick":false}],"why":"Noticing patterns calmly and keeping the relationship open help; a single panicked search breaks trust.","relearn":"Watch for dependence with calm pattern-noticing and an open relationship, not one panicked search.","persona":"any","source":"steady watching"},
  {"id":"na-060","cat":"respond-dont-rupture","type":"role-play","hook":"Your child is defensive and expecting you to yell. You want to disarm that with calm.","setup":"Disarm with calm:","yourLine":[{"text":"\"I'm not here to shout at you, I love you and I want to understand and help.\"","best":true},{"text":"\"You should be ashamed of yourself.\""}],"relearn":"Leading with calm and love disarms a defensive child and keeps the conversation, and the help, possible.","persona":"Vikram","source":"disarm with calm"},
  {"id":"na-061","cat":"respond-dont-rupture","type":"sort","hook":"Sort: a response that keeps the door open, or one that slams it?","items":[{"id":"a","text":"'Let's talk, I'm on your side'"},{"id":"b","text":"'You're dead to me'"},{"id":"c","text":"Staying calm and curious"},{"id":"d","text":"Screaming and threats"}],"bins":[{"id":"open","label":"Keeps it open"},{"id":"slam","label":"Slams it shut"}],"key":{"a":"open","b":"slam","c":"open","d":"slam"},"relearn":"'I'm on your side' and calm curiosity keep the door open; 'dead to me' and screaming slam it shut.","persona":"any","source":"open or slam"},
  {"id":"na-062","cat":"respond-dont-rupture","type":"branch","hook":"You want to set a real limit without it becoming a rupture.","options":[{"text":"Pair a clear limit with warmth and connection","consequence":"You hold a boundary and the bond.","outcome":"limit-warmth","best":true},{"text":"Deliver the limit as a cold ultimatum","consequence":"Pairing a clear limit with warmth holds the boundary and the bond; a cold ultimatum often ruptures the connection."}],"debrief":"Pair a clear limit with warmth and connection so a boundary doesn't become a rupture.","relearn":"Hold limits warmly; a cold ultimatum can rupture the connection a struggling child needs.","persona":"Divya","source":"limit with warmth"},
  {"id":"na-063","cat":"respond-dont-rupture","type":"match","hook":"Match each hard moment to a connecting move.","pairs":[{"left":"They're defensive","right":"Lower your voice and your stakes"},{"left":"They lie","right":"Name it calmly, keep the door open"},{"left":"They relapse","right":"Disappointment without rejection"}],"relearn":"Defensiveness, lies and relapse each meet a connecting move that keeps a child reachable.","persona":"any","source":"connecting moves"},
  {"id":"na-064","cat":"its-a-health-issue","type":"role-play","hook":"Your child calls themselves 'a junkie' or 'hopeless'. You want to counter the shame with truth.","setup":"Counter with truth:","yourLine":[{"text":"\"You have a health problem we can treat, you're not hopeless, and I'm not giving up on you.\"","best":true},{"text":"\"Well, you've made your bed now.\""}],"relearn":"Replacing a shaming self-label with 'a treatable health problem, I'm not giving up' restores hope a child needs to recover.","persona":"Vikram","source":"counter the shame"},
  {"id":"na-065","cat":"its-a-health-issue","type":"sort","hook":"Sort: treats dependence as the health issue it is, or as a moral failing?","items":[{"id":"a","text":"Seeking treatment without blame"},{"id":"b","text":"Calling the child a disgrace"},{"id":"c","text":"Believing recovery is possible"},{"id":"d","text":"Treating it as a character flaw"}],"bins":[{"id":"health","label":"Health issue"},{"id":"moral","label":"Moral-failing view"}],"key":{"a":"health","b":"moral","c":"health","d":"moral"},"relearn":"Seeking treatment without blame and believing in recovery treat it as health; 'disgrace' and 'character flaw' don't.","persona":"any","source":"health or moral"},
  {"id":"na-066","cat":"its-a-health-issue","type":"branch","hook":"You catch yourself thinking your child's dependence makes them a bad person.","options":[{"text":"Separate the child from the condition; they're unwell, not bad","consequence":"You respond with care instead of contempt.","outcome":"separate","best":true},{"text":"Let the judgement colour how you treat them","consequence":"Separating the child from the condition lets you respond with care; judging them as 'bad' fuels the shame that deepens it."}],"debrief":"Separate your child from the condition: they have a health problem, they aren't a bad person.","relearn":"See your child as unwell, not bad; the condition isn't who they are, and care beats contempt.","persona":"Vikram","source":"child not condition"},
  {"id":"na-067","cat":"its-a-health-issue","type":"role-play","hook":"A relative dismisses your child's struggle as 'just being spoilt'. You want to reframe it firmly.","setup":"Reframe it firmly:","yourLine":[{"text":"\"It's a real health condition, not spoiling, and what helps is treatment and support, not contempt.\"","best":true},{"text":"\"Maybe you're right, we did spoil him.\""}],"relearn":"Firmly reframing dependence as a health condition needing treatment protects your child from stigma-driven contempt.","persona":"Kamla","source":"reframe to relative"},
  {"id":"na-068","cat":"its-a-health-issue","type":"spot","hook":"Spot the belief that supports a child's recovery.","scene":[{"id":"a","text":"'This is treatable and you can recover'","trick":false},{"id":"b","text":"'You're a lost cause'","trick":true},{"id":"c","text":"'I'm in your corner through this'","trick":false}],"why":"'Treatable, you can recover' and 'I'm in your corner' support recovery; 'lost cause' destroys the hope it needs.","relearn":"Support recovery with belief that it's treatable and you're in their corner, not 'lost cause' despair.","persona":"any","source":"supports recovery"},
  {"id":"na-069","cat":"get-the-right-help","type":"role-play","hook":"You're nervous about calling a de-addiction service for the first time. You picture how to begin.","setup":"Just begin honestly:","yourLine":[{"text":"\"Hello, I'm worried my child may be dependent on something, and I want to understand how to help them.\"","best":true},{"text":"\"Sorry, never mind, we'll handle it ourselves somehow.\""}],"relearn":"A simple, honest opening is all a service needs; you don't need the perfect words to start getting help.","persona":"Divya","source":"first call"},
  {"id":"na-070","cat":"get-the-right-help","type":"sort","hook":"Sort: gets a child effective help, or delays it?","items":[{"id":"a","text":"Seeing a professional early"},{"id":"b","text":"Waiting for rock bottom"},{"id":"c","text":"A family-inclusive treatment plan"},{"id":"d","text":"Keeping it a total secret"}],"bins":[{"id":"helps","label":"Gets help"},{"id":"delays","label":"Delays help"}],"key":{"a":"helps","b":"delays","c":"helps","d":"delays"},"relearn":"Early professional help and a family-inclusive plan get help; waiting for rock bottom and secrecy delay it.","persona":"any","source":"helps or delays"},
  {"id":"na-071","cat":"get-the-right-help","type":"branch","hook":"The first help you try doesn't seem to fit your child.","options":[{"text":"Keep looking for the right professional or approach","consequence":"You find the support that works for them.","outcome":"keep-looking","best":true},{"text":"Conclude that nothing and no one can help","consequence":"Persisting to find the right fit gets effective help; concluding nothing helps abandons a child who is treatable."}],"debrief":"If the first help doesn't fit, keep looking for the right professional or approach rather than giving up.","relearn":"Keep searching for the right-fit help; one poor fit doesn't mean nothing can help your child.","persona":"Vikram","source":"keep looking"},
  {"id":"na-072","cat":"get-the-right-help","type":"match","hook":"Match each worry about getting help to the reassuring truth.","pairs":[{"left":"'It's shameful to ask'","right":"It's wise, like any health issue"},{"left":"'It won't work'","right":"Treatment helps and recovery is real"},{"left":"'We're alone in this'","right":"Services and helplines are there"}],"relearn":"Each worry about getting help has a reassurance: it's wise, treatment works, and you're not alone.","persona":"any","source":"worry to truth"},
  {"id":"na-073","cat":"get-the-right-help","type":"role-play","hook":"Your struggling child resists treatment. You want to encourage them without force.","setup":"Encourage gently:","yourLine":[{"text":"\"I'll be with you every step, getting help is brave, and you don't have to face this alone.\"","best":true},{"text":"\"Go to rehab or you're out of this house.\""}],"relearn":"Encouraging with companionship and 'you're not alone' invites a child toward help better than threats and ultimatums.","persona":"Vikram","source":"encourage to treatment"},
  {"id":"na-074","cat":"get-the-right-help","type":"spot","hook":"Spot the move that opens the door to real help.","scene":[{"id":"a","text":"Reaching out early without shame","trick":false},{"id":"b","text":"Hiding it until it explodes","trick":true},{"id":"c","text":"Involving the family in treatment","trick":false}],"why":"Reaching out early and involving the family open the door to help; hiding it until crisis closes it.","relearn":"Open the door to help by reaching out early and involving the family, not hiding it until crisis.","persona":"any","source":"open to help"},
  {"id":"na-075","cat":"screens-and-modelling","type":"role-play","hook":"Your child says your phone use is hypocritical when you set their limits. You want to respond with honesty.","setup":"Respond honestly:","yourLine":[{"text":"\"You're right, and I'm going to follow the same limits, we'll do this together as a family.\"","best":true},{"text":"\"Don't be cheeky, the rules are for you, not me.\""}],"relearn":"Owning the hypocrisy and committing to the same limits gives the rules integrity and models honesty.","persona":"Kamla","source":"own the hypocrisy"},
  {"id":"na-076","cat":"screens-and-modelling","type":"sort","hook":"Sort: a habit that helps a child manage screens, or one that fuels dependence?","items":[{"id":"a","text":"Screen-free family meals"},{"id":"b","text":"Endless unstructured screen time"},{"id":"c","text":"Good offline things to do"},{"id":"d","text":"Screens as the only way to cope"}],"bins":[{"id":"helps","label":"Helps manage it"},{"id":"fuels","label":"Fuels dependence"}],"key":{"a":"helps","b":"fuels","c":"helps","d":"fuels"},"relearn":"Screen-free meals and good offline options help; endless screen time and screens-as-only-coping fuel dependence.","persona":"any","source":"helps or fuels"},
  {"id":"na-077","cat":"screens-and-modelling","type":"branch","hook":"You want to reduce your child's gaming but they have nothing else to fill the time.","options":[{"text":"Replace screen time with appealing offline activities together","consequence":"You crowd out the habit with better things.","outcome":"replace","best":true},{"text":"Just take the device and leave a void","consequence":"Replacing screen time with appealing activities crowds out the habit; just removing the device leaves a void that pulls them back."}],"debrief":"Reduce gaming by replacing it with appealing offline activities, not just removing the device and leaving a void.","relearn":"Fill the gap with better things when cutting screen time; a void just pulls a child back to the habit.","persona":"Priya","source":"replace not just remove"},
  {"id":"na-078","cat":"screens-and-modelling","type":"match","hook":"Match each modelling choice to what it teaches a child.","pairs":[{"left":"Parents off phones at dinner","right":"Connection over screens"},{"left":"Healthy ways to de-stress","right":"Coping without numbing"},{"left":"Owning your own slip-ups","right":"Honesty and growth"}],"relearn":"Parents off phones, healthy de-stressing and owning slip-ups each teach a child something that protects them.","persona":"Kamla","source":"modelling teaches"},
  {"id":"na-079","cat":"screens-and-modelling","type":"role-play","hook":"You want to set a family tech agreement together rather than imposing rules. You propose it.","setup":"Propose it together:","yourLine":[{"text":"\"Let's make a family screen plan together, fair for everyone, parents included, what should be in it?\"","best":true},{"text":"\"New rule: I confiscate phones whenever I feel like it.\""}],"relearn":"Proposing a fair family agreement everyone shapes, parents included, gets far more buy-in than imposed, arbitrary rules.","persona":"Priya","source":"family agreement"},
  {"id":"na-080","cat":"screens-and-modelling","type":"sort","hook":"Sort: models healthy habits, or models the opposite?","items":[{"id":"a","text":"Coping with stress without substances"},{"id":"b","text":"Drinking to unwind every night"},{"id":"c","text":"Balanced phone use"},{"id":"d","text":"Doom-scrolling for hours daily"}],"bins":[{"id":"healthy","label":"Models healthy"},{"id":"opposite","label":"Models the opposite"}],"key":{"a":"healthy","b":"opposite","c":"healthy","d":"opposite"},"relearn":"Coping without substances and balanced phone use model healthy habits; nightly drinking and doom-scrolling model the opposite.","persona":"Kamla","source":"models which"},
  {"id":"na-081","cat":"tools-and-safety","type":"role-play","hook":"You want to make sure both you and your co-parent know what to do in an emergency. You set the plan.","setup":"Set the plan together:","yourLine":[{"text":"\"If there's ever an emergency, we call 112 or go straight to hospital, no hesitation, agreed?\"","best":true},{"text":"\"Let's just hope nothing like that ever happens.\""}],"relearn":"Agreeing a clear emergency plan in advance means no hesitation when seconds count.","persona":"Vikram","source":"emergency plan"},
  {"id":"na-082","cat":"tools-and-safety","type":"sort","hook":"Sort: a wise preparation, or a risky gap?","items":[{"id":"a","text":"Saved helpline and emergency numbers"},{"id":"b","text":"No plan for a crisis"},{"id":"c","text":"Knowing the signs of acute danger"},{"id":"d","text":"Assuming it'll never happen to you"}],"bins":[{"id":"wise","label":"Wise preparation"},{"id":"gap","label":"Risky gap"}],"key":{"a":"wise","b":"gap","c":"wise","d":"gap"},"relearn":"Saved numbers and knowing the danger signs are wise; no crisis plan and 'never us' denial are risky gaps.","persona":"any","source":"prep or gap"},
  {"id":"na-083","cat":"tools-and-safety","type":"role-play","hook":"A friend's child is struggling and they don't know where to turn. You want to point them to help.","setup":"Point them to help:","yourLine":[{"text":"\"It's a health issue, not a disgrace, Tele-MANAS 14416 and a de-addiction counsellor are good places to start.\"","best":true},{"text":"\"That's so shameful, I wouldn't tell anyone if I were you.\""}],"relearn":"Sharing that it's a health issue with concrete help routes serves a struggling friend far better than fuelling shame.","persona":"Divya","source":"point a friend"},
  {"id":"na-084","cat":"tools-and-safety","type":"role-play","hook":"Your child is finally getting help and you want to commit to staying involved. You tell them.","setup":"Commit to staying:","yourLine":[{"text":"\"I'm in this with you for the long haul, the good days and the hard ones, you're not alone.\"","best":true},{"text":"\"There, I got you help, now it's your problem to fix.\""}],"relearn":"Committing to stay involved through recovery, good days and hard, gives a child the steady support that helps it last.","persona":"Vikram","source":"stay involved"},
];

export const NAVIGATING_ADDICTIONS: V2GameConfig = {
  gameId: "navigating-addictions",
  title: "Navigating Addictions",
  greet: "It’s Lensy. Worried about a child and substances or screens? Shame hides it; calm connection brings it to light. Dependence is treatable; recovery is real.",
  scenarios: SCENARIOS,
  categories: [
    { id: "spot-the-signs", emoji: "🔍", label: "Spot the signs" },
    { id: "respond-dont-rupture", emoji: "🤝", label: "Respond, don’t rupture" },
    { id: "its-a-health-issue", emoji: "🩺", label: "It’s a health issue" },
    { id: "get-the-right-help", emoji: "🆘", label: "Get the right help" },
    { id: "screens-and-modelling", emoji: "📱", label: "Screens & modelling" },
    { id: "tools-and-safety", emoji: "🧰", label: "Tools & safety" },
  ],
  badge: {
    title: "Navigating Addictions 🎮",
    blurb: "You know connection beats shame: spot the signs calmly, stay firm yet there, treat dependence as a health issue not a failing, and get help early. 🩺",
  },
  helpLine: "Dependence is treatable and recovery is real. Get help early: Tele-MANAS 14416, Childline 1098. For acute danger like an overdose, call 112 now.",
  helpLabel: "Get help · Tele-MANAS 14416 / 112",
  reassure: "Dependence is treatable; recovery is real. Get help early: Tele-MANAS 14416, Childline 1098. For acute danger like an overdose, call 112 now. 🩺",
  reassureCats: ["respond-dont-rupture", "its-a-health-issue", "get-the-right-help"],
};
