// Content for Not Fair, Not Funny (node g11, ages 6–9, Chapter 2) — NEW v2 build to GDD 11 (mechanic-
// embodying), the gender-teasing & ally game in the Gender & Respect thread. "A joke shouldn't hurt." 84
// researched, India-aware scenarios across six categories, each encoded as one of the shared v2 play actions
// (branch / reflect / strike-rewrite / role-play / sort / build / spot / match) — no binary "tap the right
// card", led by teasing-moment DILEMMAS (branch ×24 — decide the kind/ally move, see the ripple, get a
// debrief), say-the-comeback / ally lines (role-play), and the ally-toolkit builder (build). Teaches: fun vs
// mean teasing, why "just a joke" doesn't erase harm (impact over intent), recognising & refusing gender
// put-downs ("like a girl", "boys don't cry", "so girly"), the concrete upstander moves (speak up,
// distract, support, tell, check in), and checking your own jokes. IMPACT OVER INTENT (how a joke lands, not
// whether it was 'meant'); DON'T VILLAINISE THE JOKER (Reyansh-type checks & repairs, never branded 'bad');
// PROTECT THE TARGET (the teased child is never at fault); SAFE ESCALATION (telling a trusted adult is
// reporting, not tattling — Childline 1098). Builds on g10 (Fair Play World); prereq g10. Rendered by the
// shared engine (components/games/v2-engine.tsx). gameId "not-funny" (the GDD/library "not-fair-not-funny"
// is design-doc only — config must use the engine-host registry id). DO NOT RENAME.

import type { Scenario, V2GameConfig } from "./v2-schema";

const SCENARIOS: Scenario[] = [
  // — Fun teasing vs mean teasing —
  {"id":"nf-001","cat":"fun-vs-mean","type":"sort","hook":"Lensy: some teasing is fun, some is mean. Sort these.","items":[{"id":"a","text":"You both laugh and it stops when asked"},{"id":"b","text":"It keeps going after you say stop"},{"id":"c","text":"A gentle joke you're both smiling at"},{"id":"d","text":"A jab meant to hurt"}],"bins":[{"id":"fun","label":"Fun teasing"},{"id":"mean","label":"Mean teasing"}],"key":{"a":"fun","b":"mean","c":"fun","d":"mean"},"relearn":"Fun teasing makes both laugh and stops when asked; mean teasing aims to hurt and keeps going.","persona":"any","source":"teasing vs bullying"},
  {"id":"nf-002","cat":"fun-vs-mean","type":"branch","hook":"You make a joke and your friend stops smiling.","options":[{"text":"Check in: \"sorry, that wasn't kind, you okay?\"","consequence":"They feel respected; you repair it fast.","outcome":"kind","best":true},{"text":"Say \"can't you take a joke?\"","consequence":"They feel worse; the joke became a jab.","outcome":"unkind"}],"debrief":"If a joke stops being fun for the other person, it's stopped being a joke.","relearn":"If your joke hurts someone, checking in beats doubling down.","persona":"Reyansh","source":"impact over intent"},
  {"id":"nf-003","cat":"fun-vs-mean","type":"reflect","hook":"Lensy: how do you tell fun teasing from mean teasing?","prompt":"Pick the best clue.","options":["Is everyone laughing?","Does it stop when asked?","Does it aim to hurt?"],"affirm":"All good clues, the big one is: does it hurt, and does it stop when asked?","relearn":"The test: is everyone okay, and does it stop when asked?","persona":"any","source":"teasing vs bullying"},
  {"id":"nf-004","cat":"fun-vs-mean","type":"strike-rewrite","hook":"\"If I find it funny, it must be okay.\"","myth":{"un":"If I find it funny, it must be okay for everyone.","re":"A joke is only fun if it's fun for the person it's about, too.","why":"Funny-to-you can still hurt someone else."},"relearn":"A joke isn't fun if it hurts the person it's about.","persona":"Reyansh","source":"impact over intent"},
  {"id":"nf-005","cat":"fun-vs-mean","type":"sort","hook":"Sort: a joke WITH someone, or AT someone?","items":[{"id":"a","text":"A silly inside joke you share"},{"id":"b","text":"Mocking someone's looks"},{"id":"c","text":"Laughing together at a funny film"},{"id":"d","text":"Making someone the punchline"}],"bins":[{"id":"with","label":"WITH (kind)"},{"id":"at","label":"AT (unkind)"}],"key":{"a":"with","b":"at","c":"with","d":"at"},"relearn":"Laughing WITH people is kind; laughing AT people isn't.","persona":"any","source":"humor"},
  {"id":"nf-006","cat":"fun-vs-mean","type":"reflect","hook":"Lensy: the best jokes leave everyone smiling. Agree?","prompt":"What do you think?","options":["Yes","Everyone laughs","No one's hurt"],"affirm":"The best humor includes everyone, no one's the target.","relearn":"Great jokes leave everyone, including the 'target', smiling.","persona":"any","source":"inclusive humor"},
  {"id":"nf-007","cat":"fun-vs-mean","type":"branch","hook":"Your friends are teasing you and it's actually fun, then it tips into mean.","options":[{"text":"Say \"okay, that part's not funny, let's stop\"","consequence":"Good friends ease off; the fun stays fun.","outcome":"assertive","best":true},{"text":"Pretend it's fine while it stings","consequence":"Naming the line helps friends respect it."}],"debrief":"You can enjoy the fun part and call the line when it's crossed.","relearn":"You can name when teasing tips from fun into mean.","persona":"any","source":"assertiveness"},
  {"id":"nf-008","cat":"fun-vs-mean","type":"spot","hook":"Spot the mean one (the others are friendly).","scene":[{"id":"a","text":"\"Ha, you tripped, you okay though?\"","trick":false},{"id":"b","text":"Repeating 'loser' at someone to hurt them","trick":true},{"id":"c","text":"A goofy nickname you both like","trick":false}],"why":"Repeating a hurtful name to wound someone is mean, not a joke.","relearn":"A name repeated to hurt is mean teasing, not fun.","persona":"any","source":"teasing vs bullying"},
  // — 'Just a joke' isn't a free pass —
  {"id":"nf-009","cat":"just-a-joke","type":"strike-rewrite","hook":"\"It's just a joke, so it doesn't count.\"","myth":{"un":"If you call it a joke, it can't really hurt.","re":"'Just a joke' doesn't erase the hurt; the harm is real.","why":"Calling it a joke is often a way to dodge the hurt caused."},"relearn":"'Just a joke' doesn't make a put-down okay.","persona":"Reyansh","source":"disparagement humor"},
  {"id":"nf-010","cat":"just-a-joke","type":"branch","hook":"A kid makes fun of another's accent, then says \"relax, just joking.\"","options":[{"text":"Say \"it's not funny if it hurts them\"","consequence":"You name the dodge; the teasing loses cover.","outcome":"ally","best":true},{"text":"Let 'just joking' settle it","consequence":"'Just joking' shouldn't be a free pass for hurt."}],"debrief":"'Just joking' isn't a magic pass that erases the hurt.","relearn":"You can call out a put-down even when it's labelled a 'joke'.","persona":"Ananya","source":"disparagement humor"},
  {"id":"nf-011","cat":"just-a-joke","type":"strike-rewrite","hook":"\"Jokes about a whole group are harmless fun.\"","myth":{"un":"Jokes that put down a whole group are harmless.","re":"Group put-down jokes spread unfair ideas about people.","why":"They make unkind beliefs feel normal and okay."},"relearn":"Jokes that put down a group quietly spread unfairness.","persona":"any","source":"disparagement humor"},
  {"id":"nf-012","cat":"just-a-joke","type":"sort","hook":"Sort: a joke that's fine, or one that puts a group down?","items":[{"id":"a","text":"A pun about vegetables"},{"id":"b","text":"\"Girls are bad at maths\" as a 'joke'"},{"id":"c","text":"A silly knock-knock joke"},{"id":"d","text":"A 'joke' that boys are dumb"}],"bins":[{"id":"fine","label":"Fine fun"},{"id":"putdown","label":"Group put-down"}],"key":{"a":"fine","b":"putdown","c":"fine","d":"putdown"},"relearn":"Jokes that put a group down aren't the same as harmless fun.","persona":"any","source":"disparagement humor"},
  {"id":"nf-013","cat":"just-a-joke","type":"reflect","hook":"Lensy: who decides if a joke went too far, the teller or the person it's about?","prompt":"What do you think?","options":["The person it's about","Both, but their feelings count","Not just the teller"],"affirm":"The feelings of the person it's about matter most, not just the teller's intent.","relearn":"Whether a joke hurt is mostly about how the other person felt.","persona":"any","source":"impact over intent"},
  {"id":"nf-014","cat":"just-a-joke","type":"branch","hook":"You hear a 'joke' that puts down a group you belong to.","options":[{"text":"Say \"that's not really funny to me\"","consequence":"You stand up for yourself; some rethink it.","outcome":"assertive","best":true},{"text":"Force a laugh","consequence":"You can name that it doesn't feel funny to you."}],"debrief":"You're allowed to say a 'joke' about your group doesn't land.","relearn":"You can say a put-down joke about your group isn't funny.","persona":"Faizan-type","source":"self-advocacy"},
  {"id":"nf-015","cat":"just-a-joke","type":"strike-rewrite","hook":"\"If you don't laugh, you can't take a joke.\"","myth":{"un":"Not laughing means you can't take a joke.","re":"Not laughing at a put-down means you noticed it wasn't kind.","why":"'Can't take a joke' is used to silence people who are hurt."},"relearn":"You don't have to laugh at something unkind.","persona":"any","source":"disparagement humor"},
  {"id":"nf-016","cat":"just-a-joke","type":"role-play","hook":"Someone says \"can't you take a joke?\" after a mean dig.","setup":"Hold your ground. Say:","yourLine":[{"text":"\"I like jokes, just not ones that hurt people.\"","best":true},{"text":"\"Sorry, I'll laugh.\""}],"relearn":"You can love jokes and still refuse the mean ones.","persona":"Ananya","source":"assertiveness / voice"},
  {"id":"nf-017","cat":"just-a-joke","type":"reflect","hook":"Lensy: a joke can be clever AND kind. Want both?","prompt":"What do you think?","options":["Yes","Clever and kind","The best kind"],"affirm":"The cleverest jokes don't need a victim. Aim for those.","relearn":"The best humor is clever and kind, no victim needed.","persona":"any","source":"inclusive humor"},
  // — Gender teasing & put-downs —
  {"id":"nf-018","cat":"gender-teasing","type":"strike-rewrite","hook":"\"You throw like a girl!\" (said as an insult)","myth":{"un":"'Like a girl' is an insult.","re":"Girls throw, run and play brilliantly; 'like a girl' isn't a put-down.","why":"Using a gender as an insult puts down half the world."},"relearn":"'Like a girl' isn't an insult, girls are great at everything.","persona":"Ananya","source":"gender teasing"},
  {"id":"nf-019","cat":"gender-teasing","type":"branch","hook":"Kids tease a boy for crying: \"baby! boys don't cry!\"","options":[{"text":"Say \"everyone cries, that's not a put-down\"","consequence":"He's supported; the put-down loses power.","outcome":"ally","best":true},{"text":"Join in","consequence":"He feels ashamed of a normal feeling."}],"debrief":"Teasing a boy for crying punishes a normal, healthy feeling.","relearn":"Crying isn't 'unmanly'; teasing it isn't fair or funny.","persona":"Faizan-type","source":"gender teasing (links g01)"},
  {"id":"nf-020","cat":"gender-teasing","type":"strike-rewrite","hook":"\"That's so girly\" (said to shame a boy)","myth":{"un":"Calling something 'girly' is a way to shame a boy.","re":"Liking 'girly' things is fine; 'girly' isn't an insult.","why":"It only stings if we treat girls' things as lesser."},"relearn":"'Girly' isn't an insult; everyone can like anything.","persona":"Faizan-type","source":"gender teasing"},
  {"id":"nf-021","cat":"gender-teasing","type":"spot","hook":"Spot the gender put-down.","scene":[{"id":"a","text":"\"Nice goal!\"","trick":false},{"id":"b","text":"\"Pink? What are you, a girl?\"","trick":true},{"id":"c","text":"\"Want to join our team?\"","trick":false}],"why":"Using 'a girl' as a put-down is gender teasing.","relearn":"Spot when a gender is being used as an insult.","persona":"Reyansh","source":"gender teasing"},
  {"id":"nf-022","cat":"gender-teasing","type":"role-play","hook":"A friend is teased: \"that game's for girls, why do YOU play it?\"","setup":"Back them up. Say:","yourLine":[{"text":"\"Games are for everyone, it's a great game.\"","best":true},{"text":"Laugh along"}],"relearn":"A calm comeback defends a friend and the truth.","persona":"Reyansh","source":"comebacks / voice"},
  {"id":"nf-023","cat":"gender-teasing","type":"strike-rewrite","hook":"\"Boys who do ballet/cooking deserve teasing.\"","myth":{"un":"Boys who like 'girl' activities deserve teasing.","re":"Boys can love ballet, cooking, anything, no teasing earned.","why":"Interests aren't gendered; teasing them is unfair."},"relearn":"No one earns teasing for liking something 'not for their gender'.","persona":"Faizan-type","source":"gender norms"},
  {"id":"nf-024","cat":"gender-teasing","type":"branch","hook":"A girl is mocked for being 'bossy' when she leads.","options":[{"text":"Say \"she's a good leader, not bossy\"","consequence":"You reframe it; leadership isn't a girl flaw.","outcome":"ally","best":true},{"text":"Agree she's bossy","consequence":"'Bossy' is often just 'leading while a girl'."}],"debrief":"Girls get called 'bossy' for the leading boys get praised for.","relearn":"Leading isn't 'bossy'; don't tease girls for it.","persona":"Ananya","source":"gender teasing"},
  {"id":"nf-025","cat":"gender-teasing","type":"reflect","hook":"Lensy: using a gender as an insult, who does it hurt?","prompt":"What do you think?","options":["The kid teased","All of that gender","Lots of people"],"affirm":"It hurts the kid AND quietly puts down everyone of that gender.","relearn":"Gender insults hurt the person and a whole group at once.","persona":"any","source":"disparagement humor"},
  {"id":"nf-026","cat":"gender-teasing","type":"strike-rewrite","hook":"\"Teasing about looks or skin is fine if it's funny.\"","myth":{"un":"Teasing someone's looks or skin colour is okay if it's 'funny'.","re":"Mocking looks or skin colour hurts; it's never just funny.","why":"It attacks something a person can't and shouldn't change."},"relearn":"Teasing looks or skin colour isn't funny; it's hurtful.","persona":"any","source":"appearance / colourism (links g06)"},
  {"id":"nf-027","cat":"gender-teasing","type":"sort","hook":"Sort: a kind comment, or a gender/looks put-down?","items":[{"id":"a","text":"\"Cool haircut!\""},{"id":"b","text":"\"You're too dark to be pretty\""},{"id":"c","text":"\"Great catch!\""},{"id":"d","text":"\"You run like a girl, ha\""}],"bins":[{"id":"kind","label":"Kind"},{"id":"putdown","label":"Put-down"}],"key":{"a":"kind","b":"putdown","c":"kind","d":"putdown"},"relearn":"Spot put-downs about gender, looks and skin, they're not jokes.","persona":"any","source":"appearance / gender teasing"},
  {"id":"nf-028","cat":"gender-teasing","type":"role-play","hook":"Someone teases a friend's dark skin as a 'joke'.","setup":"Stand up, kindly. Say:","yourLine":[{"text":"\"Every skin colour is great, that's not funny.\"","best":true},{"text":"Laugh"}],"relearn":"You can shut down a colourist 'joke' with a kind, clear line.","persona":"Ananya","source":"colourism / ally (links g06)"},
  // — How put-downs feel (impact over intent) —
  {"id":"nf-029","cat":"how-it-feels","type":"reflect","hook":"Lensy: think of a time a 'joke' was about you and stung.","prompt":"How did it feel?","options":["Bad","Embarrassing","Lonely"],"affirm":"That sting is real, and it's why we don't aim jokes at people.","relearn":"Put-down 'jokes' really sting; that feeling matters.","persona":"Faizan-type","source":"empathy"},
  {"id":"nf-030","cat":"how-it-feels","type":"branch","hook":"You realise a joke you made really hurt someone.","options":[{"text":"Apologise: \"I'm sorry, that was unkind\"","consequence":"They feel better; you grow as a friend.","outcome":"repair","best":true},{"text":"Defend it: \"I didn't mean it like that\"","consequence":"Intent matters less than the hurt; owning it helps."}],"debrief":"What you meant matters less than how it landed, own the impact.","relearn":"If a joke hurt, apologise for the impact, not just your intent.","persona":"Reyansh","source":"impact over intent / repair"},
  {"id":"nf-031","cat":"how-it-feels","type":"strike-rewrite","hook":"\"If I didn't mean to hurt, it doesn't count.\"","myth":{"un":"If I didn't mean to hurt, the hurt doesn't count.","re":"Hurt counts even when it wasn't meant; you can still make it right.","why":"Caring about impact is what kind people do."},"relearn":"Even unmeant hurt is real; you can still say sorry.","persona":"Reyansh","source":"impact over intent"},
  {"id":"nf-032","cat":"how-it-feels","type":"reflect","hook":"Lensy: before a joke, ask 'how would this land for them?' Good habit?","prompt":"What do you think?","options":["Yes","A kind check","I'll try it"],"affirm":"A quick 'how would this land?' keeps your jokes kind.","relearn":"Checking how a joke might land is a kind habit.","persona":"any","source":"empathy / perspective-taking"},
  {"id":"nf-033","cat":"how-it-feels","type":"branch","hook":"A friend laughs off a mean joke but looks hurt underneath.","options":[{"text":"Check in later: \"that joke wasn't fair, you okay?\"","consequence":"They feel seen; laughing it off was a mask.","outcome":"kind","best":true},{"text":"Assume they're fine","consequence":"A brave laugh can hide real hurt; checking in helps."}],"debrief":"People often laugh to hide hurt, a quiet check-in means a lot.","relearn":"A laugh can hide hurt; check in on a friend after.","persona":"any","source":"empathy"},
  {"id":"nf-034","cat":"how-it-feels","type":"match","hook":"Match the put-down to the feeling it can cause.","pairs":[{"left":"Mocked for looks","right":"Ashamed"},{"left":"Left out by a 'joke'","right":"Lonely"},{"left":"Teased every day","right":"Worn down"}],"relearn":"Put-downs cause real feelings: shame, loneliness, being worn down.","persona":"any","source":"empathy"},
  {"id":"nf-035","cat":"how-it-feels","type":"reflect","hook":"Lensy: kindness costs nothing and helps a lot. Worth choosing?","prompt":"What do you think?","options":["Yes","Always","Easy choice"],"affirm":"Choosing kind over a cheap laugh is a small, powerful habit.","relearn":"Choosing kindness over a put-down laugh is always worth it.","persona":"any","source":"values"},
  {"id":"nf-036","cat":"how-it-feels","type":"branch","hook":"Everyone's laughing at a 'joke' about a quiet kid who isn't there.","options":[{"text":"Say \"that's not fair on them\" and change the subject","consequence":"The pile-on stops; you protected someone absent.","outcome":"ally","best":true},{"text":"Add your own joke","consequence":"Talking someone down behind their back is still unkind."}],"debrief":"Put-downs behind someone's back are still put-downs.","relearn":"Standing up for someone who isn't there is real kindness.","persona":"Ananya","source":"empathy / bystander"},
  // — Being an ally (upstander moves) —
  {"id":"nf-037","cat":"be-an-ally","type":"branch","hook":"A friend is being teased about their gender right in front of you.","options":[{"text":"Speak up: \"that's not kind, stop\"","consequence":"Often the teasing stops fast when someone speaks up.","outcome":"upstander","best":true},{"text":"Look away","consequence":"Silence lets it continue; speaking up helps."}],"debrief":"When a peer steps in, teasing often stops within seconds.","relearn":"Speaking up, even two words, can stop teasing fast.","persona":"Faizan-type","source":"upstander research"},
  {"id":"nf-038","cat":"be-an-ally","type":"strike-rewrite","hook":"\"If it's not happening to me, it's not my problem.\"","myth":{"un":"Teasing someone else is none of my business.","re":"An ally who steps in can stop it; silence lets it grow.","why":"Bystanders set the tone, for better or worse."},"relearn":"Standing up for others is exactly your business.","persona":"Ananya","source":"bystander research"},
  {"id":"nf-039","cat":"be-an-ally","type":"role-play","hook":"You want to step in but it feels scary.","setup":"Try a short, calm line. Say:","yourLine":[{"text":"\"Hey, that's not cool.\"","best":true},{"text":"Nothing"}],"relearn":"You don't need a speech, a short \"that's not cool\" works.","persona":"any","source":"upstander / voice"},
  {"id":"nf-040","cat":"be-an-ally","type":"branch","hook":"It feels too risky to speak up to the teaser directly.","options":[{"text":"Distract, or go support the kid, or tell a trusted adult","consequence":"There's more than one way to be an ally.","outcome":"upstander","best":true},{"text":"Do nothing because you can't confront them","consequence":"Distracting, supporting and telling are ally moves too."}],"debrief":"Allies have options: distract, support, or tell an adult.","relearn":"You can ally without confronting.","persona":"quiet child","source":"upstander moves"},
  {"id":"nf-041","cat":"be-an-ally","type":"role-play","hook":"After someone was teased, you go find them.","setup":"Offer support. Say:","yourLine":[{"text":"\"That wasn't fair to you. Want to hang out?\"","best":true},{"text":"Pretend it didn't happen"}],"relearn":"Checking in after, and including them, is powerful allyship.","persona":"any","source":"upstander / support"},
  {"id":"nf-042","cat":"be-an-ally","type":"sort","hook":"Sort: an ally (upstander) move, or not?","items":[{"id":"a","text":"Saying 'that's not kind'"},{"id":"b","text":"Laughing along"},{"id":"c","text":"Sitting with the teased kid"},{"id":"d","text":"Filming it for fun"}],"bins":[{"id":"ally","label":"Ally move"},{"id":"no","label":"Not an ally"}],"key":{"a":"ally","b":"no","c":"ally","d":"no"},"relearn":"Allies speak up and support; laughing or filming feeds the harm.","persona":"any","source":"upstander moves"},
  {"id":"nf-043","cat":"be-an-ally","type":"branch","hook":"You spoke up and the teaser turned on you a bit.","options":[{"text":"Stay calm; get a friend or adult to back you","consequence":"With backup it's easier; the right people respect you.","outcome":"upstander","best":true},{"text":"Wish you'd stayed quiet","consequence":"Bringing backup makes standing up safer and easier."}],"debrief":"You don't have to be a lone hero, bring a friend or an adult.","relearn":"If speaking up gets hard, bring backup, a friend or adult.","persona":"any","source":"upstander / safety"},
  {"id":"nf-044","cat":"be-an-ally","type":"reflect","hook":"Lensy: being an ally takes courage. Got some?","prompt":"What do you think?","options":["Yes","A bit, growing","I'll be brave"],"affirm":"Courage grows each time you use it. You've got this.","relearn":"Allyship takes courage, and courage grows with practice.","persona":"any","source":"self-efficacy"},
  {"id":"nf-045","cat":"be-an-ally","type":"branch","hook":"A whole group is teasing one kid; you're just one person.","options":[{"text":"Stand next to the kid; others often join you","consequence":"One upstander gives other quiet kids courage to join.","outcome":"upstander","best":true},{"text":"Assume one person can't help","consequence":"One upstander often sparks others to step up too."}],"debrief":"One person standing up gives everyone else permission to.","relearn":"Even one ally can shift the whole group.","persona":"Ananya","source":"bystander research"},
  {"id":"nf-046","cat":"be-an-ally","type":"role-play","hook":"You see a 'just a joke' put-down and want to name it.","setup":"Say the two-word classic:","yourLine":[{"text":"\"Not funny.\"","best":true},{"text":"A nervous laugh"}],"relearn":"A simple \"not funny\" can open everyone's eyes.","persona":"Ananya","source":"upstander / voice"},
  {"id":"nf-047","cat":"be-an-ally","type":"strike-rewrite","hook":"\"Telling an adult about teasing is tattling.\"","myth":{"un":"Telling an adult about teasing is tattling.","re":"Telling to keep someone safe is reporting, and it's brave.","why":"Reporting helps; tattling is just to get someone in trouble."},"relearn":"Telling an adult to stop teasing is reporting, not tattling.","persona":"Ananya","source":"telling vs tattling"},
  {"id":"nf-048","cat":"be-an-ally","type":"reflect","hook":"Lensy: which ally move feels most like you?","prompt":"Pick one to try.","options":["Speak up","Distract","Support the kid","Tell an adult"],"affirm":"That's your go-to ally move, keep it ready.","relearn":"Pick an ally move that fits you; any of them helps.","persona":"any","source":"upstander moves"},
  {"id":"nf-049","cat":"be-an-ally","type":"branch","hook":"Your own friend is the one doing the teasing.","options":[{"text":"Quietly tell them \"that's not cool, ease off\"","consequence":"A friend's word often lands best; they stop.","outcome":"upstander","best":true},{"text":"Stay loyal and say nothing","consequence":"Real loyalty includes helping a friend be kinder."}],"debrief":"Telling a friend to stop is hard, and a real act of friendship.","relearn":"A good friend helps another friend stop being unkind.","persona":"Reyansh","source":"upstander / friendship"},
  {"id":"nf-050","cat":"be-an-ally","type":"build","hook":"Build your ally toolkit.","prompt":"Pick the moves to keep ready.","pieces":["speak up: 'not cool'","distract / change subject","support the kid after","tell a trusted adult","laugh along"],"mode":"assemble","key":["speak up: 'not cool'","distract / change subject","support the kid after","tell a trusted adult"],"relearn":"Your ally toolkit: speak up, distract, support, tell, never laugh along.","persona":"any","source":"upstander moves"},
  {"id":"nf-051","cat":"be-an-ally","type":"reflect","hook":"Lensy: when you stand up for someone, how do they feel?","prompt":"What do you think?","options":["Less alone","Supported","Grateful"],"affirm":"Your stand tells them they're not alone, that's huge.","relearn":"Standing up tells someone they're not alone.","persona":"any","source":"support"},
  {"id":"nf-052","cat":"be-an-ally","type":"branch","hook":"You weren't brave enough to step in this time.","options":[{"text":"Check in with the kid after, and plan to do better","consequence":"You still help, and you're readier next time.","outcome":"growth","best":true},{"text":"Feel guilty and do nothing","consequence":"You can still help after, and try again next time."}],"debrief":"If you froze, you can still support after, and grow braver.","relearn":"Even if you froze, you can help after and try again.","persona":"quiet child","source":"self-compassion / growth"},
  // — Checking my own jokes —
  {"id":"nf-053","cat":"my-own-jokes","type":"reflect","hook":"Lensy honest check: do your jokes ever punch DOWN at someone?","prompt":"Be honest with yourself.","options":["Sometimes","Maybe","I'll watch for it"],"affirm":"Noticing your own jokes is exactly what a kind, funny person does.","relearn":"Checking your own jokes for who they punch at is smart and kind.","persona":"Reyansh","source":"self-awareness"},
  {"id":"nf-054","cat":"my-own-jokes","type":"strike-rewrite","hook":"\"The best way to be funny is to roast someone.\"","myth":{"un":"You have to put someone down to be funny.","re":"The funniest people make jokes that don't need a victim.","why":"Wit beats cruelty, and ages better."},"relearn":"You can be hilarious without putting anyone down.","persona":"Reyansh","source":"inclusive humor"},
  {"id":"nf-055","cat":"my-own-jokes","type":"branch","hook":"You think of a joke that would get a big laugh but it targets a kid.","options":[{"text":"Skip it, or aim it at yourself / a silly thing instead","consequence":"You still get the laugh, no one's hurt.","outcome":"kind","best":true},{"text":"Tell it anyway for the laugh","consequence":"A laugh at someone's cost isn't worth the hurt."}],"debrief":"A laugh that costs someone else isn't worth it, redirect the joke.","relearn":"Aim jokes at ideas or yourself, not at a person.","persona":"Reyansh","source":"inclusive humor"},
  {"id":"nf-056","cat":"my-own-jokes","type":"role-play","hook":"You made a joke that hurt; you want to fix it.","setup":"Make it right. Say:","yourLine":[{"text":"\"That came out unkind, I'm sorry.\"","best":true},{"text":"\"You're too sensitive.\""}],"relearn":"A clean apology beats blaming the person you hurt.","persona":"Reyansh","source":"repair / voice"},
  {"id":"nf-057","cat":"my-own-jokes","type":"sort","hook":"Sort: a joke that's safe to tell, or one to skip?","items":[{"id":"a","text":"A pun everyone enjoys"},{"id":"b","text":"A jab at a kid's family"},{"id":"c","text":"A silly story about yourself"},{"id":"d","text":"Mocking how someone talks"}],"bins":[{"id":"safe","label":"Safe to tell"},{"id":"skip","label":"Skip it"}],"key":{"a":"safe","b":"skip","c":"safe","d":"skip"},"relearn":"Puns and self-jokes are safe; jabs at people are ones to skip.","persona":"any","source":"inclusive humor"},
  {"id":"nf-058","cat":"my-own-jokes","type":"reflect","hook":"Lensy: a good rule, joke UP or sideways, not DOWN. Makes sense?","prompt":"What do you think?","options":["Yes","Don't punch down","Good rule"],"affirm":"Don't punch down, jokes shouldn't kick someone who's already a target.","relearn":"Aim humor sideways or at yourself, not down at someone vulnerable.","persona":"any","source":"inclusive humor"},
  {"id":"nf-059","cat":"my-own-jokes","type":"branch","hook":"Friends egg you on to mock another kid for laughs.","options":[{"text":"Say \"nah, let's not, that's not cool\"","consequence":"You hold your line; good friends respect it.","outcome":"values","best":true},{"text":"Do it to please them","consequence":"You don't have to be unkind to keep friends."}],"debrief":"You can resist the pressure to get laughs by hurting someone.","relearn":"You can say no to making someone the joke, even for friends.","persona":"Reyansh","source":"peer pressure / values"},
  {"id":"nf-060","cat":"my-own-jokes","type":"reflect","hook":"Lensy: being funny AND kind, that's the real skill. Up for it?","prompt":"What do you think?","options":["Yes","Funny and kind","That's my goal"],"affirm":"Funny-and-kind is the gold standard. You can be both.","relearn":"The real skill is being funny and kind at the same time.","persona":"any","source":"inclusive humor"},
  {"id":"nf-061","cat":"my-own-jokes","type":"strike-rewrite","hook":"\"Saying sorry for a joke is weak.\"","myth":{"un":"Apologising for a joke makes you look weak.","re":"Owning a joke that hurt is strong and respected.","why":"Big people repair; only small ones double down."},"relearn":"Apologising for a joke that hurt is a strong move.","persona":"Reyansh","source":"repair / values"},
  {"id":"nf-062","cat":"my-own-jokes","type":"build","hook":"Build a 'kind comedian' code.","prompt":"Pick the rules.","pieces":["joke with people, not at them","punch up or sideways, never down","stop if it hurts","apologise if it lands wrong","make someone the target"],"mode":"assemble","key":["joke with people, not at them","punch up or sideways, never down","stop if it hurts","apologise if it lands wrong"],"relearn":"Kind comedian code: with not at, never down, stop if it hurts, apologise.","persona":"Reyansh","source":"inclusive humor"},
  {"id":"nf-063","cat":"gender-teasing","type":"branch","hook":"A boy is mocked for having girls as his best friends.","options":[{"text":"Say \"boys and girls can totally be friends\"","consequence":"You defend a real friendship; the mocking fades.","outcome":"ally","best":true},{"text":"Tease him too","consequence":"Friendship across genders is normal and good."}],"debrief":"There's nothing to mock about boys and girls being friends.","relearn":"Boys and girls being friends isn't something to tease.","persona":"Faizan-type","source":"gender norms / friendship"},
  {"id":"nf-064","cat":"just-a-joke","type":"spot","hook":"Spot the 'joke' that's really a put-down.","scene":[{"id":"a","text":"\"Why did the chicken cross the road?\"","trick":false},{"id":"b","text":"\"You're so dumb for a girl, haha\"","trick":true},{"id":"c","text":"\"Knock knock!\"","trick":false}],"why":"A 'joke' that insults a girl's intelligence is a put-down.","relearn":"Watch for put-downs dressed up as jokes.","persona":"Ananya","source":"disparagement humor"},
  {"id":"nf-065","cat":"how-it-feels","type":"branch","hook":"You're the one being teased and it really hurts.","options":[{"text":"Say \"that's not okay\" and tell a trusted adult if it keeps on","consequence":"You stand up for yourself and get support.","outcome":"assertive","best":true},{"text":"Bottle it up","consequence":"You deserve support; telling someone helps."}],"debrief":"If you're the target, you can speak up and get help, it's not your fault.","relearn":"If you're teased, you can say 'not okay' and tell a trusted adult.","persona":"Faizan-type","source":"self-advocacy"},
  {"id":"nf-066","cat":"be-an-ally","type":"branch","hook":"Online, kids are piling mean 'jokes' on someone in a group chat.","options":[{"text":"Don't add to it; message the kid kindly and tell an adult","consequence":"You break the pile-on and support them.","outcome":"upstander","best":true},{"text":"Add a laughing emoji","consequence":"Even an emoji feeds an online pile-on."}],"debrief":"Online put-downs spread fast; not adding, and supporting, matters.","relearn":"Don't feed an online pile-on; support the target and tell an adult.","persona":"Reyansh","source":"cyberbullying / upstander"},
  {"id":"nf-067","cat":"fun-vs-mean","type":"reflect","hook":"Lensy: with real friends, teasing stops the moment it stings. True?","prompt":"What do you think?","options":["Yes","Real friends stop","That's the test"],"affirm":"Real friends ease off the instant it stops being fun.","relearn":"Real friends stop teasing the moment it hurts.","persona":"any","source":"friendship / teasing"},
  {"id":"nf-068","cat":"gender-teasing","type":"role-play","hook":"Someone says 'don't be such a girl' to a boy who's scared.","setup":"Reframe it. Say:","yourLine":[{"text":"\"Being scared is human, not a 'girl' thing.\"","best":true},{"text":"Snigger"}],"relearn":"Feelings aren't a gender; don't use 'girl' as an insult.","persona":"Faizan-type","source":"gender teasing"},
  {"id":"nf-069","cat":"my-own-jokes","type":"reflect","hook":"Lensy: would your joke still feel funny if it were about YOU?","prompt":"A good test?","options":["Yes, great test","I'll use it","Helps me check"],"affirm":"The 'would I laugh if it were me?' test keeps jokes kind.","relearn":"Test a joke by imagining it aimed at you.","persona":"Reyansh","source":"empathy / perspective-taking"},
  {"id":"nf-070","cat":"be-an-ally","type":"branch","hook":"You see teasing but you're new and don't want trouble.","options":[{"text":"Start small, sit with the kid or tell an adult quietly","consequence":"Even quiet allyship helps and feels safer.","outcome":"upstander","best":true},{"text":"Decide it's not your place","consequence":"Quiet allyship still counts and is a safe start."}],"debrief":"Allyship can be quiet, you don't have to make a scene.","relearn":"You can be a quiet ally: sit with them, tell an adult.","persona":"quiet child","source":"upstander moves"},
  {"id":"nf-071","cat":"just-a-joke","type":"reflect","hook":"Lensy: 'I was joking' shouldn't erase someone's hurt. Agree?","prompt":"What do you think?","options":["Yes","Hurt still counts","Agree"],"affirm":"'I was joking' doesn't undo the hurt, caring about that is kindness.","relearn":"'I was joking' doesn't cancel the hurt a joke caused.","persona":"any","source":"impact over intent"},
  {"id":"nf-072","cat":"how-it-feels","type":"reflect","hook":"Lensy: a kind word can undo a mean joke's sting. Want to be that person?","prompt":"What do you think?","options":["Yes","I can be kind","Count me in"],"affirm":"You can be the kind word that helps someone bounce back.","relearn":"A kind word can heal the sting of a put-down.","persona":"any","source":"support"},
  {"id":"nf-073","cat":"fun-vs-mean","type":"branch","hook":"A classmate gives you a goofy nickname; you actually don't like it.","options":[{"text":"Say \"please don't call me that\"","consequence":"A kind classmate stops; your feelings count.","outcome":"assertive","best":true},{"text":"Put up with it","consequence":"You're allowed to say a nickname doesn't sit right."}],"debrief":"Even a 'friendly' nickname should stop if you don't like it.","relearn":"You can ask someone to stop a nickname you dislike.","persona":"any","source":"boundaries"},
  {"id":"nf-074","cat":"gender-teasing","type":"strike-rewrite","hook":"\"Teasing toughens kids up, so it's good for them.\"","myth":{"un":"Teasing toughens kids up.","re":"Mean teasing wears kids down; support builds real strength.","why":"Kids grow strong from safety and support, not put-downs."},"relearn":"Mean teasing doesn't toughen kids; it wears them down.","persona":"any","source":"child wellbeing"},
  {"id":"nf-075","cat":"be-an-ally","type":"role-play","hook":"The class is laughing at one kid; you decide to flip it.","setup":"Redirect with warmth. Say:","yourLine":[{"text":"\"Hey, leave them, who wants to play?\"","best":true},{"text":"Add to the laughing"}],"relearn":"Redirecting the group's energy is a clever ally move.","persona":"Ananya","source":"upstander / distraction"},
  {"id":"nf-076","cat":"my-own-jokes","type":"branch","hook":"Capstone: the whole group's watching and you've a joke ready, about a kid.","options":[{"text":"Switch it to a silly self-joke or a fun topic","consequence":"You get the laugh and keep everyone safe.","outcome":"kind","best":true},{"text":"Land the joke at the kid's expense","consequence":"Power over a crowd is a chance to be kind, not cruel."}],"debrief":"With the crowd, use it to include, not to wound.","relearn":"With everyone watching, pick the joke that hurts no one.","persona":"Reyansh","source":"inclusive humor / consolidation"},
  {"id":"nf-077","cat":"be-an-ally","type":"reflect","hook":"Lensy: who could YOU stand up for this week?","prompt":"Think of someone.","options":["A teased classmate","A left-out kid","Anyone put down","Myself"],"affirm":"That's an upstander plan. Small stands change the whole room.","relearn":"You can choose to be an ally, in small ways, often.","persona":"any","source":"agency"},
  {"id":"nf-078","cat":"gender-teasing","type":"sort","hook":"Sort: a fair comment, or a gender put-down dressed as a joke?","items":[{"id":"a","text":"\"You're really good at this\""},{"id":"b","text":"\"For a girl, not bad, haha\""},{"id":"c","text":"\"Want to team up?\""},{"id":"d","text":"\"Real boys don't do that\""}],"bins":[{"id":"fair","label":"Fair"},{"id":"putdown","label":"Gender put-down"}],"key":{"a":"fair","b":"putdown","c":"fair","d":"putdown"},"relearn":"'For a girl' and 'real boys don't' are put-downs, not compliments or jokes.","persona":"Ananya","source":"gender teasing"},
  {"id":"nf-079","cat":"how-it-feels","type":"branch","hook":"A group you're in always jokes about the same kid.","options":[{"text":"Name it: \"we always pick on them, let's stop\"","consequence":"You break a mean pattern the group drifted into.","outcome":"upstander","best":true},{"text":"Keep the pattern going","consequence":"'Jokes' aimed at one kid are bullying; you can break them."}],"debrief":"A repeated 'joke' at one kid is bullying. Name it and stop it.","relearn":"Always joking about one kid is bullying; break it.","persona":"Ananya","source":"teasing vs bullying"},
  {"id":"nf-080","cat":"just-a-joke","type":"reflect","hook":"Lensy: 'not fair, not funny', when does a joke fail that test?","prompt":"Pick one.","options":["When it hurts someone","When it puts a group down","When it won't stop"],"affirm":"All of those, that's exactly when a joke isn't fair or funny.","relearn":"A joke fails when it hurts, puts a group down, or won't stop.","persona":"any","source":"consolidation"},
  {"id":"nf-081","cat":"be-an-ally","type":"build","hook":"Capstone: build your upstander plan.","prompt":"Pick what you'll do when you see a put-down.","pieces":["say 'not cool'","support the kid after","distract / redirect","tell a trusted adult","laugh along"],"mode":"assemble","key":["say 'not cool'","support the kid after","distract / redirect","tell a trusted adult"],"relearn":"Your upstander plan: speak up, support, distract, tell, never laugh along.","persona":"any","source":"consolidation"},
  {"id":"nf-082","cat":"my-own-jokes","type":"reflect","hook":"Lensy: what will you carry from Not Fair, Not Funny?","prompt":"Pick your motto.","options":["Joke with, not at","Not funny if it hurts","Be an ally","Punch up, never down"],"affirm":"Carry that. You can be the funny one AND the kind one.","relearn":"Jokes are for laughing together, never at someone; and be an ally.","persona":"any","source":"consolidation"},
  {"id":"nf-083","cat":"fun-vs-mean","type":"strike-rewrite","hook":"\"Everyone teases, so it's just normal.\"","myth":{"un":"Everyone teases, so mean teasing is just normal.","re":"Common doesn't mean kind; we can do better than mean teasing.","why":"Normal isn't the same as fair or funny."},"relearn":"Just because teasing is common doesn't make it okay.","persona":"any","source":"norms"},
  {"id":"nf-084","cat":"be-an-ally","type":"reflect","hook":"Lensy: imagine a class where everyone's an ally. Good place?","prompt":"What do you think?","options":["Amazing","Everyone safe","Yes!"],"affirm":"That's the world allies build, one 'not cool' at a time.","relearn":"When everyone's an ally, everyone is safer and kinder.","persona":"any","source":"vision"},
];

export const NOT_FUNNY: V2GameConfig = {
  gameId: "not-funny",
  title: "Not Fair, Not Funny",
  greet: "Hey! Some jokes are fun — and some are not fair, not funny. 😄 Let's tell them apart, stand up for friends, and be the funny AND kind one.",
  scenarios: SCENARIOS,
  categories: [
    { id: "fun-vs-mean", emoji: "😄", label: "Fun or mean?" },
    { id: "just-a-joke", emoji: "🃏", label: "Just a joke?" },
    { id: "gender-teasing", emoji: "🚫", label: "Gender put-downs" },
    { id: "how-it-feels", emoji: "💔", label: "How it feels" },
    { id: "be-an-ally", emoji: "🦸", label: "Be an ally" },
    { id: "my-own-jokes", emoji: "🪞", label: "My own jokes" },
  ],
  badge: {
    title: "Upstander! 🦸",
    blurb: "You can tell fun teasing from mean, see through 'just a joke', refuse gender put-downs, and step in as an ally. Standing up is your business. 🦸💛",
  },
  helpLine: "If teasing keeps going, tell a trusted grown-up or call Childline, one-zero-nine-eight. Telling to keep someone safe is reporting, not tattling.",
  helpLabel: "Get help · Childline 1098",
  reassure: "If someone teases or puts you down, it's not your fault — and telling a trusted grown-up is brave, not tattling. 💛",
  reassureCats: ["how-it-feels"],
  buildLabels: { assemble: "That's your ally toolkit! 🦸" },
};
