// Content for Outbreak: Stop the Spread (node g23, ages 12–15, Chapter 4) — NEW v2 build to GDD 23
// (mechanic-embodying), the STI + HIV public-health + anti-stigma node (Thread F · SRH). "The real enemy is
// the infection and the stigma, never the person." 84 researched, India-grounded scenarios across the
// how-STIs-spread → silent-part → stop-the-spread → test-and-treat → bust-myths → end-stigma arc, each
// encoded as one of the shared v2 play actions (branch / sort / strike-rewrite / build / reflect / match /
// role-play) — no binary "tap the right card". Lead mechanics: branch (make the public-health move ×18),
// strike-rewrite (bust the STI myth ×18), sort (real route vs myth, reliable vs not ×16). Teaches: how STIs
// spread (sexual contact, blood, parent-to-baby) and DON'T (casual contact); that many STIs are SILENT so
// testing is the only way to know; the real public-health toolkit (waiting — fully reliable; condoms;
// vaccines incl. the HPV vaccine, free for 14-year-old girls in India; testing; treatment); that all STIs
// are treatable and most curable; and that STIGMA is the real harm (STIs are common health conditions, not a
// sign of being 'dirty' or 'bad'; testing is responsible and often confidential; people with an STI deserve
// care, not shame). School-comfort: matter-of-fact, NON-EXPLICIT; routes to a clinic/doctor for testing &
// facts. GATED at the path layer (age band). Builds on g20 (Defenders of the Body); prereq g22. Rendered by
// the shared engine (components/games/v2-engine.tsx). gameId "outbreak" (the engine-host registry id; the
// GDD/library aspirational id is "outbreak-stop-the-spread"). DO NOT RENAME.

import type { Scenario, V2GameConfig } from "./v2-schema";

const SCENARIOS: Scenario[] = [
  // — How STIs spread (and don't) —
  {"id":"ob-001","cat":"how-stis-spread","type":"sort","hook":"Sort: a real way STIs spread, or not?","items":[{"id":"a","text":"Through sexual contact"},{"id":"b","text":"Sharing a meal"},{"id":"c","text":"Shared needles (blood)"},{"id":"d","text":"A hug"}],"bins":[{"id":"spreads","label":"Can spread STIs"},{"id":"not","label":"Does not"}],"key":{"a":"spreads","b":"not","c":"spreads","d":"not"},"relearn":"STIs spread through sexual contact and blood, not hugs or shared meals.","persona":"any","source":"transmission (CDC)"},
  {"id":"ob-002","cat":"how-stis-spread","type":"sort","hook":"Sort: can pass an STI, or completely safe everyday contact?","items":[{"id":"a","text":"Sitting next to someone"},{"id":"b","text":"Sharing a water bottle"},{"id":"c","text":"Unprotected sexual contact"},{"id":"d","text":"Shaking hands"}],"bins":[{"id":"risk","label":"A real route"},{"id":"safe","label":"Safe everyday contact"}],"key":{"a":"safe","b":"safe","c":"risk","d":"safe"},"relearn":"Everyday contact is safe; STIs need specific routes like sexual contact.","persona":"any","source":"transmission / anti-stigma"},
  {"id":"ob-003","cat":"how-stis-spread","type":"sort","hook":"Sort: the three real transmission routes, or a myth route?","items":[{"id":"a","text":"Sexual contact"},{"id":"b","text":"Blood (e.g. shared needles)"},{"id":"c","text":"Parent to baby"},{"id":"d","text":"Toilet seats"}],"bins":[{"id":"real","label":"Real route"},{"id":"myth","label":"Myth route"}],"key":{"a":"real","b":"real","c":"real","d":"myth"},"relearn":"STIs spread by sexual contact, blood, and parent-to-baby, not toilet seats.","persona":"any","source":"transmission"},
  {"id":"ob-004","cat":"how-stis-spread","type":"sort","hook":"Sort: which contact carries a risk worth protecting against?","items":[{"id":"a","text":"Unprotected sexual contact"},{"id":"b","text":"Studying together"},{"id":"c","text":"Sharing earphones"},{"id":"d","text":"Playing sport together"}],"bins":[{"id":"protect","label":"Worth protecting"},{"id":"none","label":"No STI risk"}],"key":{"a":"protect","b":"none","c":"none","d":"none"},"relearn":"Only specific contact carries STI risk; ordinary closeness doesn't.","persona":"any","source":"transmission"},
  {"id":"ob-005","cat":"how-stis-spread","type":"sort","hook":"Sort: true or false about how STIs move?","items":[{"id":"a","text":"They need a specific route to spread"},{"id":"b","text":"They float around like a cold"},{"id":"c","text":"Casual contact is safe"},{"id":"d","text":"You can catch them from a doorknob"}],"bins":[{"id":"true","label":"True"},{"id":"false","label":"False"}],"key":{"a":"true","b":"false","c":"true","d":"false"},"relearn":"STIs need specific routes; they aren't airborne or on doorknobs.","persona":"any","source":"transmission"},
  {"id":"ob-006","cat":"how-stis-spread","type":"sort","hook":"Sort: reduces a real route, or irrelevant to STIs?","items":[{"id":"a","text":"Using a condom"},{"id":"b","text":"Not sharing needles"},{"id":"c","text":"Washing your hands after class"},{"id":"d","text":"Sitting apart from people"}],"bins":[{"id":"reduces","label":"Reduces STI risk"},{"id":"irrelevant","label":"Irrelevant to STIs"}],"key":{"a":"reduces","b":"reduces","c":"irrelevant","d":"irrelevant"},"relearn":"Condoms and not sharing needles cut STI risk; distancing doesn't apply.","persona":"any","source":"prevention"},
  {"id":"ob-007","cat":"how-stis-spread","type":"strike-rewrite","hook":"\"You can catch an STI from a toilet seat.\"","myth":{"un":"STIs spread from toilet seats and surfaces.","re":"STIs do not spread from toilet seats or everyday surfaces.","why":"They need specific contact routes, not furniture."},"relearn":"You can't catch an STI from a toilet seat.","persona":"any","source":"myth-busting (CDC)"},
  {"id":"ob-008","cat":"how-stis-spread","type":"strike-rewrite","hook":"\"Being near someone with an STI is risky.\"","myth":{"un":"Just being near someone with an STI is risky.","re":"Everyday closeness, sitting, talking, hugging, carries no STI risk.","why":"STIs aren't spread by ordinary contact."},"relearn":"Everyday closeness to someone with an STI carries no risk.","persona":"Riya","source":"anti-stigma"},
  {"id":"ob-009","cat":"how-stis-spread","type":"strike-rewrite","hook":"\"Mosquitoes can spread STIs like HIV.\"","myth":{"un":"Mosquitoes can spread HIV and other STIs.","re":"Mosquitoes do not spread HIV or STIs.","why":"The viruses can't survive or pass on that way."},"relearn":"Mosquitoes do not spread HIV or other STIs.","persona":"any","source":"myth-busting (links g20)"},
  {"id":"ob-010","cat":"how-stis-spread","type":"match","hook":"Match the route to a way to lower its risk.","pairs":[{"left":"Sexual contact","right":"Waiting, or condoms"},{"left":"Shared needles","right":"Never share needles"},{"left":"Parent to baby","right":"Care from a doctor"}],"relearn":"Each real route has a clear way to lower the risk.","persona":"any","source":"prevention"},
  {"id":"ob-011","cat":"how-stis-spread","type":"match","hook":"Match the belief to fact or myth.","pairs":[{"left":"\"Spread by hugs\"","right":"Myth"},{"left":"\"Spread by sexual contact\"","right":"Fact"},{"left":"\"Spread by sharing food\"","right":"Myth"}],"relearn":"Sort the real routes from the stigma-myths.","persona":"any","source":"transmission"},
  {"id":"ob-012","cat":"how-stis-spread","type":"strike-rewrite","hook":"\"STIs are rare and only happen to 'other people'.\"","myth":{"un":"STIs are rare and only affect 'certain' people.","re":"STIs are common and can affect anyone who's sexually active.","why":"They're health conditions, not a marker of who someone is."},"relearn":"STIs are common and can affect anyone; they're not about 'type' of person.","persona":"any","source":"anti-stigma"},
  {"id":"ob-013","cat":"how-stis-spread","type":"reflect","hook":"Lensy: knowing exactly how STIs spread, and don't, kills a lot of fear. Notice that?","prompt":"What do you think?","options":["Yes","Less scary now","Facts help"],"affirm":"Clear facts replace fear with calm, useful knowledge.","relearn":"Knowing the real routes replaces fear with understanding.","persona":"any","source":"framing"},
  {"id":"ob-014","cat":"how-stis-spread","type":"reflect","hook":"Lensy: most ways people 'think' STIs spread turn out to be myths. Surprising?","prompt":"What do you think?","options":["Yes","Mostly myths","Good to know"],"affirm":"Most everyday fears about catching STIs simply aren't true.","relearn":"Most everyday fears about catching STIs are myths.","persona":"any","source":"anti-stigma"},
  // — The silent part —
  {"id":"ob-015","cat":"silent-part","type":"strike-rewrite","hook":"\"You'd always know if you had an STI.\"","myth":{"un":"You'd definitely know if you had an STI.","re":"Many STIs have no symptoms at all, the only way to know is testing.","why":"Chlamydia and gonorrhoea are often 'silent'."},"relearn":"Many STIs have no symptoms; only testing can tell.","persona":"any","source":"asymptomatic (CDC)"},
  {"id":"ob-016","cat":"silent-part","type":"strike-rewrite","hook":"\"You can tell who has an STI by looking.\"","myth":{"un":"You can tell who has an STI by how they look.","re":"You cannot tell by looking; many people don't know themselves.","why":"There's often nothing to see."},"relearn":"You can't tell who has an STI by looking; many don't know either.","persona":"any","source":"asymptomatic"},
  {"id":"ob-017","cat":"silent-part","type":"strike-rewrite","hook":"\"No symptoms means no infection.\"","myth":{"un":"If there are no symptoms, there's no infection.","re":"You can carry and pass on an STI with no symptoms at all.","why":"Silent infections are still active."},"relearn":"No symptoms doesn't mean no infection; silent STIs are real.","persona":"any","source":"asymptomatic"},
  {"id":"ob-018","cat":"silent-part","type":"strike-rewrite","hook":"\"If I feel fine, testing is pointless.\"","myth":{"un":"Feeling fine means there's no point testing.","re":"Because many STIs are silent, testing is exactly how you find out.","why":"Testing catches what you can't feel."},"relearn":"Testing matters even when you feel fine, many STIs are silent.","persona":"any","source":"testing rationale"},
  {"id":"ob-019","cat":"silent-part","type":"sort","hook":"Sort: a reliable way to know your status, or not?","items":[{"id":"a","text":"Getting tested"},{"id":"b","text":"Guessing by how you feel"},{"id":"c","text":"A lab result"},{"id":"d","text":"Hoping for the best"}],"bins":[{"id":"reliable","label":"Reliable"},{"id":"not","label":"Not reliable"}],"key":{"a":"reliable","b":"not","c":"reliable","d":"not"},"relearn":"Only testing reliably tells you your STI status; guessing doesn't.","persona":"any","source":"testing"},
  {"id":"ob-020","cat":"silent-part","type":"sort","hook":"Sort: true or false about symptoms?","items":[{"id":"a","text":"Many STIs show no symptoms"},{"id":"b","text":"Symptoms always appear right away"},{"id":"c","text":"You can pass one without knowing"},{"id":"d","text":"Feeling fine proves you're clear"}],"bins":[{"id":"true","label":"True"},{"id":"false","label":"False"}],"key":{"a":"true","b":"false","c":"true","d":"false"},"relearn":"STIs can be symptomless and passed on unknowingly; feeling fine isn't proof.","persona":"any","source":"asymptomatic"},
  {"id":"ob-021","cat":"silent-part","type":"sort","hook":"Sort: why testing is smart, or a weak excuse to skip it?","items":[{"id":"a","text":"It catches silent infections"},{"id":"b","text":"\"I feel okay so why bother\""},{"id":"c","text":"It protects you and partners"},{"id":"d","text":"\"Only sick-looking people need it\""}],"bins":[{"id":"smart","label":"Why it's smart"},{"id":"excuse","label":"Weak excuse"}],"key":{"a":"smart","b":"excuse","c":"smart","d":"excuse"},"relearn":"Testing catches silent infections and protects everyone; excuses don't.","persona":"any","source":"testing"},
  {"id":"ob-022","cat":"silent-part","type":"match","hook":"Match the silent-infection fact to why it matters.","pairs":[{"left":"Often no symptoms","right":"Test to know for sure"},{"left":"Can't tell by looking","right":"Don't judge, don't assume"},{"left":"Can be passed unknowingly","right":"Testing protects partners"}],"relearn":"Silent infections are exactly why testing matters so much.","persona":"any","source":"asymptomatic"},
  {"id":"ob-023","cat":"silent-part","type":"match","hook":"Match the 'silent' STI fact to the right response.","pairs":[{"left":"No symptoms yet","right":"Still worth testing"},{"left":"Unsure of status","right":"Ask a clinic"},{"left":"A partner's status unknown","right":"Both can test"}],"relearn":"When status is unknown, testing is the calm, smart move.","persona":"any","source":"testing"},
  {"id":"ob-024","cat":"silent-part","type":"reflect","hook":"Lensy: 'silent' infections are exactly why testing is normal, not scary. Make sense?","prompt":"What do you think?","options":["Yes","Testing is smart","Less scary now"],"affirm":"Testing is just how you find what you can't feel, sensible and routine.","relearn":"Testing is the sensible way to find silent infections.","persona":"any","source":"testing"},
  {"id":"ob-025","cat":"silent-part","type":"reflect","hook":"Lensy: 'I feel fine' is the most common reason people skip testing, and the riskiest. See why?","prompt":"What do you think?","options":["Yes","Silent ones hide","I'd still test"],"affirm":"Feeling fine is exactly when silent infections slip by unnoticed.","relearn":"'I feel fine' is the riskiest reason to skip testing.","persona":"any","source":"testing"},
  {"id":"ob-026","cat":"silent-part","type":"reflect","hook":"Lensy: if you can't tell by looking, then judging someone's looks proves nothing. Agree?","prompt":"What do you think?","options":["Yes","No judging","Looks tell nothing"],"affirm":"Since looks reveal nothing, judging by them is both unkind and useless.","relearn":"You can't judge STI status by looks; doing so is unfair and wrong.","persona":"any","source":"anti-stigma"},
  // — Stop the spread (the toolkit) —
  {"id":"ob-027","cat":"stop-the-spread","type":"branch","hook":"Outbreak sim: an infection is spreading. What's your first containment move?","options":[{"text":"Deploy education, people who know the facts protect themselves","consequence":"Knowledge slows the spread fast.","outcome":"strategist","best":true},{"text":"Do nothing and hope it fades","consequence":"Education is the front line; knowledge stops spread."}],"debrief":"Education is the public-health toolkit's first and biggest weapon.","relearn":"Accurate knowledge is the first tool to stop an outbreak.","persona":"any","source":"public health / sim"},
  {"id":"ob-028","cat":"stop-the-spread","type":"branch","hook":"Outbreak sim: which tool most reliably prevents an STI for someone not ready for sex?","options":[{"text":"Not having sex, fully reliable and respected","consequence":"Zero risk, and a completely valid choice.","outcome":"strategist","best":true},{"text":"Just luck","consequence":"Not having sex is the only fully reliable prevention."}],"debrief":"For anyone not ready, waiting is the fully reliable, respected choice.","relearn":"Not having sex fully prevents STIs and is completely valid.","persona":"Veer","source":"prevention / values-first"},
  {"id":"ob-029","cat":"stop-the-spread","type":"branch","hook":"Outbreak sim: deploy a tool that reduces both STIs and pregnancy.","options":[{"text":"Condoms, used correctly","consequence":"Risk drops on both fronts.","outcome":"strategist","best":true},{"text":"A 'lucky charm'","consequence":"Condoms (used correctly) cut STI and pregnancy risk; charms don't."}],"debrief":"Condoms are the one tool that lowers both STI and pregnancy risk.","relearn":"Condoms, used correctly, reduce both STIs and pregnancy.","persona":"any","source":"prevention"},
  {"id":"ob-030","cat":"stop-the-spread","type":"branch","hook":"Outbreak sim: a vaccine can wipe out most of one cancer-causing infection. Deploy it?","options":[{"text":"Yes, vaccinate, the HPV vaccine prevents most cervical cancer","consequence":"A whole future disease burden drops.","outcome":"strategist","best":true},{"text":"Skip it","consequence":"The HPV vaccine prevents around 70% of cervical cancers; deploy it."}],"debrief":"Vaccines like HPV are a powerful, lasting containment tool.","relearn":"The HPV vaccine prevents most cervical cancers; vaccines are key tools.","persona":"Riya","source":"HPV vaccine (India 2026)"},
  {"id":"ob-031","cat":"stop-the-spread","type":"branch","hook":"Outbreak sim: cases are silent and hidden. Which tool finds them?","options":[{"text":"Testing, it reveals what symptoms hide","consequence":"Hidden cases surface and get treated.","outcome":"strategist","best":true},{"text":"Wait for symptoms","consequence":"Testing finds the silent cases that waiting misses."}],"debrief":"Testing is how a containment plan finds the hidden cases.","relearn":"Testing finds silent cases so they can be treated.","persona":"any","source":"testing"},
  {"id":"ob-032","cat":"stop-the-spread","type":"branch","hook":"Outbreak sim: found cases. What stops them spreading further?","options":[{"text":"Treatment, treating cases protects everyone","consequence":"The chain of spread breaks.","outcome":"strategist","best":true},{"text":"Ignore them","consequence":"Treating cases is what actually stops onward spread."}],"debrief":"Treatment doesn't just heal a person, it stops the spread.","relearn":"Treating infections protects the person and stops spread.","persona":"Counsellor","source":"treatment"},
  {"id":"ob-033","cat":"stop-the-spread","type":"branch","hook":"Outbreak sim: fear and silence are making people hide. What do you deploy?","options":[{"text":"Reduce stigma so people seek help","consequence":"People come forward, test and treat.","outcome":"strategist","best":true},{"text":"Blame and shame the infected","consequence":"Stigma drives it underground; reducing it helps people seek care."}],"debrief":"Cutting stigma is a public-health tool, it gets people to care.","relearn":"Reducing stigma helps people seek testing and treatment.","persona":"any","source":"anti-stigma / public health"},
  {"id":"ob-034","cat":"stop-the-spread","type":"branch","hook":"Outbreak sim: combine your tools for the strongest plan.","options":[{"text":"Education + prevention + testing + treatment together","consequence":"The outbreak is contained.","outcome":"strategist","best":true},{"text":"Pick just one and ignore the rest","consequence":"The toolkit works best when layered together."}],"debrief":"Real containment layers all the tools, not just one.","relearn":"Layering education, prevention, testing and treatment works best.","persona":"any","source":"public health"},
  {"id":"ob-035","cat":"stop-the-spread","type":"build","hook":"Build the public-health containment toolkit.","prompt":"Assemble the tools that stop the spread.","pieces":["education and facts","prevention (waiting or condoms)","vaccines like HPV","testing and treatment"],"mode":"assemble","key":["education and facts","prevention (waiting or condoms)","vaccines like HPV","testing and treatment"],"relearn":"The toolkit: education, prevention, vaccines, testing and treatment.","persona":"any","source":"public health"},
  {"id":"ob-036","cat":"stop-the-spread","type":"build","hook":"Build the prevention ladder, most to least reliable.","prompt":"Order from most reliable down.","pieces":["not having sex","condoms used correctly","condoms used carelessly","nothing at all"],"mode":"sequence","key":["not having sex","condoms used correctly","condoms used carelessly","nothing at all"],"relearn":"Not having sex is most reliable; correct condom use next; nothing is the riskiest.","persona":"any","source":"prevention"},
  {"id":"ob-037","cat":"stop-the-spread","type":"build","hook":"Build what the HPV vaccine does (India context).","prompt":"Assemble the facts.","pieces":["prevents most cervical cancer","also prevents genital warts","free for 14-year-old girls in India","given at a health centre"],"mode":"assemble","key":["prevents most cervical cancer","also prevents genital warts","free for 14-year-old girls in India","given at a health centre"],"relearn":"The HPV vaccine prevents most cervical cancer and is free for 14-year-old girls in India.","persona":"Riya","source":"HPV vaccine (India 2026)"},
  {"id":"ob-038","cat":"stop-the-spread","type":"sort","hook":"Sort: a real prevention tool, or not?","items":[{"id":"a","text":"The HPV vaccine"},{"id":"b","text":"Condoms"},{"id":"c","text":"Crossing fingers"},{"id":"d","text":"A 'detox' drink"}],"bins":[{"id":"real","label":"Real tool"},{"id":"not","label":"Not a tool"}],"key":{"a":"real","b":"real","c":"not","d":"not"},"relearn":"Vaccines and condoms are real prevention; luck and 'detoxes' aren't.","persona":"any","source":"prevention"},
  {"id":"ob-039","cat":"stop-the-spread","type":"sort","hook":"Sort: helps stop the spread, or spreads it further?","items":[{"id":"a","text":"Getting vaccinated"},{"id":"b","text":"Hiding an infection out of shame"},{"id":"c","text":"Getting tested and treated"},{"id":"d","text":"Believing rumours"}],"bins":[{"id":"stops","label":"Stops spread"},{"id":"spreads","label":"Spreads it"}],"key":{"a":"stops","b":"spreads","c":"stops","d":"spreads"},"relearn":"Vaccines, testing and treatment stop spread; shame and rumours fuel it.","persona":"any","source":"public health"},
  {"id":"ob-040","cat":"stop-the-spread","type":"sort","hook":"Sort: condom facts, true or false?","items":[{"id":"a","text":"They reduce STI risk"},{"id":"b","text":"They also reduce pregnancy"},{"id":"c","text":"They work without correct use"},{"id":"d","text":"They're 100% guaranteed"}],"bins":[{"id":"true","label":"True"},{"id":"false","label":"False"}],"key":{"a":"true","b":"true","c":"false","d":"false"},"relearn":"Condoms reduce STI and pregnancy risk when used correctly; no method is 100% except not having sex.","persona":"any","source":"prevention"},
  {"id":"ob-041","cat":"stop-the-spread","type":"reflect","hook":"Lensy: it feels good to realise STIs are preventable, not some unstoppable doom. Right?","prompt":"What do you think?","options":["Yes","They're preventable","Reassuring"],"affirm":"STIs are preventable and manageable, knowledge really is power here.","relearn":"STIs are preventable; the toolkit gives you real control.","persona":"any","source":"empowerment"},
  {"id":"ob-042","cat":"stop-the-spread","type":"reflect","hook":"Lensy: the strongest containment plan is layered, not a single magic fix. See why?","prompt":"What do you think?","options":["Yes","Layers work","Combine the tools"],"affirm":"No single tool is magic; layered together they're powerful.","relearn":"Layered prevention beats relying on any single tool.","persona":"any","source":"public health"},
  // — Testing & treatment —
  {"id":"ob-043","cat":"test-and-treat","type":"branch","hook":"You realise you should probably get tested but feel nervous.","options":[{"text":"Go to a clinic or doctor; it's routine and often confidential","consequence":"You get clarity and care.","outcome":"responsible","best":true},{"text":"Avoid it out of nerves","consequence":"Testing is routine and confidential; it's the responsible step."}],"debrief":"Testing is a normal, responsible health check, not a verdict.","relearn":"Testing is routine and often confidential; getting tested is responsible.","persona":"Counsellor","source":"testing"},
  {"id":"ob-044","cat":"test-and-treat","type":"branch","hook":"A clinic visit feels intimidating and you don't know what happens.","options":[{"text":"Ask what to expect; bring a trusted person if it helps","consequence":"It feels manageable and you go.","outcome":"resourceful","best":true},{"text":"Skip it because it's unknown","consequence":"Asking what to expect, or bringing someone, makes it doable."}],"debrief":"Knowing what to expect makes testing far less scary.","relearn":"You can ask what to expect and bring support to a clinic.","persona":"any","source":"testing / access"},
  {"id":"ob-045","cat":"test-and-treat","type":"branch","hook":"You're worried testing won't be private.","options":[{"text":"Ask about confidentiality; many services protect your privacy","consequence":"You learn your privacy is taken seriously.","outcome":"informed","best":true},{"text":"Assume the worst and avoid it","consequence":"Ask, many services are confidential and youth-friendly."}],"debrief":"Privacy concerns are valid, and often well protected; ask first.","relearn":"You can ask about confidentiality; many testing services protect privacy.","persona":"any","source":"confidentiality"},
  {"id":"ob-046","cat":"test-and-treat","type":"branch","hook":"A diagnosis comes back positive for a treatable STI.","options":[{"text":"Follow treatment and tell partners so they can test too","consequence":"You get well and stop the spread.","outcome":"responsible","best":true},{"text":"Panic and hide it","consequence":"Most STIs are treatable; treatment and telling partners is the way."}],"debrief":"A positive result is a health issue to treat, not a catastrophe.","relearn":"A treatable STI means: get treated and tell partners to test.","persona":"Counsellor","source":"treatment / partner notification"},
  {"id":"ob-047","cat":"test-and-treat","type":"branch","hook":"You're unsure whether STIs can even be cured.","options":[{"text":"Learn the facts: all are treatable, most are curable","consequence":"The fear shrinks with the facts.","outcome":"informed","best":true},{"text":"Assume it's hopeless","consequence":"All STIs are treatable and most are curable; it's far from hopeless."}],"debrief":"All STIs are treatable and most are curable, that's the real picture.","relearn":"All STIs are treatable and most are curable.","persona":"any","source":"treatment (CDC)"},
  {"id":"ob-048","cat":"test-and-treat","type":"branch","hook":"A friend is scared to get tested. You want to help.","options":[{"text":"Reassure them it's normal and offer to go along","consequence":"They feel supported enough to go.","outcome":"caring","best":true},{"text":"Tell them they're overthinking it","consequence":"Reassurance and company help more than dismissal."}],"debrief":"Going with a friend can turn fear into a done, healthy step.","relearn":"You can reassure a friend and go with them to get tested.","persona":"any","source":"peer support"},
  {"id":"ob-049","cat":"test-and-treat","type":"role-play","hook":"You want to ask a doctor about getting tested.","setup":"Just ask plainly. Say:","yourLine":[{"text":"\"I'd like to get tested, can you tell me how it works?\"","best":true},{"text":"Say nothing and leave"}],"relearn":"You can simply ask a doctor how testing works; that's their job.","persona":"any","source":"help-seeking"},
  {"id":"ob-050","cat":"test-and-treat","type":"role-play","hook":"A partner needs to hear you've tested positive for something treatable.","setup":"Be honest and caring. Say:","yourLine":[{"text":"\"I got tested and want you to be able to test too, just to be safe.\"","best":true},{"text":"Say nothing and hope it's fine"}],"relearn":"Telling a partner so they can test is honest and protects them.","persona":"any","source":"partner notification"},
  {"id":"ob-051","cat":"test-and-treat","type":"role-play","hook":"A friend says getting tested means you've 'done something shameful'.","setup":"Reframe it. Say:","yourLine":[{"text":"\"Testing is just smart healthcare, like any check-up.\"","best":true},{"text":"\"Yeah, maybe it is shameful...\""}],"relearn":"Testing is responsible healthcare, not something shameful.","persona":"Veer","source":"de-stigmatise"},
  {"id":"ob-052","cat":"test-and-treat","type":"strike-rewrite","hook":"\"Getting tested means you assume the worst about yourself.\"","myth":{"un":"Getting tested means you think the worst of yourself.","re":"Testing is a normal, caring health habit, like any check-up.","why":"It protects you and the people you care about."},"relearn":"Testing is a caring, normal health habit, not self-suspicion.","persona":"any","source":"de-stigmatise"},
  {"id":"ob-053","cat":"test-and-treat","type":"build","hook":"Build the smart 'test and treat' sequence.","prompt":"Order the responsible steps.","pieces":["get tested when needed","get the result","follow treatment if positive","tell partners so they can test"],"mode":"sequence","key":["get tested when needed","get the result","follow treatment if positive","tell partners so they can test"],"relearn":"Test, get the result, treat if needed, and tell partners, the responsible chain.","persona":"any","source":"test & treat"},
  {"id":"ob-054","cat":"test-and-treat","type":"build","hook":"Build the 'where to go' list for testing and facts.","prompt":"Assemble trustworthy options.","pieces":["a doctor or clinic","a youth-friendly health service","a trusted adult to help you go","reliable health information"],"mode":"assemble","key":["a doctor or clinic","a youth-friendly health service","a trusted adult to help you go","reliable health information"],"relearn":"For testing and facts: clinics, youth services, a trusted adult, reliable info.","persona":"Counsellor","source":"access"},
  {"id":"ob-055","cat":"test-and-treat","type":"match","hook":"Match the worry to the reassuring fact.","pairs":[{"left":"\"It'll be public\"","right":"Often confidential"},{"left":"\"It's hopeless\"","right":"Treatable, often curable"},{"left":"\"I'll be judged\"","right":"It's routine healthcare"}],"relearn":"Common testing fears each have a reassuring, factual answer.","persona":"any","source":"testing"},
  {"id":"ob-056","cat":"test-and-treat","type":"reflect","hook":"Lensy: testing early means easier treatment and less spread, a win all round. Agree?","prompt":"What do you think?","options":["Yes","Early is better","Win-win"],"affirm":"The sooner you know, the easier it is to treat and protect others.","relearn":"Testing early makes treatment easier and protects others.","persona":"any","source":"testing"},
  // — Bust the STI myths —
  {"id":"ob-057","cat":"bust-myths","type":"strike-rewrite","hook":"\"Only 'certain kinds' of people get STIs.\"","myth":{"un":"Only certain 'kinds' of people get STIs.","re":"Anyone who is sexually active can get an STI; they don't discriminate.","why":"They're infections, not a judgement on character."},"relearn":"Anyone sexually active can get an STI; they aren't about 'type' of person.","persona":"any","source":"anti-stigma"},
  {"id":"ob-058","cat":"bust-myths","type":"strike-rewrite","hook":"\"Having an STI means you're dirty or a bad person.\"","myth":{"un":"An STI means you're dirty or a bad person.","re":"An STI is a common health condition, nothing to do with worth.","why":"Illness is never a moral failing."},"relearn":"An STI is a health condition, not a sign of being 'dirty' or 'bad'.","persona":"any","source":"anti-stigma"},
  {"id":"ob-059","cat":"bust-myths","type":"strike-rewrite","hook":"\"If someone looks clean and healthy, they're definitely STI-free.\"","myth":{"un":"A 'clean-looking', healthy person can't have an STI.","re":"You can't tell by looks; many carriers feel and look fine.","why":"Silent infections show nothing."},"relearn":"You can't judge STI status by how 'clean' someone looks.","persona":"any","source":"asymptomatic"},
  {"id":"ob-060","cat":"bust-myths","type":"strike-rewrite","hook":"\"Doing it just once can't give you an STI.\"","myth":{"un":"You can't get an STI from a single time.","re":"One instance of unprotected contact can transmit an STI.","why":"Risk is there from the first time."},"relearn":"One time of unprotected contact can transmit an STI.","persona":"any","source":"transmission"},
  {"id":"ob-061","cat":"bust-myths","type":"strike-rewrite","hook":"\"Two showers and you're fine after risky contact.\"","myth":{"un":"Washing well after sex prevents STIs.","re":"Washing does not prevent or remove an STI.","why":"You can't rinse an infection away."},"relearn":"Washing afterwards doesn't prevent STIs; only real prevention does.","persona":"any","source":"myth-busting"},
  {"id":"ob-062","cat":"bust-myths","type":"strike-rewrite","hook":"\"STIs always have obvious, gross symptoms.\"","myth":{"un":"STIs always come with obvious symptoms.","re":"Many have none; symptoms are an unreliable guide.","why":"Silent infections are extremely common."},"relearn":"STIs often have no symptoms; you can't rely on noticing.","persona":"any","source":"asymptomatic"},
  {"id":"ob-063","cat":"bust-myths","type":"strike-rewrite","hook":"\"There's no point learning this unless you're already having sex.\"","myth":{"un":"This is only worth learning once you're having sex.","re":"Knowing it early helps you stay safe and unstigmatised whenever the time comes.","why":"Knowledge ahead of time is protection."},"relearn":"Learning STI facts early is protection for whenever it's relevant.","persona":"Veer","source":"CSE rationale"},
  {"id":"ob-064","cat":"bust-myths","type":"sort","hook":"Sort: STI myth, or fact?","items":[{"id":"a","text":"\"You'd always know you had one\""},{"id":"b","text":"\"Many are symptomless\""},{"id":"c","text":"\"Only 'certain people' get them\""},{"id":"d","text":"\"Most are curable\""}],"bins":[{"id":"myth","label":"Myth"},{"id":"fact","label":"Fact"}],"key":{"a":"myth","b":"fact","c":"myth","d":"fact"},"relearn":"'You'd know' and 'only certain people' are myths; symptomless and curable are facts.","persona":"any","source":"myth-busting"},
  {"id":"ob-065","cat":"bust-myths","type":"sort","hook":"Sort: protects you, or is a useless myth?","items":[{"id":"a","text":"Condoms used correctly"},{"id":"b","text":"Washing after"},{"id":"c","text":"Vaccines like HPV"},{"id":"d","text":"Judging by looks"}],"bins":[{"id":"protects","label":"Actually protects"},{"id":"myth","label":"Useless myth"}],"key":{"a":"protects","b":"myth","c":"protects","d":"myth"},"relearn":"Condoms and vaccines protect; washing-after and looks-judging don't.","persona":"any","source":"prevention / myth"},
  {"id":"ob-066","cat":"bust-myths","type":"sort","hook":"Sort: reduces stigma, or spreads it?","items":[{"id":"a","text":"\"STIs are common health conditions\""},{"id":"b","text":"\"Only bad people get them\""},{"id":"c","text":"\"Testing is responsible\""},{"id":"d","text":"\"They're dirty and shameful\""}],"bins":[{"id":"reduces","label":"Reduces stigma"},{"id":"spreads","label":"Spreads stigma"}],"key":{"a":"reduces","b":"spreads","c":"reduces","d":"spreads"},"relearn":"Framing STIs as common, treatable health issues reduces stigma.","persona":"any","source":"anti-stigma"},
  {"id":"ob-067","cat":"bust-myths","type":"match","hook":"Match the myth to the fact that beats it.","pairs":[{"left":"\"You'd know\"","right":"Many are silent"},{"left":"\"Only certain people\"","right":"Anyone can"},{"left":"\"Incurable doom\"","right":"Treatable, often curable"}],"relearn":"Every STI myth has a clear, reassuring fact that beats it.","persona":"any","source":"myth-busting"},
  {"id":"ob-068","cat":"bust-myths","type":"match","hook":"Match the reliable source to the unreliable one.","pairs":[{"left":"A doctor or clinic","right":"Trust it"},{"left":"A scary forwarded message","right":"Be skeptical"},{"left":"A reputable health site","right":"Trust it"}],"relearn":"Trust clinics and reputable health info over scary forwards.","persona":"any","source":"media literacy"},
  {"id":"ob-069","cat":"bust-myths","type":"reflect","hook":"Lensy: notice how many STI 'facts' people repeat are actually stigma in disguise?","prompt":"What do you think?","options":["Yes","A lot are","I'll question them"],"affirm":"Many 'STI facts' are really just stigma; questioning them helps everyone.","relearn":"Many repeated STI 'facts' are stigma in disguise; question them.","persona":"any","source":"anti-stigma"},
  {"id":"ob-070","cat":"bust-myths","type":"reflect","hook":"Lensy: which myth do you think trips the most people up?","prompt":"Pick one.","options":["\"You'd always know\"","\"Only certain people\"","\"One time is fine\"","\"You can tell by looks\""],"affirm":"Spotting the trickiest myth means you can help correct it.","relearn":"Knowing the common myths helps you correct them.","persona":"any","source":"myth-busting"},
  // — End the stigma —
  {"id":"ob-071","cat":"end-stigma","type":"branch","hook":"Classmates are mocking someone rumoured to have an STI.","options":[{"text":"Refuse to join and shut the cruelty down","consequence":"You protect a person from real harm.","outcome":"ally","best":true},{"text":"Laugh along","consequence":"Mocking someone over an STI is cruel; refuse and defend."}],"debrief":"An STI rumour is a health matter, never material for mockery.","relearn":"Don't mock anyone over an STI; defend them instead.","persona":"any","source":"anti-stigma / upstander (links g19)"},
  {"id":"ob-072","cat":"end-stigma","type":"branch","hook":"A friend confides they tested positive and feels ashamed.","options":[{"text":"Reassure them it's a treatable health issue, not a character flaw","consequence":"They feel supported and seek treatment.","outcome":"caring","best":true},{"text":"Pull away from them","consequence":"Support and facts help; pulling away deepens shame."}],"debrief":"A diagnosis needs support and facts, not distance.","relearn":"Support a friend with an STI; it's a health issue, not a flaw.","persona":"any","source":"anti-stigma"},
  {"id":"ob-073","cat":"end-stigma","type":"branch","hook":"You catch yourself feeling judgemental about someone with an STI.","options":[{"text":"Remember the facts and choose compassion","consequence":"Your knowledge replaces judgement.","outcome":"growth","best":true},{"text":"Let the judgement stand","consequence":"The facts, common, treatable, no shame, point to compassion."}],"debrief":"Facts turn judgement into understanding and kindness.","relearn":"Let the facts move you from judging to compassion.","persona":"any","source":"anti-stigma / self"},
  {"id":"ob-074","cat":"end-stigma","type":"branch","hook":"Stigma is stopping people in your community from getting tested.","options":[{"text":"Share that testing is normal, smart and confidential","consequence":"More people feel safe to test.","outcome":"changemaker","best":true},{"text":"Stay quiet about it","consequence":"Normalising testing helps people overcome the stigma barrier."}],"debrief":"Reducing stigma is what gets people through the clinic door.","relearn":"Normalising testing helps people get past stigma to care.","persona":"Counsellor","source":"anti-stigma / public health"},
  {"id":"ob-075","cat":"end-stigma","type":"role-play","hook":"Someone says people with STIs 'deserve it'.","setup":"Push back. Say:","yourLine":[{"text":"\"No one deserves illness; they deserve care.\"","best":true},{"text":"Nod along"}],"relearn":"No one 'deserves' an STI; everyone deserves care.","persona":"any","source":"anti-stigma"},
  {"id":"ob-076","cat":"end-stigma","type":"role-play","hook":"A friend is terrified to tell anyone about their diagnosis.","setup":"Be a safe place. Say:","yourLine":[{"text":"\"I'm still your friend, and this stays with me.\"","best":true},{"text":"\"This changes everything between us.\""}],"relearn":"You can be a safe, private support for a friend with an STI.","persona":"any","source":"anti-stigma / privacy"},
  {"id":"ob-077","cat":"end-stigma","type":"role-play","hook":"People are spreading a cruel rumour about someone's status.","setup":"Stop it. Say:","yourLine":[{"text":"\"Their health is private, let's drop it.\"","best":true},{"text":"Pass the rumour on"}],"relearn":"Someone's STI status is private; refuse to spread rumours.","persona":"Riya","source":"anti-stigma / privacy"},
  {"id":"ob-078","cat":"end-stigma","type":"strike-rewrite","hook":"\"Stigma is harmless, it's just words.\"","myth":{"un":"Stigma about STIs is harmless, just words.","re":"Stigma stops people testing and treating, so it spreads disease.","why":"Shame is itself a public-health danger."},"relearn":"Stigma is harmful, it stops people getting tested and treated.","persona":"Counsellor","source":"anti-stigma"},
  {"id":"ob-079","cat":"end-stigma","type":"reflect","hook":"Lensy: 'the real enemy is the infection, never the person', sit right with you?","prompt":"What do you think?","options":["Yes","Never the person","Well put"],"affirm":"Fight the infection and the stigma, never the people.","relearn":"The enemy is the infection and the stigma, never the person.","persona":"any","source":"anti-stigma"},
  {"id":"ob-080","cat":"end-stigma","type":"reflect","hook":"Lensy: a community without shame is one where people actually get tested. See the link?","prompt":"What do you think?","options":["Yes","Less shame, more care","It connects"],"affirm":"Less stigma means more testing, treatment and health for everyone.","relearn":"Less stigma leads to more testing and better health for all.","persona":"any","source":"public health"},
  {"id":"ob-081","cat":"end-stigma","type":"reflect","hook":"Lensy: biggest take-away from Outbreak?","prompt":"Pick your motto.","options":["Knowledge stops the spread","Testing is smart and normal","Most STIs are treatable","Stigma is the real enemy"],"affirm":"Stop the spread with facts, prevention and care, never with shame.","relearn":"Beat STIs with facts, prevention, testing and care, not stigma.","persona":"any","source":"consolidation"},
  {"id":"ob-082","cat":"end-stigma","type":"sort","hook":"Sort: a kind, fact-based response, or a stigmatising one?","items":[{"id":"a","text":"\"Let's get you to a clinic\""},{"id":"b","text":"\"You're disgusting now\""},{"id":"c","text":"\"It's treatable, you'll be okay\""},{"id":"d","text":"\"I'm telling everyone\""}],"bins":[{"id":"kind","label":"Kind & factual"},{"id":"stigma","label":"Stigmatising"}],"key":{"a":"kind","b":"stigma","c":"kind","d":"stigma"},"relearn":"Kind, factual responses help; mockery and exposure harm.","persona":"any","source":"anti-stigma"},
  {"id":"ob-083","cat":"end-stigma","type":"strike-rewrite","hook":"\"People with STIs should be kept away from everyone.\"","myth":{"un":"People with STIs should be shunned or kept apart.","re":"They belong fully in everyday life; STIs don't spread by ordinary contact.","why":"Exclusion is fear, not fact."},"relearn":"People with STIs belong fully in everyday life; shunning is wrong.","persona":"any","source":"anti-stigma"},
  {"id":"ob-084","cat":"end-stigma","type":"reflect","hook":"Lensy: you can be the person who reacts with facts and kindness. Want to be?","prompt":"What do you think?","options":["Yes","Facts and kindness","That's me"],"affirm":"That's exactly the person who helps stop both the disease and the shame.","relearn":"Reacting with facts and kindness stops both disease and stigma.","persona":"any","source":"consolidation"},
];

export const OUTBREAK: V2GameConfig = {
  gameId: "outbreak",
  title: "Outbreak: Stop the Spread",
  greet: "Hey, it's Lensy. 🧫 Let's stop an outbreak with the real toolkit: facts, prevention, testing, treatment. The enemy is the infection and stigma, not people.",
  scenarios: SCENARIOS,
  categories: [
    { id: "how-stis-spread", emoji: "🧫", label: "How STIs spread" },
    { id: "silent-part", emoji: "🤐", label: "The silent part" },
    { id: "stop-the-spread", emoji: "🛡️", label: "Stop the spread" },
    { id: "test-and-treat", emoji: "🩺", label: "Test & treat" },
    { id: "bust-myths", emoji: "💥", label: "Bust the myths" },
    { id: "end-stigma", emoji: "💛", label: "End the stigma" },
  ],
  badge: {
    title: "Outbreak Stopper! 🧫",
    blurb: "You know how STIs spread (and don't), why testing matters, the toolkit (waiting, condoms, vaccines, testing, treatment), and that stigma is the real enemy.",
  },
  helpLine: "For STI facts or testing, see a clinic, youth health service, or doctor, it's routine and often confidential. Get facts from clinics, not scary forwards.",
  helpLabel: "Get tested · ask a clinic",
  reassure: "STIs are common, treatable health conditions, never a sign of being 'dirty' or 'bad'. The enemy is the infection and the stigma, never the person. 💛",
  reassureCats: ["end-stigma"],
  buildLabels: { assemble: "That's the toolkit 🛡️", sequence: "That's the smart order ✅" },
};
