// Content for Puberty Quest (node g13, ages 9–12, Chapter 3) — NEW v2 build to GDD 13 (mechanic-embodying),
// the timely puberty node and the FIRST Chapter 3 node, where the register turns matter-of-fact, near-peer
// (Lensy grows up a little) and the play goes PRIVATE / SOLO. "Your body's growing up, and that's normal."
// 85 researched, India-grounded scenarios across six categories, each encoded as one of the shared v2 play
// actions (strike-rewrite / reflect / branch / match / sort / build / role-play) — no binary "tap the right
// card", led by myth-busts (strike-rewrite ×23 — the densest taboo-busting set so far) + private reflections
// + real-moment dilemmas (branch). Teaches: what puberty is & why (wide range of normal), girls' changes
// (periods explained), boys' changes (voice, wet dreams, erections — the ones no one warns them about),
// body care & moods, PERIODS WITHOUT SHAME (busting India's menstrual taboos — 'impure', can't-touch-food,
// must-miss-school — with dignity), and where to find trusted answers. PRIVATE & SOLO (no 'show a parent';
// embarrassment is the gatekeeper, so the app is the trusted source); ACCURATE & INCLUSIVE (proper names;
// girls AND boys; boys learn about periods too); BUST TABOOS, RESPECT FAMILIES (named as myths while keeping
// the child's dignity, never told to defy elders); EQUITY & DIGNITY (period poverty handled with care, no one
// should miss school); never graphic; routes to trusted sources / support (Childline 1098). Builds on g06
// (Body Lab Juniors); feeds g14 (The Amazing Journey) & g38 (Mind Matters). Rendered by the shared engine
// (components/games/v2-engine.tsx). gameId "puberty-quest". DO NOT RENAME.

import type { Scenario, V2GameConfig } from "./v2-schema";

const SCENARIOS: Scenario[] = [
  // — What puberty is (and that it's normal) —
  {"id":"pq-001","cat":"whats-puberty","type":"strike-rewrite","hook":"\"Something must be wrong, my body is changing.\"","myth":{"un":"My body changing means something is wrong with me.","re":"Puberty is the normal, healthy way your body grows up.","why":"Everyone's body goes through it."},"relearn":"Puberty is a normal, healthy part of growing up.","persona":"Diya","source":"puberty basics"},
  {"id":"pq-002","cat":"whats-puberty","type":"reflect","hook":"Lensy (near-peer): puberty is just your body's 'growing-up' phase. How does that land?","prompt":"What do you think?","options":["Makes sense","Good to know","Less scary now"],"affirm":"Knowing it's normal takes a lot of the worry out of it.","relearn":"Puberty is a phase everybody goes through; knowing that helps.","persona":"any","source":"normalisation"},
  {"id":"pq-003","cat":"whats-puberty","type":"strike-rewrite","hook":"\"Everyone changes at the same time, so I'm 'behind' or 'ahead'.\"","myth":{"un":"Everyone should go through puberty at the same time.","re":"Puberty starts anywhere from about 8-14; everyone's on their own clock.","why":"There's a wide range of totally normal."},"relearn":"Everyone starts puberty at their own time; there's a wide normal range.","persona":"any","source":"timeline variation"},
  {"id":"pq-004","cat":"whats-puberty","type":"match","hook":"Match the puberty change to what's behind it.","pairs":[{"left":"Growth spurt","right":"Hormones telling you to grow"},{"left":"New body hair","right":"A normal puberty sign"},{"left":"Mood swings","right":"Hormones, totally normal"}],"relearn":"Hormones drive puberty's changes, and they're all normal.","persona":"any","source":"puberty science"},
  {"id":"pq-005","cat":"whats-puberty","type":"reflect","hook":"Lensy: feeling a bit nervous about changes is normal too. You?","prompt":"How are you feeling?","options":["Curious","A bit nervous","Mostly okay","Want to know more"],"affirm":"All of those are normal. Knowing what's coming makes it easier.","relearn":"It's normal to feel curious or nervous about puberty.","persona":"Diya","source":"emotional normalisation"},
  {"id":"pq-006","cat":"whats-puberty","type":"sort","hook":"Sort: a normal puberty change, or not a thing?","items":[{"id":"a","text":"Getting taller fast"},{"id":"b","text":"Suddenly needing a different shoe size overnight by magic"},{"id":"c","text":"New body hair"},{"id":"d","text":"Your eye colour totally changing"}],"bins":[{"id":"normal","label":"Normal puberty change"},{"id":"not","label":"Not a puberty thing"}],"key":{"a":"normal","b":"not","c":"normal","d":"not"},"relearn":"Growth spurts and new body hair are real puberty changes.","persona":"any","source":"puberty basics"},
  {"id":"pq-007","cat":"whats-puberty","type":"strike-rewrite","hook":"\"Puberty only happens to girls.\"","myth":{"un":"Puberty only happens to girls.","re":"All bodies go through puberty, girls and boys, in their own ways.","why":"Everyone's body grows up."},"relearn":"Puberty happens to everyone, just with some different changes.","persona":"Aarav","source":"puberty basics"},
  {"id":"pq-008","cat":"whats-puberty","type":"reflect","hook":"Lensy: this is private, just-for-you info. Glad it's a safe space?","prompt":"What do you think?","options":["Yes","Good, it's private","Easier to learn here"],"affirm":"This is your private space to learn what you're too shy to ask. No judgement.","relearn":"You can learn about your body privately and without shame.","persona":"Diya","source":"privacy / trust"},
  {"id":"pq-009","cat":"whats-puberty","type":"branch","hook":"A friend says puberty is 'gross' and refuses to learn about it.","options":[{"text":"Say \"it's just normal growing up, good to understand\"","consequence":"You both feel less weird about it.","outcome":"matter-of-fact","best":true},{"text":"Agree it's gross and stay confused","consequence":"Understanding it beats being grossed out and unprepared."}],"debrief":"Puberty isn't gross; it's just biology, and worth understanding.","relearn":"Puberty is normal biology, not something gross.","persona":"any","source":"normalisation"},
  // — Changes for girls (periods explained) —
  {"id":"pq-010","cat":"girls-changes","type":"strike-rewrite","hook":"\"A period means something is wrong or I'm hurt.\"","myth":{"un":"Bleeding during a period means something is wrong.","re":"A period is a normal, healthy monthly cycle, not an injury.","why":"It's a sign the body is growing up as it should."},"relearn":"A period is a normal, healthy part of growing up, not an injury.","persona":"Diya","source":"menstruation basics"},
  {"id":"pq-011","cat":"girls-changes","type":"reflect","hook":"Lensy explains simply: a period is the body's monthly cycle, where a little blood leaves through the vagina over a few days. Clearer now?","prompt":"What do you think?","options":["Yes, clearer","Good to know","Makes sense"],"affirm":"That's all it is, a normal monthly cycle. Now you know.","relearn":"A period is a normal monthly cycle lasting a few days.","persona":"Diya","source":"menstruation basics"},
  {"id":"pq-012","cat":"girls-changes","type":"match","hook":"Match the period question to its simple answer.","pairs":[{"left":"How long does it last?","right":"Usually a few days, monthly"},{"left":"What can I use?","right":"Pads, cloth, or a cup"},{"left":"Cramps, normal?","right":"Yes, common; warmth/rest help"}],"relearn":"Periods last a few days, products help, and cramps are common.","persona":"Diya","source":"menstruation basics"},
  {"id":"pq-013","cat":"girls-changes","type":"branch","hook":"You get your first period at school and feel panicked.","options":[{"text":"Tell a trusted teacher or friend and get a pad","consequence":"You're sorted; it's a normal thing lots handle daily.","outcome":"prepared","best":true},{"text":"Hide and feel ashamed all day","consequence":"There's no shame; asking for a pad is completely okay."}],"debrief":"A first period is normal; asking a trusted person for a pad is fine.","relearn":"If your period starts, it's okay to ask a trusted person for help.","persona":"Diya","source":"menstruation / preparedness"},
  {"id":"pq-014","cat":"girls-changes","type":"strike-rewrite","hook":"\"Breast changes mean I'm developing 'too early' or 'wrong'.\"","myth":{"un":"Breast changes at my age are wrong or too early.","re":"Breast development is a normal early sign of puberty, on its own timeline.","why":"It starts at different ages for everyone."},"relearn":"Breast changes are a normal puberty sign, at your own pace.","persona":"any","source":"puberty basics"},
  {"id":"pq-015","cat":"girls-changes","type":"build","hook":"Build a 'first-period kit' to keep ready.","prompt":"Pack what helps.","pieces":["a few pads (or cloth/cup)","a spare underwear","a small pouch","know a trusted person to ask"],"mode":"assemble","key":["a few pads (or cloth/cup)","a spare underwear","a small pouch","know a trusted person to ask"],"relearn":"Being prepared with a small kit makes periods no big deal.","persona":"Diya","source":"menstrual preparedness"},
  {"id":"pq-016","cat":"girls-changes","type":"reflect","hook":"Lensy: periods are something half the world experiences. Feel less alone?","prompt":"What do you think?","options":["Yes","So many people get them","Less weird now"],"affirm":"Billions of people menstruate; you're in very good company.","relearn":"Periods are extremely common; you're not alone.","persona":"Diya","source":"normalisation"},
  {"id":"pq-017","cat":"girls-changes","type":"strike-rewrite","hook":"\"Periods should be a secret nobody ever mentions.\"","myth":{"un":"Periods must be kept totally secret.","re":"Periods are normal and okay to talk about with trusted people.","why":"Silence makes a normal thing feel shameful."},"relearn":"It's okay to talk about periods with people you trust.","persona":"Rekha","source":"stigma reduction"},
  {"id":"pq-018","cat":"girls-changes","type":"match","hook":"Match the period-care basic to why it matters.","pairs":[{"left":"Change pad/cloth regularly","right":"Stays clean & comfy"},{"left":"Wash and dry cloth well","right":"Keeps it hygienic"},{"left":"Rest if cramps are bad","right":"Helps you feel better"}],"relearn":"Simple care keeps periods clean, comfy and no big deal.","persona":"Asha","source":"menstrual hygiene"},
  // — Changes for boys —
  {"id":"pq-019","cat":"boys-changes","type":"strike-rewrite","hook":"\"My voice cracking means something's wrong with me.\"","myth":{"un":"A cracking voice means something's wrong.","re":"Voice changes are a normal puberty sign for boys; it settles.","why":"The voice box is growing."},"relearn":"A changing, cracking voice is a normal puberty sign.","persona":"Aarav","source":"puberty basics"},
  {"id":"pq-020","cat":"boys-changes","type":"reflect","hook":"Lensy (matter-of-fact): wet dreams, releasing some fluid during sleep, are a normal puberty thing. Good to know before it happens?","prompt":"What do you think?","options":["Yes, glad to know","Less confusing now","Good heads-up"],"affirm":"Totally normal, not bedwetting, and nothing to be embarrassed about.","relearn":"Wet dreams are a normal part of puberty; nothing to be ashamed of.","persona":"Aarav","source":"puberty basics"},
  {"id":"pq-021","cat":"boys-changes","type":"match","hook":"Match the boys' puberty change to 'normal'.","pairs":[{"left":"Deeper voice","right":"Normal"},{"left":"More body & facial hair","right":"Normal"},{"left":"Growth spurt & bigger feet","right":"Normal"}],"relearn":"Deeper voice, more hair and growth are all normal for boys.","persona":"Aarav","source":"puberty basics"},
  {"id":"pq-022","cat":"boys-changes","type":"strike-rewrite","hook":"\"Boys shouldn't feel emotional during puberty, just 'be a man'.\"","myth":{"un":"Real boys don't get emotional during puberty.","re":"Hormones bring mood changes for everyone; boys' feelings are normal too.","why":"Bottling up emotions isn't strength."},"relearn":"Boys feel mood changes too; that's normal, not unmanly.","persona":"Aarav","source":"gender / emotional health"},
  {"id":"pq-023","cat":"boys-changes","type":"branch","hook":"You notice puberty changes and feel embarrassed to ask anyone.","options":[{"text":"Look it up from a trusted source or ask a trusted adult","consequence":"You get accurate info instead of guessing.","outcome":"informed","best":true},{"text":"Guess from random online stuff","consequence":"Trusted sources beat random guesses for body questions."}],"debrief":"For body questions, trusted sources beat random internet guesses.","relearn":"Get puberty info from trusted sources, not random guesses.","persona":"Aarav","source":"information literacy"},
  {"id":"pq-023b","cat":"boys-changes","type":"reflect","hook":"Lensy: every boy goes through this, even the ones who act like they don't. True?","prompt":"What do you think?","options":["Yes","Everyone does","Reassuring"],"affirm":"Every boy goes through puberty; the cool act is just an act.","relearn":"All boys go through puberty, whatever they pretend.","persona":"Aarav","source":"normalisation"},
  {"id":"pq-024","cat":"boys-changes","type":"strike-rewrite","hook":"\"Bodies on screens are what 'normal' looks like.\"","myth":{"un":"My body should look like the ones online.","re":"Real bodies vary hugely; screen bodies are edited or extreme.","why":"Comparison to screens isn't fair or real."},"relearn":"Real bodies vary widely; don't measure yours against screens.","persona":"Aarav","source":"body image / media"},
  // — Body care, hygiene & moods —
  {"id":"pq-025","cat":"body-care-mood","type":"branch","hook":"You're sweating more and notice body odour now.","options":[{"text":"Wash daily and it's sorted","consequence":"You feel fresh; it's just puberty.","outcome":"healthy","best":true},{"text":"Worry there's something wrong with you","consequence":"More sweat and odour is normal in puberty; washing handles it."}],"debrief":"More sweat and body odour is a normal puberty change; daily washing helps.","relearn":"Body odour in puberty is normal; daily washing handles it.","persona":"any","source":"puberty hygiene"},
  {"id":"pq-026","cat":"body-care-mood","type":"strike-rewrite","hook":"\"Acne means I'm dirty.\"","myth":{"un":"Getting pimples means I'm dirty.","re":"Acne is caused by puberty hormones, not by being unclean.","why":"It happens to most teens, even with good hygiene."},"relearn":"Acne is from hormones, not dirtiness; it's normal in puberty.","persona":"any","source":"puberty skin"},
  {"id":"pq-027","cat":"body-care-mood","type":"build","hook":"Build a simple puberty self-care routine.","prompt":"Add the basics.","pieces":["wash daily","clean clothes","brush teeth","sleep well","move/play"],"mode":"assemble","key":["wash daily","clean clothes","brush teeth","sleep well","move/play"],"relearn":"Daily washing, clean clothes, sleep and movement handle most puberty care.","persona":"any","source":"self-care"},
  {"id":"pq-028","cat":"body-care-mood","type":"branch","hook":"Your moods swing a lot lately and it confuses you.","options":[{"text":"Remind yourself it's hormones, and use your calm-down tools","consequence":"You ride the mood out without it running you.","outcome":"regulated","best":true},{"text":"Assume you're 'going crazy'","consequence":"Mood swings are normal in puberty; tools (links Heart Smart) help."}],"debrief":"Hormones cause mood swings; your Heart Smart tools still work.","relearn":"Puberty mood swings are normal; calm-down tools help.","persona":"any","source":"emotional regulation (links g41)"},
  {"id":"pq-029","cat":"body-care-mood","type":"reflect","hook":"Lensy: your changing body is doing exactly what it should. Can you be patient with it?","prompt":"What do you think?","options":["Yes","I'll try","It's doing its job"],"affirm":"Being patient and kind to your changing body helps a lot.","relearn":"Be patient and kind with your body as it changes.","persona":"any","source":"body positivity"},
  {"id":"pq-030","cat":"body-care-mood","type":"sort","hook":"Sort: helps with puberty changes, or an unhelpful myth?","items":[{"id":"a","text":"Washing daily for body odour"},{"id":"b","text":"Scrubbing skin raw to 'cure' acne"},{"id":"c","text":"Resting when you're tired from growing"},{"id":"d","text":"Starving yourself to change your shape"}],"bins":[{"id":"helps","label":"Helps"},{"id":"myth","label":"Unhelpful / harmful"}],"key":{"a":"helps","b":"myth","c":"helps","d":"myth"},"relearn":"Gentle daily care helps; harsh 'fixes' and starving don't.","persona":"any","source":"self-care"},
  {"id":"pq-031","cat":"body-care-mood","type":"strike-rewrite","hook":"\"I should compare my body to my friends'.\"","myth":{"un":"I should measure my body against my friends'.","re":"Everyone develops at their own pace; comparison isn't useful.","why":"Different timelines are all normal."},"relearn":"Don't compare your body's pace to others'; yours is fine.","persona":"Diya","source":"body image / timeline"},
  {"id":"pq-032","cat":"body-care-mood","type":"reflect","hook":"Lensy: which change feels biggest for you right now?","prompt":"Pick one (private to you).","options":["Growth/looks","Moods","Body care","Periods/other"],"affirm":"Whatever it is, it's normal and you can handle it, one step at a time.","relearn":"Naming what's changing helps you handle it calmly.","persona":"any","source":"self-awareness"},
  // — Periods without shame (busting taboos) —
  {"id":"pq-033","cat":"periods-no-shame","type":"strike-rewrite","hook":"\"A girl on her period is 'impure' or 'dirty'.\"","myth":{"un":"A girl on her period is impure or dirty.","re":"A period is clean and natural; no one is 'impure' for menstruating.","why":"It's a normal, healthy body process."},"relearn":"Menstruation is clean and natural; no one is 'impure'.","persona":"Diya","source":"India menstrual taboos"},
  {"id":"pq-034","cat":"periods-no-shame","type":"strike-rewrite","hook":"\"Girls on their period can't touch food or enter the kitchen.\"","myth":{"un":"Girls on their period shouldn't touch food or cook.","re":"Menstruating people can cook and touch any food safely.","why":"There's nothing unhygienic about a period; it's a myth."},"relearn":"You can cook and touch food on your period; that taboo is a myth.","persona":"Rekha","source":"India menstrual taboos"},
  {"id":"pq-035","cat":"periods-no-shame","type":"branch","hook":"At home, you're told to stay apart and not enter certain rooms on your period.","options":[{"text":"Know the truth: you're not impure, even if customs differ","consequence":"You keep your dignity; you can talk to a trusted adult.","outcome":"dignified","best":true},{"text":"Believe you're dirty","consequence":"Customs vary, but the truth is you are never 'dirty'."}],"debrief":"Some families follow old customs; the truth is you're never impure.","relearn":"Whatever customs say, a period never makes you dirty or less.","persona":"Diya","source":"India taboos / dignity"},
  {"id":"pq-036","cat":"periods-no-shame","type":"strike-rewrite","hook":"\"Girls must miss school during their period.\"","myth":{"un":"Girls should stay home from school on their period.","re":"With a pad/cloth and care, you can go to school as normal.","why":"Missing school harms your future for no real reason."},"relearn":"You can go to school on your period; you don't have to miss out.","persona":"Lakshmi","source":"period & education"},
  {"id":"pq-037","cat":"periods-no-shame","type":"reflect","hook":"Lensy: about 23 million girls in India drop out of school after periods start, often from stigma and no products. Is that fair?","prompt":"What do you think?","options":["No","Not fair at all","We can change it"],"affirm":"It's not fair, and knowing the truth and getting products helps change it.","relearn":"No one should miss school for a period; that's an unfairness we can fix.","persona":"Lakshmi","source":"period poverty / dropout"},
  {"id":"pq-038","cat":"periods-no-shame","type":"branch","hook":"You need a pad but feel too guilty to ask family for money.","options":[{"text":"Ask a trusted adult, teacher or Asha worker for help","consequence":"You get what you need; many can help, free or cheap.","outcome":"supported","best":true},{"text":"Use unsafe rags and say nothing","consequence":"Asking for help is okay; safe products protect your health."}],"debrief":"Period products are a need, not a luxury; it's okay to ask for help.","relearn":"It's okay to ask a trusted adult or health worker for period products.","persona":"Lakshmi","source":"period poverty"},
  {"id":"pq-039","cat":"periods-no-shame","type":"strike-rewrite","hook":"\"Exercising or playing on your period is dangerous.\"","myth":{"un":"You can't exercise or play on your period.","re":"You can move, play and exercise on your period; it can even help cramps.","why":"A period doesn't make you fragile."},"relearn":"You can play and exercise on your period; it may even help.","persona":"Asha","source":"menstruation myths"},
  {"id":"pq-040","cat":"periods-no-shame","type":"sort","hook":"Sort: period truth, or period myth?","items":[{"id":"a","text":"A period is clean and normal"},{"id":"b","text":"Menstruating people are impure"},{"id":"c","text":"You can go to school and play"},{"id":"d","text":"You can't touch pickles or plants"}],"bins":[{"id":"true","label":"True"},{"id":"myth","label":"Myth"}],"key":{"a":"true","b":"myth","c":"true","d":"myth"},"relearn":"Periods are clean and normal; 'impure' and 'can't touch food' are myths.","persona":"Diya","source":"India menstrual taboos"},
  {"id":"pq-041","cat":"periods-no-shame","type":"role-play","hook":"A friend whispers that her period makes her 'dirty'.","setup":"Reassure her. Say:","yourLine":[{"text":"\"It's clean and normal, you're not dirty at all.\"","best":true},{"text":"\"Yeah, better hide it.\""}],"relearn":"You can reassure a friend that periods are normal and clean.","persona":"Diya","source":"peer support / stigma"},
  {"id":"pq-042","cat":"periods-no-shame","type":"branch","hook":"A boy in class teases a girl about periods.","options":[{"text":"Say \"periods are normal, that's not something to tease\"","consequence":"You shut down the stigma; everyone learns.","outcome":"ally","best":true},{"text":"Laugh along","consequence":"Teasing about periods spreads shame; you can stop it."}],"debrief":"Periods are normal biology; teasing about them isn't okay.","relearn":"Periods aren't a joke; boys can be allies, not teasers.","persona":"Aarav","source":"ally / stigma"},
  {"id":"pq-043","cat":"periods-no-shame","type":"strike-rewrite","hook":"\"Boys don't need to know anything about periods.\"","myth":{"un":"Boys don't need to know about periods.","re":"Everyone benefits from understanding periods; it builds respect.","why":"Knowledge ends teasing and stigma."},"relearn":"Boys should learn about periods too; it builds respect.","persona":"Aarav","source":"inclusive education"},
  {"id":"pq-044","cat":"periods-no-shame","type":"reflect","hook":"Lensy: periods are normal, and you deserve dignity and the right products. Agree?","prompt":"What do you think?","options":["Yes","Dignity matters","I deserve that"],"affirm":"You deserve accurate info, products, and dignity, always.","relearn":"Everyone who menstruates deserves info, products and dignity.","persona":"Lakshmi","source":"dignity / rights"},
  {"id":"pq-045","cat":"periods-no-shame","type":"build","hook":"Build a 'periods are normal' fact card to remember.","prompt":"Pick the true facts.","pieces":["a period is clean & normal","I can go to school","I'm never 'impure'","I can ask for products","I must hide it forever"],"mode":"assemble","key":["a period is clean & normal","I can go to school","I'm never 'impure'","I can ask for products"],"relearn":"Periods: clean, normal, school's fine, never impure, ask for what you need.","persona":"Diya","source":"consolidation / stigma"},
  // — Where to find out (trusted, accurate) —
  {"id":"pq-046","cat":"where-to-find-out","type":"branch","hook":"You have an embarrassing puberty question you can't ask your parents.","options":[{"text":"Ask a trusted adult, teacher or health worker, or a reliable source","consequence":"You get accurate, calm answers.","outcome":"informed","best":true},{"text":"Ask random people in a game chat","consequence":"Trusted sources are safer and more accurate than random chats."}],"debrief":"There's always a trusted way to get your questions answered.","relearn":"For shy questions, use a trusted adult or reliable source.","persona":"Aarav","source":"information literacy"},
  {"id":"pq-047","cat":"where-to-find-out","type":"strike-rewrite","hook":"\"Whatever I read online about my body is true.\"","myth":{"un":"Everything online about puberty and bodies is true.","re":"A lot online is wrong or extreme; check trusted sources.","why":"Anyone can post anything."},"relearn":"Online body info can be wrong; check trusted sources.","persona":"Aarav","source":"information literacy (links g12)"},
  {"id":"pq-048","cat":"where-to-find-out","type":"match","hook":"Match the source to how much to trust it for body questions.","pairs":[{"left":"A doctor or health worker","right":"Trust it"},{"left":"A random online comment","right":"Be careful"},{"left":"A trusted teacher / Asha didi","right":"Trust it"}],"relearn":"Doctors, teachers and health workers are trusted sources for body questions.","persona":"Asha","source":"information literacy"},
  {"id":"pq-049","cat":"where-to-find-out","type":"reflect","hook":"Lensy: it's okay not to know things about your own body yet. Asking is smart, right?","prompt":"What do you think?","options":["Yes","Asking is smart","No question is silly"],"affirm":"No puberty question is silly; asking is how you learn.","relearn":"It's smart to ask questions about your changing body.","persona":"Diya","source":"learning mindset"},
  {"id":"pq-050","cat":"where-to-find-out","type":"branch","hook":"A friend gives you 'facts' about puberty that sound wrong.","options":[{"text":"Double-check with a trusted source","consequence":"You learn what's actually true.","outcome":"informed","best":true},{"text":"Believe and repeat it","consequence":"Friends can be wrong too; check puberty 'facts'."}],"debrief":"Friends mean well but can be wrong; verify body facts.","relearn":"Check puberty 'facts' from friends against trusted sources.","persona":"any","source":"information literacy"},
  {"id":"pq-051","cat":"where-to-find-out","type":"role-play","hook":"You decide to ask a trusted adult a puberty question.","setup":"Open the conversation. Say:","yourLine":[{"text":"\"Can I ask you something about growing up?\"","best":true},{"text":"Never ask and stay unsure"}],"relearn":"A simple opener makes asking a trusted adult easier.","persona":"Aarav","source":"help-seeking / voice"},
  {"id":"pq-052","cat":"where-to-find-out","type":"reflect","hook":"Lensy: a near-peer like an older cousin or Asha didi can be easier to ask. Got one?","prompt":"Who could you ask?","options":["An older sibling/cousin","A teacher","A health worker","A trusted adult"],"affirm":"Having a go-to person for questions is really helpful.","relearn":"A trusted near-peer or adult is a great person to ask.","persona":"Asha","source":"trusted sources"},
  {"id":"pq-053","cat":"where-to-find-out","type":"strike-rewrite","hook":"\"Asking about puberty means I'm weird or behind.\"","myth":{"un":"Asking puberty questions means something's wrong with me.","re":"Everyone has these questions; asking is normal and smart.","why":"This is new for every single person."},"relearn":"Everyone has puberty questions; asking is completely normal.","persona":"any","source":"normalisation"},
  {"id":"pq-054","cat":"whats-puberty","type":"branch","hook":"You feel like you're changing 'too slowly' compared to classmates.","options":[{"text":"Remember everyone's clock is different; yours is fine","consequence":"You stop worrying about a normal difference.","outcome":"reassured","best":true},{"text":"Panic that you're abnormal","consequence":"Starting later is normal; bodies have their own timing."}],"debrief":"Developing later (or earlier) than friends is completely normal.","relearn":"Your puberty timing is your own; later or earlier is normal.","persona":"any","source":"timeline variation"},
  {"id":"pq-055","cat":"girls-changes","type":"branch","hook":"Your period is irregular at first and you're worried.","options":[{"text":"Know early periods are often irregular; ask a doctor if very worried","consequence":"You're reassured and know when to check.","outcome":"informed","best":true},{"text":"Assume something is seriously wrong","consequence":"Irregular early periods are common; a doctor can reassure you."}],"debrief":"Periods are often irregular at first; that's usually normal.","relearn":"Early periods are often irregular; that's usually normal.","persona":"Diya","source":"menstruation basics"},
  {"id":"pq-056","cat":"boys-changes","type":"reflect","hook":"Lensy: getting an erection sometimes, including at random, is a normal puberty thing. Good to know calmly?","prompt":"What do you think?","options":["Yes","Glad it's normal","Less confusing"],"affirm":"It's a normal, automatic body thing in puberty, nothing to worry about.","relearn":"Erections, including random ones, are a normal part of puberty.","persona":"Aarav","source":"puberty basics"},
  {"id":"pq-057","cat":"body-care-mood","type":"branch","hook":"You feel tired and hungry a lot during a growth spurt.","options":[{"text":"Eat well and rest; your body's building","consequence":"You support your growing body.","outcome":"healthy","best":true},{"text":"Ignore hunger and sleep","consequence":"Growing bodies need extra food and rest."}],"debrief":"Growth spurts make you hungry and tired; feed and rest your body.","relearn":"Eat well and rest during growth spurts; your body needs it.","persona":"any","source":"puberty nutrition"},
  {"id":"pq-058","cat":"periods-no-shame","type":"branch","hook":"A younger girl is scared because no one told her about periods.","options":[{"text":"Calmly tell her it's normal and how it works","consequence":"You spare her the fear you might have had.","outcome":"ally","best":true},{"text":"Tell her it's secret and scary","consequence":"Sharing calm, true info helps the next girl."}],"debrief":"Passing on calm, accurate info breaks the cycle of fear.","relearn":"You can help a younger girl by sharing accurate, calm info.","persona":"Asha","source":"peer education"},
  {"id":"pq-059","cat":"where-to-find-out","type":"sort","hook":"Sort: a reliable place for puberty info, or risky?","items":[{"id":"a","text":"A school health class"},{"id":"b","text":"A stranger in a game chat"},{"id":"c","text":"A doctor"},{"id":"d","text":"A clickbait video"}],"bins":[{"id":"reliable","label":"Reliable"},{"id":"risky","label":"Risky"}],"key":{"a":"reliable","b":"risky","c":"reliable","d":"risky"},"relearn":"Health classes and doctors are reliable; strangers and clickbait aren't.","persona":"any","source":"information literacy"},
  {"id":"pq-060","cat":"whats-puberty","type":"reflect","hook":"Lensy: puberty is a quest everyone goes on. Feeling more ready for yours?","prompt":"What do you think?","options":["Yes","More ready","Less scared"],"affirm":"You're more prepared already, just by understanding it.","relearn":"Understanding puberty makes you ready for your own.","persona":"any","source":"empowerment"},
  {"id":"pq-061","cat":"girls-changes","type":"strike-rewrite","hook":"\"Using a menstrual cup or tampon 'breaks' something.\"","myth":{"un":"Using a cup or tampon damages your body.","re":"Cups and tampons are safe options; you choose what's comfy.","why":"They're designed to be safe to use."},"relearn":"Pads, cloth, cups and tampons are all safe; you choose.","persona":"Asha","source":"menstrual products"},
  {"id":"pq-062","cat":"boys-changes","type":"branch","hook":"Friends brag and compare about puberty 'milestones'.","options":[{"text":"Opt out: \"everyone's different, it's not a race\"","consequence":"You skip a pointless, anxious comparison.","outcome":"grounded","best":true},{"text":"Feel bad you're 'behind'","consequence":"Puberty isn't a competition; timelines differ."}],"debrief":"Puberty isn't a race or a bragging contest.","relearn":"Don't turn puberty into a competition; everyone differs.","persona":"Aarav","source":"body image / timeline"},
  {"id":"pq-063","cat":"body-care-mood","type":"role-play","hook":"You feel low and not yourself during a hormonal week.","setup":"Be kind to yourself. Say:","yourLine":[{"text":"\"It's hormones, I'll be gentle with myself today.\"","best":true},{"text":"\"What's wrong with me?\""}],"relearn":"Kind self-talk helps on rough hormonal days.","persona":"any","source":"self-compassion (links g41)"},
  {"id":"pq-064","cat":"periods-no-shame","type":"reflect","hook":"Lensy: a period is a sign of a healthy, growing body, not a curse. Reframe it?","prompt":"What do you think?","options":["Yes","A healthy sign","Reframed"],"affirm":"A period is your body working well, that's something to respect, not fear.","relearn":"A period is a sign of a healthy body, not a curse.","persona":"Diya","source":"period positivity"},
  {"id":"pq-065","cat":"where-to-find-out","type":"branch","hook":"You see scary 'health' claims about puberty online.","options":[{"text":"Check with a doctor or trusted adult before believing","consequence":"You avoid scary myths and get the truth.","outcome":"informed","best":true},{"text":"Panic and believe it","consequence":"Scary online claims are often false; verify first."}],"debrief":"Scary online puberty claims are often myths; verify with a pro.","relearn":"Verify scary puberty claims with a doctor or trusted adult.","persona":"Aarav","source":"information literacy"},
  {"id":"pq-066","cat":"whats-puberty","type":"sort","hook":"Sort: a feeling that's normal in puberty, or a sign to get support?","items":[{"id":"a","text":"Occasional mood swings"},{"id":"b","text":"Feeling sad nearly every day for weeks"},{"id":"c","text":"Curiosity about changes"},{"id":"d","text":"Feeling hopeless a lot"}],"bins":[{"id":"normal","label":"Normal ups & downs"},{"id":"support","label":"Reach out for support"}],"key":{"a":"normal","b":"support","c":"normal","d":"support"},"relearn":"Ups and downs are normal; but lasting sadness means reach out (see Mind Matters).","persona":"any","source":"mental health (links g38)"},
  {"id":"pq-067","cat":"girls-changes","type":"reflect","hook":"Lensy: knowing what a period is BEFORE it comes makes it way less scary. Helpful?","prompt":"What do you think?","options":["Yes","Glad I know now","Much less scary"],"affirm":"Being prepared turns a scary surprise into a normal, manageable thing.","relearn":"Knowing about periods in advance makes them no big deal.","persona":"Diya","source":"preparedness"},
  {"id":"pq-068","cat":"boys-changes","type":"strike-rewrite","hook":"\"Puberty makes boys 'become men' who must be tough and silent.\"","myth":{"un":"Becoming a man means being tough and never showing feelings.","re":"Growing up is about being kind, honest and yourself, feelings included.","why":"Real strength includes caring and being open."},"relearn":"Growing up well means staying kind and open, not just 'tough'.","persona":"Aarav","source":"healthy masculinity (links manosphere prevention)"},
  {"id":"pq-069","cat":"body-care-mood","type":"match","hook":"Match the puberty change to a simple way to handle it.","pairs":[{"left":"Body odour","right":"Wash daily, clean clothes"},{"left":"Acne","right":"Gentle cleansing, don't pick"},{"left":"Tiredness","right":"Sleep and good food"}],"relearn":"Most puberty changes have simple, calm ways to handle them.","persona":"any","source":"self-care"},
  {"id":"pq-070","cat":"periods-no-shame","type":"strike-rewrite","hook":"\"Period blood is dirty blood the body is getting rid of.\"","myth":{"un":"Period blood is 'dirty blood'.","re":"Period blood is just the normal lining of the uterus; it isn't 'dirty'.","why":"It's a healthy, natural part of the cycle."},"relearn":"Period blood isn't 'dirty'; it's a normal part of the cycle.","persona":"Asha","source":"menstruation science"},
  {"id":"pq-071","cat":"where-to-find-out","type":"reflect","hook":"Lensy: this game answered things you were shy to ask. Will you keep asking trusted sources?","prompt":"What do you think?","options":["Yes","Always trusted ones","I will"],"affirm":"Keep taking your questions to trusted sources, that's the smart habit.","relearn":"Keep asking trusted sources about your body and growing up.","persona":"any","source":"habit"},
  {"id":"pq-072","cat":"whats-puberty","type":"branch","hook":"You feel alone, like you're the only one going through changes.","options":[{"text":"Remember every single person goes through puberty","consequence":"You feel less alone; everyone's in it.","outcome":"reassured","best":true},{"text":"Believe you're the only one","consequence":"Literally everyone goes through puberty; you're not alone."}],"debrief":"Every adult you know went through exactly this.","relearn":"You're never alone in puberty; everyone goes through it.","persona":"any","source":"normalisation"},
  {"id":"pq-073","cat":"girls-changes","type":"branch","hook":"You stained your clothes during your period at school.","options":[{"text":"Tie a jacket round your waist, ask a trusted person for help","consequence":"You handle it calmly; it happens to loads of people.","outcome":"prepared","best":true},{"text":"Feel humiliated and hide all day","consequence":"Stains happen to many; a calm fix and help is all you need."}],"debrief":"A period stain is common and fixable; no shame needed.","relearn":"Period leaks happen; handle them calmly and ask for help.","persona":"Diya","source":"menstrual preparedness"},
  {"id":"pq-074","cat":"boys-changes","type":"reflect","hook":"Lensy: your body is yours and changing at its own pace. Can you respect that?","prompt":"What do you think?","options":["Yes","My pace is fine","I'll respect it"],"affirm":"Respecting your body's own pace is a sign of real maturity.","relearn":"Respect your body's own pace through puberty.","persona":"Aarav","source":"body respect"},
  {"id":"pq-075","cat":"periods-no-shame","type":"role-play","hook":"An elder repeats a 'periods are impure' custom.","setup":"Hold your dignity, kindly. Say (to yourself or a trusted adult):","yourLine":[{"text":"\"I respect them, and I know a period doesn't make me impure.\"","best":true},{"text":"\"I guess I'm dirty then.\""}],"relearn":"You can respect elders and still know the truth about your body.","persona":"Rekha","source":"India taboos / dignity"},
  {"id":"pq-076","cat":"body-care-mood","type":"reflect","hook":"Lensy: puberty changes how you look, but you're still YOU inside. True?","prompt":"What do you think?","options":["Yes","Still me","My body changes, I'm me"],"affirm":"Your body grows up, but the real you carries right through.","relearn":"Your body changes in puberty, but you're still you.","persona":"any","source":"identity (links g07)"},
  {"id":"pq-077","cat":"where-to-find-out","type":"branch","hook":"Capstone: you have a puberty worry and three options to handle it.","options":[{"text":"Take it to a trusted adult or reliable source","consequence":"You get calm, accurate help.","outcome":"informed","best":true},{"text":"Bottle it up","consequence":"A trusted source beats worrying alone."},{"text":"Trust a random online claim","consequence":"Random claims can be wrong; trusted sources are safer."}],"debrief":"For any puberty worry: trusted adult or reliable source, not alone or random.","relearn":"Handle puberty worries with trusted, accurate help.","persona":"any","source":"consolidation"},
  {"id":"pq-078","cat":"periods-no-shame","type":"reflect","hook":"Lensy: imagine a world where no girl misses school or feels shame for her period. Worth building?","prompt":"What do you think?","options":["Yes","Definitely","Let's build it"],"affirm":"That world starts with the truth you now know, and sharing it.","relearn":"Ending period stigma starts with knowing and sharing the truth.","persona":"Lakshmi","source":"vision / rights"},
  {"id":"pq-079","cat":"whats-puberty","type":"strike-rewrite","hook":"\"Once puberty starts, it's scary and out of control.\"","myth":{"un":"Puberty is a scary, out-of-control time.","re":"Puberty is a gradual, normal change you can understand and handle.","why":"Knowing what's happening puts you in control."},"relearn":"Puberty is gradual and manageable when you understand it.","persona":"any","source":"empowerment"},
  {"id":"pq-080","cat":"boys-changes","type":"branch","hook":"Capstone: you have a private body question and a phone in your hand.","options":[{"text":"Use a trusted health source or ask a trusted adult","consequence":"You get accurate info, privately and safely.","outcome":"informed","best":true},{"text":"Search something risky or ask a stranger","consequence":"Trusted sources keep you accurate and safe."}],"debrief":"A phone can reach great info or bad info, choose trusted sources.","relearn":"Use your phone for trusted body info, not risky searches.","persona":"Aarav","source":"information literacy / consolidation"},
  {"id":"pq-081","cat":"girls-changes","type":"build","hook":"Capstone: build your 'period confidence' kit (knowledge + supplies).","prompt":"Pick what makes you confident.","pieces":["I know what a period is","products ready","a trusted person to ask","I know I'm never 'impure'"],"mode":"assemble","key":["I know what a period is","products ready","a trusted person to ask","I know I'm never 'impure'"],"relearn":"Period confidence = knowledge, supplies, support, and zero shame.","persona":"Diya","source":"consolidation"},
  {"id":"pq-082","cat":"whats-puberty","type":"reflect","hook":"Lensy: what's your biggest take-away from Puberty Quest?","prompt":"Pick your motto.","options":["It's all normal","My pace is fine","No shame, ask away","I've got this"],"affirm":"Carry that. You're ready for your own puberty quest.","relearn":"Puberty is normal, everyone's pace differs, there's no shame, and help is there.","persona":"any","source":"consolidation"},
  {"id":"pq-083","cat":"periods-no-shame","type":"strike-rewrite","hook":"\"Talking about periods in front of boys is shameful.\"","myth":{"un":"Periods must never be mentioned around boys.","re":"Periods are normal biology everyone can learn about together.","why":"Open, respectful info ends the stigma."},"relearn":"Periods can be discussed openly and respectfully by everyone.","persona":"Asha","source":"stigma reduction"},
  {"id":"pq-084","cat":"body-care-mood","type":"reflect","hook":"Lensy: be patient and kind to your changing body and mind. Promise yourself that?","prompt":"What do you think?","options":["Yes","I promise","I'll be kind to me"],"affirm":"That kindness to yourself will carry you through every change.","relearn":"Being patient and kind to yourself is the heart of growing up well.","persona":"any","source":"self-compassion"},
];

export const PUBERTY_QUEST: V2GameConfig = {
  gameId: "puberty-quest",
  title: "Puberty Quest",
  greet: "Hey, it's Lensy. 🌱 Real talk about your body growing up — what's normal, periods without the weirdness, and where to get true answers. All private, no judging.",
  scenarios: SCENARIOS,
  categories: [
    { id: "whats-puberty", emoji: "🌱", label: "What is puberty?" },
    { id: "girls-changes", emoji: "🩸", label: "Girls' changes" },
    { id: "boys-changes", emoji: "🧔", label: "Boys' changes" },
    { id: "body-care-mood", emoji: "🧼", label: "Body care & moods" },
    { id: "periods-no-shame", emoji: "🙌", label: "Periods, no shame" },
    { id: "where-to-find-out", emoji: "🔎", label: "Where to find out" },
  ],
  badge: {
    title: "Puberty Quest complete! 🌱",
    blurb: "You know what's changing and why, that everyone's on their own clock, periods are clean and normal (never 'impure'), and boys' changes are normal too. 🌱",
  },
  helpLine: "Too shy to ask? A trusted adult, doctor, nurse or Asha worker can help, and for any worry call Childline, one-zero-nine-eight. No body question is silly.",
  helpLabel: "Get help · Childline 1098",
  reassure: "Everything about your changing body is normal and clean — no one is ever 'impure', and you deserve facts, products and dignity. 💛",
  reassureCats: ["periods-no-shame"],
  buildLabels: { assemble: "Sorted — you're prepared! ✅" },
};
