// Content for Raising Neurodiverse Kids (node g67, Parent Layer, Chapter 8) — NEW v2 build to GDD 67
// (mechanic-embodying), a Parent-Layer pillar and a warm callback to Same Same, Different (g04): difference is
// wonderful, grown up for parents. It reframes neurodivergence as DIFFERENCE, not deficiency — strengths-first and
// never deficit-shaming. 84 researched, India-grounded scenarios across understand-your-child → accommodate →
// advocate → drop-the-shame → strengths-and-wellbeing → support-and-you, each encoded as one of the shared v2 play
// actions (strike-rewrite / branch / sort / reflect / match / role-play / spot) — no binary "tap the right card".
// Lead: strike-rewrite (bust the myth), branch (your move), sort. Six modes: understand your child (the common
// neurodivergences, strengths-first, your child's own profile & pace; different, not less; brains naturally vary),
// accommodate (adjust the environment & expectations to the child rather than forcing them to mask; sensory,
// attention, transitions, routines; accommodations give fair access like glasses, they don't spoil), advocate (you
// are your child's key advocate; school accommodations, family understanding, services — with rights under the
// Rights of Persons with Disabilities Act 2016, which recognises autism & learning disabilities and mandates
// reasonable accommodation; seek assessment without shame), drop the shame and blame (it's no one's fault — NOT
// caused by parenting, screens or vaccines; meltdowns are overwhelm not naughtiness; you don't grow out of it;
// stop hiding it), strengths and wellbeing (build on strengths & passions, meet meltdowns with calm co-regulation
// not punishment, take co-occurring anxiety seriously, see the whole wonderful child not a label), support and you
// (parent wellbeing matters and it is demanding — lean on peer parents & professionals; routes parent burnout to
// Looking After You g63). Strengths-based and NEVER deficit-shaming, never blaming parent or child, accurate &
// expert-reviewed; NOT a diagnostic tool — points to professionals. Builds on Same Same, Different (g04); a
// Parent-Layer pillar alongside Break the Cycle (g65) and Raising Gender-Diverse Kids (g66). India: neurodiversity
// is heavily stigmatised & under-recognised, with delayed diagnoses often blamed on parenting and school
// accommodations a fight — the node de-stigmatises, helps parents seek assessment & support without shame, and
// points to rights under the RPwD Act 2016. gameId "raising-neurodiverse-kids".
import type { V2GameConfig, Scenario } from "./v2-schema";

const SCENARIOS: Scenario[] = [
  {"id":"nd-001","cat":"understand-your-child","type":"strike-rewrite","hook":"\"A neurodiverse child is broken or less than other children.\"","myth":{"un":"A neurodiverse child is broken or less than other children.","re":"Neurodivergence is a different way a brain is wired, not a fault or a lesser version; different, not less.","why":"Different wiring isn't damaged wiring."},"relearn":"A neurodiverse child isn't broken or less; their brain is wired differently, different, not less.","persona":"Meena","source":"different not less"},
  {"id":"nd-002","cat":"understand-your-child","type":"strike-rewrite","hook":"\"Autism, ADHD and dyslexia are just labels for naughty or lazy kids.\"","myth":{"un":"Autism, ADHD and dyslexia are just labels for naughty or lazy kids.","re":"They're real, recognised ways of being and learning, not naughtiness or laziness; understanding them changes everything.","why":"A profile isn't a character flaw."},"relearn":"Autism, ADHD and dyslexia are real ways of being and learning, not naughtiness or laziness.","persona":"Meena","source":"real not naughty"},
  {"id":"nd-003","cat":"understand-your-child","type":"reflect","hook":"Sam: understanding how your child is actually wired is the first, biggest act of love. Sit right?","prompt":"What do you think?","options":["Sits right","Understand first","Act of love"],"affirm":"Truly understanding how your child is wired, rather than judging them by a typical template, is a foundational act of love.","relearn":"Understanding how your child is actually wired is the first, biggest act of love.","persona":"Meena","source":"understand first"},
  {"id":"nd-004","cat":"understand-your-child","type":"sort","hook":"Sort: a strength a neurodiverse child may bring, or a 'deficit' the old view focuses on?","items":[{"id":"a","text":"Deep focus on a passion"},{"id":"b","text":"Only 'won't sit still'"},{"id":"c","text":"Pattern-spotting and memory"},{"id":"d","text":"Only 'can't pay attention'"}],"bins":[{"id":"strength","label":"A real strength"},{"id":"deficit","label":"The deficit-only view"}],"key":{"a":"strength","b":"deficit","c":"strength","d":"deficit"},"relearn":"Deep focus and pattern-spotting are real strengths; the 'won't sit still, can't focus' view sees only deficits.","persona":"any","source":"strength vs deficit"},
  {"id":"nd-005","cat":"understand-your-child","type":"match","hook":"Match each neurodivergence to a common strength (every child is individual).","pairs":[{"left":"Autism","right":"Deep focus, honesty, pattern recognition"},{"left":"ADHD","right":"Energy, creativity, quick thinking"},{"left":"Dyslexia","right":"Big-picture and spatial thinking"}],"relearn":"Autism, ADHD and dyslexia each commonly come with real strengths, though every child's profile is their own.","persona":"any","source":"strengths by profile"},
  {"id":"nd-006","cat":"understand-your-child","type":"branch","hook":"You keep comparing your child to 'typical' milestones and feeling worried.","options":[{"text":"Understand and support your child's own profile and pace","consequence":"You meet your actual child, not a template.","outcome":"their-pace","best":true},{"text":"Keep measuring them against a standard mould","consequence":"Understanding your child's own profile meets them where they are; measuring against a standard mould misses who they are."}],"debrief":"Support your child's own profile and pace rather than measuring them against a typical template.","relearn":"Meet your actual child's profile and pace, not a one-size template that misses them.","persona":"Divya","source":"their own pace"},
  {"id":"nd-007","cat":"understand-your-child","type":"strike-rewrite","hook":"\"There's one normal way for a child's brain to work, and my child should fit it.\"","myth":{"un":"There's one normal way for a child's brain to work, and my child should fit it.","re":"Brains naturally vary; neurodiversity is part of human variation, and your child's way of thinking is valid.","why":"Variation is the norm, not the exception."},"relearn":"There's no single 'normal' brain; neurodiversity is natural human variation, and your child's mind is valid.","persona":"Meena","source":"variation is natural"},
  {"id":"nd-008","cat":"understand-your-child","type":"reflect","hook":"Sam: when you see your child's strengths, not just their struggles, you change how they see themselves. Resonate?","prompt":"What's your take?","options":["Resonates","See strengths","Changes them"],"affirm":"Seeing a neurodiverse child's strengths, not only their struggles, shapes how they come to see themselves.","relearn":"When you see your child's strengths, not just struggles, you change how they see themselves.","persona":"Meena","source":"see strengths"},
  {"id":"nd-009","cat":"understand-your-child","type":"spot","hook":"Spot the understanding that serves a neurodiverse child.","scene":[{"id":"a","text":"'My child's brain works differently, and that's okay'","trick":false},{"id":"b","text":"'My child is just being difficult on purpose'","trick":true},{"id":"c","text":"'Let me learn how they experience the world'","trick":false}],"why":"'Works differently and that's okay' and 'let me learn how they experience it' serve the child; 'difficult on purpose' doesn't.","relearn":"Serve a neurodiverse child by understanding their different experience, not labelling them 'difficult on purpose'.","persona":"Meena","source":"serving understanding"},
  {"id":"nd-010","cat":"understand-your-child","type":"branch","hook":"Your child has just been identified as neurodivergent and you feel overwhelmed.","options":[{"text":"Take it as information that helps you understand and support them","consequence":"The label becomes a key, not a sentence.","outcome":"a-key","best":true},{"text":"Treat it as a tragedy or a verdict","consequence":"Treating it as helpful information unlocks support; treating it as a tragedy projects fear onto a child who is the same child."}],"debrief":"Treat a neurodivergence as information that helps you support your child, not a tragedy or a verdict.","relearn":"A diagnosis is a key to understanding and support, not a tragedy; your child is the same wonderful child.","persona":"Meena","source":"a key not a sentence"},
  {"id":"nd-011","cat":"accommodate","type":"strike-rewrite","hook":"\"My child must be forced to fit the standard environment and behave 'normally'.\"","myth":{"un":"My child must be forced to fit the standard environment and behave 'normally'.","re":"It works far better to adjust the environment and expectations to the child than to force the child to mask who they are.","why":"Flex the setting, not the child."},"relearn":"Adjust the environment and expectations to your child rather than forcing them to mask and fit a standard mould.","persona":"Meena","source":"flex the setting"},
  {"id":"nd-012","cat":"accommodate","type":"sort","hook":"Sort: a supportive accommodation, or forcing the child to mask?","items":[{"id":"a","text":"Noise-cancelling headphones for sensory overload"},{"id":"b","text":"Punishing stimming"},{"id":"c","text":"A visual schedule and routine"},{"id":"d","text":"Demanding constant eye contact"}],"bins":[{"id":"support","label":"Supportive accommodation"},{"id":"mask","label":"Forcing masking"}],"key":{"a":"support","b":"mask","c":"support","d":"mask"},"relearn":"Headphones and visual schedules support; punishing stimming or demanding eye contact force a child to mask painfully.","persona":"Meena","source":"support vs mask"},
  {"id":"nd-013","cat":"accommodate","type":"match","hook":"Match each need to a practical home accommodation.","pairs":[{"left":"Sensory overload","right":"A calm, low-stimulation space"},{"left":"Trouble with transitions","right":"Warnings and a visual routine"},{"left":"Attention differences","right":"Short steps, movement breaks"}],"relearn":"Sensory overload, transitions and attention each have a simple, practical accommodation that helps a child thrive.","persona":"any","source":"need to accommodation"},
  {"id":"nd-014","cat":"accommodate","type":"strike-rewrite","hook":"\"Accommodations spoil a child or are unfair to others.\"","myth":{"un":"Accommodations spoil a child or are unfair to others.","re":"Accommodations give a child fair access to the same chances, like glasses for sight; they level the ground, not tilt it.","why":"Fair isn't always identical."},"relearn":"Accommodations don't spoil a child; like glasses, they give fair access to the same chances.","persona":"Vikram","source":"fair access"},
  {"id":"nd-015","cat":"accommodate","type":"branch","hook":"Your child melts down in loud, crowded places every time.","options":[{"text":"Adjust plans and bring sensory supports to prevent overload","consequence":"You set your child up to cope, not fail.","outcome":"prevent","best":true},{"text":"Keep forcing the situation and punishing the meltdown","consequence":"Adjusting and bringing supports prevents overload; forcing the situation and punishing the meltdown harms a child who is overwhelmed, not misbehaving."}],"debrief":"Prevent sensory overload by adjusting plans and bringing supports, rather than forcing the situation and punishing the result.","relearn":"Adjust for sensory overload instead of forcing it; a meltdown is overwhelm, not misbehaviour to punish.","persona":"Meena","source":"prevent overload"},
  {"id":"nd-016","cat":"accommodate","type":"reflect","hook":"Sam: a child who is accommodated can show you their best; one who is forced to mask is just surviving. Sit right?","prompt":"What do you think?","options":["Sits right","Their best","Not just surviving"],"affirm":"When a child's environment is accommodated they can flourish and show their strengths, rather than exhausting themselves masking.","relearn":"An accommodated child can show you their best; a child forced to mask is just surviving.","persona":"Meena","source":"show their best"},
  {"id":"nd-017","cat":"accommodate","type":"spot","hook":"Spot the accommodation that helps a child thrive.","scene":[{"id":"a","text":"Adjusting the environment to their needs","trick":false},{"id":"b","text":"Forcing them to suppress who they are","trick":true},{"id":"c","text":"Building on their strengths and interests","trick":false}],"why":"Adjusting the environment and building on strengths help a child thrive; forcing suppression just drains them.","relearn":"Help a neurodiverse child thrive by adjusting the environment and building on strengths, not forcing suppression.","persona":"Meena","source":"thrive accommodation"},
  {"id":"nd-018","cat":"accommodate","type":"match","hook":"Match each setting to an accommodation that helps.","pairs":[{"left":"Mealtimes","right":"Respect food sensitivities, no force"},{"left":"Bedtime","right":"A predictable, calming routine"},{"left":"Homework","right":"Chunked tasks and breaks"}],"relearn":"Mealtimes, bedtime and homework each go better with accommodations that fit the child's wiring.","persona":"any","source":"setting to support"},
  {"id":"nd-019","cat":"accommodate","type":"strike-rewrite","hook":"\"If I accommodate my child, they'll never learn to cope with the real world.\"","myth":{"un":"If I accommodate my child, they'll never learn to cope with the real world.","re":"Accommodation builds the security and skills from which real coping grows; forcing distress teaches fear, not coping.","why":"Support is the launchpad, not the crutch."},"relearn":"Accommodation builds the security from which coping grows; forced distress teaches fear, not real-world skills.","persona":"Vikram","source":"support builds coping"},
  {"id":"nd-020","cat":"accommodate","type":"branch","hook":"You're unsure which accommodations your child actually needs.","options":[{"text":"Watch, ask your child, and try supports to see what helps","consequence":"You find what works for your real child.","outcome":"tailored","best":true},{"text":"Apply a generic checklist and ignore their cues","consequence":"Watching, asking and trying tailors support to your child; a generic checklist that ignores their cues often misses the mark."}],"debrief":"Find the right accommodations by watching, asking your child and trying supports, not a one-size checklist.","relearn":"Tailor accommodations by observing and asking your child, rather than applying a generic checklist.","persona":"Divya","source":"find what works"},
  {"id":"nd-021","cat":"advocate","type":"strike-rewrite","hook":"\"It's not my place to push for support; I should just accept whatever school gives.\"","myth":{"un":"It's not my place to push for support; I should just accept whatever school gives.","re":"You are your child's most important advocate; pushing kindly but firmly for the support they need is part of the job.","why":"No one will champion your child like you."},"relearn":"You are your child's key advocate; pushing kindly but firmly for the support they need is part of parenting.","persona":"Meena","source":"you are the advocate"},
  {"id":"nd-022","cat":"advocate","type":"strike-rewrite","hook":"\"My neurodiverse child has no real rights to support in India.\"","myth":{"un":"My neurodiverse child has no real rights to support in India.","re":"The Rights of Persons with Disabilities Act 2016 recognises autism and learning disabilities and mandates reasonable accommodation, including in schools.","why":"The law is on your child's side."},"relearn":"Your child has rights: the RPwD Act 2016 recognises autism and learning disabilities and mandates reasonable accommodation.","persona":"Meena","source":"RPwD rights"},
  {"id":"nd-023","cat":"advocate","type":"sort","hook":"Sort: effective advocacy for your child, or giving up their support?","items":[{"id":"a","text":"Requesting accommodations in writing"},{"id":"b","text":"Accepting 'he's just naughty' from school"},{"id":"c","text":"Bringing evidence and staying calm"},{"id":"d","text":"Hiding the diagnosis from teachers"}],"bins":[{"id":"advocate","label":"Effective advocacy"},{"id":"giveup","label":"Gives up support"}],"key":{"a":"advocate","b":"giveup","c":"advocate","d":"giveup"},"relearn":"Written requests and calm evidence are effective advocacy; accepting 'just naughty' or hiding the diagnosis give up support.","persona":"any","source":"advocate vs giveup"},
  {"id":"nd-024","cat":"advocate","type":"branch","hook":"The school dismisses your child's needs as 'bad behaviour'.","options":[{"text":"Calmly explain the profile and request specific accommodations","consequence":"You shift them from blame to support.","outcome":"support","best":true},{"text":"Accept the blame and ask nothing","consequence":"Explaining the profile and requesting accommodations shifts the school to support; accepting blame leaves your child unhelped."}],"debrief":"When school calls needs 'bad behaviour', calmly explain the profile and request specific accommodations.","relearn":"Reframe 'bad behaviour' at school by explaining your child's profile and requesting accommodations, not accepting blame.","persona":"Meena","source":"explain and request"},
  {"id":"nd-025","cat":"advocate","type":"match","hook":"Match each arena to an advocacy move.","pairs":[{"left":"School","right":"Request accommodations under the RPwD Act"},{"left":"Family","right":"Share understanding, set respectful limits"},{"left":"Services","right":"Seek assessment and ongoing support"}],"relearn":"At school, with family and with services, advocacy means requesting accommodations, sharing understanding, and seeking support.","persona":"Meena","source":"arena to move"},
  {"id":"nd-026","cat":"advocate","type":"role-play","hook":"A relative insists your child just needs 'strict discipline'. You want to advocate calmly.","setup":"Advocate calmly:","yourLine":[{"text":"\"His brain works differently, and what helps him is support and understanding, not harsher punishment.\"","best":true},{"text":"\"You're right, maybe I'm too soft on him.\""}],"relearn":"Calmly explaining that support, not harsher punishment, is what helps protects your child from misguided 'discipline'.","persona":"Meena","source":"calm advocacy"},
  {"id":"nd-027","cat":"advocate","type":"reflect","hook":"Sam: every time you advocate, you teach your child that they're worth fighting for. Worth it?","prompt":"What do you think?","options":["Worth it","Worth fighting for","Yes"],"affirm":"Each act of advocacy teaches a neurodiverse child that they matter and are worth standing up for.","relearn":"Every time you advocate, you teach your child that they're worth fighting for.","persona":"Meena","source":"worth fighting for"},
  {"id":"nd-028","cat":"advocate","type":"spot","hook":"Spot the advocacy that gets a child real support.","scene":[{"id":"a","text":"Knowing their rights and asking clearly","trick":false},{"id":"b","text":"Staying silent to avoid being 'that parent'","trick":true},{"id":"c","text":"Partnering with teachers on a plan","trick":false}],"why":"Knowing rights, asking clearly and partnering with teachers get support; staying silent to avoid fuss leaves the child without it.","relearn":"Real support comes from knowing rights, asking clearly and partnering with school, not staying silent.","persona":"any","source":"effective advocacy"},
  {"id":"nd-029","cat":"advocate","type":"branch","hook":"You suspect your child is neurodivergent but worry that seeking assessment is 'making a problem'.","options":[{"text":"Seek a professional assessment; understanding helps your child","consequence":"You open the door to the right support.","outcome":"assess","best":true},{"text":"Avoid it so as not to 'label' them","consequence":"Seeking assessment opens the door to support and understanding; avoiding it to dodge a 'label' delays the help your child needs."}],"debrief":"Seek a professional assessment if you suspect neurodivergence; understanding opens the door to support, it isn't 'making a problem'.","relearn":"Pursue assessment rather than avoiding a 'label'; understanding unlocks the support your child needs.","persona":"Divya","source":"seek assessment"},
  {"id":"nd-030","cat":"advocate","type":"strike-rewrite","hook":"\"Asking for help with my child marks me as a failing parent.\"","myth":{"un":"Asking for help with my child marks me as a failing parent.","re":"Seeking support and accommodations is exactly what good, informed parents of neurodiverse kids do; it's strength, not failure.","why":"Getting help is wise parenting."},"relearn":"Asking for help and accommodations is what good parents of neurodiverse kids do; it's strength, not failure.","persona":"Vikram","source":"help is strength"},
  {"id":"nd-031","cat":"drop-the-shame","type":"strike-rewrite","hook":"\"My child's neurodivergence is caused by my bad parenting.\"","myth":{"un":"My child's neurodivergence is caused by my bad parenting.","re":"Neurodivergence isn't caused by parenting, screens, vaccines or anything you did; it's simply how your child is wired.","why":"It's no one's fault, least of all yours."},"relearn":"Neurodivergence isn't caused by your parenting or by screens or vaccines; it's simply how your child is wired.","persona":"Meena","source":"not your fault"},
  {"id":"nd-032","cat":"drop-the-shame","type":"strike-rewrite","hook":"\"A child who melts down or can't sit still is just badly behaved.\"","myth":{"un":"A child who melts down or can't sit still is just badly behaved.","re":"Meltdowns and restlessness are often the brain overwhelmed or wired differently, not naughtiness to be punished.","why":"Behaviour is communication, not defiance."},"relearn":"Meltdowns and restlessness are usually overwhelm or different wiring, not bad behaviour to punish.","persona":"Meena","source":"not bad behaviour"},
  {"id":"nd-033","cat":"drop-the-shame","type":"strike-rewrite","hook":"\"They'll just grow out of it if we ignore it.\"","myth":{"un":"They'll just grow out of it if we ignore it.","re":"Neurodivergence is lifelong; understanding and support help a child thrive, while ignoring it leaves them struggling alone.","why":"Support helps; waiting it out doesn't."},"relearn":"A child doesn't 'grow out of' neurodivergence; understanding and support help them thrive, ignoring it doesn't.","persona":"Vikram","source":"not grow out of it"},
  {"id":"nd-034","cat":"drop-the-shame","type":"sort","hook":"Sort: a fact that lifts shame, or a myth that piles it on?","items":[{"id":"a","text":"It's no one's fault"},{"id":"b","text":"'You spoiled or caused this'"},{"id":"c","text":"Your child can thrive with support"},{"id":"d","text":"'A good family hides it'"}],"bins":[{"id":"lifts","label":"Lifts shame"},{"id":"piles","label":"Piles on shame"}],"key":{"a":"lifts","b":"piles","c":"lifts","d":"piles"},"relearn":"'No one's fault' and 'can thrive with support' lift shame; 'you caused it' and 'hide it' pile shame on unfairly.","persona":"any","source":"lifts vs piles"},
  {"id":"nd-035","cat":"drop-the-shame","type":"reflect","hook":"Sam: you didn't cause this, you can't 'cure' it, and you absolutely can help your child flourish. Land okay?","prompt":"What do you think?","options":["Lands okay","Not my fault","I can help"],"affirm":"You didn't cause your child's neurodivergence and can't cure it, but you can absolutely help them flourish.","relearn":"You didn't cause it, you can't cure it, and you can help your child flourish.","persona":"Meena","source":"didnt cause it"},
  {"id":"nd-036","cat":"drop-the-shame","type":"branch","hook":"Relatives blame you, or your child, for the neurodivergence.","options":[{"text":"Calmly correct the blame and protect your child from it","consequence":"You shield your child from undeserved shame.","outcome":"shield","best":true},{"text":"Absorb the blame and pass it to your child","consequence":"Calmly correcting the blame shields your child; absorbing it and passing it on hands your child shame they don't deserve."}],"debrief":"Correct relatives' blame calmly and protect your child from it; it's no one's fault.","relearn":"Shield your child from blame by correcting it calmly; don't pass undeserved shame on to them.","persona":"Meena","source":"shield from blame"},
  {"id":"nd-037","cat":"drop-the-shame","type":"spot","hook":"Spot what helps a family drop the shame.","scene":[{"id":"a","text":"Knowing it's no one's fault","trick":false},{"id":"b","text":"Hiding the child from relatives","trick":true},{"id":"c","text":"Talking about it openly and kindly","trick":false}],"why":"Knowing it's no one's fault and talking openly drop the shame; hiding the child keeps the shame alive.","relearn":"Families drop the shame by knowing it's no one's fault and talking openly, not by hiding the child.","persona":"any","source":"drop the shame"},
  {"id":"nd-038","cat":"drop-the-shame","type":"reflect","hook":"Sam: shame helps no one; your energy is better spent understanding and championing your child. Agree?","prompt":"What's your take?","options":["Agree","Champion not shame","Energy well spent"],"affirm":"Shame and blame help no one; that energy is far better spent understanding and championing your child.","relearn":"Shame helps no one; spend that energy understanding and championing your child instead.","persona":"Meena","source":"champion not shame"},
  {"id":"nd-039","cat":"drop-the-shame","type":"strike-rewrite","hook":"\"I should hide my child's diagnosis so people don't judge us.\"","myth":{"un":"I should hide my child's diagnosis so people don't judge us.","re":"Hiding it reinforces stigma and isolates you both; openness, on your own terms, lets support and understanding in.","why":"Secrecy feeds the shame it fears."},"relearn":"Hiding a diagnosis reinforces stigma and isolation; sharing on your own terms lets in support and understanding.","persona":"Vikram","source":"openness over hiding"},
  {"id":"nd-040","cat":"drop-the-shame","type":"branch","hook":"You feel grief and guilt about your child's diagnosis.","options":[{"text":"Allow the feelings, drop the guilt, and refocus on your child as they are","consequence":"You move from grief to engaged support.","outcome":"refocus","best":true},{"text":"Stay stuck in guilt and what-ifs","consequence":"Allowing feelings and dropping guilt frees you to support your child; staying stuck in guilt helps no one and drains you."}],"debrief":"Allow grief but drop the guilt, and refocus on supporting the wonderful child in front of you.","relearn":"Feel what you feel, drop the guilt, and refocus on your child as they are; guilt and what-ifs help no one.","persona":"Meena","source":"drop the guilt"},
  {"id":"nd-041","cat":"strengths-and-wellbeing","type":"strike-rewrite","hook":"\"I should focus only on fixing my neurodiverse child's weaknesses.\"","myth":{"un":"I should focus only on fixing my neurodiverse child's weaknesses.","re":"Building on a child's strengths and passions does more for their confidence and growth than fixating on deficits.","why":"Strengths are the foundation to build on."},"relearn":"Build on your child's strengths and passions, not only their weaknesses; that grows confidence and skills.","persona":"Meena","source":"build on strengths"},
  {"id":"nd-042","cat":"strengths-and-wellbeing","type":"sort","hook":"Sort: nurtures a neurodiverse child's wellbeing, or chips at their self-worth?","items":[{"id":"a","text":"Celebrating their passions"},{"id":"b","text":"Constantly comparing them to others"},{"id":"c","text":"Praising effort and strengths"},{"id":"d","text":"Making them feel like a problem"}],"bins":[{"id":"nurture","label":"Nurtures wellbeing"},{"id":"chip","label":"Chips at self-worth"}],"key":{"a":"nurture","b":"chip","c":"nurture","d":"chip"},"relearn":"Celebrating passions and praising strengths nurture wellbeing; constant comparison and 'a problem' framing chip at self-worth.","persona":"Meena","source":"nurture vs chip"},
  {"id":"nd-043","cat":"strengths-and-wellbeing","type":"strike-rewrite","hook":"\"A meltdown is my child trying to manipulate or defy me.\"","myth":{"un":"A meltdown is my child trying to manipulate or defy me.","re":"A meltdown is usually distress and overwhelm spilling over, not manipulation; your child needs co-regulation, not punishment.","why":"Overwhelm needs comfort, not consequences."},"relearn":"A meltdown is overwhelm spilling over, not manipulation; your child needs calm co-regulation, not punishment.","persona":"Meena","source":"meltdown is distress"},
  {"id":"nd-044","cat":"strengths-and-wellbeing","type":"branch","hook":"Your child is melting down and you feel your own frustration rising.","options":[{"text":"Stay calm, keep them safe, and co-regulate until the wave passes","consequence":"You help your child through the storm.","outcome":"co-regulate","best":true},{"text":"Match their dysregulation with anger","consequence":"Staying calm and co-regulating helps the wave pass; matching it with anger escalates and frightens an overwhelmed child."}],"debrief":"Meet a meltdown with calm co-regulation and safety, not anger; it's a storm to ride out together.","relearn":"Co-regulate a meltdown with calm and safety; meeting overwhelm with anger only escalates it.","persona":"Meena","source":"co-regulate"},
  {"id":"nd-045","cat":"strengths-and-wellbeing","type":"match","hook":"Match each strength to a way to nurture it.","pairs":[{"left":"An intense interest","right":"Give it space and resources"},{"left":"Honesty and fairness","right":"Praise and model it back"},{"left":"Creative thinking","right":"Open-ended play and projects"}],"relearn":"An intense interest, honesty and creative thinking each grow when a parent nurtures rather than discourages them.","persona":"any","source":"nurture strengths"},
  {"id":"nd-046","cat":"strengths-and-wellbeing","type":"reflect","hook":"Sam: a neurodiverse child who feels celebrated, not just corrected, grows up liking who they are. Worth it?","prompt":"What do you think?","options":["Worth it","Celebrated","Likes who they are"],"affirm":"A neurodiverse child who feels celebrated, not constantly corrected, grows up with self-worth and confidence.","relearn":"A child who feels celebrated, not just corrected, grows up liking who they are.","persona":"Meena","source":"feel celebrated"},
  {"id":"nd-047","cat":"strengths-and-wellbeing","type":"spot","hook":"Spot what supports a neurodiverse child's wellbeing.","scene":[{"id":"a","text":"Noticing and easing their anxiety","trick":false},{"id":"b","text":"Dismissing their distress as drama","trick":true},{"id":"c","text":"Celebrating who they are","trick":false}],"why":"Easing anxiety and celebrating who they are support wellbeing; dismissing distress as drama harms it.","relearn":"Support a neurodiverse child's wellbeing by easing anxiety and celebrating them, not dismissing their distress.","persona":"any","source":"support wellbeing"},
  {"id":"nd-048","cat":"strengths-and-wellbeing","type":"branch","hook":"Your neurodiverse child often seems anxious or down.","options":[{"text":"Take their wellbeing seriously and seek support if it persists","consequence":"You catch a co-occurring need early.","outcome":"wellbeing","best":true},{"text":"Assume it's just part of the diagnosis and ignore it","consequence":"Taking wellbeing seriously catches anxiety early; assuming distress is 'just the diagnosis' can miss a treatable need."}],"debrief":"Take a neurodiverse child's anxiety or low mood seriously and seek support if it persists; co-occurring needs are real.","relearn":"Don't dismiss persistent anxiety as 'just the diagnosis'; take a neurodiverse child's wellbeing seriously and seek support.","persona":"Meena","source":"wellbeing matters"},
  {"id":"nd-049","cat":"strengths-and-wellbeing","type":"reflect","hook":"Sam: your child is so much more than a diagnosis; seeing the whole, wonderful person is everything. Sit right?","prompt":"What's your take?","options":["Sits right","Whole person","More than a label"],"affirm":"A neurodiverse child is a whole, wonderful person, not a diagnosis; seeing all of them is what matters most.","relearn":"Your child is so much more than a diagnosis; seeing the whole, wonderful person is everything.","persona":"Meena","source":"whole person"},
  {"id":"nd-050","cat":"support-and-you","type":"strike-rewrite","hook":"\"A devoted parent of a neurodiverse child should run on empty and never need support.\"","myth":{"un":"A devoted parent of a neurodiverse child should run on empty and never need support.","re":"Supporting a neurodiverse child can be exhausting; looking after yourself and getting support helps you keep showing up.","why":"Your wellbeing is part of your child's support."},"relearn":"Parenting a neurodiverse child is demanding; caring for yourself and getting support is essential, not optional.","persona":"Meena","source":"your wellbeing matters"},
  {"id":"nd-051","cat":"support-and-you","type":"match","hook":"Match each support to what it offers a parent.","pairs":[{"left":"Other parents of neurodiverse kids","right":"Understanding and practical tips"},{"left":"Professionals and therapists","right":"Assessment and tailored strategies"},{"left":"Your own wellbeing care (Looking After You)","right":"Energy to keep going"}],"relearn":"Peer parents, professionals and your own wellbeing care each give a parent of a neurodiverse child real, different support.","persona":"any","source":"the supports"},
  {"id":"nd-052","cat":"support-and-you","type":"branch","hook":"You're burning out from the daily demands and the fight for support.","options":[{"text":"Reach for support and protect your own wellbeing too (see Looking After You)","consequence":"You sustain yourself so you can sustain them.","outcome":"sustain","best":true},{"text":"Push on alone until you crash","consequence":"Reaching for support sustains you for the long haul; pushing on alone until you crash helps neither you nor your child."}],"debrief":"Protect your own wellbeing and reach for support when the demands mount; a sustained parent sustains their child.","relearn":"Get support and tend your own wellbeing; pushing on alone to a crash serves no one (see Looking After You).","persona":"Divya","source":"sustain yourself"},
  {"id":"nd-053","cat":"support-and-you","type":"strike-rewrite","hook":"\"This game can diagnose my child or replace a professional.\"","myth":{"un":"This game can diagnose my child or replace a professional.","re":"This offers understanding and support, not diagnosis; a qualified professional assesses and guides specific care.","why":"Understanding tools point to professionals; they don't replace them."},"relearn":"This supports understanding but doesn't diagnose; a qualified professional assesses and guides your child's care.","persona":"any","source":"not a diagnosis"},
  {"id":"nd-054","cat":"support-and-you","type":"sort","hook":"Sort: a wise step for a parent, or one to rethink?","items":[{"id":"a","text":"Joining a parent support group"},{"id":"b","text":"Trying a miracle 'cure' online"},{"id":"c","text":"Seeing a qualified professional"},{"id":"d","text":"Coping in isolation and silence"}],"bins":[{"id":"wise","label":"Wise step"},{"id":"rethink","label":"Rethink it"}],"key":{"a":"wise","b":"rethink","c":"wise","d":"rethink"},"relearn":"Support groups and qualified professionals are wise; miracle 'cures' and silent isolation need a rethink.","persona":"any","source":"wise step"},
  {"id":"nd-055","cat":"support-and-you","type":"reflect","hook":"Sam: you don't have to know everything or do it perfectly; a learning, loving, supported parent is enough. Resonate?","prompt":"What do you think?","options":["Resonates","Enough","Learning is okay"],"affirm":"A learning, loving, supported parent is exactly what a neurodiverse child needs; you don't have to be perfect or all-knowing.","relearn":"You don't have to be perfect; a learning, loving, supported parent is enough.","persona":"any","source":"enough"},
  {"id":"nd-056","cat":"support-and-you","type":"role-play","hook":"Another exhausted parent of a neurodiverse child confides they feel alone. You want to support them.","setup":"Support them warmly:","yourLine":[{"text":"\"You're not alone, and you're doing a hard job with love, let's swap what helps and lean on each other.\"","best":true},{"text":"\"Yeah, it's impossible, I don't know how anyone does it.\""}],"relearn":"Telling an isolated parent they're not alone and offering to share what helps builds the network that sustains them both.","persona":"Priya","source":"support a parent"},
  {"id":"nd-057","cat":"support-and-you","type":"spot","hook":"Spot the sustainable way to raise a neurodiverse child well.","scene":[{"id":"a","text":"Understanding, accommodating and advocating over time","trick":false},{"id":"b","text":"Chasing a 'cure' and burning out","trick":true},{"id":"c","text":"Building a support network for you both","trick":false}],"why":"Understanding, accommodating, advocating and a support network are sustainable; chasing a 'cure' and burning out aren't.","relearn":"Raise a neurodiverse child well through understanding, accommodation, advocacy and support, not a 'cure' and burnout.","persona":"any","source":"sustainable way"},
  {"id":"nd-058","cat":"support-and-you","type":"reflect","hook":"Sam: understand, accommodate, advocate, drop the shame, and look after yourself too. Your child is lucky to have you. Ready?","prompt":"What's your take?","options":["Ready","Lucky to have me","Let's go"],"affirm":"Understanding, accommodating, advocating, dropping the shame and caring for yourself is how you raise a neurodiverse child well.","relearn":"Understand, accommodate, advocate, drop the shame, and look after yourself; that's the whole of it.","persona":"any","source":"the whole of it"},
  {"id":"nd-059","cat":"support-and-you","type":"role-play","hook":"Your co-parent struggles to accept the diagnosis and stay involved. You want to bring them in.","setup":"Bring them in gently:","yourLine":[{"text":"\"Our child needs us both to understand and support them, let's learn this together, as a team.\"","best":true},{"text":"\"Fine, I'll deal with all of it myself then.\""}],"relearn":"Inviting a co-parent to learn and support together shares the load and doubles a neurodiverse child's champions.","persona":"Vikram","source":"bring co-parent in"},
  {"id":"nd-060","cat":"understand-your-child","type":"role-play","hook":"Your child's sibling calls them 'weird'. You want to reframe it with warmth.","setup":"Reframe it warmly:","yourLine":[{"text":"\"Their brain works in its own brilliant way, different isn't weird, it's just different, and we love it.\"","best":true},{"text":"\"Yes, your sibling is a bit odd, ignore it.\""}],"relearn":"Reframing 'weird' as a different, valued way of being teaches a sibling acceptance instead of othering.","persona":"Divya","source":"reframe weird"},
  {"id":"nd-061","cat":"understand-your-child","type":"role-play","hook":"Your child asks if something is 'wrong' with them. You want to answer with love and truth.","setup":"Answer with love:","yourLine":[{"text":"\"Nothing is wrong with you, your brain just works in its own way, and that comes with real gifts.\"","best":true},{"text":"\"We're working on fixing it, don't worry.\""}],"relearn":"Telling a child nothing is wrong, their brain just works its own way with real gifts, protects their self-worth.","persona":"Meena","source":"nothing is wrong"},
  {"id":"nd-062","cat":"understand-your-child","type":"sort","hook":"Sort: an accurate understanding of neurodivergence, or a myth?","items":[{"id":"a","text":"Brains naturally vary"},{"id":"b","text":"It's contagious or a trend"},{"id":"c","text":"Every profile is individual"},{"id":"d","text":"It means low intelligence"}],"bins":[{"id":"accurate","label":"Accurate"},{"id":"myth","label":"Myth"}],"key":{"a":"accurate","b":"myth","c":"accurate","d":"myth"},"relearn":"Brains varying and individual profiles are accurate; 'contagious/trend' and 'means low intelligence' are myths.","persona":"any","source":"accurate or myth"},
  {"id":"nd-063","cat":"understand-your-child","type":"spot","hook":"Spot the lens that helps you understand your child.","scene":[{"id":"a","text":"'How does my child experience the world?'","trick":false},{"id":"b","text":"'Why won't they just act normal?'","trick":true},{"id":"c","text":"'What are their strengths and needs?'","trick":false}],"why":"Asking how they experience the world and their strengths and needs helps; 'why won't they act normal' doesn't.","relearn":"Understand your child by asking how they experience the world and what they need, not why they won't 'act normal'.","persona":"Meena","source":"helpful lens"},
  {"id":"nd-064","cat":"accommodate","type":"role-play","hook":"A relative tells you to stop 'pandering' with accommodations. You want to explain calmly.","setup":"Explain calmly:","yourLine":[{"text":"\"These aren't pampering, they're like glasses, they give him fair access so he can do his best.\"","best":true},{"text":"\"Maybe you're right, I should make him tough it out.\""}],"relearn":"Framing accommodations as fair access, like glasses, defends them against the 'pandering' myth without a fight.","persona":"Vikram","source":"not pandering"},
  {"id":"nd-065","cat":"accommodate","type":"sort","hook":"Sort: respects how the child is wired, or forces them to mask?","items":[{"id":"a","text":"Letting them fidget to focus"},{"id":"b","text":"Forcing stillness and 'normal' behaviour"},{"id":"c","text":"Quiet breaks when overstimulated"},{"id":"d","text":"Punishing self-soothing"}],"bins":[{"id":"respect","label":"Respects the wiring"},{"id":"mask","label":"Forces masking"}],"key":{"a":"respect","b":"mask","c":"respect","d":"mask"},"relearn":"Letting them fidget and giving quiet breaks respect the wiring; forcing stillness and punishing self-soothing force masking.","persona":"Meena","source":"respect or mask"},
  {"id":"nd-066","cat":"accommodate","type":"branch","hook":"Your child copes best with strict routine, but plans change suddenly today.","options":[{"text":"Prepare them with warning and a visual of the change","consequence":"You ease a hard transition for them.","outcome":"prepared","best":true},{"text":"Spring the change and expect them to just adapt","consequence":"Warning and a visual ease a hard transition; springing change on a child who needs routine sets them up to be overwhelmed."}],"debrief":"Ease sudden changes for a routine-reliant child with warning and a visual, rather than springing it on them.","relearn":"Prepare a routine-reliant child for change with warning and a visual; don't spring it and expect instant adapting.","persona":"Divya","source":"ease transitions"},
  {"id":"nd-067","cat":"accommodate","type":"match","hook":"Match each tricky moment to the accommodation that helps.","pairs":[{"left":"Overwhelming party","right":"A quiet exit plan and headphones"},{"left":"New place","right":"Visit or preview it in advance"},{"left":"Big feelings","right":"A calm-down space, not a telling-off"}],"relearn":"Parties, new places and big feelings each go better with a simple accommodation than with force.","persona":"any","source":"moment to accommodation"},
  {"id":"nd-068","cat":"advocate","type":"role-play","hook":"You're meeting your child's teacher to request support. You want to open as a partner, not a complainer.","setup":"Open as a partner:","yourLine":[{"text":"\"I'd love to work with you so he can do his best, here's what helps him, and what could we try together?\"","best":true},{"text":"\"Your class is failing my child and it's your fault.\""}],"relearn":"Opening as a collaborative partner, with what helps, gets a teacher on side far better than blame.","persona":"Meena","source":"partner with teacher"},
  {"id":"nd-069","cat":"advocate","type":"sort","hook":"Sort: strengthens your advocacy, or weakens it?","items":[{"id":"a","text":"Documenting needs and what works"},{"id":"b","text":"Giving up after one 'no'"},{"id":"c","text":"Knowing the RPwD Act protections"},{"id":"d","text":"Apologising for asking at all"}],"bins":[{"id":"strong","label":"Strengthens it"},{"id":"weak","label":"Weakens it"}],"key":{"a":"strong","b":"weak","c":"strong","d":"weak"},"relearn":"Documentation and knowing the law strengthen advocacy; giving up after one 'no' or over-apologising weaken it.","persona":"any","source":"strong or weak"},
  {"id":"nd-070","cat":"advocate","type":"branch","hook":"A service is slow and dismissive about assessing your child.","options":[{"text":"Persist politely, follow up, and seek another route if needed","consequence":"You keep the path to support open.","outcome":"persist","best":true},{"text":"Give up and assume nothing is available","consequence":"Polite persistence and alternate routes keep support reachable; giving up assumes a 'no' that may not be final."}],"debrief":"Persist politely and seek other routes when a service is slow; don't give up on the support your child needs.","relearn":"Keep advocating through slow services; one dismissal isn't the end of the road to support.","persona":"Divya","source":"persist politely"},
  {"id":"nd-071","cat":"advocate","type":"match","hook":"Match each right or support to where it applies.","pairs":[{"left":"Reasonable accommodation (RPwD Act)","right":"School and services"},{"left":"A learning support plan","right":"The classroom"},{"left":"Family understanding","right":"The home and gatherings"}],"relearn":"Reasonable accommodation, a support plan and family understanding each apply where your child needs championing.","persona":"Meena","source":"right to place"},
  {"id":"nd-072","cat":"drop-the-shame","type":"role-play","hook":"A relative whispers that your child's diagnosis is 'a punishment' or 'karma'. You want to shut it down kindly.","setup":"Shut it down kindly:","yourLine":[{"text":"\"It's no one's fault and no punishment, it's just how his brain works, and he's wonderful.\"","best":true},{"text":"\"Maybe, I do wonder what we did wrong.\""}],"relearn":"Naming that it's no one's fault and no punishment protects both you and your child from cruel, baseless blame.","persona":"Meena","source":"no punishment"},
  {"id":"nd-073","cat":"drop-the-shame","type":"sort","hook":"Sort: a true, shame-lifting statement, or a harmful blame myth?","items":[{"id":"a","text":"'You didn't cause this'"},{"id":"b","text":"'Bad mothers raise such kids'"},{"id":"c","text":"'Your child can thrive'"},{"id":"d","text":"'Hide it from everyone'"}],"bins":[{"id":"true","label":"True, lifts shame"},{"id":"blame","label":"Harmful blame"}],"key":{"a":"true","b":"blame","c":"true","d":"blame"},"relearn":"'You didn't cause this' and 'your child can thrive' lift shame; blaming mothers and 'hide it' are harmful.","persona":"any","source":"true or blame"},
  {"id":"nd-074","cat":"drop-the-shame","type":"spot","hook":"Spot the move that frees a family from shame.","scene":[{"id":"a","text":"Accepting it's no one's fault","trick":false},{"id":"b","text":"Blaming yourself endlessly","trick":true},{"id":"c","text":"Focusing energy on support","trick":false}],"why":"Accepting it's no one's fault and focusing on support free a family; endless self-blame keeps them stuck.","relearn":"Free your family from shame by accepting it's no one's fault and focusing on support, not endless self-blame.","persona":"any","source":"free from shame"},
  {"id":"nd-075","cat":"drop-the-shame","type":"branch","hook":"You feel pressure to keep your child's diagnosis a secret from everyone.","options":[{"text":"Share it on your own terms with people who can support you","consequence":"You let understanding and help in.","outcome":"share","best":true},{"text":"Keep it hidden and carry it alone","consequence":"Sharing on your terms lets in understanding and help; total secrecy isolates you and quietly reinforces the stigma."}],"debrief":"Share the diagnosis on your own terms with supportive people; total secrecy isolates you and feeds stigma.","relearn":"Choose openness on your terms over total secrecy; hiding it carries the shame it's trying to avoid.","persona":"Vikram","source":"share on your terms"},
  {"id":"nd-076","cat":"strengths-and-wellbeing","type":"role-play","hook":"Your child is fixated on one topic and others call it 'obsessive'. You want to honour it.","setup":"Honour the passion:","yourLine":[{"text":"\"That deep interest is a strength, let's feed it, it might become something amazing for you.\"","best":true},{"text":"\"Enough of that, talk about normal things.\""}],"relearn":"Honouring an intense interest as a strength to feed builds confidence, unlike dismissing it as 'obsessive'.","persona":"Meena","source":"honour the passion"},
  {"id":"nd-077","cat":"strengths-and-wellbeing","type":"role-play","hook":"After a meltdown has passed, your child seems ashamed. You want to reconnect with warmth.","setup":"Reconnect warmly:","yourLine":[{"text":"\"That was a hard moment and it's over, you're not in trouble, I'm here and I love you.\"","best":true},{"text":"\"See what happens when you don't control yourself?\""}],"relearn":"Reconnecting after a meltdown with reassurance, not reproach, rebuilds safety and self-worth.","persona":"Meena","source":"reconnect after meltdown"},
  {"id":"nd-078","cat":"strengths-and-wellbeing","type":"sort","hook":"Sort: builds a neurodiverse child's confidence, or erodes it?","items":[{"id":"a","text":"Naming what they're great at"},{"id":"b","text":"Only ever pointing out problems"},{"id":"c","text":"Celebrating small wins"},{"id":"d","text":"Comparing them to 'normal' kids"}],"bins":[{"id":"build","label":"Builds confidence"},{"id":"erode","label":"Erodes it"}],"key":{"a":"build","b":"erode","c":"build","d":"erode"},"relearn":"Naming strengths and celebrating wins build confidence; problem-only focus and comparisons erode it.","persona":"any","source":"build or erode"},
  {"id":"nd-079","cat":"strengths-and-wellbeing","type":"match","hook":"Match each sign to what your child may need.","pairs":[{"left":"Overwhelmed and melting down","right":"Calm, co-regulation, less stimulation"},{"left":"Anxious before changes","right":"Preparation and reassurance"},{"left":"Lighting up over an interest","right":"Encouragement and space"}],"relearn":"Overwhelm, anxiety and a lit-up interest each tell you what your child needs: calm, preparation, or encouragement.","persona":"Meena","source":"sign to need"},
  {"id":"nd-080","cat":"strengths-and-wellbeing","type":"spot","hook":"Spot what nurtures a neurodiverse child's self-worth.","scene":[{"id":"a","text":"Seeing and naming their gifts","trick":false},{"id":"b","text":"Treating them as a list of deficits","trick":true},{"id":"c","text":"Loving them for exactly who they are","trick":false}],"why":"Seeing their gifts and loving who they are nurture self-worth; treating them as deficits erodes it.","relearn":"Nurture a neurodiverse child's self-worth by seeing their gifts and loving who they are, not listing deficits.","persona":"Meena","source":"nurture self-worth"},
  {"id":"nd-081","cat":"support-and-you","type":"role-play","hook":"You're exhausted and a friend asks how you really are. You want to be honest, not brush it off.","setup":"Be honest:","yourLine":[{"text":"\"Honestly, it's hard and I'm tired, I love him fiercely and I could use some support too.\"","best":true},{"text":"\"Oh, we're totally fine, no problems at all.\""}],"relearn":"Being honest that it's hard and you need support opens the door to the help that sustains you for your child.","persona":"Divya","source":"be honest"},
  {"id":"nd-082","cat":"support-and-you","type":"sort","hook":"Sort: sustains a parent for the long haul, or burns them out?","items":[{"id":"a","text":"Sharing the load and resting"},{"id":"b","text":"Doing everything alone, always"},{"id":"c","text":"Leaning on a support network"},{"id":"d","text":"Never asking for help"}],"bins":[{"id":"sustain","label":"Sustains you"},{"id":"burn","label":"Burns you out"}],"key":{"a":"sustain","b":"burn","c":"sustain","d":"burn"},"relearn":"Sharing the load and a support network sustain you; doing it all alone and never asking burn you out.","persona":"any","source":"sustain or burn"},
  {"id":"nd-083","cat":"support-and-you","type":"match","hook":"Match a parent need to the support for it.","pairs":[{"left":"Feeling alone","right":"A parent support group"},{"left":"Needing strategies","right":"A professional or therapist"},{"left":"Running on empty","right":"Your own wellbeing care (g63)"}],"relearn":"Loneliness, needing strategies and running on empty each have a support: peers, professionals, and your own wellbeing care.","persona":"any","source":"need to support"},
  {"id":"nd-084","cat":"support-and-you","type":"role-play","hook":"Your child's grandparent wants to help but doesn't understand the diagnosis. You want to guide them in.","setup":"Guide them in warmly:","yourLine":[{"text":"\"Here's a simple way to understand him, and here's exactly how you can help, he adores you.\"","best":true},{"text":"\"Just don't get involved if you don't understand it.\""}],"relearn":"Warmly explaining and giving a concrete way to help turns a willing grandparent into real support, not a closed door.","persona":"Priya","source":"guide grandparent"},
];

export const RAISING_NEURODIVERSE_KIDS: V2GameConfig = {
  gameId: "raising-neurodiverse-kids",
  title: "Raising Neurodiverse Kids",
  greet: "Hey — it’s Sam. Remember ‘same same, but different’? Here it is grown up. If your child is autistic, has ADHD or a learning difference, the big reframe is this: that’s difference, not deficiency — brains naturally vary, and your child is different, not less. We’ll lead with their strengths, accommodate instead of forcing them to mask (accommodations are fair access, like glasses), advocate for their rights, and drop the shame — it’s no one’s fault, not parenting, screens or vaccines. Meltdowns are overwhelm, not naughtiness. And you matter too: this is demanding, so lean on support.",
  scenarios: SCENARIOS,
  categories: [
    { id: "understand-your-child", emoji: "🧠", label: "Understand your child" },
    { id: "accommodate", emoji: "🛠️", label: "Accommodate" },
    { id: "advocate", emoji: "📣", label: "Advocate" },
    { id: "drop-the-shame", emoji: "💛", label: "Drop the shame" },
    { id: "strengths-and-wellbeing", emoji: "🌟", label: "Strengths & wellbeing" },
    { id: "support-and-you", emoji: "🧰", label: "Support & you" },
  ],
  badge: {
    title: "Raising Neurodiverse Kids 🧩",
    blurb: "You know neurodivergence is difference, not deficiency — your child is different, not less. You lead with strengths, accommodate instead of forcing masking, advocate for their rights (RPwD Act 2016), drop the shame (it’s no one’s fault), and look after yourself too. 🌟",
  },
  helpLine: "Neurodivergence is difference, not deficiency — your child’s brain works differently, and that’s not less. It’s no one’s fault: not parenting, not screens, not vaccines. Meltdowns are overwhelm, not naughtiness. Seek assessment without shame — under India’s Rights of Persons with Disabilities Act 2016, your child has rights to reasonable accommodation. This is not a diagnostic tool; a professional can assess. And parenting this is demanding: lean on peer parents and professionals, and look after yourself too (see Looking After You; Tele-MANAS 14416).",
  helpLabel: "Find support · a professional / Tele-MANAS 14416",
  reassure: "Neurodivergence is difference, not deficiency — your child is different, not less, and brains naturally vary. It is no one’s fault: not parenting, not screens, not vaccines — and meltdowns are overwhelm, not naughtiness. Seek assessment without shame; under the RPwD Act 2016 your child has rights to reasonable accommodation. And this is demanding work: lean on peer parents and professionals, and look after yourself too — Looking After You, or Tele-MANAS 14416. 🌟",
  reassureCats: ["drop-the-shame", "support-and-you"],
};
