// Content for Raising Gender-Diverse Kids (node g66, Parent Layer, Chapter 8) — NEW v2 build to GDD 66
// (mechanic-embodying), a SENSITIVE Parent-Layer node handled with the care of Spectrum (g32): dignity-first,
// never-out, child-safety-centred. The evidence is the spine: an affirming, accepting parent is the single biggest
// protective factor in such a child's wellbeing & safety — family acceptance roughly HALVES the odds of suicidal
// thoughts and attempts and raises self-esteem and health. 84 researched, India-grounded scenarios across
// acceptance-is-protection → understand → if-they-come-out → protect-and-affirm → your-own-journey →
// support-and-india, each encoded as one of the shared v2 play actions (strike-rewrite / branch / role-play /
// reflect / sort / match / spot) — no binary "tap the right card". Lead: strike-rewrite (bust the myth), branch
// (your move), role-play (say it). Six modes: acceptance is protection (busts 'accepting causes it' and
// 'disapproval steers them back'; lead with love before full understanding), understand (orientation, gender
// identity & expression are three DIFFERENT things; busts phase/choice/illness/foreign-invention/bad-parenting
// myths), if they come out (the first reaction matters most — lead with gratitude & unconditional love, process
// your own shock later, NEVER out the child), protect and affirm (be the safe harbour & advocate, shield from
// bullying, follow the child's lead with no pressure to label or mask, use their name & pronouns), your own
// journey (meet your own fears & grief honestly and move toward acceptance without shame — take your struggle to a
// supportive ADULT, not your child), support and the India context (affirming counsellors & helplines, NEVER
// conversion 'cures', and the settled value that every child deserves a safe loving home — set against India's
// constitutional dignity, the NALSA recognition of transgender persons & self-identification, and the
// decriminalisation of consensual same-sex relations). Affirming and evidence-based, yet compassionate: it meets
// parents wherever they start, without shaming them or their beliefs, while keeping the child's safety & dignity
// NON-NEGOTIABLE; it never encourages outing a child, records no identity, and signposts KIRAN 1800-599-0019,
// Tele-MANAS 14416 & affirming counsellors; expert-reviewed. Builds on Spectrum (g32) and What Makes Me, Me (g07).
// India: families navigate real cultural & legal complexity, so the node leads with the settled value and meets
// fear with facts, not blame. gameId "raising-gender-diverse-kids".
import type { V2GameConfig, Scenario } from "./v2-schema";

const SCENARIOS: Scenario[] = [
  {"id":"gd-001","cat":"acceptance-is-protection","type":"strike-rewrite","hook":"\"Accepting a gender-diverse child encourages or causes it.\"","myth":{"un":"Accepting a gender-diverse child encourages or causes it.","re":"Acceptance doesn't cause anything; it's the single biggest protective factor in such a child's wellbeing and safety.","why":"Affirming a child protects them; it doesn't create who they are."},"relearn":"Accepting a gender-diverse child doesn't cause it; an affirming parent is their biggest protective factor.","persona":"Priya","source":"acceptance protects"},
  {"id":"gd-002","cat":"acceptance-is-protection","type":"strike-rewrite","hook":"\"Being strict or disapproving will steer my child back to 'normal'.\"","myth":{"un":"Being strict or disapproving will steer my child back to 'normal'.","re":"Rejection doesn't change who a child is; it just raises their risk of depression, self-harm and worse.","why":"Disapproval harms; it doesn't redirect."},"relearn":"Disapproval doesn't change a child's identity; it only raises their risk of depression and self-harm.","persona":"Priya","source":"rejection harms"},
  {"id":"gd-003","cat":"acceptance-is-protection","type":"reflect","hook":"Lensy: the research is clear, an affirming parent is the most powerful protection a gender-diverse child can have. Sit right?","prompt":"What do you think?","options":["Sits right","Most powerful protection","I can be that"],"affirm":"An affirming, accepting parent is the strongest protective factor for a gender-diverse child's safety and wellbeing.","relearn":"An affirming parent is the most powerful protection a gender-diverse child can have.","persona":"Priya","source":"powerful protection"},
  {"id":"gd-004","cat":"acceptance-is-protection","type":"sort","hook":"Sort: a parental response that protects a gender-diverse child, or one that raises their risk?","items":[{"id":"a","text":"Warmth and acceptance"},{"id":"b","text":"Shaming or punishing who they are"},{"id":"c","text":"Standing up for them"},{"id":"d","text":"Threatening to reject them"}],"bins":[{"id":"protects","label":"Protects them"},{"id":"risk","label":"Raises their risk"}],"key":{"a":"protects","b":"risk","c":"protects","d":"risk"},"relearn":"Warmth, acceptance and advocacy protect a child; shaming, punishing or threatening rejection raise their risk.","persona":"any","source":"protect vs risk"},
  {"id":"gd-005","cat":"acceptance-is-protection","type":"match","hook":"Match each affirming action to the protection it gives.","pairs":[{"left":"Supporting their gender expression","right":"Lower depression and self-harm risk"},{"left":"Talking respectfully about their identity","right":"Far lower odds of a suicide attempt"},{"left":"Welcoming their friends","right":"Belonging and safety"}],"relearn":"Supporting expression, talking respectfully and welcoming friends each measurably protect a gender-diverse child.","persona":"Priya","source":"actions protect"},
  {"id":"gd-006","cat":"acceptance-is-protection","type":"branch","hook":"You're torn between your worries and the evidence that acceptance keeps your child safe.","options":[{"text":"Let the child's safety lead; lead with acceptance, work through worries alongside","consequence":"You protect your child while you process.","outcome":"safety-first","best":true},{"text":"Let the worries drive you to reject or pressure","consequence":"Leading with acceptance protects your child while you process worries; letting fear drive rejection endangers them."}],"debrief":"Let your child's safety lead, lead with acceptance and work through your worries separately.","relearn":"Put your child's safety first, leading with acceptance, while you work through your own worries.","persona":"Priya","source":"safety leads"},
  {"id":"gd-007","cat":"acceptance-is-protection","type":"reflect","hook":"Lensy: you don't have to understand everything to love and protect your child today. Make sense?","prompt":"What's your take?","options":["Makes sense","Love first","Protect today"],"affirm":"You can fully love and protect your child now, even while you're still learning and understanding.","relearn":"You don't have to understand everything to love and protect your child today.","persona":"any","source":"love before understanding"},
  {"id":"gd-008","cat":"acceptance-is-protection","type":"spot","hook":"Spot what makes home a protective place for a gender-diverse child.","scene":[{"id":"a","text":"Being loved and accepted as they are","trick":false},{"id":"b","text":"Fearing rejection at home","trick":true},{"id":"c","text":"Knowing a parent has their back","trick":false}],"why":"Being loved as they are and having a parent's backing protect a child; fearing rejection at home harms them.","relearn":"Home protects a gender-diverse child when they're loved as they are and know a parent has their back.","persona":"any","source":"protective home"},
  {"id":"gd-009","cat":"acceptance-is-protection","type":"strike-rewrite","hook":"\"My disapproval is harmless as long as I still feed and house my child.\"","myth":{"un":"My disapproval is harmless as long as I still feed and house my child.","re":"Children feel rejection deeply; ongoing disapproval harms their mental health even when material needs are met.","why":"Felt rejection wounds, food or not."},"relearn":"Disapproval isn't harmless even with needs met; children feel rejection deeply, and it harms their mental health.","persona":"any","source":"felt rejection"},
  {"id":"gd-010","cat":"acceptance-is-protection","type":"reflect","hook":"Lensy: 'I love you, no matter what' may be the most protective sentence your child ever hears. Worth saying often?","prompt":"What do you think?","options":["Worth it","Say it often","Most protective"],"affirm":"Hearing 'I love you no matter what', and feeling it, is profoundly protective for a gender-diverse child.","relearn":"'I love you, no matter what' may be the most protective sentence your child ever hears.","persona":"Priya","source":"most protective sentence"},
  {"id":"gd-011","cat":"understand","type":"strike-rewrite","hook":"\"Being gender-diverse or LGBTQ+ is just a phase or a trend kids copy.\"","myth":{"un":"Being gender-diverse or LGBTQ+ is just a phase or a trend kids copy.","re":"Identity isn't a trend or a passing phase to wait out; whether it shifts or not, your child deserves respect now.","why":"You respect a child as they are, today."},"relearn":"Being LGBTQ+ or gender-diverse isn't a trend to wait out; respect your child as they are now.","persona":"Priya","source":"not a phase"},
  {"id":"gd-012","cat":"understand","type":"strike-rewrite","hook":"\"Someone chose to be this way, or was made this way by bad parenting.\"","myth":{"un":"Someone chose to be this way, or was made this way by bad parenting.","re":"Sexual orientation and gender identity aren't a choice or caused by parenting; they're part of who a person is.","why":"It's not a choice and not your fault."},"relearn":"Orientation and gender identity aren't chosen or caused by parenting; they're simply part of who a child is.","persona":"Priya","source":"not a choice"},
  {"id":"gd-013","cat":"understand","type":"sort","hook":"Sort: an accurate idea about gender and orientation, or a myth to drop?","items":[{"id":"a","text":"Gender identity is an innate sense of self"},{"id":"b","text":"It's an illness to be cured"},{"id":"c","text":"Orientation and gender identity are different things"},{"id":"d","text":"It's a foreign or modern invention"}],"bins":[{"id":"accurate","label":"Accurate"},{"id":"myth","label":"Myth to drop"}],"key":{"a":"accurate","b":"myth","c":"accurate","d":"myth"},"relearn":"Identity as innate and orientation differing from gender identity are accurate; 'illness' and 'foreign invention' are myths.","persona":"any","source":"accurate vs myth"},
  {"id":"gd-014","cat":"understand","type":"match","hook":"Match each term to what it means.","pairs":[{"left":"Sexual orientation","right":"Who you're attracted to"},{"left":"Gender identity","right":"Your own inner sense of your gender"},{"left":"Gender expression","right":"How you show it, clothes, hair, style"}],"relearn":"Orientation (attraction), gender identity (inner sense) and expression (how you show it) are three different things.","persona":"any","source":"the three terms"},
  {"id":"gd-015","cat":"understand","type":"strike-rewrite","hook":"\"A boy who likes 'girl things' (or vice versa) must be confused or broken.\"","myth":{"un":"A boy who likes 'girl things' (or vice versa) must be confused or broken.","re":"Children explore interests and expression freely; a boy in a dress or a girl who loves trucks is just a child being themselves.","why":"Interests have no gender; kids aren't broken for crossing them."},"relearn":"A child crossing 'gendered' interests isn't confused or broken; they're just being themselves.","persona":"Priya","source":"interests no gender"},
  {"id":"gd-016","cat":"understand","type":"reflect","hook":"Lensy: replacing fear with accurate facts is the first gift you give a gender-diverse child. Resonate?","prompt":"What do you think?","options":["Resonates","Facts over fear","First gift"],"affirm":"Replacing fear and myth with accurate understanding is the foundation of affirming and protecting your child.","relearn":"Replacing fear with accurate facts is the first gift you give a gender-diverse child.","persona":"Priya","source":"facts over fear"},
  {"id":"gd-017","cat":"understand","type":"strike-rewrite","hook":"\"Transgender means the same thing as gay.\"","myth":{"un":"Transgender means the same thing as gay.","re":"They're different: being transgender is about gender identity, while gay is about orientation; a person can be either, both or neither.","why":"Identity and attraction are separate."},"relearn":"Transgender (gender identity) and gay (orientation) are different things; they're not the same.","persona":"any","source":"trans vs gay"},
  {"id":"gd-018","cat":"understand","type":"spot","hook":"Spot the accurate understanding of a gender-diverse child.","scene":[{"id":"a","text":"They're being who they are","trick":false},{"id":"b","text":"They're doing it to rebel or hurt you","trick":true},{"id":"c","text":"Their identity is real and theirs","trick":false}],"why":"A child being who they are, with a real identity, is accurate; 'doing it to hurt you' is a hurtful myth.","relearn":"A gender-diverse child is being who they are; it isn't rebellion or an attack on you.","persona":"Priya","source":"accurate understanding"},
  {"id":"gd-019","cat":"understand","type":"branch","hook":"You don't fully understand your child's identity and feel out of your depth.","options":[{"text":"Learn from good sources and your child, with humility","consequence":"Your understanding grows alongside your love.","outcome":"learn","best":true},{"text":"Reject what you don't yet understand","consequence":"Learning with humility grows understanding and trust; rejecting what you don't understand harms your child and bond."}],"debrief":"Meet what you don't understand with humble learning from good sources and your child, not rejection.","relearn":"Learn with humility when you're out of your depth; rejecting what you don't yet understand harms your child.","persona":"Vikram","source":"learn with humility"},
  {"id":"gd-020","cat":"understand","type":"reflect","hook":"Lensy: you can be a beginner at this and still be exactly the parent your child needs. Sit right?","prompt":"What's your take?","options":["Sits right","Beginner is okay","I can learn"],"affirm":"You don't need to be an expert; a willing, loving, learning parent is exactly what a gender-diverse child needs.","relearn":"You can be a beginner at this and still be exactly the parent your child needs.","persona":"any","source":"beginner is enough"},
  {"id":"gd-021","cat":"if-they-come-out","type":"strike-rewrite","hook":"\"How I first react to my child coming out doesn't really matter.\"","myth":{"un":"How I first react to my child coming out doesn't really matter.","re":"The first reaction matters enormously; a warm, loving response is something a child remembers and is protected by for life.","why":"That first moment can shape everything."},"relearn":"Your first reaction to a child coming out matters enormously; warmth in that moment protects them for life.","persona":"Priya","source":"first reaction matters"},
  {"id":"gd-022","cat":"if-they-come-out","type":"role-play","hook":"Your child nervously tells you they think they're LGBTQ+ or gender-diverse. You want your first words to land with love.","setup":"Respond with love:","yourLine":[{"text":"\"Thank you for trusting me, I love you exactly as you are, and that will never change.\"","best":true},{"text":"\"Are you sure? It's probably just a phase.\""}],"relearn":"Leading with gratitude and unconditional love is the single most protective first response you can give.","persona":"Priya","source":"first words"},
  {"id":"gd-023","cat":"if-they-come-out","type":"branch","hook":"Your child comes out and you feel shock, but you don't want to wound them.","options":[{"text":"Lead with love now; you can process your own feelings later","consequence":"Your child feels safe even as you adjust.","outcome":"love-now","best":true},{"text":"React from the shock and say something harsh","consequence":"Leading with love now keeps your child safe while you adjust privately; a harsh shocked reaction can wound deeply."}],"debrief":"Lead with love in the moment a child comes out, and process your own shock later, separately.","relearn":"Give love first when a child comes out; handle your own shock later so you don't wound them.","persona":"Vikram","source":"love now, process later"},
  {"id":"gd-024","cat":"if-they-come-out","type":"match","hook":"Match each first-response instinct to the affirming version.","pairs":[{"left":"'Are you sure?'","right":"'Thank you for telling me'"},{"left":"'It's a phase'","right":"'I love you no matter what'"},{"left":"'What did we do wrong?'","right":"'How can I support you?'"}],"relearn":"Each doubting first instinct has an affirming version that protects the child instead of questioning them.","persona":"Priya","source":"affirming versions"},
  {"id":"gd-025","cat":"if-they-come-out","type":"strike-rewrite","hook":"\"If my child comes out, I should immediately tell relatives.\"","myth":{"un":"If my child comes out, I should immediately tell relatives.","re":"It's the child's story to share or not; never out them, let them choose who knows and when.","why":"Their identity is theirs to disclose."},"relearn":"Never out your child to relatives; whether and when to share their identity is the child's own choice.","persona":"Priya","source":"never out them"},
  {"id":"gd-026","cat":"if-they-come-out","type":"reflect","hook":"Lensy: 'I love you and I'm so glad you told me' is a response your child will carry forever. Worth getting right?","prompt":"What do you think?","options":["Worth it","Carry it forever","Get it right"],"affirm":"A warm 'I love you and I'm glad you told me' is a response a child carries, and is protected by, for life.","relearn":"'I love you and I'm so glad you told me' is a response your child will carry forever.","persona":"Priya","source":"carry forever"},
  {"id":"gd-027","cat":"if-they-come-out","type":"spot","hook":"Spot the response that keeps a child safe when they come out.","scene":[{"id":"a","text":"Warmth, love and 'thank you for telling me'","trick":false},{"id":"b","text":"Shock, anger or denial","trick":true},{"id":"c","text":"'I'm here, let's figure it out together'","trick":false}],"why":"Warmth and 'we'll figure it out together' keep a child safe; shock, anger or denial put them at risk.","relearn":"Meet a coming-out with warmth and 'we'll figure it out together', not shock, anger or denial.","persona":"Priya","source":"safe response"},
  {"id":"gd-028","cat":"if-they-come-out","type":"branch","hook":"You reacted badly when your child first came out, and you regret it.","options":[{"text":"Go back, apologise, and reaffirm your love","consequence":"You repair and restore their safety with you.","outcome":"repair","best":true},{"text":"Let it stand because the moment passed","consequence":"Going back to apologise and reaffirm love repairs the rupture; letting a bad reaction stand leaves your child unsafe with you."}],"debrief":"If you reacted badly to a coming-out, go back, apologise and reaffirm your love; repair is always possible.","relearn":"Repair a bad first reaction by going back to apologise and reaffirm love; it's never too late.","persona":"Vikram","source":"repair the reaction"},
  {"id":"gd-029","cat":"if-they-come-out","type":"role-play","hook":"Your child asks if you still love them after coming out. You want to leave zero doubt.","setup":"Leave zero doubt:","yourLine":[{"text":"\"I love you completely, nothing about this changes that, you're my child and always will be.\"","best":true},{"text":"\"Of course, but I wish things were different.\""}],"relearn":"A clear, unconditional 'nothing changes my love' leaves no room for the doubt that endangers a child.","persona":"Priya","source":"zero doubt"},
  {"id":"gd-030","cat":"if-they-come-out","type":"reflect","hook":"Lensy: a child who comes out to you has handed you their trust; how you hold it shapes their life. Feel the weight?","prompt":"What's your take?","options":["Feel it","Hold the trust","It matters"],"affirm":"When a child comes out to you, they're handing you their trust; holding it with love shapes their whole life.","relearn":"A child coming out hands you their trust; how you hold it shapes their life.","persona":"any","source":"hold the trust"},
  {"id":"gd-031","cat":"protect-and-affirm","type":"strike-rewrite","hook":"\"My job is to toughen my gender-diverse child up against a harsh world.\"","myth":{"un":"My job is to toughen my gender-diverse child up against a harsh world.","re":"The world may be hard, but your job is to be their safe harbour and advocate, not another source of toughening or pressure.","why":"Be the shelter, not the storm."},"relearn":"Your job isn't to toughen a gender-diverse child against the world, but to be their safe harbour and advocate.","persona":"Priya","source":"be the harbour"},
  {"id":"gd-032","cat":"protect-and-affirm","type":"branch","hook":"Your child is being bullied for being different. ","options":[{"text":"Step in, support them, and advocate for their safety","consequence":"Your child knows you'll protect them.","outcome":"advocate","best":true},{"text":"Tell them to just fit in to avoid trouble","consequence":"Stepping in and advocating shows your child you'll protect them; 'just fit in' tells them their safety is their burden alone."}],"debrief":"Protect a bullied gender-diverse child by stepping in and advocating, not by telling them to fit in.","relearn":"Advocate for a bullied child's safety; 'just fit in to avoid trouble' abandons them to the harm.","persona":"Priya","source":"advocate for them"},
  {"id":"gd-033","cat":"protect-and-affirm","type":"strike-rewrite","hook":"\"I should pressure my child to look and act 'normal' for their own good.\"","myth":{"un":"I should pressure my child to look and act 'normal' for their own good.","re":"Pressuring a child to mask who they are harms their mental health; affirming who they are is what truly serves them.","why":"Masking costs a child dearly."},"relearn":"Pressuring a child to mask harms their mental health; affirming who they are is what truly serves them.","persona":"Priya","source":"no masking pressure"},
  {"id":"gd-034","cat":"protect-and-affirm","type":"sort","hook":"Sort: affirming and following the child, or forcing them into a box?","items":[{"id":"a","text":"Letting them express themselves"},{"id":"b","text":"Banning the clothes or names they prefer"},{"id":"c","text":"Following their lead, no rush to label"},{"id":"d","text":"Demanding they pick or drop a label"}],"bins":[{"id":"affirm","label":"Affirm & follow"},{"id":"force","label":"Force a box"}],"key":{"a":"affirm","b":"force","c":"affirm","d":"force"},"relearn":"Letting them express and following their lead affirms; banning expression or demanding labels forces a box.","persona":"any","source":"affirm vs force"},
  {"id":"gd-035","cat":"protect-and-affirm","type":"match","hook":"Match each affirming move to what it gives your child.","pairs":[{"left":"Using the name or pronouns they ask for","right":"Feeling seen and respected"},{"left":"Defending them to others","right":"Safety and a fierce ally"},{"left":"No pressure to label or 'decide'","right":"Room to just be"}],"relearn":"Using their name, defending them and not pressuring labels each give a gender-diverse child safety and respect.","persona":"Priya","source":"affirming moves"},
  {"id":"gd-036","cat":"protect-and-affirm","type":"reflect","hook":"Lensy: you don't have to label or fix anything; following your child with love is the whole job. Resonate?","prompt":"What do you think?","options":["Resonates","Follow with love","No fixing"],"affirm":"Affirming a child means following them with love, not labelling, fixing or rushing them into any box.","relearn":"You don't have to label or fix anything; following your child with love is the whole job.","persona":"any","source":"follow with love"},
  {"id":"gd-037","cat":"protect-and-affirm","type":"spot","hook":"Spot what affirms a gender-diverse child rather than pressuring them.","scene":[{"id":"a","text":"Respecting their name and expression","trick":false},{"id":"b","text":"Forcing them to conform to look normal","trick":true},{"id":"c","text":"Letting them lead at their own pace","trick":false}],"why":"Respecting their expression and letting them lead affirm; forcing conformity to look 'normal' pressures and harms.","relearn":"Affirm by respecting expression and following the child's pace, not by forcing conformity.","persona":"any","source":"affirm not pressure"},
  {"id":"gd-038","cat":"protect-and-affirm","type":"branch","hook":"Relatives want you to shame or 'correct' your child at a family event.","options":[{"text":"Quietly protect your child and decline to shame them","consequence":"Your child knows home and you are safe.","outcome":"protect","best":true},{"text":"Join in to avoid family conflict","consequence":"Quietly protecting your child keeps you their safe place; joining the shaming to avoid conflict betrays them where it matters most."}],"debrief":"Protect your child from relatives' pressure to shame them; their safety with you matters more than avoiding conflict.","relearn":"Shield your child from relatives' shaming; don't join in to keep the peace, home must stay safe.","persona":"Priya","source":"protect at events"},
  {"id":"gd-039","cat":"protect-and-affirm","type":"role-play","hook":"Someone misgenders or mocks your child in front of you. You want to model calm advocacy.","setup":"Advocate calmly:","yourLine":[{"text":"\"Actually, this is my child and we use their name and pronouns, please respect that.\"","best":true},{"text":"\"Haha, kids these days, ignore it.\""}],"relearn":"Calmly correcting and standing up for your child models advocacy and shows them you always have their back.","persona":"Vikram","source":"calm advocacy"},
  {"id":"gd-040","cat":"protect-and-affirm","type":"reflect","hook":"Lensy: home should be the place your child is safest, never the place they're least safe. Feel the weight?","prompt":"What's your take?","options":["Feel it","Safest place","Never least safe"],"affirm":"For a gender-diverse child, home should be the safest place in their life, not the most dangerous one.","relearn":"Home should be where your child is safest, never where they're least safe.","persona":"Priya","source":"safest place"},
  {"id":"gd-041","cat":"your-own-journey","type":"strike-rewrite","hook":"\"If I have any fears or struggles about this, I'm a bad, bigoted parent.\"","myth":{"un":"If I have any fears or struggles about this, I'm a bad, bigoted parent.","re":"Having feelings to work through is human, especially if you weren't raised with this; what matters is the direction you move, toward acceptance.","why":"Your starting point isn't your verdict."},"relearn":"Having fears to work through doesn't make you bad; what matters is moving toward acceptance, and you can.","persona":"Vikram","source":"feelings are human"},
  {"id":"gd-042","cat":"your-own-journey","type":"reflect","hook":"Lensy: you can love your child completely and still need time to understand and adjust. Both can be true. Sit right?","prompt":"What do you think?","options":["Sits right","Both true","Time to adjust"],"affirm":"Loving your child fully and needing time to adjust can both be true; the love can lead while understanding catches up.","relearn":"You can love your child completely and still need time to understand and adjust.","persona":"Vikram","source":"both true"},
  {"id":"gd-043","cat":"your-own-journey","type":"sort","hook":"Sort: helps you move toward acceptance, or keeps you stuck?","items":[{"id":"a","text":"Learning and sitting with your feelings"},{"id":"b","text":"Blaming yourself or your child"},{"id":"c","text":"Talking to a supportive person"},{"id":"d","text":"Refusing to engage at all"}],"bins":[{"id":"toward","label":"Moves you toward"},{"id":"stuck","label":"Keeps you stuck"}],"key":{"a":"toward","b":"stuck","c":"toward","d":"stuck"},"relearn":"Learning, sitting with feelings and supportive talk move you toward acceptance; blame and refusal keep you stuck.","persona":"Vikram","source":"toward vs stuck"},
  {"id":"gd-044","cat":"your-own-journey","type":"strike-rewrite","hook":"\"Grieving the future I imagined for my child means I've rejected them.\"","myth":{"un":"Grieving the future I imagined for my child means I've rejected them.","re":"Quietly grieving an imagined future is a normal part of many parents' journeys; you can feel that and still fully embrace your real child.","why":"Private grief and full love can coexist."},"relearn":"Grieving an imagined future is a normal part of the journey; you can feel it and still fully embrace your real child.","persona":"Vikram","source":"grief and love coexist"},
  {"id":"gd-045","cat":"your-own-journey","type":"branch","hook":"Your own beliefs and your child's identity feel like they're in tension.","options":[{"text":"Hold your child's safety and dignity as the non-negotiable while you work it through","consequence":"Your child stays safe as you grow.","outcome":"non-negotiable","best":true},{"text":"Put your discomfort above your child's wellbeing","consequence":"Keeping your child's safety non-negotiable protects them as you work through tension; putting discomfort first endangers them."}],"debrief":"When beliefs and your child's identity feel in tension, hold their safety and dignity as the non-negotiable.","relearn":"Make your child's safety and dignity the non-negotiable while you work through any tension with your beliefs.","persona":"Vikram","source":"child is non-negotiable"},
  {"id":"gd-046","cat":"your-own-journey","type":"reflect","hook":"Lensy: doing the work on your own feelings, so they don't land on your child, is an act of love. Resonate?","prompt":"What's your take?","options":["Resonates","Act of love","I'll do the work"],"affirm":"Processing your own feelings privately, so they don't burden your child, is a real act of parental love.","relearn":"Doing the work on your own feelings, so they don't land on your child, is an act of love.","persona":"Vikram","source":"do the work"},
  {"id":"gd-047","cat":"your-own-journey","type":"role-play","hook":"You're struggling and want to talk to someone supportive rather than burden your child. You reach out.","setup":"Reach out honestly:","yourLine":[{"text":"\"I love my child and I'm finding my feet with this, can I talk it through with you?\"","best":true},{"text":"\"I just can't accept this, and I've told my child so.\""}],"relearn":"Taking your struggle to a supportive adult, not your child, lets you process without making your child carry it.","persona":"Vikram","source":"process elsewhere"},
  {"id":"gd-048","cat":"your-own-journey","type":"spot","hook":"Spot the healthy way to handle your own journey.","scene":[{"id":"a","text":"Learning and moving toward acceptance","trick":false},{"id":"b","text":"Making your child manage your feelings","trick":true},{"id":"c","text":"Getting your own support","trick":false}],"why":"Learning, moving toward acceptance and getting your own support are healthy; making your child carry your feelings isn't.","relearn":"Handle your journey by learning and getting support, not by making your child manage your feelings.","persona":"any","source":"healthy journey"},
  {"id":"gd-049","cat":"your-own-journey","type":"reflect","hook":"Lensy: even small steps toward acceptance, today, make your child safer. Worth taking one? ","prompt":"What's your take?","options":["Worth it","Small steps","One today"],"affirm":"Acceptance can be a journey of small steps, and each step you take today makes your child safer.","relearn":"Even small steps toward acceptance, today, make your child safer.","persona":"Priya","source":"small steps count"},
  {"id":"gd-050","cat":"support-and-india","type":"strike-rewrite","hook":"\"There's no support for families like mine in India, so I'm on my own.\"","myth":{"un":"There's no support for families like mine in India, so I'm on my own.","re":"Support exists, affirming counsellors and helplines like KIRAN 1800-599-0019 and Tele-MANAS 14416, for both you and your child.","why":"You and your child aren't alone."},"relearn":"Support exists in India, affirming counsellors and helplines (KIRAN 1800-599-0019, Tele-MANAS 14416), for you and your child.","persona":"Priya","source":"support exists"},
  {"id":"gd-051","cat":"support-and-india","type":"strike-rewrite","hook":"\"Indian law and culture mean my gender-diverse child has no dignity or rights.\"","myth":{"un":"Indian law and culture mean my gender-diverse child has no dignity or rights.","re":"Dignity and equality are constitutional: the NALSA judgment recognises transgender persons and self-ID, and consensual same-sex relations are decriminalised.","why":"The settled value is dignity for every child."},"relearn":"Dignity and equality are constitutional in India; NALSA recognises transgender persons and same-sex relations are decriminalised.","persona":"Priya","source":"dignity and rights"},
  {"id":"gd-052","cat":"support-and-india","type":"match","hook":"Match each Indian legal landmark to what it affirms (general info, not legal advice).","pairs":[{"left":"NALSA judgment (2014)","right":"Recognition of transgender persons and self-identity"},{"left":"Section 377 read down (2018)","right":"Consensual same-sex relations decriminalised"},{"left":"Transgender Persons Act (2019)","right":"Protection from discrimination"}],"relearn":"NALSA, the 2018 Section 377 ruling and the 2019 Act each affirm dignity and rights for gender-diverse people in India.","persona":"Priya","source":"legal landmarks"},
  {"id":"gd-053","cat":"support-and-india","type":"branch","hook":"You want help but worry that reaching out could out your child.","options":[{"text":"Seek support that protects your child's privacy, never outing them","consequence":"You get help while keeping their story theirs.","outcome":"private-support","best":true},{"text":"Avoid all support and struggle in silence","consequence":"Privacy-protecting support helps without outing your child; avoiding all support leaves you both struggling alone."}],"debrief":"Seek support that protects your child's privacy and never outs them; you can get help and keep their story theirs.","relearn":"Get privacy-protecting support rather than struggling in silence; never out your child to get help.","persona":"Priya","source":"private support"},
  {"id":"gd-054","cat":"support-and-india","type":"sort","hook":"Sort: a supportive, affirming resource, or one to be wary of?","items":[{"id":"a","text":"An affirming counsellor"},{"id":"b","text":"Anyone promising to 'cure' or change your child"},{"id":"c","text":"A peer support group for parents"},{"id":"d","text":"So-called conversion practices"}],"bins":[{"id":"support","label":"Genuine support"},{"id":"wary","label":"Be wary, harmful"}],"key":{"a":"support","b":"wary","c":"support","d":"wary"},"relearn":"Affirming counsellors and parent support groups help; anyone promising to 'cure' a child, or conversion practices, harm.","persona":"Priya","source":"support vs harm"},
  {"id":"gd-055","cat":"support-and-india","type":"reflect","hook":"Lensy: leading with the settled value, every child deserves a safe, loving home, carries you through the hard parts. Sit right?","prompt":"What do you think?","options":["Sits right","Every child","Lead with that"],"affirm":"Leading with the settled value that every child deserves a safe, loving home guides a parent through real complexity.","relearn":"Leading with 'every child deserves a safe, loving home' carries you through the hard parts.","persona":"Priya","source":"the settled value"},
  {"id":"gd-056","cat":"support-and-india","type":"strike-rewrite","hook":"\"So-called 'conversion' or 'cure' approaches will help my child.\"","myth":{"un":"So-called 'conversion' or 'cure' approaches will help my child.","re":"Conversion practices are discredited and harmful; affirming support is what genuinely helps a gender-diverse child.","why":"There is nothing to cure, only a child to support."},"relearn":"Conversion or 'cure' approaches are discredited and harmful; affirming support is what genuinely helps your child.","persona":"Priya","source":"no conversion"},
  {"id":"gd-057","cat":"support-and-india","type":"spot","hook":"Spot the move that supports both you and your child well.","scene":[{"id":"a","text":"Finding affirming, privacy-respecting help","trick":false},{"id":"b","text":"Seeking someone to change the child","trick":true},{"id":"c","text":"Connecting with other accepting parents","trick":false}],"why":"Affirming, private help and connecting with accepting parents support you both; seeking to change the child harms.","relearn":"Support both of you with affirming, private help and accepting peers, never by trying to change your child.","persona":"any","source":"supports both"},
  {"id":"gd-058","cat":"support-and-india","type":"role-play","hook":"Another parent of a gender-diverse child confides they're scared and ashamed. You want to support them.","setup":"Support them warmly:","yourLine":[{"text":"\"You're not alone, and loving your kid through this is the bravest, best thing, let's find support together.\"","best":true},{"text":"\"Yeah, it's a disaster, I don't know how you'll cope.\""}],"relearn":"Telling a frightened parent they're not alone and pointing to support, without judgement, helps them be their child's safe place.","persona":"Vikram","source":"support a parent"},
  {"id":"gd-059","cat":"support-and-india","type":"reflect","hook":"Lensy: be the safe place, lead with love, protect fiercely, and reach for support. Your child is lucky to have you trying. Ready?","prompt":"What's your take?","options":["Ready","Be the safe place","Lead with love"],"affirm":"Being the safe place, leading with love, protecting fiercely and reaching for support is how you raise a gender-diverse child well.","relearn":"Be the safe place, lead with love, protect fiercely, and reach for support; that's the whole of it.","persona":"any","source":"be the safe place"},
  {"id":"gd-060","cat":"acceptance-is-protection","type":"role-play","hook":"Your child seems to be testing whether you'll still love them if they're different. You want to reassure them clearly.","setup":"Reassure them clearly:","yourLine":[{"text":"\"There is nothing you could be that would make me love you any less, ever.\"","best":true},{"text":"\"Well, that depends on what you mean.\""}],"relearn":"An unconditional 'nothing makes me love you less' gives a child the safety that protects them most.","persona":"Divya","source":"unconditional love"},
  {"id":"gd-061","cat":"acceptance-is-protection","type":"sort","hook":"Sort: a parent behaviour shown to protect LGBTQ+ youth, or one shown to harm?","items":[{"id":"a","text":"Supporting their identity openly"},{"id":"b","text":"Blocking their friends and expression"},{"id":"c","text":"Advocating when they're mistreated"},{"id":"d","text":"Frequent criticism of who they are"}],"bins":[{"id":"protect","label":"Protects"},{"id":"harm","label":"Harms"}],"key":{"a":"protect","b":"harm","c":"protect","d":"harm"},"relearn":"Open support and advocacy protect LGBTQ+ youth; blocking their friends and criticising who they are harm them.","persona":"any","source":"protect or harm"},
  {"id":"gd-062","cat":"acceptance-is-protection","type":"branch","hook":"You're tempted to withhold warmth to express your disapproval.","options":[{"text":"Keep the warmth flowing; your acceptance is their lifeline","consequence":"Your child stays anchored and safe.","outcome":"warmth","best":true},{"text":"Go cold to signal you don't approve","consequence":"Keeping warmth keeps your child anchored and safe; going cold to signal disapproval is exactly what raises their risk."}],"debrief":"Keep your warmth flowing even while you process; your acceptance is your child's lifeline, not a reward to withhold.","relearn":"Don't withdraw warmth to show disapproval; that acceptance is your child's lifeline.","persona":"Priya","source":"keep warmth"},
  {"id":"gd-063","cat":"acceptance-is-protection","type":"match","hook":"Match each fear to the protective fact that answers it.","pairs":[{"left":"'Accepting will make it worse'","right":"Acceptance protects; it doesn't cause"},{"left":"'They'll have a hard life'","right":"Your support is what makes it easier"},{"left":"'I'll lose my child'","right":"Rejection loses children; love keeps them"}],"relearn":"Each parental fear has a protective fact: acceptance protects, your support eases their path, and love keeps your child close.","persona":"Priya","source":"fear to fact"},
  {"id":"gd-064","cat":"understand","type":"role-play","hook":"Your younger child asks why their sibling is 'different'. You want to explain simply and kindly.","setup":"Explain simply:","yourLine":[{"text":"\"People come in lots of kinds, and your sibling is just being who they are, and we love them for it.\"","best":true},{"text":"\"Don't ask about that, it's not normal.\""}],"relearn":"A simple 'people come in lots of kinds, and we love them' teaches a sibling acceptance instead of shame.","persona":"Divya","source":"explain to sibling"},
  {"id":"gd-065","cat":"understand","type":"sort","hook":"Sort: an accurate statement, or a harmful myth, about gender-diverse kids?","items":[{"id":"a","text":"A child can know their own gender"},{"id":"b","text":"It can be 'caught' from friends"},{"id":"c","text":"Expression and identity can differ"},{"id":"d","text":"It's caused by too much screen time"}],"bins":[{"id":"accurate","label":"Accurate"},{"id":"myth","label":"Harmful myth"}],"key":{"a":"accurate","b":"myth","c":"accurate","d":"myth"},"relearn":"A child knowing their gender and expression differing from identity are accurate; 'caught from friends' and 'screen time' are myths.","persona":"any","source":"accurate or myth"},
  {"id":"gd-066","cat":"understand","type":"branch","hook":"You catch yourself reacting from an old myth you grew up believing.","options":[{"text":"Update the belief with accurate information","consequence":"Your parenting follows facts, not fear.","outcome":"update","best":true},{"text":"Act on the myth because it's familiar","consequence":"Updating the belief lets your parenting follow facts; acting on a familiar myth passes fear and harm to your child."}],"debrief":"When an old myth drives your reaction, update it with accurate information rather than acting on the fear.","relearn":"Replace the inherited myths with facts; acting on a familiar myth just harms your child.","persona":"Vikram","source":"update the belief"},
  {"id":"gd-067","cat":"understand","type":"spot","hook":"Spot the accurate, helpful frame for a parent.","scene":[{"id":"a","text":"'My child is showing me who they are'","trick":false},{"id":"b","text":"'My child is sick and needs curing'","trick":true},{"id":"c","text":"'My job is to understand and support'","trick":false}],"why":"'Showing me who they are' and 'understand and support' are accurate; 'sick and needs curing' is a harmful myth.","relearn":"The accurate frame is 'my child is showing me who they are, and my job is to support', not 'curing' them.","persona":"Priya","source":"accurate frame"},
  {"id":"gd-068","cat":"if-they-come-out","type":"role-play","hook":"Days after coming out, your child is watching how you treat them. You want every signal to say 'safe'.","setup":"Signal safety:","yourLine":[{"text":"\"I've been thinking about what you told me, I'm proud you trusted me, and I'm right here with you.\"","best":true},{"text":"\"Let's just not bring it up again, okay?\""}],"relearn":"Following up with pride and presence, rather than silence, tells a child the door is genuinely open and safe.","persona":"Priya","source":"signal safety"},
  {"id":"gd-069","cat":"if-they-come-out","type":"branch","hook":"You want to ask your child questions, but worry about getting it wrong.","options":[{"text":"Ask gently and follow their comfort, it's okay to be learning","consequence":"Your child feels respected and led.","outcome":"gentle-ask","best":true},{"text":"Either interrogate them or avoid it entirely","consequence":"Asking gently at their pace respects your child; interrogating or avoiding both miss the warm middle they need."}],"debrief":"Ask gentle questions led by your child's comfort; you can be learning without interrogating or avoiding.","relearn":"Ask gently and follow your child's comfort; you needn't get every word perfect to be supportive.","persona":"Vikram","source":"gentle questions"},
  {"id":"gd-070","cat":"if-they-come-out","type":"sort","hook":"Sort: a response that affirms a coming-out, or one that wounds?","items":[{"id":"a","text":"'Thank you for telling me'"},{"id":"b","text":"'You're too young to know'"},{"id":"c","text":"'I love you, tell me more'"},{"id":"d","text":"'Don't tell anyone, it's shameful'"}],"bins":[{"id":"affirm","label":"Affirms"},{"id":"wound","label":"Wounds"}],"key":{"a":"affirm","b":"wound","c":"affirm","d":"wound"},"relearn":"'Thank you for telling me' and 'I love you, tell me more' affirm; 'too young' and 'shameful' wound.","persona":"any","source":"affirm or wound"},
  {"id":"gd-071","cat":"if-they-come-out","type":"match","hook":"Match each thing a child needs after coming out to how you give it.","pairs":[{"left":"To feel still loved","right":"Say it, clearly and often"},{"left":"To feel safe","right":"Keep their confidence, don't out them"},{"left":"To feel led","right":"Follow their pace, no rush"}],"relearn":"After coming out a child needs to feel loved, safe and led, given through clear love, confidence kept, and their own pace.","persona":"Priya","source":"what they need"},
  {"id":"gd-072","cat":"protect-and-affirm","type":"role-play","hook":"Your child asks you to use a different name or pronoun. You want to honour it warmly.","setup":"Honour it warmly:","yourLine":[{"text":"\"Of course, I'll use that, and I'll get it right, just remind me kindly if I slip.\"","best":true},{"text":"\"That's too confusing, I'll call you what I always have.\""}],"relearn":"Agreeing warmly to a child's name and pronouns, slips and all, is a powerful, daily act of affirmation.","persona":"Priya","source":"name and pronouns"},
  {"id":"gd-073","cat":"protect-and-affirm","type":"branch","hook":"A teacher or relative pressures your child to conform 'or else'.","options":[{"text":"Stand between your child and the pressure as their advocate","consequence":"Your child has a fierce protector.","outcome":"advocate","best":true},{"text":"Side with the adult to keep the peace","consequence":"Standing between your child and the pressure makes you their protector; siding with the adult leaves them exposed."}],"debrief":"Be the advocate who stands between your child and those pressuring them to conform, not the one who sides against them.","relearn":"Protect your child from pressure to conform; don't side with the adult against them to keep the peace.","persona":"Priya","source":"stand between"},
  {"id":"gd-074","cat":"protect-and-affirm","type":"sort","hook":"Sort: affirms and protects your child, or exposes them to harm?","items":[{"id":"a","text":"Backing them up publicly"},{"id":"b","text":"Mocking their expression at home"},{"id":"c","text":"Keeping home a safe space"},{"id":"d","text":"Letting others shame them unchecked"}],"bins":[{"id":"protect","label":"Affirms & protects"},{"id":"expose","label":"Exposes to harm"}],"key":{"a":"protect","b":"expose","c":"protect","d":"expose"},"relearn":"Backing them publicly and a safe home protect; mocking them or letting others shame them unchecked expose them to harm.","persona":"any","source":"protect or expose"},
  {"id":"gd-075","cat":"protect-and-affirm","type":"match","hook":"Match each pressure on your child to the protective response.","pairs":[{"left":"Bullying at school","right":"Advocate with the school, support at home"},{"left":"Relatives' disapproval","right":"Shield your child, hold your line"},{"left":"Pressure to mask","right":"Affirm that they can be themselves with you"}],"relearn":"Bullying, relatives' disapproval and pressure to mask each have a protective response that keeps your child safe.","persona":"Priya","source":"pressure to response"},
  {"id":"gd-076","cat":"your-own-journey","type":"role-play","hook":"You slipped and said something hurtful out of your own fear. You want to own and repair it.","setup":"Own and repair it:","yourLine":[{"text":"\"What I said came from my own fear, not the truth, I'm sorry, I love you and I'm learning.\"","best":true},{"text":"\"You'll understand when you're older why I said it.\""}],"relearn":"Owning that a hurtful comment came from your fear, not the truth, repairs it and models growth for your child.","persona":"Vikram","source":"own and repair"},
  {"id":"gd-077","cat":"your-own-journey","type":"branch","hook":"Your discomfort is tempting you to delay supporting your child 'until you're ready'.","options":[{"text":"Support them now and keep working on yourself in parallel","consequence":"Your child gets safety now, not someday.","outcome":"now","best":true},{"text":"Make your child wait for your comfort","consequence":"Supporting now while you work on yourself gives your child safety today; making them wait risks them while you catch up."}],"debrief":"Support your child now and work on your own comfort in parallel; don't make their safety wait for your readiness.","relearn":"Don't make your child wait for your comfort; support them now and keep growing alongside.","persona":"Vikram","source":"support now"},
  {"id":"gd-078","cat":"your-own-journey","type":"sort","hook":"Sort: moves your own journey forward kindly, or stalls it?","items":[{"id":"a","text":"Self-compassion for where you start"},{"id":"b","text":"Drowning in guilt and freezing"},{"id":"c","text":"Small, steady learning"},{"id":"d","text":"Demanding instant perfection of yourself"}],"bins":[{"id":"forward","label":"Moves forward"},{"id":"stall","label":"Stalls it"}],"key":{"a":"forward","b":"stall","c":"forward","d":"stall"},"relearn":"Self-compassion and steady learning move you forward; guilt-freezing and demanding instant perfection stall you.","persona":"Vikram","source":"forward or stall"},
  {"id":"gd-079","cat":"your-own-journey","type":"match","hook":"Match each parent feeling to a healthy way through it.","pairs":[{"left":"Fear for their future","right":"Learn how support changes the odds"},{"left":"Grief for an imagined path","right":"Feel it privately, embrace the real child"},{"left":"Confusion","right":"Ask questions and keep learning"}],"relearn":"Fear, grief and confusion each have a healthy way through that keeps the child supported while you process.","persona":"Vikram","source":"feeling to way through"},
  {"id":"gd-080","cat":"your-own-journey","type":"role-play","hook":"Your co-parent is struggling to accept your child. You want to bring them along, not into a fight.","setup":"Bring them along gently:","yourLine":[{"text":"\"I know this is hard for you, and our kid needs us both, let's learn and support them together.\"","best":true},{"text":"\"You're a bigot and you're ruining our child.\""}],"relearn":"Inviting a struggling co-parent to learn and support together moves them toward acceptance better than condemnation.","persona":"Meena","source":"bring co-parent along"},
  {"id":"gd-081","cat":"support-and-india","type":"role-play","hook":"You want to find help but don't know where to start. You picture making the first call.","setup":"Start simply:","yourLine":[{"text":"\"Hi, I'm a parent of a gender-diverse child and I want to support them well, can you help me?\"","best":true},{"text":"\"Hi, can you tell me how to change my child back to normal?\""}],"relearn":"A simple 'I want to support them well' opens the right, affirming kind of help for you and your child.","persona":"Divya","source":"first call"},
  {"id":"gd-082","cat":"support-and-india","type":"branch","hook":"A relative pushes you toward a 'cure' or conversion practice for your child.","options":[{"text":"Refuse it and seek affirming support instead","consequence":"You protect your child from real harm.","outcome":"refuse","best":true},{"text":"Try it to satisfy the family","consequence":"Refusing conversion practices and seeking affirming support protects your child; trying a 'cure' to please family causes real harm."}],"debrief":"Refuse conversion or 'cure' practices, which are discredited and harmful, and seek affirming support instead.","relearn":"Refuse 'cure' or conversion practices; they harm your child. Seek affirming support instead.","persona":"Priya","source":"refuse conversion"},
  {"id":"gd-083","cat":"support-and-india","type":"sort","hook":"Sort: an accurate point about dignity and rights in India, or a misconception?","items":[{"id":"a","text":"Dignity and equality are constitutional"},{"id":"b","text":"Trans people have no legal recognition"},{"id":"c","text":"Consensual same-sex relations are decriminalised"},{"id":"d","text":"There is zero support anywhere"}],"bins":[{"id":"accurate","label":"Accurate"},{"id":"wrong","label":"Misconception"}],"key":{"a":"accurate","b":"wrong","c":"accurate","d":"wrong"},"relearn":"Constitutional dignity and the decriminalisation of same-sex relations are accurate; 'no recognition' and 'zero support' are misconceptions.","persona":"Priya","source":"accurate or wrong"},
  {"id":"gd-084","cat":"support-and-india","type":"spot","hook":"Spot the move that makes you your child's safe place.","scene":[{"id":"a","text":"Leading with love and seeking affirming help","trick":false},{"id":"b","text":"Outing them to get advice","trick":true},{"id":"c","text":"Protecting their privacy and dignity","trick":false}],"why":"Leading with love, affirming help and protecting privacy make you a safe place; outing your child does not.","relearn":"Be your child's safe place by leading with love and affirming help while protecting their privacy, never outing them.","persona":"any","source":"safe place move"},
];

export const RAISING_GENDER_DIVERSE_KIDS: V2GameConfig = {
  gameId: "raising-gender-diverse-kids",
  title: "Raising Gender-Diverse Kids",
  greet: "Hey — it’s Lensy. If your child is LGBTQ+ or gender-diverse, the key fact: an accepting parent roughly halves the odds of suicidal thoughts. Lead with love.",
  scenarios: SCENARIOS,
  categories: [
    { id: "acceptance-is-protection", emoji: "🛡️", label: "Acceptance is protection" },
    { id: "understand", emoji: "📖", label: "Understand" },
    { id: "if-they-come-out", emoji: "🌈", label: "If they come out" },
    { id: "protect-and-affirm", emoji: "🫶", label: "Protect & affirm" },
    { id: "your-own-journey", emoji: "🧭", label: "Your own journey" },
    { id: "support-and-india", emoji: "🧰", label: "Support & help" },
  ],
  badge: {
    title: "Raising Gender-Diverse Kids 🏳️‍🌈",
    blurb: "An accepting parent is a child’s biggest protector — it roughly halves the odds of suicidal thoughts. You lead with love, never out them, and reject ‘cures’. 🫶",
  },
  helpLine: "An accepting parent halves an LGBTQ+ child’s odds of suicidal thoughts. ‘Cures’ harm. KIRAN 1800-599-0019, Tele-MANAS 14416, crisis 112. India: NALSA dignity.",
  helpLabel: "Get help · KIRAN 1800-599-0019",
  reassure: "An accepting parent roughly halves your child’s odds of suicidal thoughts. Lead with love; ‘cures’ harm. Help: KIRAN 1800-599-0019, Tele-MANAS 14416. 🫶",
  reassureCats: ["acceptance-is-protection", "if-they-come-out", "your-own-journey"],
};
