// Content for Reality Check (node g28, ages 12–15, Chapter 4) — NEW v2 build to GDD 28 (mechanic-embodying),
// the teen MEDIA-LITERACY peak (Thread G · Values, Rights & Media). "Real vs reel — see the curation, spot
// the trick, think for yourself." 85 researched, India-grounded, NON-EXPLICIT scenarios across the
// real-vs-reel → manipulation-files → media-love-sex (gated) → fakes-and-rights → finding-help →
// think-for-yourself arc, each encoded as one of the shared v2 play actions (spot / strike-rewrite / swipe /
// branch / reflect / sort / role-play / match) — no binary "tap the right card". Lead mechanics: spot (catch
// the trick ×16), strike-rewrite (bust the claim ×15), swipe (real or reel? ×13). Teaches: seeing curation
// (filters, highlight reels, ads), the manipulation toolkit, a GATED non-explicit media-&-sexuality module
// (films/songs ≠ real love; pornography is staged performance, NOT sex-ed; normal bodies vary; CURIOSITY IS
// NORMAL — no shame; learn from trusted sources), deepfakes & your rights (a fake nude of a minor is illegal
// CSAM, never the target's fault, reportable; verify the source), and the four critical questions. CALM,
// critical, never explicit. POCSO + BNS + IT-Rules aware. Routes to a trusted adult, cybercrime.gov.in / 1930,
// Childline 1098, plus a private Q&A. Builds on g16 (Crossroads) & g12/g17; sets up g36 (Decoded). Rendered
// by the shared engine (components/games/v2-engine.tsx). gameId "reality-check". DO NOT RENAME.

import type { Scenario, V2GameConfig } from "./v2-schema";

const SCENARIOS: Scenario[] = [
  // — Real vs reel: seeing the curation —
  {"id":"rc-001","cat":"real-vs-reel","type":"swipe","hook":"Real, or reel?","cue":"A friend's flawless 'just woke up like this' selfie","left":"Real & unedited","right":"Posed & filtered","answer":"right","relearn":"A 'effortless' selfie is usually posed, lit and filtered.","persona":"Riya","source":"media literacy / curation"},
  {"id":"rc-002","cat":"real-vs-reel","type":"swipe","hook":"Real, or reel?","cue":"An influencer's '24 hours in my perfect life' reel","left":"Their actual everyday","right":"A curated highlight","answer":"right","relearn":"A 'perfect life' reel is a highlight, not anyone's real day.","persona":"any","source":"media literacy / curation"},
  {"id":"rc-003","cat":"real-vs-reel","type":"swipe","hook":"Real, or reel?","cue":"A clip of a real news event from a trusted, named outlet","left":"Likely real","right":"Likely staged","answer":"left","relearn":"A named, reliable source reporting an event is likely real, still worth checking.","persona":"any","source":"media literacy"},
  {"id":"rc-004","cat":"real-vs-reel","type":"swipe","hook":"Real, or reel?","cue":"A 'we never fight, perfect couple' relationship account","left":"How relationships really are","right":"A curated image","answer":"right","relearn":"No real relationship is the conflict-free fantasy a feed performs.","persona":"Riya","source":"media literacy / relationships"},
  {"id":"rc-005","cat":"real-vs-reel","type":"swipe","hook":"Real, or reel?","cue":"A relatable post showing a messy, ordinary, unfiltered day","left":"Real & unfiltered","right":"Staged perfection","answer":"left","relearn":"Some posts are honestly ordinary, that's real, and refreshing.","persona":"any","source":"media literacy"},
  {"id":"rc-006","cat":"real-vs-reel","type":"swipe","hook":"Real, or reel?","cue":"A 'gym transformation' shot taken seconds apart with different light and pose","left":"Months of change","right":"A lighting-and-pose trick","answer":"right","relearn":"Many 'transformations' are minutes apart, just pose, light and angle.","persona":"Veer","source":"media literacy / body image"},
  {"id":"rc-007","cat":"real-vs-reel","type":"swipe","hook":"Real, or reel?","cue":"A travel photo with a faint '#ad · paid partnership' label","left":"Just sharing a trip","right":"Paid promotion","answer":"right","relearn":"A paid partnership is an ad, however casual the post looks.","persona":"any","source":"media literacy / ads"},
  {"id":"rc-008","cat":"real-vs-reel","type":"swipe","hook":"Real, or reel?","cue":"A candid group photo a friend posts of a genuinely fun evening","left":"A real moment","right":"Faked for likes","answer":"left","relearn":"Real moments exist online too; the skill is telling them apart, not cynicism.","persona":"any","source":"media literacy"},
  {"id":"rc-009","cat":"real-vs-reel","type":"spot","hook":"Spot what makes this 'spontaneous' photo staged.","scene":[{"id":"a","text":"A ring light and tripod just out of frame","trick":true},{"id":"b","text":"The friend is genuinely smiling","trick":false},{"id":"c","text":"It's the best of 40 retakes","trick":true}],"why":"The ring light and 40 retakes are the curation behind the 'candid' shot.","relearn":"'Spontaneous' posts are often carefully set up and re-shot.","persona":"any","source":"curation"},
  {"id":"rc-010","cat":"real-vs-reel","type":"spot","hook":"Spot the editing tells in this 'natural' photo.","scene":[{"id":"a","text":"A bent, warped line on the wall behind the waist","trick":true},{"id":"b","text":"The person looks happy","trick":false},{"id":"c","text":"Skin is smoothed to have no texture at all","trick":true}],"why":"Warped backgrounds and texture-free skin are edit tells.","relearn":"Warped lines and plastic-smooth skin reveal heavy editing.","persona":"Riya","source":"curation / body image"},
  {"id":"rc-011","cat":"real-vs-reel","type":"spot","hook":"Spot what's left out of this 'perfect life' feed.","scene":[{"id":"a","text":"Only wins, holidays and good-hair days","trick":true},{"id":"b","text":"They post most days","trick":false},{"id":"c","text":"No ordinary, boring or hard days, ever","trick":true}],"why":"A feed with zero ordinary days is curated; everyone has them.","relearn":"Feeds hide the ordinary and hard days everyone actually has.","persona":"any","source":"curation / comparison"},
  {"id":"rc-012","cat":"real-vs-reel","type":"strike-rewrite","hook":"\"If it's online, it's real.\"","myth":{"un":"If it's online, it's real.","re":"A feed is a curated, constructed highlight reel, not reality.","why":"The best angle, lucky shot and good day are selected; the rest is cut."},"relearn":"Online is a curated highlight reel, not unfiltered reality.","persona":"any","source":"media literacy"},
  {"id":"rc-013","cat":"real-vs-reel","type":"strike-rewrite","hook":"\"Everyone's life is better than mine, look at their feeds.\"","myth":{"un":"Everyone's life is better than mine; their feeds prove it.","re":"You're comparing your behind-the-scenes to their highlight reel.","why":"They edit out exactly the ordinary bits you're judging yourself on."},"relearn":"Comparing your real life to others' highlight reels isn't fair, or true.","persona":"Riya","source":"comparison / wellbeing"},
  {"id":"rc-014","cat":"real-vs-reel","type":"reflect","hook":"Lensy: once you see a feed as a highlight reel, does scrolling feel different?","prompt":"What do you think?","options":["Less envy","More aware","I compare less"],"affirm":"Seeing the curation takes the sting out of the comparison.","relearn":"Knowing feeds are curated protects you from unfair comparison.","persona":"any","source":"wellbeing"},
  {"id":"rc-015","cat":"real-vs-reel","type":"reflect","hook":"Lensy: one healthy move when a feed makes you feel low?","prompt":"Pick one.","options":["Follow more real, honest accounts","Take a scroll break","Talk to a friend about it"],"affirm":"Curating your feed and taking breaks are real, kind self-care, far better than comparing.","relearn":"You can curate your feed and take breaks to protect how you feel.","persona":"any","source":"wellbeing (healthy coping)"},
  // — The manipulation files: spotting the tricks —
  {"id":"rc-016","cat":"manipulation-files","type":"spot","hook":"Spot the disguised ad.","scene":[{"id":"a","text":"A 'casual' post raving about one exact product","trick":true},{"id":"b","text":"It's a nice photo","trick":false},{"id":"c","text":"Tiny '#ad / paid partnership' text at the bottom","trick":true}],"why":"A glowing single-product post with a paid-partnership tag is an ad.","relearn":"Disguised ads look like normal posts; check for the paid tag.","persona":"any","source":"undisclosed sponsorship"},
  {"id":"rc-017","cat":"manipulation-files","type":"spot","hook":"Spot the clickbait trick.","scene":[{"id":"a","text":"\"You WON'T believe what happened next!!\"","trick":true},{"id":"b","text":"A headline about a real topic","trick":false},{"id":"c","text":"The payoff is nothing like the headline promised","trick":true}],"why":"Outrage/curiosity headlines that don't deliver are clickbait engineered for clicks.","relearn":"Clickbait sells the click with a promise it doesn't keep.","persona":"any","source":"clickbait"},
  {"id":"rc-018","cat":"manipulation-files","type":"spot","hook":"Spot the misinformation tell.","scene":[{"id":"a","text":"A shocking 'fact' with no source named","trick":true},{"id":"b","text":"It's been forwarded many times","trick":false},{"id":"c","text":"No reliable outlet is reporting it anywhere","trick":true}],"why":"A sourceless, much-forwarded claim no reliable outlet confirms is a misinformation red flag.","relearn":"No source + no reliable outlet confirming = likely misinformation.","persona":"any","source":"misinformation / India forwards"},
  {"id":"rc-019","cat":"manipulation-files","type":"spot","hook":"Spot the out-of-context trick.","scene":[{"id":"a","text":"A real old photo relabelled as today's news","trick":true},{"id":"b","text":"The image is genuine","trick":false},{"id":"c","text":"It's from a different year and place entirely","trick":true}],"why":"A real image with a false caption is a classic out-of-context fake.","relearn":"A real photo can still lie if the caption rips it out of context.","persona":"any","source":"misinformation"},
  {"id":"rc-020","cat":"manipulation-files","type":"spot","hook":"Spot the influencer-perfection machine.","scene":[{"id":"a","text":"Flawless skin, body and home in every post","trick":true},{"id":"b","text":"They seem friendly","trick":false},{"id":"c","text":"Filters, edits and sponsors behind every 'effortless' shot","trick":true}],"why":"Relentless perfection is manufactured by filters, edits and sponsorship.","relearn":"'Effortless perfection' is a manufactured, sponsored product.","persona":"Riya","source":"influencer perfection"},
  {"id":"rc-021","cat":"manipulation-files","type":"spot","hook":"Spot the engagement bait.","scene":[{"id":"a","text":"\"Like and share or you don't care!\"","trick":true},{"id":"b","text":"A photo of a sunset","trick":false},{"id":"c","text":"Manufactured guilt to force a share","trick":true}],"why":"Guilt-tripping you into sharing is engagement bait, not a real cause.","relearn":"Guilt-trip 'share or else' posts are engineered to spread, not to matter.","persona":"any","source":"engagement bait"},
  {"id":"rc-022","cat":"manipulation-files","type":"sort","hook":"Sort: a disguised ad, or an organic post?","items":[{"id":"a","text":"'Loved this!' with a paid-partnership tag"},{"id":"b","text":"A friend's holiday snaps, no products"},{"id":"c","text":"A code 'use SAVE10 at checkout'"},{"id":"d","text":"A meme about Mondays"}],"bins":[{"id":"ad","label":"An ad"},{"id":"organic","label":"Organic"}],"key":{"a":"ad","b":"organic","c":"ad","d":"organic"},"relearn":"Paid tags and discount codes mark ads; check before you trust a 'rave'.","persona":"any","source":"ads"},
  {"id":"rc-023","cat":"manipulation-files","type":"sort","hook":"Sort: a reliable signal, or a manipulation?","items":[{"id":"a","text":"A named, checkable source"},{"id":"b","text":"ALL-CAPS outrage and no source"},{"id":"c","text":"Several reliable outlets agreeing"},{"id":"d","text":"'Forward before they delete this!'"}],"bins":[{"id":"reliable","label":"Reliable signal"},{"id":"manip","label":"Manipulation"}],"key":{"a":"reliable","b":"manip","c":"reliable","d":"manip"},"relearn":"Named sources and corroboration are reliable; urgency and outrage are manipulation.","persona":"any","source":"media literacy"},
  {"id":"rc-024","cat":"manipulation-files","type":"sort","hook":"Sort the trick to its family.","items":[{"id":"a","text":"Ad dressed as a normal post"},{"id":"b","text":"'You won't believe...' headline"},{"id":"c","text":"Old photo, today's caption"},{"id":"d","text":"A face swapped into a fake video"}],"bins":[{"id":"sell","label":"Selling you something"},{"id":"fool","label":"Fooling you with fakes"}],"key":{"a":"sell","b":"sell","c":"fool","d":"fool"},"relearn":"Some tricks sell to you; others fool you with fakes, both are spottable.","persona":"any","source":"taxonomy"},
  {"id":"rc-025","cat":"manipulation-files","type":"sort","hook":"Sort: worth trusting, or check first?","items":[{"id":"a","text":"A health 'cure' from an anonymous forward"},{"id":"b","text":"Guidance from a recognised health body"},{"id":"c","text":"A miracle claim selling a product"},{"id":"d","text":"A report carried by several outlets"}],"bins":[{"id":"check","label":"Check first / distrust"},{"id":"trust","label":"More trustworthy"}],"key":{"a":"check","b":"trust","c":"check","d":"trust"},"relearn":"Anonymous forwards and miracle sales need checking; recognised bodies and corroboration earn more trust.","persona":"any","source":"misinformation / health"},
  {"id":"rc-026","cat":"manipulation-files","type":"swipe","hook":"Trick, or not?","cue":"A countdown 'only 2 left, buy in 5 minutes!'","left":"Genuine scarcity","right":"Pressure tactic","answer":"right","relearn":"Fake urgency and scarcity are pressure tactics to stop you thinking.","persona":"any","source":"persuasion tactics"},
  {"id":"rc-027","cat":"manipulation-files","type":"swipe","hook":"Trick, or not?","cue":"A 'news' site you've never heard of with one wild story","left":"A real outlet","right":"Likely a fake-news site","answer":"right","relearn":"Unknown 'news' sites with one viral shocker are often fakes.","persona":"any","source":"misinformation"},
  {"id":"rc-028","cat":"manipulation-files","type":"swipe","hook":"Trick, or not?","cue":"A celebrity 'endorsing' a crypto scheme in an odd-looking video","left":"A real endorsement","right":"Likely a deepfake scam","answer":"right","relearn":"Celebrity 'get rich' videos are a classic deepfake scam.","persona":"Veer","source":"deepfake scams"},
  {"id":"rc-029","cat":"manipulation-files","type":"match","hook":"Match the trick to the tell that exposes it.","pairs":[{"left":"Disguised ad","right":"A paid-partnership tag"},{"left":"Clickbait","right":"Headline the story never pays off"},{"left":"Misinformation","right":"No source, no outlet confirms"}],"relearn":"Every manipulation has a tell; learn the tell and it stops working.","persona":"any","source":"media literacy"},
  {"id":"rc-030","cat":"manipulation-files","type":"match","hook":"Match the move to what it's really doing.","pairs":[{"left":"'Like or you don't care'","right":"Guilt-tripping a share"},{"left":"'Only 2 left!'","right":"Fake-urgency pressure"},{"left":"'They don't want you to see this'","right":"Bait dressed as forbidden truth"}],"relearn":"Naming the tactic, guilt, urgency, forbidden-truth, defuses it.","persona":"any","source":"persuasion"},
  {"id":"rc-031","cat":"manipulation-files","type":"spot","hook":"Spot the genuinely useful post (not a trick).","scene":[{"id":"a","text":"A clear how-to from a named, qualified person","trick":false},{"id":"b","text":"A 'doctors hate this one trick' miracle","trick":true},{"id":"c","text":"A sponsored 'cure' with a discount code","trick":true}],"why":"Real value comes from named, qualified sources, not miracle-cure bait.","relearn":"Not everything is a trick; named, qualified help is the real thing.","persona":"any","source":"balance"},
  // — Love, romance & sex on screen (non-explicit) —
  {"id":"rc-032","cat":"media-love-sex","type":"strike-rewrite","hook":"\"Films and songs show what real love is like.\"","myth":{"un":"Films and songs show what real love is really like.","re":"They show a dramatic fantasy script; real love is two-way, ordinary and unglamorous too.","why":"Grand gestures and 'mind-reading' partners are writing, not life."},"relearn":"Screen romance is a fantasy script, not a model for real love.","persona":"Riya","source":"media & relationships (KC7)"},
  {"id":"rc-033","cat":"media-love-sex","type":"strike-rewrite","hook":"\"A real partner should just know what I want, like in the movies.\"","myth":{"un":"A real partner should just 'know' what I want, like on screen.","re":"Real relationships run on talking and asking, not mind-reading.","why":"The 'they just knew' trope sets real partners up to fail."},"relearn":"Real intimacy needs communication; mind-reading is a movie myth.","persona":"any","source":"media & relationships"},
  {"id":"rc-033b","cat":"media-love-sex","type":"swipe","hook":"Realistic, or a screen fantasy?","cue":"Two people talk about what they're comfortable with before anything","left":"Realistic & healthy","right":"Screen fantasy","answer":"left","relearn":"Talking and checking in is what real, respectful intimacy looks like, rarely shown on screen.","persona":"any","source":"media & relationships"},
  {"id":"rc-034","cat":"media-love-sex","type":"strike-rewrite","hook":"\"Pornography shows what real sex is like.\"","myth":{"un":"Pornography shows what real sex is like.","re":"It's staged performance by paid actors, not real sex.","why":"It's scripted, edited and filmed for views, like any other media."},"relearn":"Pornography is staged performance, not a picture of real sex.","persona":"any","source":"porn literacy (Rothman/Frontiers)"},
  {"id":"rc-035","cat":"media-love-sex","type":"strike-rewrite","hook":"\"Porn is a good way to learn about sex.\"","myth":{"un":"Pornography is a good way to learn about sex.","re":"It isn't sex education; it usually shows no real consent, communication or care.","why":"Accurate, trusted sources are how you actually learn."},"relearn":"Pornography is not sex education; trusted sources are.","persona":"Veer","source":"porn literacy"},
  {"id":"rc-036","cat":"media-love-sex","type":"strike-rewrite","hook":"\"Bodies in media and porn are what normal bodies look like.\"","myth":{"un":"The bodies in media and porn are what 'normal' looks like.","re":"They're selected, filtered and edited; real bodies vary hugely and that's normal.","why":"It's a casting and editing choice, not a measure of you."},"relearn":"Real bodies vary; edited, selected ones aren't the standard.","persona":"Riya","source":"porn literacy / body image (links g21)"},
  {"id":"rc-037","cat":"media-love-sex","type":"strike-rewrite","hook":"\"Everyone watches it, so it must be harmless and accurate.\"","myth":{"un":"Loads of people watch it, so it must be harmless and accurate.","re":"Common doesn't mean accurate; relying on it can distort what you expect.","why":"Popularity isn't truth, here as anywhere in media."},"relearn":"Common doesn't mean accurate; popularity isn't a reality check.","persona":"any","source":"porn literacy"},
  {"id":"rc-038","cat":"media-love-sex","type":"strike-rewrite","hook":"\"If you've seen it, something's wrong with you.\"","myth":{"un":"If you've come across it, something's wrong with you.","re":"Curiosity is normal and many teens encounter it; what matters is thinking critically about it.","why":"Shame helps no one; understanding does."},"relearn":"Curiosity is normal; what matters is knowing it isn't real, no shame.","persona":"Counsellor","source":"porn literacy / no shame"},
  {"id":"rc-039","cat":"media-love-sex","type":"strike-rewrite","hook":"\"Real partners should look and act like people on screen.\"","myth":{"un":"A real partner should look and act like people on screen.","re":"Expecting that sets real relationships up to disappoint; real intimacy is respect and communication.","why":"Comparing a real person to a performance is unfair to both of you."},"relearn":"Expecting screen 'performance' from real partners only breeds disappointment.","persona":"any","source":"porn literacy / relationships"},
  {"id":"rc-040","cat":"media-love-sex","type":"sort","hook":"Sort: a realistic idea of intimacy, or a media fantasy?","items":[{"id":"a","text":"Partners talk about what they're okay with"},{"id":"b","text":"It's always perfect with zero awkwardness"},{"id":"c","text":"Respect and consent matter most"},{"id":"d","text":"One partner just 'knows' everything"}],"bins":[{"id":"real","label":"Realistic"},{"id":"fantasy","label":"Media fantasy"}],"key":{"a":"real","b":"fantasy","c":"real","d":"fantasy"},"relearn":"Real intimacy is talk, respect and consent; the flawless mind-reading version is fantasy.","persona":"any","source":"media & relationships"},
  {"id":"rc-041","cat":"media-love-sex","type":"sort","hook":"Sort: what pornography is, vs what it isn't.","items":[{"id":"a","text":"Paid actors and a script"},{"id":"b","text":"A model for real relationships"},{"id":"c","text":"Edited and filmed for views"},{"id":"d","text":"Reliable sex education"}],"bins":[{"id":"is","label":"What it is"},{"id":"isnt","label":"What it isn't"}],"key":{"a":"is","b":"isnt","c":"is","d":"isnt"},"relearn":"Pornography is paid, scripted, edited performance, not a relationship model or sex-ed.","persona":"any","source":"porn literacy"},
  {"id":"rc-042","cat":"media-love-sex","type":"sort","hook":"Sort: a trusted way to learn about bodies and sex, or not?","items":[{"id":"a","text":"A qualified health source or trusted adult"},{"id":"b","text":"Pornography"},{"id":"c","text":"Your school's RSE / a doctor"},{"id":"d","text":"Random viral forwards"}],"bins":[{"id":"trusted","label":"Trusted"},{"id":"not","label":"Not trusted"}],"key":{"a":"trusted","b":"not","c":"trusted","d":"not"},"relearn":"Learn from qualified sources and trusted adults, not porn or forwards.","persona":"any","source":"finding accurate info"},
  {"id":"rc-043","cat":"media-love-sex","type":"reflect","hook":"Lensy: it's fine to feel curious, and fine to close something that makes you uncomfortable. Okay?","prompt":"What do you think?","options":["Yes","Good to know","That helps"],"affirm":"Curiosity is human, and you're always allowed to look away.","relearn":"Curiosity is normal and you can always close what feels uncomfortable.","persona":"any","source":"agency / no shame"},
  {"id":"rc-044","cat":"media-love-sex","type":"reflect","hook":"Lensy: if something you saw online worries or confuses you, what's a good move?","prompt":"Pick one.","options":["Ask a trusted adult","Use the private Q&A","Check a reliable source"],"affirm":"Asking is the smart, brave move, no question is too awkward for a trusted adult or the Q&A.","relearn":"If something online worries you, ask a trusted adult or use the private Q&A.","persona":"Counsellor","source":"finding help"},
  {"id":"rc-045","cat":"media-love-sex","type":"reflect","hook":"Lensy: knowing screen sex and romance are performances, does real life feel less pressured?","prompt":"What do you think?","options":["Yes","Less pressure","More realistic"],"affirm":"Dropping the performance standard makes real relationships kinder and saner.","relearn":"Knowing it's a performance frees real relationships from an impossible standard.","persona":"any","source":"wellbeing"},
  // — Fakes & your rights —
  {"id":"rc-046","cat":"fakes-and-rights","type":"strike-rewrite","hook":"\"You can always spot a deepfake by the weird hands.\"","myth":{"un":"You can always spot a deepfake, just look for weird hands.","re":"Fakes keep improving and visual 'tells' often fail; verify the source instead.","why":"It's an arms race, glitch-spotting alone isn't reliable anymore."},"relearn":"Don't rely on glitches; verify the source to catch fakes.","persona":"Veer","source":"deepfakes 2026 (MIT/ESET)"},
  {"id":"rc-047","cat":"fakes-and-rights","type":"strike-rewrite","hook":"\"If a photo looks real, it must be real.\"","myth":{"un":"If a photo or video looks real, it must be real.","re":"AI can make convincing fakes; 'looks real' is no longer proof.","why":"Seeing is no longer simply believing."},"relearn":"'Looks real' isn't proof; convincing fakes exist, check before trusting.","persona":"any","source":"deepfakes 2026"},
  {"id":"rc-048","cat":"fakes-and-rights","type":"strike-rewrite","hook":"\"Making a fake nude of someone is just a prank.\"","myth":{"un":"Making a fake 'nude' of someone is just a prank.","re":"It's harmful and illegal; a fake of a minor is child sexual abuse material.","why":"It causes real harm to a real person, never a joke."},"relearn":"Fake or non-consensual sexual images are illegal and seriously harmful, not a prank.","persona":"Counsellor","source":"NCII / POCSO / BNS"},
  {"id":"rc-049","cat":"fakes-and-rights","type":"strike-rewrite","hook":"\"If someone's image is faked, nothing can be done.\"","myth":{"un":"If someone's image is faked or leaked, nothing can be done.","re":"It can be reported and taken down fast; the law is on the target's side.","why":"India's portal mandates rapid removal of non-consensual imagery."},"relearn":"Faked or leaked images can be reported and removed; help exists.","persona":"Counsellor","source":"cybercrime.gov.in / IT Rules"},
  {"id":"rc-050","cat":"fakes-and-rights","type":"branch","hook":"A wild photo is going viral. Before you believe or share it, what do you do?","options":[{"text":"Verify the source, reverse-image search, check reliable outlets","consequence":"You find it's old/fake and don't spread it.","outcome":"verified","best":true},{"text":"Share it because it looks real","consequence":"Verify the source first; 'looks real' isn't proof."}],"debrief":"With fakes this good, source-checking, not eyeballing, is the real skill.","relearn":"Verify the source before believing or sharing; don't rely on how it looks.","persona":"any","source":"deepfakes 2026 / verify source"},
  {"id":"rc-051","cat":"fakes-and-rights","type":"branch","hook":"Someone shares a fake, embarrassing image of a classmate in a group.","options":[{"text":"Don't forward it; tell them to delete it and report it","consequence":"You stop the spread and protect the classmate.","outcome":"upstander","best":true},{"text":"Forward it for a laugh","consequence":"Forwarding spreads harm and can be illegal; never forward it."}],"debrief":"Not forwarding is the single most protective thing a bystander can do.","relearn":"Never forward a fake or private image; stopping the spread protects people.","persona":"Veer","source":"NCII / bystander"},
  {"id":"rc-052","cat":"fakes-and-rights","type":"branch","hook":"A stranger online asks you to send a private photo of yourself.","options":[{"text":"Don't send it; block, and tell a trusted adult","consequence":"You stay safe and a grown-up can help.","outcome":"safe","best":true},{"text":"Send it so they'll leave you alone","consequence":"Never send private images; block and tell a trusted adult."}],"debrief":"Requests like this are a red flag; blocking and telling an adult is right.","relearn":"Never send private images to anyone online; block and tell a trusted adult.","persona":"Counsellor","source":"online safety / POCSO"},
  {"id":"rc-053","cat":"fakes-and-rights","type":"branch","hook":"You realise a 'news' image you almost shared is an out-of-context fake.","options":[{"text":"Don't share, and gently correct anyone who did","consequence":"You slow the misinformation down.","outcome":"responsible","best":true},{"text":"Share anyway; people can decide for themselves","consequence":"Knowingly sharing a fake spreads it; correct it instead."}],"debrief":"Choosing not to spread, and correcting kindly, is real digital citizenship.","relearn":"Don't share what you know is fake; correcting it helps everyone.","persona":"any","source":"misinformation / citizenship"},
  {"id":"rc-054","cat":"fakes-and-rights","type":"branch","hook":"A friend is panicking because a faked image of them is circulating.","options":[{"text":"Support them, save evidence, and report via cybercrime.gov.in / 1098","consequence":"They feel less alone and the report gets help moving.","outcome":"caring","best":true},{"text":"Tell them to just ignore it","consequence":"Support them and help them report; don't leave them to 'ignore it'."}],"debrief":"Belief, evidence and the right report channel are what actually help.","relearn":"Support a friend, save evidence, and report to cybercrime.gov.in / 1098.","persona":"Counsellor","source":"reporting (verified)"},
  {"id":"rc-055","cat":"fakes-and-rights","type":"spot","hook":"Spot the safer verification move.","scene":[{"id":"a","text":"Reverse-image search the photo's origin","trick":false},{"id":"b","text":"Just trust it because a friend sent it","trick":true},{"id":"c","text":"See if reliable outlets report the same thing","trick":false}],"why":"Reverse-search and checking reliable outlets verify; 'a friend sent it' doesn't.","relearn":"Verify with reverse-search and reliable outlets, not just who sent it.","persona":"any","source":"verify source"},
  {"id":"rc-056","cat":"fakes-and-rights","type":"spot","hook":"Spot the deepfake-video clues (helpful, but not proof on their own).","scene":[{"id":"a","text":"The face barely blinks, then blinks oddly","trick":true},{"id":"b","text":"It's a short clip","trick":false},{"id":"c","text":"Lighting and shadows flicker between frames","trick":true}],"why":"Odd blinking and flickering light are clues, but always confirm by checking the source.","relearn":"Visual clues can hint at a fake, but verifying the source is what confirms it.","persona":"any","source":"deepfakes 2026"},
  {"id":"rc-057","cat":"fakes-and-rights","type":"match","hook":"Match the right to what protects it online.","pairs":[{"left":"Right to your own image","right":"Laws against non-consensual images"},{"left":"Right to be safe online","right":"Report & takedown channels"},{"left":"Right to say no to sending","right":"Consent"}],"relearn":"Your image, safety and 'no' are rights, backed by consent, law and reporting.","persona":"any","source":"rights / law"},
  {"id":"rc-058","cat":"fakes-and-rights","type":"sort","hook":"Sort: legal and okay, or harmful and illegal?","items":[{"id":"a","text":"Sharing a friend's photo with their okay"},{"id":"b","text":"Making a fake sexual image of someone"},{"id":"c","text":"Forwarding a leaked private image"},{"id":"d","text":"Reporting a fake to get it removed"}],"bins":[{"id":"ok","label":"Okay"},{"id":"illegal","label":"Harmful / illegal"}],"key":{"a":"ok","b":"illegal","c":"illegal","d":"ok"},"relearn":"Making or forwarding fake/private sexual images is illegal; reporting them is right.","persona":"any","source":"NCII / POCSO / BNS"},
  // — Find help, report, protect —
  {"id":"rc-059","cat":"finding-help","type":"role-play","hook":"A friend got a scary message demanding a photo or 'else'.","setup":"Reassure and guide them. Say:","yourLine":[{"text":"\"This isn't your fault. Don't send anything, let's tell a trusted adult and report it.\"","best":true},{"text":"\"Just give them what they want so they stop.\""}],"relearn":"Tell a friend being threatened: not your fault, don't comply, report it.","persona":"Counsellor","source":"sextortion / reporting"},
  {"id":"rc-060","cat":"finding-help","type":"role-play","hook":"A friend is embarrassed to report a fake image.","setup":"Encourage them. Say:","yourLine":[{"text":"\"You did nothing wrong, the person who made it did. Reporting it is how we stop it.\"","best":true},{"text":"\"Maybe just hope it goes away.\""}],"relearn":"Reassure: the maker is at fault, and reporting is how harm is stopped.","persona":"any","source":"no shame / reporting"},
  {"id":"rc-061","cat":"finding-help","type":"role-play","hook":"You want to tell a younger sibling how to handle something scary online.","setup":"Keep it simple. Say:","yourLine":[{"text":"\"If anything online scares you, don't reply, screenshot it, and come tell me or an adult.\"","best":true},{"text":"\"Just deal with it yourself.\""}],"relearn":"Teach: don't reply, save a screenshot, and tell a trusted adult.","persona":"any","source":"mentoring / safety"},
  {"id":"rc-062","cat":"finding-help","type":"role-play","hook":"You need to flag a serious online problem to a trusted adult.","setup":"Open the conversation. Say:","yourLine":[{"text":"\"Something online is worrying me and I need help, can we talk?\"","best":true},{"text":"Say nothing and hope it passes"}],"relearn":"Naming it plainly to a trusted adult is how you get real help.","persona":"any","source":"finding help"},
  {"id":"rc-063","cat":"finding-help","type":"role-play","hook":"A friend says 'reporting never does anything'.","setup":"Offer the facts, kindly. Say:","yourLine":[{"text":"\"Actually the cybercrime portal has to take these down fast, it's worth reporting.\"","best":true},{"text":"\"Yeah, you're probably right, forget it.\""}],"relearn":"Reporting works: non-consensual images must be removed quickly.","persona":"Counsellor","source":"IT Rules / reporting"},
  {"id":"rc-064","cat":"finding-help","type":"branch","hook":"You've seen something online that's clearly child sexual abuse material.","options":[{"text":"Don't share or save it; tell a trusted adult and report it","consequence":"It reaches people who can act; you stay safe and lawful.","outcome":"right","best":true},{"text":"Send it to a friend to show how bad it is","consequence":"Never share it; report to a trusted adult / authorities instead."}],"debrief":"CSAM is a grave crime; the only move is report, never share.","relearn":"Never share CSAM; report it to a trusted adult and authorities at once.","persona":"Counsellor","source":"POCSO / safeguarding"},
  {"id":"rc-065","cat":"finding-help","type":"branch","hook":"You're not sure if something you saw is 'serious enough' to tell someone.","options":[{"text":"Tell a trusted adult anyway and let them help judge","consequence":"Better safe; they can guide you.","outcome":"safe","best":true},{"text":"Stay quiet in case it's nothing","consequence":"When unsure, tell a trusted adult; they can help you judge."}],"debrief":"You never have to decide alone whether something's serious.","relearn":"If unsure, tell a trusted adult; you don't have to judge it alone.","persona":"any","source":"finding help"},
  {"id":"rc-066","cat":"finding-help","type":"branch","hook":"A scammy message says you've 'won' a prize and must click a link now.","options":[{"text":"Don't click; it's a scam, delete or report it","consequence":"You dodge the trap.","outcome":"safe","best":true},{"text":"Click to claim before it expires","consequence":"Urgent 'you won' links are scams; don't click, report them."}],"debrief":"Surprise wins and urgent links are classic scams, never click.","relearn":"Don't click 'you won, act now' links; they're scams, report them.","persona":"any","source":"scams"},
  {"id":"rc-067","cat":"finding-help","type":"match","hook":"Match the problem to where to report it (India).","pairs":[{"left":"A fake/non-consensual image","right":"cybercrime.gov.in / 1930"},{"left":"Anyone under 18 at risk","right":"Childline 1098"},{"left":"Something that scares you","right":"A trusted adult"}],"relearn":"India routes: cybercrime.gov.in / 1930, Childline 1098, and a trusted adult.","persona":"Counsellor","source":"helplines (verified)"},
  {"id":"rc-068","cat":"finding-help","type":"sort","hook":"Sort: a safe response to online trouble, or a risky one?","items":[{"id":"a","text":"Screenshot as evidence, then report"},{"id":"b","text":"Reply and argue with the sender"},{"id":"c","text":"Tell a trusted adult"},{"id":"d","text":"Send the demanded photo"}],"bins":[{"id":"safe","label":"Safe"},{"id":"risky","label":"Risky"}],"key":{"a":"safe","b":"risky","c":"safe","d":"risky"},"relearn":"Save evidence and tell an adult; don't argue with or comply with bad actors.","persona":"any","source":"online safety"},
  {"id":"rc-069","cat":"finding-help","type":"reflect","hook":"Lensy: knowing exactly who to tell, do you feel readier to handle online trouble?","prompt":"What do you think?","options":["Yes","I know who to call","Readier"],"affirm":"Knowing the routes, an adult, 1098, the cyber portal, turns worry into action.","relearn":"Knowing the help routes makes online trouble manageable, not scary.","persona":"any","source":"finding help"},
  {"id":"rc-070","cat":"finding-help","type":"reflect","hook":"Lensy: the bravest online move is usually...","prompt":"Pick one.","options":["Telling someone","Not forwarding it","Asking for help"],"affirm":"Telling, not forwarding, and asking for help are the strong, grown-up moves.","relearn":"Telling someone and asking for help are the bravest online moves.","persona":"any","source":"agency"},
  // — Think for yourself: the four questions —
  {"id":"rc-071","cat":"think-for-yourself","type":"spot","hook":"Apply Q1, 'Who made this and why?'. Spot the agenda.","scene":[{"id":"a","text":"A 'study' pushed by the company that profits from it","trick":true},{"id":"b","text":"It has charts","trick":false},{"id":"c","text":"No independent source backs it","trick":true}],"why":"Who-benefits and no independent backing reveal the agenda behind the 'study'.","relearn":"Ask who made it and why; follow who benefits.","persona":"any","source":"critical questions / Q1"},
  {"id":"rc-072","cat":"think-for-yourself","type":"spot","hook":"Apply Q2, 'What's left out?'. Spot the missing piece.","scene":[{"id":"a","text":"A 'before/after' with no timeframe or method","trick":true},{"id":"b","text":"Bright, confident captions","trick":false},{"id":"c","text":"No mention of edits, lighting or product paid-for","trick":true}],"why":"What's omitted, time, method, edits, sponsorship, is where the truth hides.","relearn":"Ask what's left out; omissions often hide the real story.","persona":"Riya","source":"critical questions / Q2"},
  {"id":"rc-073","cat":"think-for-yourself","type":"spot","hook":"Apply Q3, 'Is it staged, sponsored or faked?'. Spot the flag.","scene":[{"id":"a","text":"A glowing single-product 'honest review'","trick":true},{"id":"b","text":"It's well filmed","trick":false},{"id":"c","text":"A gifting/paid disclosure in the description","trick":true}],"why":"A paid or gifting disclosure tells you the 'honest review' is sponsored.","relearn":"Ask if it's staged, sponsored or faked; check for disclosures.","persona":"any","source":"critical questions / Q3"},
  {"id":"rc-074","cat":"think-for-yourself","type":"spot","hook":"Apply Q4, 'Does a reliable source confirm it?'. Spot the check.","scene":[{"id":"a","text":"Several recognised outlets report the same facts","trick":false},{"id":"b","text":"It's a dramatic claim","trick":false},{"id":"c","text":"...but only one anonymous post is the origin","trick":true}],"why":"One anonymous origin with no corroboration fails the reliable-source check.","relearn":"Ask if a reliable source confirms it; one anonymous post isn't enough.","persona":"any","source":"critical questions / Q4"},
  {"id":"rc-075","cat":"think-for-yourself","type":"reflect","hook":"Lensy: the four questions, who made it & why, what's left out, staged/sponsored/faked, reliably confirmed. Useful kit?","prompt":"What do you think?","options":["Yes","I'll use them","Powerful"],"affirm":"Four quick questions, and almost nothing can fool you.","relearn":"The four questions are a toolkit you can apply to anything online.","persona":"any","source":"critical questions"},
  {"id":"rc-076","cat":"think-for-yourself","type":"reflect","hook":"Lensy: which question will you use most?","prompt":"Pick one.","options":["Who made it and why?","What's left out?","Does a reliable source confirm it?"],"affirm":"Whichever you reach for, you're thinking, not just absorbing.","relearn":"Reaching for any of the four questions makes you an active, not passive, viewer.","persona":"any","source":"critical questions"},
  {"id":"rc-077","cat":"think-for-yourself","type":"reflect","hook":"Lensy: being hard to fool isn't about cynicism, it's about checking. Agree?","prompt":"What do you think?","options":["Yes","Check, don't sneer","Makes sense"],"affirm":"Healthy skepticism checks; it doesn't just disbelieve everything.","relearn":"Media literacy is checking, not blanket cynicism.","persona":"any","source":"balance"},
  {"id":"rc-078","cat":"think-for-yourself","type":"branch","hook":"A forwarded message says a scary thing will happen tomorrow. What's your move?","options":[{"text":"Run the four questions before reacting or forwarding","consequence":"You find no reliable source and don't spread panic.","outcome":"critical","best":true},{"text":"Forward it to warn everyone","consequence":"Check it with the four questions before forwarding a scare."}],"debrief":"The four questions turn a viral panic into a quick, calm check.","relearn":"Run the four questions before reacting to or forwarding a scare.","persona":"any","source":"critical thinking / India forwards"},
  {"id":"rc-079","cat":"think-for-yourself","type":"branch","hook":"You catch yourself feeling rubbish after comparing to perfect feeds.","options":[{"text":"Remind yourself it's a highlight reel, and curate or take a break","consequence":"The feeling loosens; you feel more yourself.","outcome":"healthy","best":true},{"text":"Keep scrolling and comparing","consequence":"Name the highlight-reel trick and take a break; don't spiral."}],"debrief":"Naming the curation and stepping back is healthy, kind self-care.","relearn":"When comparison bites, name the highlight reel and take a break.","persona":"Riya","source":"wellbeing (healthy coping)"},
  {"id":"rc-080","cat":"think-for-yourself","type":"branch","hook":"Friends are sharing a juicy rumour screenshot about someone you know.","options":[{"text":"Don't pass it on; it's unverified and could hurt someone","consequence":"You break the chain and protect a person.","outcome":"responsible","best":true},{"text":"Share it, everyone else is","consequence":"Unverified and harmful, don't pass it on."}],"debrief":"'Everyone's sharing it' is never a reason; verify, and protect people.","relearn":"Don't pass on unverified, hurtful screenshots, even if everyone is.","persona":"any","source":"citizenship"},
  {"id":"rc-081","cat":"think-for-yourself","type":"role-play","hook":"A friend is upset by a 'perfect life' account.","setup":"Reframe it for them. Say:","yourLine":[{"text":"\"That's their highlight reel, not their real life, don't measure yourself against an edit.\"","best":true},{"text":"\"Yeah, their life is just better than ours.\""}],"relearn":"Help a friend see a feed as a highlight reel, not a measuring stick.","persona":"Riya","source":"comparison / support"},
  {"id":"rc-082","cat":"think-for-yourself","type":"sort","hook":"Sort: an active, critical viewer, or a passive one?","items":[{"id":"a","text":"Asks who made it and why"},{"id":"b","text":"Believes whatever's on top of the feed"},{"id":"c","text":"Checks a second reliable source"},{"id":"d","text":"Forwards before reading"}],"bins":[{"id":"active","label":"Critical viewer"},{"id":"passive","label":"Passive viewer"}],"key":{"a":"active","b":"passive","c":"active","d":"passive"},"relearn":"A critical viewer questions and checks; a passive one just absorbs and forwards.","persona":"any","source":"media literacy"},
  {"id":"rc-083","cat":"think-for-yourself","type":"swipe","hook":"Would a critical viewer trust this at face value?","cue":"A miracle health claim, one anonymous source, urgent 'share now'","left":"Trust it","right":"Check it first","answer":"right","relearn":"Miracle claim + anonymous + urgency = check before trusting.","persona":"any","source":"critical thinking"},
  {"id":"rc-084","cat":"think-for-yourself","type":"strike-rewrite","hook":"\"I'm too smart to ever be fooled online.\"","myth":{"un":"I'm too smart to be fooled online.","re":"Anyone can be fooled; the protection is habits, the four questions, not cleverness.","why":"Overconfidence is exactly what manipulators count on."},"relearn":"No one's unfoolable; good habits, not ego, keep you sharp.","persona":"Veer","source":"humility / media literacy"},
];

export const REALITY_CHECK: V2GameConfig = {
  gameId: "reality-check",
  title: "Reality Check",
  greet: "Hey, it's Lensy. Almost nothing online is as real as it looks — filters, highlight reels, ads, even fakes. Let's see the curation and ask the four questions.",
  scenarios: SCENARIOS,
  categories: [
    { id: "real-vs-reel", emoji: "🪞", label: "Real vs reel" },
    { id: "manipulation-files", emoji: "🧲", label: "Manipulation files" },
    { id: "media-love-sex", emoji: "🎬", label: "Love & sex on screen" },
    { id: "fakes-and-rights", emoji: "🕵️", label: "Fakes & your rights" },
    { id: "finding-help", emoji: "💛", label: "Find help & report" },
    { id: "think-for-yourself", emoji: "🧠", label: "The four questions" },
  ],
  badge: {
    title: "Reality Checker! 🔍",
    blurb: "You can see the curation, spot the manipulation, tell real from reel, and know your rights against fakes — and where to report them. You decide what's real. 🔍",
  },
  helpLine: "A fake or private image of you or a friend is never your fault — save evidence, tell a trusted adult, report at cybercrime.gov.in / 1930 or Childline 1098.",
  helpLabel: "Get help · 1930 / Childline 1098",
  reassure: "Curiosity is normal. A faked or leaked image is NEVER your fault — tell a trusted adult and report at cybercrime.gov.in / 1930 or Childline 1098. 💛",
  reassureCats: ["media-love-sex", "fakes-and-rights", "finding-help"],
};
