// Content for Respect at Home (node g56, ages 22+, Chapter 7) — NEW v2 build to GDD 56 (mechanic-embodying), the
// CHAPTER'S HIGHEST-SAFEGUARDING node: it carries the consent thread into marriage and committed partnership — the
// place consent is most often assumed away. Marriage doesn't cancel consent, and love is never control. 84
// researched, India-grounded scenarios across respect-daily → consent-inside → spot-abuse-control →
// safety-and-help → never-your-fault → tools-and-help, each encoded as one of the shared v2 play actions
// (strike-rewrite / branch / role-play / sort / reflect / spot / match) — no binary "tap the right card". Lead:
// strike-rewrite (bust the myth), branch (your move), role-play (say it). Five modes: respect daily (mutual
// respect & an equal voice), consent inside (married is NOT standing consent; UN&RE), spot abuse & control (the
// forms of domestic abuse — emotional, financial, sexual, physical — and coercive control; it's never love),
// safety & help (recognising danger, safety-planning basics, where to get help, NO blame), tools/help. HIGH-STAKES
// & survivor-centred throughout: NEVER victim-blaming (abuse is always the perpetrator's responsibility), urgent
// disclosure routing (181, 1091, 112), even-handed across genders (men and others can be victims and are
// especially silenced), strictly non-graphic. Protections framed around India's Protection of Women from Domestic
// Violence Act 2005 (covering physical, emotional, sexual & economic abuse — protection orders & maintenance); the
// marital-consent CRIMINAL-law landscape is contested and evolving, so this is educational, not legal advice.
// Safety-planning handled with care — risk can RISE at leaving. Builds on Mutual (g31) and Consent, For Real (g44);
// the protective backbone of Chapter 7 (g55 routes coercive control here). gameId "respect-at-home".
import type { V2GameConfig, Scenario } from "./v2-schema";

const SCENARIOS: Scenario[] = [
  {"id":"rh-001","cat":"respect-daily","type":"sort","hook":"Sort: mutual respect at home, or its absence?","items":[{"id":"a","text":"Both partners' opinions count"},{"id":"b","text":"One person decides everything"},{"id":"c","text":"You can disagree safely"},{"id":"d","text":"You walk on eggshells"}],"bins":[{"id":"respect","label":"Respect"},{"id":"absence","label":"Its absence"}],"key":{"a":"respect","b":"absence","c":"respect","d":"absence"},"relearn":"Both opinions counting and disagreeing safely is respect; one person deciding and eggshells is its absence.","persona":"any","source":"respect markers"},
  {"id":"rh-002","cat":"respect-daily","type":"reflect","hook":"Sam: respect, an equal voice and safety belong inside the home as much as anywhere. Agree?","prompt":"What do you think?","options":["Yes","At home too","An equal voice"],"affirm":"Respect, an equal voice and safety don't stop at your front door; they belong inside the home.","relearn":"Respect, an equal voice and safety belong inside the home as much as anywhere.","persona":"any","source":"home too"},
  {"id":"rh-003","cat":"respect-daily","type":"branch","hook":"Your partner expects all the household decisions to be theirs alone.","options":[{"text":"Establish that big decisions are made together","consequence":"You claim your equal voice.","outcome":"equal-voice","best":true},{"text":"Defer on everything to keep the peace","consequence":"Establishing that big decisions are joint is your equal voice; deferring on everything erodes it."}],"debrief":"An equal voice in decisions, money and plans is part of a respectful partnership.","relearn":"Big decisions should be made together; you have an equal voice.","persona":"any","source":"equal voice"},
  {"id":"rh-004","cat":"respect-daily","type":"strike-rewrite","hook":"\"Once you're married, you give up your own rights and autonomy.\"","myth":{"un":"Once married, you give up your own rights and autonomy.","re":"You keep your rights, autonomy and dignity inside a marriage; partnership doesn't erase them.","why":"A wedding ring isn't a surrender of self."},"relearn":"You keep your rights, autonomy and dignity inside a marriage.","persona":"Reshma","source":"keep your autonomy"},
  {"id":"rh-005","cat":"respect-daily","type":"sort","hook":"Sort: a sign of a respectful home, or a warning?","items":[{"id":"a","text":"You feel safe to be yourself"},{"id":"b","text":"You fear your partner's reactions"},{"id":"c","text":"Your needs are taken seriously"},{"id":"d","text":"Your money is controlled for you"}],"bins":[{"id":"respect","label":"Respectful"},{"id":"warning","label":"Warning"}],"key":{"a":"respect","b":"warning","c":"respect","d":"warning"},"relearn":"Feeling safe and having your needs taken seriously is respectful; fear and money control are warnings.","persona":"any","source":"respect vs warning"},
  {"id":"rh-006","cat":"respect-daily","type":"branch","hook":"You want to build a home where both of you feel genuinely respected.","options":[{"text":"Make space for both voices, needs and choices","consequence":"You set a respectful foundation.","outcome":"respectful","best":true},{"text":"Let one person's word always rule","consequence":"Making space for both voices and choices builds respect; one person always ruling doesn't."}],"debrief":"A respectful home actively makes room for both partners' voices, needs and choices.","relearn":"Make space for both voices, needs and choices to build a respectful home.","persona":"any","source":"building respect"},
  {"id":"rh-007","cat":"respect-daily","type":"reflect","hook":"Sam: in a healthy partnership, your partner is glad you have your own mind, money and friends. Recognise that?","prompt":"What do you think?","options":["Yes","Glad I'm me","Healthy"],"affirm":"A good partner welcomes your independence, your mind, money and friendships; that's real respect.","relearn":"A healthy partner is glad you keep your own mind, money and friends.","persona":"any","source":"welcomes independence"},
  {"id":"rh-008","cat":"consent-inside","type":"strike-rewrite","hook":"\"Marriage means standing, automatic consent.\"","myth":{"un":"Marriage means standing, automatic consent.","re":"Consent is ongoing inside marriage; you can say no any time, and your body is yours.","why":"A relationship is not blanket permission."},"relearn":"Consent is ongoing inside marriage; you can say no any time, and your body is yours.","persona":"any","source":"not standing consent"},
  {"id":"rh-009","cat":"consent-inside","type":"strike-rewrite","hook":"\"Forcing sex within marriage isn't really a violation.\"","myth":{"un":"Forcing sex within marriage isn't really a violation.","re":"Coercing sex is a violation of consent and dignity, regardless of marital status or the law's current state.","why":"Your body remains your own inside a marriage."},"relearn":"Coercing sex within marriage is a violation of consent and dignity; your body remains yours.","persona":"Reshma","source":"marital consent"},
  {"id":"rh-010","cat":"consent-inside","type":"branch","hook":"Your partner insists you 'owe' them sex because you're married.","options":[{"text":"Hold that consent is yours to give, always","consequence":"You keep your bodily autonomy.","outcome":"autonomy","best":true},{"text":"Give in because you feel obligated","consequence":"Consent is always yours to give; marriage never makes it an obligation you owe."}],"debrief":"No one is 'owed' sex by marriage; consent is freely given, every time, inside a relationship too.","relearn":"You never 'owe' sex; consent is yours to give, always, marriage or not.","persona":"any","source":"never owed"},
  {"id":"rh-011","cat":"consent-inside","type":"reflect","hook":"Sam: consent doesn't expire at the wedding, it stays yours for life. Land clearly?","prompt":"What do you think?","options":["Yes","Stays mine","Doesn't expire"],"affirm":"Your consent is yours for life; it never expires or transfers because of a marriage.","relearn":"Consent doesn't expire at the wedding; it stays yours for life.","persona":"any","source":"never expires"},
  {"id":"rh-012","cat":"consent-inside","type":"role-play","hook":"You want to say no to your partner without it becoming a fight.","setup":"Be clear and calm. Say:","yourLine":[{"text":"\"Not tonight, I'm not feeling it, and that's okay.\"","best":true},{"text":"Go along with it to avoid conflict"}],"relearn":"You can calmly say no to your partner; a respectful partner accepts it.","persona":"any","source":"saying no"},
  {"id":"rh-013","cat":"consent-inside","type":"sort","hook":"Sort: respects consent inside a relationship, or ignores it?","items":[{"id":"a","text":"Checking in and accepting a no"},{"id":"b","text":"Pressuring after a no"},{"id":"c","text":"Stopping when asked"},{"id":"d","text":"Treating marriage as permission"}],"bins":[{"id":"respects","label":"Respects consent"},{"id":"ignores","label":"Ignores it"}],"key":{"a":"respects","b":"ignores","c":"respects","d":"ignores"},"relearn":"Checking in and stopping when asked respects consent; pressuring or treating marriage as permission ignores it.","persona":"any","source":"consent inside"},
  {"id":"rh-014","cat":"consent-inside","type":"branch","hook":"You feel unsure whether you're even allowed to say no to your spouse.","options":[{"text":"Know that you always can; your consent is yours","consequence":"You reclaim your right to say no.","outcome":"clear","best":true},{"text":"Assume marriage took that right away","consequence":"You always can say no; marriage never takes away your right to your own consent."}],"debrief":"You are always allowed to say no inside a marriage; that right is never given up.","relearn":"You can always say no to your spouse; that right is never given up.","persona":"Reshma","source":"you can say no"},
  {"id":"rh-015","cat":"spot-abuse-control","type":"strike-rewrite","hook":"\"It's only abuse if it's physical.\"","myth":{"un":"It's only abuse if it's physical.","re":"Emotional, sexual, economic and coercive-control abuse are all real domestic abuse, recognised by law.","why":"Harm comes in many forms, not only bruises."},"relearn":"Emotional, sexual, economic and coercive-control abuse are all real domestic abuse.","persona":"any","source":"all forms"},
  {"id":"rh-016","cat":"spot-abuse-control","type":"strike-rewrite","hook":"\"Controlling the money is just practical, or the man's role.\"","myth":{"un":"Controlling all the money is just practical.","re":"Controlling money and denying independence is economic abuse, a recognised form of domestic violence.","why":"Money used to control is a tool of abuse."},"relearn":"Controlling money and denying independence is economic abuse, a form of domestic violence.","persona":"Reshma","source":"economic abuse"},
  {"id":"rh-017","cat":"spot-abuse-control","type":"strike-rewrite","hook":"\"Love sometimes looks like jealousy, monitoring and control.\"","myth":{"un":"Love sometimes looks like jealousy, monitoring and control.","re":"Coercion, monitoring, isolation and control are abuse, not love.","why":"Real love trusts and frees; control polices."},"relearn":"Coercion, monitoring, isolation and control are abuse, not love.","persona":"any","source":"never love"},
  {"id":"rh-018","cat":"spot-abuse-control","type":"spot","hook":"Spot the coercive control.","scene":[{"id":"a","text":"Tracking your location and contacts","trick":true},{"id":"b","text":"Asking how your day was","trick":false},{"id":"c","text":"Cutting you off from family and friends","trick":true}],"why":"Tracking your movements and isolating you from people is coercive control; ordinary interest isn't.","relearn":"Tracking your movements and isolating you from people is coercive control.","persona":"any","source":"spotting control"},
  {"id":"rh-019","cat":"spot-abuse-control","type":"sort","hook":"Sort: a form of domestic abuse, or not?","items":[{"id":"a","text":"Constant insults and humiliation"},{"id":"b","text":"A fair disagreement"},{"id":"c","text":"Withholding money to control you"},{"id":"d","text":"Sharing decisions openly"}],"bins":[{"id":"abuse","label":"Domestic abuse"},{"id":"not","label":"Not abuse"}],"key":{"a":"abuse","b":"not","c":"abuse","d":"not"},"relearn":"Constant humiliation and withholding money to control are abuse; a fair disagreement or shared decisions aren't.","persona":"any","source":"is it abuse"},
  {"id":"rh-020","cat":"spot-abuse-control","type":"strike-rewrite","hook":"\"They only get controlling because they love me so much.\"","myth":{"un":"They only get controlling because they love me.","re":"Control isn't a sign of love; it's a sign of abuse, and it tends to escalate.","why":"Devotion doesn't require surveillance or fear."},"relearn":"Control isn't love; it's abuse, and it tends to escalate.","persona":"any","source":"control isn't love"},
  {"id":"rh-021","cat":"spot-abuse-control","type":"spot","hook":"Spot the emotional abuse behind 'normal' words.","scene":[{"id":"a","text":"Constant put-downs disguised as jokes","trick":true},{"id":"b","text":"Honest, kind feedback","trick":false},{"id":"c","text":"\"You're worthless without me\"","trick":true}],"why":"Disguised put-downs and 'worthless without me' are emotional abuse; honest kind feedback isn't.","relearn":"Disguised put-downs and 'worthless without me' are emotional abuse.","persona":"any","source":"emotional abuse"},
  {"id":"rh-022","cat":"spot-abuse-control","type":"sort","hook":"Sort: care, or control dressed as care?","items":[{"id":"a","text":"Trusting you with your own life"},{"id":"b","text":"Monitoring your phone and movements"},{"id":"c","text":"Being glad you have friends"},{"id":"d","text":"Deciding what you can wear or do"}],"bins":[{"id":"care","label":"Care"},{"id":"control","label":"Control"}],"key":{"a":"care","b":"control","c":"care","d":"control"},"relearn":"Trusting your life and welcoming your friends is care; monitoring you and dictating your choices is control.","persona":"any","source":"care vs control"},
  {"id":"rh-023","cat":"spot-abuse-control","type":"strike-rewrite","hook":"\"What happens in a marriage is private; outsiders shouldn't be involved.\"","myth":{"un":"What happens in a marriage is private; no one should get involved.","re":"Abuse is not a private family matter; 'private' is not a shield, and help and legal protection exist.","why":"Privacy must never cover for harm."},"relearn":"Abuse isn't a private matter; 'private' is no shield, and help and protection exist.","persona":"Razia","source":"private is no shield"},
  {"id":"rh-024","cat":"spot-abuse-control","type":"branch","hook":"You're noticing early signs of control that you'd been brushing off.","options":[{"text":"Take them seriously and name them honestly","consequence":"You see the pattern early.","outcome":"clear","best":true},{"text":"Keep telling yourself it's normal","consequence":"Naming early control honestly, rather than normalising it, is how you protect yourself early."}],"debrief":"Early signs of control are easy to normalise; naming them honestly is the first protection.","relearn":"Take early signs of control seriously and name them honestly.","persona":"Reshma","source":"early signs"},
  {"id":"rh-025","cat":"safety-and-help","type":"branch","hook":"You realise you may be in an abusive situation and feel frightened.","options":[{"text":"Reach out for help; you're not alone and it's not your fault","consequence":"You connect with real support.","outcome":"supported","best":true},{"text":"Stay silent and try to manage alone","consequence":"Reaching out for help (181, 1091, 112, a trusted person) connects you to real support; you're not alone, and it's not your fault."}],"debrief":"If you're frightened in your relationship, reaching out, to a helpline or trusted person, is the brave, right step; it's never your fault.","relearn":"If you're frightened, reach out for help (181, 1091, 112); you're not alone, and it's not your fault.","persona":"any","source":"reaching for help"},
  {"id":"rh-026","cat":"safety-and-help","type":"reflect","hook":"Sam: abuse can escalate, especially around leaving, so safety planning matters. Important to know?","prompt":"What do you think?","options":["Yes","Plan for safety","Risk rises at leaving"],"affirm":"Knowing that risk can rise around leaving, and planning for safety, is vital, careful knowledge.","relearn":"Abuse can escalate, especially around leaving; safety planning matters.","persona":"any","source":"risk rises at leaving"},
  {"id":"rh-027","cat":"safety-and-help","type":"sort","hook":"Sort: part of a safety plan, or not?","items":[{"id":"a","text":"A safe place you can go"},{"id":"b","text":"Confronting them alone when angry"},{"id":"c","text":"Key documents and a small bag ready"},{"id":"d","text":"Hoping it just stops"}],"bins":[{"id":"plan","label":"Safety plan"},{"id":"not","label":"Not safe"}],"key":{"a":"plan","b":"not","c":"plan","d":"not"},"relearn":"A safe place and key documents ready are part of a safety plan; confronting them alone or just hoping isn't.","persona":"any","source":"safety plan"},
  {"id":"rh-028","cat":"safety-and-help","type":"branch","hook":"You want to be ready in case things become dangerous.","options":[{"text":"Quietly prepare: a trusted contact, documents, a code word","consequence":"You build a safety net.","outcome":"prepared","best":true},{"text":"Assume it won't come to that","consequence":"Quietly preparing a trusted contact, documents and a code word builds a safety net, just in case."}],"debrief":"A quiet safety plan, a trusted contact, documents, a code word, a safe place, is wise preparation.","relearn":"Quietly prepare a safety net: a trusted contact, documents, a code word, a safe place.","persona":"any","source":"preparing"},
  {"id":"rh-029","cat":"safety-and-help","type":"role-play","hook":"You need to set up a code word with a trusted friend for emergencies.","setup":"Arrange it quietly. Say:","yourLine":[{"text":"\"If I ever text you this word, please call and check on me or send help.\"","best":true},{"text":"Tell no one in case it gets back to them"}],"relearn":"Set up a code word with a trusted friend so they can act if you're in danger.","persona":"any","source":"code word"},
  {"id":"rh-030","cat":"safety-and-help","type":"branch","hook":"You're keeping a record of incidents but worry it's pointless.","options":[{"text":"Keep a dated record and save evidence safely","consequence":"You strengthen any future case and protection.","outcome":"documented","best":true},{"text":"Don't bother documenting anything","consequence":"A dated record and saved evidence (screenshots, messages) can support protection orders later; it's not pointless."}],"debrief":"A dated record and saved evidence, stored safely, can support protection orders and help under the DV Act.","relearn":"Keep a dated record and save evidence safely; it can support protection later.","persona":"any","source":"documenting safely"},
  {"id":"rh-031","cat":"safety-and-help","type":"match","hook":"Match the need to where help lives (India).","pairs":[{"left":"In danger right now","right":"Emergency 112"},{"left":"Domestic violence support","right":"Women Helpline 181"},{"left":"A woman in distress","right":"1091"}],"relearn":"112 for immediate danger, 181 for DV support, 1091 for a woman in distress.","persona":"any","source":"help routes"},
  {"id":"rh-032","cat":"safety-and-help","type":"reflect","hook":"Sam: whether and when to leave is the survivor's own decision, and any choice deserves support. Agree?","prompt":"What do you think?","options":["Yes","Their choice","Support either way"],"affirm":"Whether and when to leave is the survivor's decision; every choice deserves support, never pressure.","relearn":"Whether and when to leave is the survivor's own decision, and deserves support.","persona":"any","source":"their decision"},
  {"id":"rh-033","cat":"safety-and-help","type":"match","hook":"Match the need to its real route (India).","pairs":[{"left":"Know your rights in depth","right":"Free legal aid (NALSA)"},{"left":"Stop the violence","right":"A protection order"},{"left":"Stay in your home","right":"A residence order"}],"relearn":"Free legal aid and the DV Act's protection and residence orders are real routes.","persona":"Razia","source":"the DV Act"},
  {"id":"rh-034","cat":"never-your-fault","type":"strike-rewrite","hook":"\"If they hurt me, I must have provoked it.\"","myth":{"un":"If they hurt me, I must have provoked it.","re":"Abuse is never the victim's fault; the responsibility lies only with the abuser.","why":"Nothing you do justifies being abused."},"relearn":"Abuse is never the victim's fault; responsibility lies only with the abuser.","persona":"any","source":"never your fault"},
  {"id":"rh-035","cat":"never-your-fault","type":"strike-rewrite","hook":"\"Men can't be victims of domestic abuse.\"","myth":{"un":"Men can't be victims of domestic abuse.","re":"Anyone of any gender can be a victim, and male and other survivors are especially silenced.","why":"Abuse isn't defined by the victim's gender."},"relearn":"Anyone of any gender can be a victim of domestic abuse and deserves support.","persona":"any","source":"even-handed"},
  {"id":"rh-036","cat":"never-your-fault","type":"role-play","hook":"A friend confides they're being abused and blames themselves.","setup":"Be clear and warm. Say:","yourLine":[{"text":"\"This is not your fault. The only person responsible is the one hurting you. I'm here.\"","best":true},{"text":"\"What did you do to set them off?\""}],"relearn":"Tell a survivor it's not their fault; the responsibility is only the abuser's.","persona":"any","source":"no blame"},
  {"id":"rh-037","cat":"never-your-fault","type":"strike-rewrite","hook":"\"A good wife or husband just endures it for the family.\"","myth":{"un":"A good spouse just endures abuse for the family.","re":"No one should endure abuse; safety and dignity come first, and help exists.","why":"Family is never a reason to suffer harm."},"relearn":"No one should endure abuse for the family; safety and dignity come first.","persona":"Reshma","source":"don't endure it"},
  {"id":"rh-038","cat":"never-your-fault","type":"branch","hook":"You experienced abuse and feel deep shame about it.","options":[{"text":"Remind yourself the shame belongs to the abuser, not you","consequence":"You release misplaced shame.","outcome":"freed","best":true},{"text":"Carry the shame as if it's yours","consequence":"The shame belongs to the person who abused you, never to you; you deserve support, not shame."}],"debrief":"Survivors often carry shame that belongs entirely to the abuser; releasing it is part of healing.","relearn":"The shame of abuse belongs to the abuser, never to you.","persona":"any","source":"misplaced shame"},
  {"id":"rh-039","cat":"never-your-fault","type":"role-play","hook":"A male friend hints he's being abused but fears no one will believe him.","setup":"Believe him fully. Say:","yourLine":[{"text":"\"I believe you, this is real and it's not your fault, and you deserve help.\"","best":true},{"text":"\"Come on, that doesn't happen to men.\""}],"relearn":"Believe male and other survivors fully; abuse is real and never their fault.","persona":"any","source":"believe all survivors"},
  {"id":"rh-040","cat":"never-your-fault","type":"spot","hook":"Spot what determines fault in abuse.","scene":[{"id":"a","text":"The abuser's choice to abuse","trick":false},{"id":"b","text":"What the victim wore or said","trick":true},{"id":"c","text":"Only the person doing the harm","trick":false}],"why":"The abuser's choice alone determines fault; what the victim wore or said never does.","relearn":"Nothing you wore, said or did makes abuse your fault; it's the abuser's alone.","persona":"any","source":"nothing justifies it"},
  {"id":"rh-041","cat":"tools-and-help","type":"match","hook":"Match the form of abuse to its description.","pairs":[{"left":"Economic abuse","right":"Controlling money, denying independence"},{"left":"Emotional abuse","right":"Insults, threats, humiliation"},{"left":"Coercive control","right":"Monitoring, isolation, surveillance"}],"relearn":"Economic, emotional and coercive-control abuse each have clear, recognisable forms.","persona":"any","source":"the forms"},
  {"id":"rh-042","cat":"tools-and-help","type":"sort","hook":"Sort: a real source of help, or not?","items":[{"id":"a","text":"Women Helpline 181"},{"id":"b","text":"Just bottling it up"},{"id":"c","text":"A women's-rights or legal-aid worker"},{"id":"d","text":"Hoping the abuser changes"}],"bins":[{"id":"real","label":"Real help"},{"id":"not","label":"Not help"}],"key":{"a":"real","b":"not","c":"real","d":"not"},"relearn":"181 and a legal-aid worker are real help; bottling up or hoping the abuser changes aren't.","persona":"Razia","source":"real help"},
  {"id":"rh-043","cat":"tools-and-help","type":"reflect","hook":"Sam: this is education and signposting, not legal advice, and the marital-consent law is still evolving. Clear?","prompt":"What do you think?","options":["Yes","Get real help","Law is evolving"],"affirm":"This points you to real help and the law; for an actual case, qualified or free legal aid is the right step.","relearn":"This is education and signposting, not legal advice; the marital-consent law is still evolving.","persona":"any","source":"not legal advice"},
  {"id":"rh-044","cat":"tools-and-help","type":"branch","hook":"A friend is in an abusive relationship and doesn't know help exists.","options":[{"text":"Gently share the routes: 181, a counsellor, the DV Act","consequence":"You open a door to safety.","outcome":"connected","best":true},{"text":"Stay out of it; it's their marriage","consequence":"Gently sharing the routes (181, a counsellor, the DV Act) can be the lifeline a friend in an abusive marriage needs."}],"debrief":"Knowing help exists, and where, can be exactly what gets a friend toward safety.","relearn":"Gently share the help routes (181, a counsellor, the DV Act) with a friend in an abusive relationship.","persona":"any","source":"sharing routes"},
  {"id":"rh-045","cat":"tools-and-help","type":"match","hook":"Match the protection to what the DV Act can offer.","pairs":[{"left":"Stop the violence","right":"A protection order"},{"left":"Financial support","right":"Maintenance"},{"left":"A right to stay safely","right":"A residence order"}],"relearn":"The DV Act can offer protection orders, maintenance and residence orders.","persona":"Razia","source":"DV Act remedies"},
  {"id":"rh-046","cat":"tools-and-help","type":"reflect","hook":"Sam: respect, an equal voice, consent and safety, these belong to you at home, always. Believe it?","prompt":"What do you think?","options":["Yes","They're mine","Always"],"affirm":"Respect, an equal voice, consent and safety are yours at home, always; never settle below them.","relearn":"Respect, an equal voice, consent and safety belong to you at home, always.","persona":"any","source":"they're yours"},
  {"id":"rh-047","cat":"tools-and-help","type":"spot","hook":"Spot the supportive response to a survivor.","scene":[{"id":"a","text":"\"I believe you, it's not your fault\"","trick":false},{"id":"b","text":"\"What did you do to provoke it?\"","trick":true},{"id":"c","text":"\"You deserve safety and support\"","trick":false}],"why":"Belief and 'you deserve safety' support a survivor; 'what did you do?' blames them.","relearn":"Belief and 'you deserve safety' support a survivor; blame questions don't.","persona":"any","source":"supportive response"},
  {"id":"rh-048","cat":"tools-and-help","type":"match","hook":"Match the home truth to what it protects.","pairs":[{"left":"Marriage isn't standing consent","right":"Your bodily autonomy"},{"left":"Control isn't love","right":"Your freedom"},{"left":"Help exists","right":"Your safety"}],"relearn":"Marriage isn't standing consent, control isn't love, it's never your fault, and help exists.","persona":"any","source":"carry forward"},
  {"id":"rh-049","cat":"respect-daily","type":"sort","hook":"Sort: an equal voice, or being silenced?","items":[{"id":"a","text":"Your views shape decisions"},{"id":"b","text":"Your opinions routinely dismissed"},{"id":"c","text":"Both of you are heard"},{"id":"d","text":"One voice always overrides"}],"bins":[{"id":"voice","label":"Equal voice"},{"id":"silenced","label":"Silenced"}],"key":{"a":"voice","b":"silenced","c":"voice","d":"silenced"},"relearn":"Your views shaping decisions and both being heard is an equal voice; routine dismissal or being overridden is silencing.","persona":"any","source":"your voice counts"},
  {"id":"rh-050","cat":"consent-inside","type":"strike-rewrite","hook":"\"Saying no to your spouse is being a bad partner.\"","myth":{"un":"Saying no to your spouse makes you a bad partner.","re":"You can lovingly say no; a respectful partner accepts it, consent stays yours.","why":"A no is not a betrayal of the relationship."},"relearn":"You can lovingly say no to your spouse; a respectful partner accepts it.","persona":"any","source":"no isn't bad"},
  {"id":"rh-051","cat":"spot-abuse-control","type":"branch","hook":"A relative tells you the control in your marriage is 'just how husbands are'.","options":[{"text":"Reject the normalising; control isn't normal or okay","consequence":"You refuse to accept abuse as normal.","outcome":"clear","best":true},{"text":"Accept it as just how it is","consequence":"Rejecting 'that's just how husbands are' refuses to normalise control, which is never normal or okay."}],"debrief":"Normalising control as 'just how they are' keeps people trapped; naming it as wrong is the first step out.","relearn":"Don't accept control as 'just how husbands are'; it's never normal or okay.","persona":"Reshma","source":"refusing to normalise"},
  {"id":"rh-052","cat":"safety-and-help","type":"role-play","hook":"You're ready to reach out to a helpline but are scared.","setup":"You can keep it simple. Say:","yourLine":[{"text":"\"I think I'm being abused at home and I need help and to know my options.\"","best":true},{"text":"Hang up before anyone answers"}],"relearn":"A simple 'I think I'm being abused and I need help' is enough to start.","persona":"any","source":"making the call"},
  {"id":"rh-053","cat":"never-your-fault","type":"sort","hook":"Sort: a supportive thing to tell a survivor, or a harmful one?","items":[{"id":"a","text":"\"It's not your fault\""},{"id":"b","text":"\"Why don't you just leave?\""},{"id":"c","text":"\"I'm here, what do you need?\""},{"id":"d","text":"\"You must have done something\""}],"bins":[{"id":"supportive","label":"Supportive"},{"id":"harmful","label":"Harmful"}],"key":{"a":"supportive","b":"harmful","c":"supportive","d":"harmful"},"relearn":"'Not your fault' and 'what do you need?' support; 'just leave' and 'you must have done something' harm.","persona":"any","source":"what to say"},
  {"id":"rh-054","cat":"tools-and-help","type":"branch","hook":"You want to support a survivor without taking over their choices.","options":[{"text":"Believe them, ask what they need, respect their pace","consequence":"You give safe, survivor-led support.","outcome":"survivor-led","best":true},{"text":"Decide and act for them","consequence":"Believing them, asking what they need and respecting their pace is survivor-led support; taking over isn't."}],"debrief":"Survivor-centred support believes, asks what's needed, and respects the survivor's own choices and pace.","relearn":"Believe a survivor, ask what they need, and respect their pace; don't take over.","persona":"Saxena","source":"survivor-led"},
  {"id":"rh-055","cat":"spot-abuse-control","type":"spot","hook":"Spot the financial abuse.","scene":[{"id":"a","text":"Taking all your earnings and giving an 'allowance'","trick":true},{"id":"b","text":"Sharing money decisions openly","trick":false},{"id":"c","text":"Blocking you from working or having an account","trick":true}],"why":"Taking your earnings and blocking your access to work or money is financial abuse; open sharing isn't.","relearn":"Taking your earnings or blocking your access to work and money is financial abuse.","persona":"Reshma","source":"financial abuse"},
  {"id":"rh-056","cat":"consent-inside","type":"reflect","hook":"Sam: a loving partner never needs to pressure or coerce; they wait for a real yes. Recognise that?","prompt":"What do you think?","options":["Yes","Waits for yes","Never coerces"],"affirm":"Real love waits for a genuine yes and never coerces; that's the standard inside marriage too.","relearn":"A loving partner never pressures or coerces; they wait for a real yes.","persona":"any","source":"waits for yes"},
  {"id":"rh-057","cat":"respect-daily","type":"sort","hook":"Sort: an equal voice in the home, or a one-sided power?","items":[{"id":"a","text":"Both decide how money is spent"},{"id":"b","text":"One controls all the finances"},{"id":"c","text":"Both opinions shape big choices"},{"id":"d","text":"One person's word is final, always"}],"bins":[{"id":"equal","label":"Equal voice"},{"id":"onesided","label":"One-sided power"}],"key":{"a":"equal","b":"onesided","c":"equal","d":"onesided"},"relearn":"Both deciding money and shaping choices is an equal voice; one controlling finances or always having the final word isn't.","persona":"any","source":"equal vs one-sided"},
  {"id":"rh-058","cat":"never-your-fault","type":"branch","hook":"You worry that reporting abuse will 'break up the family' and it'll be your fault.","options":[{"text":"Know that the abuse, not your reporting, is what harms the family","consequence":"You release a false guilt.","outcome":"clear","best":true},{"text":"Stay silent to 'keep the family together'","consequence":"The abuse, not your reporting it, is what harms the family; your safety isn't a betrayal."}],"debrief":"Seeking safety doesn't break a family; the abuse does. Your wellbeing is never the thing to sacrifice.","relearn":"The abuse, not your reporting it, is what harms a family; your safety isn't a betrayal.","persona":"Reshma","source":"not your fault to report"},
  {"id":"rh-059","cat":"spot-abuse-control","type":"strike-rewrite","hook":"\"Nothing can really be done legally about abuse in a marriage.\"","myth":{"un":"Nothing can be done legally about abuse in a marriage.","re":"The Domestic Violence Act 2005 offers real civil protections, protection orders, maintenance and residence rights.","why":"The law provides concrete remedies."},"relearn":"The DV Act 2005 offers real protections: protection orders, maintenance and residence rights.","persona":"Razia","source":"the law can help"},
  {"id":"rh-060","cat":"safety-and-help","type":"branch","hook":"You have little money or privacy, which makes reaching out feel impossible.","options":[{"text":"Use discreet, free routes: 181, a trusted person, legal aid","consequence":"You find a safe path despite the barriers.","outcome":"reached","best":true},{"text":"Conclude help is out of reach","consequence":"Discreet, free routes (181, a trusted person, free legal aid) exist for exactly these barriers; help is reachable."}],"debrief":"Even with little money or privacy, discreet and free routes, helplines, trusted people, legal aid, can reach you.","relearn":"Even with little money or privacy, discreet free routes (181, a trusted person, legal aid) can help.","persona":"Reshma","source":"reaching the most at-risk"},
  {"id":"rh-061","cat":"respect-daily","type":"reflect","hook":"Sam: you deserve to feel safe, heard and respected in your own home. Believe that for yourself?","prompt":"What do you think?","options":["Yes","I deserve that","Safe and heard"],"affirm":"You absolutely deserve to feel safe, heard and respected at home; never accept less.","relearn":"You deserve to feel safe, heard and respected in your own home.","persona":"any","source":"you deserve safety"},
  {"id":"rh-062","cat":"consent-inside","type":"branch","hook":"Your partner sulks or punishes you whenever you say no to intimacy.","options":[{"text":"Recognise that punishment for a no is coercion, not love","consequence":"You see the pattern clearly.","outcome":"clear","best":true},{"text":"Give in each time to avoid the punishment","consequence":"Punishment for a no is coercion, not love; giving in to avoid it isn't real consent."}],"debrief":"Being punished for saying no turns 'consent' into coercion; that isn't a free yes.","relearn":"Punishment for saying no is coercion, not love; a coerced yes isn't consent.","persona":"any","source":"coercion not consent"},
  {"id":"rh-063","cat":"spot-abuse-control","type":"sort","hook":"Sort: a warning sign of coercive control, or healthy?","items":[{"id":"a","text":"Needing to approve who you see"},{"id":"b","text":"Trusting your friendships"},{"id":"c","text":"Checking your phone constantly"},{"id":"d","text":"Respecting your privacy"}],"bins":[{"id":"warning","label":"Warning sign"},{"id":"healthy","label":"Healthy"}],"key":{"a":"warning","b":"healthy","c":"warning","d":"healthy"},"relearn":"Approving who you see and checking your phone is coercive control; trusting friendships and respecting privacy is healthy.","persona":"any","source":"control warning signs"},
  {"id":"rh-064","cat":"never-your-fault","type":"role-play","hook":"A survivor fears you'll judge their choices about staying or leaving.","setup":"Offer compassion, not judgement. Say:","yourLine":[{"text":"\"Whatever you decide, I'm with you, no judgement, just support.\"","best":true},{"text":"\"You have to leave right now.\""}],"relearn":"Whatever a survivor decides, they deserve compassion, never judgement.","persona":"any","source":"compassion not judgement"},
  {"id":"rh-065","cat":"tools-and-help","type":"sort","hook":"Sort: this game's commitment, or against it?","items":[{"id":"a","text":"Abuse is never the victim's fault"},{"id":"b","text":"Blaming survivors"},{"id":"c","text":"Routing danger to real help"},{"id":"d","text":"Treating abuse as private"}],"bins":[{"id":"for","label":"Its commitment"},{"id":"against","label":"Against it"}],"key":{"a":"for","b":"against","c":"for","d":"against"},"relearn":"Never-the-victim's-fault and routing danger to help is the commitment; blaming survivors or 'it's private' isn't.","persona":"any","source":"the commitment"},
  {"id":"rh-066","cat":"respect-daily","type":"role-play","hook":"You want to set a respectful tone of equal voice with your partner.","setup":"Name it warmly. Say:","yourLine":[{"text":"\"Let's make decisions together as equals, both our voices matter here.\"","best":true},{"text":"Let one of you quietly dominate"}],"relearn":"Name an equal-voice intention early; both partners' voices should matter.","persona":"any","source":"equal-voice tone"},
  {"id":"rh-067","cat":"consent-inside","type":"sort","hook":"Sort: respects bodily autonomy in marriage, or violates it?","items":[{"id":"a","text":"Accepting a no without punishment"},{"id":"b","text":"Coercing or pressuring sex"},{"id":"c","text":"Checking in about what each wants"},{"id":"d","text":"Treating marriage as entitlement"}],"bins":[{"id":"respects","label":"Respects autonomy"},{"id":"violates","label":"Violates it"}],"key":{"a":"respects","b":"violates","c":"respects","d":"violates"},"relearn":"Accepting a no and checking in respects bodily autonomy; coercion and entitlement violate it.","persona":"any","source":"bodily autonomy"},
  {"id":"rh-068","cat":"spot-abuse-control","type":"spot","hook":"Spot what makes something count as abuse.","scene":[{"id":"a","text":"It controls, coerces or humiliates you","trick":false},{"id":"b","text":"It must leave visible bruises to count","trick":true},{"id":"c","text":"It harms or frightens you","trick":false}],"why":"Control, coercion, humiliation and harm count as abuse; it doesn't need visible bruises.","relearn":"If it controls, coerces, humiliates or harms you, it counts as abuse.","persona":"any","source":"it counts"},
  {"id":"rh-069","cat":"never-your-fault","type":"strike-rewrite","hook":"\"If they were really abusive, you'd have left already.\"","myth":{"un":"If they were really abusive, you'd have left already.","re":"Leaving is complex and dangerous; staying doesn't mean it isn't abuse or that it's your fault.","why":"Many reasons, fear, money, children, make leaving hard."},"relearn":"Staying doesn't mean it isn't abuse; leaving is complex and dangerous, and it's never your fault.","persona":"any","source":"why people stay"},
  {"id":"rh-070","cat":"safety-and-help","type":"reflect","hook":"Sam: if you're ever in immediate danger, reaching for emergency help (112) is always the right call. Clear?","prompt":"What do you think?","options":["Yes","112 for danger","Always right"],"affirm":"In immediate danger, calling emergency help (112) is always right; your safety comes first.","relearn":"In immediate danger, reaching for emergency help (112) is always the right call.","persona":"any","source":"immediate danger"},
  {"id":"rh-071","cat":"respect-daily","type":"match","hook":"Match the marriage belief to whether it's equal or a hierarchy.","pairs":[{"left":"Both voices matter","right":"Equal partnership"},{"left":"Decisions made together","right":"Equal partnership"},{"left":"One leads, one follows","right":"A hierarchy"}],"relearn":"A respectful marriage is a partnership of equals, not a leader-and-follower hierarchy.","persona":"any","source":"equals not hierarchy"},
  {"id":"rh-072","cat":"consent-inside","type":"role-play","hook":"You want to talk openly with your partner about consent within your marriage.","setup":"Open it gently. Say:","yourLine":[{"text":"\"I want us to always check in with each other, a real yes from both of us, every time.\"","best":true},{"text":"Assume it never needs discussing"}],"relearn":"Talk openly about ongoing consent in marriage: a real yes from both, every time.","persona":"any","source":"the consent talk"},
  {"id":"rh-073","cat":"spot-abuse-control","type":"spot","hook":"Spot the line between control and devotion.","scene":[{"id":"a","text":"Control that shrinks your world","trick":true},{"id":"b","text":"Love that expands it","trick":false},{"id":"c","text":"Freedom and trust","trick":false}],"why":"Control that shrinks your world is abuse; love that expands it, with freedom and trust, isn't.","relearn":"Control that shrinks your world, money, friends, freedom, is abuse, not devotion.","persona":"any","source":"shrinks your world"},
  {"id":"rh-074","cat":"never-your-fault","type":"role-play","hook":"You're supporting a survivor who keeps minimising what's happening to them.","setup":"Gently reflect the seriousness, without pushing. Say:","yourLine":[{"text":"\"What you're describing sounds serious and not okay, and I'm here whenever you're ready.\"","best":true},{"text":"\"I'm sure it's not that bad.\""}],"relearn":"Gently name that a survivor's experience is serious and not okay, without pushing them.","persona":"Saxena","source":"naming seriousness gently"},
  {"id":"rh-075","cat":"tools-and-help","type":"match","hook":"Match the survivor-support step to why it matters.","pairs":[{"left":"\"I believe you\"","right":"Belief is what survivors fear losing"},{"left":"\"It's not your fault\"","right":"Lifts misplaced shame"},{"left":"Signpost help","right":"Connects to real safety"}],"relearn":"Belief, removing blame and signposting are why the survivor-support steps matter.","persona":"any","source":"support steps"},
  {"id":"rh-076","cat":"safety-and-help","type":"branch","hook":"A friend in danger asks you to keep their abuse a total secret and do nothing.","options":[{"text":"Stay supportive and help them reach real safety options","consequence":"You honour them while connecting them to help.","outcome":"supported","best":true},{"text":"Promise to do nothing at all","consequence":"Staying supportive while gently helping them toward safety options serves them better than doing nothing about real danger."}],"debrief":"You can respect a survivor's choices while still gently helping them toward safety and real support.","relearn":"Stay supportive and help a friend in danger reach real safety options.","persona":"any","source":"supporting safely"},
  {"id":"rh-077","cat":"never-your-fault","type":"role-play","hook":"A survivor feels the abuse defines who they are.","setup":"Reflect their worth back. Say:","yourLine":[{"text":"\"You are not what was done to you, that reflects the abuser, not your worth.\"","best":true},{"text":"\"Maybe you brought some of it on.\""}],"relearn":"You are not what was done to you; abuse reflects the abuser, not your worth.","persona":"any","source":"your worth intact"},
  {"id":"rh-078","cat":"respect-daily","type":"branch","hook":"You want your home to be a place of safety and respect for both of you.","options":[{"text":"Build mutual respect, an equal voice and consent into daily life","consequence":"You make home genuinely safe.","outcome":"safe-home","best":true},{"text":"Let power and control creep in unchecked","consequence":"Building mutual respect, an equal voice and consent daily makes home safe; unchecked power and control don't."}],"debrief":"A safe, respectful home is built day by day through equal voice, consent and mutual respect.","relearn":"Build mutual respect, an equal voice and consent into daily life for a safe home.","persona":"any","source":"a safe home"},
  {"id":"rh-079","cat":"consent-inside","type":"strike-rewrite","hook":"\"Your partner's needs always come before your own no.\"","myth":{"un":"Your partner's needs always come before your own no.","re":"Your no matters as much as their wants; consent is mutual, not one-sided.","why":"No one's desires override another's consent."},"relearn":"Your no matters as much as their wants; consent is mutual, not one-sided.","persona":"any","source":"your no matters"},
  {"id":"rh-080","cat":"spot-abuse-control","type":"strike-rewrite","hook":"\"A bit of jealousy and checking up is healthy in a marriage.\"","myth":{"un":"A bit of jealousy and checking up is healthy.","re":"Monitoring and possessiveness aren't healthy; trust and freedom are the signs of a good marriage.","why":"Surveillance erodes the trust a marriage needs."},"relearn":"Monitoring and possessiveness aren't healthy; trust and freedom are.","persona":"any","source":"not healthy jealousy"},
  {"id":"rh-081","cat":"safety-and-help","type":"match","hook":"Match the safety-plan piece to its purpose.","pairs":[{"left":"A code word","right":"Signals a trusted person to act"},{"left":"Key documents ready","right":"Lets you leave quickly if needed"},{"left":"A dated record","right":"Supports protection later"}],"relearn":"A code word, ready documents and a dated record each serve a clear safety purpose.","persona":"any","source":"safety-plan pieces"},
  {"id":"rh-082","cat":"tools-and-help","type":"reflect","hook":"Sam: knowing the forms of abuse and where to get help could protect you, or someone you love. Worth carrying?","prompt":"What do you think?","options":["Yes","Could protect us","Worth carrying"],"affirm":"This knowledge, the forms of abuse and where help lives, is genuinely protective, for you and others.","relearn":"Knowing the forms of abuse and where to get help is genuinely protective.","persona":"any","source":"protective knowledge"},
  {"id":"rh-083","cat":"never-your-fault","type":"branch","hook":"You're starting to heal after leaving an abusive relationship.","options":[{"text":"Be gentle with yourself and lean on support","consequence":"You heal at your own pace.","outcome":"healing","best":true},{"text":"Blame yourself for how long it took","consequence":"Being gentle with yourself and leaning on support helps you heal; self-blame for the time it took doesn't."}],"debrief":"Healing after abuse takes time and self-compassion; you got out, and that's what matters.","relearn":"Be gentle with yourself and lean on support as you heal after abuse.","persona":"any","source":"healing"},
  {"id":"rh-084","cat":"tools-and-help","type":"reflect","hook":"Sam: marriage doesn't cancel consent, love is never control, and help always exists. Carry which truth home?","prompt":"What will you carry?","options":["Consent is ongoing","Love is never control","Never the victim's fault","Help always exists"],"affirm":"Carry that truth home, and you help make every home, yours or another's, a place of respect and safety.","relearn":"Consent is ongoing, love is never control, it's never your fault, and help always exists.","persona":"any","source":"carry home"},
];

export const RESPECT_AT_HOME: V2GameConfig = {
  gameId: "respect-at-home",
  title: "Respect at Home",
  greet: "Hey — it’s Sam. Consent and respect don’t stop at your front door. Marriage doesn’t cancel consent — your yes is still yours, every time — and love is never control. We’ll look at respect in the everyday, name the forms abuse and coercive control can take (so they’re easier to see), and know where help is. If any of this is close to home: it is never your fault, anyone can be hurt this way, and you are not alone.",
  scenarios: SCENARIOS,
  categories: [
    { id: "respect-daily", emoji: "🤝", label: "Respect daily" },
    { id: "consent-inside", emoji: "💗", label: "Consent inside" },
    { id: "spot-abuse-control", emoji: "🚩", label: "Spot abuse & control" },
    { id: "safety-and-help", emoji: "🆘", label: "Safety & help" },
    { id: "never-your-fault", emoji: "💛", label: "Never your fault" },
    { id: "tools-and-help", emoji: "🧰", label: "Tools & help" },
  ],
  badge: {
    title: "Respect at Home 🏠",
    blurb: "You know marriage doesn’t cancel consent and love is never control; you can name the forms of abuse and coercive control; and you know help is real and reachable. If it’s ever close to home, it’s not your fault and you’re not alone. 💛",
  },
  helpLine: "Abuse is never the fault of the person being hurt — the responsibility is only the person choosing to harm, and anyone of any gender can be a victim. You deserve respect and safety. In India, the Protection of Women from Domestic Violence Act 2005 covers physical, emotional, sexual and economic abuse (protection orders & maintenance). Reach a trusted person, the Women Helpline 181, women-in-distress 1091, or emergency 112. Leaving can be the riskiest time — a safety plan and support help.",
  helpLabel: "Get help · 181 / 1091 / 112",
  reassure: "If this is close to home: abuse is never your fault — the responsibility lies only with the person choosing to harm — and you deserve respect and safety. Anyone, of any gender, can be hurt this way, and you are not alone. Reach a trusted person, the Women Helpline 181, women-in-distress 1091, or emergency 112. Leaving can be the riskiest time, so a safety plan and support matter. 💛",
  reassureCats: ["spot-abuse-control", "safety-and-help", "never-your-fault"],
};
