// Content for Safety Squad (node g08, ages 6–9, Chapter 2) — reworked to GDD 08 v2 (mechanic-embodying).
// "Spot it, act on it, tell someone." The personal-safety / child-protection game: 84 researched,
// India-grounded scenarios across six categories, each re-encoded to one of the shared v2 play actions
// (reflect / role-play / strike-rewrite / branch / sort / match / build / explore-label / SPOT) — no binary
// "tap the right card", led by deciding real safety dilemmas (branch), rehearsing "No, Go, Tell" (role-play),
// and the NEW signature spot-the-trick verb (find the red flag / lure / online trick). EMPOWER, NEVER
// FRIGHTEN: always "safe/unsafe" (never "good/bad"); nothing is ever the child's fault; tricky-people
// (watch behaviours) over stranger-danger (most harm is from known, trusted people); every unsafe drill ends
// on reassurance ("it's never your fault; telling helps") + Childline 1098. Skills, not anatomy (private =
// swimsuit, deferred to g02). Builds on g02; feeds Boundary Bot (g15) + Firewall (g40). Rendered by the
// shared engine (components/games/v2-engine.tsx). gameId "safety-squad". DO NOT RENAME.

import type { Scenario, V2GameConfig } from "./v2-schema";

const SCENARIOS: Scenario[] = [
  // — Safe & unsafe touch —
  {"id":"ss-001","cat":"safe-unsafe-touch","type":"sort","hook":"Safety Squad drill! Sort the touches.","items":[{"id":"a","text":"A hug you wanted"},{"id":"b","text":"Hitting or pinching"},{"id":"c","text":"A high-five"},{"id":"d","text":"A touch on your private parts"}],"bins":[{"id":"safe","label":"Safe touch"},{"id":"unsafe","label":"Unsafe touch"}],"key":{"a":"safe","b":"unsafe","c":"safe","d":"unsafe"},"relearn":"Safe touches feel caring; unsafe touches hurt or touch private parts.","persona":"any","source":"safe vs unsafe touch"},
  {"id":"ss-002","cat":"safe-unsafe-touch","type":"strike-rewrite","hook":"Grown-ups sometimes say 'good touch / bad touch'.","myth":{"un":"Touch is either 'good' or 'bad' and you must judge it.","re":"We say 'safe' and 'unsafe', so nothing ever feels like your fault.","why":"Safe/unsafe takes any blame off the child."},"relearn":"Safety Squad says safe and unsafe touch.","persona":"educator","source":"language guidance"},
  {"id":"ss-003","cat":"safe-unsafe-touch","type":"branch","hook":"Someone wants to touch your private parts.","options":[{"text":"Say no, get away, and tell a trusted adult","consequence":"You stay safe and a grown-up can help.","outcome":"safe","best":true},{"text":"Stay quiet, unsure","consequence":"Telling is what keeps you safe; you can always tell."}],"debrief":"That's an unsafe touch, no, go, tell, and it's never your fault.","relearn":"No one should touch your private parts; tell a trusted adult.","persona":"any","source":"body safety"},
  {"id":"ss-004","cat":"safe-unsafe-touch","type":"role-play","hook":"You don't want a hug right now.","setup":"Use your words. Say:","yourLine":[{"text":"\"No thanks, not right now.\"","best":true},{"text":"Hug anyway, feeling uncomfortable"}],"relearn":"You can say no to a touch; your body, your rules.","persona":"Faizan-type","source":"consent (links g02) / voice"},
  {"id":"ss-005","cat":"safe-unsafe-touch","type":"strike-rewrite","hook":"\"If someone says 'don't tell', you must obey.\"","myth":{"un":"If someone says keep it secret, you must obey.","re":"Anyone who says 'don't tell' about touch, that's exactly when to tell.","why":"Secrecy about touch is a red flag."},"relearn":"'Don't tell' about touch means tell a trusted adult.","persona":"any","source":"grooming awareness"},
  {"id":"ss-006","cat":"safe-unsafe-touch","type":"role-play","hook":"Tickling was fun but now you want it to stop.","setup":"Say it clearly:","yourLine":[{"text":"\"Stop, please. I've had enough.\"","best":true},{"text":"Keep laughing though you want it to stop"}],"relearn":"Even in fun, stop means stop, for everyone.","persona":"any","source":"consent"},
  {"id":"ss-007","cat":"safe-unsafe-touch","type":"reflect","hook":"Lensy: a touch gives you an 'uh-oh' feeling. Trust it?","prompt":"What do you think?","options":["Yes","Listen to it","Tell someone"],"affirm":"Your 'uh-oh' feeling is a clever warning, listen and tell.","relearn":"Trust your 'uh-oh' feeling and tell a trusted adult.","persona":"any","source":"body cues"},
  {"id":"ss-008","cat":"safe-unsafe-touch","type":"branch","hook":"An older kid wants to play a 'secret touching game'.","options":[{"text":"Say no and tell a trusted adult","consequence":"You stay safe; that's never an okay game.","outcome":"safe","best":true},{"text":"Play because they're older","consequence":"A 'secret touching game' is never okay; tell."}],"debrief":"A 'secret touching game' is never okay, no matter who asks.","relearn":"A 'secret touching game' is unsafe; say no and tell.","persona":"any","source":"grooming awareness"},
  {"id":"ss-009","cat":"safe-unsafe-touch","type":"strike-rewrite","hook":"\"If something unsafe happens, it's the kid's fault.\"","myth":{"un":"If something bad happens, the child is to blame.","re":"It is never the child's fault.","why":"The person who does it is responsible, always."},"relearn":"An unsafe touch is never the child's fault.","persona":"any","source":"non-blame"},
  {"id":"ss-010","cat":"safe-unsafe-touch","type":"sort","hook":"Sort: a safe touch, or unsafe?","items":[{"id":"a","text":"A doctor checking you with a parent there"},{"id":"b","text":"Someone hurting your body"},{"id":"c","text":"A pat on the back you're okay with"},{"id":"d","text":"A secret touch you're told to hide"}],"bins":[{"id":"safe","label":"Safe"},{"id":"unsafe","label":"Unsafe"}],"key":{"a":"safe","b":"unsafe","c":"safe","d":"unsafe"},"relearn":"Caring or health touches (with a parent) are safe; hurting or secret touches are not.","persona":"any","source":"safe vs unsafe touch"},
  {"id":"ss-011","cat":"safe-unsafe-touch","type":"role-play","hook":"A touch feels unsafe and you need it to stop.","setup":"Say your Safety Squad words:","yourLine":[{"text":"\"No! Stop. I'm telling.\"","best":true},{"text":"Freeze and say nothing"}],"relearn":"You can say 'no, stop, I'm telling', strong and right.","persona":"Faizan-type","source":"assertiveness / voice"},
  {"id":"ss-012","cat":"safe-unsafe-touch","type":"reflect","hook":"Lensy: knowing safe from unsafe keeps you the boss of your body. Agree?","prompt":"What do you think?","options":["Yes","I'm the boss","Safe and strong"],"affirm":"Knowing safe from unsafe is real Safety Squad power.","relearn":"Knowing safe vs unsafe keeps you in charge of your body.","persona":"any","source":"empowerment"},
  {"id":"ss-059","cat":"safe-unsafe-touch","type":"branch","hook":"A doctor checks you to stay healthy, with your parent there.","options":[{"text":"Okay, a parent is there and it's for health","consequence":"You understand the safe exception.","outcome":"safe","best":true},{"text":"Panic that all touch is unsafe","consequence":"A health check with a parent is safe."}],"debrief":"A doctor checking you, with a parent there, for health is okay.","relearn":"A doctor with a parent, for health, is a safe exception.","persona":"any","source":"exceptions"},
  {"id":"ss-066","cat":"safe-unsafe-touch","type":"reflect","hook":"Lensy: who decides about your body and private parts?","prompt":"What's true?","options":["Me","Me, and a parent/doctor for health","I'm the boss"],"affirm":"You're the boss of your body, with grown-ups only to keep you healthy.","relearn":"You decide about your body; grown-ups only help keep you healthy.","persona":"any","source":"body autonomy"},
  {"id":"ss-069","cat":"safe-unsafe-touch","type":"strike-rewrite","hook":"\"You must always obey grown-ups, no matter what.\"","myth":{"un":"You must always obey grown-ups, no matter what.","re":"You can say no to anyone if a touch or ask feels unsafe.","why":"Your safety comes first."},"relearn":"You can refuse anything unsafe, even from a grown-up.","persona":"Faizan-type","source":"empowerment"},
  {"id":"ss-077","cat":"safe-unsafe-touch","type":"branch","hook":"Capstone: someone tries an unsafe touch and says keep it secret.","options":[{"text":"No, get away, and tell a trusted adult","consequence":"You used every Safety Squad power, safe!","outcome":"safe","best":true},{"text":"Freeze and keep the secret","consequence":"No, go, tell, and it's never your fault."}],"debrief":"No, go, tell, your Safety Squad superpower, and it's never your fault.","relearn":"No, go, tell, and it's never the child's fault.","persona":"any","source":"consolidation"},
  {"id":"ss-083","cat":"safe-unsafe-touch","type":"reflect","hook":"Lensy: if something feels unsafe, whose fault is it?","prompt":"What's true?","options":["Never mine","Not the child's","The person who did it"],"affirm":"It is never your fault, and telling always helps.","relearn":"Unsafe things are never the child's fault; telling helps.","persona":"any","source":"non-blame"},

  // — Secrets & surprises —
  {"id":"ss-013","cat":"secrets-surprises","type":"sort","hook":"Sort: a happy surprise, or an unsafe secret?","items":[{"id":"a","text":"A birthday surprise (told soon)"},{"id":"b","text":"\"Don't tell your parents I touched you\""},{"id":"c","text":"A gift to reveal at the party"},{"id":"d","text":"\"Keep this touch a secret forever\""}],"bins":[{"id":"surprise","label":"Happy surprise"},{"id":"unsafe","label":"Unsafe secret, tell!"}],"key":{"a":"surprise","b":"unsafe","c":"surprise","d":"unsafe"},"relearn":"Surprises get told happily; unsafe secrets you always tell.","persona":"any","source":"secrets vs surprises"},
  {"id":"ss-014","cat":"secrets-surprises","type":"strike-rewrite","hook":"\"You must keep every secret you're told.\"","myth":{"un":"You must keep every secret you're told.","re":"Never keep a secret about unsafe touch, always tell.","why":"Safety beats a promise to hide."},"relearn":"Never keep a secret about unsafe touch.","persona":"any","source":"secrets"},
  {"id":"ss-015","cat":"secrets-surprises","type":"spot","hook":"Spot the red flag in what this person says.","scene":[{"id":"a","text":"\"Let's plan a surprise party for your mum.\"","trick":false},{"id":"b","text":"\"This is our secret, don't tell your parents.\"","trick":true},{"id":"c","text":"\"Want to play outside with everyone?\"","trick":false}],"why":"'Don't tell your parents' is a red flag, surprises get told soon.","relearn":"'Don't tell your parents' is a red flag; tell them.","persona":"any","source":"grooming awareness"},
  {"id":"ss-016","cat":"secrets-surprises","type":"branch","hook":"Someone says \"you'll get in trouble if you tell.\"","options":[{"text":"Tell a trusted adult anyway","consequence":"You won't be in trouble; telling keeps you safe.","outcome":"safe","best":true},{"text":"Stay quiet, scared of trouble","consequence":"You won't be in trouble for telling; telling helps."}],"debrief":"You won't be in trouble for telling, telling is brave.","relearn":"Telling about an unsafe secret is safe and brave.","persona":"any","source":"disclosure"},
  {"id":"ss-017","cat":"secrets-surprises","type":"reflect","hook":"Lensy: a secret that makes your tummy feel bad, what do you do?","prompt":"What do you think?","options":["Tell someone","Share with a grown-up","Don't keep it"],"affirm":"A secret that feels bad inside is one to share with a trusted adult.","relearn":"If a secret feels bad, tell a trusted adult.","persona":"any","source":"body cues"},
  {"id":"ss-018","cat":"secrets-surprises","type":"strike-rewrite","hook":"\"A promise means you can never tell.\"","myth":{"un":"If you promised, you can never tell.","re":"A promise to hide something unsafe doesn't count; you can still tell.","why":"No promise outranks your safety."},"relearn":"A promise to hide something unsafe doesn't count.","persona":"any","source":"disclosure"},
  {"id":"ss-019","cat":"secrets-surprises","type":"sort","hook":"Sort: keep for now (happy), or tell right away?","items":[{"id":"a","text":"A wrapped gift for the party"},{"id":"b","text":"An unsafe touch"},{"id":"c","text":"A surprise visit"},{"id":"d","text":"Someone hurting you"}],"bins":[{"id":"keep","label":"Keep (happy, told soon)"},{"id":"tell","label":"Tell right away"}],"key":{"a":"keep","b":"tell","c":"keep","d":"tell"},"relearn":"Happy surprises can wait; anything unsafe, tell right away.","persona":"any","source":"secrets vs surprises"},
  {"id":"ss-020","cat":"secrets-surprises","type":"branch","hook":"A 'friend' says \"give me your pen or I'll tell your secret.\"","options":[{"text":"Say \"that's not how friends act\" and tell a trusted adult","consequence":"The threat fizzles; a grown-up helps.","outcome":"safe","best":true},{"text":"Hand over the pen","consequence":"It works once, so they'll repeat it; tell instead."}],"debrief":"Using a secret as a threat isn't friendship; tell an adult.","relearn":"A friend who blackmails you isn't a friend; tell.","persona":"any","source":"coercion / safeguarding"},
  {"id":"ss-062","cat":"secrets-surprises","type":"reflect","hook":"Lensy: surprises end with a smile; unsafe secrets you tell. Got it?","prompt":"What do you think?","options":["Yes","Surprises smile, secrets tell","Got it"],"affirm":"Surprises end happily; unsafe secrets always get told.","relearn":"Surprises end happily; unsafe secrets you always tell.","persona":"any","source":"secrets vs surprises"},
  {"id":"ss-074","cat":"secrets-surprises","type":"branch","hook":"Someone says \"if you tell, I'll be sad / angry.\"","options":[{"text":"Tell a trusted adult anyway","consequence":"Your safety matters more than their feelings.","outcome":"safe","best":true},{"text":"Stay quiet to protect their feelings","consequence":"Your safety comes first; tell anyway."}],"debrief":"Someone's feelings don't outrank your safety, tell.","relearn":"Tell about unsafe things even if someone might be upset.","persona":"any","source":"disclosure"},

  // — My trusted grown-ups —
  {"id":"ss-021","cat":"trusted-adults","type":"build","hook":"Build your Safety Squad of trusted grown-ups.","prompt":"Pick 3-5 grown-ups you can always tell.","pieces":["a parent","a grandparent","a teacher","a guardian","an aunt or uncle"],"mode":"assemble","key":["a parent","a grandparent","a teacher","a guardian","an aunt or uncle"],"relearn":"Pick 3-5 trusted grown-ups, your safety squad.","persona":"any","source":"trusted-adults network"},
  {"id":"ss-022","cat":"trusted-adults","type":"build","hook":"Learn the Safety Squad move for unsafe moments.","prompt":"Put it in order.","pieces":["say No","Go away","Tell a trusted adult"],"mode":"sequence","key":["say No","Go away","Tell a trusted adult"],"relearn":"No, Go, Tell, say no, get away, tell a trusted adult.","persona":"any","source":"No-Go-Tell"},
  {"id":"ss-023","cat":"trusted-adults","type":"branch","hook":"You told one grown-up but they didn't help.","options":[{"text":"Tell another, and keep telling until someone helps","consequence":"Someone will help; keep going.","outcome":"safe","best":true},{"text":"Give up","consequence":"If one doesn't help, the next one can."}],"debrief":"Keep telling trusted grown-ups until someone helps.","relearn":"If one grown-up doesn't help, tell another.","persona":"quiet child","source":"keep telling"},
  {"id":"ss-024","cat":"trusted-adults","type":"strike-rewrite","hook":"\"Telling a grown-up is just tattling.\"","myth":{"un":"Telling is just tattling.","re":"Telling to keep safe is brave, not tattling.","why":"Safety telling helps you and others."},"relearn":"Telling to stay safe is brave, not tattling.","persona":"Ananya","source":"telling vs tattling"},
  {"id":"ss-025","cat":"trusted-adults","type":"reflect","hook":"Lensy: in India you can call Childline at 1098 for help. Good to know?","prompt":"What do you think?","options":["Yes","1098 helps kids","Good to know"],"affirm":"Yes, Childline 1098 is there to help children in India.","relearn":"In India, Childline 1098 is a helpline for children.","persona":"India","source":"Childline 1098"},
  {"id":"ss-026","cat":"trusted-adults","type":"role-play","hook":"Something unsafe happened and you feel scared to tell.","setup":"Be brave. Say:","yourLine":[{"text":"\"I need to tell you something that happened.\"","best":true},{"text":"Keep it inside"}],"relearn":"Even when it's scary, telling a trusted adult is right.","persona":"quiet child","source":"disclosure / voice"},
  {"id":"ss-027","cat":"trusted-adults","type":"strike-rewrite","hook":"\"If it already happened, it's too late to tell.\"","myth":{"un":"If it already happened, you can't tell anymore.","re":"You can always tell, even later.","why":"It's never too late to get help."},"relearn":"It's never too late to tell.","persona":"any","source":"disclosure"},
  {"id":"ss-028","cat":"trusted-adults","type":"sort","hook":"Sort: a trusted grown-up to tell, or not the right person?","items":[{"id":"a","text":"A parent who listens"},{"id":"b","text":"Someone who says 'don't tell'"},{"id":"c","text":"A caring teacher"},{"id":"d","text":"Someone who made you feel unsafe"}],"bins":[{"id":"trusted","label":"Trusted grown-up"},{"id":"no","label":"Not the right person"}],"key":{"a":"trusted","b":"no","c":"trusted","d":"no"},"relearn":"Trusted grown-ups listen and help; not the ones who say 'don't tell'.","persona":"any","source":"trusted adults"},
  {"id":"ss-029","cat":"trusted-adults","type":"reflect","hook":"Lensy: whose fault is it if something unsafe happens?","prompt":"What's true?","options":["Never the child's","Not mine","The grown-up who did it"],"affirm":"It is never the child's fault, and telling helps it stop.","relearn":"It's never the child's fault; telling brings help.","persona":"any","source":"non-blame"},
  {"id":"ss-030","cat":"trusted-adults","type":"branch","hook":"Practise the plan: if you felt unsafe today, what would you do?","options":[{"text":"Go to a trusted adult on my squad and tell","consequence":"You know your plan before you ever need it.","outcome":"prepared","best":true},{"text":"Not sure / no one","consequence":"Knowing who you'd tell, in advance, is real safety."}],"debrief":"Knowing who you'd tell, before you need to, is real safety.","relearn":"Have a trusted adult in mind before you ever need them.","persona":"any","source":"planning"},
  {"id":"ss-060","cat":"trusted-adults","type":"role-play","hook":"A friend tells you something unsafe happened to them.","setup":"Help them. Say:","yourLine":[{"text":"\"Let's tell a trusted grown-up together.\"","best":true},{"text":"\"Keep it a secret.\""}],"relearn":"You can help a friend by telling a trusted grown-up together.","persona":"Ananya","source":"peer support / voice"},
  {"id":"ss-065","cat":"trusted-adults","type":"branch","hook":"You're worried a grown-up won't believe you.","options":[{"text":"Tell anyway, and keep telling till someone listens","consequence":"A trusted grown-up will listen and help.","outcome":"safe","best":true},{"text":"Stay silent","consequence":"Keep telling; you deserve to be heard."}],"debrief":"Keep telling trusted grown-ups; you deserve to be heard.","relearn":"Keep telling until a trusted grown-up listens.","persona":"quiet child","source":"keep telling"},
  {"id":"ss-070","cat":"trusted-adults","type":"sort","hook":"Sort: telling, or tattling-to-get-someone-in-trouble?","items":[{"id":"a","text":"Telling because someone is unsafe"},{"id":"b","text":"Telling to get a kid in trouble for fun"},{"id":"c","text":"Telling about a scary secret"},{"id":"d","text":"Telling tales just to be mean"}],"bins":[{"id":"safe","label":"Safety telling"},{"id":"tattle","label":"Just tattling"}],"key":{"a":"safe","b":"tattle","c":"safe","d":"tattle"},"relearn":"Telling to keep someone safe is different from mean tattling.","persona":"Ananya","source":"telling vs tattling"},
  {"id":"ss-075","cat":"trusted-adults","type":"role-play","hook":"Practise telling, with Lensy as your trusted grown-up.","setup":"Try the words:","yourLine":[{"text":"\"Something unsafe happened and I need help.\"","best":true},{"text":"\"Never mind, forget it.\""}],"relearn":"Practising the words makes telling easier when it's real.","persona":"any","source":"disclosure / voice"},
  {"id":"ss-079","cat":"trusted-adults","type":"reflect","hook":"Lensy: you have a whole squad of grown-ups. How does that feel?","prompt":"Pick one.","options":["Safe","Not alone","Strong"],"affirm":"You're never alone, your Safety Squad of grown-ups has your back.","relearn":"You have a team of trusted grown-ups; you're not alone.","persona":"any","source":"trusted adults"},
  {"id":"ss-084","cat":"trusted-adults","type":"role-play","hook":"Lead the Safety Squad cheer to remember your moves.","setup":"Say it loud:","yourLine":[{"text":"\"Spot it, act on it, tell someone!\"","best":true},{"text":"Stay quiet"}],"relearn":"Safety Squad hero: spot it, act on it, and tell someone.","persona":"any","source":"empowerment / voice"},

  // — Tricky people —
  {"id":"ss-031","cat":"tricky-people","type":"strike-rewrite","hook":"\"Only strangers are dangerous.\"","myth":{"un":"Only strangers are dangerous.","re":"Most unsafe people are known; watch what someone DOES, not whether you know them.","why":"Tricky is about behaviour, not familiarity."},"relearn":"Watch behaviours, not just 'strangers'.","persona":"educator","source":"tricky people"},
  {"id":"ss-032","cat":"tricky-people","type":"spot","hook":"Spot the tricky-person move.","scene":[{"id":"a","text":"A grown-up asks YOU (a kid) to help find their puppy","trick":true},{"id":"b","text":"A grown-up asks another grown-up for directions","trick":false},{"id":"c","text":"A teacher helps the class line up","trick":false}],"why":"Safe adults ask other adults for help, not children.","relearn":"A grown-up asking a kid for help is a trick, don't go, tell.","persona":"any","source":"lures"},
  {"id":"ss-033","cat":"tricky-people","type":"branch","hook":"Someone offers you sweets to come with them, alone.","options":[{"text":"Say no and tell a trusted adult","consequence":"You stay safe; gifts to go off alone are a trick.","outcome":"safe","best":true},{"text":"Go for the sweets","consequence":"Gifts to lure you away are a trick; say no and tell."}],"debrief":"Gifts to go off alone are a lure; say no and tell.","relearn":"Don't go off alone for sweets or gifts; tell a grown-up.","persona":"any","source":"lures"},
  {"id":"ss-034","cat":"tricky-people","type":"spot","hook":"A family password keeps you safe. Spot who's okay to go with.","scene":[{"id":"a","text":"A pickup grown-up who knows your family password","trick":false},{"id":"b","text":"\"Your mum sent me\", but no password","trick":true},{"id":"c","text":"Your own parent at the gate","trick":false}],"why":"No password, no going, even if they say your mum sent them.","relearn":"A safe pickup grown-up knows your family password.","persona":"any","source":"family password"},
  {"id":"ss-035","cat":"tricky-people","type":"strike-rewrite","hook":"\"Nice-seeming people are always safe.\"","myth":{"un":"Nice-seeming people are always safe.","re":"Tricky people often seem nice; judge by what they ask you to do.","why":"Niceness isn't proof of safety."},"relearn":"Watch what someone asks you to do, not how nice they seem.","persona":"any","source":"grooming awareness"},
  {"id":"ss-036","cat":"tricky-people","type":"branch","hook":"Someone wants you to come somewhere private, away from others.","options":[{"text":"Say no and stay where other people are","consequence":"You stay safe in sight of others.","outcome":"safe","best":true},{"text":"Go along to be polite","consequence":"Stay where others are; don't go off alone."}],"debrief":"Stay where other people are; don't go off alone with someone.","relearn":"Don't go somewhere private alone with someone; stay in sight.","persona":"any","source":"safety rules"},
  {"id":"ss-037","cat":"tricky-people","type":"role-play","hook":"A grown-up asks you to do something that feels unsafe.","setup":"You're allowed to refuse. Say:","yourLine":[{"text":"\"No. I need to check with my parent first.\"","best":true},{"text":"Do it because they're a grown-up"}],"relearn":"You can say no to anyone, even a grown-up, if it feels unsafe.","persona":"Faizan-type","source":"empowerment / voice"},
  {"id":"ss-038","cat":"tricky-people","type":"reflect","hook":"Lensy: you get an 'uh-oh' feeling around someone. What do you do?","prompt":"What's smart?","options":["Trust it","Get to a trusted adult","Both"],"affirm":"Trust your 'uh-oh' feeling and head to a trusted adult.","relearn":"Trust your 'uh-oh' and get to a trusted adult.","persona":"any","source":"body cues"},
  {"id":"ss-039","cat":"tricky-people","type":"spot","hook":"Spot the trick (the others are fine).","scene":[{"id":"a","text":"\"It's our secret, don't tell.\"","trick":true},{"id":"b","text":"\"Let's ask your parent first.\"","trick":false},{"id":"c","text":"\"Want to join the whole group?\"","trick":false}],"why":"'Our secret, don't tell' is a tricky-person move.","relearn":"'Our secret' plus 'don't tell' is a trick; tell anyway.","persona":"any","source":"grooming awareness"},
  {"id":"ss-040","cat":"tricky-people","type":"branch","hook":"You're a bit unsure whether something is safe.","options":[{"text":"Check with a parent first","consequence":"When unsure, checking is always okay.","outcome":"safe","best":true},{"text":"Just decide alone","consequence":"When unsure, it's smart to check with a parent."}],"debrief":"When unsure, checking with a parent first is always okay.","relearn":"If you're unsure, check with a trusted grown-up first.","persona":"any","source":"safety rules"},
  {"id":"ss-061","cat":"tricky-people","type":"sort","hook":"Sort: a tricky-person move, or just normal?","items":[{"id":"a","text":"Asking a kid to keep a secret from parents"},{"id":"b","text":"A teacher giving the class homework"},{"id":"c","text":"Offering sweets to come away alone"},{"id":"d","text":"A friend inviting you to a group game"}],"bins":[{"id":"tricky","label":"Tricky move"},{"id":"normal","label":"Normal"}],"key":{"a":"tricky","b":"normal","c":"tricky","d":"normal"},"relearn":"Secrets-from-parents and come-away-alone are tricky moves.","persona":"any","source":"tricky people"},
  {"id":"ss-067","cat":"tricky-people","type":"role-play","hook":"Someone you met online wants to meet, and says keep it secret.","setup":"Use your safety line:","yourLine":[{"text":"\"No. I'm telling a trusted adult.\"","best":true},{"text":"\"Okay, our secret.\""}],"relearn":"Never meet an online contact; a 'keep it secret' meet-up is a red flag.","persona":"Reyansh","source":"online safety / voice"},
  {"id":"ss-071","cat":"tricky-people","type":"branch","hook":"A grown-up at the park keeps asking you to come help them, alone.","options":[{"text":"Say no, move toward your group, and tell a trusted adult","consequence":"You stay safe and get help.","outcome":"safe","best":true},{"text":"Go help to be polite","consequence":"Adults ask adults; don't go off alone, tell a grown-up."}],"debrief":"Adults ask other adults for help; don't go off alone.","relearn":"Don't go off alone to 'help' a grown-up; tell a trusted adult.","persona":"any","source":"lures"},
  {"id":"ss-076","cat":"tricky-people","type":"spot","hook":"Spot the trick: which one means 'don't go'?","scene":[{"id":"a","text":"\"Come see the puppies in my house, just you.\"","trick":true},{"id":"b","text":"\"Let's all play tag here.\"","trick":false},{"id":"c","text":"\"Ask your dad if you can come over.\"","trick":false}],"why":"'Come alone to my house' is a lure, don't go, tell.","relearn":"'Come alone' to a private place is a trick; don't go, tell.","persona":"any","source":"lures"},
  {"id":"ss-081","cat":"tricky-people","type":"reflect","hook":"Lensy: judge people by what they ask you to do, not how they look. Agree?","prompt":"What do you think?","options":["Yes","By behaviour","Not by looks"],"affirm":"Yes, watch behaviours, that's how Safety Squad spots tricky people.","relearn":"Judge by behaviour, not by how someone looks or how nice they seem.","persona":"educator","source":"tricky people"},

  // — If I'm lost —
  {"id":"ss-041","cat":"lost-or-trouble","type":"branch","hook":"You're lost in a busy market.","options":[{"text":"Stay calm-ish and find a safe helper","consequence":"You get help and find your family.","outcome":"safe","best":true},{"text":"Run around panicking","consequence":"Staying put and finding a helper works better."}],"debrief":"If lost: stay calm-ish, stay put or find a safe helper.","relearn":"If you're lost, stay calm and find a safe helper.","persona":"any","source":"if lost"},
  {"id":"ss-042","cat":"lost-or-trouble","type":"spot","hook":"You're lost. Spot the safe helper.","scene":[{"id":"a","text":"A police officer in uniform","trick":false},{"id":"b","text":"A shop worker with a nametag","trick":false},{"id":"c","text":"A stranger saying 'come to my car to find your mum'","trick":true}],"why":"Choose uniforms and nametags (or a parent with kids), not a car with a stranger.","relearn":"Good helpers: police, staff with nametags, or a parent with kids.","persona":"any","source":"safe helpers"},
  {"id":"ss-043","cat":"lost-or-trouble","type":"reflect","hook":"Lensy: do you know a parent's phone number by heart?","prompt":"How about learning it?","options":["I do","I'll learn it","Good idea"],"affirm":"Knowing a parent's number helps a safe helper reach your family.","relearn":"Knowing a parent's phone number helps helpers help you.","persona":"any","source":"emergency info"},
  {"id":"ss-044","cat":"lost-or-trouble","type":"branch","hook":"You just got separated from your family.","options":[{"text":"Stay near where you got separated","consequence":"It's easier for them to find you.","outcome":"safe","best":true},{"text":"Wander off looking","consequence":"Staying near where you separated is easier to be found."}],"debrief":"Stay near where you got separated; it's easier to be found.","relearn":"If separated, stay put near where it happened.","persona":"any","source":"if lost"},
  {"id":"ss-045","cat":"lost-or-trouble","type":"sort","hook":"Sort: a safe place if lost, or not safe?","items":[{"id":"a","text":"A shop"},{"id":"b","text":"A quiet alley"},{"id":"c","text":"A library"},{"id":"d","text":"An empty lot"}],"bins":[{"id":"safe","label":"Safe place"},{"id":"no","label":"Not safe"}],"key":{"a":"safe","b":"no","c":"safe","d":"no"},"relearn":"Head to a busy, safe place like a shop or library.","persona":"any","source":"safe places"},
  {"id":"ss-046","cat":"lost-or-trouble","type":"role-play","hook":"You're scared and need help in a crowd.","setup":"It's okay to be loud. Say:","yourLine":[{"text":"\"I need help, I can't find my family!\"","best":true},{"text":"Stay silent and hope"}],"relearn":"It's okay to be loud and ask for help when you're scared.","persona":"any","source":"empowerment / voice"},
  {"id":"ss-047","cat":"lost-or-trouble","type":"reflect","hook":"Lensy: if you feel unsafe, which way do you go?","prompt":"What's safest?","options":["Toward people and helpers","Toward a busy shop","Not away alone"],"affirm":"Head toward people and helpers, not away on your own.","relearn":"If you feel unsafe, go toward people and helpers.","persona":"any","source":"safety rules"},
  {"id":"ss-048","cat":"lost-or-trouble","type":"branch","hook":"Someone says \"I'll help you find your mum, come to my car.\"","options":[{"text":"Say no; find a uniform or nametag helper instead","consequence":"You pick a truly safe helper.","outcome":"safe","best":true},{"text":"Go to the car","consequence":"Don't go to a car; choose a uniform/nametag helper."}],"debrief":"Don't go to a car with anyone; pick a uniformed or nametag helper.","relearn":"Never go to a car; choose a safe helper instead.","persona":"any","source":"lures"},
  {"id":"ss-064","cat":"lost-or-trouble","type":"spot","hook":"Spot the safe grown-up to ask if you're lost at the mall.","scene":[{"id":"a","text":"A mum with her own kids","trick":false},{"id":"b","text":"A shop worker with a nametag","trick":false},{"id":"c","text":"A stranger who wants to take you to find your parents","trick":true}],"why":"A parent-with-kids or nametag staff is safer than going off with a stranger.","relearn":"Ask a parent-with-kids or nametag staff if you're lost.","persona":"any","source":"safe helpers"},
  {"id":"ss-072","cat":"lost-or-trouble","type":"reflect","hook":"Lensy: staying calm and finding a helper, is that the hero move?","prompt":"What do you think?","options":["Yes","The hero move","Stay calm, find help"],"affirm":"Staying calm and finding a helper is exactly the hero move.","relearn":"Staying calm and finding a safe helper is the hero move.","persona":"any","source":"empowerment"},
  {"id":"ss-080","cat":"lost-or-trouble","type":"build","hook":"Build your 'if I'm lost' plan.","prompt":"Order the steps.","pieces":["stay calm-ish","stay put or go to a safe place","find a uniform/nametag helper","ask them to call my family"],"mode":"sequence","key":["stay calm-ish","stay put or go to a safe place","find a uniform/nametag helper","ask them to call my family"],"relearn":"Stay calm, stay safe, find a helper, get your family called.","persona":"any","source":"if lost"},

  // — Online safety —
  {"id":"ss-049","cat":"online-safety","type":"spot","hook":"Spot the online red flag.","scene":[{"id":"a","text":"\"Great drawing you posted!\"","trick":false},{"id":"b","text":"\"What's your real name and address?\"","trick":true},{"id":"c","text":"\"Want to play the game together?\"","trick":false}],"why":"Asking for your real name and address is a red flag.","relearn":"Keep your name, address and details private online.","persona":"Reyansh","source":"online safety"},
  {"id":"ss-050","cat":"online-safety","type":"strike-rewrite","hook":"\"People online are who they say they are.\"","myth":{"un":"People online are always who they say they are.","re":"Online, people can pretend to be someone they're not.","why":"You can't see who's really typing."},"relearn":"People online can pretend; stay careful.","persona":"any","source":"online safety"},
  {"id":"ss-051","cat":"online-safety","type":"branch","hook":"A stranger online asks you to send a photo of yourself.","options":[{"text":"Don't send it; tell a trusted adult","consequence":"You stay safe; a grown-up can handle it.","outcome":"safe","best":true},{"text":"Send it to be friendly","consequence":"Don't send photos online; tell a trusted adult."}],"debrief":"Don't send photos to people online; tell a trusted adult.","relearn":"Never send photos to online contacts; tell a grown-up.","persona":"any","source":"online safety"},
  {"id":"ss-052","cat":"online-safety","type":"sort","hook":"Sort: private info to keep secret, or fine to share?","items":[{"id":"a","text":"Your home address"},{"id":"b","text":"Your favourite colour"},{"id":"c","text":"Your school name"},{"id":"d","text":"A game you like"}],"bins":[{"id":"private","label":"Keep private"},{"id":"ok","label":"Fine to share"}],"key":{"a":"private","b":"ok","c":"private","d":"ok"},"relearn":"Keep name, address, school and photos private online.","persona":"Reyansh","source":"online safety"},
  {"id":"ss-053","cat":"online-safety","type":"branch","hook":"A new 'online friend' asks to meet you in real life.","options":[{"text":"Say no and tell a trusted adult","consequence":"You stay safe; never meet an online contact.","outcome":"safe","best":true},{"text":"Agree to meet","consequence":"Never meet an online contact; tell a trusted adult."}],"debrief":"Never meet an online contact in person; tell a trusted adult.","relearn":"Don't meet online contacts in real life; tell a grown-up.","persona":"any","source":"online safety"},
  {"id":"ss-054","cat":"online-safety","type":"strike-rewrite","hook":"\"Secret online chats away from parents are harmless fun.\"","myth":{"un":"Secret online chats, away from parents, are harmless.","re":"'Chat secretly, away from parents' is an online red flag.","why":"Secrecy from parents online is a warning sign."},"relearn":"Secret online chats away from parents are a red flag.","persona":"any","source":"grooming awareness"},
  {"id":"ss-055","cat":"online-safety","type":"branch","hook":"Someone is being mean to you in a game chat.","options":[{"text":"Tell a grown-up (and you can block/leave)","consequence":"You get support; you don't handle it alone.","outcome":"safe","best":true},{"text":"Keep it to yourself","consequence":"Tell a grown-up; you don't handle meanness alone."}],"debrief":"If someone's mean online, tell a grown-up.","relearn":"Tell a grown-up if someone's mean to you online.","persona":"any","source":"online safety"},
  {"id":"ss-056","cat":"online-safety","type":"reflect","hook":"Lensy: same rules online and off, private is private, tell a trusted adult. Agree?","prompt":"What do you think?","options":["Yes","Same rules","Makes sense"],"affirm":"Yes, the same safety rules work online and offline.","relearn":"Keep private things private and tell a trusted adult, online too.","persona":"any","source":"online safety"},
  {"id":"ss-057","cat":"online-safety","type":"spot","hook":"Spot the trick online.","scene":[{"id":"a","text":"A pop-up: 'You won a prize! Click here!'","trick":true},{"id":"b","text":"A game's normal start button","trick":false},{"id":"c","text":"A message from a real friend","trick":false}],"why":"Surprise 'you won!' pop-ups are tricks, ask a grown-up.","relearn":"Surprise 'you won a prize' pop-ups are tricks.","persona":"Reyansh","source":"online safety"},
  {"id":"ss-058","cat":"online-safety","type":"role-play","hook":"You see something online that gives you an 'uh-oh'.","setup":"What do you do? Say:","yourLine":[{"text":"\"I'll close it and tell a trusted adult.\"","best":true},{"text":"Keep looking"}],"relearn":"An online 'uh-oh' means close it and tell a trusted adult.","persona":"any","source":"online safety / voice"},
  {"id":"ss-063","cat":"online-safety","type":"strike-rewrite","hook":"\"It's polite to answer anyone who asks online.\"","myth":{"un":"It's rude not to answer questions online.","re":"You don't owe strangers private info; keep it private.","why":"Safety beats online politeness."},"relearn":"You can keep private info private, even if someone asks.","persona":"Reyansh","source":"online safety"},
  {"id":"ss-068","cat":"online-safety","type":"reflect","hook":"Lensy: be kind online too, treat people how you'd want. Agree?","prompt":"What do you think?","options":["Yes","Kind online too","Treat people well"],"affirm":"Being kind online matters as much as offline.","relearn":"Be kind online, just like in person.","persona":"any","source":"digital citizenship"},
  {"id":"ss-073","cat":"online-safety","type":"sort","hook":"Sort: a safe online move, or risky?","items":[{"id":"a","text":"Keeping your address private"},{"id":"b","text":"Sharing your password with an online 'friend'"},{"id":"c","text":"Telling a grown-up about a creepy message"},{"id":"d","text":"Meeting an online contact alone"}],"bins":[{"id":"safe","label":"Safe move"},{"id":"risky","label":"Risky"}],"key":{"a":"safe","b":"risky","c":"safe","d":"risky"},"relearn":"Keep info private and tell a grown-up; never share passwords or meet alone.","persona":"Reyansh","source":"online safety"},
  {"id":"ss-078","cat":"online-safety","type":"branch","hook":"An online game asks for your real name to 'join the club'.","options":[{"text":"Keep it private and ask a grown-up","consequence":"You protect your info; a grown-up can check it.","outcome":"safe","best":true},{"text":"Type in your real details","consequence":"Keep real details private; ask a grown-up first."}],"debrief":"Keep private info private online; check with a grown-up.","relearn":"Don't give real details online; ask a trusted grown-up.","persona":"Reyansh","source":"online safety"},
  {"id":"ss-082","cat":"online-safety","type":"reflect","hook":"Lensy: what's your online safety motto?","prompt":"Pick one.","options":["Private is private","People can pretend","Tell a grown-up","Same rules online"],"affirm":"Carry that online every day. Smart and safe.","relearn":"Keep private info private; people can pretend; tell a grown-up.","persona":"Reyansh","source":"consolidation"},
];

export const SAFETY_SQUAD: V2GameConfig = {
  gameId: "safety-squad",
  title: "Safety Squad",
  greet: "Welcome to the Safety Squad! 🦺 You're brave, capable, and never alone. Let's train: spot it, say no, and tell.",
  scenarios: SCENARIOS,
  categories: [
  { id: "safe-unsafe-touch", emoji: "🖐️", label: "Safe & unsafe touch" },
  { id: "secrets-surprises", emoji: "🎁", label: "Secrets & surprises" },
  { id: "trusted-adults", emoji: "🫂", label: "My trusted grown-ups" },
  { id: "tricky-people", emoji: "🕵️", label: "Tricky people" },
  { id: "lost-or-trouble", emoji: "🧭", label: "If I'm lost" },
  { id: "online-safety", emoji: "📱", label: "Online safety" },
  ],
  badge: {
    title: "Safety Squad Hero! 🦺",
    blurb: "You can spot the tricks, say No-Go-Tell, and keep telling till someone helps — and it's never your fault. 🦺💛",
  },
  helpLine: "If anything ever feels unsafe, tell a trusted grown-up. You can also call Childline — one-zero-nine-eight — it's free, any time.",
  helpLabel: "Get help · Childline 1098",
  reassure: "Remember: it's never your fault, and telling always helps. 💛",
  reassureCats: ["safe-unsafe-touch"],
  buildLabels: { assemble: "That's my Safety Squad! 🦺", sequence: "That's my plan!" },
};
