// Content for Smart Screen Heroes (node g12, ages 6–9, Chapter 2) — NEW v2 build to GDD 12 (mechanic-
// embodying), the early media-literacy game that opens the Values, Rights & Media thread and completes
// Chapter 2. "Real or pretend? You decide." 84 researched, India-aware scenarios across six categories, each
// encoded as one of the shared v2 play actions (branch / reflect / strike-rewrite / sort / spot / role-play /
// build) — no binary "tap the right card", led by smart-screen DILEMMAS (branch ×24), the signature
// spot-the-ad / spot-the-fake scenes (spot), and the balanced-day / healthy-screen builders (build). Teaches:
// real vs pretend on screens, spotting ads & persuasion (their job is to sell), checking what's true (not
// everything online is), smart screen choices & balance, screen hygiene (eyes/posture/sleep, as self-care),
// and being kind & safe online. NOT ANTI-TECH (savvy & balance, never fear or banning — screens are one good
// thing among many); PERSUASION NAMED (ads/auto-play/'free'/'hurry' tricks exposed so the child stays in
// charge); WELLBEING AS SELF-CARE; SAFETY HAND-OFF (online strangers / upsetting content route to a trusted
// grown-up & Safety Squad — Childline 1098). Builds on g11 (Not Fair, Not Funny); prereq g11. Rendered by the
// shared engine (components/games/v2-engine.tsx). gameId "smart-screen" (the GDD/library "smart-screen-heroes"
// is design-doc only — config must use the engine-host registry id). DO NOT RENAME.

import type { Scenario, V2GameConfig } from "./v2-schema";

const SCENARIOS: Scenario[] = [
  // — Real vs pretend on screens —
  {"id":"sh-001","cat":"real-or-pretend","type":"spot","hook":"Smart Screen Heroes, look closely! Spot the pretend one.","scene":[{"id":"a","text":"A cartoon superhero flying","trick":true},{"id":"b","text":"A video of a real dog","trick":false},{"id":"c","text":"A photo of your school","trick":false}],"why":"A flying superhero cartoon is pretend, not real life.","relearn":"Lots of fun screen stuff is pretend, not real life.","persona":"Reyansh","source":"media literacy"},
  {"id":"sh-002","cat":"real-or-pretend","type":"strike-rewrite","hook":"\"If it's on a screen, it must be real.\"","myth":{"un":"If it's on a screen, it's real.","re":"Screens show real AND pretend; you get to tell which.","why":"Cartoons, games and edits are made-up fun."},"relearn":"Screens mix real and pretend; a Smart Screen Hero tells them apart.","persona":"Reyansh","source":"media literacy"},
  {"id":"sh-003","cat":"real-or-pretend","type":"sort","hook":"Sort: real, or pretend/made-up?","items":[{"id":"a","text":"A video call with grandma"},{"id":"b","text":"A talking cartoon animal"},{"id":"c","text":"A magic potion in a game"},{"id":"d","text":"A photo of your dinner"}],"bins":[{"id":"real","label":"Real"},{"id":"pretend","label":"Pretend"}],"key":{"a":"real","b":"pretend","c":"pretend","d":"real"},"relearn":"You can sort real from pretend on a screen.","persona":"any","source":"media literacy"},
  {"id":"sh-004","cat":"real-or-pretend","type":"branch","hook":"A video shows someone with 'perfect' looks and a 'perfect' life.","options":[{"text":"Remember it's often edited and posed","consequence":"You enjoy it without feeling 'less than'.","outcome":"savvy","best":true},{"text":"Believe their life is really like that","consequence":"Screens show edited highlights, not the whole real life."}],"debrief":"People online show their edited best, not their whole real life.","relearn":"Online 'perfect' is usually edited and posed, not real.","persona":"any","source":"media literacy / body image"},
  {"id":"sh-005","cat":"real-or-pretend","type":"strike-rewrite","hook":"\"Photos and videos online are always exactly true.\"","myth":{"un":"Photos and videos online are always exactly true.","re":"Many are filtered, edited or staged to look a certain way.","why":"Tools can change how things look easily."},"relearn":"Online pictures can be filtered or staged; they aren't always true.","persona":"Reyansh","source":"media literacy"},
  {"id":"sh-006","cat":"real-or-pretend","type":"spot","hook":"Spot the edited/filtered one.","scene":[{"id":"a","text":"A face with a sparkly filter and huge eyes","trick":true},{"id":"b","text":"A plain photo of a tree","trick":false},{"id":"c","text":"A normal class group photo","trick":false}],"why":"The sparkly, big-eyed face is filtered, not how someone really looks.","relearn":"Filters change how people really look.","persona":"any","source":"media literacy"},
  {"id":"sh-007","cat":"real-or-pretend","type":"reflect","hook":"Lensy: knowing what's real vs pretend, does that make screens more fun or less?","prompt":"What do you think?","options":["More fun","I enjoy it smarter","Less fooled"],"affirm":"Knowing the difference means you enjoy screens AND don't get fooled.","relearn":"Telling real from pretend lets you enjoy screens wisely.","persona":"any","source":"media literacy"},
  {"id":"sh-008","cat":"real-or-pretend","type":"branch","hook":"A game character does amazing stunts that look real.","options":[{"text":"Enjoy it as game fun, not real life","consequence":"You have fun and stay grounded.","outcome":"savvy","best":true},{"text":"Try the dangerous stunt for real","consequence":"Game stunts are pretend; copying them can hurt you."}],"debrief":"Game stunts are pretend; don't copy risky ones in real life.","relearn":"What's safe in a game can be dangerous in real life.","persona":"Reyansh","source":"media literacy / safety"},
  {"id":"sh-009","cat":"real-or-pretend","type":"reflect","hook":"Lensy: a Smart Screen Hero asks 'is this real or pretend?' Will you?","prompt":"What do you think?","options":["Yes","Every time","I'll check"],"affirm":"That one question is a Smart Screen Hero's superpower.","relearn":"Asking 'real or pretend?' is a screen superpower.","persona":"any","source":"media literacy"},
  // — Spotting ads (they want to sell) —
  {"id":"sh-010","cat":"spot-the-ad","type":"spot","hook":"Spot the ad (it wants you to buy something).","scene":[{"id":"a","text":"\"Buy the new SuperFizz drink now!\"","trick":true},{"id":"b","text":"A friend's drawing they shared","trick":false},{"id":"c","text":"A video about how rainbows form","trick":false}],"why":"\"Buy now!\" means it's an ad, made to sell you something.","relearn":"An ad's job is to get you to buy something.","persona":"Reyansh","source":"advertising literacy"},
  {"id":"sh-011","cat":"spot-the-ad","type":"strike-rewrite","hook":"\"If my favourite YouTuber loves a toy, it must be the best.\"","myth":{"un":"If a YouTuber shows a toy, it must be the best.","re":"Sometimes they're paid to show it, that's an ad in disguise.","why":"Being shown a product isn't the same as it being great."},"relearn":"A favourite person showing a product can be a paid ad.","persona":"Reyansh","source":"influencer marketing"},
  {"id":"sh-012","cat":"spot-the-ad","type":"sort","hook":"Sort: an ad (selling), or just content?","items":[{"id":"a","text":"\"This game is FREE, download now!\""},{"id":"b","text":"A song you like"},{"id":"c","text":"\"Get yours before they sell out!\""},{"id":"d","text":"A how-to-draw video"}],"bins":[{"id":"ad","label":"Ad (selling)"},{"id":"content","label":"Just content"}],"key":{"a":"ad","b":"content","c":"ad","d":"content"},"relearn":"Ads push you to buy or download; content is just to enjoy or learn.","persona":"any","source":"advertising literacy"},
  {"id":"sh-013","cat":"spot-the-ad","type":"branch","hook":"A game says it's 'free' but keeps asking you to buy gems to win.","options":[{"text":"Don't buy; tell a grown-up it keeps asking","consequence":"You spot the trick; no surprise charges.","outcome":"savvy","best":true},{"text":"Tap 'buy' to win faster","consequence":"'Free' games often push you to spend; check with a grown-up."}],"debrief":"'Free' games often try to get you to spend, that's the catch.","relearn":"'Free' often hides 'pay to win'; ask a grown-up before buying.","persona":"Reyansh","source":"in-app purchases"},
  {"id":"sh-014","cat":"spot-the-ad","type":"reflect","hook":"Lensy: what does every ad really want from you?","prompt":"Pick the best.","options":["To buy/want something","Your attention","Your money"],"affirm":"Ads want you to buy or want something, knowing that is power.","relearn":"Ads want you to buy or want something; spotting that protects you.","persona":"any","source":"persuasive intent"},
  {"id":"sh-015","cat":"spot-the-ad","type":"spot","hook":"Spot the hidden ad in the video.","scene":[{"id":"a","text":"A toy review that says 'this brand paid me'","trick":true},{"id":"b","text":"A clip of real puppies","trick":false},{"id":"c","text":"A maths trick explained","trick":false}],"why":"A paid review is an ad, even if it looks like a normal video.","relearn":"Paid reviews are ads, even when they look like normal videos.","persona":"Reyansh","source":"sponsored content"},
  {"id":"sh-016","cat":"spot-the-ad","type":"strike-rewrite","hook":"\"Ads always tell the whole truth.\"","myth":{"un":"Ads tell you the whole truth about a product.","re":"Ads show only the good bits to make you want it.","why":"Their job is to sell, not to be balanced."},"relearn":"Ads show only the good bits; they're not the whole story.","persona":"any","source":"advertising literacy"},
  {"id":"sh-017","cat":"spot-the-ad","type":"role-play","hook":"An ad makes you really want a toy right now.","setup":"Pause and say:","yourLine":[{"text":"\"That's an ad, I'll think about it and ask a grown-up.\"","best":true},{"text":"\"I need it NOW!\""}],"relearn":"Naming an ad and pausing beats buying on impulse.","persona":"Reyansh","source":"self-regulation / voice"},
  {"id":"sh-018","cat":"spot-the-ad","type":"branch","hook":"A pop-up says 'You WON a prize! Tap here!'","options":[{"text":"Don't tap; show a grown-up","consequence":"You avoid a trick; surprise 'wins' are usually fake.","outcome":"savvy","best":true},{"text":"Tap to get the prize","consequence":"Surprise 'you won' pop-ups are almost always tricks."}],"debrief":"Surprise 'you won!' pop-ups are tricks, don't tap.","relearn":"Surprise prize pop-ups are tricks; show a grown-up.","persona":"any","source":"scams (links g08)"},
  // — Not everything online is true —
  {"id":"sh-019","cat":"is-it-true","type":"strike-rewrite","hook":"\"If lots of people shared it, it must be true.\"","myth":{"un":"If something is shared a lot, it must be true.","re":"Lots of shares doesn't make something true.","why":"False things can spread fast too."},"relearn":"Popular online doesn't mean true.","persona":"any","source":"misinformation"},
  {"id":"sh-020","cat":"is-it-true","type":"branch","hook":"A forwarded message says something scary that might not be true.","options":[{"text":"Check with a grown-up before believing or sharing","consequence":"You don't spread a scare that may be false.","outcome":"savvy","best":true},{"text":"Believe it and forward to everyone","consequence":"Forwards aren't always true; check before sharing."}],"debrief":"A forward isn't proof; check with a grown-up before sharing.","relearn":"Check before you believe or share a forward.","persona":"any","source":"misinformation"},
  {"id":"sh-021","cat":"is-it-true","type":"sort","hook":"Sort: a good way to check if something's true, or not?","items":[{"id":"a","text":"Ask a trusted grown-up"},{"id":"b","text":"Believe it because it's funny"},{"id":"c","text":"Look for it on a trusted site"},{"id":"d","text":"Trust it because a friend shared it"}],"bins":[{"id":"good","label":"Good check"},{"id":"no","label":"Not a real check"}],"key":{"a":"good","b":"no","c":"good","d":"no"},"relearn":"Real checks: ask a grown-up, look at trusted sources.","persona":"any","source":"information literacy"},
  {"id":"sh-022","cat":"is-it-true","type":"reflect","hook":"Lensy: not everything online is true. Surprised?","prompt":"What do you think?","options":["A bit","Makes sense","I'll be careful"],"affirm":"Some things online are wrong or made-up, checking keeps you smart.","relearn":"Not everything online is true; check before you believe.","persona":"any","source":"misinformation"},
  {"id":"sh-023","cat":"is-it-true","type":"strike-rewrite","hook":"\"A confident voice means it's true.\"","myth":{"un":"If someone sounds sure, they must be right.","re":"Sounding confident isn't the same as being correct.","why":"Anyone can sound sure online, even when wrong."},"relearn":"Confident isn't the same as correct.","persona":"any","source":"critical thinking"},
  {"id":"sh-024","cat":"is-it-true","type":"branch","hook":"A video gives 'facts' that sound strange.","options":[{"text":"Double-check with a grown-up or a book","consequence":"You learn what's actually true.","outcome":"savvy","best":true},{"text":"Repeat it as fact to friends","consequence":"Strange 'facts' are worth checking before repeating."}],"debrief":"If a 'fact' sounds off, check it before repeating it.","relearn":"Check surprising 'facts' before you repeat them.","persona":"Reyansh","source":"information literacy"},
  {"id":"sh-025","cat":"is-it-true","type":"reflect","hook":"Lensy: a Smart Screen Hero's question, 'how do I know this is true?'","prompt":"Good question?","options":["Yes","I'll ask it","Smart"],"affirm":"'How do I know it's true?' is a hero-level question.","relearn":"Asking 'how do I know it's true?' keeps you from being fooled.","persona":"any","source":"critical thinking"},
  {"id":"sh-026","cat":"is-it-true","type":"spot","hook":"Spot the one that needs checking.","scene":[{"id":"a","text":"\"Eat this sweet and you'll fly!\"","trick":true},{"id":"b","text":"\"Brush your teeth twice a day\"","trick":false},{"id":"c","text":"\"Drink water when thirsty\"","trick":false}],"why":"\"Eat this and fly\" is clearly not true, check wild claims.","relearn":"Wild claims (like 'you'll fly') are signs to check.","persona":"any","source":"critical thinking"},
  // — Smart screen choices & balance —
  {"id":"sh-027","cat":"screen-choices","type":"branch","hook":"You've been on the tablet a long time and there's a sunny day outside.","options":[{"text":"Take a break and go play outside","consequence":"You feel better; screens will still be there later.","outcome":"balanced","best":true},{"text":"Keep watching for hours more","consequence":"Balance feels better than endless screens."}],"debrief":"Balancing screens with play and people feels best.","relearn":"A good screen choice is knowing when to take a break.","persona":"any","source":"screen-time balance"},
  {"id":"sh-028","cat":"screen-choices","type":"strike-rewrite","hook":"\"More screen time is always better.\"","myth":{"un":"More screen time is always better.","re":"A balance of screens, play, people and sleep is best.","why":"Too much of anything crowds out other good things."},"relearn":"Balance beats endless screen time.","persona":"any","source":"screen-time balance"},
  {"id":"sh-029","cat":"screen-choices","type":"sort","hook":"Sort: a great screen choice, or a not-so-great one?","items":[{"id":"a","text":"Watching something that teaches you"},{"id":"b","text":"Skipping sleep to keep watching"},{"id":"c","text":"A video call with family"},{"id":"d","text":"Ignoring everyone to scroll"}],"bins":[{"id":"good","label":"Great choice"},{"id":"no","label":"Not so great"}],"key":{"a":"good","b":"no","c":"good","d":"no"},"relearn":"Good screen choices teach or connect; not-so-great ones cost sleep or people.","persona":"any","source":"screen choices"},
  {"id":"sh-030","cat":"screen-choices","type":"branch","hook":"A grown-up says screen time is over for now.","options":[{"text":"Stop kindly and do something else","consequence":"You keep trust and find other fun.","outcome":"balanced","best":true},{"text":"Beg, sulk or sneak more","consequence":"Stopping when asked keeps screen trust strong."}],"debrief":"Stopping when asked builds the trust that earns more screen time.","relearn":"Stopping screens kindly when asked is a Smart Screen Hero move.","persona":"Reyansh","source":"self-regulation"},
  {"id":"sh-031","cat":"screen-choices","type":"build","hook":"Build a balanced day.","prompt":"Add a good mix.","pieces":["some screen fun","outdoor play","time with people","reading or making","good sleep"],"mode":"assemble","key":["some screen fun","outdoor play","time with people","reading or making","good sleep"],"relearn":"A balanced day has some screens AND play, people, making and sleep.","persona":"Aditi (parent)","source":"balance"},
  {"id":"sh-032","cat":"screen-choices","type":"reflect","hook":"Lensy: what do you love doing that ISN'T a screen?","prompt":"Pick one.","options":["Cricket / play","Drawing","Being with friends","Reading"],"affirm":"Great, screens are one fun thing among many. Keep that mix.","relearn":"Screens are one fun thing; keep lots of others too.","persona":"any","source":"balance"},
  {"id":"sh-033","cat":"screen-choices","type":"branch","hook":"You could watch one more video or finish your homework.","options":[{"text":"Homework first, video as a treat after","consequence":"You feel proud and still get your video.","outcome":"balanced","best":true},{"text":"Endless videos, homework forgotten","consequence":"Screens are better as a treat after the must-dos."}],"debrief":"Screens make a great treat after the important stuff.","relearn":"Do the important things first; screens as a treat after.","persona":"any","source":"self-regulation"},
  {"id":"sh-034","cat":"screen-choices","type":"strike-rewrite","hook":"\"I can't have fun without a screen.\"","myth":{"un":"Fun only happens on a screen.","re":"Tons of fun happens off-screen too, play, friends, making.","why":"Screens are one kind of fun, not the only kind."},"relearn":"Lots of the best fun is off-screen.","persona":"Reyansh","source":"balance"},
  // — Screen hygiene (breaks, eyes, sleep) —
  {"id":"sh-035","cat":"screen-hygiene","type":"branch","hook":"Your eyes feel tired after lots of close screen time.","options":[{"text":"Take a break and look far away (20-20-20)","consequence":"Your eyes feel better; that's screen hygiene.","outcome":"healthy","best":true},{"text":"Keep staring through the tired feeling","consequence":"Eye breaks help; every 20 min, look far for 20 sec."}],"debrief":"The 20-20-20 rule: every 20 min, look 20 feet away for 20 seconds.","relearn":"Give your eyes breaks: look far away every little while.","persona":"any","source":"screen hygiene / eyes"},
  {"id":"sh-036","cat":"screen-hygiene","type":"strike-rewrite","hook":"\"Screens right before bed are fine.\"","myth":{"un":"Watching screens right before bed is fine.","re":"Screen light makes sleep harder; switch off before bed.","why":"The light tricks your brain into staying awake."},"relearn":"Turn screens off a while before bed for good sleep.","persona":"any","source":"screens & sleep"},
  {"id":"sh-037","cat":"screen-hygiene","type":"sort","hook":"Sort: good for your body, or hard on it?","items":[{"id":"a","text":"Taking screen breaks"},{"id":"b","text":"Screens in bed late at night"},{"id":"c","text":"Sitting up with good light"},{"id":"d","text":"Hours hunched in the dark"}],"bins":[{"id":"good","label":"Good for me"},{"id":"no","label":"Hard on me"}],"key":{"a":"good","b":"no","c":"good","d":"no"},"relearn":"Breaks, good light and posture help; late-night dark scrolling doesn't.","persona":"any","source":"screen hygiene"},
  {"id":"sh-038","cat":"screen-hygiene","type":"branch","hook":"It's almost bedtime and you're mid-video.","options":[{"text":"Wind down: screens off, get ready to sleep","consequence":"You sleep better and feel good tomorrow.","outcome":"healthy","best":true},{"text":"Sneak the screen under the blanket","consequence":"Late screens steal good sleep; switch off before bed."}],"debrief":"Screens off before bed means better sleep.","relearn":"Turning screens off before bed helps you sleep well.","persona":"any","source":"screens & sleep"},
  {"id":"sh-039","cat":"screen-hygiene","type":"reflect","hook":"Lensy: how do your eyes/body feel after a long screen stretch with no breaks?","prompt":"Pick one.","options":["Tired eyes","A bit achy","Restless"],"affirm":"That's your body asking for a break, listen and take one.","relearn":"Your body signals when it needs a screen break.","persona":"any","source":"body cues / screen hygiene"},
  {"id":"sh-040","cat":"screen-hygiene","type":"build","hook":"Build a healthy-screen routine.","prompt":"Add the healthy habits.","pieces":["breaks every little while","look far to rest eyes","good light & sit up","no screens in bed","screens off before sleep"],"mode":"assemble","key":["breaks every little while","look far to rest eyes","good light & sit up","no screens in bed","screens off before sleep"],"relearn":"Healthy screens: breaks, eye rests, good posture, none in bed, off before sleep.","persona":"Aditi (parent)","source":"screen hygiene"},
  {"id":"sh-041","cat":"screen-hygiene","type":"role-play","hook":"You've been scrolling a while; time to look after yourself.","setup":"Say it and do it:","yourLine":[{"text":"\"Break time, eyes and legs need a stretch!\"","best":true},{"text":"\"Just five more videos...\""}],"relearn":"Calling your own break is a Smart Screen Hero skill.","persona":"any","source":"self-regulation / voice"},
  {"id":"sh-042","cat":"screen-hygiene","type":"reflect","hook":"Lensy: taking care of your eyes, body and sleep around screens, that's heroic. Agree?","prompt":"What do you think?","options":["Yes","Self-care","I'll do it"],"affirm":"Looking after yourself around screens is what a Smart Screen Hero does.","relearn":"Screen hygiene is caring for your body and sleep.","persona":"any","source":"self-care"},
  // — Being kind & caring online —
  {"id":"sh-043","cat":"caring-online","type":"branch","hook":"You could post a mean comment on a video for a laugh.","options":[{"text":"Don't, be kind online like in person","consequence":"You keep the internet a kinder place.","outcome":"kind","best":true},{"text":"Post the mean comment","consequence":"Mean words online still hurt real people."}],"debrief":"There's a real person behind the screen, be kind online.","relearn":"Be as kind online as you are in person.","persona":"any","source":"digital citizenship"},
  {"id":"sh-044","cat":"caring-online","type":"strike-rewrite","hook":"\"Mean words online don't really hurt.\"","myth":{"un":"Mean comments online don't really hurt anyone.","re":"A real person reads them; online words hurt too.","why":"There's always a person behind the screen."},"relearn":"Online words reach real people and can really hurt.","persona":"any","source":"digital citizenship"},
  {"id":"sh-045","cat":"caring-online","type":"branch","hook":"Someone is being picked on in a group chat.","options":[{"text":"Don't join in; be kind and tell a grown-up","consequence":"You help instead of harm.","outcome":"upstander","best":true},{"text":"Add a laughing emoji","consequence":"Even an emoji feeds an online pile-on."}],"debrief":"Online, you can be an ally too, don't pile on, get help.","relearn":"Be an ally online: don't pile on; support and tell a grown-up.","persona":"Ananya","source":"cyberbullying (links g11)"},
  {"id":"sh-046","cat":"caring-online","type":"branch","hook":"You see something online that upsets or scares you.","options":[{"text":"Close it and tell a trusted grown-up","consequence":"You get help and feel better.","outcome":"safe","best":true},{"text":"Keep watching alone","consequence":"An upsetting thing online is one to tell a grown-up about."}],"debrief":"If something online upsets you, close it and tell a grown-up.","relearn":"Tell a trusted grown-up about anything online that upsets you.","persona":"any","source":"online safety (links g08)"},
  {"id":"sh-047","cat":"caring-online","type":"reflect","hook":"Lensy: what you watch can change how you feel. Noticed that?","prompt":"What do you think?","options":["Yes","Some things cheer me","Some upset me"],"affirm":"Choosing kind, fun things to watch is a way of caring for yourself.","relearn":"What you watch affects your mood; choose kind, good things.","persona":"any","source":"wellbeing / media diet"},
  {"id":"sh-048","cat":"caring-online","type":"sort","hook":"Sort: kind online, or unkind?","items":[{"id":"a","text":"Cheering a friend's post"},{"id":"b","text":"Mocking someone's video"},{"id":"c","text":"Sharing something nice"},{"id":"d","text":"Spreading a mean rumour"}],"bins":[{"id":"kind","label":"Kind online"},{"id":"no","label":"Unkind"}],"key":{"a":"kind","b":"no","c":"kind","d":"no"},"relearn":"Cheering and sharing nicely are kind; mocking and rumours aren't.","persona":"any","source":"digital citizenship"},
  {"id":"sh-049","cat":"caring-online","type":"role-play","hook":"A friend's post is sweet and you want to be kind.","setup":"Leave a good comment. Say:","yourLine":[{"text":"\"This is great, well done!\"","best":true},{"text":"Something mean for a laugh"}],"relearn":"Kind comments make the internet nicer for everyone.","persona":"any","source":"digital citizenship / voice"},
  {"id":"sh-050","cat":"caring-online","type":"strike-rewrite","hook":"\"What I share online disappears and doesn't matter.\"","myth":{"un":"What I share online just disappears.","re":"Things online can stick around and be seen by many.","why":"Once it's out, it's hard to take back."},"relearn":"Think before you share; online things can stick around.","persona":"Reyansh","source":"digital footprint"},
  {"id":"sh-051","cat":"caring-online","type":"branch","hook":"You want to share a funny photo of a friend, but they might not like it.","options":[{"text":"Ask them first before sharing","consequence":"You respect their choice; no hurt feelings.","outcome":"kind","best":true},{"text":"Share it without asking","consequence":"Ask first; it's their picture and their choice too."}],"debrief":"Ask before you share someone else's photo, that's consent online.","relearn":"Ask permission before sharing someone else's photo.","persona":"Sana (sibling)","source":"consent online (links g02)"},
  {"id":"sh-052","cat":"caring-online","type":"reflect","hook":"Lensy: being a kind person online matters as much as offline. Agree?","prompt":"What do you think?","options":["Yes","Same kindness","Always"],"affirm":"Kindness counts everywhere, screen or not.","relearn":"Be the same kind person online as off.","persona":"any","source":"values"},
  {"id":"sh-053","cat":"real-or-pretend","type":"branch","hook":"A video makes a far-off place look like a magic land.","options":[{"text":"Enjoy it, knowing it's edited to look amazing","consequence":"You enjoy the wonder without being fooled.","outcome":"savvy","best":true},{"text":"Believe it's exactly like that","consequence":"Videos often edit places to look more magical than real."}],"debrief":"Even 'real' videos are edited to look their most amazing.","relearn":"Real-looking videos are still edited to impress.","persona":"any","source":"media literacy"},
  {"id":"sh-054","cat":"spot-the-ad","type":"branch","hook":"An ad says 'all the cool kids have this'.","options":[{"text":"Notice the trick: it's pushing you to fit in","consequence":"You decide for yourself, not because of pressure.","outcome":"savvy","best":true},{"text":"Feel you must have it to be cool","consequence":"'All the cool kids' is a sales trick, not the truth."}],"debrief":"'Everyone has it' is a sales trick to make you want it.","relearn":"Ads use 'everyone has it' to pressure you, spot it.","persona":"Reyansh","source":"persuasion tactics"},
  {"id":"sh-055","cat":"is-it-true","type":"role-play","hook":"A friend repeats a wild 'fact' from a video.","setup":"Gently question it. Say:","yourLine":[{"text":"\"Cool, should we check if that's really true?\"","best":true},{"text":"\"Yeah, must be true!\""}],"relearn":"Asking to check together is friendly and smart.","persona":"Reyansh","source":"information literacy / voice"},
  {"id":"sh-056","cat":"screen-choices","type":"reflect","hook":"Lensy: who's the boss, you or the screen?","prompt":"What do you think?","options":["Me!","I decide","I'm in charge"],"affirm":"You're the boss of the screen, not the other way around.","relearn":"You're in charge of the screen, not the screen of you.","persona":"Reyansh","source":"agency / self-regulation"},
  {"id":"sh-057","cat":"screen-hygiene","type":"branch","hook":"You're playing a game and a grown-up calls everyone for dinner.","options":[{"text":"Pause and come to eat with family","consequence":"You enjoy real connection (and food!).","outcome":"balanced","best":true},{"text":"Ignore them to keep playing","consequence":"Meals are for people, not screens; pause and join."}],"debrief":"Screens off at meals keeps family connection.","relearn":"Pause screens for meals and people.","persona":"Aditi (parent)","source":"screen hygiene / connection"},
  {"id":"sh-058","cat":"caring-online","type":"branch","hook":"An online stranger is super friendly, asking many questions.","options":[{"text":"Don't share private info; tell a grown-up","consequence":"You stay safe; friendly strangers can be tricky.","outcome":"safe","best":true},{"text":"Answer everything to be polite","consequence":"Keep info private; tell a grown-up (see Safety Squad)."}],"debrief":"Over-friendly online strangers are a flag.","relearn":"Don't share private info online; tell a grown-up.","persona":"Sana (sibling)","source":"online safety (links g08)"},
  {"id":"sh-059","cat":"real-or-pretend","type":"sort","hook":"Sort: shows real life, or a 'highlight' version?","items":[{"id":"a","text":"Only the best, happiest moments"},{"id":"b","text":"A normal day with boring bits"},{"id":"c","text":"Posed 'perfect' photos"},{"id":"d","text":"A real, unedited video call"}],"bins":[{"id":"highlight","label":"Highlight/edited"},{"id":"real","label":"Real life"}],"key":{"a":"highlight","b":"real","c":"highlight","d":"real"},"relearn":"Online is often a 'highlights reel', not the whole real life.","persona":"any","source":"media literacy / body image"},
  {"id":"sh-060","cat":"spot-the-ad","type":"reflect","hook":"Lensy: you can enjoy ads AND not be fooled by them. Feel that power?","prompt":"What do you think?","options":["Yes","I spot them now","Hero power"],"affirm":"Spotting ads means you choose, they don't choose for you.","relearn":"Spotting ads puts you in charge of your choices.","persona":"Reyansh","source":"advertising literacy"},
  {"id":"sh-061","cat":"is-it-true","type":"branch","hook":"You see a 'news' clip that seems made to scare or anger people.","options":[{"text":"Pause; check it with a grown-up","consequence":"You don't get swept up by a scary clip.","outcome":"savvy","best":true},{"text":"Share it everywhere right away","consequence":"Clips made to scare are exactly the ones to check first."}],"debrief":"Content made to scare or anger is worth checking, not spreading.","relearn":"If something's made to scare or anger you, check before sharing.","persona":"any","source":"misinformation / emotion"},
  {"id":"sh-062","cat":"screen-choices","type":"branch","hook":"Auto-play keeps starting the next video automatically.","options":[{"text":"Decide to stop and choose what's next yourself","consequence":"You break the auto-play trance; you choose.","outcome":"balanced","best":true},{"text":"Let it play forever","consequence":"Auto-play is designed to keep you watching; you can stop it."}],"debrief":"Auto-play wants you to keep watching, you decide when to stop.","relearn":"You can switch off auto-play and choose for yourself.","persona":"Reyansh","source":"design tricks / agency"},
  {"id":"sh-063","cat":"caring-online","type":"strike-rewrite","hook":"\"It's funny to film someone without asking.\"","myth":{"un":"Filming someone without asking is just a laugh.","re":"Film or share someone only if they say it's okay.","why":"Everyone has a say over their own photos and videos."},"relearn":"Ask before filming or sharing someone.","persona":"any","source":"consent online"},
  {"id":"sh-064","cat":"real-or-pretend","type":"spot","hook":"Spot the made-up character.","scene":[{"id":"a","text":"A cartoon mascot selling cereal","trick":true},{"id":"b","text":"A real teacher in a class video","trick":false},{"id":"c","text":"A real footballer playing","trick":false}],"why":"A cartoon mascot is made up, often to sell you something.","relearn":"Made-up mascots are often there to sell to you.","persona":"any","source":"media literacy / advertising"},
  {"id":"sh-065","cat":"is-it-true","type":"reflect","hook":"Lensy: it's okay to say 'I'm not sure if that's true'. Agree?","prompt":"What do you think?","options":["Yes","Better than guessing","I'll check"],"affirm":"Saying 'I'm not sure, let's check' is smart and honest.","relearn":"It's smart to say 'I'm not sure' and check.","persona":"any","source":"critical thinking"},
  {"id":"sh-066","cat":"screen-hygiene","type":"reflect","hook":"Lensy: how do you feel after lots of screens vs after playing outside?","prompt":"Pick one.","options":["Outside feels better","More energy outside","Both are fun, balance helps"],"affirm":"Noticing how you feel helps you find your healthy balance.","relearn":"Notice how different activities make you feel, and balance them.","persona":"any","source":"wellbeing"},
  {"id":"sh-067","cat":"spot-the-ad","type":"sort","hook":"Sort: a trick to make you buy/keep playing, or fair?","items":[{"id":"a","text":"'Only 2 left, hurry!'"},{"id":"b","text":"A clear price and info"},{"id":"c","text":"'Spin to win' pop-ups"},{"id":"d","text":"An honest how-to video"}],"bins":[{"id":"trick","label":"Pushy trick"},{"id":"fair","label":"Fair"}],"key":{"a":"trick","b":"fair","c":"trick","d":"fair"},"relearn":"'Hurry!' and 'spin to win' are pushy tricks; spot them.","persona":"Reyansh","source":"persuasion tactics"},
  {"id":"sh-068","cat":"caring-online","type":"reflect","hook":"Lensy: a Smart Screen Hero leaves the internet a bit kinder. Will you?","prompt":"What do you think?","options":["Yes","One kind act at a time","Count me in"],"affirm":"Every kind click and comment makes the internet better.","relearn":"You can make the internet kinder, one action at a time.","persona":"any","source":"digital citizenship"},
  {"id":"sh-069","cat":"real-or-pretend","type":"strike-rewrite","hook":"\"Everyone online really lives like that.\"","myth":{"un":"People's lives are really as perfect as they look online.","re":"Online shows edited highlights; real life has ordinary and hard bits too.","why":"Nobody posts all their boring or tough moments."},"relearn":"Real lives have ordinary and tough bits, not just the highlights.","persona":"any","source":"media literacy / wellbeing"},
  {"id":"sh-070","cat":"screen-choices","type":"role-play","hook":"You notice you've been scrolling without even enjoying it.","setup":"Take charge. Say:","yourLine":[{"text":"\"This isn't even fun, I'll do something else.\"","best":true},{"text":"\"I'll just keep scrolling.\""}],"relearn":"Noticing 'this isn't fun anymore' is your cue to switch.","persona":"Reyansh","source":"self-regulation / voice"},
  {"id":"sh-071","cat":"is-it-true","type":"branch","hook":"A quiz says 'share to 10 friends or bad luck!'","options":[{"text":"Ignore it; that's not how anything works","consequence":"You don't spread a silly chain message.","outcome":"savvy","best":true},{"text":"Share it just in case","consequence":"'Share or else' messages are tricks, not real."}],"debrief":"'Share or bad luck' messages are tricks, ignore them.","relearn":"Chain messages with threats are fake; don't pass them on.","persona":"any","source":"misinformation"},
  {"id":"sh-072","cat":"caring-online","type":"branch","hook":"Capstone: you see an ad, a mean comment, a sad friend's post.","options":[{"text":"Skip the ad, ignore the mean bait, support your friend","consequence":"You use every hero skill at once.","outcome":"hero","best":true},{"text":"Buy the ad thing and join the mean comment","consequence":"A hero spots ads, skips meanness, helps."}],"debrief":"A Smart Screen Hero does all three at once.","relearn":"Put it together: spot ads, skip meanness, support.","persona":"any","source":"consolidation"},
  {"id":"sh-073","cat":"screen-hygiene","type":"strike-rewrite","hook":"\"Sitting hunched over a screen for hours is fine.\"","myth":{"un":"Sitting hunched at a screen for hours is fine.","re":"Your body needs breaks, movement and good posture.","why":"Long, hunched screen time tires eyes and body."},"relearn":"Break, move and sit well during screen time.","persona":"any","source":"screen hygiene"},
  {"id":"sh-074","cat":"spot-the-ad","type":"strike-rewrite","hook":"\"A free game costs nothing.\"","myth":{"un":"A 'free' game never costs anything.","re":"Many 'free' games push ads and in-app purchases.","why":"That's often how 'free' makes its money."},"relearn":"'Free' games often sell things inside; ask a grown-up.","persona":"Reyansh","source":"in-app purchases"},
  {"id":"sh-075","cat":"real-or-pretend","type":"reflect","hook":"Lensy: you can tell real from pretend, ads from content, true from fake. Hero yet?","prompt":"What do you think?","options":["Getting there","Yes!","Smart Screen Hero"],"affirm":"You've got the hero skills: real-or-pretend, ad-or-not, true-or-fake.","relearn":"Real-or-pretend, ad-or-not, true-or-fake, your hero toolkit.","persona":"any","source":"consolidation"},
  {"id":"sh-076","cat":"is-it-true","type":"sort","hook":"Sort: a trusted source, or be careful?","items":[{"id":"a","text":"A teacher or library book"},{"id":"b","text":"A random anonymous post"},{"id":"c","text":"A known science site (with a grown-up)"},{"id":"d","text":"A 'my uncle says' forward"}],"bins":[{"id":"trusted","label":"More trustworthy"},{"id":"careful","label":"Be careful"}],"key":{"a":"trusted","b":"careful","c":"trusted","d":"careful"},"relearn":"Teachers, books and known sites are safer than random posts and forwards.","persona":"any","source":"information literacy"},
  {"id":"sh-077","cat":"screen-choices","type":"reflect","hook":"Lensy: what's one screen habit you'd like to make smarter?","prompt":"Pick one.","options":["Take breaks","Stop before bed","Check what's true","Be kinder online"],"affirm":"Great goal. Small habit changes make a big difference.","relearn":"You can pick one screen habit to improve.","persona":"any","source":"habit"},
  {"id":"sh-078","cat":"caring-online","type":"role-play","hook":"A friend online seems sad in their messages.","setup":"Reach out. Say:","yourLine":[{"text":"\"You okay? I'm here if you want to talk.\"","best":true},{"text":"Ignore it"}],"relearn":"Kindness online includes checking on friends.","persona":"any","source":"empathy / voice"},
  {"id":"sh-079","cat":"spot-the-ad","type":"spot","hook":"Last ad check, spot it fast.","scene":[{"id":"a","text":"\"Tap to claim your FREE coins!\"","trick":true},{"id":"b","text":"A friend's birthday message","trick":false},{"id":"c","text":"A nature documentary clip","trick":false}],"why":"'Tap to claim free coins' is an ad/trick to grab your attention or money.","relearn":"'Free coins, tap now' is an ad trick; don't tap.","persona":"Reyansh","source":"advertising / scams"},
  {"id":"sh-080","cat":"screen-hygiene","type":"branch","hook":"Capstone: it's late, your eyes ache, and one more episode is tempting.","options":[{"text":"Switch off, rest your eyes, sleep","consequence":"You wake up fresh; the show waits for tomorrow.","outcome":"healthy","best":true},{"text":"Watch till midnight","consequence":"Sleep and rested eyes beat one more episode."}],"debrief":"Knowing when to switch off is the ultimate Smart Screen Hero move.","relearn":"Switching off for sleep and rest is real hero strength.","persona":"any","source":"screen hygiene / consolidation"},
  {"id":"sh-081","cat":"is-it-true","type":"strike-rewrite","hook":"\"I should believe whatever my favourite creator says.\"","myth":{"un":"My favourite creator is always right.","re":"Even people you like can be wrong or paid; think for yourself.","why":"Liking someone doesn't make everything they say true."},"relearn":"Even favourites can be wrong or paid; think for yourself.","persona":"Reyansh","source":"critical thinking / parasocial"},
  {"id":"sh-082","cat":"screen-choices","type":"build","hook":"Capstone: build your Smart Screen Hero plan.","prompt":"Pick your hero habits.","pieces":["spot ads and tricks","check if it's true","take breaks & sleep","be kind online","ask a grown-up when unsure"],"mode":"assemble","key":["spot ads and tricks","check if it's true","take breaks & sleep","be kind online","ask a grown-up when unsure"],"relearn":"Hero plan: spot ads, check what's true, take breaks, be kind, ask when unsure.","persona":"any","source":"consolidation"},
  {"id":"sh-083","cat":"caring-online","type":"reflect","hook":"Lensy: what will you carry from Smart Screen Heroes?","prompt":"Pick your motto.","options":["Real or pretend?","Spot the ad","Check if it's true","Be kind online"],"affirm":"Carry that. You're a Smart Screen Hero now, in charge of your screens.","relearn":"Tell real from pretend, spot ads, check what's true, and be kind online.","persona":"any","source":"consolidation"},
  {"id":"sh-084","cat":"screen-choices","type":"reflect","hook":"Lensy: who could YOU teach one screen-hero skill to?","prompt":"Think of someone.","options":["A younger sibling","A friend","My family","Anyone!"],"affirm":"Teaching a screen-hero skill makes you, and them, even smarter.","relearn":"Sharing what you've learned helps others be screen-smart too.","persona":"Reyansh","source":"agency / sharing"},
];

export const SMART_SCREEN: V2GameConfig = {
  gameId: "smart-screen",
  title: "Smart Screen Heroes",
  greet: "Hey, Smart Screen Hero! 📱 Real or pretend? Ad or not? True or fake? Let's get screen-smart — and stay kind online.",
  scenarios: SCENARIOS,
  categories: [
    { id: "real-or-pretend", emoji: "🪄", label: "Real or pretend?" },
    { id: "spot-the-ad", emoji: "📢", label: "Spot the ad" },
    { id: "is-it-true", emoji: "🔍", label: "Is it true?" },
    { id: "screen-choices", emoji: "🎮", label: "Smart choices" },
    { id: "screen-hygiene", emoji: "👀", label: "Screen care" },
    { id: "caring-online", emoji: "💬", label: "Kind online" },
  ],
  badge: {
    title: "Smart Screen Hero! 📱",
    blurb: "You can tell real from pretend, spot the ad and the trick, check what's true, balance your screen time, look after your eyes and sleep, and be kind online. 📱✨",
  },
  helpLine: "If something online worries or upsets you, or someone's unkind, close it and tell a trusted grown-up — you can also call Childline, one-zero-nine-eight.",
  helpLabel: "Get help · Childline 1098",
  reassure: "If something online upsets you or someone's unkind, it's not your fault — close it and tell a trusted grown-up. You can always step away from a screen. 💛",
  buildLabels: { assemble: "That's a Smart Screen plan! 📱" },
};
