// Content for Speak Up (node g19, ages 9–12, Chapter 3) — NEW v2 build to GDD 19 (mechanic-embodying), the
// bystander-to-upstander node (Thread E · Gender & Respect). "From bystander to upstander." 85 researched,
// India-grounded scenarios across the name → why → moves → words → help → act arc, each encoded as one of the
// shared v2 play actions (branch / role-play / sort / spot / reflect / strike-rewrite / match) — no binary
// "tap the right card", led by the **five-moves chooser** (branch ×25 — choose an upstander move, see it play
// out safely; the reference branch engine Stand Up g27 & Defenders of the Body g20 reuse). Teaches: naming
// the forms of gender-based harm (gendered name-calling, exclusion, unwanted touch, body-mocking, online
// hate), why speaking up matters, the **five safe upstander moves** (the 5 Ds — Say something/Direct,
// Distract, Get help/Delegate, Check in/Delay, Report/Document), finding the actual words, where to get help,
// and being the upstander. SAFETY OVER HEROICS (never confront danger alone — "get help" is always honoured);
// NEVER BLAME THE TARGET; TELLING IS NOT TATTLING (help-seeking reframed); FREEZING IS OKAY (a second chance);
// real routes to help (trusted adults, school counsellors, **Childline 1098 / 112**). Builds on g11 (Not Fair,
// Not Funny); prereq g18; pairs g08. Rendered by the shared engine (components/games/v2-engine.tsx).
// gameId "speak-up". DO NOT RENAME.

import type { Scenario, V2GameConfig } from "./v2-schema";

const SCENARIOS: Scenario[] = [
  // — Name the harm —
  {"id":"su-001","cat":"name-the-harm","type":"spot","hook":"In the corridor. Spot what's harmful.","scene":[{"id":"a","text":"A boy calls a girl a gendered slur to get laughs","trick":true},{"id":"b","text":"Kids are walking to class","trick":false},{"id":"c","text":"He says \"it's just a joke\"","trick":true}],"why":"A gendered insult is harm, even when it's dressed up as 'a joke'.","relearn":"Gendered name-calling is harm, even when called 'a joke'.","persona":"any","source":"gender-based harm / naming"},
  {"id":"su-002","cat":"name-the-harm","type":"spot","hook":"At the playground. Spot what's harmful.","scene":[{"id":"a","text":"A group won't let a girl join 'because girls are useless at this'","trick":true},{"id":"b","text":"They're playing cricket","trick":false},{"id":"c","text":"She walks away upset","trick":true}],"why":"Shutting someone out because of their gender is harm, not just 'a game'.","relearn":"Excluding someone because of their gender is a form of harm.","persona":"Diya","source":"gender-based harm / exclusion"},
  {"id":"su-003","cat":"name-the-harm","type":"spot","hook":"In class. Spot what's harmful.","scene":[{"id":"a","text":"Boys snigger and mime about a girl's changing body","trick":true},{"id":"b","text":"The teacher writes on the board","trick":false},{"id":"c","text":"She tries to disappear into her seat","trick":true}],"why":"Mocking someone's body or puberty is harm that can really hurt.","relearn":"Mocking someone's body or puberty is gender-based harm.","persona":"Diya","source":"gender-based harm / bodies"},
  {"id":"su-004","cat":"name-the-harm","type":"spot","hook":"On the bus. Spot what's harmful.","scene":[{"id":"a","text":"An older kid keeps touching a younger one who's said stop","trick":true},{"id":"b","text":"The bus is crowded","trick":false},{"id":"c","text":"\"Don't be dramatic,\" the older one says","trick":true}],"why":"Touching someone after they've said stop is harm; their 'no' counts.","relearn":"Unwanted touching after a 'no' is harm; the 'no' must be respected.","persona":"any","source":"gender-based harm / touch (links g15)"},
  {"id":"su-005","cat":"name-the-harm","type":"spot","hook":"Online. Spot what's harmful.","scene":[{"id":"a","text":"Someone shares a mean, gendered meme about a classmate","trick":true},{"id":"b","text":"It's a group chat","trick":false},{"id":"c","text":"Others start forwarding it","trick":true}],"why":"Spreading a cruel, gendered post is online harm, and forwarding makes it worse.","relearn":"Sharing cruel gendered posts is online harm; forwarding spreads it.","persona":"any","source":"gender-based harm / online (links g12)"},
  {"id":"su-006","cat":"name-the-harm","type":"spot","hook":"In the lane. Spot what's harmful.","scene":[{"id":"a","text":"A boy is teased and shoved for being 'too girly'","trick":true},{"id":"b","text":"There's a tea stall nearby","trick":false},{"id":"c","text":"\"Real boys aren't like you,\" they jeer","trick":true}],"why":"Bullying a boy for not fitting a gender mould is gender-based harm too.","relearn":"Bullying someone for not fitting gender norms is harm.","persona":"Aarav","source":"gender-based harm / norms (links g17)"},
  {"id":"su-007","cat":"name-the-harm","type":"spot","hook":"At a family event. Spot what's harmful.","scene":[{"id":"a","text":"A relative keeps making 'jokes' about a cousin's weight and looks","trick":true},{"id":"b","text":"There's lots of food","trick":false},{"id":"c","text":"She laughs but looks crushed","trick":true}],"why":"Repeated 'jokes' about someone's body are harm, even from family.","relearn":"Repeated 'jokes' about a person's body are harmful, even from family.","persona":"any","source":"gender-based harm / body-shaming"},
  {"id":"su-008","cat":"name-the-harm","type":"sort","hook":"Sort: harm, or okay?","items":[{"id":"a","text":"Teasing a girl about her period"},{"id":"b","text":"Inviting everyone to play"},{"id":"c","text":"A gendered slur 'as a joke'"},{"id":"d","text":"Cheering a friend on"}],"bins":[{"id":"harm","label":"Harm"},{"id":"okay","label":"Okay"}],"key":{"a":"harm","b":"okay","c":"harm","d":"okay"},"relearn":"Teasing about bodies and gendered slurs are harm; kindness is okay.","persona":"any","source":"naming harm"},
  {"id":"su-009","cat":"name-the-harm","type":"sort","hook":"Sort: harm, or okay?","items":[{"id":"a","text":"Leaving someone out for being a girl"},{"id":"b","text":"Disagreeing politely"},{"id":"c","text":"Grabbing someone who said stop"},{"id":"d","text":"Asking before a hug"}],"bins":[{"id":"harm","label":"Harm"},{"id":"okay","label":"Okay"}],"key":{"a":"harm","b":"okay","c":"harm","d":"okay"},"relearn":"Exclusion and ignoring a 'stop' are harm; asking and disagreeing kindly are okay.","persona":"any","source":"naming harm"},
  {"id":"su-010","cat":"name-the-harm","type":"sort","hook":"Sort: a joke everyone enjoys, or harm dressed as a joke?","items":[{"id":"a","text":"A silly pun about homework"},{"id":"b","text":"A 'joke' that humiliates one kid's gender"},{"id":"c","text":"A funny story you both laugh at"},{"id":"d","text":"Mocking how a girl's body is changing"}],"bins":[{"id":"fun","label":"Fun for all"},{"id":"harm","label":"Harm as 'joke'"}],"key":{"a":"fun","b":"harm","c":"fun","d":"harm"},"relearn":"If a 'joke' humiliates one person, it's harm, not fun.","persona":"any","source":"naming harm (links g11)"},
  {"id":"su-011","cat":"name-the-harm","type":"sort","hook":"Sort: which of these is gender-based harm?","items":[{"id":"a","text":"\"You can't play, you're a girl\""},{"id":"b","text":"\"Let's take turns\""},{"id":"c","text":"\"Boys like you are pathetic\""},{"id":"d","text":"\"Nice shot!\""}],"bins":[{"id":"harm","label":"Gender-based harm"},{"id":"fine","label":"Just fine"}],"key":{"a":"harm","b":"fine","c":"harm","d":"fine"},"relearn":"Put-downs aimed at someone's gender are gender-based harm.","persona":"any","source":"naming harm"},
  {"id":"su-012","cat":"name-the-harm","type":"strike-rewrite","hook":"\"If it's a joke, it can't be harmful.\"","myth":{"un":"Anything said as a joke can't really be harmful.","re":"A 'joke' that hurts or humiliates someone is still harm.","why":"The harm is in the impact, not the label."},"relearn":"Calling harm 'a joke' doesn't stop it being harm.","persona":"Aarav","source":"naming harm"},
  {"id":"su-013","cat":"name-the-harm","type":"strike-rewrite","hook":"\"If they don't cry, it didn't hurt them.\"","myth":{"un":"If someone doesn't cry, the harm didn't affect them.","re":"People often hide hurt behind a laugh or a blank face.","why":"You can't measure harm by tears alone."},"relearn":"Hidden hurt is still real; don't judge harm by tears.","persona":"any","source":"naming harm / empathy"},
  {"id":"su-014","cat":"name-the-harm","type":"reflect","hook":"Lensy: harm can be words, leaving-out, touching, or online. Recognise the shapes now?","prompt":"What do you think?","options":["Yes","Many shapes","I can spot them"],"affirm":"Harm comes in many shapes; naming it is the first step to stopping it.","relearn":"Gender-based harm takes many shapes: words, exclusion, touch, online.","persona":"any","source":"naming harm"},
  // — Why speaking up matters —
  {"id":"su-015","cat":"why-speak-up","type":"strike-rewrite","hook":"\"It's none of my business if it's not happening to me.\"","myth":{"un":"If it's not happening to me, it's none of my business.","re":"When you see harm, speaking up is everyone's business.","why":"Silence lets harm continue."},"relearn":"Witnessing harm makes it your business too.","persona":"any","source":"why speak up / allyship"},
  {"id":"su-016","cat":"why-speak-up","type":"strike-rewrite","hook":"\"Telling an adult is just tattling.\"","myth":{"un":"Telling an adult about harm is tattling.","re":"Tattling is to get someone in trouble; telling is to keep someone safe.","why":"Help-seeking for safety is brave, not sneaky."},"relearn":"Telling to keep someone safe is help-seeking, not tattling.","persona":"Asha","source":"why speak up / help-seeking"},
  {"id":"su-017","cat":"why-speak-up","type":"strike-rewrite","hook":"\"If I stay quiet, at least I'm not making it worse.\"","myth":{"un":"Staying silent is the safe, neutral choice.","re":"Silence can let the person being harmed feel alone.","why":"Doing nothing quietly sides with the harm."},"relearn":"Silence isn't neutral; it can leave the target alone.","persona":"any","source":"why speak up / bystander effect"},
  {"id":"su-018","cat":"why-speak-up","type":"strike-rewrite","hook":"\"Someone else will surely step in.\"","myth":{"un":"Someone else is bound to step in, so I don't need to.","re":"When everyone thinks that, no one acts; you can be the one.","why":"This is the bystander trap."},"relearn":"Don't wait for someone else; you can be the one who acts.","persona":"any","source":"why speak up / bystander effect"},
  {"id":"su-019","cat":"why-speak-up","type":"strike-rewrite","hook":"\"The person being harmed must have done something to deserve it.\"","myth":{"un":"If someone's being harmed, they must have asked for it.","re":"Harm is never the fault of the person being hurt.","why":"Blaming the target excuses the person doing harm."},"relearn":"Harm is never the target's fault.","persona":"any","source":"why speak up / no victim-blaming"},
  {"id":"su-020","cat":"why-speak-up","type":"reflect","hook":"Lensy: imagine being harmed and one person stands with you. How much would that matter?","prompt":"What do you think?","options":["A lot","Everything","I'd feel less alone"],"affirm":"One upstander can change everything for the person being harmed.","relearn":"One person standing with you can make all the difference.","persona":"Diya","source":"why speak up / empathy"},
  {"id":"su-021","cat":"why-speak-up","type":"reflect","hook":"Lensy: what kind of bystander do you want to be, the silent one or the upstander?","prompt":"Be honest.","options":["The upstander","The one who helps","Not the silent one"],"affirm":"Choosing to be an upstander is a choice you can make every time.","relearn":"You can choose to be an upstander, not a silent bystander.","persona":"any","source":"why speak up / identity"},
  {"id":"su-022","cat":"why-speak-up","type":"reflect","hook":"Lensy: speaking up can feel scary, and still be worth it. Agree?","prompt":"What do you think?","options":["Yes","Scary but worth it","Brave is okay to be"],"affirm":"Courage isn't feeling unafraid; it's acting even while afraid.","relearn":"Speaking up can feel scary and still be the right, brave thing.","persona":"Aarav","source":"why speak up / courage"},
  {"id":"su-023","cat":"why-speak-up","type":"sort","hook":"Sort: an upstander, or a bystander?","items":[{"id":"a","text":"Telling the kids to stop"},{"id":"b","text":"Watching and saying nothing"},{"id":"c","text":"Getting a teacher"},{"id":"d","text":"Laughing along"}],"bins":[{"id":"up","label":"Upstander"},{"id":"by","label":"Silent bystander"}],"key":{"a":"up","b":"by","c":"up","d":"by"},"relearn":"Upstanders act; silent bystanders watch or laugh along.","persona":"any","source":"why speak up"},
  {"id":"su-024","cat":"why-speak-up","type":"sort","hook":"Sort: helps the person harmed, or helps the harm continue?","items":[{"id":"a","text":"Checking if they're okay"},{"id":"b","text":"Forwarding the mean post"},{"id":"c","text":"Sitting with them"},{"id":"d","text":"Egging it on"}],"bins":[{"id":"helps","label":"Helps the person"},{"id":"continues","label":"Helps the harm"}],"key":{"a":"helps","b":"continues","c":"helps","d":"continues"},"relearn":"Small acts either help the person or help the harm; choose to help the person.","persona":"any","source":"why speak up"},
  {"id":"su-025","cat":"why-speak-up","type":"branch","hook":"You see harm but think \"maybe I'm overreacting\".","options":[{"text":"Trust that if it looks like harm, it's worth acting on","consequence":"You step in or get help, just in case.","outcome":"upstander","best":true},{"text":"Talk yourself out of it","consequence":"If it looks like harm, it's worth checking, not ignoring."}],"debrief":"It's better to act on a maybe than to ignore real harm.","relearn":"If it looks like harm, act, don't talk yourself out of it.","persona":"any","source":"why speak up"},
  {"id":"su-026","cat":"why-speak-up","type":"branch","hook":"Stepping in might make the bullies turn on you.","options":[{"text":"Pick a safe move: get an adult or distract, not a fight","consequence":"You help without putting yourself in danger.","outcome":"smart","best":true},{"text":"Do nothing out of fear","consequence":"There are safe ways to help that don't mean fighting."}],"debrief":"You can help safely; upstanding isn't the same as fighting.","relearn":"You can help in safe ways, without confronting bullies directly.","persona":"any","source":"why speak up / safety"},
  // — The five upstander moves —
  {"id":"su-026b","cat":"five-moves","type":"reflect","hook":"Lensy: there are five safe ways to help, the five upstander moves. Want them?","prompt":"What do you think?","options":["Yes please","Teach me","Five tools"],"affirm":"Say something, distract, get help, check in, and report, your toolkit.","relearn":"The upstander toolkit: speak up, distract, get help, check in, report.","persona":"Asha","source":"5 Ds (Right To Be)"},
  {"id":"su-027","cat":"five-moves","type":"branch","hook":"Move 1, SAY SOMETHING. Kids are taunting a classmate; it feels safe to speak.","options":[{"text":"Say calmly \"hey, that's not okay, stop\"","consequence":"Naming it often makes harm pause.","outcome":"direct","best":true},{"text":"Stay quiet","consequence":"A calm 'that's not okay' is the Direct move; it works."}],"debrief":"The Direct move: say plainly that it's not okay, when it's safe.","relearn":"Move 1 (Direct): say calmly that the behaviour isn't okay.","persona":"Aarav","source":"5 Ds / Direct"},
  {"id":"su-028","cat":"five-moves","type":"branch","hook":"Move 2, DISTRACT. It doesn't feel safe to confront the bullies head-on.","options":[{"text":"Break it up: ask the target a random question, drop your books","consequence":"The distraction interrupts the harm safely.","outcome":"distract","best":true},{"text":"Confront the biggest bully alone","consequence":"When direct feels unsafe, Distract interrupts without a clash."}],"debrief":"The Distract move: derail the moment without a confrontation.","relearn":"Move 2 (Distract): interrupt the harm sideways when direct feels unsafe.","persona":"any","source":"5 Ds / Distract"},
  {"id":"su-029","cat":"five-moves","type":"branch","hook":"Move 3, GET HELP. The harm is serious or scary.","options":[{"text":"Find a teacher or trusted adult fast","consequence":"An adult can step in with authority.","outcome":"delegate","best":true},{"text":"Try to handle a scary situation alone","consequence":"For serious harm, getting an adult (Delegate) is the right move."}],"debrief":"The Delegate move: bring in an adult for anything serious or scary.","relearn":"Move 3 (Delegate): get a trusted adult for serious harm.","persona":"Asha","source":"5 Ds / Delegate"},
  {"id":"su-030","cat":"five-moves","type":"branch","hook":"Move 4, CHECK IN. The moment has passed, but the person looked hurt.","options":[{"text":"Go over later: \"are you okay? that wasn't fair\"","consequence":"They feel seen and less alone.","outcome":"delay","best":true},{"text":"Forget about it","consequence":"Checking in afterward (Delay) really helps the person heal."}],"debrief":"The Delay move: check in afterwards so they don't feel alone.","relearn":"Move 4 (Delay): check in with the person after the harm.","persona":"Diya","source":"5 Ds / Delay"},
  {"id":"su-031","cat":"five-moves","type":"branch","hook":"Move 5, REPORT. There's a cruel post being spread online.","options":[{"text":"Don't forward it; report it and tell an adult","consequence":"You stop the spread and create a record.","outcome":"report","best":true},{"text":"Share it 'to show people'","consequence":"Don't spread it; reporting it safely is the move."}],"debrief":"The Report move: don't spread harm online, report it and tell an adult.","relearn":"Move 5 (Report): report online harm and don't forward it.","persona":"any","source":"5 Ds / Document-report"},
  {"id":"su-032","cat":"five-moves","type":"branch","hook":"You want to help, but which move fits a loud taunt in a safe corridor?","options":[{"text":"A calm Direct \"that's not okay\"","consequence":"Direct fits when it's safe and clear.","outcome":"direct","best":true},{"text":"Secretly film it","consequence":"Here a calm Direct works; filming isn't needed."}],"debrief":"Match the move to the moment; Direct suits a safe, clear situation.","relearn":"Choose the upstander move that fits the situation.","persona":"any","source":"5 Ds / choosing"},
  {"id":"su-033","cat":"five-moves","type":"branch","hook":"A big, aggressive group is harming someone. Which move?","options":[{"text":"Get an adult fast (Delegate), don't go in alone","consequence":"You bring real help without risking yourself.","outcome":"delegate","best":true},{"text":"Jump into the middle of the group","consequence":"For a scary group, Delegate (get an adult) is safest."}],"debrief":"For anything dangerous, Delegate beats going in alone.","relearn":"For dangerous situations, get an adult rather than going in alone.","persona":"any","source":"5 Ds / safety"},
  {"id":"su-034","cat":"five-moves","type":"sort","hook":"Sort the move to its name.","items":[{"id":"a","text":"\"That's not okay, stop\""},{"id":"b","text":"Dropping books to break it up"},{"id":"c","text":"Fetching a teacher"},{"id":"d","text":"\"Are you okay?\" afterwards"}],"bins":[{"id":"direct","label":"Direct / Distract"},{"id":"help","label":"Delegate / Delay"}],"key":{"a":"direct","b":"direct","c":"help","d":"help"},"relearn":"Speaking up and distracting are one set; getting help and checking in another.","persona":"any","source":"5 Ds"},
  {"id":"su-035","cat":"five-moves","type":"sort","hook":"Sort: a safe upstander move, or risky?","items":[{"id":"a","text":"Getting an adult"},{"id":"b","text":"Fighting the bully"},{"id":"c","text":"Distracting to break it up"},{"id":"d","text":"Threatening them back"}],"bins":[{"id":"safe","label":"Safe move"},{"id":"risky","label":"Risky move"}],"key":{"a":"safe","b":"risky","c":"safe","d":"risky"},"relearn":"Upstander moves are designed to help safely, not to fight.","persona":"any","source":"5 Ds / safety"},
  {"id":"su-036","cat":"five-moves","type":"sort","hook":"Sort: which move fits, get help, or check in?","items":[{"id":"a","text":"Serious harm happening now"},{"id":"b","text":"The person looked sad afterwards"},{"id":"c","text":"Something scary you can't stop"},{"id":"d","text":"They're sitting alone, hurt, later"}],"bins":[{"id":"gethelp","label":"Get help now"},{"id":"checkin","label":"Check in after"}],"key":{"a":"gethelp","b":"checkin","c":"gethelp","d":"checkin"},"relearn":"Get help during serious harm; check in with the person afterwards.","persona":"any","source":"5 Ds"},
  {"id":"su-037","cat":"five-moves","type":"sort","hook":"Sort: helps safely online, or makes it worse?","items":[{"id":"a","text":"Reporting the post"},{"id":"b","text":"Forwarding it"},{"id":"c","text":"Telling an adult"},{"id":"d","text":"Adding a mean comment"}],"bins":[{"id":"helps","label":"Helps safely"},{"id":"worse","label":"Makes it worse"}],"key":{"a":"helps","b":"worse","c":"helps","d":"worse"},"relearn":"Report and tell an adult; never forward or pile on.","persona":"any","source":"5 Ds / online"},
  {"id":"su-038","cat":"five-moves","type":"role-play","hook":"You choose the Direct move on a taunt.","setup":"Say it calm and clear:","yourLine":[{"text":"\"That's not okay. Leave them alone.\"","best":true},{"text":"\"...\" (say nothing)"}],"relearn":"A calm, clear 'that's not okay' is a strong Direct move.","persona":"Aarav","source":"5 Ds / Direct voice"},
  {"id":"su-039","cat":"five-moves","type":"role-play","hook":"You use the Distract move.","setup":"Break the moment naturally. Say:","yourLine":[{"text":"\"Hey, the teacher's looking for you, come on.\"","best":true},{"text":"\"Carry on then.\""}],"relearn":"A casual interruption is an effective, safe Distract.","persona":"any","source":"5 Ds / Distract voice"},
  {"id":"su-040","cat":"five-moves","type":"role-play","hook":"You use the Check-in move afterwards.","setup":"Be warm. Say:","yourLine":[{"text":"\"That wasn't fair on you. Are you okay?\"","best":true},{"text":"Avoid them so it's not awkward"}],"relearn":"A warm 'are you okay?' afterwards helps the person feel less alone.","persona":"Diya","source":"5 Ds / Delay voice"},
  {"id":"su-041","cat":"five-moves","type":"reflect","hook":"Lensy: five moves means you've always got at least one safe option. Reassuring?","prompt":"What do you think?","options":["Yes","Always an option","I can always help"],"affirm":"With five moves, there's always a safe way to help.","relearn":"With five moves, you can always find a safe way to help.","persona":"any","source":"5 Ds"},
  {"id":"su-042","cat":"five-moves","type":"reflect","hook":"Lensy: which move feels most like 'you'?","prompt":"Pick one.","options":["Say something","Distract","Get help","Check in"],"affirm":"Start with the move that fits you; you can grow the others.","relearn":"Start with the upstander move that feels most natural to you.","persona":"any","source":"5 Ds"},
  // — Find the words —
  {"id":"su-043","cat":"find-the-words","type":"role-play","hook":"A friend is being called a gendered name.","setup":"Step in for them. Say:","yourLine":[{"text":"\"Don't call them that. Not cool.\"","best":true},{"text":"Laugh nervously"}],"relearn":"A short, firm line can stop name-calling in its tracks.","persona":"any","source":"upstander voice"},
  {"id":"su-044","cat":"find-the-words","type":"role-play","hook":"A girl is being shut out of the game.","setup":"Open the door. Say:","yourLine":[{"text":"\"She's on my team. Let's play.\"","best":true},{"text":"\"Guess she can't play.\""}],"relearn":"Inviting someone in is a powerful upstander move.","persona":"Diya","source":"upstander voice / inclusion"},
  {"id":"su-045","cat":"find-the-words","type":"role-play","hook":"People are mocking a boy for being gentle.","setup":"Back him up. Say:","yourLine":[{"text":"\"Being kind isn't something to mock.\"","best":true},{"text":"Join in so you fit in"}],"relearn":"You can defend someone mocked for not fitting a gender mould.","persona":"Aarav","source":"upstander voice / norms"},
  {"id":"su-046","cat":"find-the-words","type":"role-play","hook":"A classmate is being teased about her changing body.","setup":"Shut it down kindly. Say:","yourLine":[{"text":"\"Everyone's body changes. Leave her alone.\"","best":true},{"text":"Snigger along"}],"relearn":"Normalising bodies while defending someone stops body-teasing.","persona":"Diya","source":"upstander voice / bodies"},
  {"id":"su-047","cat":"find-the-words","type":"role-play","hook":"Friends want you to forward a cruel post.","setup":"Refuse clearly. Say:","yourLine":[{"text":"\"I'm not sending that. It's mean.\"","best":true},{"text":"\"Okay, sending.\""}],"relearn":"You can refuse to forward harm, out loud.","persona":"any","source":"upstander voice / online"},
  {"id":"su-048","cat":"find-the-words","type":"role-play","hook":"You need to tell a teacher about ongoing harm.","setup":"Report it clearly. Say:","yourLine":[{"text":"\"Miss, something's happening that someone needs help with.\"","best":true},{"text":"Keep it to yourself"}],"relearn":"You can clearly ask a trusted adult to step in.","persona":"Asha","source":"upstander voice / help"},
  {"id":"su-049","cat":"find-the-words","type":"role-play","hook":"The person doing harm says \"why do you even care?\"","setup":"Hold steady. Say:","yourLine":[{"text":"\"Because it's not okay, that's why.\"","best":true},{"text":"\"...sorry, never mind.\""}],"relearn":"You can stand by your reason for speaking up.","persona":"any","source":"upstander voice / steady"},
  {"id":"su-050","cat":"find-the-words","type":"role-play","hook":"You froze the first time; now you get another chance.","setup":"Try again. Say:","yourLine":[{"text":"\"Hey, stop, that's enough.\"","best":true},{"text":"Freeze again"}],"relearn":"Freezing once is okay; you can find your voice next time.","persona":"Aarav","source":"upstander voice / second chance"},
  {"id":"su-051","cat":"find-the-words","type":"role-play","hook":"You want to support the target without making a scene.","setup":"Quietly ally. Say:","yourLine":[{"text":"\"Come sit with us.\"","best":true},{"text":"Pretend not to notice"}],"relearn":"A quiet 'come sit with us' is a gentle, real upstander move.","persona":"Diya","source":"upstander voice / quiet ally"},
  {"id":"su-052","cat":"find-the-words","type":"branch","hook":"You've got the words ready but your heart is pounding.","options":[{"text":"Take a breath and say your line anyway","consequence":"You act through the nerves; it gets easier.","outcome":"brave","best":true},{"text":"Swallow the words","consequence":"Breathe and say it; courage grows with each try."}],"debrief":"Nerves are normal; say your line anyway.","relearn":"You can speak up even with your heart pounding.","persona":"any","source":"upstander voice / courage"},
  {"id":"su-053","cat":"find-the-words","type":"branch","hook":"Your first line didn't work; the harm continues.","options":[{"text":"Switch moves: now go get an adult","consequence":"You escalate to help instead of giving up.","outcome":"persistent","best":true},{"text":"Give up because one try failed","consequence":"If one move fails, switch to another, like getting help."}],"debrief":"If one move doesn't work, switch to another.","relearn":"If your first move fails, switch to another, like getting help.","persona":"any","source":"upstander voice / persistence"},
  {"id":"su-054","cat":"find-the-words","type":"reflect","hook":"Lensy: having a line ready makes it easier to use in the moment. Worth practising?","prompt":"What do you think?","options":["Yes","I'll practise","Ready lines help"],"affirm":"A rehearsed line comes out far more easily under pressure.","relearn":"Practising a ready line helps you use it in the moment.","persona":"any","source":"upstander voice / rehearsal"},
  // — Where to get help —
  {"id":"su-055","cat":"get-help","type":"match","hook":"Match the situation to who can help.","pairs":[{"left":"Harm at school","right":"A trusted teacher"},{"left":"Harm at home","right":"A trusted adult or relative"},{"left":"A serious emergency","right":"Childline 1098 / 112"}],"relearn":"Different situations have the right helper; know who to turn to.","persona":"Asha","source":"get help / UNESCO 5.5"},
  {"id":"su-056","cat":"get-help","type":"match","hook":"Match the helper to what they can do.","pairs":[{"left":"School counsellor","right":"Listen and support privately"},{"left":"Parent or guardian","right":"Step in and protect"},{"left":"Childline 1098","right":"24-hour help for children"}],"relearn":"Counsellors, parents and Childline 1098 each offer real help.","persona":"any","source":"get help / UNESCO 5.5"},
  {"id":"su-057","cat":"get-help","type":"match","hook":"Match the worry to a first step.","pairs":[{"left":"Scared to tell alone","right":"Bring a friend with you"},{"left":"Don't know who to trust","right":"Pick any safe adult to start"},{"left":"It's urgent and scary","right":"Call 1098 or 112"}],"relearn":"There's always a first step to getting help, even when it's hard.","persona":"Diya","source":"get help"},
  {"id":"su-058","cat":"get-help","type":"match","hook":"Match: tattling or telling?","pairs":[{"left":"To get someone in trouble","right":"Tattling"},{"left":"To keep someone safe","right":"Telling"},{"left":"Reporting serious harm","right":"Telling"}],"relearn":"Telling keeps people safe; that's different from tattling.","persona":"any","source":"get help / help-seeking"},
  {"id":"su-059","cat":"get-help","type":"branch","hook":"You told one adult and nothing changed.","options":[{"text":"Tell another trusted adult, keep going until someone helps","consequence":"Persistence gets the harm taken seriously.","outcome":"persistent","best":true},{"text":"Give up, assuming no one will help","consequence":"If one adult doesn't act, tell another, don't give up."}],"debrief":"If the first adult doesn't help, tell another, and another.","relearn":"Keep telling trusted adults until someone helps.","persona":"Asha","source":"get help / persistence"},
  {"id":"su-060","cat":"get-help","type":"branch","hook":"A friend is being harmed but begs you not to tell anyone.","options":[{"text":"For serious harm, tell a trusted adult anyway, kindly","consequence":"You keep them safe even if they're upset for now.","outcome":"caring","best":true},{"text":"Promise to keep the secret","consequence":"Safety comes before a secret; tell a trusted adult."}],"debrief":"Some secrets aren't safe to keep; safety comes first.","relearn":"For serious harm, tell a trusted adult even if asked to keep it secret.","persona":"any","source":"get help / safe vs unsafe secrets (links g08)"},
  {"id":"su-061","cat":"get-help","type":"branch","hook":"You're not totally sure if it counts as 'serious enough' to report.","options":[{"text":"Ask a trusted adult; let them help you decide","consequence":"You get guidance instead of guessing alone.","outcome":"resourceful","best":true},{"text":"Decide alone it's probably nothing","consequence":"When unsure, a trusted adult can help you judge."}],"debrief":"When unsure, asking an adult is itself a smart move.","relearn":"When unsure if harm is 'serious enough', ask a trusted adult.","persona":"any","source":"get help"},
  {"id":"su-062","cat":"get-help","type":"branch","hook":"The harm is happening online to you or a friend.","options":[{"text":"Save proof, don't reply, and tell a trusted adult","consequence":"You handle it safely and get backup.","outcome":"savvy","best":true},{"text":"Fight back in the comments","consequence":"Save proof and tell an adult; don't get pulled into a fight."}],"debrief":"For online harm: keep proof, don't engage, tell an adult.","relearn":"For online harm, save proof, don't reply, and tell a trusted adult.","persona":"any","source":"get help / online (links g12)"},
  {"id":"su-063","cat":"get-help","type":"strike-rewrite","hook":"\"Asking for help means I'm weak.\"","myth":{"un":"Asking for help means I'm weak.","re":"Asking for help is a smart, strong thing to do.","why":"Even the bravest people get backup."},"relearn":"Asking for help is strong and smart, not weak.","persona":"Aarav","source":"get help / help-seeking"},
  {"id":"su-064","cat":"get-help","type":"strike-rewrite","hook":"\"Adults never do anything anyway.\"","myth":{"un":"There's no point telling adults; they never help.","re":"Many adults will help; if one doesn't, another will.","why":"You may need to find the right adult."},"relearn":"Many adults will help; keep looking for the right one.","persona":"any","source":"get help"},
  {"id":"su-065","cat":"get-help","type":"sort","hook":"Sort: a trusted helper, or not a safe choice?","items":[{"id":"a","text":"A teacher you trust"},{"id":"b","text":"A stranger online offering to 'sort it'"},{"id":"c","text":"A parent or guardian"},{"id":"d","text":"The person doing the harm"}],"bins":[{"id":"trusted","label":"Trusted helper"},{"id":"not","label":"Not safe"}],"key":{"a":"trusted","b":"not","c":"trusted","d":"not"},"relearn":"Turn to trusted adults, not strangers or the person causing harm.","persona":"any","source":"get help / who to trust"},
  {"id":"su-066","cat":"get-help","type":"sort","hook":"Sort: a good time to call 1098 / 112, or handle another way?","items":[{"id":"a","text":"A child is in danger right now"},{"id":"b","text":"A small disagreement over a game"},{"id":"c","text":"Someone is being seriously hurt"},{"id":"d","text":"You don't like the homework"}],"bins":[{"id":"call","label":"Call for help"},{"id":"other","label":"Handle another way"}],"key":{"a":"call","b":"other","c":"call","d":"other"},"relearn":"Helplines like 1098/112 are for real danger and serious harm.","persona":"any","source":"get help / helpline"},
  {"id":"su-067","cat":"get-help","type":"role-play","hook":"You're helping a friend make the call for help.","setup":"Encourage them. Say:","yourLine":[{"text":"\"I'll be right here with you while you tell them.\"","best":true},{"text":"\"You're on your own with this.\""}],"relearn":"Being beside someone makes asking for help far easier.","persona":"Diya","source":"get help / support"},
  {"id":"su-068","cat":"get-help","type":"role-play","hook":"You decide to tell a trusted adult about ongoing harm.","setup":"Open clearly. Say:","yourLine":[{"text":"\"I need to tell you something to keep someone safe.\"","best":true},{"text":"Hint vaguely and hope they guess"}],"relearn":"Opening clearly helps a trusted adult understand and act.","persona":"any","source":"get help / voice"},
  // — Be the upstander —
  {"id":"su-069","cat":"be-the-upstander","type":"branch","hook":"Capstone: a girl is cornered and teased by a group; it's loud but not physical.","options":[{"text":"Distract to break it up, then check she's okay","consequence":"You interrupt safely and support her.","outcome":"upstander","best":true},{"text":"Watch from a distance","consequence":"A distract-then-check-in combo helps without a clash."}],"debrief":"Pair moves: distract in the moment, check in afterwards.","relearn":"You can combine upstander moves: distract, then check in.","persona":"Diya","source":"upstander / combo"},
  {"id":"su-070","cat":"be-the-upstander","type":"branch","hook":"A boy is being shoved and called slurs; it's turning physical.","options":[{"text":"Get an adult immediately","consequence":"You bring help for a dangerous situation.","outcome":"delegate","best":true},{"text":"Jump in to fight them off","consequence":"When it's physical and dangerous, get an adult fast."}],"debrief":"Physical danger calls for an adult, not a solo rescue.","relearn":"When harm turns physical, get an adult immediately.","persona":"Aarav","source":"upstander / safety"},
  {"id":"su-071","cat":"be-the-upstander","type":"branch","hook":"Your own friend is the one doing the harm.","options":[{"text":"Tell your friend honestly it's not okay","consequence":"A real friend can hear the truth from you.","outcome":"honest","best":true},{"text":"Let it slide because they're your friend","consequence":"Being a true friend includes telling them when they're wrong."}],"debrief":"Upstanding sometimes means correcting your own friend.","relearn":"You can tell even a friend that their harm isn't okay.","persona":"any","source":"upstander / friends"},
  {"id":"su-072","cat":"be-the-upstander","type":"branch","hook":"You're scared that helping will make you the next target.","options":[{"text":"Choose a safe move (get help, distract) so you help and stay safe","consequence":"You protect the target and yourself.","outcome":"smart","best":true},{"text":"Do nothing out of fear","consequence":"Safe moves let you help without becoming a target."}],"debrief":"Your safety matters too; pick the move that protects everyone.","relearn":"Choose safe moves so you can help without endangering yourself.","persona":"any","source":"upstander / safety"},
  {"id":"su-073","cat":"be-the-upstander","type":"branch","hook":"Everyone else is just watching the harm happen.","options":[{"text":"Be the first to act; others often join once someone starts","consequence":"Your move gives others courage to help too.","outcome":"leader","best":true},{"text":"Wait with the crowd","consequence":"Someone has to be first; it can be you, and others follow."}],"debrief":"The first upstander often unfreezes the whole crowd.","relearn":"Being the first to act can free others to help too.","persona":"any","source":"upstander / leadership"},
  {"id":"su-074","cat":"be-the-upstander","type":"branch","hook":"You helped once and it worked. Now it's happening again, to someone else.","options":[{"text":"Step up again, you know you can","consequence":"You become a reliable upstander.","outcome":"consistent","best":true},{"text":"Feel you've 'done your bit' already","consequence":"Upstanding is a habit, not a one-time act."}],"debrief":"Being an upstander is something you keep choosing.","relearn":"Upstanding is an ongoing habit, not a one-off.","persona":"any","source":"upstander / habit"},
  {"id":"su-075","cat":"be-the-upstander","type":"branch","hook":"You witness subtle harm: a sly gendered 'joke' that lands hard.","options":[{"text":"Name it lightly: \"that's not really funny, though\"","consequence":"You flag it without a big confrontation.","outcome":"direct","best":true},{"text":"Let it pass as 'just a joke'","consequence":"Even subtle harm can be named, lightly."}],"debrief":"Quiet harm deserves a quiet upstander too.","relearn":"You can gently name subtle harm, not just obvious harm.","persona":"any","source":"upstander / subtle"},
  {"id":"su-076","cat":"be-the-upstander","type":"branch","hook":"A younger child is being harmed and looks to you.","options":[{"text":"Step in and get them to a trusted adult","consequence":"You protect a younger kid who needs you.","outcome":"protector","best":true},{"text":"Decide it's not your problem","consequence":"A younger child needs an older one to step up."}],"debrief":"Older kids can be powerful upstanders for younger ones.","relearn":"You can step up to protect a younger child.","persona":"Asha","source":"upstander / mentoring"},
  {"id":"su-077","cat":"be-the-upstander","type":"branch","hook":"You realise you once laughed along at harm. You see it again now.","options":[{"text":"Do it differently this time, speak up","consequence":"You grow from bystander to upstander.","outcome":"growth","best":true},{"text":"Laugh along again","consequence":"You can change; this time, be the upstander."}],"debrief":"You can change from bystander to upstander any time.","relearn":"You can choose differently and become an upstander.","persona":"Aarav","source":"upstander / growth"},
  {"id":"su-078","cat":"be-the-upstander","type":"branch","hook":"Capstone: online, a friend is being targeted with gendered hate.","options":[{"text":"Don't share it, report it, save proof, and tell an adult","consequence":"You use the safe online toolkit fully.","outcome":"upstander","best":true},{"text":"Reply with insults to defend them","consequence":"Report, save proof, and tell an adult; don't fuel the fight."}],"debrief":"Online upstanding: report, preserve proof, tell an adult, never pile on.","relearn":"Online: report, save proof, tell an adult, and don't pile on.","persona":"any","source":"upstander / online"},
  {"id":"su-079","cat":"be-the-upstander","type":"spot","hook":"A scene with many people. Spot the upstander.","scene":[{"id":"a","text":"One kid quietly fetches a teacher","trick":true},{"id":"b","text":"Most are filming for laughs","trick":false},{"id":"c","text":"Another goes to sit with the target","trick":true}],"why":"The upstanders are the ones getting help and supporting the target, not filming.","relearn":"Upstanders get help and support the target; they don't film for laughs.","persona":"any","source":"upstander / spotting"},
  {"id":"su-080","cat":"be-the-upstander","type":"spot","hook":"After the harm. Spot the caring move.","scene":[{"id":"a","text":"Someone sits with the hurt kid","trick":true},{"id":"b","text":"The corridor is busy","trick":false},{"id":"c","text":"Someone says \"want to tell a teacher together?\"","trick":true}],"why":"Sitting with someone and offering to get help together are caring upstander moves.","relearn":"Caring afterwards, sitting with someone, offering help, matters.","persona":"Diya","source":"upstander / care"},
  {"id":"su-081","cat":"be-the-upstander","type":"spot","hook":"Check yourself. Spot your safest first move here.","scene":[{"id":"a","text":"You could quietly get the nearby teacher","trick":true},{"id":"b","text":"The bullies are bigger than you","trick":false},{"id":"c","text":"You could jump into the middle","trick":false}],"why":"With bigger bullies, quietly getting the teacher is the safe, smart first move.","relearn":"When outmatched, getting an adult is the safest first move.","persona":"any","source":"upstander / safety"},
  {"id":"su-082","cat":"be-the-upstander","type":"strike-rewrite","hook":"\"I'm just a kid, I can't make a difference.\"","myth":{"un":"I'm just a kid; I can't make a difference to harm.","re":"Kids are upstanders every day; your action counts.","why":"Even one small safe move can change someone's day."},"relearn":"Even as a kid, your upstander action makes a real difference.","persona":"any","source":"upstander / agency"},
  {"id":"su-083","cat":"be-the-upstander","type":"reflect","hook":"Lensy: biggest take-away from Speak Up?","prompt":"Pick your motto.","options":["Name the harm","Pick a safe move","Telling isn't tattling","Be the upstander"],"affirm":"You can spot harm, choose a safe move, and help, every time.","relearn":"Spot the harm, choose a safe move, get help, be the upstander.","persona":"any","source":"consolidation"},
  {"id":"su-084","cat":"be-the-upstander","type":"reflect","hook":"Lensy: knowing the five moves and 1098, do you feel ready to help?","prompt":"What do you think?","options":["Ready","Yes","I know what to do"],"affirm":"You've got the moves and the helplines, you're ready to be an upstander.","relearn":"With the five moves and helplines, you're ready to help safely.","persona":"any","source":"consolidation"},
];

export const SPEAK_UP: V2GameConfig = {
  gameId: "speak-up",
  title: "Speak Up",
  greet: "Hey, it's Lensy. 🦸 See something wrong and freeze? Let's learn the five safe upstander moves, find the words, and know where to get help — so you can step up without putting yourself in danger.",
  scenarios: SCENARIOS,
  categories: [
    { id: "name-the-harm", emoji: "🔎", label: "Name the harm" },
    { id: "why-speak-up", emoji: "💬", label: "Why speak up" },
    { id: "five-moves", emoji: "🖐️", label: "Five moves" },
    { id: "find-the-words", emoji: "🗣️", label: "Find the words" },
    { id: "get-help", emoji: "🆘", label: "Get help" },
    { id: "be-the-upstander", emoji: "🦸", label: "Be the upstander" },
  ],
  badge: {
    title: "Upstander! 🦸",
    blurb: "You can name gender-based harm, pick from five safe upstander moves (say something, distract, get help, check in, report), find the words, and reach real help — and harm is never the target's fault. 🦸",
  },
  helpLine: "If you or someone you know is being harmed, tell a trusted grown-up — a teacher, a parent, a school counsellor — and for real danger you can call Childline, one-zero-nine-eight (or one-one-two). Telling to keep someone safe is brave, not tattling.",
  helpLabel: "Get help · Childline 1098",
  reassure: "If you or someone you know is being harmed, it's never your fault — and telling a trusted grown-up is brave, not tattling. For real danger, call Childline 1098 (or 112). 💛",
  reassureCats: ["get-help"],
};
