// Content for The Talks, Age by Age (node g64, Parent Layer, Chapter 8) — NEW v2 build to GDD 64
// (mechanic-embodying), the KEYSTONE of the Parent Layer and the hinge of the generational loop: a parent guided
// here becomes the trusted adult the kids' journey always assumed. The core reframe: it isn't one dreaded "talk",
// it's many small, age-right conversations, and you can do them. 84 researched, India-grounded scenarios across
// how-to-talk → early-years → middle-years → the-teen-talks → facts-and-values → tools-and-help, each encoded as
// one of the shared v2 play actions (role-play / strike-rewrite / branch / sort / reflect / match / spot) — no
// binary "tap the right card". Lead: role-play (say it), strike-rewrite (bust the myth), branch (your move). Six
// modes: how to talk (start early, stay calm, answer "I don't know" honestly, be the askable open door), the early
// years (correct body-part names — which protect against abuse and aid disclosure — body safety & consent basics,
// no body secrets, where-babies-come-from simply, consent in greetings), the middle years (prepare for puberty
// BEFORE it starts, periods and wet dreams for ALL children, online basics & reporting scary content), the teen
// talks (consent, online & porn-literacy against the manosphere, respect in relationships, staying askable through
// the eye-rolls), facts and your values (give honest facts AND share your values rather than choosing between
// them — silence cedes the field to peers and the algorithm), tools & help (age-by-age guides, ready scripts, the
// open-door habit, and routing any child-safety concern to Be the Safe Adult g69). Protective and evidence-based:
// correct names and talking make children SAFER, not more at risk; age-appropriate, accurate, non-explicit
// guidance is expert-reviewed; respects family values while keeping facts honest and NEVER shames a parent for not
// knowing. Builds on (and mirrors) the kids' journey from My Body, My Rules (g02); around it sit the
// positive-parenting pillars (g65-g69). India: these conversations are too often never had, and silence and "log
// kya kahenge" leave the internet and the manosphere to teach instead — the node gently breaks the cycle with
// culturally-aware scripts, mindful of grandparents and joint families. gameId "the-talks".
import type { V2GameConfig, Scenario } from "./v2-schema";

const SCENARIOS: Scenario[] = [
  {"id":"tk-001","cat":"how-to-talk","type":"strike-rewrite","hook":"\"There's one big, dreaded 'talk' you have to get perfectly right.\"","myth":{"un":"There's one big, dreaded 'talk' you have to get perfectly right.","re":"It isn't one talk; it's many small, age-right conversations over years, and you can absolutely do those.","why":"Lots of small chats beat one terrifying lecture."},"relearn":"It's not one big talk; it's many small, age-right conversations over time, and you can do those.","persona":"Vikram","source":"many small talks"},
  {"id":"tk-002","cat":"how-to-talk","type":"strike-rewrite","hook":"\"If I talk to my child about bodies and relationships, I'll encourage them too early.\"","myth":{"un":"If I talk to my child about bodies and relationships, I'll encourage them too early.","re":"Research shows honest, age-appropriate talks lead to later, safer choices, not earlier ones; silence is the real risk.","why":"Talking protects; it doesn't push."},"relearn":"Honest, age-appropriate talks lead to later and safer choices, not earlier ones; talking protects kids.","persona":"Divya","source":"talking protects"},
  {"id":"tk-003","cat":"how-to-talk","type":"branch","hook":"Your child asks a question about bodies and you feel a jolt of panic.","options":[{"text":"Stay calm, answer simply and honestly at their level","consequence":"You stay their go-to source.","outcome":"calm","best":true},{"text":"Get flustered, shut it down or say 'ask later'","consequence":"Staying calm and answering simply keeps you their source; shutting it down sends them to find out elsewhere."}],"debrief":"Meet a child's question calmly and answer simply at their level, rather than shutting it down.","relearn":"Answer kids' body questions calmly and simply; shutting them down just sends them elsewhere.","persona":"Vikram","source":"stay calm"},
  {"id":"tk-004","cat":"how-to-talk","type":"strike-rewrite","hook":"\"If I don't know the answer, I shouldn't say anything at all.\"","myth":{"un":"If I don't know the answer, I shouldn't say anything at all.","re":"'I don't know, let's find out together' is a great answer; it models honesty and keeps the door open.","why":"Not-knowing handled well builds trust."},"relearn":"'I don't know, let's find out together' is a great answer; you don't need every answer ready.","persona":"Divya","source":"I don't know"},
  {"id":"tk-005","cat":"how-to-talk","type":"match","hook":"Match each conversation skill to what it does.","pairs":[{"left":"Staying calm and unshocked","right":"Keeps your child willing to ask"},{"left":"Answering at their level","right":"Makes the answer land"},{"left":"Saying 'great question'","right":"Rewards them for coming to you"}],"relearn":"Staying calm, answering at their level and welcoming questions keep your child coming to you.","persona":"any","source":"talk skills"},
  {"id":"tk-006","cat":"how-to-talk","type":"reflect","hook":"Sam: the aim isn't a perfect speech; it's being the askable parent your child keeps coming back to. Sit right?","prompt":"What do you think?","options":["Sits right","Be askable","Keep the door open"],"affirm":"The goal isn't a flawless talk but being the askable, open-door parent a child keeps returning to.","relearn":"The aim is to be the askable parent your child keeps coming back to, not to give a perfect speech.","persona":"any","source":"be askable"},
  {"id":"tk-007","cat":"how-to-talk","type":"spot","hook":"Spot what keeps a child coming to their parent with questions.","scene":[{"id":"a","text":"Calm, warm, honest answers","trick":false},{"id":"b","text":"Shock, anger or 'you're too young'","trick":true},{"id":"c","text":"Welcoming even awkward questions","trick":false}],"why":"Calm, warm, honest, welcoming answers keep a child asking; shock and shaming send them away.","relearn":"Keep a child asking by answering calmly and welcoming even awkward questions, not by shaming them.","persona":"any","source":"keep them asking"},
  {"id":"tk-008","cat":"how-to-talk","type":"branch","hook":"You missed a chance to talk and now feel you've left it too late.","options":[{"text":"Start now; it's never too late to open the conversation","consequence":"You reopen the door at any age.","outcome":"start-now","best":true},{"text":"Decide the window has closed and stay silent","consequence":"Starting now reopens the door at any age; deciding it's too late guarantees the silence you fear."}],"debrief":"It's never too late to start the conversations; begin now rather than deciding the window has closed.","relearn":"Start the talks now whatever your child's age; it's never too late to open the door.","persona":"Divya","source":"never too late"},
  {"id":"tk-009","cat":"how-to-talk","type":"role-play","hook":"Your child asks something about bodies in the middle of a busy moment. You want to honour it.","setup":"Honour the question:","yourLine":[{"text":"\"That's a really good question, let's talk about it properly after dinner, I'll remember.\"","best":true},{"text":"\"Shh, we don't talk about that, especially not here.\""}],"relearn":"Honouring the question, even if you park it briefly, keeps it safe to ask, rather than teaching shame.","persona":"Priya","source":"honour the question"},
  {"id":"tk-010","cat":"how-to-talk","type":"reflect","hook":"Sam: every calm answer makes the next, harder question easier for your child to ask. Worth it?","prompt":"What's your take?","options":["Worth it","Builds the habit","Yes"],"affirm":"Each calm answer builds the trust that makes the next, harder question easier for your child to bring you.","relearn":"Every calm answer makes the next, harder question easier for your child to ask.","persona":"any","source":"each answer builds"},
  {"id":"tk-011","cat":"how-to-talk","type":"sort","hook":"Sort: an approach that opens the conversation, or one that closes it?","items":[{"id":"a","text":"Honest, calm, age-right answers"},{"id":"b","text":"Shame, panic or avoidance"},{"id":"c","text":"Little chats as they come up"},{"id":"d","text":"Waiting for one perfect big talk"}],"bins":[{"id":"opens","label":"Opens it up"},{"id":"closes","label":"Shuts it down"}],"key":{"a":"opens","b":"closes","c":"opens","d":"closes"},"relearn":"Honest calm answers and little ongoing chats open the conversation; shame and waiting for one big talk shut it down.","persona":"any","source":"open vs close"},
  {"id":"tk-012","cat":"how-to-talk","type":"role-play","hook":"You feel awkward but want to start a first small conversation with your child. You begin gently.","setup":"Begin gently:","yourLine":[{"text":"\"I want you to know you can always ask me anything about your body or growing up, no question is silly.\"","best":true},{"text":"\"We'll talk about all that when you're much older.\""}],"relearn":"An open invitation that no question is silly starts the lifelong door, even if you feel awkward doing it.","persona":"Vikram","source":"open invitation"},
  {"id":"tk-013","cat":"early-years","type":"strike-rewrite","hook":"\"Teaching little kids the correct names for private body parts is inappropriate.\"","myth":{"un":"Teaching little kids the correct names for private body parts is inappropriate.","re":"Correct names are a protection: children who know them are likelier to be left alone by abusers and to tell clearly if something happens.","why":"Right words are a safety tool, not a loss of innocence."},"relearn":"Teaching correct body-part names protects children; it helps prevent abuse and helps them disclose clearly.","persona":"Divya","source":"correct names protect"},
  {"id":"tk-014","cat":"early-years","type":"sort","hook":"Sort: a body-safety basic for a young child, or not age-appropriate yet?","items":[{"id":"a","text":"Correct names for body parts"},{"id":"b","text":"Explicit details of sex"},{"id":"c","text":"Private parts are private; safe vs unsafe touch"},{"id":"d","text":"Adult relationship complexities"}],"bins":[{"id":"now","label":"Right for young kids"},{"id":"later","label":"For when older"}],"key":{"a":"now","b":"later","c":"now","d":"later"},"relearn":"Correct names and safe-vs-unsafe touch suit young children; explicit details and adult complexities come much later.","persona":"any","source":"now vs later"},
  {"id":"tk-015","cat":"early-years","type":"match","hook":"Match each early body-safety idea to a simple way to teach it.","pairs":[{"left":"Your body belongs to you","right":"\"You're the boss of your own body.\""},{"left":"Private parts are private","right":"\"These are just for you, not for others.\""},{"left":"Tell a safe grown-up","right":"\"If anything feels wrong, tell me, you'll never be in trouble.\""}],"relearn":"Body ownership, privacy and 'tell a safe grown-up' are taught simply, in a young child's own words.","persona":"Divya","source":"teach it simply"},
  {"id":"tk-016","cat":"early-years","type":"strike-rewrite","hook":"\"Kids should keep 'body secrets' to be polite to adults.\"","myth":{"un":"Kids should keep 'body secrets' to be polite to adults.","re":"Teach that no one should ask them to keep a secret about their body, and they can always say no and tell you.","why":"Body secrets are a grooming red flag."},"relearn":"No one should ask a child to keep a body secret; teach them they can always say no and tell you.","persona":"Divya","source":"no body secrets"},
  {"id":"tk-017","cat":"early-years","type":"branch","hook":"Your little one asks 'where do babies come from?' and you freeze.","options":[{"text":"Give a simple, true answer at their level","consequence":"You satisfy their curiosity honestly.","outcome":"simple-true","best":true},{"text":"Tell a stork-style story or shut it down","consequence":"A simple true answer satisfies curiosity and builds trust; a made-up story or shutdown teaches the topic is off-limits."}],"debrief":"Answer 'where do babies come from?' simply and truthfully at the child's level, not with a myth or a shutdown.","relearn":"Give little kids a simple true answer about where babies come from, not a stork story or silence.","persona":"Vikram","source":"simple true answer"},
  {"id":"tk-018","cat":"early-years","type":"strike-rewrite","hook":"\"Forcing a child to hug relatives teaches good manners.\"","myth":{"un":"Forcing a child to hug relatives teaches good manners.","re":"Letting a child choose how to greet people teaches consent, that their yes and no about their body count.","why":"Bodily choice now builds consent for life."},"relearn":"Letting a child choose whether to hug teaches consent; forcing affection overrides their bodily 'no'.","persona":"Priya","source":"consent in greetings"},
  {"id":"tk-019","cat":"early-years","type":"reflect","hook":"Sam: 'you're the boss of your body' is consent, taught at age four. Powerful, isn't it?","prompt":"What do you think?","options":["Powerful","Consent early","Love that"],"affirm":"Teaching a small child that they're the boss of their own body plants the roots of consent for life.","relearn":"'You're the boss of your body' is consent taught at age four, the foundation for everything later.","persona":"any","source":"consent at four"},
  {"id":"tk-020","cat":"early-years","type":"spot","hook":"Spot the early lesson that keeps a child safer.","scene":[{"id":"a","text":"Knowing correct body-part names","trick":false},{"id":"b","text":"Being told their body isn't theirs to control","trick":true},{"id":"c","text":"Knowing they can always tell you","trick":false}],"why":"Correct names and 'you can always tell me' keep a child safer; teaching they don't control their body doesn't.","relearn":"Early safety comes from correct names and an open door, not from teaching a child their body isn't theirs.","persona":"Divya","source":"safer early"},
  {"id":"tk-021","cat":"early-years","type":"role-play","hook":"Your child proudly uses a correct body-part name and a relative gasps. You want to back your child.","setup":"Back your child calmly:","yourLine":[{"text":"\"Those are just the proper names, we teach them so she stays safe and can tell us things.\"","best":true},{"text":"\"Sorry, sorry, we'll teach her not to say that.\""}],"relearn":"Calmly backing the correct names protects your child's safety tool instead of shaming them into silence.","persona":"Divya","source":"back the names"},
  {"id":"tk-022","cat":"early-years","type":"branch","hook":"A young child says they don't want a certain adult to bathe or touch them.","options":[{"text":"Listen, take it seriously, and respect their 'no'","consequence":"You honour their instincts and safety.","outcome":"respected","best":true},{"text":"Override them because the adult is family","consequence":"Taking a child's 'no' seriously honours their instincts and safety; overriding it teaches them their 'no' doesn't count."}],"debrief":"Take a young child's 'no' about their body seriously, even with family; it protects them and teaches consent.","relearn":"Respect a child's 'no' about their body, even toward family; overriding it erodes their safety instinct.","persona":"Priya","source":"respect their no"},
  {"id":"tk-023","cat":"middle-years","type":"strike-rewrite","hook":"\"You should wait until puberty starts to explain puberty.\"","myth":{"un":"You should wait until puberty starts to explain puberty.","re":"Prepare children before the changes begin, ideally by around nine, so periods, wet dreams and body changes never come as a frightening shock.","why":"Forewarned is far less frightening."},"relearn":"Explain puberty before it starts (by around nine) so the changes never come as a frightening shock.","persona":"Divya","source":"prep before puberty"},
  {"id":"tk-024","cat":"middle-years","type":"sort","hook":"Sort: worth covering before puberty hits, or leave for later?","items":[{"id":"a","text":"Periods and wet dreams are normal"},{"id":"b","text":"Body changes that are coming"},{"id":"c","text":"Detailed adult relationship advice"},{"id":"d","text":"Basic online safety and privacy"}],"bins":[{"id":"before","label":"Cover before puberty"},{"id":"later","label":"Later"}],"key":{"a":"before","b":"before","c":"later","d":"before"},"relearn":"Periods, wet dreams, coming changes and online basics suit pre-puberty; detailed adult advice waits.","persona":"any","source":"before or later"},
  {"id":"tk-025","cat":"middle-years","type":"strike-rewrite","hook":"\"Only girls need to know about periods, and only boys about wet dreams.\"","myth":{"un":"Only girls need to know about periods, and only boys about wet dreams.","re":"All children benefit from understanding everyone's puberty; it builds empathy and ends shame and teasing.","why":"Shared knowledge ends shame."},"relearn":"All children should learn about everyone's puberty, periods and wet dreams alike; it builds empathy and ends shame.","persona":"Priya","source":"everyone learns"},
  {"id":"tk-026","cat":"middle-years","type":"branch","hook":"Your nine-year-old is getting a phone and the online world is opening up.","options":[{"text":"Start simple talks about privacy, kindness and telling you about anything scary","consequence":"You build their online safety net early.","outcome":"online-safe","best":true},{"text":"Hand over the device with no conversation","consequence":"Early simple online talks build a safety net; handing over a device silently leaves them to the internet alone."}],"debrief":"Start simple online-safety talks (privacy, kindness, telling you about anything scary) as a child goes online.","relearn":"Pair a first device with simple online-safety talks; don't hand it over with no conversation.","persona":"Vikram","source":"online basics"},
  {"id":"tk-027","cat":"middle-years","type":"match","hook":"Match each pre-teen topic to a calm way in.","pairs":[{"left":"Periods","right":"\"It's a normal, healthy sign of growing up.\""},{"left":"Wet dreams","right":"\"This happens to bodies, nothing's wrong.\""},{"left":"Online strangers","right":"\"Tell me about anyone who makes you uneasy.\""}],"relearn":"Periods, wet dreams and online strangers each have a calm, normalising way to open the conversation.","persona":"any","source":"calm ways in"},
  {"id":"tk-028","cat":"middle-years","type":"reflect","hook":"Sam: a child told about periods before their first one feels prepared, not terrified. Worth it?","prompt":"What do you think?","options":["Worth it","Prepared not scared","Yes"],"affirm":"Preparing a child for puberty before it starts replaces fear and shame with readiness and confidence.","relearn":"A child prepared for puberty before it starts feels ready, not terrified.","persona":"Divya","source":"prepared"},
  {"id":"tk-029","cat":"middle-years","type":"spot","hook":"Spot the pre-teen message that builds safety and confidence.","scene":[{"id":"a","text":"\"These changes are normal and healthy\"","trick":false},{"id":"b","text":"\"We don't talk about such dirty things\"","trick":true},{"id":"c","text":"\"Tell me about anything online that scares you\"","trick":false}],"why":"Normalising changes and inviting them to report scary online things build safety; shaming the topic doesn't.","relearn":"Pre-teen safety comes from normalising the changes and inviting them to tell you, not from shame.","persona":"any","source":"build safety"},
  {"id":"tk-030","cat":"middle-years","type":"branch","hook":"Your pre-teen mentions something they saw online that clearly unsettled them.","options":[{"text":"Stay calm, thank them for telling you, and talk it through","consequence":"They learn telling you is safe and worth it.","outcome":"safe-telling","best":true},{"text":"React with anger or take the device away as punishment","consequence":"Calm thanks and talking it through keeps them telling you; anger or punishment teaches them to hide it next time."}],"debrief":"When a child reports something unsettling online, stay calm and thank them so they keep telling you.","relearn":"Thank a child for reporting scary online content and talk it through; reacting with anger teaches them to hide it.","persona":"Vikram","source":"thank them for telling"},
  {"id":"tk-031","cat":"middle-years","type":"role-play","hook":"You want to prepare your daughter for periods, calmly and positively. You bring it up.","setup":"Bring it up warmly:","yourLine":[{"text":"\"Soon your body will start changing and one day you'll get your period, it's normal and I'll help you through it.\"","best":true},{"text":"\"You'll find out about all that when it happens.\""}],"relearn":"A warm, matter-of-fact heads-up makes a first period feel expected and supported, not frightening or shameful.","persona":"Divya","source":"prep for periods"},
  {"id":"tk-032","cat":"middle-years","type":"reflect","hook":"Sam: the years just before puberty are the golden window, prepared kids handle it so much better. Agree?","prompt":"What's your take?","options":["Agree","Golden window","Prepare them"],"affirm":"The years just before puberty are the ideal window to prepare a child so the changes feel manageable.","relearn":"The years just before puberty are the golden window; prepared kids handle the changes far better.","persona":"any","source":"golden window"},
  {"id":"tk-033","cat":"the-teen-talks","type":"strike-rewrite","hook":"\"Once they're teens and online, it's too late and pointless to talk.\"","myth":{"un":"Once they're teens and online, it's too late and pointless to talk.","re":"Teens still want a trusted adult; staying askable about relationships, consent and online life matters most now.","why":"The door matters more, not less, in the teen years."},"relearn":"Teens still need a trusted adult; staying askable about relationships, consent and online life matters most now.","persona":"Vikram","source":"not too late"},
  {"id":"tk-034","cat":"the-teen-talks","type":"sort","hook":"Sort: a teen-years talk worth having, or one to skip?","items":[{"id":"a","text":"What consent really means"},{"id":"b","text":"How online porn distorts real sex and bodies"},{"id":"c","text":"Respect in dating and breakups"},{"id":"d","text":"Nothing, they'll figure it out alone"}],"bins":[{"id":"have","label":"Worth having"},{"id":"skip","label":"Don't skip the talks"}],"key":{"a":"have","b":"have","c":"have","d":"skip"},"relearn":"Consent, porn-literacy and respect in relationships are worth talking about; leaving teens to 'figure it out alone' isn't.","persona":"any","source":"have the talk"},
  {"id":"tk-035","cat":"the-teen-talks","type":"strike-rewrite","hook":"\"What teens see online about sex and relationships is a fine substitute for talking to me.\"","myth":{"un":"What teens see online about sex and relationships is a fine substitute for talking to me.","re":"Online content and the manosphere often teach distortion and disrespect; your honest voice is the antidote.","why":"If you stay silent, the algorithm fills the gap."},"relearn":"Online content often distorts sex and respect; if you stay silent the algorithm teaches instead, so your voice matters.","persona":"Vikram","source":"your voice is the antidote"},
  {"id":"tk-036","cat":"the-teen-talks","type":"branch","hook":"Your teen rolls their eyes and says they 'already know everything' about relationships.","options":[{"text":"Stay warm and open, sharing your view without lecturing","consequence":"You stay a resource they'll quietly use.","outcome":"open","best":true},{"text":"Lecture or give up because they resist","consequence":"Staying warm and non-lecturing keeps you a resource teens quietly use; lecturing or quitting closes the door."}],"debrief":"With an eye-rolling teen, stay warm and open and share without lecturing; you remain a quiet resource.","relearn":"Stay open and non-lecturing with a resistant teen; that keeps you a resource even through the eye-rolls.","persona":"Vikram","source":"through the eye-rolls"},
  {"id":"tk-037","cat":"the-teen-talks","type":"match","hook":"Match each teen topic to an opener that respects them.","pairs":[{"left":"Consent","right":"\"Both people freely wanting it, every time, matters.\""},{"left":"Online porn","right":"\"A lot of it isn't real; let's talk about what is.\""},{"left":"A first relationship","right":"\"I'm here, no judgement, whenever you want to talk.\""}],"relearn":"Consent, porn-literacy and first relationships each have a respectful opener that keeps a teen listening.","persona":"any","source":"respectful openers"},
  {"id":"tk-038","cat":"the-teen-talks","type":"reflect","hook":"Sam: a teen who can come to you about sex and relationships is a safer teen. Feel the stakes?","prompt":"What do you think?","options":["Feel it","Safer teen","Worth staying open"],"affirm":"A teen who can bring you questions about sex and relationships is safer than one left to the internet.","relearn":"A teen who can come to you about sex and relationships is a safer teen.","persona":"any","source":"safer teen"},
  {"id":"tk-039","cat":"the-teen-talks","type":"strike-rewrite","hook":"\"Talking to my teen about consent will give them ideas.\"","myth":{"un":"Talking to my teen about consent will give them ideas.","re":"Teaching consent gives them respect and safety, not ideas; it's among the most protective talks you can have.","why":"Consent knowledge protects, never encourages."},"relearn":"Teaching a teen consent gives them respect and safety, not 'ideas'; it's a deeply protective talk.","persona":"Vikram","source":"consent protects"},
  {"id":"tk-040","cat":"the-teen-talks","type":"spot","hook":"Spot what keeps a teen safe and connected.","scene":[{"id":"a","text":"Honest, non-judgemental conversations","trick":false},{"id":"b","text":"Shaming them about bodies or crushes","trick":true},{"id":"c","text":"Being a calm, askable resource","trick":false}],"why":"Honest non-judgemental talks and being askable keep a teen connected; shaming pushes them away and online.","relearn":"Teens stay safe and connected through honest, non-judgemental, askable parenting, not shame.","persona":"any","source":"safe and connected"},
  {"id":"tk-041","cat":"the-teen-talks","type":"role-play","hook":"Your teen asks something about sex that catches you off guard. You want to stay open.","setup":"Stay open and honest:","yourLine":[{"text":"\"Good question, I'm glad you asked me, here's what I know, and let's find out the rest together.\"","best":true},{"text":"\"Where did you hear that? You shouldn't be thinking about this.\""}],"relearn":"Welcoming a tough teen question, and finding answers together, keeps you their trusted source over the internet.","persona":"Vikram","source":"stay open teen"},
  {"id":"tk-042","cat":"the-teen-talks","type":"reflect","hook":"Sam: every awkward, honest teen talk is a small vote for them trusting you over the algorithm. Worth it?","prompt":"What's your take?","options":["Worth it","Over the algorithm","Keep talking"],"affirm":"Each honest teen conversation builds the trust that keeps your child coming to you rather than the algorithm.","relearn":"Every honest teen talk is a vote for them trusting you over the algorithm.","persona":"any","source":"over the algorithm"},
  {"id":"tk-043","cat":"facts-and-values","type":"strike-rewrite","hook":"\"I have to choose between honest facts and my family's values.\"","myth":{"un":"I have to choose between honest facts and my family's values.","re":"You can give accurate facts and share your values; kids can hold both, the facts to stay safe and your values to guide them.","why":"Facts and values are partners, not rivals."},"relearn":"You don't choose between honest facts and your values; give both, the facts for safety and your values to guide.","persona":"Vikram","source":"facts and values"},
  {"id":"tk-044","cat":"facts-and-values","type":"sort","hook":"Sort: belongs in the 'honest facts' a child needs, or in 'your family's values to share'?","items":[{"id":"a","text":"How bodies work and how to stay safe"},{"id":"b","text":"What your family believes about timing"},{"id":"c","text":"Accurate names and basic health facts"},{"id":"d","text":"Your hopes and guidance for them"}],"bins":[{"id":"facts","label":"Honest facts"},{"id":"values","label":"Your values"}],"key":{"a":"facts","b":"values","c":"facts","d":"values"},"relearn":"Body facts and safety are honest facts every child needs; beliefs about timing and your hopes are values to share.","persona":"any","source":"facts vs values"},
  {"id":"tk-045","cat":"facts-and-values","type":"strike-rewrite","hook":"\"Withholding facts will keep my child innocent and safe.\"","myth":{"un":"Withholding facts will keep my child innocent and safe.","re":"Missing facts make children more vulnerable, not safer; honest information plus your values is what truly protects them.","why":"Knowledge is a shield, not a threat."},"relearn":"Withholding facts makes children more vulnerable; honest information plus your values protects them.","persona":"Divya","source":"facts protect"},
  {"id":"tk-046","cat":"facts-and-values","type":"branch","hook":"Your values differ from some facts your child needs, and you're unsure how to handle it.","options":[{"text":"Share the facts honestly and add your values as your view","consequence":"Your child gets safety and your guidance both.","outcome":"both","best":true},{"text":"Hide the facts to enforce the values","consequence":"Sharing facts plus your values gives safety and guidance; hiding facts to enforce values leaves your child unsafe and likely to find out anyway."}],"debrief":"Give the honest facts and share your values as your perspective; don't hide facts to enforce values.","relearn":"Offer honest facts and your values together; hiding facts to protect values just leaves a child unsafe.","persona":"Vikram","source":"both together"},
  {"id":"tk-047","cat":"facts-and-values","type":"match","hook":"Match each tricky moment to a facts-plus-values response.","pairs":[{"left":"'What does that word mean?'","right":"Define it simply, then share your view"},{"left":"'When is it okay to...?'","right":"Give the facts, then your family's values"},{"left":"'My friend is dating'","right":"Discuss respect and safety, and your hopes"}],"relearn":"Each tricky question gets honest facts first, then your family's values, so a child has both safety and guidance.","persona":"any","source":"facts plus values"},
  {"id":"tk-048","cat":"facts-and-values","type":"reflect","hook":"Sam: your child can know the facts to stay safe and still carry the values you raise them with. Resonate?","prompt":"What do you think?","options":["Resonates","Both at once","That works"],"affirm":"Children can hold accurate facts for safety alongside the values their family raises them with; it isn't either/or.","relearn":"Your child can know the facts to stay safe and carry your values too; it's not either/or.","persona":"any","source":"hold both"},
  {"id":"tk-049","cat":"facts-and-values","type":"strike-rewrite","hook":"\"If I stay silent on values, my child won't be influenced by anyone.\"","myth":{"un":"If I stay silent on values, my child won't be influenced by anyone.","re":"If you don't share your values, peers, media and the algorithm will fill the gap; your voice belongs in the mix.","why":"Silence cedes the field to everyone else."},"relearn":"Silence on values doesn't keep a child neutral; peers and the algorithm fill the gap, so share your voice.","persona":"Vikram","source":"share your voice"},
  {"id":"tk-050","cat":"facts-and-values","type":"spot","hook":"Spot the approach that protects a child best.","scene":[{"id":"a","text":"Honest facts plus your shared values","trick":false},{"id":"b","text":"Silence and hoping for the best","trick":true},{"id":"c","text":"Open conversation, no shame","trick":false}],"why":"Honest facts with your values and open, shame-free conversation protect a child; silence leaves them exposed.","relearn":"Children are protected best by honest facts plus shared values and open talk, not by silence.","persona":"any","source":"protects best"},
  {"id":"tk-051","cat":"facts-and-values","type":"reflect","hook":"Sam: breaking the family silence doesn't betray your culture; it lets you pass on the best of it. Sit right?","prompt":"What's your take?","options":["Sits right","Pass on the best","Not a betrayal"],"affirm":"Breaking the silence around these topics lets parents pass on their values intentionally, rather than ceding them.","relearn":"Breaking the silence doesn't betray your culture; it lets you pass on the best of it, on purpose.","persona":"any","source":"pass it on"},
  {"id":"tk-052","cat":"tools-and-help","type":"branch","hook":"You want to actually feel ready for the questions instead of caught off guard.","options":[{"text":"Keep a few simple, age-right scripts ready for the common questions","consequence":"You answer with calm confidence.","outcome":"scripted","best":true},{"text":"Wing every question and hope you don't freeze","consequence":"A few ready scripts let you answer with calm confidence; winging every question risks the freeze that shuts kids down."}],"debrief":"Keep a few simple, age-right scripts ready so common questions don't catch you off guard.","relearn":"Ready a few age-right scripts; winging every hard question invites the freeze that closes the door.","persona":"Divya","source":"ready scripts"},
  {"id":"tk-053","cat":"tools-and-help","type":"match","hook":"Match each tool to what it gives a parent.","pairs":[{"left":"Age-by-age guides","right":"What to cover, and when"},{"left":"Ready scripts","right":"Words when you're caught off guard"},{"left":"The open-door habit","right":"A child who keeps coming to you"}],"relearn":"Age-by-age guides, ready scripts and the open-door habit are the core tools of guiding a child's RSE.","persona":"any","source":"the toolkit"},
  {"id":"tk-054","cat":"tools-and-help","type":"strike-rewrite","hook":"\"My own gaps and embarrassment mean I can't guide my child at all.\"","myth":{"un":"My own gaps and embarrassment mean I can't guide my child at all.","re":"You can learn alongside your child; nobody starts an expert, and your willingness matters more than perfect knowledge.","why":"Willingness beats expertise."},"relearn":"Your own gaps don't disqualify you; you can learn alongside your child, and willingness matters more than expertise.","persona":"Vikram","source":"learn alongside"},
  {"id":"tk-055","cat":"tools-and-help","type":"sort","hook":"Sort: a green-flag move for guiding your child, or one to rethink?","items":[{"id":"a","text":"Many small, calm, honest talks"},{"id":"b","text":"One panicked lecture, then silence"},{"id":"c","text":"Learning the facts you're unsure of"},{"id":"d","text":"Shaming questions away"}],"bins":[{"id":"green","label":"Green-flag move"},{"id":"rethink","label":"Rethink it"}],"key":{"a":"green","b":"rethink","c":"green","d":"rethink"},"relearn":"Small calm talks and learning the facts are green flags; one panicked lecture and shaming questions need a rethink.","persona":"any","source":"green or rethink"},
  {"id":"tk-056","cat":"tools-and-help","type":"branch","hook":"A question or comment from your child makes you worried about their safety.","options":[{"text":"Take it seriously and seek safeguarding guidance and support","consequence":"You act on a possible warning sign.","outcome":"safeguard","best":true},{"text":"Brush it off so you don't have to deal with it","consequence":"Taking it seriously and seeking guidance acts on a possible warning sign; brushing it off can miss real harm."}],"debrief":"If something your child says worries you for their safety, take it seriously and seek safeguarding guidance (see Be the Safe Adult).","relearn":"Act on a child-safety worry by taking it seriously and seeking guidance; don't brush it off.","persona":"Meena","source":"safeguard route"},
  {"id":"tk-057","cat":"tools-and-help","type":"reflect","hook":"Sam: the scripts you give your child are the ones you may never have got yourself, and that's the cycle breaking. Feel it?","prompt":"What do you think?","options":["Feel it","Cycle breaking","Giving what I missed"],"affirm":"Giving your child the words and openness you may never have received is exactly how the silence cycle breaks.","relearn":"The scripts you give your child are the ones you never got; that's the cycle breaking.","persona":"any","source":"cycle breaking"},
  {"id":"tk-058","cat":"tools-and-help","type":"spot","hook":"Spot the sustainable way to guide a child's RSE.","scene":[{"id":"a","text":"Ongoing small talks as they grow","trick":false},{"id":"b","text":"One big talk and never again","trick":true},{"id":"c","text":"Staying askable for years","trick":false}],"why":"Ongoing small talks and staying askable for years are sustainable; one big talk and done isn't.","relearn":"Guiding a child's RSE is ongoing small talks and an open door over years, not one big talk.","persona":"any","source":"sustainable guidance"},
  {"id":"tk-059","cat":"tools-and-help","type":"match","hook":"Match a parent's worry to the reassuring tool.","pairs":[{"left":"'I'll freeze on a hard question'","right":"A ready, simple script"},{"left":"'I don't know enough'","right":"Learn it together, age by age"},{"left":"'Something my child said worries me'","right":"Safeguarding guidance (Be the Safe Adult)"}],"relearn":"Each parent worry has a tool: a script, learning together, or safeguarding guidance when safety is a concern.","persona":"any","source":"worry to tool"},
  {"id":"tk-060","cat":"tools-and-help","type":"reflect","hook":"Sam: be askable, keep it age-right, give facts and your values, and route real worries to help. Equipped?","prompt":"What's your take?","options":["Equipped","I've got this","Ready"],"affirm":"Being askable, age-appropriate, honest with your values, and ready to route real worries equips a parent fully.","relearn":"You hold the kit: be askable, age-right, facts plus values, and route real safety worries to help.","persona":"any","source":"equipped"},
  {"id":"tk-061","cat":"tools-and-help","type":"role-play","hook":"Your co-parent feels too awkward to take part in the talks. You want to bring them in.","setup":"Bring them in gently:","yourLine":[{"text":"\"Let's do this together, even just being calm and askable matters, our kids need both of us.\"","best":true},{"text":"\"Fine, I'll handle all the awkward stuff myself then.\""}],"relearn":"Inviting a co-parent to simply be calm and askable shares the job and doubles a child's trusted doors.","persona":"Vikram","source":"bring co-parent in"},
  {"id":"tk-062","cat":"how-to-talk","type":"role-play","hook":"Your child asks a blunt question in front of guests and everyone goes quiet. You want to handle it gracefully.","setup":"Handle it gracefully:","yourLine":[{"text":"\"Great question, let's chat about it together a bit later, I'll give you a proper answer.\"","best":true},{"text":"\"Don't be rude, we'll never discuss that.\""}],"relearn":"A graceful park-it-for-later keeps the question safe to ask without shaming the child in front of others.","persona":"Priya","source":"graceful in public"},
  {"id":"tk-063","cat":"how-to-talk","type":"branch","hook":"You realise you tend to over-explain and overwhelm your child with too much at once.","options":[{"text":"Answer just what they asked, simply, and let them come back for more","consequence":"Your child takes it in and keeps asking.","outcome":"right-sized","best":true},{"text":"Deliver a long, anxious lecture","consequence":"Answering just what was asked keeps it digestible and the door open; an anxious lecture overwhelms and deters."}],"debrief":"Answer just the question asked, simply, and let your child come back for more, rather than over-explaining.","relearn":"Answer the actual question simply; over-explaining overwhelms a child and closes the door.","persona":"Vikram","source":"right-sized answers"},
  {"id":"tk-064","cat":"early-years","type":"role-play","hook":"Your four-year-old points and asks what a body part is called. You want to answer plainly.","setup":"Answer plainly:","yourLine":[{"text":"\"That's called a penis (or vulva), it's just the proper name, like elbow or knee.\"","best":true},{"text":"\"We don't say that word, it's rude.\""}],"relearn":"Naming body parts as plainly as elbows removes shame and gives a child the words that keep them safe.","persona":"Divya","source":"name it plainly"},
  {"id":"tk-065","cat":"early-years","type":"role-play","hook":"You want to teach your young child the 'safe grown-up' rule simply. You explain it.","setup":"Explain it simply:","yourLine":[{"text":"\"If anyone touches your private parts or asks you to keep a body secret, tell me, you'll never be in trouble.\"","best":true},{"text":"\"Just be good and do what grown-ups say.\""}],"relearn":"A clear 'tell me, you'll never be in trouble' rule gives a child permission to disclose, unlike 'obey grown-ups'.","persona":"Divya","source":"safe grown-up rule"},
  {"id":"tk-066","cat":"early-years","type":"sort","hook":"Sort: teaches a young child body safety, or accidentally undermines it?","items":[{"id":"a","text":"'You can say no to unwanted touch'"},{"id":"b","text":"'Always let elders hug and kiss you'"},{"id":"c","text":"'Tell me anything, no secrets about bodies'"},{"id":"d","text":"'Good kids never refuse adults'"}],"bins":[{"id":"safety","label":"Builds safety"},{"id":"undermine","label":"Undermines it"}],"key":{"a":"safety","b":"undermine","c":"safety","d":"undermine"},"relearn":"'You can say no' and 'no body secrets' build safety; 'always let elders' and 'never refuse adults' undermine it.","persona":"any","source":"safety or not"},
  {"id":"tk-067","cat":"early-years","type":"match","hook":"Match each young-child question to a simple, honest answer.","pairs":[{"left":"'Why is my body different from my sibling's?'","right":"Bodies come in different kinds, both are normal"},{"left":"'What's that for?'","right":"A calm, correct, one-line answer"},{"left":"'Can I say no to a hug?'","right":"Yes, your body is yours"}],"relearn":"Young children's body questions each have a simple, honest, shame-free answer that keeps them curious and safe.","persona":"Priya","source":"honest little answers"},
  {"id":"tk-068","cat":"middle-years","type":"role-play","hook":"Your pre-teen seems embarrassed about body changes. You want to normalise it warmly.","setup":"Normalise it warmly:","yourLine":[{"text":"\"Everything that's happening to your body is normal and healthy, and you can ask me anything, anytime.\"","best":true},{"text":"\"You're too sensitive about all this.\""}],"relearn":"Warmly normalising the changes and inviting questions replaces embarrassment with reassurance.","persona":"Divya","source":"normalise changes"},
  {"id":"tk-069","cat":"middle-years","type":"sort","hook":"Sort: a healthy pre-teen online habit to encourage, or a risk to address?","items":[{"id":"a","text":"Telling you about anything that feels off"},{"id":"b","text":"Sharing private info with strangers"},{"id":"c","text":"Keeping passwords and privacy"},{"id":"d","text":"Meeting online 'friends' alone"}],"bins":[{"id":"encourage","label":"Encourage it"},{"id":"address","label":"Address the risk"}],"key":{"a":"encourage","b":"address","c":"encourage","d":"address"},"relearn":"Telling you about off things and keeping privacy are healthy; sharing info with or meeting strangers are risks to address.","persona":"Vikram","source":"encourage or address"},
  {"id":"tk-070","cat":"middle-years","type":"branch","hook":"Your pre-teen asks a frank question about sex, earlier than you expected.","options":[{"text":"Answer honestly and age-appropriately, without shame","consequence":"You keep trust and give safe, true info.","outcome":"honest","best":true},{"text":"Act scandalised and refuse to answer","consequence":"An honest, age-right answer keeps trust and safety; acting scandalised teaches them not to ask you again."}],"debrief":"Answer an earlier-than-expected frank question honestly and age-appropriately, without shame.","relearn":"Answer frank pre-teen questions honestly and without shame; being scandalised just sends them elsewhere.","persona":"Divya","source":"answer honestly"},
  {"id":"tk-071","cat":"middle-years","type":"spot","hook":"Spot what best prepares a pre-teen for the years ahead.","scene":[{"id":"a","text":"Honest prep before changes and online life","trick":false},{"id":"b","text":"Leaving them to learn from peers and feeds","trick":true},{"id":"c","text":"An open door for any worry","trick":false}],"why":"Honest prep and an open door prepare a pre-teen; leaving them to peers and feeds leaves them exposed.","relearn":"Prepare a pre-teen with honest prep and an open door, not by leaving them to peers and the feed.","persona":"any","source":"best prep"},
  {"id":"tk-072","cat":"the-teen-talks","type":"role-play","hook":"Your teen asks about something explicit they saw online. You want to stay unflustered.","setup":"Stay unflustered:","yourLine":[{"text":"\"Thanks for asking me, a lot of that isn't how real life or real respect works, let's talk about what is.\"","best":true},{"text":"\"That's disgusting, I don't want to hear another word.\""}],"relearn":"Meeting an explicit question with calm porn-literacy keeps you the trusted source over the algorithm.","persona":"Vikram","source":"unflustered teen"},
  {"id":"tk-073","cat":"the-teen-talks","type":"role-play","hook":"Your teen is being pressured by a partner and confides in you. You want to support, not control.","setup":"Support, not control:","yourLine":[{"text":"\"I'm really glad you told me, no one should pressure you, what do you want to do, and how can I help?\"","best":true},{"text":"\"That's it, you're not seeing them again, end of discussion.\""}],"relearn":"Supporting their agency while offering help keeps a pressured teen talking to you, unlike taking over.","persona":"Vikram","source":"support not control"},
  {"id":"tk-074","cat":"the-teen-talks","type":"sort","hook":"Sort: keeps a teen coming to you, or pushes them to hide things?","items":[{"id":"a","text":"Calm, non-judgemental listening"},{"id":"b","text":"Punishing them for honesty"},{"id":"c","text":"Respecting their growing autonomy"},{"id":"d","text":"Snooping and shaming"}],"bins":[{"id":"comes","label":"Keeps them coming"},{"id":"hides","label":"Makes them hide"}],"key":{"a":"comes","b":"hides","c":"comes","d":"hides"},"relearn":"Calm listening and respecting autonomy keep a teen coming to you; punishing honesty and snooping make them hide.","persona":"any","source":"come or hide"},
  {"id":"tk-075","cat":"the-teen-talks","type":"branch","hook":"Your teen makes a choice about relationships you disagree with.","options":[{"text":"Stay connected and share your view while keeping the door open","consequence":"You keep influence and their trust.","outcome":"connected","best":true},{"text":"Issue ultimatums that end the conversation","consequence":"Staying connected keeps both your influence and their trust; ultimatums end the conversation and your sway with it."}],"debrief":"Stay connected and share your view on a teen's choice while keeping the door open, rather than issuing ultimatums.","relearn":"Keep the door open on choices you dislike; ultimatums cost you both influence and trust.","persona":"Vikram","source":"keep the door open"},
  {"id":"tk-076","cat":"facts-and-values","type":"role-play","hook":"Your child asks something where your values are strong. You want to give facts and your view honestly.","setup":"Give both honestly:","yourLine":[{"text":"\"Here's how it actually works, and here's what we believe about it in our family, both matter.\"","best":true},{"text":"\"Never mind the facts, just do as we say.\""}],"relearn":"Pairing the honest facts with your stated values gives a child both safety and your guidance to weigh.","persona":"Vikram","source":"both honestly"},
  {"id":"tk-077","cat":"facts-and-values","type":"sort","hook":"Sort: an honest fact a child needs for safety, or a value you choose to share?","items":[{"id":"a","text":"How conception and contraception work"},{"id":"b","text":"When your family feels is the right time"},{"id":"c","text":"Consent and how to stay safe"},{"id":"d","text":"Your hopes for their relationships"}],"bins":[{"id":"fact","label":"Safety fact"},{"id":"value","label":"Shared value"}],"key":{"a":"fact","b":"value","c":"fact","d":"value"},"relearn":"How bodies and consent work are safety facts; the 'right time' and your hopes are values you choose to share.","persona":"any","source":"fact or value"},
  {"id":"tk-078","cat":"facts-and-values","type":"sort","hook":"Sort: protects a child, or leaves them exposed?","items":[{"id":"a","text":"Honest facts plus your values"},{"id":"b","text":"Silence to 'protect innocence'"},{"id":"c","text":"An open, shame-free door"},{"id":"d","text":"Letting the feed teach instead"}],"bins":[{"id":"protects","label":"Protects them"},{"id":"exposed","label":"Leaves them exposed"}],"key":{"a":"protects","b":"exposed","c":"protects","d":"exposed"},"relearn":"Honest facts with values and an open door protect; silence and ceding to the feed leave a child exposed.","persona":"any","source":"protect or expose"},
  {"id":"tk-079","cat":"facts-and-values","type":"branch","hook":"You worry that giving facts will clash with what grandparents want kept quiet.","options":[{"text":"Give your child the safety facts while respecting elders kindly","consequence":"Your child stays informed and safe.","outcome":"informed","best":true},{"text":"Withhold facts to keep the peace at home","consequence":"Giving safety facts kindly keeps your child informed; withholding them for peace leaves your child unsafe."}],"debrief":"Give your child the safety facts they need while handling elders kindly; don't withhold them to keep the peace.","relearn":"Prioritise your child's safety facts over keeping the silence elders prefer; do it kindly, but do it.","persona":"Vikram","source":"facts over silence"},
  {"id":"tk-080","cat":"facts-and-values","type":"match","hook":"Match a values-laden question to a both-and reply.","pairs":[{"left":"'Is it wrong to...?'","right":"Here are the facts; here's what we believe"},{"left":"'Everyone's doing it'","right":"Let's separate facts from pressure, and our values"},{"left":"'Why can't I yet?'","right":"The honest reasons, plus our family's view"}],"relearn":"Values-laden questions each get a both-and reply: honest facts first, then your family's view.","persona":"any","source":"both-and replies"},
  {"id":"tk-081","cat":"tools-and-help","type":"role-play","hook":"You froze on a question yesterday and want to go back and repair it. You reopen it.","setup":"Reopen it warmly:","yourLine":[{"text":"\"I didn't answer you well yesterday, I was caught off guard, let's talk about it properly now.\"","best":true},{"text":"\"Let's just forget you ever asked that.\""}],"relearn":"Going back to repair a fumbled answer models honesty and shows your child the door is genuinely always open.","persona":"Divya","source":"repair a fumble"},
  {"id":"tk-082","cat":"tools-and-help","type":"sort","hook":"Sort: a realistic, sustainable parenting-talk habit, or an unrealistic one?","items":[{"id":"a","text":"Tiny talks in the car or at bedtime"},{"id":"b","text":"One scheduled formal lecture"},{"id":"c","text":"Answering as questions arise"},{"id":"d","text":"Waiting until you feel fully expert"}],"bins":[{"id":"real","label":"Realistic habit"},{"id":"unreal","label":"Unrealistic"}],"key":{"a":"real","b":"unreal","c":"real","d":"unreal"},"relearn":"Tiny everyday talks and answering as questions arise are realistic; a formal lecture or waiting to feel expert aren't.","persona":"any","source":"realistic habit"},
  {"id":"tk-083","cat":"tools-and-help","type":"spot","hook":"Spot the move that makes a parent more askable over time.","scene":[{"id":"a","text":"Welcoming questions without shame","trick":false},{"id":"b","text":"Reacting with anger or panic","trick":true},{"id":"c","text":"Repairing when you get one wrong","trick":false}],"why":"Welcoming questions and repairing mistakes make you more askable; anger and panic make you less.","relearn":"Become more askable by welcoming questions and repairing missteps, not by reacting with anger or panic.","persona":"any","source":"more askable"},
  {"id":"tk-084","cat":"tools-and-help","type":"match","hook":"Match each age to the headline focus of the talks.","pairs":[{"left":"Around 3-6","right":"Correct names, body safety, consent basics"},{"left":"Around 9-12","right":"Prepare for puberty and online life"},{"left":"13+","right":"Consent, online-literacy, respect in relationships"}],"relearn":"Each age has a headline focus: body safety young, puberty prep before, and consent and relationships in the teens.","persona":"any","source":"age to focus"},
];

export const THE_TALKS: V2GameConfig = {
  gameId: "the-talks",
  title: "The Talks, Age by Age",
  greet: "Hey — it’s Sam. Here’s the secret: there is no one dreaded ‘talk’. It’s many small, age-right conversations, and you can absolutely do them. We’ll go age by age — correct body names and consent for the little ones, puberty before it starts for the middle years, consent and porn-literacy for the teens — and you’ll learn to give honest facts AND your values, not one or the other. You don’t need every answer; ‘I don’t know, let’s find out together’ is a great one. Stay the askable open door, and the algorithm doesn’t get to teach them instead.",
  scenarios: SCENARIOS,
  categories: [
    { id: "how-to-talk", emoji: "🚪", label: "How to talk" },
    { id: "early-years", emoji: "🧒", label: "The early years" },
    { id: "middle-years", emoji: "🌱", label: "The middle years" },
    { id: "the-teen-talks", emoji: "🧑", label: "The teen talks" },
    { id: "facts-and-values", emoji: "⚖️", label: "Facts & your values" },
    { id: "tools-and-help", emoji: "🧰", label: "Tools & help" },
  ],
  badge: {
    title: "The Talks, Age by Age 💬",
    blurb: "You know it’s never one dreaded ‘talk’ but many small, age-right ones — correct body names and consent early, puberty before it starts, consent and porn-literacy for teens. You give honest facts AND your values, and stay the askable open door. 🚪",
  },
  helpLine: "Talking openly and using the correct body-part names make children SAFER, not more at risk — and they make it easier for a child to tell you if something is wrong. If a child ever shares that someone hurt or touched them, stay calm, believe them, tell them it’s not their fault, and get help: Childline 1098 or emergency 112. (Recognising and responding to child-safety concerns is covered in Be the Safe Adult.) This is guidance, not a substitute for professional advice.",
  helpLabel: "Get help · Childline 1098",
  reassure: "It isn’t one dreaded ‘talk’ — it’s many small, age-right conversations, and you can do them. You don’t need every answer; ‘I don’t know, let’s find out together’ is a great one and keeps you the askable door. Talking and using the correct body-part names make children safer, not more at risk — and you are never behind for starting today. If a child ever shares that someone hurt them, believe them and call Childline 1098. 🚪",
  reassureCats: ["how-to-talk"],
};
