// Content for Us, After Kids (node g61, Parenthood, Chapter 8) — NEW v2 build to GDD 61 (mechanic-embodying),
// OPENING Chapter 8 (Parenthood) with the relationship parenting strains most: the couple's own, and the self
// within it. A baby changes everything, including you two. 84 researched, India-grounded scenarios across
// the-big-shift → talk-through-tired → share-dont-resent → reconnecting → you-still-matter → tools-and-help, each
// encoded as one of the shared v2 play actions (branch / strike-rewrite / role-play / sort / reflect / match /
// spot) — no binary "tap the right card". Lead: branch (your move), strike-rewrite (bust the myth), role-play (say
// it). Six modes: the big shift (a baby reshapes the couple and each self — normalised; ~2 in 3 couples feel the
// dip and it isn't a verdict; thrivers use learnable skills, not luck), talk through the tired (communication &
// repair under exhaustion — name the tiredness, not each other; appreciation; assume good intent; busts "the
// romance is just over"), share don't resent (fair division is the strongest relationship protector; a partner's
// involvement is practical AND symbolic — "this is ours, not yours"; engages FATHERS directly — a father isn't
// "babysitting" his own child; links Equal Parents g62), reconnecting (rebuild emotional & physical intimacy at
// the pace of BOTH partners' readiness — no deadline, no obligation; recovery is individual; postpartum discomfort
// routes to a clinician), you still matter (protect each partner's identity & wellbeing — you're still a whole
// person, not only a parent; the "I used to be someone else" shift is common; persistent low mood routes to
// Looking After You g63), tools & help. Even-handed and warm: engages fathers as equal parents, offers partnership
// not pity, applies NO pressure on intimacy timing, frank but respectful; NOT medical advice. Builds on Choosing &
// Building (g53) and Real Relationships (g46); links Equal Parents (g62), Looking After You (g63), The Family Map
// (g57) and Respect at Home (g56). India: a new baby often arrives within a joint family (help, but also pressure
// & less couple privacy), and postpartum women face a dual burden, role conflict and guilt; strain that turns to
// control or abuse routes to Respect at Home (g56) and help. gameId "us-after-kids".
import type { V2GameConfig, Scenario } from "./v2-schema";

const SCENARIOS: Scenario[] = [
  {"id":"uk-001","cat":"the-big-shift","type":"strike-rewrite","hook":"\"If our relationship struggles after the baby, it means we're failing.\"","myth":{"un":"If our relationship struggles after the baby, it means we're failing.","re":"Around two in three couples find their satisfaction dips after a first child; the strain is common, not a verdict on your love.","why":"Knowing it's normal takes the panic out of it."},"relearn":"Most couples feel the strain after a baby; it's common and normal, not a sign you're failing.","persona":"Divya","source":"common not failing"},
  {"id":"uk-002","cat":"the-big-shift","type":"strike-rewrite","hook":"\"The couples who stay happy after kids just got lucky with an easy baby.\"","myth":{"un":"The couples who stay happy after kids just got lucky with an easy baby.","re":"The couples who thrive aren't luckier; they use specific skills, sharing the load, communicating and appreciating each other.","why":"It's skills you can learn, not luck."},"relearn":"Couples who thrive after kids use learnable skills, not luck or an easier baby.","persona":"Vikram","source":"skills not luck"},
  {"id":"uk-003","cat":"the-big-shift","type":"sort","hook":"Sort: a normal part of the new-baby shift, or a sign something's truly wrong?","items":[{"id":"a","text":"Feeling tired and short on couple time"},{"id":"b","text":"Being controlled or frightened by your partner"},{"id":"c","text":"More friction while you adjust"},{"id":"d","text":"Threats or being put down constantly"}],"bins":[{"id":"normal","label":"Normal adjustment"},{"id":"wrong","label":"Truly wrong, get help"}],"key":{"a":"normal","b":"wrong","c":"normal","d":"wrong"},"relearn":"Tiredness and more friction are normal adjustment; control, threats and constant put-downs are not, and need help.","persona":"any","source":"normal vs wrong"},
  {"id":"uk-004","cat":"the-big-shift","type":"branch","hook":"Since the baby, you and your partner feel more like exhausted teammates than lovers, and it scares you.","options":[{"text":"Name it together as a normal phase you'll actively work through","consequence":"You face the shift as a team, not a crisis.","outcome":"team","best":true},{"text":"Assume the relationship is over and withdraw","consequence":"Assuming it's over and withdrawing makes the distance real."}],"debrief":"Treat the post-baby dip as a normal phase to work through together, not proof the relationship is over.","relearn":"Name the post-baby shift as a normal phase to work on together, not a crisis.","persona":"Divya","source":"name the phase"},
  {"id":"uk-005","cat":"the-big-shift","type":"match","hook":"Match each part of the big shift to the reassuring truth.","pairs":[{"left":"Less time and energy for each other","right":"Common, and it eases as you adapt"},{"left":"You both feel changed","right":"New parents do change; that's normal"},{"left":"More little conflicts","right":"Friction while adjusting isn't the end"}],"relearn":"The dip in time, the sense of change and the extra friction are all normal parts of becoming parents.","persona":"any","source":"reassuring truths"},
  {"id":"uk-006","cat":"the-big-shift","type":"strike-rewrite","hook":"\"Becoming a parent shouldn't change who I am at all.\"","myth":{"un":"Becoming a parent shouldn't change who I am at all.","re":"Parenthood does shift your identity, and feeling 'I used to be someone else' is common; you can hold both selves.","why":"Acknowledging the change helps you adapt."},"relearn":"Parenthood shifts your identity; feeling changed is normal, and you can hold both who you were and who you're becoming.","persona":"Divya","source":"identity shifts"},
  {"id":"uk-007","cat":"the-big-shift","type":"reflect","hook":"Lensy: a baby reshapes you two and each of you; knowing that's normal is the first relief. Land okay?","prompt":"What do you think?","options":["Lands okay","That's a relief","Good to know"],"affirm":"Knowing the post-baby reshaping of the couple and the self is normal removes a lot of needless fear.","relearn":"The post-baby reshaping of you two, and of each of you, is normal; knowing that is the first relief.","persona":"any","source":"first relief"},
  {"id":"uk-008","cat":"the-big-shift","type":"spot","hook":"Spot the healthy way to meet the big shift.","scene":[{"id":"a","text":"Expecting an adjustment and teaming up","trick":false},{"id":"b","text":"Reading every hard day as doom","trick":true},{"id":"c","text":"Being patient with each other and yourselves","trick":false}],"why":"Expecting adjustment, teaming up and patience are healthy; reading every hard day as doom isn't.","relearn":"Meet the big shift with patience and teamwork, not by reading every hard day as doom.","persona":"Vikram","source":"meet the shift"},
  {"id":"uk-009","cat":"the-big-shift","type":"branch","hook":"You catch yourself comparing your tired, messy reality to glossy 'perfect new parents' online.","options":[{"text":"Tune out the highlight reel and judge by your own real progress","consequence":"You drop a needless extra weight.","outcome":"real","best":true},{"text":"Feel you're failing for not matching the feed","consequence":"Comparing to curated perfection only adds shame to exhaustion."}],"debrief":"Don't measure your real new-parent life against curated online perfection; judge by your own progress.","relearn":"Ignore the 'perfect parents' highlight reel; your real, messy progress is the only fair measure.","persona":"Divya","source":"no highlight reel"},
  {"id":"uk-010","cat":"the-big-shift","type":"reflect","hook":"Lensy: you're not a worse couple now, you're a couple under new load. Big difference. Feel it?","prompt":"What's your take?","options":["Feel it","Under load","Not worse"],"affirm":"You're not a worse couple after a baby; you're a couple carrying new load, which is workable.","relearn":"You're not a worse couple now, just one under new load, and that's something you can work with.","persona":"any","source":"under load"},
  {"id":"uk-011","cat":"talk-through-tired","type":"strike-rewrite","hook":"\"Once you have kids, the romance and real talking are just over.\"","myth":{"un":"Once you have kids, the romance and real talking are just over.","re":"Connection changes shape but isn't over; small, intentional communication and appreciation keep the bond alive.","why":"The bond is maintained, not finished."},"relearn":"Romance and real talking aren't over after kids; small, intentional connection keeps the bond alive.","persona":"Vikram","source":"not over"},
  {"id":"uk-012","cat":"talk-through-tired","type":"strike-rewrite","hook":"\"When we're both exhausted, snapping at each other is just unavoidable.\"","myth":{"un":"When we're both exhausted, snapping at each other is just unavoidable.","re":"Exhaustion is the enemy, not your partner; naming the tiredness and pausing hard talks for calmer moments protects you both.","why":"Aim the frustration at the problem, not the person."},"relearn":"Snapping isn't unavoidable; name the exhaustion, not each other, and hold hard talks for calmer moments.","persona":"Divya","source":"name the tired"},
  {"id":"uk-013","cat":"talk-through-tired","type":"branch","hook":"A small thing flares into a fight, but really you're both just running on no sleep.","options":[{"text":"Pause and say 'we're both exhausted, let's revisit this rested'","consequence":"You stop the spiral before it wounds.","outcome":"paused","best":true},{"text":"Push the argument to 'win' it while depleted","consequence":"Pushing to win while depleted says things you'll both regret."}],"debrief":"When a fight is really exhaustion talking, pause and revisit it rested rather than pushing to win.","relearn":"Pause depleted fights and revisit rested; don't try to win an argument that's really just tiredness.","persona":"Vikram","source":"pause the spiral"},
  {"id":"uk-014","cat":"talk-through-tired","type":"match","hook":"Match each communication habit to what it protects after a baby.","pairs":[{"left":"Naming tiredness, not blaming","right":"Fewer needless fights"},{"left":"Repairing quickly after a snap","right":"Trust through the hard weeks"},{"left":"Small daily appreciation","right":"The warmth the load erodes"}],"relearn":"Naming tiredness, repairing fast and appreciating each other are the habits that protect a couple under load.","persona":"any","source":"protective habits"},
  {"id":"uk-015","cat":"talk-through-tired","type":"strike-rewrite","hook":"\"Saying thank you for ordinary parenting stuff is unnecessary.\"","myth":{"un":"Saying thank you for ordinary parenting stuff is unnecessary.","re":"Expressing appreciation, even small and imperfect, is one of the strongest things that keeps couples close through this phase.","why":"Feeling seen sustains the bond."},"relearn":"Appreciation, even for ordinary parenting work, is one of the strongest ways couples stay close after kids.","persona":"Divya","source":"appreciation matters"},
  {"id":"uk-016","cat":"talk-through-tired","type":"role-play","hook":"Your partner has been quietly carrying a lot. You want to make them feel seen.","setup":"Tell them warmly:","yourLine":[{"text":"\"I see how much you're doing, and I'm grateful, we're in this together.\"","best":true},{"text":"\"This is just what parents do, no need to make a thing of it.\""}],"relearn":"Naming what they do and that you're in it together makes a depleted partner feel seen and held.","persona":"Vikram","source":"make them seen"},
  {"id":"uk-017","cat":"talk-through-tired","type":"spot","hook":"Spot the move that helps a hard conversation under exhaustion.","scene":[{"id":"a","text":"Picking a calmer moment to talk","trick":false},{"id":"b","text":"Launching a serious talk at 3am, depleted","trick":true},{"id":"c","text":"Leading with 'I' and a soft start","trick":false}],"why":"A calmer moment and a soft start help; launching a serious talk depleted at 3am rarely goes well.","relearn":"Help hard talks land by choosing a calmer moment and a soft start, not a depleted 3am ambush.","persona":"any","source":"help the talk"},
  {"id":"uk-018","cat":"talk-through-tired","type":"branch","hook":"You're hurt by something your partner said while frazzled, and resentment is building.","options":[{"text":"Raise it gently once you're both calmer, assuming good intent","consequence":"You clear the air without a blow-up.","outcome":"cleared","best":true},{"text":"Store it up as evidence against them","consequence":"Storing it as evidence builds a case that poisons the team."}],"debrief":"Raise hurts gently when calm and assume good intent; don't store them up as evidence.","relearn":"Raise hurts calmly, assuming good intent; storing them as a case against your partner corrodes the team.","persona":"Divya","source":"clear the air"},
  {"id":"uk-019","cat":"talk-through-tired","type":"reflect","hook":"Lensy: under sleep deprivation, assume your partner is tired, not against you. Worth holding onto?","prompt":"What do you think?","options":["Worth it","Tired not against me","I'll hold it"],"affirm":"Assuming good intent, that your partner is tired rather than against you, prevents most exhausted conflicts.","relearn":"Under exhaustion, assume your partner is tired, not against you; it defuses most conflicts.","persona":"any","source":"assume good intent"},
  {"id":"uk-020","cat":"talk-through-tired","type":"match","hook":"Match a frazzled moment to a kinder response.","pairs":[{"left":"Partner snaps over something small","right":"\"We're both wiped, let's pause.\""},{"left":"You feel unseen","right":"\"I need a little appreciation too.\""},{"left":"A serious issue keeps colliding with chaos","right":"\"Let's set ten calm minutes for this.\""}],"relearn":"Each frazzled moment has a kinder response that protects the couple instead of escalating.","persona":"any","source":"kinder responses"},
  {"id":"uk-021","cat":"share-dont-resent","type":"strike-rewrite","hook":"\"The mother is the natural default parent; the father just helps out.\"","myth":{"un":"The mother is the natural default parent; the father just helps out.","re":"Both parents are real parents; sharing the load fairly, not 'helping', is one of the strongest protectors of the relationship.","why":"Co-parenting is shared ownership, not assistance."},"relearn":"Both are real parents; fairly sharing the load, not 'helping out', strongly protects the relationship.","persona":"Vikram","source":"both real parents"},
  {"id":"uk-022","cat":"share-dont-resent","type":"strike-rewrite","hook":"\"A father looking after his own child is 'babysitting'.\"","myth":{"un":"A father looking after his own child is 'babysitting'.","re":"It's just parenting; a father caring for his child is doing his own job, not doing anyone a favour.","why":"You don't babysit your own kid."},"relearn":"A father caring for his child is parenting, not babysitting; it's his own job, not a favour.","persona":"Vikram","source":"not babysitting"},
  {"id":"uk-023","cat":"share-dont-resent","type":"sort","hook":"Sort: shared parenting that protects the couple, or a lopsided load that breeds resentment?","items":[{"id":"a","text":"Both tracking and doing the baby's needs"},{"id":"b","text":"One parent silently carrying it all"},{"id":"c","text":"Splitting nights and tasks fairly"},{"id":"d","text":"One parent 'helping' only when asked"}],"bins":[{"id":"shared","label":"Protective sharing"},{"id":"lopsided","label":"Resentment-breeding"}],"key":{"a":"shared","b":"lopsided","c":"shared","d":"lopsided"},"relearn":"Both tracking and doing, and fair splits, protect the couple; one carrying it all or only 'helping when asked' breeds resentment.","persona":"Divya","source":"shared vs lopsided"},
  {"id":"uk-024","cat":"share-dont-resent","type":"branch","hook":"You realise one of you is carrying almost all the baby load and quietly resenting it.","options":[{"text":"Make the whole load visible and renegotiate a fairer split together","consequence":"Resentment turns into a workable plan.","outcome":"renegotiated","best":true},{"text":"Let it build silently until it explodes","consequence":"Silent resentment grows until it bursts."}],"debrief":"Surface the full baby load and renegotiate a fair split before resentment builds and bursts.","relearn":"Make the load visible and share it fairly; silent resentment is what eventually explodes.","persona":"Divya","source":"renegotiate the load"},
  {"id":"uk-025","cat":"share-dont-resent","type":"match","hook":"Match each kind of post-baby work to the fair approach.","pairs":[{"left":"Night feeds and wake-ups","right":"Shared or alternated, not one person's"},{"left":"The mental load of tracking needs","right":"Both notice and plan, not one manager"},{"left":"Chores and baby care","right":"Owned in fair shares, not 'helped' with"}],"relearn":"Night wake-ups, the mental load and the chores are all fairer when owned together, not dumped on one parent.","persona":"any","source":"fair approach"},
  {"id":"uk-026","cat":"share-dont-resent","type":"strike-rewrite","hook":"\"Co-parenting and load-sharing are really mothers' topics.\"","myth":{"un":"Co-parenting and load-sharing are really mothers' topics.","re":"Co-parenting is for both parents directly; a father's involvement in the load is a top predictor of a happy couple.","why":"This is a both-parents conversation."},"relearn":"Co-parenting isn't a mothers-only topic; a father's real involvement strongly predicts a happy couple.","persona":"Vikram","source":"both-parent topic"},
  {"id":"uk-027","cat":"share-dont-resent","type":"reflect","hook":"Lensy: sharing the load isn't just practical, it says 'this is ours, not yours'. Feel the difference?","prompt":"What do you think?","options":["Feel it","Ours not yours","It matters"],"affirm":"Sharing the load is practical and symbolic: it tells your partner the children are 'ours', not their sole burden.","relearn":"Sharing the load says 'this is ours, not yours', which protects the couple as much as the practical help does.","persona":"Vikram","source":"ours not yours"},
  {"id":"uk-028","cat":"share-dont-resent","type":"spot","hook":"Spot what genuinely shares the parenting load.","scene":[{"id":"a","text":"Owning whole tasks without being asked","trick":false},{"id":"b","text":"Waiting to be told each step","trick":true},{"id":"c","text":"Both holding the mental load","trick":false}],"why":"Owning whole tasks unprompted and sharing the mental load genuinely share the work; waiting to be told doesn't.","relearn":"Truly sharing the load means owning tasks unprompted and holding the mental load, not waiting to be told.","persona":"Vikram","source":"genuine sharing"},
  {"id":"uk-029","cat":"share-dont-resent","type":"branch","hook":"Relatives praise your partner lavishly for doing the basic parenting you do daily unremarked.","options":[{"text":"Gently reset the frame: this is shared, ordinary parenting for you both","consequence":"You keep the standard equal for both parents.","outcome":"equal-standard","best":true},{"text":"Let the gendered double standard stand","consequence":"Letting it stand quietly devalues the default parent."}],"debrief":"Push back kindly on the double standard that praises a father for the parenting a mother does unremarked.","relearn":"Reset the gendered double standard kindly; the same parenting deserves the same.","persona":"Divya","source":"equal standard"},
  {"id":"uk-030","cat":"share-dont-resent","type":"reflect","hook":"Lensy: the fairer the load, the warmer the couple; this is the strongest protector there is. Worth prioritising?","prompt":"What's your take?","options":["Worth it","Fair load, warm couple","Prioritising it"],"affirm":"A fairly shared load is one of the strongest protectors of post-baby relationship satisfaction.","relearn":"The fairer the load, the warmer the couple; sharing it is the strongest protector there is.","persona":"any","source":"fair protects"},
  {"id":"uk-031","cat":"reconnecting","type":"strike-rewrite","hook":"\"After a baby, you owe each other sex again by a set date.\"","myth":{"un":"After a baby, you owe each other sex again by a set date.","re":"There's no deadline; intimacy returns at the pace of both partners' physical and emotional readiness, never on a schedule or by obligation.","why":"Readiness leads, never a clock."},"relearn":"Intimacy after a baby has no deadline; it returns at both partners' physical and emotional readiness, never by obligation.","persona":"any","source":"no deadline"},
  {"id":"uk-032","cat":"reconnecting","type":"strike-rewrite","hook":"\"Wanting to wait for intimacy after birth means something is wrong with you.\"","myth":{"un":"Wanting to wait for intimacy after birth means something is wrong with you.","re":"Recovery is individual and bodies and feelings differ; needing time, often weeks or more, is normal and healthy, not a problem.","why":"Healing has its own timeline."},"relearn":"Needing time for intimacy after birth is normal and healthy; recovery is individual, not a problem with you.","persona":"Divya","source":"waiting is normal"},
  {"id":"uk-033","cat":"reconnecting","type":"sort","hook":"Sort: a healthy way to rebuild closeness after kids, or pressure to avoid?","items":[{"id":"a","text":"Going at a pace you both choose"},{"id":"b","text":"Pressuring a partner who isn't ready"},{"id":"c","text":"Reconnecting emotionally first"},{"id":"d","text":"Treating intimacy as an obligation owed"}],"bins":[{"id":"healthy","label":"Healthy reconnecting"},{"id":"pressure","label":"Pressure to avoid"}],"key":{"a":"healthy","b":"pressure","c":"healthy","d":"pressure"},"relearn":"A shared pace and emotional reconnection first are healthy; pressuring an unready partner or treating intimacy as owed are not.","persona":"any","source":"healthy vs pressure"},
  {"id":"uk-034","cat":"reconnecting","type":"branch","hook":"You miss physical closeness, but your partner isn't ready yet after the birth.","options":[{"text":"Reconnect in small non-sexual ways and let intimacy return without pressure","consequence":"Closeness rebuilds on a foundation of safety.","outcome":"patient","best":true},{"text":"Push or guilt them into it before they're ready","consequence":"Pushing or guilting an unready partner damages trust and desire."}],"debrief":"Rebuild closeness without pressure, letting intimacy return when both are ready.","relearn":"Reconnect gently and patiently; pushing an unready partner harms the very closeness you want.","persona":"Vikram","source":"patient closeness"},
  {"id":"uk-035","cat":"reconnecting","type":"match","hook":"Match each small reconnection to what it rebuilds.","pairs":[{"left":"A short walk or chat together","right":"Everyday emotional closeness"},{"left":"A genuine hug, no agenda","right":"Safe physical warmth"},{"left":"Ten minutes of real attention","right":"Feeling like partners again"}],"relearn":"Small reconnections, a walk, an honest hug, real attention, rebuild the closeness a busy new-parent life erodes.","persona":"any","source":"small reconnections"},
  {"id":"uk-036","cat":"reconnecting","type":"strike-rewrite","hook":"\"Reconnecting means jumping straight back to how sex was before.\"","myth":{"un":"Reconnecting means jumping straight back to how sex was before.","re":"Intimacy after kids often rebuilds gradually and may look different; communication and patience matter more than going 'back to before'.","why":"New normal, not a rewind."},"relearn":"Intimacy after kids rebuilds gradually and may look different; patience and talking matter more than rushing back to before.","persona":"any","source":"new normal"},
  {"id":"uk-037","cat":"reconnecting","type":"role-play","hook":"You want to talk with your partner about reconnecting, without either of you feeling pressured.","setup":"Open it gently:","yourLine":[{"text":"\"No pressure at all, I just miss us, can we find small ways to feel close again when you're ready?\"","best":true},{"text":"\"It's been long enough, hasn't it?\""}],"relearn":"A no-pressure, 'I miss us', ready-when-you-are opener invites closeness instead of demanding it.","persona":"Vikram","source":"talk reconnect"},
  {"id":"uk-038","cat":"reconnecting","type":"reflect","hook":"Lensy: closeness rebuilds best on safety and zero pressure; emotional first, the rest follows. Make sense?","prompt":"What do you think?","options":["Makes sense","Safety first","No pressure"],"affirm":"Closeness rebuilds best with emotional safety and no pressure; emotional reconnection tends to come first.","relearn":"Closeness rebuilds on safety and no pressure, with emotional reconnection usually leading the way.","persona":"any","source":"safety first"},
  {"id":"uk-039","cat":"reconnecting","type":"branch","hook":"Intimacy after the birth is uncomfortable or painful and you're unsure if that's normal.","options":[{"text":"Talk to a clinician; discomfort is common and there's help for it","consequence":"You get real care instead of worry or shame.","outcome":"care","best":true},{"text":"Push through pain or avoid it in silence","consequence":"Pushing through pain or hiding it helps no one."}],"debrief":"Postpartum discomfort is common and treatable; see a clinician rather than pushing through pain or staying silent.","relearn":"See a clinician about postpartum discomfort; it's common and helpable, not to be endured.","persona":"Divya","source":"get care"},
  {"id":"uk-040","cat":"reconnecting","type":"reflect","hook":"Lensy: this is frank but yours to pace; nothing here is owed, and care is there if you need it. Feel respected?","prompt":"What's your take?","options":["Respected","Mine to pace","Good"],"affirm":"Intimacy after kids is yours to pace, with nothing owed and real care available; that's the respectful frame.","relearn":"Intimacy after kids is yours to pace, nothing owed, with care available if you need it.","persona":"any","source":"yours to pace"},
  {"id":"uk-041","cat":"you-still-matter","type":"strike-rewrite","hook":"\"A good parent disappears completely into their children.\"","myth":{"un":"A good parent disappears completely into their children.","re":"You're still a whole person, not only a parent; keeping some of your own self makes you a steadier, happier parent.","why":"A self isn't selfish; it sustains you."},"relearn":"Good parents don't vanish into their kids; keeping some of your own self makes you steadier and happier.","persona":"Divya","source":"still a person"},
  {"id":"uk-042","cat":"you-still-matter","type":"strike-rewrite","hook":"\"Feeling like 'I used to be someone else' after a baby is shameful.\"","myth":{"un":"Feeling like 'I used to be someone else' after a baby is shameful.","re":"This identity shift is extremely common; naming it, and reclaiming small pieces of your old self, is healthy, not shameful.","why":"Naming it is the start of holding both."},"relearn":"Feeling 'I used to be someone else' after a baby is very common and nothing to be ashamed of.","persona":"Divya","source":"identity is common"},
  {"id":"uk-043","cat":"you-still-matter","type":"sort","hook":"Sort: protects a parent's sense of self, or quietly erases it?","items":[{"id":"a","text":"Keeping one small thing that's just yours"},{"id":"b","text":"Zero time or identity outside the baby"},{"id":"c","text":"Partners covering so each gets a break"},{"id":"d","text":"Guilt for any need of your own"}],"bins":[{"id":"protects","label":"Protects the self"},{"id":"erases","label":"Erases it"}],"key":{"a":"protects","b":"erases","c":"protects","d":"erases"},"relearn":"A small thing of your own and partners trading breaks protect the self; zero identity and guilt for any need erase it.","persona":"any","source":"protect or erase"},
  {"id":"uk-044","cat":"you-still-matter","type":"branch","hook":"Your partner is fading into 'just a parent' and seems lost in it.","options":[{"text":"Actively make space for them to keep a piece of their own self","consequence":"You protect the person you fell for.","outcome":"space","best":true},{"text":"Assume self-sacrifice is just what parents do","consequence":"Assuming total self-sacrifice is normal lets the person you love disappear."}],"debrief":"Help your partner keep a piece of their own self; total self-erasure isn't what good parenting requires.","relearn":"Make space for your partner's own self; self-erasure isn't the price of good parenting.","persona":"Vikram","source":"make space"},
  {"id":"uk-045","cat":"you-still-matter","type":"match","hook":"Match each parent's need to why it matters.","pairs":[{"left":"A little time that's their own","right":"Refuels them for the kids"},{"left":"Being asked how they are","right":"Counters the invisible-parent feeling"},{"left":"Support for an old interest","right":"Keeps their identity alive"}],"relearn":"A little own-time, being asked how they are, and support for an interest all keep a parent whole.","persona":"Divya","source":"needs that matter"},
  {"id":"uk-046","cat":"you-still-matter","type":"strike-rewrite","hook":"\"Asking how the parent is, not just the baby, is unnecessary.\"","myth":{"un":"Asking how the parent is, not just the baby, is unnecessary.","re":"New parents, especially the one recovering, often feel unseen; asking 'how are you?' is small and powerful.","why":"Being asked matters more than it seems."},"relearn":"Asking how the parent is, not only the baby, matters; new parents often feel unseen, and the question helps.","persona":"Divya","source":"ask how they are"},
  {"id":"uk-047","cat":"you-still-matter","type":"reflect","hook":"Lensy: you can pour into your child and still keep a self; in fact, keeping one helps you parent. Sit right?","prompt":"What do you think?","options":["Sits right","Keep a self","It helps"],"affirm":"Keeping some of your own identity isn't at odds with good parenting; it sustains the parent you want to be.","relearn":"You can love your child fully and keep a self; in fact, keeping one makes you a steadier parent.","persona":"any","source":"keep a self"},
  {"id":"uk-048","cat":"you-still-matter","type":"spot","hook":"Spot what supports a new parent's wellbeing.","scene":[{"id":"a","text":"Regularly checking how they're really doing","trick":false},{"id":"b","text":"Expecting them to run on empty","trick":true},{"id":"c","text":"Sharing care so they can rest","trick":false}],"why":"Checking in and sharing care support wellbeing; expecting a parent to run on empty harms them.","relearn":"Support a new parent's wellbeing by checking in and sharing care, not by expecting them to run on empty.","persona":"Vikram","source":"support wellbeing"},
  {"id":"uk-049","cat":"you-still-matter","type":"branch","hook":"Your partner seems persistently low, tearful or detached weeks after the birth.","options":[{"text":"Gently encourage support; their mental health is real and helpable","consequence":"You meet a real need with care, not dismissal.","outcome":"supported","best":true},{"text":"Tell them to just cheer up and get on with it","consequence":"Postpartum low mood can be serious; 'just cheer up' harmfully dismisses it."}],"debrief":"Persistent low mood after birth is real and helpable; encourage support (see Looking After You).","relearn":"Take post-birth low mood seriously; encourage support.","persona":"Divya","source":"postpartum support"},
  {"id":"uk-050","cat":"tools-and-help","type":"branch","hook":"You want a simple way to keep the couple connected through the chaos.","options":[{"text":"Set up a short daily check-in: how are you, what do you need, one thank-you","consequence":"Connection becomes a habit, not an accident.","outcome":"check-in","best":true},{"text":"Wait for a calm week that never comes","consequence":"Waiting for a calm week means waiting forever."}],"debrief":"A short daily check-in, how are you, what do you need, one thank-you, keeps a couple connected through the chaos.","relearn":"Build a tiny daily check-in; don't wait for a calm week that never arrives.","persona":"Vikram","source":"daily check-in"},
  {"id":"uk-051","cat":"tools-and-help","type":"match","hook":"Match each tool to the job it does after kids.","pairs":[{"left":"The daily check-in","right":"Stay connected through the load"},{"left":"Protected couple time","right":"Keep the partnership alive"},{"left":"The help routes","right":"When strain needs more than the two of you"}],"relearn":"The check-in, protected couple time and the help routes are the core tools for a couple after kids.","persona":"any","source":"the toolkit"},
  {"id":"uk-052","cat":"tools-and-help","type":"role-play","hook":"In a busy joint household, you want to protect a little couple time without offending anyone.","setup":"Ask warmly:","yourLine":[{"text":"\"We love the help, and we'd treasure a short walk just the two of us now and then.\"","best":true},{"text":"\"We never get a moment alone in this house.\""}],"relearn":"A warm 'we love the help, and we'd treasure some couple time' protects the bond without a family rift.","persona":"Vikram","source":"protect couple time"},
  {"id":"uk-053","cat":"tools-and-help","type":"sort","hook":"Sort: a healthy support for the couple after kids, or strain that needs outside help?","items":[{"id":"a","text":"A weekly appreciation and check-in"},{"id":"b","text":"A partner controlling or frightening you"},{"id":"c","text":"Sharing the load and small reconnects"},{"id":"d","text":"Strain turning into put-downs or threats"}],"bins":[{"id":"support","label":"Healthy support"},{"id":"help","label":"Needs outside help"}],"key":{"a":"support","b":"help","c":"support","d":"help"},"relearn":"Check-ins, shared load and small reconnects are healthy support; control, threats or put-downs need outside help (see Respect at Home).","persona":"any","source":"support vs help"},
  {"id":"uk-054","cat":"tools-and-help","type":"strike-rewrite","hook":"\"If things get hard after the baby, there's nothing to do but endure it.\"","myth":{"un":"If things get hard after the baby, there's nothing to do but endure it.","re":"There's a lot you can do, share the load, communicate, reconnect, and reach for help for postpartum wellbeing or serious strain.","why":"It's workable, not just endurable."},"relearn":"Hard times after a baby are workable: share the load, communicate, reconnect, and reach for help when needed.","persona":"any","source":"workable not endure"},
  {"id":"uk-055","cat":"tools-and-help","type":"reflect","hook":"Lensy: protect the team, share the load, reconnect gently, and get help when it's beyond you two. Equipped?","prompt":"What do you think?","options":["Equipped","I've got this","Ready"],"affirm":"Protecting the team, sharing the load, reconnecting gently and reaching for help equip a couple for life after kids.","relearn":"You hold the kit: protect the team, share the load, reconnect gently, and get help when it's beyond the two of you.","persona":"any","source":"equipped"},
  {"id":"uk-056","cat":"tools-and-help","type":"branch","hook":"You're unsure whether your or your partner's struggle after the baby needs more than time.","options":[{"text":"Reach out, to each other, a clinician or support, you don't have to be sure","consequence":"You get clarity and help early.","outcome":"reached","best":true},{"text":"Wait it out alone until it feels unbearable","consequence":"Waiting it out alone until it's unbearable prolongs the struggle."}],"debrief":"You can reach out about a post-baby struggle while unsure; help for wellbeing or the couple is there early.","relearn":"Reach out early about a post-baby struggle; you don't have to be certain.","persona":"Divya","source":"reach out"},
  {"id":"uk-057","cat":"tools-and-help","type":"match","hook":"Match a post-baby need to where it routes.","pairs":[{"left":"Persistent low mood after birth","right":"Postpartum wellbeing support (Looking After You)"},{"left":"Sharing the parenting load fairly","right":"The equal-parenting node (Equal Parents)"},{"left":"Strain turning to control or fear","right":"Respect at Home and help"}],"relearn":"Postpartum wellbeing, fair load-sharing and any turn to control each have a clear place to route for help.","persona":"any","source":"where it routes"},
  {"id":"uk-058","cat":"tools-and-help","type":"spot","hook":"Spot the sustainable way to keep a couple strong after kids.","scene":[{"id":"a","text":"Small, regular connection and fair sharing","trick":false},{"id":"b","text":"One big holiday to 'fix' everything","trick":true},{"id":"c","text":"Reaching for help early when needed","trick":false}],"why":"Small regular connection, fair sharing and early help are sustainable; one big fix-it holiday rarely is.","relearn":"Keep a couple strong after kids with small regular connection and fair sharing, not one big fix-it.","persona":"any","source":"sustainable couple"},
  {"id":"uk-059","cat":"tools-and-help","type":"role-play","hook":"Your partner asks how you'll get through this exhausting new-parent stretch together. Set the tone.","setup":"Say it as a team:","yourLine":[{"text":"\"As a team, we share it, we check in daily, we stay kind, and we ask for help when we need it.\"","best":true},{"text":"\"We'll just survive it somehow.\""}],"relearn":"Setting a shared, kind, help-friendly tone turns survival into a plan you carry together.","persona":"Vikram","source":"set the tone"},
  {"id":"uk-060","cat":"the-big-shift","type":"role-play","hook":"A new-parent friend confides she fears her marriage is doomed because it feels so hard. You want to reassure her.","setup":"Reassure her warmly:","yourLine":[{"text":"\"Almost every couple feels this after a baby, it's the load, not your love; it can get better.\"","best":true},{"text":"\"Yeah, kids do ruin relationships, sadly.\""}],"relearn":"Telling her the strain is near-universal and about load, not love, replaces dread with hope she can act on.","persona":"Priya","source":"reassure friend"},
  {"id":"uk-061","cat":"the-big-shift","type":"sort","hook":"Sort: a fair expectation of early parenthood, or a setup for disappointment?","items":[{"id":"a","text":"Less sleep and less couple time for a while"},{"id":"b","text":"Everything staying exactly as before"},{"id":"c","text":"Needing to adapt as a team"},{"id":"d","text":"Feeling like perfect parents instantly"}],"bins":[{"id":"fair","label":"Fair expectation"},{"id":"setup","label":"Setup to hurt"}],"key":{"a":"fair","b":"setup","c":"fair","d":"setup"},"relearn":"Expecting less sleep and needing to adapt is fair; expecting nothing to change or instant perfection sets you up to hurt.","persona":"any","source":"fair expectations"},
  {"id":"uk-062","cat":"the-big-shift","type":"sort","hook":"Sort: within the normal post-baby adjustment, or a reason to get support?","items":[{"id":"a","text":"Occasional tears from sheer exhaustion"},{"id":"b","text":"Weeks of feeling numb or hopeless"},{"id":"c","text":"Bickering more while sleep-starved"},{"id":"d","text":"Frightening thoughts that worry you"}],"bins":[{"id":"normal","label":"Normal adjustment"},{"id":"support","label":"Get support"}],"key":{"a":"normal","b":"support","c":"normal","d":"support"},"relearn":"Exhausted tears and more bickering are normal; weeks of numbness or frightening thoughts are reasons to get support.","persona":"Divya","source":"adjust vs support"},
  {"id":"uk-063","cat":"the-big-shift","type":"reflect","hook":"Lensy: the goal isn't to skip the hard part, it's to go through it as a team. Sit right?","prompt":"What do you think?","options":["Sits right","Through it together","As a team"],"affirm":"The aim isn't to avoid the hard transition but to move through it together, which keeps the couple whole.","relearn":"The goal isn't skipping the hard part, but going through it as a team.","persona":"any","source":"through it together"},
  {"id":"uk-064","cat":"talk-through-tired","type":"role-play","hook":"You snapped at your partner over nothing while running on no sleep. You want to repair.","setup":"Repair simply:","yourLine":[{"text":"\"I'm sorry I snapped, that was the exhaustion talking, not how I feel about you.\"","best":true},{"text":"\"Well, you started it.\""}],"relearn":"A quick, honest repair, naming the exhaustion, mends a snap before it hardens into distance.","persona":"Vikram","source":"quick repair"},
  {"id":"uk-065","cat":"talk-through-tired","type":"sort","hook":"Sort: a soft start to a hard talk, or a harsh one that backfires?","items":[{"id":"a","text":"\"I'm struggling and need your help with...\""},{"id":"b","text":"\"You never do anything around here.\""},{"id":"c","text":"\"Can we find a calm minute to sort this?\""},{"id":"d","text":"\"What is wrong with you?\""}],"bins":[{"id":"soft","label":"Soft start"},{"id":"harsh","label":"Harsh start"}],"key":{"a":"soft","b":"harsh","c":"soft","d":"harsh"},"relearn":"'I'm struggling, can we find a calm minute' are soft starts; 'you never' and 'what is wrong with you' are harsh and backfire.","persona":"any","source":"soft vs harsh"},
  {"id":"uk-066","cat":"talk-through-tired","type":"match","hook":"Match each exhausted-couple trap to the skill that defuses it.","pairs":[{"left":"Snapping over nothing","right":"Pause and name the tiredness"},{"left":"Keeping score of who did more","right":"Appreciate instead of tally"},{"left":"Letting hurts pile up","right":"Repair quickly and gently"}],"relearn":"Snapping, score-keeping and piling up hurts are each defused by naming tiredness, appreciating and repairing fast.","persona":"any","source":"defusing traps"},
  {"id":"uk-067","cat":"talk-through-tired","type":"branch","hook":"You and your partner keep having the same fight in circles, both too tired to resolve it.","options":[{"text":"Agree to park it and book ten calm minutes when you're both rested","consequence":"You break the exhausted loop.","outcome":"parked","best":true},{"text":"Keep re-running it at midnight","consequence":"Re-running it depleted at midnight just deepens the rut."}],"debrief":"Break a circular tired fight by parking it for a calm, rested ten minutes, not re-running it depleted.","relearn":"Park circular tired fights for a rested moment; midnight re-runs never resolve them.","persona":"Vikram","source":"break the loop"},
  {"id":"uk-068","cat":"share-dont-resent","type":"role-play","hook":"You want to step up as an equal parent, not a 'helper'. You tell your partner how you see it.","setup":"Claim it as yours:","yourLine":[{"text":"\"These aren't your jobs I help with, they're ours, I'll own my half without being asked.\"","best":true},{"text":"\"Just tell me what you want me to do.\""}],"relearn":"Claiming the work as shared and owning it unasked turns a 'helper' into a true co-parent.","persona":"Vikram","source":"own my half"},
  {"id":"uk-069","cat":"share-dont-resent","type":"sort","hook":"Sort: a co-parenting move that shares the load, or one that quietly dumps it?","items":[{"id":"a","text":"Tracking the baby's needs yourself too"},{"id":"b","text":"Waiting to be handed a task list"},{"id":"c","text":"Taking whole nights in turn"},{"id":"d","text":"Calling your own parenting 'helping out'"}],"bins":[{"id":"share","label":"Shares the load"},{"id":"dump","label":"Dumps it on one"}],"key":{"a":"share","b":"dump","c":"share","d":"dump"},"relearn":"Tracking needs yourself and taking whole nights share the load; waiting for a list and 'helping out' dump it on one parent.","persona":"Vikram","source":"share or dump"},
  {"id":"uk-070","cat":"share-dont-resent","type":"role-play","hook":"Your partner keeps managing everything and won't hand any of it over. You want to truly take a share.","setup":"Offer to own, not assist:","yourLine":[{"text":"\"Let me fully own bath and bedtime, start to finish, so it's off your mind for good.\"","best":true},{"text":"\"Tell me if you need anything.\""}],"relearn":"Offering to own a whole domain end-to-end lifts the mental load, not just the task, off your partner.","persona":"Meena","source":"own a domain"},
  {"id":"uk-071","cat":"share-dont-resent","type":"match","hook":"Match each parent's contribution to the respect it deserves.","pairs":[{"left":"Night feeds and soothing","right":"Real, tiring work, equally valued"},{"left":"Tracking jabs, food, supplies","right":"The mental load, shared not solo"},{"left":"Daytime care while the other works","right":"Parenting, not 'babysitting'"}],"relearn":"Night care, the mental load and daytime care are all real parenting work that deserves equal respect.","persona":"any","source":"respect the work"},
  {"id":"uk-072","cat":"reconnecting","type":"role-play","hook":"You want your recovering partner to know there's zero pressure about intimacy. You reassure them.","setup":"Reassure clearly:","yourLine":[{"text":"\"There's no clock here, we go at your pace, I just want to feel close in whatever way works.\"","best":true},{"text":"\"So when are things going back to normal?\""}],"relearn":"A clear 'no clock, your pace' reassurance removes pressure and makes safe closeness possible.","persona":"Vikram","source":"zero pressure"},
  {"id":"uk-073","cat":"reconnecting","type":"sort","hook":"Sort: rebuilds closeness safely, or pressures a recovering partner?","items":[{"id":"a","text":"Letting readiness lead, both ways"},{"id":"b","text":"Hinting they're overdue"},{"id":"c","text":"Cuddles and talk with no agenda"},{"id":"d","text":"Sulking when they're not ready"}],"bins":[{"id":"safe","label":"Safe rebuilding"},{"id":"pressure","label":"Pressures them"}],"key":{"a":"safe","b":"pressure","c":"safe","d":"pressure"},"relearn":"Letting readiness lead and agenda-free affection rebuild safely; hinting they're overdue or sulking is pressure.","persona":"any","source":"safe vs pressure"},
  {"id":"uk-074","cat":"reconnecting","type":"reflect","hook":"Lensy: feeling close again often starts with a laugh or a hug, long before anything else. Reassuring?","prompt":"What do you think?","options":["Reassuring","Starts small","No rush"],"affirm":"Reconnection usually starts with small emotional closeness, a laugh or a hug, well before physical intimacy.","relearn":"Feeling close again often starts with a laugh or a hug, long before anything else.","persona":"Divya","source":"starts small"},
  {"id":"uk-075","cat":"reconnecting","type":"spot","hook":"Spot the pressure-free way to rebuild intimacy.","scene":[{"id":"a","text":"Following both partners' readiness","trick":false},{"id":"b","text":"Setting a deadline to 'get back to normal'","trick":true},{"id":"c","text":"Talking openly about what feels right","trick":false}],"why":"Following readiness and talking openly are pressure-free; setting a 'back to normal' deadline isn't.","relearn":"Rebuild intimacy by following readiness and talking openly, never by setting a deadline.","persona":"any","source":"pressure-free rebuild"},
  {"id":"uk-076","cat":"you-still-matter","type":"role-play","hook":"Your partner hasn't had a moment to themselves in weeks. You want to give them a real break.","setup":"Offer it generously:","yourLine":[{"text":"\"Go take two hours that are just yours, I've got the baby, you matter too.\"","best":true},{"text":"\"You can rest once everything's done.\""}],"relearn":"A real, no-strings break that says 'you matter too' refuels your partner and protects the person they are.","persona":"Vikram","source":"give a break"},
  {"id":"uk-077","cat":"you-still-matter","type":"role-play","hook":"A relative keeps asking only about the baby and never how the new mother is doing. You want to shift it.","setup":"Gently redirect:","yourLine":[{"text":"\"The baby's great, and how is Divya doing? She's been amazing and could use the asking.\"","best":true},{"text":"\"Yes, baby's fine, that's all that matters.\""}],"relearn":"Redirecting attention to how the parent is counters the invisible-parent feeling that wears new parents down.","persona":"Priya","source":"ask about the parent"},
  {"id":"uk-078","cat":"you-still-matter","type":"sort","hook":"Sort: keeps a parent whole, or erases them into the role?","items":[{"id":"a","text":"Holding onto one small personal thing"},{"id":"b","text":"Guilt over any time for yourself"},{"id":"c","text":"Partners trading time off"},{"id":"d","text":"Believing needs make you a bad parent"}],"bins":[{"id":"whole","label":"Keeps them whole"},{"id":"erase","label":"Erases them"}],"key":{"a":"whole","b":"erase","c":"whole","d":"erase"},"relearn":"A small personal thing and trading time off keep a parent whole; guilt over any need erases them into the role.","persona":"Meena","source":"whole vs erased"},
  {"id":"uk-079","cat":"you-still-matter","type":"match","hook":"Match each sign to what a depleted parent really needs.","pairs":[{"left":"Snappy and tearful from no rest","right":"A genuine break and support"},{"left":"Feeling invisible behind the baby","right":"To be seen and asked about"},{"left":"Losing touch with who they are","right":"Space to reclaim a little self"}],"relearn":"A depleted parent needs rest, to be seen, and space to keep some self, not more pressure.","persona":"Divya","source":"what they need"},
  {"id":"uk-080","cat":"you-still-matter","type":"branch","hook":"You feel guilty for wanting an hour to yourself away from the baby.","options":[{"text":"Take the hour without guilt; a refuelled parent is a better parent","consequence":"You return steadier and more present.","outcome":"refuelled","best":true},{"text":"Deny yourself any break to prove devotion","consequence":"Taking the hour refuels you to parent well; denying all rest to prove devotion just burns you out."}],"debrief":"Taking some time for yourself isn't a failure of devotion; a refuelled parent parents better.","relearn":"Take the break without guilt; self-care refuels the parent, it doesn't betray the child.","persona":"Divya","source":"guilt-free break"},
  {"id":"uk-081","cat":"tools-and-help","type":"role-play","hook":"You want to start a tiny nightly ritual to stay connected. You suggest it to your partner.","setup":"Suggest it warmly:","yourLine":[{"text":"\"Each night, two minutes, one hard thing and one good thing each? Just to stay us.\"","best":true},{"text":"\"We'll talk properly when life calms down.\""}],"relearn":"A tiny, doable nightly ritual keeps the couple connected now, instead of waiting for a calm that never comes.","persona":"Vikram","source":"nightly ritual"},
  {"id":"uk-082","cat":"tools-and-help","type":"role-play","hook":"Your partner seems to be struggling more than 'just tired', and you want to gently open the door to help.","setup":"Open it gently:","yourLine":[{"text":"\"I'm a bit worried about how heavy this feels for you, would it help to talk to someone together?\"","best":true},{"text":"\"You'll be fine, everyone copes.\""}],"relearn":"A gentle, worried, 'shall we talk to someone together' opens the door to help without shame or dismissal.","persona":"Meena","source":"open the door"},
  {"id":"uk-083","cat":"tools-and-help","type":"sort","hook":"Sort: a green-flag couple habit after kids, or a pattern to change?","items":[{"id":"a","text":"Daily check-ins and appreciation"},{"id":"b","text":"Bottling everything up"},{"id":"c","text":"Protecting a little couple time"},{"id":"d","text":"Keeping a silent resentment ledger"}],"bins":[{"id":"keep","label":"Green-flag habit"},{"id":"change","label":"Pattern to change"}],"key":{"a":"keep","b":"change","c":"keep","d":"change"},"relearn":"Check-ins, appreciation and protected couple time are habits to keep; bottling up and a resentment ledger need changing.","persona":"any","source":"keep or change"},
  {"id":"uk-084","cat":"tools-and-help","type":"reflect","hook":"Lensy: small habits, said out loud, beat grand gestures you never have energy for. Agree?","prompt":"What's your take?","options":["Agree","Small and steady","Out loud"],"affirm":"Small, consistent, spoken habits sustain a couple after kids better than grand gestures you can't sustain.","relearn":"Small habits done consistently beat grand gestures you never have the energy for.","persona":"any","source":"small beats grand"},
];

export const US_AFTER_KIDS: V2GameConfig = {
  gameId: "us-after-kids",
  title: "Us, After Kids",
  greet: "Hey — it’s Lensy. A baby changes everything — including you two. Two in three couples feel the dip; if it’s harder, that’s normal, not a verdict, but the load.",
  scenarios: SCENARIOS,
  categories: [
    { id: "the-big-shift", emoji: "🔄", label: "The big shift" },
    { id: "talk-through-tired", emoji: "💬", label: "Talk through the tired" },
    { id: "share-dont-resent", emoji: "🤝", label: "Share, don’t resent" },
    { id: "reconnecting", emoji: "💞", label: "Reconnecting" },
    { id: "you-still-matter", emoji: "🫂", label: "You still matter" },
    { id: "tools-and-help", emoji: "🧰", label: "Tools & help" },
  ],
  badge: {
    title: "Us, After Kids 💑",
    blurb: "You know the post-baby dip is normal, not a verdict. You name the tiredness not each other, share the load, stay whole — and dads are equal parents. 💞",
  },
  helpLine: "A new baby reshaping the couple is normal. If low mood or hopelessness persists, perinatal depression is real and treatable: Tele-MANAS 14416. Abuse: 181, 112.",
  helpLabel: "Get help · Tele-MANAS 14416",
  reassure: "If parenthood made things harder, that’s normal — two in three couples feel the dip, no verdict. You’re still whole. If low mood lingers, call Tele-MANAS 14416.",
  reassureCats: ["the-big-shift", "you-still-matter"],
};
