// Content for What Makes Me, Me (node g07, ages 6–9, Chapter 2) — reworked to GDD 07 v2 (mechanic-embodying).
// "Who I am is mine." The BASE of the gender thread (UNESCO 3.1): 82 researched, India-grounded scenarios
// across six categories, each re-encoded to one of the shared v2 play actions (reflect / role-play /
// strike-rewrite / branch / sort / match / build) — no binary "tap the right card", led by the me-collage
// BUILD ("the one and only you", many parts → one me) + the gentle sex-vs-gender explainer (the body you're
// born with vs who you know you are inside). Many-ways-to-be is anchored in INDIA's own hijra heritage and
// the Supreme Court's NALSA (2014) third-gender recognition — homegrown, not imported. Respect is the floor
// for EVERY family (use the name given, don't tease, include everyone); self-knowledge, never pressure
// ("only you know yourself", "you never have to prove or change") — protecting the gender-diverse child AND
// the majority child. Scope-disciplined: body anatomy stays light here (it lives in g02/g06); this node owns
// the IDEA, not the biology — no medical / romantic / political content. Rendered by the shared engine
// (components/games/v2-engine.tsx). gameId "what-makes-me" (the GDD's "what-makes-me-me" is design-doc only). DO NOT RENAME.

import type { Scenario, V2GameConfig } from "./v2-schema";

const SCENARIOS: Scenario[] = [
  // — All my parts —
  {"id":"wm-001","cat":"parts-of-me","type":"build","hook":"Lensy: let's build the one and only YOU. What goes in?","prompt":"Drag the parts that make you, you, into your collage.","pieces":["my name","what I love","my feelings","my family","my body","who I am inside"],"mode":"assemble","key":["my name","what I love","my feelings","my family","my body","who I am inside"],"relearn":"Lots of things together make you, you, and your gender is one part among many.","persona":"any","source":"self-concept"},
  {"id":"wm-002","cat":"parts-of-me","type":"reflect","hook":"Lensy: which part of you feels most 'you' today?","prompt":"Point to one (or say your own).","options":["What I love doing","My family","How I make people laugh","Who I am inside"],"affirm":"All of those are part of the one-of-a-kind you. Lovely.","relearn":"You're made of many parts, and you get to notice them.","persona":"any","source":"self-concept"},
  {"id":"wm-003","cat":"parts-of-me","type":"match","hook":"Match each part of you to where it lives.","pairs":[{"left":"My name","right":"What people call me"},{"left":"My feelings","right":"Inside my heart"},{"left":"Who I am","right":"Something only I know best"}],"relearn":"Different parts of you live in different places, and all are yours.","persona":"any","source":"self-concept"},
  {"id":"wm-004","cat":"parts-of-me","type":"reflect","hook":"Lensy: is there anyone exactly like you in the world?","prompt":"What do you think?","options":["No, I'm one of a kind","Nobody's just like me","I'm unique"],"affirm":"Nobody else is exactly you, that's pretty amazing.","relearn":"You are one of a kind; nobody else is just like you.","persona":"any","source":"uniqueness"},
  {"id":"wm-005","cat":"parts-of-me","type":"build","hook":"Add 'who I am inside' to your collage.","prompt":"Place it among your other parts (one of many).","pieces":["I'm a boy / a girl / me","plus all my other parts"],"mode":"assemble","key":["I'm a boy / a girl / me","plus all my other parts"],"relearn":"Who you are (your gender) is one important part of you, among many.","persona":"gender thread","source":"identity facets"},
  {"id":"wm-006","cat":"parts-of-me","type":"sort","hook":"Sort: a part of who I am, or not really?","items":[{"id":"a","text":"My feelings"},{"id":"b","text":"My shoe brand"},{"id":"c","text":"What I love doing"},{"id":"d","text":"My family"}],"bins":[{"id":"me","label":"Part of me"},{"id":"no","label":"Not really"}],"key":{"a":"me","b":"no","c":"me","d":"me"},"relearn":"Your feelings, loves and family are real parts of you.","persona":"any","source":"self-concept"},
  {"id":"wm-007","cat":"parts-of-me","type":"reflect","hook":"Lensy: it's okay to still be figuring yourself out. Agree?","prompt":"What do you think?","options":["Yes","I'm still discovering me","That's okay"],"affirm":"You're still discovering who you are, and that's exactly right.","relearn":"You're still discovering you, and that's okay.","persona":"any","source":"identity exploration"},
  {"id":"wm-008","cat":"parts-of-me","type":"match","hook":"Match the kid to a part they're proud of.","pairs":[{"left":"Loves cricket","right":"That's part of them"},{"left":"Great at drawing","right":"That's part of them"},{"left":"Very kind","right":"That's part of them"}],"relearn":"The things you love and do are proud parts of you.","persona":"any","source":"self-concept"},
  {"id":"wm-009","cat":"parts-of-me","type":"sort","hook":"Sort the parts of you into where they live.","items":[{"id":"a","text":"My arms and legs"},{"id":"b","text":"My feelings"},{"id":"c","text":"My height"},{"id":"d","text":"Who I know I am"}],"bins":[{"id":"body","label":"My body (outside)"},{"id":"inside","label":"My inside-self"}],"key":{"a":"body","b":"inside","c":"body","d":"inside"},"relearn":"Your body and who you are inside are both part of you.","persona":"any","source":"self-concept"},
  {"id":"wm-010","cat":"parts-of-me","type":"build","hook":"Finish version one of your collage.","prompt":"Add a frame that says...","pieces":["one of a kind","made of many parts","good as I am"],"mode":"assemble","key":["one of a kind","made of many parts","good as I am"],"relearn":"All your parts together make one special, one-of-a-kind you.","persona":"any","source":"self-concept"},
  {"id":"wm-011","cat":"parts-of-me","type":"role-play","hook":"A new friend asks \"what are you like?\"","setup":"Tell them about you. Say:","yourLine":[{"text":"\"I'm ___, I love ___, and I'm me.\"","best":true},{"text":"\"I'm just like everyone.\""}],"relearn":"You can describe yourself by your many parts, in your own words.","persona":"any","source":"self-expression / voice"},
  {"id":"wm-012","cat":"parts-of-me","type":"reflect","hook":"Lensy: all your parts add up to one special you. How's that feel?","prompt":"Pick one.","options":["Good","Cool","I like being me"],"affirm":"All your parts together make one special you. Carry that.","relearn":"You're a wonderful whole, made of many parts.","persona":"any","source":"self-concept"},

  // — Body & inside-me —
  {"id":"wm-013","cat":"sex-and-gender","type":"match","hook":"Two words to learn. Match them.","pairs":[{"left":"Sex","right":"The body you're born with"},{"left":"Gender","right":"Who you know you are inside"}],"relearn":"Sex is the body you're born with; gender is who you know you are inside.","persona":"educator","source":"UNESCO 3.1"},
  {"id":"wm-014","cat":"sex-and-gender","type":"branch","hook":"One friend's body and inside-self match; another's feel different.","options":[{"text":"Say \"both of you are okay, just as you are\"","consequence":"Both friends feel accepted and safe.","outcome":"kind","best":true},{"text":"Say one of them is 'wrong'","consequence":"A friend is hurt over something that's perfectly okay.","outcome":"unkind"}],"debrief":"For most people body and inside-self match; for some they differ, and both are okay.","relearn":"For most people body and inside-self match; for some they differ, both okay.","persona":"gender thread","source":"gender development"},
  {"id":"wm-015","cat":"sex-and-gender","type":"strike-rewrite","hook":"\"Everyone always feels like the body they were born with.\"","myth":{"un":"Everyone always feels like the body they were born with.","re":"Most do; some people feel different inside, and that's real and okay.","why":"People know their own inside-selves."},"relearn":"Some people feel different inside, and that is real and okay.","persona":"gender thread","source":"gender diversity"},
  {"id":"wm-016","cat":"sex-and-gender","type":"reflect","hook":"Lensy: gender is about...?","prompt":"Pick the best.","options":["Who you know you are inside","Your true self","How you feel inside"],"affirm":"Yes, gender is who you know yourself to be inside.","relearn":"Gender is who you know you are inside.","persona":"any","source":"UNESCO 3.1"},
  {"id":"wm-017","cat":"sex-and-gender","type":"sort","hook":"When a baby is born, a doctor says 'it's a girl!' by looking. Sort what that's about.","items":[{"id":"a","text":"Looking at the body"},{"id":"b","text":"Knowing the baby's inside-self"}],"bins":[{"id":"sex","label":"About the body (sex)"},{"id":"gender","label":"About inside-self (gender)"}],"key":{"a":"sex","b":"gender"},"relearn":"That first guess is about the body (sex); gender is who you grow to know you are.","persona":"educator","source":"sex vs gender"},
  {"id":"wm-018","cat":"sex-and-gender","type":"strike-rewrite","hook":"\"You can tell someone's gender by how they look.\"","myth":{"un":"You can tell someone's gender by their hair or clothes.","re":"You can't; gender is who someone knows they are inside.","why":"Looks don't reveal an inside-self."},"relearn":"You can't know someone's gender from how they look.","persona":"any","source":"gender vs expression"},
  {"id":"wm-019","cat":"sex-and-gender","type":"reflect","hook":"Lensy: who knows your inside-self best?","prompt":"What do you think?","options":["Me","Only I do","I know myself best"],"affirm":"Only you know who you are inside. That's yours.","relearn":"Only you know who you are inside.","persona":"be-yourself","source":"self-identification"},
  {"id":"wm-020","cat":"sex-and-gender","type":"role-play","hook":"You're not sure if a new classmate is a boy or a girl.","setup":"What's the kind thing to do? Say:","yourLine":[{"text":"\"Hi! What's your name?\" (and use it)","best":true},{"text":"\"Are you a boy or a girl?\" (loudly)"}],"relearn":"Let people tell you; use the name they give you.","persona":"respect","source":"respect / voice"},
  {"id":"wm-021","cat":"sex-and-gender","type":"match","hook":"Match each kid to 'okay and normal'. (Trick: all are!)","pairs":[{"left":"Feels like the boy he was called","right":"Okay and common"},{"left":"Feels like the girl she was called","right":"Okay and common"},{"left":"Feels like a different gender","right":"Okay too"}],"relearn":"Feeling like the boy or girl you were called is common; feeling different is okay too.","persona":"gender thread","source":"gender development"},
  {"id":"wm-022","cat":"sex-and-gender","type":"strike-rewrite","hook":"\"If you feel like a different gender, something's wrong.\"","myth":{"un":"Feeling like a different gender means something's wrong.","re":"Some kids feel like a different gender, and that's okay too.","why":"It's a normal part of how people are."},"relearn":"Feeling like a different gender is okay too.","persona":"gender thread","source":"gender diversity"},
  {"id":"wm-023","cat":"sex-and-gender","type":"match","hook":"Match the word to a simple meaning.","pairs":[{"left":"Sex","right":"Body parts you're born with"},{"left":"Gender","right":"The you, you know inside"},{"left":"Respect","right":"Letting people be themselves"}],"relearn":"Knowing these words helps us understand ourselves and others.","persona":"educator","source":"body literacy"},
  {"id":"wm-024","cat":"sex-and-gender","type":"reflect","hook":"Lensy: who someone is inside is precious. Worth respecting?","prompt":"What do you think?","options":["Yes","Always","Definitely"],"affirm":"Yes, who someone is inside deserves respect.","relearn":"Who someone is inside deserves respect.","persona":"respect","source":"respect"},

  // — Not what you like —
  {"id":"wm-025","cat":"not-what-you-like","type":"strike-rewrite","hook":"A boy's favourite colour is pink.","myth":{"un":"Liking pink means a boy isn't really a boy.","re":"Liking a colour doesn't change who you are.","why":"Pink is just a colour."},"relearn":"What you like doesn't change who you are inside.","persona":"Faizan-type","source":"gender vs expression"},
  {"id":"wm-026","cat":"not-what-you-like","type":"strike-rewrite","hook":"A girl has short hair and loves football.","myth":{"un":"Short hair and football mean she isn't really a girl.","re":"What she likes doesn't change that she's a girl.","why":"Hair and hobbies aren't a gender."},"relearn":"What you like doesn't change who you are.","persona":"Ananya","source":"gender vs expression"},
  {"id":"wm-027","cat":"not-what-you-like","type":"sort","hook":"Sort: does this decide your gender, or is it just something you like?","items":[{"id":"a","text":"Liking dolls"},{"id":"b","text":"Who you know you are inside"},{"id":"c","text":"Your haircut"},{"id":"d","text":"The clothes you wear"}],"bins":[{"id":"gender","label":"Decides gender"},{"id":"like","label":"Just what you like"}],"key":{"a":"like","b":"gender","c":"like","d":"like"},"relearn":"Only who you know you are inside is your gender; the rest is just what you like.","persona":"gender thread","source":"UNESCO 3.1"},
  {"id":"wm-028","cat":"not-what-you-like","type":"branch","hook":"A boy enjoys playing with dolls and a kid says \"that makes you a girl.\"","options":[{"text":"Say \"toys don't decide who I am\"","consequence":"He keeps playing happily; the myth loses.","outcome":"assertive","best":true},{"text":"Stop playing to avoid teasing","consequence":"He gives up fun over a wrong idea.","outcome":"missed"}],"debrief":"Toys don't decide your gender; he's still a boy.","relearn":"Toys don't decide your gender.","persona":"Faizan-type","source":"gender vs expression"},
  {"id":"wm-029","cat":"not-what-you-like","type":"strike-rewrite","hook":"\"Crying makes a boy a girl.\"","myth":{"un":"Crying makes a boy a girl.","re":"Everyone cries; feelings aren't a gender.","why":"Tears are for every kid (see Feelings Friends)."},"relearn":"Feelings aren't a gender; everyone cries.","persona":"Faizan-type","source":"links g01"},
  {"id":"wm-030","cat":"not-what-you-like","type":"role-play","hook":"Someone teases a boy for dancing.","setup":"Back him up. Say:","yourLine":[{"text":"\"Dancing's great, and he's still exactly who he is.\"","best":true},{"text":"Laugh along"}],"relearn":"Dancing (or anything you love) doesn't change who you are.","persona":"Faizan-type","source":"gender vs expression / voice"},
  {"id":"wm-031","cat":"not-what-you-like","type":"strike-rewrite","hook":"\"The clothes you wear decide who you are inside.\"","myth":{"un":"Clothes decide who you are inside.","re":"Clothes are just clothes; they don't decide your inside-self.","why":"A kurta or a frock is an outfit, not an identity."},"relearn":"Clothes don't decide who you are inside.","persona":"any","source":"gender vs expression"},
  {"id":"wm-032","cat":"not-what-you-like","type":"sort","hook":"Sort: hair, a gender, or just hair?","items":[{"id":"a","text":"Long hair"},{"id":"b","text":"Short hair"},{"id":"c","text":"A bun"},{"id":"d","text":"Who you know you are"}],"bins":[{"id":"hair","label":"Just hair"},{"id":"gender","label":"Your gender"}],"key":{"a":"hair","b":"hair","c":"hair","d":"gender"},"relearn":"Long or short, hair is just hair, not a gender.","persona":"any","source":"gender vs expression"},
  {"id":"wm-033","cat":"not-what-you-like","type":"reflect","hook":"Lensy: can you like 'boy things' AND 'girl things'?","prompt":"What do you think?","options":["Yes, they're just things","Of course","Things have no gender"],"affirm":"Yes, you can like anything; they're just things, not rules.","relearn":"You can like anything; they're just things.","persona":"any","source":"gender vs expression"},
  {"id":"wm-034","cat":"not-what-you-like","type":"strike-rewrite","hook":"\"Playing a different game changes your gender.\"","myth":{"un":"Playing a different game can change your gender.","re":"Nothing you play or wear changes who you are inside.","why":"Your inside-self is steady."},"relearn":"Nothing you play or wear changes who you are inside.","persona":"any","source":"gender stability"},
  {"id":"wm-035","cat":"not-what-you-like","type":"branch","hook":"Friends say you can't like a thing because of your gender.","options":[{"text":"Say \"I can like what I like\"","consequence":"You keep what you love; others often agree.","outcome":"assertive","best":true},{"text":"Drop it to fit in","consequence":"You give up something you enjoy for a silly rule.","outcome":"missed"}],"debrief":"What you enjoy is yours; gender doesn't decide it.","relearn":"You can like what you like, whatever your gender.","persona":"Reyansh","source":"peer norms"},
  {"id":"wm-036","cat":"not-what-you-like","type":"reflect","hook":"Lensy: your gender is...?","prompt":"Finish it.","options":["who I am inside","not what I like or wear","mine to know"],"affirm":"Your gender is who you are inside, not what you like or wear.","relearn":"Gender is who you are inside, not what you like or wear.","persona":"gender thread","source":"UNESCO 3.1"},

  // — Many ways to be —
  {"id":"wm-037","cat":"many-ways","type":"strike-rewrite","hook":"\"There are only two kinds of people and everyone must fit.\"","myth":{"un":"There are only two kinds of people and everyone must fit.","re":"Boy, girl, and some feel like neither or both, all real.","why":"People are wonderfully varied."},"relearn":"Boy, girl, and some people feel like neither or both, all real.","persona":"gender thread","source":"gender diversity"},
  {"id":"wm-038","cat":"many-ways","type":"reflect","hook":"Lensy: in India, people beyond just 'boy' and 'girl' have been part of life for a very long time. Did you know?","prompt":"What do you think?","options":["I do now!","That's interesting","Cool, our own history"],"affirm":"Yes, India has known people beyond boy and girl for a very long time.","relearn":"India has known people beyond boy and girl for a very long time.","persona":"India","source":"hijra history"},
  {"id":"wm-039","cat":"many-ways","type":"strike-rewrite","hook":"\"India's law only recognises male and female.\"","myth":{"un":"India only recognises male and female.","re":"India's law recognises a third gender, not only male and female.","why":"The Supreme Court recognised it (NALSA, 2014)."},"relearn":"India's law recognises a third gender.","persona":"India","source":"NALSA 2014"},
  {"id":"wm-040","cat":"many-ways","type":"match","hook":"Match each way of being to 'real and okay'. (Trick: all are!)","pairs":[{"left":"A boy","right":"Real and okay"},{"left":"A girl","right":"Real and okay"},{"left":"Someone who feels like neither/both","right":"Real and okay"}],"relearn":"Being a boy, a girl, or something else, all okay.","persona":"gender thread","source":"gender diversity"},
  {"id":"wm-041","cat":"many-ways","type":"role-play","hook":"Someone uses 'they' for themselves.","setup":"Use it kindly. Say:","yourLine":[{"text":"\"Okay! I'll use 'they' for you.\"","best":true},{"text":"\"That's too weird.\""}],"relearn":"Some people use 'they'; using it for them is kind and easy.","persona":"respect","source":"respect / voice"},
  {"id":"wm-042","cat":"many-ways","type":"strike-rewrite","hook":"\"There's only one right way to be a boy.\"","myth":{"un":"There's only one right way to be a boy.","re":"There are many ways to be a boy, quiet, loud, sporty, arty.","why":"Boys are as varied as all people."},"relearn":"There are many ways to be a boy.","persona":"Faizan-type","source":"gender norms"},
  {"id":"wm-043","cat":"many-ways","type":"strike-rewrite","hook":"\"There's only one right way to be a girl.\"","myth":{"un":"There's only one right way to be a girl.","re":"There are many ways to be a girl, bold, gentle, sporty, bookish.","why":"Girls are as varied as all people."},"relearn":"There are many ways to be a girl.","persona":"Ananya","source":"gender norms"},
  {"id":"wm-044","cat":"many-ways","type":"reflect","hook":"Lensy: a child who feels like a different gender than their body, real and okay?","prompt":"What do you think?","options":["Yes","Real and okay","They're just being themselves"],"affirm":"Yes, a child who feels like a different gender is real and okay.","relearn":"A child who feels like a different gender is real and okay.","persona":"gender thread","source":"gender diversity"},
  {"id":"wm-045","cat":"many-ways","type":"sort","hook":"Sort: true about people, or a too-tight box?","items":[{"id":"a","text":"People are wonderfully varied"},{"id":"b","text":"Everyone fits two neat boxes"},{"id":"c","text":"There are many ways to be"},{"id":"d","text":"Everyone must be the same"}],"bins":[{"id":"true","label":"True"},{"id":"box","label":"Too-tight box"}],"key":{"a":"true","b":"box","c":"true","d":"box"},"relearn":"People don't fit neat boxes; we're wonderfully varied.","persona":"gender thread","source":"gender diversity"},
  {"id":"wm-046","cat":"many-ways","type":"reflect","hook":"Lensy: meeting someone different from you, what's that like?","prompt":"What do you think?","options":["Interesting","I learn something","Good"],"affirm":"Meeting people different from you makes the world interesting.","relearn":"Meeting different people makes the world interesting.","persona":"any","source":"diversity"},
  {"id":"wm-047","cat":"many-ways","type":"strike-rewrite","hook":"\"Some people are 'made wrong'.\"","myth":{"un":"Some people are 'made wrong' for being who they are.","re":"No one is made wrong for being who they are.","why":"Every person deserves dignity."},"relearn":"No one is 'made wrong' for being who they are.","persona":"respect","source":"dignity"},
  {"id":"wm-048","cat":"many-ways","type":"match","hook":"Match the fact to where it comes from.","pairs":[{"left":"Hijra community","right":"Long part of India's history"},{"left":"Third gender in law","right":"India's Supreme Court (NALSA)"},{"left":"Many ways to be","right":"True of people everywhere"}],"relearn":"'More than two' is part of India's own history and law.","persona":"India","source":"hijra history / NALSA"},
  {"id":"wm-049","cat":"many-ways","type":"role-play","hook":"You feel sure you're a boy/girl, and you meet someone who feels different.","setup":"Say the both-at-once line:","yourLine":[{"text":"\"I know who I am, and I respect who you are.\"","best":true},{"text":"\"You should be like me.\""}],"relearn":"You can be sure of yourself and respect others at the same time.","persona":"respect","source":"respect / voice"},
  {"id":"wm-050","cat":"many-ways","type":"sort","hook":"Sort: deserves kindness? (Trick: everyone does.)","items":[{"id":"a","text":"A boy"},{"id":"b","text":"A girl"},{"id":"c","text":"Someone who feels different"},{"id":"d","text":"Everyone"}],"bins":[{"id":"yes","label":"Deserves kindness"},{"id":"no","label":"Doesn't"}],"key":{"a":"yes","b":"yes","c":"yes","d":"yes"},"relearn":"Every way of being a person deserves kindness.","persona":"respect","source":"dignity"},
  {"id":"wm-082","cat":"many-ways","type":"reflect","hook":"Lensy looks around at the whole class of collages.","prompt":"Is every kid a different, wonderful 'me'?","options":["Yes","Every one","We're all different and good"],"affirm":"Every single kid is a different, wonderful 'me'.","relearn":"Every single kid is a different, wonderful 'me'.","persona":"any","source":"diversity"},

  // — Respect everyone —
  {"id":"wm-051","cat":"respect-me","type":"role-play","hook":"A new friend says \"my name is Aarav, I'm a boy.\"","setup":"Show respect. Say:","yourLine":[{"text":"\"Hi Aarav! Want to play?\"","best":true},{"text":"Use a different name anyway"}],"relearn":"Call people the name they give you; it shows respect.","persona":"respect","source":"respect / voice"},
  {"id":"wm-052","cat":"respect-me","type":"branch","hook":"A classmate is teased for being 'too girly'.","options":[{"text":"Say \"leave them alone, that's not kind\"","consequence":"The teasing often stops when someone steps in.","outcome":"ally","best":true},{"text":"Join in so you fit in","consequence":"They feel alone and hurt.","outcome":"bystander"}],"debrief":"Teasing someone for who they are isn't kind; you can step in.","relearn":"You can stand up when someone's teased for who they are.","persona":"Faizan-type","source":"bystander"},
  {"id":"wm-053","cat":"respect-me","type":"role-play","hook":"You accidentally call someone the wrong name.","setup":"Make it right. Say:","yourLine":[{"text":"\"Sorry! [right name]. I'll get it.\"","best":true},{"text":"Keep using the wrong one"}],"relearn":"Mistakes happen; say sorry and try again. That's kind.","persona":"respect","source":"repair / voice"},
  {"id":"wm-054","cat":"respect-me","type":"strike-rewrite","hook":"\"Using the wrong name on purpose is just a joke.\"","myth":{"un":"Using the wrong name on purpose to be mean is just a joke.","re":"Using the wrong name on purpose to hurt isn't kind.","why":"Names matter to people."},"relearn":"Using the wrong name on purpose to hurt isn't kind.","persona":"respect","source":"respect"},
  {"id":"wm-055","cat":"respect-me","type":"branch","hook":"A kid says \"you can't play, you're a girl.\"","options":[{"text":"Say \"that's not fair, anyone can play\"","consequence":"The game opens up; it's fairer and more fun.","outcome":"fair","best":true},{"text":"Let it slide","consequence":"Someone's left out for no good reason.","outcome":"unfair"}],"debrief":"Leaving someone out for their gender isn't fair.","relearn":"No one should be left out for their gender.","persona":"Ananya","source":"fairness"},
  {"id":"wm-056","cat":"respect-me","type":"role-play","hook":"A friend likes things people call 'for the other gender'.","setup":"Be a good friend. Say:","yourLine":[{"text":"\"Cool, want to play it together?\"","best":true},{"text":"\"That's weird, stop.\""}],"relearn":"What a friend likes doesn't change your friendship.","persona":"any","source":"friendship / voice"},
  {"id":"wm-057","cat":"respect-me","type":"sort","hook":"Sort: respectful, or not?","items":[{"id":"a","text":"Using the name someone gives"},{"id":"b","text":"Teasing how someone looks"},{"id":"c","text":"Including everyone"},{"id":"d","text":"Copying an unkind word"}],"bins":[{"id":"yes","label":"Respectful"},{"id":"no","label":"Not respectful"}],"key":{"a":"yes","b":"no","c":"yes","d":"no"},"relearn":"Respect is using people's names, including them, and not copying unkind words.","persona":"respect","source":"respect"},
  {"id":"wm-058","cat":"respect-me","type":"reflect","hook":"Lensy: the golden rule. How should you treat others' 'me'?","prompt":"Pick the best.","options":["The way I'd want mine treated","With kindness","With respect"],"affirm":"Treat others' who-they-are the way you'd want yours treated.","relearn":"Treat others' 'me' the way you'd want yours treated.","persona":"respect","source":"golden rule"},
  {"id":"wm-059","cat":"respect-me","type":"branch","hook":"An older person uses an unkind word for someone different.","options":[{"text":"Choose kindness; don't copy the word","consequence":"You stay kind even when others aren't.","outcome":"values","best":true},{"text":"Copy it to fit in","consequence":"An unkind word spreads through you.","outcome":"missed"}],"debrief":"You don't have to copy unkind words; you can choose kindness.","relearn":"You can choose kindness even if a grown-up doesn't.","persona":"ally seed","source":"values"},
  {"id":"wm-060","cat":"respect-me","type":"role-play","hook":"Someone different from you wants to join the game.","setup":"Welcome them. Say:","yourLine":[{"text":"\"Come join us!\"","best":true},{"text":"\"This game's not for you.\""}],"relearn":"Including everyone, whoever they are, is kind.","persona":"any","source":"inclusion / voice"},
  {"id":"wm-061","cat":"respect-me","type":"branch","hook":"You meet someone whose way of being is new to you.","options":[{"text":"Be friendly and respectful anyway","consequence":"You make a new friend and learn something.","outcome":"kind","best":true},{"text":"Treat them as 'weird'","consequence":"You miss a friend and make them feel small.","outcome":"unkind"}],"debrief":"Even if it's new to you, every person deserves respect.","relearn":"Even if it's new to you, every person deserves respect.","persona":"respect","source":"respect"},
  {"id":"wm-062","cat":"respect-me","type":"branch","hook":"You're unsure how to treat someone you've just met.","options":[{"text":"Ask kindly and listen","consequence":"You learn who they are; they feel respected.","outcome":"kind","best":true},{"text":"Guess and tease","consequence":"You could hurt someone you've just met.","outcome":"unkind"}],"debrief":"Asking kindly and listening beats guessing or teasing.","relearn":"Asking kindly and listening shows respect.","persona":"respect","source":"respect"},
  {"id":"wm-063","cat":"respect-me","type":"strike-rewrite","hook":"\"Respect means making people be like me.\"","myth":{"un":"Respect means making people be like me.","re":"Respect means letting people be themselves.","why":"We don't all have to be the same."},"relearn":"Respect means letting people be themselves.","persona":"respect","source":"respect"},
  {"id":"wm-064","cat":"respect-me","type":"role-play","hook":"A friend was just teased for who they are.","setup":"Check on them. Say:","yourLine":[{"text":"\"You okay? You're great as you are.\"","best":true},{"text":"Pretend nothing happened"}],"relearn":"A quiet 'you okay?' tells someone they're not alone.","persona":"Faizan-type","source":"support / voice"},
  {"id":"wm-065","cat":"respect-me","type":"sort","hook":"Sort: builds respect, or breaks it?","items":[{"id":"a","text":"Listening to someone"},{"id":"b","text":"Making fun of them"},{"id":"c","text":"Using their name"},{"id":"d","text":"Leaving them out"}],"bins":[{"id":"build","label":"Builds respect"},{"id":"break","label":"Breaks it"}],"key":{"a":"build","b":"break","c":"build","d":"break"},"relearn":"Listening and using names build respect; mocking and excluding break it.","persona":"respect","source":"respect"},
  {"id":"wm-066","cat":"respect-me","type":"reflect","hook":"Lensy: one kind thing you could do for someone different tomorrow?","prompt":"Plan one.","options":["Use their name","Include them","Stand up for them","Just be friendly"],"affirm":"That's a kind plan. Small respect makes a big difference.","relearn":"You can show respect in small, everyday ways.","persona":"respect","source":"prosocial"},

  // — Be yourself —
  {"id":"wm-067","cat":"be-yourself","type":"strike-rewrite","hook":"\"You must prove you're a 'real' boy or girl.\"","myth":{"un":"You must prove your gender to others.","re":"You don't have to prove who you are to anyone.","why":"You simply are who you are."},"relearn":"You never have to prove who you are.","persona":"be-yourself","source":"gender norms"},
  {"id":"wm-068","cat":"be-yourself","type":"role-play","hook":"Someone says \"act more like a boy / a girl.\"","setup":"Hold your ground, kindly. Say:","yourLine":[{"text":"\"I'm being myself, and that's okay.\"","best":true},{"text":"Change who I am to please them"}],"relearn":"You don't have to change who you are to please others.","persona":"Faizan-type","source":"gender norms / voice"},
  {"id":"wm-069","cat":"be-yourself","type":"role-play","hook":"You catch yourself wishing you were more like someone else.","setup":"Say the kinder, truer line:","yourLine":[{"text":"\"It's good to be exactly the person I am.\"","best":true},{"text":"\"I should be someone else.\""}],"relearn":"It's good to be exactly the person you are.","persona":"be-yourself","source":"self-esteem / voice"},
  {"id":"wm-070","cat":"be-yourself","type":"branch","hook":"Others push you to be louder/quieter than you are to fit in.","options":[{"text":"Stay true to yourself","consequence":"You feel right; the right friends like the real you.","outcome":"values","best":true},{"text":"Pretend to be someone else","consequence":"It's tiring, and they like a 'you' that isn't you.","outcome":"missed"}],"debrief":"You don't have to change yourself to fit in.","relearn":"Being yourself beats pretending to fit in.","persona":"Reyansh","source":"authenticity"},
  {"id":"wm-071","cat":"be-yourself","type":"reflect","hook":"Lensy: your collage is full of your parts. Proud of them?","prompt":"What do you think?","options":["Yes","Proud","All of me"],"affirm":"You can be proud of all the parts that make you, you.","relearn":"You can be proud of all the parts that make you, you.","persona":"any","source":"self-esteem"},
  {"id":"wm-072","cat":"be-yourself","type":"reflect","hook":"Lensy: who gets to decide who you are inside?","prompt":"Who?","options":["Me","I do","Only me"],"affirm":"You get to know and decide who you are inside.","relearn":"You get to know and decide who you are inside.","persona":"be-yourself","source":"self-identification"},
  {"id":"wm-073","cat":"be-yourself","type":"branch","hook":"You feel unsure about a part of yourself.","options":[{"text":"Talk to a trusted grown-up about it","consequence":"You feel less alone; they help.","outcome":"supported","best":true},{"text":"Worry about it all alone","consequence":"The worry grows in silence.","outcome":"missed"}],"debrief":"Feeling unsure is okay; a trusted grown-up can help.","relearn":"It's okay to feel unsure, and to ask a trusted grown-up.","persona":"any","source":"trusted adults"},
  {"id":"wm-074","cat":"be-yourself","type":"role-play","hook":"A friend says 'be yourself' is good advice.","setup":"Agree, and pass it on. Say:","yourLine":[{"text":"\"Yes, you be you, and I'll be me.\"","best":true},{"text":"\"No, copy everyone else.\""}],"relearn":"Being yourself is some of the best advice there is.","persona":"be-yourself","source":"self-esteem / voice"},
  {"id":"wm-075","cat":"be-yourself","type":"strike-rewrite","hook":"\"You have to be like everyone else to be okay.\"","myth":{"un":"You have to be like everyone else to be okay.","re":"You don't have to be like everyone else to be okay.","why":"Different is normal and good."},"relearn":"You don't have to be like everyone else to be okay.","persona":"any","source":"self-esteem"},
  {"id":"wm-076","cat":"be-yourself","type":"reflect","hook":"Lensy: the things that make you different, can they be strengths?","prompt":"What do you think?","options":["Yes","They make me, me","Definitely"],"affirm":"The things that make you different can be your strengths.","relearn":"Your differences can be your strengths.","persona":"any","source":"self-esteem"},
  {"id":"wm-077","cat":"be-yourself","type":"role-play","hook":"A friend feels bad for being different.","setup":"Lift them up. Say:","yourLine":[{"text":"\"You're great just as you are.\"","best":true},{"text":"\"Try to be normal.\""}],"relearn":"Reminding a friend they're great as they are is a gift.","persona":"ally seed","source":"friendship / voice"},
  {"id":"wm-078","cat":"be-yourself","type":"reflect","hook":"Lensy: you'll grow and change. Still you?","prompt":"What do you think?","options":["Yes, still me","I grow and stay me","Of course"],"affirm":"You can grow and change and still be wonderfully you.","relearn":"You can grow and change and still be you.","persona":"any","source":"identity over time"},
  {"id":"wm-079","cat":"be-yourself","type":"branch","hook":"Capstone: a kid is being teased for who they are, and you're nearby.","options":[{"text":"Stand with them and use their name kindly","consequence":"They feel seen and safe; you set the tone.","outcome":"ally","best":true},{"text":"Walk past","consequence":"They feel alone.","outcome":"bystander"}],"debrief":"Standing with someone and using their name is real respect in action.","relearn":"You can put respect into action when it counts.","persona":"Faizan-type","source":"bystander / consolidation"},
  {"id":"wm-080","cat":"be-yourself","type":"build","hook":"Finish your me-collage and read it out.","prompt":"Add your final frame.","pieces":["one of a kind","good as I am","who I am is mine"],"mode":"assemble","key":["one of a kind","good as I am","who I am is mine"],"relearn":"I am one of a kind, and good exactly as I am.","persona":"any","source":"self-esteem"},
  {"id":"wm-081","cat":"be-yourself","type":"reflect","hook":"Lensy: what's your motto from today?","prompt":"Pick one to carry.","options":["Who I am is mine","Many ways to be","Respect everyone's me","I'm good as I am"],"affirm":"Carry that. You're going to be a wonderful, respectful you.","relearn":"Who you are is yours, there are many ways to be, and everyone deserves respect.","persona":"any","source":"consolidation"},
];

export const WHAT_MAKES_ME: V2GameConfig = {
  gameId: "what-makes-me",
  title: "What Makes Me, Me",
  greet: "Let's build the one and only YOU! 🪞 So many parts make you, you — who are you, inside?",
  scenarios: SCENARIOS,
  categories: [
  { id: "parts-of-me", emoji: "🧩", label: "All my parts" },
  { id: "sex-and-gender", emoji: "🪞", label: "Body & inside-me" },
  { id: "not-what-you-like", emoji: "🎨", label: "Not what you like" },
  { id: "many-ways", emoji: "🌈", label: "Many ways to be" },
  { id: "respect-me", emoji: "🤝", label: "Respect everyone" },
  { id: "be-yourself", emoji: "⭐", label: "Be yourself" },
  ],
  badge: {
    title: "One of a Kind! 🪞",
    blurb: "You're made of many parts, who you are is yours to know, there are many ways to be — and everyone's ‘me’ deserves respect. 🪞💛",
  },
  buildLabels: { assemble: "This is me! 💛" },
};
