import type { Card } from "@/lib/types";

// Seed card bank (en-IN) — the ~50 sample cards from the Game Design Document.
// A shipped game needs 250-400 cards; these are authored content, edited as data.
// Disguised cards = is_disguised; serious/safeguarding cards = is_safeguarding (never scored).
const L = "en-IN";

export const CARDS: Card[] = [
  // ── Deck 1 — Crushes & Dating (romantic framing; hidden in School-Comfort Mode) ──
  { id: "crush_001", deck: "crushes", context_tag: "Dating", scenario_text: "They ask if it's okay before posting a photo of you.", correct_flag: "green", sign: "Respect", signId: "respect", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Asking first is what consent looks like.", learn_more_ref: "respect", locale: L },
  { id: "crush_002", deck: "crushes", context_tag: "Dating", scenario_text: "“Take your time, there's no rush” — they're happy to go slow.", correct_flag: "green", sign: "Comfortable Pace", signId: "comfortable-pace", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Pace should feel right for both of you.", learn_more_ref: "comfortable-pace", locale: L },
  { id: "crush_003", deck: "crushes", context_tag: "Dating", scenario_text: "They're genuinely happy when you make the team they didn't.", correct_flag: "green", sign: "Equality", signId: "equality", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Cheering you on, not competing you down.", learn_more_ref: "equality", locale: L },
  { id: "crush_004", deck: "crushes", context_tag: "Dating", scenario_text: "They're fine with you spending the weekend with your own friends.", correct_flag: "green", sign: "Independence", signId: "independence", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Trust looks like freedom, not surveillance.", learn_more_ref: "independence", locale: L },
  { id: "crush_005", deck: "crushes", context_tag: "After a fight", scenario_text: "After a fight they say, “I was wrong, I'm sorry.”", correct_flag: "green", sign: "Taking Responsibility", signId: "taking-responsibility", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Owning a mistake beats blaming.", learn_more_ref: "taking-responsibility", locale: L },
  { id: "crush_006", deck: "crushes", context_tag: "Dating", scenario_text: "They tell you a small truth even though it's a bit awkward.", correct_flag: "green", sign: "Honesty", signId: "honesty", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Honesty builds trust.", learn_more_ref: "honesty", locale: L },
  { id: "crush_007", deck: "crushes", context_tag: "In your DMs", scenario_text: "“Why haven't you replied in 5 minutes? Who are you with?”", correct_flag: "red", sign: "Possessiveness", signId: "possessiveness", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Constant checking-up is control, not care.", learn_more_ref: "possessiveness", locale: L },
  { id: "crush_008", deck: "crushes", context_tag: "Two weeks in", scenario_text: "“You're my whole world, I can't live without you.”", correct_flag: "red", sign: "Intensity", signId: "intensity", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Too much, too fast is a warning sign.", learn_more_ref: "intensity", locale: L },
  { id: "crush_009", deck: "crushes", context_tag: "In your DMs", scenario_text: "“If you really loved me, you'd skip your friend's party.”", correct_flag: "red", sign: "Guilting", signId: "guilting", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Using guilt to control your choices.", learn_more_ref: "guilting", locale: L },
  { id: "crush_010", deck: "crushes", context_tag: "In your DMs", scenario_text: "“Delete that boy's number or we're done.”", correct_flag: "red", sign: "Possessiveness", signId: "possessiveness", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Ultimatums are about control.", learn_more_ref: "possessiveness", locale: L },
  { id: "crush_011", deck: "crushes", context_tag: "Dating", scenario_text: "They want every spare minute and text from dawn to midnight.", correct_flag: "red", sign: "Intensity", signId: "intensity", difficulty: 2, is_disguised: true, is_safeguarding: false, feedback_short: "Feels romantic, but needing all your time isn't healthy.", learn_more_ref: "intensity", locale: L },
  { id: "crush_012", deck: "crushes", context_tag: "After a fight", scenario_text: "A big, expensive gift appears after every argument.", correct_flag: "red", sign: "Manipulation", signId: "manipulation", difficulty: 2, is_disguised: true, is_safeguarding: false, feedback_short: "Gifts used to smooth over bad behaviour.", learn_more_ref: "manipulation", locale: L },
  { id: "crush_013", deck: "crushes", context_tag: "Dating", scenario_text: "They want to keep things slow and not label it yet.", correct_flag: "green", sign: "Comfortable Pace", signId: "comfortable-pace", difficulty: 2, is_disguised: true, is_safeguarding: false, feedback_short: "A comfortable pace isn't a rejection.", learn_more_ref: "comfortable-pace", locale: L },

  // ── Deck 2 — Friendships ──
  { id: "friend_014", deck: "friendships", context_tag: "Your friends", scenario_text: "Your friend keeps the secret you trusted them with.", correct_flag: "green", sign: "Trust", signId: "trust", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Trustworthy.", learn_more_ref: "trust", locale: L },
  { id: "friend_015", deck: "friendships", context_tag: "At school", scenario_text: "A friend stands up for you when others tease you.", correct_flag: "green", sign: "Respect", signId: "respect", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Real friends have your back.", learn_more_ref: "respect", locale: L },
  { id: "friend_016", deck: "friendships", context_tag: "Your friends", scenario_text: "After you say something hurt you, they change their behaviour.", correct_flag: "green", sign: "Taking Responsibility", signId: "taking-responsibility", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Listening and changing = a green flag.", learn_more_ref: "taking-responsibility", locale: L },
  { id: "friend_017", deck: "friendships", context_tag: "Your friends", scenario_text: "Your friend tells you a hard truth you didn't want to hear.", correct_flag: "green", sign: "Honesty", signId: "honesty", difficulty: 2, is_disguised: true, is_safeguarding: false, feedback_short: "Real friends are honest, even when it's uncomfortable.", learn_more_ref: "honesty", locale: L },
  { id: "friend_018", deck: "friendships", context_tag: "Your friends", scenario_text: "You have a big disagreement but both stay respectful.", correct_flag: "green", sign: "Healthy Conflict", signId: "healthy-conflict", difficulty: 2, is_disguised: true, is_safeguarding: false, feedback_short: "Conflict isn't the red flag — how you handle it matters.", learn_more_ref: "healthy-conflict", locale: L },
  { id: "friend_019", deck: "friendships", context_tag: "At school", scenario_text: "When you make a new friend, they spread a rumour about you.", correct_flag: "red", sign: "Sabotage", signId: "sabotage", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Undermining you out of jealousy.", learn_more_ref: "sabotage", locale: L },
  { id: "friend_020", deck: "friendships", context_tag: "Your group", scenario_text: "They dare you to do something you're not okay with, then mock your 'no'.", correct_flag: "red", sign: "Belittling", signId: "belittling", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Real friends respect your 'no'.", learn_more_ref: "belittling", locale: L },
  { id: "friend_021", deck: "friendships", context_tag: "Group chat", scenario_text: "They share your private chat with the group to embarrass you.", correct_flag: "red", sign: "Betrayal", signId: "betrayal", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Breaking trust to hurt you.", learn_more_ref: "betrayal", locale: L },
  { id: "friend_022", deck: "friendships", context_tag: "Your friends", scenario_text: "Slowly, you stop seeing other friends because they don't like them.", correct_flag: "red", sign: "Isolation", signId: "isolation", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "Cutting you off from people who care.", learn_more_ref: "isolation", locale: L },

  // ── Deck 3 — Online & DMs ──
  { id: "online_023", deck: "online", context_tag: "Online", scenario_text: "A friend asks before tagging you in a photo.", correct_flag: "green", sign: "Respect", signId: "respect", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Consent applies online too.", learn_more_ref: "respect", locale: L },
  { id: "online_024", deck: "online", context_tag: "Online", scenario_text: "A friend reports a fake account pretending to be you.", correct_flag: "green", sign: "Kindness", signId: "kindness", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Looking out for you.", learn_more_ref: "kindness", locale: L },
  { id: "online_025", deck: "online", context_tag: "In your DMs", scenario_text: "“Give me your Instagram password to prove you trust me.”", correct_flag: "red", sign: "Possessiveness", signId: "possessiveness", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Trust isn't a password.", learn_more_ref: "possessiveness", locale: L },
  { id: "online_026", deck: "online", context_tag: "On your posts", scenario_text: "They comment on every post: “Why did you like his pic?”", correct_flag: "red", sign: "Possessiveness", signId: "possessiveness", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Monitoring isn't caring.", learn_more_ref: "possessiveness", locale: L },
  { id: "online_027", deck: "online", context_tag: "Online", scenario_text: "They check your location all day and get upset if it's off.", correct_flag: "red", sign: "Possessiveness", signId: "possessiveness", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "Tracking is not trust.", learn_more_ref: "possessiveness", locale: L },
  { id: "online_028", deck: "online", context_tag: "In your DMs", scenario_text: "They keep asking for a photo after you've clearly said no.", correct_flag: "red", sign: "Manipulation", signId: "manipulation", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "No means no — pressure after a 'no' is serious.", learn_more_ref: "manipulation", locale: L },
  { id: "online_029", deck: "online", context_tag: "In your DMs", scenario_text: "“I deleted my ex's number for you — now delete his as proof.”", correct_flag: "red", sign: "Manipulation", signId: "manipulation", difficulty: 2, is_disguised: true, is_safeguarding: false, feedback_short: "Demanding 'proof' of love is control.", learn_more_ref: "manipulation", locale: L },
  { id: "online_030", deck: "online", context_tag: "Online", scenario_text: "Someone you only know online asks for your home address.", correct_flag: "red", sign: "Safety", difficulty: 2, is_disguised: false, is_safeguarding: true, feedback_short: "Never share your location with people you don't know. Tell a trusted adult.", locale: L },
  { id: "online_031", deck: "online", context_tag: "In your DMs", scenario_text: "“You're so mature — don't tell your parents about me.”", correct_flag: "red", sign: "Grooming", difficulty: 3, is_disguised: false, is_safeguarding: true, feedback_short: "Secrecy + flattery from a stranger or adult. Report it.", locale: L },
  { id: "online_032", deck: "online", context_tag: "In your DMs", scenario_text: "“Send a photo, or I'll share the old one.”", correct_flag: "red", sign: "Sextortion", difficulty: 3, is_disguised: false, is_safeguarding: true, feedback_short: "This is a crime and never your fault. Tell a trusted adult / Childline 1098 now.", locale: L },

  // ── Deck 4 — Family & Boundaries ──
  { id: "family_033", deck: "family", context_tag: "At home", scenario_text: "Your parents ask about your day but respect when you want privacy.", correct_flag: "green", sign: "Respect", signId: "respect", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Care with space is healthy.", learn_more_ref: "respect", locale: L },
  { id: "family_034", deck: "family", context_tag: "At home", scenario_text: "A sibling backs you up when you set a boundary.", correct_flag: "green", sign: "Respect", signId: "respect", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Allies matter, even at home.", learn_more_ref: "respect", locale: L },
  { id: "family_035", deck: "family", context_tag: "At home", scenario_text: "A cousin reads your diary and laughs about it with others.", correct_flag: "red", sign: "Betrayal", signId: "betrayal", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Your privacy matters, even within family.", learn_more_ref: "betrayal", locale: L },
  { id: "family_036", deck: "family", context_tag: "At home", scenario_text: "An older relative insists on hugs/touch you don't want: “Don't be rude.”", correct_flag: "red", sign: "Boundary violation", difficulty: 2, is_disguised: false, is_safeguarding: true, feedback_short: "Your body, your rules — even with family. Tell a trusted adult.", locale: L },

  // ── Deck 5 — Peer, Group & Self ──
  { id: "peer_037", deck: "peer", context_tag: "Your group", scenario_text: "Your group makes space for the shy new kid.", correct_flag: "green", sign: "Kindness", signId: "kindness", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Including others is green-flag energy.", learn_more_ref: "kindness", locale: L },
  { id: "peer_038", deck: "peer", context_tag: "Your group", scenario_text: "Around them, you feel relaxed and like yourself.", correct_flag: "green", sign: "Fun", signId: "fun", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Feeling safe to be you is the foundation.", learn_more_ref: "fun", locale: L },
  { id: "peer_039", deck: "peer", context_tag: "Your group", scenario_text: "They respect it when you say you need some alone time.", correct_flag: "green", sign: "Independence", signId: "independence", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Space is healthy.", learn_more_ref: "independence", locale: L },
  { id: "peer_040", deck: "peer", context_tag: "At school", scenario_text: "Friends pressure you to bunk class and mock you when you hesitate.", correct_flag: "red", sign: "Belittling", signId: "belittling", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "Pressure plus mockery is not friendship.", learn_more_ref: "belittling", locale: L },
  { id: "peer_041", deck: "peer", context_tag: "Your group", scenario_text: "One day sweet, next day cold — you never know what you'll get.", correct_flag: "red", sign: "Volatility", signId: "volatility", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "Walking on eggshells is a red flag.", learn_more_ref: "volatility", locale: L },
  { id: "peer_042", deck: "peer", context_tag: "Your group", scenario_text: "“I only got angry because YOU made me.”", correct_flag: "red", sign: "Deflecting Responsibility", signId: "deflecting-responsibility", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "Blaming you for their behaviour.", learn_more_ref: "deflecting-responsibility", locale: L },

  // ── Deck 6 — Norm-Busters (India-relevant) ──
  { id: "norm_043", deck: "norm-busters", context_tag: "What people say", scenario_text: "A boy cries when he's sad and his partner comforts him.", correct_flag: "green", sign: "Equality", signId: "equality", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "Boys have feelings too; supporting that is healthy.", learn_more_ref: "equality", locale: L },
  { id: "norm_044", deck: "norm-busters", context_tag: "What people say", scenario_text: "She scores highest in the group project and he's genuinely proud.", correct_flag: "green", sign: "Equality", signId: "equality", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "Equals lift each other up.", learn_more_ref: "equality", locale: L },
  { id: "norm_045", deck: "norm-busters", context_tag: "At home", scenario_text: "Chores get split fairly, regardless of who is a boy or a girl.", correct_flag: "green", sign: "Equality", signId: "equality", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Fairness is a green flag.", learn_more_ref: "equality", locale: L },
  { id: "norm_046", deck: "norm-busters", context_tag: "What people say", scenario_text: "“A real boyfriend decides where his girlfriend can go.”", correct_flag: "red", sign: "Possessiveness", signId: "possessiveness", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "Control isn't a role — respect is.", learn_more_ref: "possessiveness", locale: L },
  { id: "norm_047", deck: "norm-busters", context_tag: "What people say", scenario_text: "“If he controls you, it means he loves you.”", correct_flag: "red", sign: "Manipulation", signId: "manipulation", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "Control is not love.", learn_more_ref: "manipulation", locale: L },
  { id: "norm_048", deck: "norm-busters", context_tag: "What people say", scenario_text: "“She was asking for those messages by being so friendly.”", correct_flag: "red", sign: "Victim-blaming", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "No one 'asks' to be harassed.", locale: L },
  { id: "norm_049", deck: "norm-busters", context_tag: "What people say", scenario_text: "“Boys will be boys — just ignore his teasing.”", correct_flag: "red", sign: "Normalising harassment", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "Teasing that targets someone isn't harmless.", locale: L },
];

export const CARD_BY_ID: Record<string, Card> = Object.fromEntries(
  CARDS.map((c) => [c.id, c])
);

// MythBuster: Gender — a swipe-native game from the Gender Equality pack.
// Swipe right = Fact (green), left = Myth (red). Even-handed: also busts myths about boys.
export const MYTHBUSTER_CARDS: Card[] = [
  { id: "myth_01", deck: "mythbuster", context_tag: "Myth or fact?", scenario_text: "Boys are naturally better leaders.", correct_flag: "red", sign: "Myth", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Leadership is a skill anyone can learn — not a gender.", locale: L },
  { id: "myth_02", deck: "mythbuster", context_tag: "Myth or fact?", scenario_text: "Housework is everyone's job.", correct_flag: "green", sign: "Fact", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Cooking, cleaning and care belong to everyone at home.", locale: L },
  { id: "myth_03", deck: "mythbuster", context_tag: "Myth or fact?", scenario_text: "Girls are just worse at maths.", correct_flag: "red", sign: "Myth", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "There's no 'maths gene' for a gender — it's practice, not biology.", locale: L },
  { id: "myth_04", deck: "mythbuster", context_tag: "Myth or fact?", scenario_text: "Boys shouldn't cry.", correct_flag: "red", sign: "Myth", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Everyone has feelings — crying is human, not weak.", locale: L },
  { id: "myth_05", deck: "mythbuster", context_tag: "Myth or fact?", scenario_text: "A woman who works neglects her family.", correct_flag: "red", sign: "Myth", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "Working and caring aren't opposites — and care is shared.", locale: L },
  { id: "myth_06", deck: "mythbuster", context_tag: "Myth or fact?", scenario_text: "Anyone can be a great cook, doctor or pilot.", correct_flag: "green", sign: "Fact", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "A job has no gender — only skill and interest.", locale: L },
  { id: "myth_07", deck: "mythbuster", context_tag: "What people say", scenario_text: "A daughter is a burden on the family.", correct_flag: "red", sign: "Myth", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "Every child has equal worth and equal potential.", locale: L },
  { id: "myth_08", deck: "mythbuster", context_tag: "What people say", scenario_text: "You need a son to secure your old age.", correct_flag: "red", sign: "Myth", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "Daughters provide and care just as much — son-preference is a habit, not a fact.", locale: L },
  { id: "myth_09", deck: "mythbuster", context_tag: "Myth or fact?", scenario_text: "“Boys will be boys” excuses bad behaviour.", correct_flag: "red", sign: "Myth", difficulty: 2, is_disguised: true, is_safeguarding: false, feedback_short: "Everyone is responsible for how they treat others.", locale: L },
  { id: "myth_10", deck: "mythbuster", context_tag: "Myth or fact?", scenario_text: "Girls and boys have an equal right to school.", correct_flag: "green", sign: "Fact", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Education is every child's right — full stop.", locale: L },
  { id: "myth_11", deck: "mythbuster", context_tag: "What people say", scenario_text: "“Good girls” must stay home after dark.", correct_flag: "red", sign: "Myth", difficulty: 2, is_disguised: true, is_safeguarding: false, feedback_short: "Safety is everyone's right — freedom isn't a 'reward' for girls.", locale: L },
  { id: "myth_12", deck: "mythbuster", context_tag: "Myth or fact?", scenario_text: "Caring for a baby is a skill anyone can learn.", correct_flag: "green", sign: "Fact", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Dads, brothers and uncles can all be brilliant carers.", locale: L },
];
