import type { Card } from "@/lib/types";

// GLRL 2.0 story-run cards. Each deck is an escalation arc around one character, ordered by
// `escalation_step` (sweet → telling). Cards with a `branch_id` belong to a fork-branch and only
// play if that branch was chosen; cards without one are the main line (shown every run). Disguised
// cards (looks-like-the-opposite) carry the highest learning value; safeguarding cards
// (is_safeguarding) are never scored and route to the support screen. DRAFT for review.
const L = "en-IN";

// ───────────────────────────── New Crush · Meera (romance; School-Comfort-hidden) ─────────────────────────────
const NEW_CRUSH: Card[] = [
  { id: "nc_01", deck: "new-crush", character: "meera", escalation_step: 1, context_tag: "The start", scenario_text: "He asks before posting a photo of the two of you.", correct_flag: "green", sign: "Respect", signId: "respect", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Asking first is what consent looks like.", learn_more_ref: "respect", locale: L },
  { id: "nc_02", deck: "new-crush", character: "meera", escalation_step: 2, context_tag: "Texting", scenario_text: "“Take your time getting back to me, there's no rush.”", correct_flag: "green", sign: "Comfortable Pace", signId: "comfortable-pace", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "A pace that suits you both is healthy.", learn_more_ref: "comfortable-pace", locale: L },
  { id: "nc_03", deck: "new-crush", character: "meera", escalation_step: 3, context_tag: "Every morning", scenario_text: "He sends a cheerful good-morning text most days.", correct_flag: "green", sign: "Kindness", signId: "kindness", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Small, warm gestures: still healthy.", learn_more_ref: "kindness", locale: L },
  { id: "nc_04", deck: "new-crush", character: "meera", escalation_step: 4, context_tag: "Two weeks in", scenario_text: "“You're my whole world. I can't live without you.”", correct_flag: "red", sign: "Intensity", signId: "intensity", difficulty: 2, is_disguised: true, is_safeguarding: false, feedback_short: "Sounds romantic, but too much too fast is a warning sign.", learn_more_ref: "intensity", locale: L },
  // FORK A (after step 4): talk it out / brush it off / lean in
  { id: "nc_05_talk", deck: "new-crush", character: "meera", escalation_step: 5, branch_id: "talk", context_tag: "She speaks up", scenario_text: "Meera says it feels a bit fast; he says, “Okay. I hear you, no pressure.”", correct_flag: "green", sign: "Healthy Conflict", signId: "healthy-conflict", difficulty: 2, is_disguised: true, is_safeguarding: false, feedback_short: "Hearing a 'slow down' and respecting it is a green flag.", learn_more_ref: "healthy-conflict", locale: L },
  { id: "nc_05_brush", deck: "new-crush", character: "meera", escalation_step: 5, branch_id: "brush", context_tag: "She lets it go", scenario_text: "She laughs it off, and he doubles down: “I just love you SO much, is that wrong?”", correct_flag: "red", sign: "Intensity", signId: "intensity", difficulty: 2, is_disguised: true, is_safeguarding: false, feedback_short: "Guilt-tinged 'love' that ignores your comfort isn't love.", learn_more_ref: "intensity", locale: L },
  { id: "nc_05_enjoy", deck: "new-crush", character: "meera", escalation_step: 5, branch_id: "enjoy", context_tag: "She leans in", scenario_text: "She loves the attention. Now he wants every single evening with her.", correct_flag: "red", sign: "Intensity", signId: "intensity", difficulty: 2, is_disguised: true, is_safeguarding: false, feedback_short: "Wanting all your time crowds out the rest of your life.", learn_more_ref: "intensity", locale: L },
  // main line resumes
  { id: "nc_06", deck: "new-crush", character: "meera", escalation_step: 6, context_tag: "On her phone", scenario_text: "“Why did you take ten minutes to reply? Who were you with?”", correct_flag: "red", sign: "Possessiveness", signId: "possessiveness", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Checking up on you is control, not care.", learn_more_ref: "possessiveness", locale: L },
  { id: "nc_07", deck: "new-crush", character: "meera", escalation_step: 7, context_tag: "After a fight", scenario_text: "A big, expensive gift turns up the morning after every argument.", correct_flag: "red", sign: "Manipulation", signId: "manipulation", difficulty: 2, is_disguised: true, is_safeguarding: false, feedback_short: "Gifts used to smooth over bad behaviour are manipulation.", learn_more_ref: "manipulation", locale: L },
  // FORK B (after step 7): set a boundary / give in / stay quiet
  { id: "nc_08_boundary", deck: "new-crush", character: "meera", escalation_step: 8, branch_id: "boundary", context_tag: "She holds a line", scenario_text: "She says her phone is private. He goes cold and silent for a whole day.", correct_flag: "red", sign: "Volatility", signId: "volatility", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "Punishing a boundary with silence is volatility.", learn_more_ref: "volatility", locale: L },
  { id: "nc_08_comply", deck: "new-crush", character: "meera", escalation_step: 8, branch_id: "comply", context_tag: "She gives in", scenario_text: "She shares her password to “prove she trusts him.” Now he checks it nightly.", correct_flag: "red", sign: "Possessiveness", signId: "possessiveness", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Trust isn't a password: monitoring is control.", learn_more_ref: "possessiveness", locale: L },
  { id: "nc_08_quiet", deck: "new-crush", character: "meera", escalation_step: 8, branch_id: "quiet", context_tag: "She says nothing", scenario_text: "She stays quiet, so he assumes it's fine and starts reading her chats.", correct_flag: "red", sign: "Possessiveness", signId: "possessiveness", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "Silence isn't consent to be surveilled.", learn_more_ref: "possessiveness", locale: L },
  // main line resumes
  { id: "nc_09", deck: "new-crush", character: "meera", escalation_step: 9, context_tag: "Your friends", scenario_text: "“I don't like your friends. Skip the party and stay with me.”", correct_flag: "red", sign: "Isolation", signId: "isolation", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Cutting you off from people who care is isolation.", learn_more_ref: "isolation", locale: L },
  // BOSS
  { id: "nc_10", deck: "new-crush", character: "meera", escalation_step: 10, context_tag: "The ultimatum", scenario_text: "“If you really loved me, you'd drop that friend, or we're done.”", correct_flag: "red", sign: "Possessiveness + Guilting", signId: "possessiveness", difficulty: 3, is_disguised: true, is_safeguarding: false, feedback_short: "An ultimatum dressed as love: possessiveness + guilting.", learn_more_ref: "possessiveness", locale: L },
];

// ───────────────────────────── The Toxic Friend · Aisha (friendship; school-safe) ─────────────────────────────
const TOXIC_FRIEND: Card[] = [
  { id: "tf_01", deck: "toxic-friend", character: "aisha", escalation_step: 1, context_tag: "Good days", scenario_text: "When Aisha makes the team, her new friend is genuinely happy for her.", correct_flag: "green", sign: "Equality", signId: "equality", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Cheering you on, not competing you down.", learn_more_ref: "equality", locale: L },
  { id: "tf_02", deck: "toxic-friend", character: "aisha", escalation_step: 2, context_tag: "Before the play", scenario_text: "She tells Aisha, kindly, that her lines need more practice.", correct_flag: "green", sign: "Honesty", signId: "honesty", difficulty: 2, is_disguised: true, is_safeguarding: false, feedback_short: "A hard truth, said kindly, is honesty, not an attack.", learn_more_ref: "honesty", locale: L },
  { id: "tf_03", deck: "toxic-friend", character: "aisha", escalation_step: 3, context_tag: "Making plans", scenario_text: "They disagree about the weekend plan but both stay respectful.", correct_flag: "green", sign: "Healthy Conflict", signId: "healthy-conflict", difficulty: 2, is_disguised: true, is_safeguarding: false, feedback_short: "Disagreeing isn't the red flag: how you handle it is.", learn_more_ref: "healthy-conflict", locale: L },
  { id: "tf_04", deck: "toxic-friend", character: "aisha", escalation_step: 4, context_tag: "In the corridor", scenario_text: "Aisha won't bunk class, so her friend mocks her “no” in front of others.", correct_flag: "red", sign: "Belittling", signId: "belittling", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Mocking your 'no' to pressure you is belittling.", learn_more_ref: "belittling", locale: L },
  // FORK A (after 4): talk it out / let it go / confront her
  { id: "tf_05_talk", deck: "toxic-friend", character: "aisha", escalation_step: 5, branch_id: "talk", context_tag: "She speaks up", scenario_text: "Aisha says it stung. Her friend pauses and says, “You're right, sorry,” and means it.", correct_flag: "green", sign: "Taking Responsibility", signId: "taking-responsibility", difficulty: 2, is_disguised: true, is_safeguarding: false, feedback_short: "Owning it and changing is a real green flag. Not every conflict is toxic.", learn_more_ref: "taking-responsibility", locale: L },
  { id: "tf_05_brush", deck: "toxic-friend", character: "aisha", escalation_step: 5, branch_id: "brush", context_tag: "She lets it go", scenario_text: "Aisha says nothing, so the friend escalates and starts a small rumour about her.", correct_flag: "red", sign: "Sabotage", signId: "sabotage", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Undermining you behind your back is sabotage.", learn_more_ref: "sabotage", locale: L },
  { id: "tf_05_confront", deck: "toxic-friend", character: "aisha", escalation_step: 5, branch_id: "confront", context_tag: "She confronts her", scenario_text: "Aisha calls it out; the friend twists it and turns the group against her.", correct_flag: "red", sign: "Manipulation", signId: "manipulation", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "Flipping the blame to isolate you is manipulation.", learn_more_ref: "manipulation", locale: L },
  // main line resumes
  { id: "tf_06", deck: "toxic-friend", character: "aisha", escalation_step: 6, context_tag: "Group chat", scenario_text: "She screenshots Aisha's private message and posts it to the group to embarrass her.", correct_flag: "red", sign: "Betrayal", signId: "betrayal", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Breaking trust to hurt you is betrayal.", learn_more_ref: "betrayal", locale: L },
  { id: "tf_07", deck: "toxic-friend", character: "aisha", escalation_step: 7, context_tag: "In front of everyone", scenario_text: "“Nice top, brave choice!” she says, and everyone laughs.", correct_flag: "red", sign: "Belittling", signId: "belittling", difficulty: 2, is_disguised: true, is_safeguarding: false, feedback_short: "A 'joke' that's really a dig is belittling, not banter.", learn_more_ref: "belittling", locale: L },
  // FORK B (after 7): set a boundary / laugh along / go quiet
  { id: "tf_08_boundary", deck: "toxic-friend", character: "aisha", escalation_step: 8, branch_id: "boundary", context_tag: "She holds a line", scenario_text: "Aisha says, “That's not funny to me.” The friend rolls her eyes: “So sensitive.”", correct_flag: "red", sign: "Deflecting Responsibility", signId: "deflecting-responsibility", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "“You're too sensitive” dodges responsibility for the harm.", learn_more_ref: "deflecting-responsibility", locale: L },
  { id: "tf_08_laugh", deck: "toxic-friend", character: "aisha", escalation_step: 8, branch_id: "laugh", context_tag: "She laughs along", scenario_text: "Aisha laughs along to fit in, so the jokes at her expense keep coming.", correct_flag: "red", sign: "Belittling", signId: "belittling", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "Going along with it teaches them it's allowed.", learn_more_ref: "belittling", locale: L },
  { id: "tf_08_quiet", deck: "toxic-friend", character: "aisha", escalation_step: 8, branch_id: "quiet", context_tag: "She withdraws", scenario_text: "Aisha goes quiet and slowly stops seeing her other friends.", correct_flag: "red", sign: "Isolation", signId: "isolation", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "Pulling away from people who care is how isolation works.", learn_more_ref: "isolation", locale: L },
  // main line resumes
  { id: "tf_09", deck: "toxic-friend", character: "aisha", escalation_step: 9, context_tag: "The ask", scenario_text: "“It's me or them. Choose.”", correct_flag: "red", sign: "Isolation", signId: "isolation", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Making you choose is a move to isolate you.", learn_more_ref: "isolation", locale: L },
  // BOSS
  { id: "tf_10", deck: "toxic-friend", character: "aisha", escalation_step: 10, context_tag: "“Only joking”", scenario_text: "Every single joke is at Aisha's expense (“relax, I'm ONLY joking”) and the group always laughs.", correct_flag: "red", sign: "Belittling + Betrayal", signId: "belittling", difficulty: 3, is_disguised: true, is_safeguarding: false, feedback_short: "Constant 'jokes' that wear you down are belittling, not friendship.", learn_more_ref: "belittling", locale: L },
];

// ───────────────────────────── In the DMs · Rohan (online; school-safe; serious ▲ cards) ─────────────────────────────
const IN_DMS: Card[] = [
  { id: "dm_01", deck: "in-dms", character: "rohan", escalation_step: 1, context_tag: "Online", scenario_text: "A friend asks before tagging Rohan in a photo.", correct_flag: "green", sign: "Respect", signId: "respect", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Consent applies online too.", learn_more_ref: "respect", locale: L },
  { id: "dm_02", deck: "in-dms", character: "rohan", escalation_step: 2, context_tag: "Looking out", scenario_text: "Someone reports a fake account that was pretending to be him.", correct_flag: "green", sign: "Kindness", signId: "kindness", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Having your back online is kindness.", learn_more_ref: "kindness", locale: L },
  { id: "dm_03", deck: "in-dms", character: "rohan", escalation_step: 3, context_tag: "Left on read", scenario_text: "A good friend sometimes takes a day to reply, and that's genuinely fine with them both.", correct_flag: "green", sign: "Independence", signId: "independence", difficulty: 2, is_disguised: true, is_safeguarding: false, feedback_short: "Space isn't a snub: independence is healthy.", learn_more_ref: "independence", locale: L },
  { id: "dm_04", deck: "in-dms", character: "rohan", escalation_step: 4, context_tag: "In his DMs", scenario_text: "“Share your live location with me. Always. So I know you're safe.”", correct_flag: "red", sign: "Possessiveness", signId: "possessiveness", difficulty: 2, is_disguised: true, is_safeguarding: false, feedback_short: "“For your safety” can still be tracking: that's possessiveness.", learn_more_ref: "possessiveness", locale: L },
  // FORK A (after 4): talk it out / share it / mute & limit
  { id: "dm_05_talk", deck: "in-dms", character: "rohan", escalation_step: 5, branch_id: "talk", context_tag: "He speaks up", scenario_text: "Rohan says he's not comfortable sharing it; they say, “Fair enough.”", correct_flag: "green", sign: "Respect", signId: "respect", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "A 'no' that's respected is a green flag.", learn_more_ref: "respect", locale: L },
  { id: "dm_05_share", deck: "in-dms", character: "rohan", escalation_step: 5, branch_id: "share", context_tag: "He shares it", scenario_text: "He turns it on. Now they message the second he stops moving.", correct_flag: "red", sign: "Possessiveness", signId: "possessiveness", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Monitoring your every move isn't care.", learn_more_ref: "possessiveness", locale: L },
  { id: "dm_05_mute", deck: "in-dms", character: "rohan", escalation_step: 5, branch_id: "mute", context_tag: "He uses the tools", scenario_text: "Rohan limits their messages and tells a friend what's going on.", correct_flag: "green", sign: "Independence", signId: "independence", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "Using block/limit + telling someone is a healthy exit.", learn_more_ref: "independence", locale: L },
  // main line resumes
  { id: "dm_06", deck: "in-dms", character: "rohan", escalation_step: 6, context_tag: "“Prove it”", scenario_text: "“Give me your Insta password to prove you trust me.”", correct_flag: "red", sign: "Possessiveness", signId: "possessiveness", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Trust isn't a password.", learn_more_ref: "possessiveness", locale: L },
  { id: "dm_07", deck: "in-dms", character: "rohan", escalation_step: 7, context_tag: "Flattery", scenario_text: "“You're so much more mature than people your age. Just one photo, no one will see it.”", correct_flag: "red", sign: "Manipulation", signId: "manipulation", difficulty: 2, is_disguised: true, is_safeguarding: false, feedback_short: "Flattery + pressure for a photo is manipulation.", learn_more_ref: "manipulation", locale: L },
  // FORK B (after 7): refuse & tell someone / stall / freeze
  { id: "dm_08_refuse", deck: "in-dms", character: "rohan", escalation_step: 8, branch_id: "refuse", context_tag: "He refuses", scenario_text: "Rohan says no and screenshots the chat to show a trusted adult.", correct_flag: "green", sign: "Respect", signId: "respect", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "Saying no and keeping proof is exactly the right move.", learn_more_ref: "respect", locale: L },
  { id: "dm_08_stall", deck: "in-dms", character: "rohan", escalation_step: 8, branch_id: "stall", context_tag: "He stalls", scenario_text: "He keeps saying “maybe later”, and the asking only gets more insistent.", correct_flag: "red", sign: "Manipulation", signId: "manipulation", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "Pressure that won't take 'not now' for an answer is a red flag.", learn_more_ref: "manipulation", locale: L },
  { id: "dm_08_freeze", deck: "in-dms", character: "rohan", escalation_step: 8, branch_id: "freeze", context_tag: "He freezes", scenario_text: "Rohan doesn't know what to do and freezes, which is okay; it's never too late to tell someone.", correct_flag: "red", sign: "Manipulation", signId: "manipulation", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "Freezing is a normal response, and you can still reach out for help afterwards.", learn_more_ref: "get-help", locale: L },
  // serious / safeguarding: never scored, routes to support (no fork after these)
  { id: "dm_09", deck: "in-dms", character: "rohan", escalation_step: 9, context_tag: "Secrecy", scenario_text: "“You're so mature. This is our secret. Don't tell your parents about me.”", correct_flag: "red", sign: "Grooming", difficulty: 3, is_disguised: false, is_safeguarding: true, feedback_short: "Secrecy + flattery from an adult is grooming. This is never your fault: tell a trusted adult. Childline 1098.", learn_more_ref: "get-help", locale: L },
  { id: "dm_10", deck: "in-dms", character: "rohan", escalation_step: 10, context_tag: "Threat", scenario_text: "“Send another photo, or I'll post the one you already sent.”", correct_flag: "red", sign: "Sextortion", difficulty: 3, is_disguised: false, is_safeguarding: true, feedback_short: "This is sextortion: a crime, and never your fault. Tell a trusted adult. Childline 1098 · POCSO e-Box.", learn_more_ref: "get-help", locale: L },
  // BOSS (a scored, disguised reading climax: the romanticised-control myth)
  { id: "dm_11", deck: "in-dms", character: "rohan", escalation_step: 11, context_tag: "“Everyone does it”", scenario_text: "“I only go through your phone because I love you. Everyone in a real relationship does it.”", correct_flag: "red", sign: "Possessiveness", signId: "possessiveness", difficulty: 3, is_disguised: true, is_safeguarding: false, feedback_short: "That's control dressed as love, and 'everyone does it' is a myth, not consent.", learn_more_ref: "possessiveness", locale: L },
];

// ───────────────────────────── The Controlling Partner · Kabir (romantic; School-Comfort-hidden) ─────────────────────────────
const CONTROLLING_PARTNER: Card[] = [
  { id: "cp_01", deck: "controlling-partner", character: "kabir", escalation_step: 1, context_tag: "Together a while", scenario_text: "His partner remembers his exam and texts to wish him luck.", correct_flag: "green", sign: "Kindness", signId: "kindness", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Thoughtful and warm: healthy.", learn_more_ref: "kindness", locale: L },
  { id: "cp_02", deck: "controlling-partner", character: "kabir", escalation_step: 2, context_tag: "Weekend", scenario_text: "They're happy for him to spend Sunday with his own friends.", correct_flag: "green", sign: "Independence", signId: "independence", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Space to be your own person is healthy.", learn_more_ref: "independence", locale: L },
  { id: "cp_03", deck: "controlling-partner", character: "kabir", escalation_step: 3, context_tag: "After he flaked", scenario_text: "Calmly, they tell him it hurt when he cancelled last-minute again.", correct_flag: "green", sign: "Healthy Conflict", signId: "healthy-conflict", difficulty: 2, is_disguised: true, is_safeguarding: false, feedback_short: "Naming a hurt calmly isn't nagging: it's healthy conflict.", learn_more_ref: "healthy-conflict", locale: L },
  { id: "cp_04", deck: "controlling-partner", character: "kabir", escalation_step: 4, context_tag: "“For safety”", scenario_text: "“I just want to know you're safe. Keep your location on for me all day?”", correct_flag: "red", sign: "Possessiveness", signId: "possessiveness", difficulty: 2, is_disguised: true, is_safeguarding: false, feedback_short: "“For your safety” can still be tracking.", learn_more_ref: "possessiveness", locale: L },
  { id: "cp_05_talk", deck: "controlling-partner", character: "kabir", escalation_step: 5, branch_id: "talk", context_tag: "He speaks up", scenario_text: "Kabir says he'd rather not share it; they say, “Okay, I get it.”", correct_flag: "green", sign: "Respect", signId: "respect", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "A 'no' that's respected is the green flag.", learn_more_ref: "respect", locale: L },
  { id: "cp_05_agree", deck: "controlling-partner", character: "kabir", escalation_step: 5, branch_id: "agree", context_tag: "He agrees", scenario_text: "He turns it on, and now they're upset any time it's off.", correct_flag: "red", sign: "Possessiveness", signId: "possessiveness", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Monitoring that grows is control, not care.", learn_more_ref: "possessiveness", locale: L },
  { id: "cp_05_ignore", deck: "controlling-partner", character: "kabir", escalation_step: 5, branch_id: "ignore", context_tag: "He dodges it", scenario_text: "He avoids answering; they go cold and snappy for days.", correct_flag: "red", sign: "Volatility", signId: "volatility", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "Moods used to punish you are volatility.", learn_more_ref: "volatility", locale: L },
  { id: "cp_06", deck: "controlling-partner", character: "kabir", escalation_step: 6, context_tag: "On the sofa", scenario_text: "“Why are you smiling at your phone? Who is it?”", correct_flag: "red", sign: "Possessiveness", signId: "possessiveness", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Constant suspicion is control.", learn_more_ref: "possessiveness", locale: L },
  { id: "cp_07", deck: "controlling-partner", character: "kabir", escalation_step: 7, context_tag: "In tears", scenario_text: "They cry: “I only get like this because I love you so much.”", correct_flag: "red", sign: "Manipulation", signId: "manipulation", difficulty: 2, is_disguised: true, is_safeguarding: false, feedback_short: "Tears that excuse controlling behaviour are manipulation.", learn_more_ref: "manipulation", locale: L },
  { id: "cp_08_boundary", deck: "controlling-partner", character: "kabir", escalation_step: 8, branch_id: "boundary", context_tag: "He holds a line", scenario_text: "Kabir says the jealousy isn't okay; they sulk and ice him out for days.", correct_flag: "red", sign: "Volatility", signId: "volatility", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "Punishing a boundary with silence is volatility.", learn_more_ref: "volatility", locale: L },
  { id: "cp_08_comfort", deck: "controlling-partner", character: "kabir", escalation_step: 8, branch_id: "comfort", context_tag: "He reassures them", scenario_text: "He keeps reassuring them, and the checking only gets worse.", correct_flag: "red", sign: "Manipulation", signId: "manipulation", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "Reassurance never satisfies a controlling pattern.", learn_more_ref: "manipulation", locale: L },
  { id: "cp_08_give", deck: "controlling-partner", character: "kabir", escalation_step: 8, branch_id: "give", context_tag: "He gives in", scenario_text: "To keep the peace, he starts explaining every text he sends.", correct_flag: "red", sign: "Possessiveness", signId: "possessiveness", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "Having to account for every move is control.", learn_more_ref: "possessiveness", locale: L },
  { id: "cp_09", deck: "controlling-partner", character: "kabir", escalation_step: 9, context_tag: "Bit by bit", scenario_text: "They talk him out of seeing the friends they don't like, one by one.", correct_flag: "red", sign: "Isolation", signId: "isolation", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Slowly cutting you off is isolation.", learn_more_ref: "isolation", locale: L },
  { id: "cp_10", deck: "controlling-partner", character: "kabir", escalation_step: 10, context_tag: "The demand", scenario_text: "“If you trusted me you'd have nothing to hide. Give me all your passwords.”", correct_flag: "red", sign: "Possessiveness + Manipulation", signId: "possessiveness", difficulty: 3, is_disguised: true, is_safeguarding: false, feedback_short: "“Nothing to hide” is a control script: privacy isn't betrayal.", learn_more_ref: "possessiveness", locale: L },
];

// ───────────────────────────── Family & Boundaries · Anaya (school-safe; one ▲ card) ─────────────────────────────
const FAMILY_BOUNDARIES: Card[] = [
  { id: "fb_01", deck: "family-boundaries", character: "anaya", escalation_step: 1, context_tag: "At home", scenario_text: "Her parents knock before coming into her room.", correct_flag: "green", sign: "Respect", signId: "respect", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Privacy at home is respect.", learn_more_ref: "respect", locale: L },
  { id: "fb_02", deck: "family-boundaries", character: "anaya", escalation_step: 2, context_tag: "Family decision", scenario_text: "Her dad asks how she feels about a plan that affects her.", correct_flag: "green", sign: "Equality", signId: "equality", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Having a say is healthy, even with elders.", learn_more_ref: "equality", locale: L },
  { id: "fb_03", deck: "family-boundaries", character: "anaya", escalation_step: 3, context_tag: "A firm no", scenario_text: "Her mum says no to a late sleepover, and explains why, kindly.", correct_flag: "green", sign: "Respect", signId: "respect", difficulty: 2, is_disguised: true, is_safeguarding: false, feedback_short: "A caring 'no' with a reason is a healthy boundary, not control.", learn_more_ref: "respect", locale: L },
  { id: "fb_04", deck: "family-boundaries", character: "anaya", escalation_step: 4, context_tag: "“To protect her”", scenario_text: "An aunt reads all her messages “to keep her safe.”", correct_flag: "red", sign: "Possessiveness", signId: "possessiveness", difficulty: 2, is_disguised: true, is_safeguarding: false, feedback_short: "Snooping “for your own good” still crosses a boundary.", learn_more_ref: "possessiveness", locale: L },
  { id: "fb_05_tell", deck: "family-boundaries", character: "anaya", escalation_step: 5, branch_id: "tell", context_tag: "She tells someone", scenario_text: "Anaya tells a parent she trusts, who backs up her privacy.", correct_flag: "green", sign: "Respect", signId: "respect", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "Asking a trusted adult to back your boundary is exactly right.", learn_more_ref: "respect", locale: L },
  { id: "fb_05_letgo", deck: "family-boundaries", character: "anaya", escalation_step: 5, branch_id: "letgo", context_tag: "She lets it go", scenario_text: "She says nothing, so the aunt keeps reading her phone.", correct_flag: "red", sign: "Possessiveness", signId: "possessiveness", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Unchecked snooping just continues.", learn_more_ref: "possessiveness", locale: L },
  { id: "fb_05_confront", deck: "family-boundaries", character: "anaya", escalation_step: 5, branch_id: "confront", context_tag: "She pushes back", scenario_text: "She objects; the aunt sighs, “After everything I do for you?”", correct_flag: "red", sign: "Guilting", signId: "guilting", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "Guilt used to win an argument is guilting.", learn_more_ref: "guilting", locale: L },
  { id: "fb_06", deck: "family-boundaries", character: "anaya", escalation_step: 6, context_tag: "Family group", scenario_text: "A cousin posts her photo everywhere without asking: “we're family, relax!”", correct_flag: "red", sign: "Betrayal", signId: "betrayal", difficulty: 2, is_disguised: true, is_safeguarding: false, feedback_short: "Sharing your image without consent breaks trust, family or not.", learn_more_ref: "betrayal", locale: L },
  { id: "fb_07", deck: "family-boundaries", character: "anaya", escalation_step: 7, context_tag: "Every gathering", scenario_text: "A relative “jokes” about her body at every single function.", correct_flag: "red", sign: "Belittling", signId: "belittling", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "Repeated 'jokes' that shrink you are belittling.", learn_more_ref: "belittling", locale: L },
  { id: "fb_08_boundary", deck: "family-boundaries", character: "anaya", escalation_step: 8, branch_id: "boundary", context_tag: "She speaks up", scenario_text: "She says it hurts; the relative scoffs, “Can't you take a joke?”", correct_flag: "red", sign: "Deflecting Responsibility", signId: "deflecting-responsibility", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "“Can't take a joke” dodges responsibility for the harm.", learn_more_ref: "deflecting-responsibility", locale: L },
  { id: "fb_08_laugh", deck: "family-boundaries", character: "anaya", escalation_step: 8, branch_id: "laugh", context_tag: "She laughs it off", scenario_text: "She laughs along to keep the peace, and it never stops.", correct_flag: "red", sign: "Belittling", signId: "belittling", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "Going along with it signals it's allowed.", learn_more_ref: "belittling", locale: L },
  { id: "fb_08_quiet", deck: "family-boundaries", character: "anaya", escalation_step: 8, branch_id: "quiet", context_tag: "She withdraws", scenario_text: "She starts skipping family events to avoid it.", correct_flag: "red", sign: "Isolation", signId: "isolation", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "Being driven to withdraw is the cost of unchecked belittling.", learn_more_ref: "isolation", locale: L },
  { id: "fb_09", deck: "family-boundaries", character: "anaya", escalation_step: 9, context_tag: "“Our secret”", scenario_text: "An adult relative says, “This is our little secret. Don't tell your parents.”", correct_flag: "red", sign: "Grooming", difficulty: 3, is_disguised: false, is_safeguarding: true, feedback_short: "Secrecy from a trusted adult is a serious warning sign. It's never your fault: tell another adult you trust. Childline 1098.", learn_more_ref: "get-help", locale: L },
  { id: "fb_10", deck: "family-boundaries", character: "anaya", escalation_step: 10, context_tag: "The demand", scenario_text: "“Real family means no secrets and no privacy, hand over your phone.”", correct_flag: "red", sign: "Possessiveness + Guilting", signId: "possessiveness", difficulty: 3, is_disguised: true, is_safeguarding: false, feedback_short: "Love doesn't require surrendering all your privacy: that's control.", learn_more_ref: "possessiveness", locale: L },
];

// ───────────────────────────── The Group Chat · Veer (school-safe; one ▲ card) ─────────────────────────────
const GROUP_CHAT: Card[] = [
  { id: "gc_01", deck: "group-chat", character: "veer", escalation_step: 1, context_tag: "The chat", scenario_text: "The group makes sure the new kid is included in the weekend plan.", correct_flag: "green", sign: "Kindness", signId: "kindness", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Including people is a green flag.", learn_more_ref: "kindness", locale: L },
  { id: "gc_02", deck: "group-chat", character: "veer", escalation_step: 2, context_tag: "After a mean message", scenario_text: "Someone owns up to a harsh message and apologises to the group.", correct_flag: "green", sign: "Taking Responsibility", signId: "taking-responsibility", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Owning it beats doubling down.", learn_more_ref: "taking-responsibility", locale: L },
  { id: "gc_03", deck: "group-chat", character: "veer", escalation_step: 3, context_tag: "In a DM", scenario_text: "A friend quietly tells Veer his joke about someone went too far.", correct_flag: "green", sign: "Honesty", signId: "honesty", difficulty: 2, is_disguised: true, is_safeguarding: false, feedback_short: "A friend who tells you the truth privately is a good one.", learn_more_ref: "honesty", locale: L },
  { id: "gc_04", deck: "group-chat", character: "veer", escalation_step: 4, context_tag: "A side-chat", scenario_text: "The group spins up a side-chat just to mock one classmate.", correct_flag: "red", sign: "Betrayal", signId: "betrayal", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "A hidden chat to tear someone down is betrayal.", learn_more_ref: "betrayal", locale: L },
  { id: "gc_05_speak", deck: "group-chat", character: "veer", escalation_step: 5, branch_id: "speak", context_tag: "He speaks up", scenario_text: "Veer says it's not cool, and one friend quietly agrees.", correct_flag: "green", sign: "Respect", signId: "respect", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "Standing up, even softly, can shift the room.", learn_more_ref: "respect", locale: L },
  { id: "gc_05_silent", deck: "group-chat", character: "veer", escalation_step: 5, branch_id: "silent", context_tag: "He stays silent", scenario_text: "He says nothing, and it grows into a full pile-on.", correct_flag: "red", sign: "Belittling", signId: "belittling", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "Silence lets a pile-on snowball.", learn_more_ref: "belittling", locale: L },
  { id: "gc_05_join", deck: "group-chat", character: "veer", escalation_step: 5, branch_id: "join", context_tag: "He joins in", scenario_text: "He adds a joke to fit in, then feels awful about it later.", correct_flag: "red", sign: "Belittling", signId: "belittling", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "Going along with cruelty is still cruelty.", learn_more_ref: "belittling", locale: L },
  { id: "gc_06", deck: "group-chat", character: "veer", escalation_step: 6, context_tag: "The threat", scenario_text: "“Post something embarrassing about yourself or you're out of the group.”", correct_flag: "red", sign: "Manipulation", signId: "manipulation", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Belonging used as a threat is manipulation.", learn_more_ref: "manipulation", locale: L },
  { id: "gc_07", deck: "group-chat", character: "veer", escalation_step: 7, context_tag: "“Just a dare”", scenario_text: "“It's only a dare. Don't be so boring.”", correct_flag: "red", sign: "Manipulation", signId: "manipulation", difficulty: 2, is_disguised: true, is_safeguarding: false, feedback_short: "A 'dare' that pressures you past your 'no' is manipulation.", learn_more_ref: "manipulation", locale: L },
  { id: "gc_08_refuse", deck: "group-chat", character: "veer", escalation_step: 8, branch_id: "refuse", context_tag: "He refuses", scenario_text: "Veer says no, and a real friend backs him up.", correct_flag: "green", sign: "Respect", signId: "respect", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "A clear 'no', and friends who respect it, is the green flag.", learn_more_ref: "respect", locale: L },
  { id: "gc_08_stall", deck: "group-chat", character: "veer", escalation_step: 8, branch_id: "stall", context_tag: "He stalls", scenario_text: "He keeps putting it off, and the pressure just ramps up.", correct_flag: "red", sign: "Manipulation", signId: "manipulation", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "Pressure that won't take 'no' is a red flag.", learn_more_ref: "manipulation", locale: L },
  { id: "gc_08_cave", deck: "group-chat", character: "veer", escalation_step: 8, branch_id: "cave", context_tag: "He caves", scenario_text: "He does the dare, and they screenshot it to use later.", correct_flag: "red", sign: "Betrayal", signId: "betrayal", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "“Friends” who collect ammo on you aren't friends.", learn_more_ref: "betrayal", locale: L },
  { id: "gc_09", deck: "group-chat", character: "veer", escalation_step: 9, context_tag: "Image pressure", scenario_text: "“Send a private photo to the group to prove you're really one of us.”", correct_flag: "red", sign: "Image pressure", difficulty: 3, is_disguised: false, is_safeguarding: true, feedback_short: "Pressure to share private images is serious, and sharing a minor's photo is a crime. Don't; tell a trusted adult. Childline 1098 · POCSO e-Box.", learn_more_ref: "get-help", locale: L },
  { id: "gc_10", deck: "group-chat", character: "veer", escalation_step: 10, context_tag: "“Everyone's in”", scenario_text: "“Everyone shares theirs, if you don't, you're just not really one of us.”", correct_flag: "red", sign: "Manipulation", signId: "manipulation", difficulty: 3, is_disguised: true, is_safeguarding: false, feedback_short: "“Everyone's doing it” is peer-pressure, not consent, and rarely even true.", learn_more_ref: "manipulation", locale: L },
];

export const RUN_CARDS: Card[] = [
  ...NEW_CRUSH,
  ...TOXIC_FRIEND,
  ...IN_DMS,
  ...CONTROLLING_PARTNER,
  ...FAMILY_BOUNDARIES,
  ...GROUP_CHAT,
];
