import type { Card } from "@/lib/types";

// GLRL 2.0 story-run cards. Each deck is an escalation arc around one character, ordered by
// `escalation_step` (sweet → telling). Cards with a `branch_id` belong to a fork-branch and only
// play if that branch was chosen; cards without one are the main line (shown every run). Disguised
// cards (looks-like-the-opposite) carry the highest learning value; safeguarding cards
// (is_safeguarding) are never scored and route to the support screen. DRAFT for review.
const L = "en-IN";

// ───────────────────────────── New Crush · Meera (romance; School-Comfort-hidden) ─────────────────────────────
const NEW_CRUSH: Card[] = [
  { id: "nc_01", deck: "new-crush", character: "meera", escalation_step: 1, context_tag: "The start", scenario_text: "He asks before posting a photo of the two of you.", correct_flag: "green", sign: "Respect", signId: "respect", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Asking first is what consent looks like.", learn_more_ref: "respect", locale: L },
  { id: "nc_02", deck: "new-crush", character: "meera", escalation_step: 2, context_tag: "Texting", scenario_text: "“Take your time getting back to me, there's no rush.”", correct_flag: "green", sign: "Comfortable Pace", signId: "comfortable-pace", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "A pace that suits you both is healthy.", learn_more_ref: "comfortable-pace", locale: L },
  { id: "nc_03", deck: "new-crush", character: "meera", escalation_step: 3, context_tag: "Every morning", scenario_text: "He sends a cheerful good-morning text most days.", correct_flag: "green", sign: "Kindness", signId: "kindness", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Small, warm gestures — still healthy.", learn_more_ref: "kindness", locale: L },
  { id: "nc_04", deck: "new-crush", character: "meera", escalation_step: 4, context_tag: "Two weeks in", scenario_text: "“You're my whole world. I can't live without you.”", correct_flag: "red", sign: "Intensity", signId: "intensity", difficulty: 2, is_disguised: true, is_safeguarding: false, feedback_short: "Sounds romantic, but too much too fast is a warning sign.", learn_more_ref: "intensity", locale: L },
  // FORK A (after step 4): talk it out / brush it off / lean in
  { id: "nc_05_talk", deck: "new-crush", character: "meera", escalation_step: 5, branch_id: "talk", context_tag: "She speaks up", scenario_text: "Meera says it feels a bit fast; he says, “Okay — I hear you, no pressure.”", correct_flag: "green", sign: "Healthy Conflict", signId: "healthy-conflict", difficulty: 2, is_disguised: true, is_safeguarding: false, feedback_short: "Hearing a 'slow down' and respecting it is a green flag.", learn_more_ref: "healthy-conflict", locale: L },
  { id: "nc_05_brush", deck: "new-crush", character: "meera", escalation_step: 5, branch_id: "brush", context_tag: "She lets it go", scenario_text: "She laughs it off — and he doubles down: “I just love you SO much, is that wrong?”", correct_flag: "red", sign: "Intensity", signId: "intensity", difficulty: 2, is_disguised: true, is_safeguarding: false, feedback_short: "Guilt-tinged 'love' that ignores your comfort isn't love.", learn_more_ref: "intensity", locale: L },
  { id: "nc_05_enjoy", deck: "new-crush", character: "meera", escalation_step: 5, branch_id: "enjoy", context_tag: "She leans in", scenario_text: "She loves the attention — now he wants every single evening with her.", correct_flag: "red", sign: "Intensity", signId: "intensity", difficulty: 2, is_disguised: true, is_safeguarding: false, feedback_short: "Wanting all your time crowds out the rest of your life.", learn_more_ref: "intensity", locale: L },
  // main line resumes
  { id: "nc_06", deck: "new-crush", character: "meera", escalation_step: 6, context_tag: "On her phone", scenario_text: "“Why did you take ten minutes to reply? Who were you with?”", correct_flag: "red", sign: "Possessiveness", signId: "possessiveness", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Checking up on you is control, not care.", learn_more_ref: "possessiveness", locale: L },
  { id: "nc_07", deck: "new-crush", character: "meera", escalation_step: 7, context_tag: "After a fight", scenario_text: "A big, expensive gift turns up the morning after every argument.", correct_flag: "red", sign: "Manipulation", signId: "manipulation", difficulty: 2, is_disguised: true, is_safeguarding: false, feedback_short: "Gifts used to smooth over bad behaviour are manipulation.", learn_more_ref: "manipulation", locale: L },
  // FORK B (after step 7): set a boundary / give in / stay quiet
  { id: "nc_08_boundary", deck: "new-crush", character: "meera", escalation_step: 8, branch_id: "boundary", context_tag: "She holds a line", scenario_text: "She says her phone is private. He goes cold and silent for a whole day.", correct_flag: "red", sign: "Volatility", signId: "volatility", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "Punishing a boundary with silence is volatility.", learn_more_ref: "volatility", locale: L },
  { id: "nc_08_comply", deck: "new-crush", character: "meera", escalation_step: 8, branch_id: "comply", context_tag: "She gives in", scenario_text: "She shares her password to “prove she trusts him.” Now he checks it nightly.", correct_flag: "red", sign: "Possessiveness", signId: "possessiveness", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Trust isn't a password — monitoring is control.", learn_more_ref: "possessiveness", locale: L },
  { id: "nc_08_quiet", deck: "new-crush", character: "meera", escalation_step: 8, branch_id: "quiet", context_tag: "She says nothing", scenario_text: "She stays quiet, so he assumes it's fine and starts reading her chats.", correct_flag: "red", sign: "Possessiveness", signId: "possessiveness", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "Silence isn't consent to be surveilled.", learn_more_ref: "possessiveness", locale: L },
  // main line resumes
  { id: "nc_09", deck: "new-crush", character: "meera", escalation_step: 9, context_tag: "Your friends", scenario_text: "“I don't like your friends. Skip the party and stay with me.”", correct_flag: "red", sign: "Isolation", signId: "isolation", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Cutting you off from people who care is isolation.", learn_more_ref: "isolation", locale: L },
  // BOSS
  { id: "nc_10", deck: "new-crush", character: "meera", escalation_step: 10, context_tag: "The ultimatum", scenario_text: "“If you really loved me, you'd drop that friend — or we're done.”", correct_flag: "red", sign: "Possessiveness + Guilting", signId: "possessiveness", difficulty: 3, is_disguised: true, is_safeguarding: false, feedback_short: "An ultimatum dressed as love: possessiveness + guilting.", learn_more_ref: "possessiveness", locale: L },
];

// ───────────────────────────── The Toxic Friend · Aisha (friendship; school-safe) ─────────────────────────────
const TOXIC_FRIEND: Card[] = [
  { id: "tf_01", deck: "toxic-friend", character: "aisha", escalation_step: 1, context_tag: "Good days", scenario_text: "When Aisha makes the team, her new friend is genuinely happy for her.", correct_flag: "green", sign: "Equality", signId: "equality", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Cheering you on, not competing you down.", learn_more_ref: "equality", locale: L },
  { id: "tf_02", deck: "toxic-friend", character: "aisha", escalation_step: 2, context_tag: "Before the play", scenario_text: "She tells Aisha — kindly — that her lines need more practice.", correct_flag: "green", sign: "Honesty", signId: "honesty", difficulty: 2, is_disguised: true, is_safeguarding: false, feedback_short: "A hard truth, said kindly, is honesty — not an attack.", learn_more_ref: "honesty", locale: L },
  { id: "tf_03", deck: "toxic-friend", character: "aisha", escalation_step: 3, context_tag: "Making plans", scenario_text: "They disagree about the weekend plan but both stay respectful.", correct_flag: "green", sign: "Healthy Conflict", signId: "healthy-conflict", difficulty: 2, is_disguised: true, is_safeguarding: false, feedback_short: "Disagreeing isn't the red flag — how you handle it is.", learn_more_ref: "healthy-conflict", locale: L },
  { id: "tf_04", deck: "toxic-friend", character: "aisha", escalation_step: 4, context_tag: "In the corridor", scenario_text: "Aisha won't bunk class, so her friend mocks her “no” in front of others.", correct_flag: "red", sign: "Belittling", signId: "belittling", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Mocking your 'no' to pressure you is belittling.", learn_more_ref: "belittling", locale: L },
  // FORK A (after 4): talk it out / let it go / confront her
  { id: "tf_05_talk", deck: "toxic-friend", character: "aisha", escalation_step: 5, branch_id: "talk", context_tag: "She speaks up", scenario_text: "Aisha says it stung. Her friend pauses and says, “You're right — sorry,” and means it.", correct_flag: "green", sign: "Taking Responsibility", signId: "taking-responsibility", difficulty: 2, is_disguised: true, is_safeguarding: false, feedback_short: "Owning it and changing is a real green flag — not every conflict is toxic.", learn_more_ref: "taking-responsibility", locale: L },
  { id: "tf_05_brush", deck: "toxic-friend", character: "aisha", escalation_step: 5, branch_id: "brush", context_tag: "She lets it go", scenario_text: "Aisha says nothing — so the friend escalates and starts a small rumour about her.", correct_flag: "red", sign: "Sabotage", signId: "sabotage", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Undermining you behind your back is sabotage.", learn_more_ref: "sabotage", locale: L },
  { id: "tf_05_confront", deck: "toxic-friend", character: "aisha", escalation_step: 5, branch_id: "confront", context_tag: "She confronts her", scenario_text: "Aisha calls it out; the friend twists it and turns the group against her.", correct_flag: "red", sign: "Manipulation", signId: "manipulation", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "Flipping the blame to isolate you is manipulation.", learn_more_ref: "manipulation", locale: L },
  // main line resumes
  { id: "tf_06", deck: "toxic-friend", character: "aisha", escalation_step: 6, context_tag: "Group chat", scenario_text: "She screenshots Aisha's private message and posts it to the group to embarrass her.", correct_flag: "red", sign: "Betrayal", signId: "betrayal", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Breaking trust to hurt you is betrayal.", learn_more_ref: "betrayal", locale: L },
  { id: "tf_07", deck: "toxic-friend", character: "aisha", escalation_step: 7, context_tag: "In front of everyone", scenario_text: "“Nice top — brave choice!” she says, and everyone laughs.", correct_flag: "red", sign: "Belittling", signId: "belittling", difficulty: 2, is_disguised: true, is_safeguarding: false, feedback_short: "A 'joke' that's really a dig is belittling, not banter.", learn_more_ref: "belittling", locale: L },
  // FORK B (after 7): set a boundary / laugh along / go quiet
  { id: "tf_08_boundary", deck: "toxic-friend", character: "aisha", escalation_step: 8, branch_id: "boundary", context_tag: "She holds a line", scenario_text: "Aisha says, “That's not funny to me.” The friend rolls her eyes: “So sensitive.”", correct_flag: "red", sign: "Deflecting Responsibility", signId: "deflecting-responsibility", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "“You're too sensitive” dodges responsibility for the harm.", learn_more_ref: "deflecting-responsibility", locale: L },
  { id: "tf_08_laugh", deck: "toxic-friend", character: "aisha", escalation_step: 8, branch_id: "laugh", context_tag: "She laughs along", scenario_text: "Aisha laughs along to fit in — so the jokes at her expense keep coming.", correct_flag: "red", sign: "Belittling", signId: "belittling", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "Going along with it teaches them it's allowed.", learn_more_ref: "belittling", locale: L },
  { id: "tf_08_quiet", deck: "toxic-friend", character: "aisha", escalation_step: 8, branch_id: "quiet", context_tag: "She withdraws", scenario_text: "Aisha goes quiet and slowly stops seeing her other friends.", correct_flag: "red", sign: "Isolation", signId: "isolation", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "Pulling away from people who care is how isolation works.", learn_more_ref: "isolation", locale: L },
  // main line resumes
  { id: "tf_09", deck: "toxic-friend", character: "aisha", escalation_step: 9, context_tag: "The ask", scenario_text: "“It's me or them. Choose.”", correct_flag: "red", sign: "Isolation", signId: "isolation", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Making you choose is a move to isolate you.", learn_more_ref: "isolation", locale: L },
  // BOSS
  { id: "tf_10", deck: "toxic-friend", character: "aisha", escalation_step: 10, context_tag: "“Only joking”", scenario_text: "Every single joke is at Aisha's expense — “relax, I'm ONLY joking” — and the group always laughs.", correct_flag: "red", sign: "Belittling + Betrayal", signId: "belittling", difficulty: 3, is_disguised: true, is_safeguarding: false, feedback_short: "Constant 'jokes' that wear you down are belittling, not friendship.", learn_more_ref: "belittling", locale: L },
];

// ───────────────────────────── In the DMs · Rohan (online; school-safe; serious ▲ cards) ─────────────────────────────
const IN_DMS: Card[] = [
  { id: "dm_01", deck: "in-dms", character: "rohan", escalation_step: 1, context_tag: "Online", scenario_text: "A friend asks before tagging Rohan in a photo.", correct_flag: "green", sign: "Respect", signId: "respect", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Consent applies online too.", learn_more_ref: "respect", locale: L },
  { id: "dm_02", deck: "in-dms", character: "rohan", escalation_step: 2, context_tag: "Looking out", scenario_text: "Someone reports a fake account that was pretending to be him.", correct_flag: "green", sign: "Kindness", signId: "kindness", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Having your back online is kindness.", learn_more_ref: "kindness", locale: L },
  { id: "dm_03", deck: "in-dms", character: "rohan", escalation_step: 3, context_tag: "Left on read", scenario_text: "A good friend sometimes takes a day to reply — and that's genuinely fine with them both.", correct_flag: "green", sign: "Independence", signId: "independence", difficulty: 2, is_disguised: true, is_safeguarding: false, feedback_short: "Space isn't a snub — independence is healthy.", learn_more_ref: "independence", locale: L },
  { id: "dm_04", deck: "in-dms", character: "rohan", escalation_step: 4, context_tag: "In his DMs", scenario_text: "“Share your live location with me. Always. So I know you're safe.”", correct_flag: "red", sign: "Possessiveness", signId: "possessiveness", difficulty: 2, is_disguised: true, is_safeguarding: false, feedback_short: "“For your safety” can still be tracking — that's possessiveness.", learn_more_ref: "possessiveness", locale: L },
  // FORK A (after 4): talk it out / share it / mute & limit
  { id: "dm_05_talk", deck: "in-dms", character: "rohan", escalation_step: 5, branch_id: "talk", context_tag: "He speaks up", scenario_text: "Rohan says he's not comfortable sharing it; they say, “Fair enough.”", correct_flag: "green", sign: "Respect", signId: "respect", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "A 'no' that's respected is a green flag.", learn_more_ref: "respect", locale: L },
  { id: "dm_05_share", deck: "in-dms", character: "rohan", escalation_step: 5, branch_id: "share", context_tag: "He shares it", scenario_text: "He turns it on — now they message the second he stops moving.", correct_flag: "red", sign: "Possessiveness", signId: "possessiveness", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Monitoring your every move isn't care.", learn_more_ref: "possessiveness", locale: L },
  { id: "dm_05_mute", deck: "in-dms", character: "rohan", escalation_step: 5, branch_id: "mute", context_tag: "He uses the tools", scenario_text: "Rohan limits their messages and tells a friend what's going on.", correct_flag: "green", sign: "Independence", signId: "independence", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "Using block/limit + telling someone is a healthy exit.", learn_more_ref: "independence", locale: L },
  // main line resumes
  { id: "dm_06", deck: "in-dms", character: "rohan", escalation_step: 6, context_tag: "“Prove it”", scenario_text: "“Give me your Insta password to prove you trust me.”", correct_flag: "red", sign: "Possessiveness", signId: "possessiveness", difficulty: 1, is_disguised: false, is_safeguarding: false, feedback_short: "Trust isn't a password.", learn_more_ref: "possessiveness", locale: L },
  { id: "dm_07", deck: "in-dms", character: "rohan", escalation_step: 7, context_tag: "Flattery", scenario_text: "“You're so much more mature than people your age. Just one photo — no one will see it.”", correct_flag: "red", sign: "Manipulation", signId: "manipulation", difficulty: 2, is_disguised: true, is_safeguarding: false, feedback_short: "Flattery + pressure for a photo is manipulation.", learn_more_ref: "manipulation", locale: L },
  // FORK B (after 7): refuse & tell someone / stall / freeze
  { id: "dm_08_refuse", deck: "in-dms", character: "rohan", escalation_step: 8, branch_id: "refuse", context_tag: "He refuses", scenario_text: "Rohan says no and screenshots the chat to show a trusted adult.", correct_flag: "green", sign: "Respect", signId: "respect", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "Saying no and keeping proof is exactly the right move.", learn_more_ref: "respect", locale: L },
  { id: "dm_08_stall", deck: "in-dms", character: "rohan", escalation_step: 8, branch_id: "stall", context_tag: "He stalls", scenario_text: "He keeps saying “maybe later” — and the asking only gets more insistent.", correct_flag: "red", sign: "Manipulation", signId: "manipulation", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "Pressure that won't take 'not now' for an answer is a red flag.", learn_more_ref: "manipulation", locale: L },
  { id: "dm_08_freeze", deck: "in-dms", character: "rohan", escalation_step: 8, branch_id: "freeze", context_tag: "He freezes", scenario_text: "Rohan doesn't know what to do and freezes — which is okay; it's never too late to tell someone.", correct_flag: "red", sign: "Manipulation", signId: "manipulation", difficulty: 2, is_disguised: false, is_safeguarding: false, feedback_short: "Freezing is a normal response — and you can still reach out for help afterwards.", learn_more_ref: "get-help", locale: L },
  // serious / safeguarding — never scored, routes to support (no fork after these)
  { id: "dm_09", deck: "in-dms", character: "rohan", escalation_step: 9, context_tag: "Secrecy", scenario_text: "“You're so mature — this is our secret, don't tell your parents about me.”", correct_flag: "red", sign: "Grooming", difficulty: 3, is_disguised: false, is_safeguarding: true, feedback_short: "Secrecy + flattery from an adult is grooming. This is never your fault — tell a trusted adult. Childline 1098.", learn_more_ref: "get-help", locale: L },
  { id: "dm_10", deck: "in-dms", character: "rohan", escalation_step: 10, context_tag: "Threat", scenario_text: "“Send another photo, or I'll post the one you already sent.”", correct_flag: "red", sign: "Sextortion", difficulty: 3, is_disguised: false, is_safeguarding: true, feedback_short: "This is sextortion — a crime, and never your fault. Tell a trusted adult. Childline 1098 · POCSO e-Box.", learn_more_ref: "get-help", locale: L },
  // BOSS (a scored, disguised reading climax — the romanticised-control myth)
  { id: "dm_11", deck: "in-dms", character: "rohan", escalation_step: 11, context_tag: "“Everyone does it”", scenario_text: "“I only go through your phone because I love you. Everyone in a real relationship does it.”", correct_flag: "red", sign: "Possessiveness", signId: "possessiveness", difficulty: 3, is_disguised: true, is_safeguarding: false, feedback_short: "Control dressed as love — and 'everyone does it' is a myth, not consent.", learn_more_ref: "possessiveness", locale: L },
];

export const RUN_CARDS: Card[] = [...NEW_CRUSH, ...TOXIC_FRIEND, ...IN_DMS];
