// AUTO-GENERATED from scripts/master-node-table.xlsx by scripts/gen-path.py — do not edit by hand.
// Edit the spreadsheet and rerun the generator. Phase 0: order + thread colour + chapter
// regions; built games are playable, the rest render disabled ('not built'). No gates yet.

export type NodeType = "lesson" | "capstone";
export type ThreadKey = "A" | "B" | "C" | "D" | "E" | "F" | "G" | "E/G" | "D/E" | "F/D" | "★";

export type GameNode = {
  order: number;
  id: string; // stable table id (g01…/c1…)
  label: string;
  type: NodeType;
  chapter: string;
  ageGate: number; // 3/6/9/12/15 — carried for later phases, NOT gated yet
  thread: ThreadKey;
  threadName: string;
  hex: string; // bubble tint (one colour per thread)
  topics: string[];
  prereq?: string; // linear predecessor — carried, NOT gated yet
  buildsOn?: string; // spiral reference — analytics/callbacks only
  note?: string;
  emoji: string;
  game?: string; // dispatch id for a built game; absent => not built (disabled)
  href?: string; // navigation target (classic view / fallback)
};

export const NODES: GameNode[] = [
  { order: 1, id: "g01", label: "Feelings Friends", type: "lesson", chapter: "Ch.1 · Ages 3–6", ageGate: 3, thread: "C", threadName: "Feelings & Life Skills", hex: "#F59E0B", topics: ["5.2", "5.3", "5.6 (emotions)"], note: "Name emotions & say 'no' — the base for everything", emoji: "😊", game: "feelings", href: "/game/feelings" },
  { order: 2, id: "g02", label: "My Body, My Rules", type: "lesson", chapter: "Ch.1 · Ages 3–6", ageGate: 3, thread: "A", threadName: "Body & Growing Up", hex: "#0EA5E9", topics: ["6.1", "4.2", "4.3", "7.2", "5.5"], prereq: "g01", note: "Your body is yours; safe vs unsafe touch", emoji: "🛡️", game: "my-body", href: "/game/my-body" },
  { order: 3, id: "g37", label: "Clean Crew", type: "lesson", chapter: "Ch.1 · Ages 3–6", ageGate: 3, thread: "A", threadName: "Body & Growing Up", hex: "#0EA5E9", topics: ["6.5", "6.1"], prereq: "g02", note: "Caring for your body: washing, brushing & healthy habits", emoji: "🫧", game: "clean-crew", href: "/game/clean-crew" },
  { order: 4, id: "g03", label: "My Family Garden", type: "lesson", chapter: "Ch.1 · Ages 3–6", ageGate: 3, thread: "D", threadName: "Relationships", hex: "#EC4899", topics: ["1.1", "1.2", "7.1"], prereq: "g37", note: "Families & friends; kinds of love", emoji: "🏡", game: "family-garden", href: "/game/family-garden" },
  { order: 5, id: "g04", label: "Same Same, Different", type: "lesson", chapter: "Ch.1 · Ages 3–6", ageGate: 3, thread: "E", threadName: "Gender & Respect", hex: "#7C3AED", topics: ["3.1", "1.3"], prereq: "g03", note: "We're equal inside; difference is wonderful", emoji: "🧒", game: "same-same", href: "/game/same-same" },
  { order: 6, id: "g05", label: "Can-Do Kids", type: "lesson", chapter: "Ch.1 · Ages 3–6", ageGate: 3, thread: "E", threadName: "Gender & Respect", hex: "#7C3AED", topics: ["3.2"], prereq: "g04", buildsOn: "g04", note: "Anyone can do anything, whatever their gender", emoji: "🦸", game: "can-do", href: "/game/can-do" },
  { order: 7, id: "c1", label: "Capstone: My First Friends", type: "capstone", chapter: "Ch.1 · Ages 3–6", ageGate: 3, thread: "★", threadName: "Capstone milestone", hex: "#EAB308", topics: [], prereq: "g05", note: "Chapter 1 graduation — the Friendship Garden blooms", emoji: "🏆", game: "capstone-1", href: "/game/capstone-1" },
  { order: 8, id: "g06", label: "Body Lab Juniors", type: "lesson", chapter: "Ch.2 · Ages 6–9", ageGate: 6, thread: "A", threadName: "Body & Growing Up", hex: "#0EA5E9", topics: ["6.1", "6.2", "6.3", "6.4", "6.5"], prereq: "c1", buildsOn: "g02", note: "How bodies work & grow", emoji: "🧪", game: "body-lab", href: "/game/body-lab" },
  { order: 9, id: "g07", label: "What Makes Me, Me", type: "lesson", chapter: "Ch.2 · Ages 6–9", ageGate: 6, thread: "E", threadName: "Gender & Respect", hex: "#7C3AED", topics: ["3.1"], prereq: "g06", buildsOn: "g04", note: "Sex vs gender — base of the gender thread", emoji: "🪞", game: "what-makes-me", href: "/game/what-makes-me" },
  { order: 10, id: "g08", label: "Safety Squad", type: "lesson", chapter: "Ch.2 · Ages 6–9", ageGate: 6, thread: "B", threadName: "Safety, Consent & Boundaries", hex: "#DC2626", topics: ["4.1", "4.2", "4.3", "3.3", "5.5"], prereq: "g07", buildsOn: "g02", note: "Touch, privacy & online safety", emoji: "🦺", game: "safety-squad", href: "/game/safety-squad" },
  { order: 11, id: "g09", label: "Friend or Frenemy?", type: "lesson", chapter: "Ch.2 · Ages 6–9", ageGate: 6, thread: "D", threadName: "Relationships", hex: "#EC4899", topics: ["1.2", "5.1", "5.3", "5.6", "7.1"], prereq: "g08", buildsOn: "g03", note: "Healthy vs unhealthy friendships", emoji: "🤝", game: "friend-frenemy", href: "/game/friend-frenemy" },
  { order: 12, id: "g41", label: "Heart Smart", type: "lesson", chapter: "Ch.2 · Ages 6–9", ageGate: 6, thread: "C", threadName: "Feelings & Life Skills", hex: "#F59E0B", topics: ["5.6", "5.3", "5.2", "1.3"], prereq: "g09", buildsOn: "g01", note: "Empathy, handling feelings & getting along", emoji: "💗", game: "heart-smart", href: "/game/heart-smart" },
  { order: 13, id: "g10", label: "Fair Play World", type: "lesson", chapter: "Ch.2 · Ages 6–9", ageGate: 6, thread: "E", threadName: "Gender & Respect", hex: "#7C3AED", topics: ["3.2", "1.1", "1.3", "1.4", "2.1", "2.2", "2.3"], prereq: "g41", buildsOn: "g07", note: "Sharing chores & opportunity fairly", emoji: "⚖️", game: "fair-play", href: "/game/fair-play" },
  { order: 14, id: "g11", label: "Not Fair, Not Funny", type: "lesson", chapter: "Ch.2 · Ages 6–9", ageGate: 6, thread: "E", threadName: "Gender & Respect", hex: "#7C3AED", topics: ["3.3"], prereq: "g10", buildsOn: "g10", note: "Gender teasing, and being an ally", emoji: "🙅", game: "not-funny", href: "/game/not-funny" },
  { order: 15, id: "g12", label: "Smart Screen Heroes", type: "lesson", chapter: "Ch.2 · Ages 6–9", ageGate: 6, thread: "G", threadName: "Values, Rights & Media", hex: "#475569", topics: ["5.2", "5.4", "8.2", "8.3"], prereq: "g11", note: "Media real-vs-pretend, choices, hygiene, caring", emoji: "📱", game: "smart-screen", href: "/game/smart-screen" },
  { order: 16, id: "c2", label: "Capstone: Fair & Safe Explorer", type: "capstone", chapter: "Ch.2 · Ages 6–9", ageGate: 6, thread: "★", threadName: "Capstone milestone", hex: "#EAB308", topics: [], prereq: "g12", note: "Chapter 2 graduation", emoji: "🏆", game: "capstone-2", href: "/game/capstone-2" },
  { order: 17, id: "g13", label: "Puberty Quest", type: "lesson", chapter: "Ch.3 · Ages 9–12", ageGate: 9, thread: "A", threadName: "Body & Growing Up", hex: "#0EA5E9", topics: ["6.3", "6.1", "6.4", "6.5", "7.2"], prereq: "c2", buildsOn: "g06", note: "Puberty — timely; builds on Body Lab", emoji: "🌱", game: "puberty-quest", href: "/game/puberty-quest" },
  { order: 18, id: "g38", label: "Mind Matters", type: "lesson", chapter: "Ch.3 · Ages 9–12", ageGate: 9, thread: "C", threadName: "Feelings & Life Skills", hex: "#F59E0B", topics: ["5.6", "5.5"], prereq: "g13", buildsOn: "g01", note: "Big feelings, stress & rejection; bouncing back & asking for help", emoji: "🧠", game: "mind-matters", href: "/game/mind-matters" },
  { order: 19, id: "g14", label: "The Amazing Journey", type: "lesson", chapter: "Ch.3 · Ages 9–12", ageGate: 9, thread: "F", threadName: "Sexual & Reproductive Health", hex: "#059669", topics: ["6.2", "8.1"], prereq: "g38", buildsOn: "g13", note: "Reproduction — after anatomy & puberty", emoji: "🧬", game: "amazing-journey", href: "/game/amazing-journey" },
  { order: 20, id: "g15", label: "Boundary Bot", type: "lesson", chapter: "Ch.3 · Ages 9–12", ageGate: 9, thread: "B", threadName: "Safety, Consent & Boundaries", hex: "#DC2626", topics: ["4.1", "4.2", "4.3", "3.3", "5.5"], prereq: "g14", buildsOn: "g08", note: "Consent, boundaries & online safety", emoji: "🤖", game: "boundary-bot", href: "/game/boundary-bot" },
  { order: 21, id: "g16", label: "Crossroads", type: "lesson", chapter: "Ch.3 · Ages 9–12", ageGate: 9, thread: "D", threadName: "Relationships", hex: "#EC4899", topics: ["1.1", "1.2", "1.4", "5.1", "5.2", "5.3", "7.1"], prereq: "g15", buildsOn: "g09", note: "Peer pressure, decisions & feelings", emoji: "🔀", game: "crossroads", href: "/game/crossroads" },
  { order: 22, id: "g17", label: "Flip the Script", type: "lesson", chapter: "Ch.3 · Ages 9–12", ageGate: 9, thread: "E", threadName: "Gender & Respect", hex: "#7C3AED", topics: ["3.1", "3.2", "1.3", "2.1", "2.2", "2.3", "5.4"], prereq: "g16", buildsOn: "g10", note: "Spot & remix gender stereotypes in media", emoji: "🎬", game: "flip-script", href: "/game/flip-script" },
  { order: 23, id: "g18", label: "Norm Storm", type: "lesson", chapter: "Ch.3 · Ages 9–12", ageGate: 9, thread: "E", threadName: "Gender & Respect", hex: "#7C3AED", topics: ["3.2", "2.3"], prereq: "g17", buildsOn: "g17", note: "Which social norms help, and which harm", emoji: "🌪️", game: "norm-storm", href: "/game/norm-storm" },
  { order: 24, id: "g19", label: "Speak Up", type: "lesson", chapter: "Ch.3 · Ages 9–12", ageGate: 9, thread: "E", threadName: "Gender & Respect", hex: "#7C3AED", topics: ["3.3", "5.5"], prereq: "g18", buildsOn: "g11", note: "Forms of gender-based harm & where to get help", emoji: "📣", game: "speak-up", href: "/game/speak-up" },
  { order: 25, id: "g20", label: "Defenders of the Body", type: "lesson", chapter: "Ch.3 · Ages 9–12", ageGate: 9, thread: "F", threadName: "Sexual & Reproductive Health", hex: "#059669", topics: ["8.2", "8.3"], prereq: "g19", buildsOn: "g12", note: "HIV & infections; reducing stigma", emoji: "🦠", game: "defenders", href: "/game/defenders" },
  { order: 26, id: "c3", label: "Capstone: Growing Up Smart", type: "capstone", chapter: "Ch.3 · Ages 9–12", ageGate: 9, thread: "★", threadName: "Capstone milestone", hex: "#EAB308", topics: [], prereq: "g20", note: "Chapter 3 graduation", emoji: "🏆", game: "capstone-3", href: "/game/capstone-3" },
  { order: 27, id: "g21", label: "Body Confident", type: "lesson", chapter: "Ch.4 · Ages 12–15", ageGate: 12, thread: "A", threadName: "Body & Growing Up", hex: "#0EA5E9", topics: ["6.1", "6.3", "6.4"], prereq: "c3", buildsOn: "g13", note: "Puberty depth & body image", emoji: "💪", game: "body-confident", href: "/game/body-confident" },
  { order: 28, id: "g39", label: "Bounce", type: "lesson", chapter: "Ch.4 · Ages 12–15", ageGate: 12, thread: "C", threadName: "Feelings & Life Skills", hex: "#F59E0B", topics: ["5.6", "5.5"], prereq: "g21", buildsOn: "g38", note: "Resilience, stress & mental health; supporting friends", emoji: "🪀", game: "bounce", href: "/game/bounce" },
  { order: 29, id: "g22", label: "Plan It", type: "lesson", chapter: "Ch.4 · Ages 12–15", ageGate: 12, thread: "F", threadName: "Sexual & Reproductive Health", hex: "#059669", topics: ["6.2", "8.1"], prereq: "g39", buildsOn: "g14", note: "Fertility, pregnancy & contraception", emoji: "🗓️", game: "plan-it", href: "/game/plan-it" },
  { order: 30, id: "g23", label: "Outbreak: Stop the Spread", type: "lesson", chapter: "Ch.4 · Ages 12–15", ageGate: 12, thread: "F", threadName: "Sexual & Reproductive Health", hex: "#059669", topics: ["8.2", "8.3"], prereq: "g22", buildsOn: "g20", note: "STIs & HIV", emoji: "🧫", game: "outbreak", href: "/game/outbreak" },
  { order: 31, id: "g24", label: "Green Light / Red Light", type: "lesson", chapter: "Ch.4 · Ages 12–15", ageGate: 12, thread: "B", threadName: "Safety, Consent & Boundaries", hex: "#DC2626", topics: ["1.2", "4.2", "5.3", "7.1", "7.2"], prereq: "g23", buildsOn: "g15", note: "Reading healthy vs unhealthy relationships (flagship)", emoji: "🚦", game: "glrl", href: "/game/glrl" },
  { order: 32, id: "g25", label: "MythBuster: Gender", type: "lesson", chapter: "Ch.4 · Ages 12–15", ageGate: 12, thread: "E", threadName: "Gender & Respect", hex: "#7C3AED", topics: ["3.1", "3.2"], prereq: "g24", buildsOn: "g18", note: "Bust the gender myths teens hear constantly", emoji: "💡", game: "mythbuster-lab", href: "/game/mythbuster-lab" },
  { order: 33, id: "g26", label: "Equalize", type: "lesson", chapter: "Ch.4 · Ages 12–15", ageGate: 12, thread: "E", threadName: "Gender & Respect", hex: "#7C3AED", topics: ["3.1", "3.2", "1.4", "2.2", "3.3", "4.1"], prereq: "g25", buildsOn: "g10", note: "Equality pays off; child marriage", emoji: "🟰", game: "equalize", href: "/game/equalize" },
  { order: 34, id: "g27", label: "Stand Up", type: "lesson", chapter: "Ch.4 · Ages 12–15", ageGate: 12, thread: "B", threadName: "Safety, Consent & Boundaries", hex: "#DC2626", topics: ["3.3", "4.1", "2.2"], prereq: "g26", buildsOn: "g19", note: "GBV: bystander action & rights", emoji: "✊", game: "stand-up", href: "/game/stand-up" },
  { order: 35, id: "g40", label: "Firewall", type: "lesson", chapter: "Ch.4 · Ages 12–15", ageGate: 12, thread: "B", threadName: "Safety, Consent & Boundaries", hex: "#DC2626", topics: ["4.3", "4.1", "5.5"], prereq: "g27", buildsOn: "g15", note: "Teen online safety: grooming, sexting, sextortion & footprint", emoji: "🧱", game: "firewall", href: "/game/firewall" },
  { order: 36, id: "g43", label: "The Rabbit Hole", type: "lesson", chapter: "Ch.4 · Ages 12–15", ageGate: 12, thread: "E/G", threadName: "Gender & Media", hex: "#475569", topics: ["3.2", "3.1", "5.4", "5.1", "1.3"], prereq: "g40", buildsOn: "g25", note: "Online misogyny & the manosphere: the funnel, the grift & positive masculinity", emoji: "🕳️", game: "rabbit-hole", href: "/game/rabbit-hole" },
  { order: 37, id: "g28", label: "Reality Check", type: "lesson", chapter: "Ch.4 · Ages 12–15", ageGate: 12, thread: "G", threadName: "Values, Rights & Media", hex: "#475569", topics: ["5.1", "5.2", "5.4", "4.3", "5.5", "2.1", "2.3"], prereq: "g43", buildsOn: "g16", note: "Decisions, media & pornography literacy, finding help", emoji: "🔍", game: "reality-check", href: "/game/reality-check" },
  { order: 38, id: "c4", label: "Capstone: Reading Relationships", type: "capstone", chapter: "Ch.4 · Ages 12–15", ageGate: 12, thread: "★", threadName: "Capstone milestone", hex: "#EAB308", topics: [], prereq: "g28", note: "Chapter 4 graduation", emoji: "🏆", game: "capstone-4", href: "/game/capstone-4" },
  { order: 39, id: "g29", label: "My Choices, My Future", type: "lesson", chapter: "Ch.5 · Ages 15–18", ageGate: 15, thread: "F", threadName: "Sexual & Reproductive Health", hex: "#059669", topics: ["8.1", "6.2", "6.1", "6.3", "5.5", "2.2"], prereq: "c4", buildsOn: "g22", note: "Contraception, family planning & services", emoji: "🧭", game: "my-choices", href: "/game/my-choices" },
  { order: 40, id: "g30", label: "Status: Know It", type: "lesson", chapter: "Ch.5 · Ages 15–18", ageGate: 15, thread: "F", threadName: "Sexual & Reproductive Health", hex: "#059669", topics: ["8.2", "8.3"], prereq: "g29", buildsOn: "g23", note: "STI/HIV testing & treatment", emoji: "🩺", game: "status-know-it", href: "/game/status-know-it" },
  { order: 41, id: "g31", label: "Mutual", type: "lesson", chapter: "Ch.5 · Ages 15–18", ageGate: 15, thread: "B", threadName: "Safety, Consent & Boundaries", hex: "#DC2626", topics: ["1.2", "4.2", "5.2", "5.3", "6.4", "7.2"], prereq: "g30", buildsOn: "g24", note: "Sexual consent, legal age & relationships", emoji: "💚", game: "mutual", href: "/game/mutual" },
  { order: 42, id: "g32", label: "Spectrum", type: "lesson", chapter: "Ch.5 · Ages 15–18", ageGate: 15, thread: "D", threadName: "Relationships", hex: "#EC4899", topics: ["7.1", "1.3", "3.1"], prereq: "g31", buildsOn: "g24", note: "Identity, orientation & respect", emoji: "🌈", game: "spectrum", href: "/game/spectrum" },
  { order: 43, id: "g33", label: "Lead the Way", type: "lesson", chapter: "Ch.5 · Ages 15–18", ageGate: 15, thread: "E", threadName: "Gender & Respect", hex: "#7C3AED", topics: ["3.2"], prereq: "g32", buildsOn: "g26", note: "Structural equality: pay gap, leadership, unpaid care", emoji: "💼", game: "lead-the-way", href: "/game/lead-the-way" },
  { order: 44, id: "g34", label: "Change Makers", type: "lesson", chapter: "Ch.5 · Ages 15–18", ageGate: 15, thread: "E", threadName: "Gender & Respect", hex: "#7C3AED", topics: ["3.2", "3.3", "4.1", "2.2", "1.4"], prereq: "g33", buildsOn: "g26", note: "Campaign vs GBV & inequality; the law", emoji: "🌍", game: "change-makers", href: "/game/change-makers" },
  { order: 45, id: "g35", label: "Justice League: Rights Edition", type: "lesson", chapter: "Ch.5 · Ages 15–18", ageGate: 15, thread: "G", threadName: "Values, Rights & Media", hex: "#475569", topics: ["3.3", "2.2", "3.2", "4.1", "1.4"], prereq: "g34", buildsOn: "g27", note: "Rights & redress pathways", emoji: "🏛️", game: "justice-league", href: "/game/justice-league" },
  { order: 46, id: "g42", label: "Life Ready", type: "lesson", chapter: "Ch.5 · Ages 15–18", ageGate: 15, thread: "C", threadName: "Feelings & Life Skills", hex: "#F59E0B", topics: ["5.2", "5.6", "5.1", "5.5"], prereq: "g35", buildsOn: "g39", note: "Adult life-skills: self-knowledge, decisions, transitions & support", emoji: "🌅", game: "life-ready", href: "/game/life-ready" },
  { order: 47, id: "g36", label: "Decoded", type: "lesson", chapter: "Ch.5 · Ages 15–18", ageGate: 15, thread: "G", threadName: "Values, Rights & Media", hex: "#475569", topics: ["5.4", "4.3", "5.1", "5.6", "2.1", "2.3", "1.1"], prereq: "g42", buildsOn: "g28", note: "Pornography & critical thinking online", emoji: "🔓", game: "decoded", href: "/game/decoded" },
  { order: 48, id: "c5", label: "Capstone: Ready for the World", type: "capstone", chapter: "Ch.5 · Ages 15–18", ageGate: 15, thread: "★", threadName: "Capstone milestone", hex: "#EAB308", topics: [], prereq: "g36", note: "Final graduation — look back at the whole world built since age 4", emoji: "🏆", game: "capstone-5", href: "/game/capstone-5" },
  { order: 49, id: "g44", label: "Consent, For Real", type: "lesson", chapter: "Ch.6 · Ages 18–22", ageGate: 18, thread: "B", threadName: "Safety, Consent & Boundaries", hex: "#DC2626", topics: ["4.2", "4.1", "5.5"], prereq: "c5", buildsOn: "g31", note: "Adult consent in practice: alcohol, an ongoing yes, assault awareness & survivor support", emoji: "🫶", game: "consent-real", href: "/game/consent-real" },
  { order: 50, id: "g45", label: "Swipe Right? — Dating & Apps", type: "lesson", chapter: "Ch.6 · Ages 18–22", ageGate: 18, thread: "D", threadName: "Relationships", hex: "#EC4899", topics: ["1.2", "4.3", "5.5"], prereq: "g44", buildsOn: "g24", note: "Modern dating & app safety: meeting safely, ghosting, catfishing, digital boundaries", emoji: "💘", game: "swipe-right", href: "/game/swipe-right" },
  { order: 51, id: "g46", label: "Real Relationships", type: "lesson", chapter: "Ch.6 · Ages 18–22", ageGate: 18, thread: "D", threadName: "Relationships", hex: "#EC4899", topics: ["1.2", "5.3", "4.1", "5.6"], prereq: "g45", buildsOn: "g31", note: "Building healthy adult relationships; recognising & leaving unhealthy ones; breakups", emoji: "💞", game: "real-relationships", href: "/game/real-relationships" },
  { order: 52, id: "g47", label: "Own Your Health", type: "lesson", chapter: "Ch.6 · Ages 18–22", ageGate: 18, thread: "F", threadName: "Sexual & Reproductive Health", hex: "#059669", topics: ["8.1", "8.2", "8.3", "7.2"], prereq: "g46", buildsOn: "g30", note: "Adult SRH ownership: contraception, routine testing, sexual wellbeing & pleasure, services", emoji: "🌡️", game: "own-your-health", href: "/game/own-your-health" },
  { order: 53, id: "g48", label: "Money & Independence", type: "lesson", chapter: "Ch.6 · Ages 18–22", ageGate: 18, thread: "C", threadName: "Feelings & Life Skills", hex: "#F59E0B", topics: ["5.2", "2.2"], prereq: "g47", buildsOn: "g42", note: "Work & money: financial literacy & independence; money in relationships", emoji: "💰" },
  { order: 54, id: "g49", label: "Mind & Belonging", type: "lesson", chapter: "Ch.6 · Ages 18–22", ageGate: 18, thread: "C", threadName: "Feelings & Life Skills", hex: "#F59E0B", topics: ["5.6", "5.5", "6.4"], prereq: "g48", buildsOn: "g39", note: "College mental health, loneliness & leaving home; body image; help-seeking", emoji: "🫂" },
  { order: 55, id: "g52", label: "Find Your Feet", type: "lesson", chapter: "Ch.6 · Ages 18–22", ageGate: 18, thread: "C", threadName: "Feelings & Life Skills", hex: "#F59E0B", topics: ["5.6", "5.2", "5.1", "5.5"], prereq: "g49", buildsOn: "g42", note: "Career & future anxiety: comparison, the pressure to have it ‘figured out’, purpose & worth beyond your CV", emoji: "👣" },
  { order: 56, id: "g50", label: "Equal & Confident", type: "lesson", chapter: "Ch.6 · Ages 18–22", ageGate: 18, thread: "E", threadName: "Gender & Respect", hex: "#7C3AED", topics: ["3.2", "3.1"], prereq: "g52", buildsOn: "g33", note: "Gender equality at college/work; allyship; confidence, voice & leadership", emoji: "🌟" },
  { order: 57, id: "g51", label: "Know Your Rights (Adult)", type: "lesson", chapter: "Ch.6 · Ages 18–22", ageGate: 18, thread: "G", threadName: "Values, Rights & Media", hex: "#475569", topics: ["2.2", "4.3", "3.3"], prereq: "g50", buildsOn: "g35", note: "Adult rights: POSH/harassment, consent law, work/tenancy/cyber rights", emoji: "📜" },
  { order: 58, id: "c6", label: "Capstone: Standing on My Own", type: "capstone", chapter: "Ch.6 · Ages 18–22", ageGate: 18, thread: "★", threadName: "Capstone milestone", hex: "#EAB308", topics: [], prereq: "g51", note: "Chapter 6 graduation — an independent young adult", emoji: "🏆" },
  { order: 59, id: "g53", label: "Choosing & Building", type: "lesson", chapter: "Ch.7 · 22 → first child", ageGate: 22, thread: "D", threadName: "Relationships", hex: "#EC4899", topics: ["1.2", "1.4", "5.3", "2.1"], prereq: "c6", buildsOn: "g46", note: "Choosing a partner & what makes a healthy long-term partnership/marriage (love & arranged); commitment & communication", emoji: "💍" },
  { order: 60, id: "g54", label: "Your Path, Your Call", type: "lesson", chapter: "Ch.7 · 22 → first child", ageGate: 22, thread: "D/E", threadName: "Relationships · Gender", hex: "#EC4899", topics: ["1.2", "3.2", "2.2", "5.2"], prereq: "g53", buildsOn: "g50", note: "The freedom not to marry or have children; resisting the ‘settle down’ / ‘still-unmarried’ pressure (esp. on women); worth beyond marital status & looks", emoji: "🛤️" },
  { order: 61, id: "g55", label: "Equal Partners", type: "lesson", chapter: "Ch.7 · 22 → first child", ageGate: 22, thread: "E", threadName: "Gender & Respect", hex: "#7C3AED", topics: ["3.2", "1.1", "5.3"], prereq: "g54", buildsOn: "g26", note: "The equal home: sharing the domestic & care load (the second shift), dual careers, equality in the relationship", emoji: "🧺" },
  { order: 62, id: "g56", label: "Respect at Home", type: "lesson", chapter: "Ch.7 · 22 → first child", ageGate: 22, thread: "B", threadName: "Safety, Consent & Boundaries", hex: "#DC2626", topics: ["4.2", "4.1", "5.5"], prereq: "g55", buildsOn: "g31", note: "Consent & mutual respect in marriage; recognising & responding to coercion/DV; where to get help", emoji: "🏠" },
  { order: 63, id: "g57", label: "The Family Map", type: "lesson", chapter: "Ch.7 · 22 → first child", ageGate: 22, thread: "D", threadName: "Relationships", hex: "#EC4899", topics: ["1.1", "2.3", "5.3"], prereq: "g56", buildsOn: "g03", note: "In-laws & extended/joint family: navigating dynamics, setting boundaries, finding your place", emoji: "🗺️" },
  { order: 64, id: "g58", label: "Money, Together", type: "lesson", chapter: "Ch.7 · 22 → first child", ageGate: 22, thread: "C", threadName: "Feelings & Life Skills", hex: "#F59E0B", topics: ["5.2", "2.2"], prereq: "g57", buildsOn: "g48", note: "Work & money: joint finances & planning; financial independence within a partnership; financial control as abuse", emoji: "💵" },
  { order: 65, id: "g59", label: "If, When & Whether", type: "lesson", chapter: "Ch.7 · 22 → first child", ageGate: 22, thread: "F", threadName: "Sexual & Reproductive Health", hex: "#059669", topics: ["8.1", "6.2", "6.3"], prereq: "g58", buildsOn: "g29", note: "Reproductive planning: whether, when & spacing children; fertility awareness; preconception health; infertility & options", emoji: "🤰" },
  { order: 66, id: "g60", label: "Many Ways to Family", type: "lesson", chapter: "Ch.7 · 22 → first child", ageGate: 22, thread: "F/D", threadName: "SRH · Relationships", hex: "#059669", topics: ["8.1", "1.1", "2.2"], prereq: "g59", buildsOn: "g32", note: "Diverse routes to family — adoption/fostering, surrogacy & IVF, single & LGBTQ+ parenthood — and the gendered barriers (e.g. single men & girl-child adoption, CARA 2022)", emoji: "👪" },
  { order: 67, id: "c7", label: "Capstone: Building Together", type: "capstone", chapter: "Ch.7 · 22 → first child", ageGate: 22, thread: "★", threadName: "Capstone milestone", hex: "#EAB308", topics: [], prereq: "g60", note: "Chapter 7 graduation — a life built together, or on your own terms", emoji: "🏆" },
  { order: 68, id: "g61", label: "Us, After Kids", type: "lesson", chapter: "Ch.8 · Parenthood (first child on)", ageGate: 25, thread: "D", threadName: "Relationships", hex: "#EC4899", topics: ["1.2", "5.3", "7.1"], prereq: "c7", buildsOn: "g53", note: "Keeping the partnership & intimacy alive with kids in the picture; co-parenting connection & communication under load", emoji: "💑" },
  { order: 69, id: "g62", label: "Equal Parents", type: "lesson", chapter: "Ch.8 · Parenthood (first child on)", ageGate: 25, thread: "E", threadName: "Gender & Respect", hex: "#7C3AED", topics: ["3.2", "1.4", "1.1"], prereq: "g61", buildsOn: "g55", note: "Co-parenting as equals — sharing the care & mental load, involved fatherhood, breaking gendered parenting", emoji: "🍼" },
  { order: 70, id: "g63", label: "Looking After You", type: "lesson", chapter: "Ch.8 · Parenthood (first child on)", ageGate: 25, thread: "C", threadName: "Feelings & Life Skills", hex: "#F59E0B", topics: ["5.6", "5.5"], prereq: "g62", buildsOn: "g49", note: "Parental wellbeing & mental health; burnout; your own needs matter; the Life-Skills Toolkit under load", emoji: "🌿" },
  { order: 71, id: "g64", label: "The Talks (Age by Age)", type: "lesson", chapter: "Ch.8 · Parenthood (first child on)", ageGate: 25, thread: "F", threadName: "Parent Layer · RSE guidance", hex: "#059669", topics: ["4.2", "6.3", "7.1", "2.1"], prereq: "g63", buildsOn: "g02", note: "PARENT LAYER — age-by-age RSE guidance mapped to your child's journey (bodies, consent, puberty, relationships, sexuality, online); many small talks; facts + your values", emoji: "💬" },
  { order: 72, id: "g65", label: "Break the Cycle", type: "lesson", chapter: "Ch.8 · Parenthood (first child on)", ageGate: 25, thread: "C", threadName: "Parent Layer · Positive Parenting", hex: "#F59E0B", topics: ["5.6", "5.3"], prereq: "g64", buildsOn: "g38", note: "Positive parenting & breaking generational trauma; discipline without fear, shame or hitting; repair; healing your own wounds (Unlearn→Relearn, for parents)", emoji: "🔄" },
  { order: 73, id: "g66", label: "Raising Gender-Diverse Kids", type: "lesson", chapter: "Ch.8 · Parenthood (first child on)", ageGate: 25, thread: "E", threadName: "Parent Layer · Positive Parenting", hex: "#7C3AED", topics: ["3.1", "1.3", "7.1"], prereq: "g65", buildsOn: "g32", note: "Affirming & protecting an LGBTQ+ or gender-nonconforming child; not forcing norms; being their safe place", emoji: "🏳️‍🌈" },
  { order: 74, id: "g67", label: "Raising Neurodiverse Kids", type: "lesson", chapter: "Ch.8 · Parenthood (first child on)", ageGate: 25, thread: "C", threadName: "Parent Layer · Positive Parenting", hex: "#F59E0B", topics: ["5.6", "1.3", "5.5"], prereq: "g66", buildsOn: "g04", note: "Understanding & supporting autism, ADHD & learning differences; accommodating, advocating, de-stigmatising", emoji: "🧩" },
  { order: 75, id: "g68", label: "Navigating Addictions", type: "lesson", chapter: "Ch.8 · Parenthood (first child on)", ageGate: 25, thread: "B", threadName: "Parent Layer · Positive Parenting", hex: "#DC2626", topics: ["5.1", "5.5", "5.6"], prereq: "g67", buildsOn: "g39", note: "Recognising & responding (without shame) to a child's substance / screen / gaming dependence; getting help early; modelling healthy habits", emoji: "🎮" },
  { order: 76, id: "g69", label: "Be the Safe Adult", type: "lesson", chapter: "Ch.8 · Parenthood (first child on)", ageGate: 25, thread: "B", threadName: "Parent Layer · Safeguarding", hex: "#DC2626", topics: ["4.1", "4.2", "4.3", "5.5"], prereq: "g68", buildsOn: "g08", note: "Safeguarding literacy: spotting abuse, POCSO basics, online dangers, and how to respond to a disclosure — the trusted adult the kids' journey assumes", emoji: "🛟" },
  { order: 77, id: "c8", label: "Capstone: Raising the Next Generation", type: "capstone", chapter: "Ch.8 · Parenthood (first child on)", ageGate: 25, thread: "★", threadName: "Capstone milestone", hex: "#EAB308", topics: [], prereq: "g69", note: "Final graduation — guiding the next generation; the loop comes full circle", emoji: "🏆" },
];

export type Chapter = { key: string; title: string; subtitle: string; ageGate: number; startOrder: number; endOrder: number };
export const CHAPTERS: Chapter[] = [
  { key: "Ch.1 · Ages 3–6", title: "Ch.1 · Ages 3–6", subtitle: "Everyone is equal & can-do", ageGate: 3, startOrder: 1, endOrder: 7 },
  { key: "Ch.2 · Ages 6–9", title: "Ch.2 · Ages 6–9", subtitle: "Fair is fair", ageGate: 6, startOrder: 8, endOrder: 16 },
  { key: "Ch.3 · Ages 9–12", title: "Ch.3 · Ages 9–12", subtitle: "Question the script", ageGate: 9, startOrder: 17, endOrder: 26 },
  { key: "Ch.4 · Ages 12–15", title: "Ch.4 · Ages 12–15", subtitle: "Equality in practice", ageGate: 12, startOrder: 27, endOrder: 38 },
  { key: "Ch.5 · Ages 15–18", title: "Ch.5 · Ages 15–18", subtitle: "Change the system", ageGate: 15, startOrder: 39, endOrder: 48 },
  { key: "Ch.6 · Ages 18–22", title: "Ch.6 · Ages 18–22", subtitle: "Standing on my own", ageGate: 18, startOrder: 49, endOrder: 58 },
  { key: "Ch.7 · 22 → first child", title: "Ch.7 · 22 → first child", subtitle: "Building a life", ageGate: 22, startOrder: 59, endOrder: 67 },
  { key: "Ch.8 · Parenthood (first child on)", title: "Ch.8 · Parenthood (first child on)", subtitle: "Raising the next generation", ageGate: 25, startOrder: 68, endOrder: 77 },
];

// ---- backward-compat shape for the classic 2D view (src/components/learning-path.tsx) ----
export type PathStatus = "active" | "locked";
export type PathNode = { id: string; title: string; emoji: string; kind: string; status: PathStatus; href?: string; tag?: "gender" };
export type PathSection = { title: string; subtitle: string; nodes: PathNode[] };
export const PATH: PathSection[] = CHAPTERS.map((ch) => ({
  title: ch.title,
  subtitle: ch.subtitle,
  nodes: NODES.filter((n) => n.chapter === ch.key).map((n) => ({
    id: n.game ?? n.id,
    title: n.label,
    emoji: n.emoji,
    kind: n.threadName,
    status: (n.game ? "active" : "locked") as PathStatus,
    href: n.href,
    tag: (n.thread === "E" || n.thread === "E/G" || n.thread === "D/E") ? ("gender" as const) : undefined,
  })),
}));
